srcpkgs/ansible-base/template
This pull request bumps the ansible-base version to 2.10.9
=> ansible-base: bump to 2.10.9

srcpkgs/strongswan/template
The test failure in void was due to tzdata being a runtime dependency
of one test indirectly, so we simply add it in makedepends.
For eap-mschapv2 to be loaded at runtime, we need to have
--enable-openssl as a configuration flag. While strongswan will build
and install eap-mschapv2 without it, it will never actually load it as a
plugin and it simply won't work.
=> strongswan: bump to 5.9.2, fix tests, fix eap-mschapv2.

srcpkgs/sip4/template
This is the last release version of sip4 and contains bugfixes.
=> sip4: update to 4.19.25

srcpkgs/gnome-builder/template
validating the appstream file with network can easily time out
=> gnome-builder: fix tests

srcpkgs/mpdscribble/template
- change build system to meson (upstream change),
- add boost-devel and libgcrypt-devel to makedepends (new deps),
- drop glib-devel from makedepends (dropped upstream),
- add changelog.
=> mpdscribble: update to 0.23,

srcpkgs/zstd/template
Since this releases enables multithreading the shared library, enable it
for the static library as well.
=> zstd: update to 1.5.0.

srcpkgs/jbigkit/template, srcpkgs/jeti-filemanager/template, srcpkgs/jnettop/template, srcpkgs/joe/template, srcpkgs/john/template
=> Omnibus lint pass for SPDX issues, most packages starting with "J"

srcpkgs/kmod/template
From the `README` file in the `wrksrc` for `kmod`:
```
License:
LGPLv2.1+ for libkmod, testsuite and helper libraries
GPLv2+ for tools/*
```
The `+` is meant to mean that one can redistribute it under a later version of the respective license (e.g. `GPLv2+ -> GPL-2.0-or-later`).
=> kmod: fix license

srcpkgs/python3-telegram/patches/remove-precompiled-libraries.patch, srcpkgs/python3-telegram/patches/use-system-tdlib.patch, srcpkgs/python3-telegram/template, srcpkgs/telegram-tg/template
=> New package: telegram-tg-0.17.0

srcpkgs/git-team/template
=> git-team: update to 1.6.0.

srcpkgs/bcc/template, srcpkgs/llvm12/files/patches/compiler-rt/compiler-rt-xray-ppc64-musl.patch, srcpkgs/llvm12/template
The code erroneously disabled sanitizer support for all musl targets.
[ci skip]
@q66 
To merge when the builders have been restarted.
=> llvm12: only disable sanitizer for arm*-musl.

srcpkgs/slack-desktop/template
=> slack-desktop: update to 4.16.0

srcpkgs/gnutls/template
Instead of pulling in all makedepends from gnutls into gnutls-devel,
just use those listed in gnutls's pkgconfig files. This can speed up
local builds and avoids potential dependencies conflicts between
unnecessary packages.
=> gnutls: trim down gnutls-devel depends.

srcpkgs/gitea/files/gitea/run, srcpkgs/gitea/patches/config.patch, srcpkgs/gitea/template
Don't know why the patch fails to apply, but the package builds.
=> gitea: update to 1.14.1

srcpkgs/glibc/template
This restores the `/usr/share/locale/*/LC_MESSAGES/libc.mo` files that went missing at some point after `glibc-locales-2.30_1`.
Before: App is localized, glibc isn't:
```
$ ls ...
ls: '...' にアクセスできません: No such file or directory
```
After:
```
$ ls ...
ls: '...' にアクセスできません: そのようなファイルやディレクトリはありません
```
=> glibc: restore localized messages

srcpkgs/pipewire/patches/6df32666b4.patch, srcpkgs/pipewire/template
- The main change here is the move of default configs to `/usr/share`. `xbps` handled this well in my case (I had all default configs, which were deleted as expected). Can anyone verify that modified configs are left?
- I have briefly tried the filter-chains (`pipewire -c filter-chain/<X>.conf` runs a pipewire client that creates these "effect nodes") and they require ladspa plugins (one is not even packaged I think) but I don't think they should be hard dependencies. Also, some are borked still (e.g. `demonic.conf` ~~currently only works with a `audio.channels = 1` workaround~~ patch imported).
<details>
<summary>File diff</summary>
```
--- /tmp/old    2021-05-20 01:30:21.627554276 +0200
+++ /tmp/new    2021-05-20 01:30:37.523553285 +0200
@@ -1,14 +1,3 @@
-/etc/pipewire/client-rt.conf …
```
=> pipewire: update to 0.3.28

srcpkgs/mesa/patches/0001-radeonsi-On-Aarch64-force-persistent-buffers-to-GTT.patch, srcpkgs/mesa/template
On Xorg applications like Firefox, this buffer increase is
not adequate; it continues to artefact. Increase the size to
1024 * 1024.
=> mesa: update aarch64 patch

srcpkgs/tor/template
Tests still fail on x86_64-musl as discussed in #29307. I applied the patches Alpine uses but this oddly enough didn't fix them either. I think we should upgrade anyway for now as 0.4.5.7 fixes security issues, see https://lists.torproject.org/pipermail/tor-announce/2021-March/000216.html
cc @daniel-eys
=> tor: update to 0.4.5.8.

common/shlibs, srcpkgs/musl/patches/epoll_cp.patch, srcpkgs/musl/patches/isascii.patch, srcpkgs/musl/patches/reallocarray.patch, srcpkgs/musl/template
It's in POSIX-future and some applications have started depending on it.
It's easier to backport into musl than fix each individual package.
Since we are adding a new interface to libc, update common/shlibs entry
as well. This should probably have been done for all musl updates.
@q66
=> musl: backport reallocarray.

common/shlibs, srcpkgs/gstreamer1/template, srcpkgs/gtkd/template, srcpkgs/ldc/template, srcpkgs/onedrive/template, srcpkgs/tilix/patches/llvm-unwind.patch, srcpkgs/tilix/template
Also move to llvm12.
@q66
It ends up underlinked, because when I try building corecollector with it I get:
```
Project version: 0.3.5
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_init_local: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_get_proc_name: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_step: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_getcontext: symbol not found
Error relocating /usr/lib/libdruntime-ldc-shared.so.96: unw_get_proc_info: symbol not found
meson.build:1:0: ERROR: Executables created by D compiler ldc2 are not runnable.
```
But running with `LD_PRELOAD=/usr/lib/libunwind.so.1` after installing `llvm-libunwind` makes meson not complain.
Alpine seems to be …
=> ldc: update to 1.26.0.

srcpkgs/YACReader/template
Also add qt5-svg-devel to makedepends.
=> YACReader: update to 9.8.0.

srcpkgs/nextcloud-client/patches/fallback-primary-screen.patch, srcpkgs/nextcloud-client/template
Also added a patch to close #30713.
The patch `fallback-primary-screen.patch` comes from upstream master,
and should be removed in the next update.
=> nextcloud-client: update to 3.2.1.

srcpkgs/bluez/INSTALL.msg, srcpkgs/bluez/files/README.voidlinux, srcpkgs/bluez/files/bluetoothd/run, srcpkgs/bluez/template
Passing options to bluetoothd can be necessary in some cases.
Also move INSTALL.msg to README.voidlinux, and note that elogind can be
enough, instead of requiring group membership.
@sgn you had asked me to adopt it, if that's still the case I can do it.
=> bluez: support configs in service, adopt.

srcpkgs/font-iosevka/template
Bring back #30830 for discussion.
I divided the font into separated packages. This way the users can decide which version to choose.
Reason to include them all:
- curly: the same with the base monospace package, but with curly style
- extra: not monospace, suitable for replacing system sans, serif fonts
=> font-iosevka: update to 7.0.0

srcpkgs/soundconverter/template
=> soundconverter: update to 4.0.1.

.github/workflows/build.yaml, common/travis/changed_templates.sh, common/travis/xlint.sh
* CI will stop whenever a step is failing.
* We always want to enforce commit message lint
* `xlint` is reporting some false positive for license with " WITH "
Let's move the lint-commits step up.
=> CI: move lint-commits up in action list

srcpkgs/xdm/template
Enable Xft support to allow using more fonts with the xlogin widget.
=> xdm: enable xft support

srcpkgs/libheif/template
=> libheif: update to 1.12.0.

xbps-src
Tests pull in dependencies that are not marked as bootstrap for some packages, so if the packages have to be built, bootstrap fails.
=> xbps-src: abort bootstrap when tests are enabled

srcpkgs/libslirp/template
=> libslirp: update to 4.5.0.

common/shlibs, srcpkgs/btrfs-progs/template
Taken over and closes #28153
Why do we disable Python bindings for `libbtrfsutil`?
I gave up half way through cherry-picking tests to disable :) Most of them fail without `mount` command from util-linux.
Welcome other for battle test.
=> btrfs-progs: update to 5.11

srcpkgs/qt6-base/patches/libatomic.patch, srcpkgs/qt6-base/template
Required for #31092 
Re-building all packages depends on qt6-base to check, now.
=> qt6-base: fix QMAKE_LIBS_LIBATOMIC for armv6 

srcpkgs/openjpeg/template
Fixes:
```console
$ ./xbps-src pkg openjpeg
…
=> openjpeg-1.5.2_2: running do_configure ...
CMake Error: Unknown argument --disable-static
CMake Error: Run 'cmake --help' for all supported options.
```
=> openjpeg: fix template

srcpkgs/nnn/template
`nnn` now uses fts for disk usage calculation.
They also introduce patching system, and I'm hesitating to include the official git status patch (all we need to do is addding 1 build flag, and `libgit2-devel` to hostmakedepends).
I can compile with `x86_64-linux-musl-gcc` on my system (x86_64-musl), using `cc` fails build. I don't know how to do this nicely in the template.
=> nnn: update to 4.1

srcpkgs/kdeconnect/template
Fixes #31302
I did it for you, @Cnoob41. Is this ok?
=> kdeconnect: add qt5-quickcontrols to depends

srcpkgs/chroot-git/template, srcpkgs/git/template
=> git: not use autotools (prepare for 2.32)

srcpkgs/timewarrior/template
=> timewarrior: update to 1.4.3.

srcpkgs/go/template
Minor version update, literally works in-place exactly as you'd expect.
=> go: update to 1.16.5

srcpkgs/python3-certifi/template
=> python3-certifi: update to 2021.05.30.

srcpkgs/obs/template
=> obs: update to 27.0.0.

srcpkgs/nyxt/template
* Remove unneeded dependencies
- curl
- pkg-config
- sqlite (bookmarks stored as s-exps now)
- openssl-devel
* Add runtime dependency libfixposix-devel
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
{1000FB0103}>:
Error opening shared object "libfixposix.so":
libfixposix.so: cannot open shared object file: No such file or directory.
* Add enchant2 dependency for spell checking
Signed-off-by: Alexander Egorenkov <egorenar-dev@posteo.net>
=> nyxt: fix dependencies

srcpkgs/p11-kit/patches/we-know-glib-prefix.patch, srcpkgs/p11-kit/template
Breake this circular:
```
elfutils > libmicrohttpd
^               v
p11-kit < glib < gnutls
```
=> p11-kit: remove glib-devel from makedepends

srcpkgs/ghc-bin/template
voidlinux.de has been shut down, so the distfiles can no longer be
accessed. Someone looking to re-add support will have to create a new
tarball.
Since we are here, add broken= case to catch template mistakes early.
=> ghc-bin: remove i686-musl support.

srcpkgs/ulogd/template
=> ulogd: enable pcap output as a build option

srcpkgs/cross-vpkg-dummy/template
=> cross-vpkg-dummy: Fix typo in ld-linux-x86-64.so.2 name

srcpkgs/R/template
Changed the way in which external blas was specified, as of R version 4.0.5 the old configuration no longer worked.
=> R: update to 4.1.0.

srcpkgs/eid-mw/patches/0001-fix-unknown-type-int8_t-errors-when-compiling-for-aa.patch, srcpkgs/eid-mw/template
* new `libassuan-devel` needed (unless we want to use `pinentry` instead?)
* for cross-compiling, it's needed both as a host and as a target dependency, because the autoconf stuff needs the macros for generating `./configure` from `configure.ac`... this is not ideal, but it's how I got it to work.
* `libbsd` now needed for `strlcpy`
* `autoconf-archive` [now needed as well](https://github.com/Fedict/eid-mw#code-from-git-repository)
* [patch file needed for this issue](https://github.com/Fedict/eid-mw/pull/142/files), should be removed once that's in a new release
-------
=> eid-mw: update to 5.0.22

srcpkgs/mailnag-goa-plugin/template, srcpkgs/mailnag/files/README.voidlinux, srcpkgs/mailnag/template
=> New packages: mailnag-2.2.0, mailnag-goa-plugin-2.0.0

srcpkgs/iwd/patches/resolvconf-default.patch, srcpkgs/iwd/template
[Changelog](https://git.kernel.org/pub/scm/network/wireless/iwd.git/commit/?id=6d47354e630f770c25b635ae80818ee4d37c050c):
```
Add support for FT-over-DS procedure with multiple BSS.
Add support for estimation of VHT RX data rate.
Add support for exporting Daemon information.
```
=> iwd: update to 1.15.

srcpkgs/burp2-server/update
=> burp2-server: fix unstable release detection

srcpkgs/glfw/update
Ignore binaries:
```console
$ ./xbps-src update-check glfw
glfw-3.3.4 -> glfw-3.3.4.bin.MACOS
```
=> glfw: fix update file

srcpkgs/runc/template
=> runc: update to 1.0.0-rc95

srcpkgs/cgdb/patches/fixescape.patch, srcpkgs/cgdb/template
The current version of cgdb has broken escape sequences (its prompt is `[?2004h(gdb) `). This is already fixed in their Github repo, but the latest official release does not contain the fix. The issue mentioning this is [here](https://github.com/cgdb/cgdb/issues/256). I have created the `fixescape.patch` patch from [these](https://github.com/cgdb/cgdb/issues/239#issuecomment-706249589) patches and from [this](https://github.com/cgdb/cgdb/issues/255#issuecomment-820546156) patch.
=> cgdb: fix escape sequences

srcpkgs/fossil/template
Tarballs are [generated on demand](https://fossil-scm.org/home/help?cmd=/tarball) by fossil. The name of the file in the URL only specifies the name of the root directory inside the tarball, while the `release` parameter selects which tree to download.
All the URLs in the download page include a commit hash, which I wanted to avoid when I made #31609. I thought that omitting it was enough, but this resulted in downloading the most recent commit. Using the tag name works too.
=> fossil: fix distfiles url

srcpkgs/python3-dotenv/template
The only package that depends on this is `docker-compose`. I don't think it needs to be rebuilt since it's a python3 module. Am I correct?
=> python3-dotenv: update to 0.18.0.

srcpkgs/qemu/template
=> qemu: enable JACK Audio support

srcpkgs/sof-firmware/template, srcpkgs/sof-tools
In addition to updating the firmware to version 1.8, this commit adds the sub-package `sof-tools`, which provides binaries used for testing and development of `sof-firmware`.
=> sof-firmware: update to 1.8

srcpkgs/python3-language-server/patches/jedi_compat.patch, srcpkgs/python3-language-server/template
Project seems to be unmaintained at the moment. There's an active fork at
https://github.com/python-lsp/python-lsp-server that we can switch to
in future.
=> python3-language-server: fix compatibility with jedi 0.18.0

srcpkgs/qt5-speech/template
The cmake file references them and so without this change it breaks
builds using qt5-speech-devel with cmake (eg knotifications,
ktextwidgets).
=> qt5-speech: add other solibs to -devel depends.

.github/workflows/cron.yml, common/scripts/README.xbps-cycles.md, common/scripts/xbps-cycles.py
From https://github.com/ahesford/xbps-cycles, license is compatible with
void-packages. Will be run in CI, so it should live in the same
repository.
=> common/scripts: import xbps-cycles.

srcpkgs/deluge/files/deluged/run, srcpkgs/deluge/template
While we're at it, drop priviledge early.
Fix: https://github.com/void-linux/void-packages/issues/31690
=> deluge: set config dir to homedir

srcpkgs/libtorrent-rasterbar/template
qBittorrent builds successfully with the new library version.
=> libtorrent-rasterbar: update to 1.2.14.

srcpkgs/gnome-font-viewer/template
This also fixes the lack of desktop file, as package installs translated file
which was getting ignored when gettext was not found on the host system:
https://gitlab.gnome.org/GNOME/gnome-font-viewer/-/blob/1e5b/src/meson.build#L42
Fixes #31730
=> gnome-font-viewer: needs gettext in hostmakedepends.

srcpkgs/font-adobe-source-code-pro/template
Should the transitional dummy package be removed?
=> font-adobe-source-code-pro: update to 2.038R.

srcpkgs/musl/patches/99d5098a885feae3ae8c32b407350d8ca85dd178.patch, srcpkgs/musl/template
Will be necessary in future shadow releases, as seen in
https://github.com/shadow-maint/shadow/pull/360.
=> musl: backport crypt_blowfish update.

srcpkgs/yabause-gtk/template, srcpkgs/yeahconsole/template, srcpkgs/ykpers-gui/template
=> Omnibus lint pass for SPDX warnings - packages starting with Y

srcpkgs/libcaca/template
Using ncurses backend is preferable. See https://github.com/void-linux/void-packages/pull/31717#issuecomment-873335867
=> libcaca: enable imlib2 support without x11

srcpkgs/zisofs-tools/template, srcpkgs/zmap/template, srcpkgs/zsnes/template, srcpkgs/zsync/template
=> Omnibus lint pass for SPDX warnings - packages starting with Z

srcpkgs/LabJackPython/template, srcpkgs/exodriver/patches/destdir.patch, srcpkgs/exodriver/patches/link-so-correctly.patch, srcpkgs/exodriver/template
Running this for CI.
Could use a sanity check. Not sure if LabJackPython should be a package. I don't see the harm in it, but it's not compiled, has no compiled aspects, basically is here because it helps me  test (and also use) the exodriver library.
Also not sure if labjackusb.so (from exodriver) should be in common/shlibs, since no existing programs I know about want to link it.
=> [RFC] Labjack

srcpkgs/ImageMagick/template
=> ImageMagick: build with openjpeg2

srcpkgs/certbot-apache/template, srcpkgs/certbot-nginx/template, srcpkgs/certbot/template, srcpkgs/python3-acme/template
Updates certbot, certbot-nginx, certbot-apache.
The update to certbot-apache now also includes config for Void Linux, so `certbot --apache` should work out of the box for basic cases. 🎊
=> certbot: update to 1.17.0.

srcpkgs/grml-zsh-config/template
The current version (0.18.0) was again removed from their repo, like in the previous version (#31478). This means that the build of the current version fails with `Not Found` error. I've [reached out](https://github.com/grml/grml-etc-core/issues/120) to the maintainers, and they said that GitHub releases should be used instead of their debian mirror. This should make grml-zsh-config buildable even if newer versions are available.
---
=> grml-zsh-config: update to 0.19.0 + fix

srcpkgs/ardour/template
Also remove freedesktop integration from template. It's handled by upstream since 6.7.
=> ardour: update to 6.8.

common/shlibs, srcpkgs/lhasa/template
To avoid installation failure such as:
[*] Updating repository ...
MISSING: liblhasa>=0.3.1_1
Transaction aborted due to unresolved dependencies.
=> common/shlibs: correct lhasa pkg name

srcpkgs/boost/template
Download location documented to replace the old, non-working one:
https://www.boost.org/users/news/boost_has_moved_downloads_to_jfr.html
>> Instead of: https://dl.bintray.com/boostorg/release/ you should use https://boostorg.jfrog.io/artifactory/main/release/ to retrieve boost releases.
Tested availability of  the present version:
$ curl -I https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2 2>&1|egrep Date\|256
Date: Sat, 10 Jul 2021 21:30:24 GMT
X-Checksum-Sha256: 59c9b274bc451cf91a9ba1dd2c7fdcaf5d60b1b3aa83f2c9fa143417cc660722
[skip ci] no package change expected, only the distribution location for future builds
=> boost: new distfiles location

common/environment/setup/install.sh, common/xbps-src/libexec/xbps-src-doinstall.sh
Historically, PKGDESTDIR was only set during pkg_install, and
XBPS_PKGDESTDIR was set to indicate that we're in subpkg's
pkg_install.
However, from 0b95cb8f5d, (Merge xbps-src code to make it usable in
a standalone mode., 2014-03-22), PKGDESTDIR is always set,
regardless of states.
Let's drop all usages of XBPS_PKGDESTDIR.
While we're at it, error out of vmove is used outside of subpkg.
=> xbps-src: retire XBPS_PKGDESTDIR

srcpkgs/instaloader/template
Also:
- expand the $pkgname in distfiles
- remove license file and the special handling from the template
(now the tarball contains a license file).
=> instaloader: update to 4.7.4.

srcpkgs/i2pd/template
From upstream's 2.35.0 releasenote:
>cmake and make flag with AVX switch (USE_AVX in make and -DUSE_AVX=1 in cmake) was deprecated due to changes in code.
so I removed this flag.
=> i2pd: update to 2.38.0.

srcpkgs/gmsh/template
OpenCASCADE is needed for a lot of the functionality of gmsh, and it's suggested as one of the dependencies here: https://gitlab.onelab.info/gmsh/gmsh/-/wikis/Gmsh-compilation
I think it's reasonable to compile support for it by default.
=> gmsh: Added occt and version bump

srcpkgs/containerd/template
containerd 1.5.2 addresses a security issue: https://github.com/containerd/containerd/releases/tag/v1.5.2
=> containerd: update to 1.5.2.

srcpkgs/crash/template
---
Without `binutils`, `crash` fails due to missing `/usr/bin/strings`:
```
% crash kdump.vmcore vmlinux
...
WARNING: kernel relocated [664MB]: patching 81548 gdb minimal_symbol values
please wait... (patching 81548 gdb minimal_symbol values) sh: 1: /usr/bin/strings: not found
WARNING: kernels compiled by different gcc versions:
vmlinux: (unknown)
kdump.vmcore kernel: 7.5.0
WARNING: kernel version inconsistency between vmlinux and dumpfile
crash: incompatible arguments:  vmlinux is not SMP -- kdump.vmcore is SMP
Usage:
crash [OPTION]... NAMELIST MEMORY-IMAGE[@ADDRESS]     (dumpfile form)
crash [OPTION]... [NAMELIST]                          (live system form)
Enter "crash -h" for details.
```
=> crash: depend on binutils

srcpkgs/j4-dmenu-desktop/template
The current version of tests errors out when `/usr/share/applications` does not exist. See https://github.com/enkore/j4-dmenu-desktop/pull/123
=> j4-dmenu-desktop: add support for checks

srcpkgs/newsflash/template, srcpkgs/newsflash/update
=> New package: newsflash-1.4.2

srcpkgs/libxcb/template
So you can statically link against X programs; since libX11 links
against libxcb this is impossible now.
Either I'm not understanding how static linking works (AFAIK you *need*
the .a file?), or this is a very unpopular thing to do as it's been like
this for 9 years (changed in commit 9526648, in 2012) 🤔
=> libxcb-devel: install static libraries

srcpkgs/mkinitcpio/template
encrypt hook does not depend on lvm2 nor lvm2 hook. It just needs 11-dm-initramfs.rules, so I moved to the base package.
=> mkinitcpio: remove dependency on -lvm2 from -encrypt subpackage

srcpkgs/wireguard-tools/template
Other distros are putting them in /usr/share/wireguard-tools/examples,
so we also do that for consistency.
=> wireguard-tools: include contrib/ contents in package.

common/build-style/cmake.sh
CMake adds `-DNDEBUG` with build types `Release`, `MinSizeRel` and `RelWithDebInfo` (see https://github.com/Kitware/CMake/blob/master/Modules/Compiler/GNU.cmake#L57). `NDEBUG` disables `assert()`, which can improve performance.
=> Add -DNDEBUG to CFLAGS and CXXFLAGS in CMake build style

srcpkgs/vim/template
Our vim build support different configurations, but the template builds all of them by default. This is a problem if one just wants a "small" vim as the dependency chain is huge (featuring LLVM, MozJS, Rust, ...).
Add three options to configure the builds:
- x11 enables the X11-clipboard build
- gtk3 enables gvim
- huge enables language interpreters (disabled for cross)
Should have no functional difference, maintenance overhead is neglegible.
I cleaned up some flags that got removed in 2019.
cc @NeelChotai
=> vim: add options for different build variants.

srcpkgs/python-tkinter/template, srcpkgs/python/template, srcpkgs/python/update
ActiveState is running a branch of cPython that has a bunch of security fixes, at
https://github.com/ActiveState/cpython/
This is very convenient to use for our python package, so let's do it.
=> Move Python 2 to Active State cPython

srcpkgs/caddy/INSTALL.msg, srcpkgs/caddy/files/caddy/run, srcpkgs/caddy/patches/fix_version_command.patch, srcpkgs/caddy/template
As there is currently a bug with go build info
(https://github.com/golang/go/issues/29228) a patch is needed to
fix printing the correct version number of the binary. Once the bug is
fixed, the patch can be dropped.
Fix for #22092
- [ x] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
=> caddy: upgrade to 2.4.3

srcpkgs/zathura/patches/fix-buffer-overflow.patch, srcpkgs/zathura/template
Tested on x86_64-musl, fixes #31722
=> zathura: backport (improved) upstream patch for buffer overflow

common/shlibs, srcpkgs/dosbox-staging/template, srcpkgs/libmt32emu-devel, srcpkgs/libmt32emu/template
This is a draft based on a current git snapshot, because DOSBox Staging 0.77.0 has not been released yet.
@kcgen wrote (https://github.com/joshuakraemer/void-packages/commit/2d0e6a7ee8328c8210c8ed272dc38dd8317296ff#commitcomment-51084600):
> @joshuakraemer, looks good!
> 
> I realize this is using the `master` branch right now until we can wrap up 0.77. In the meantime, regarding: `-Duse_mt32emu=false`, can you try removing that? Meson should be able to build it internally based on its wrap. There should be no copyright concerns, as users must provide their own ROMs for this feature.
Thank you for your comments. I have added libmt32emu as a separate package, and successfully tested MT-32 emulation.
> Also, there might be more configuration options needed to ensure an optimized binary is …
=> New package: dosbox-staging-0.77.0

srcpkgs/pulseeffects-legacy/template, srcpkgs/pulseeffects/template
- pulseeffects: update to 5.0.4 & remove unneded python deps
- pulseeffects-legacy: remove unneded python deps
~~Blocked by https://github.com/void-linux/void-packages/pull/31666, though magically CI passed, I really don't know why!~~
**UPD**: see https://github.com/void-linux/void-packages/pull/31667#issuecomment-869485860
=> pulseeffects: update to 5.0.4

srcpkgs/mesa/template
=> mesa: update to 21.1.5.

srcpkgs/zlib/template
Added in 4d39b701666370b53a7167c00702a1d7a4213a87 without explanation as
to why.
We also revbump to rebuild the binary. On x86_64-musl, old libz.so,
built with gcc 7, is using a 2132KB RE mmap when dynamically linked,
probably because of a 0x200000 alignment required for the RE section.
After rebuilding, 96KB are used, with the actual RE mmap reduced to 56K.
The new alignment is 0x1000.
=> zlib: remove LDFLAGS workaround.

srcpkgs/usbguard/template
Fixes https://github.com/void-linux/void-packages/issues/31768. The `/etc/usbguard/IPCAccessControl.d` directory is needed by `usbguard-daemon` and will fail to start without it.
=> usbguard: prevent removal of IPCAccessControl.d directory

srcpkgs/libserialport/patches/0001-Remove-termiox-as-it-has-been-removed-from-recent-ke.patch, srcpkgs/libserialport/template
Without this patch, libserialport will fail opening a tty device with an "No such ioctl for device"-error. This prevents eg. sigrok/pulseview from working with a SUMP-compatible logic analyzer.
EDIT: some clarification: [see here](https://sigrok.org/gitweb/?p=libserialport.git;a=commit;h=6f9b03e597ea7200eb616a4e410add3dd1690cb1), something like their patches would work better, but, honestly, libserialport should have a new release, 0.1.1 is from years ago.
=> libserialport: add patch to prevent it from using termiox, which has been removed from recent kernels

srcpkgs/jdupes/template
Despite the flag ENABLE_BTRFS is enabled for make, this seems to be mishandled by the way the Makefile builds the CFLAGS, so the functionality does not get included.
(It does not depend on any BTRFS headers, libraries, or ioctls, only if the appropriate flag is given on run)
=> Jdupes 1200

srcpkgs/cross-x86_64-w64-mingw32/template
[ci skip]
* Mingw-w64 9.0.0
* GCC 11.1.0 (sort of future-proofing)
* Binutils harmonized with mainline (with GCC template)
* Homepage placed after license (according to `xlint`)
=> cross-x86_64-w64-mingw32: update to 9.0.0

srcpkgs/rhash/template
- significantly improve file reading performance on Linux/Unix
- print 'Nothing to verify' when verifying a hash file without a message digest
- count unparsed lines of a hash file as errors
- print line numbers of unparsed lines of a hash file
- Bugfix: fix verification of some hash files containing spaces in file paths
- [ x I built this PR locally for these architectures (if supported. mark crossbuilds):
- [ x armv7l
=> rhash: update to 1.4.2

srcpkgs/apparmor/template
* python3-dbus is needed for aa-notify, closes #32052
* ss from iproute2 is needed for aa-unconfined
=> apparmor: add missing dependencies

srcpkgs/chezmoi/template
=> chezmoi: update to 2.1.2.

srcpkgs/OpenRCT2/template
In the last version, a few of the tests were broken, so I hadn't put in the plumbing for the check step yet. Now the tests all pass, so that's cool.
Also, I removed `/usr/lib/libopenrct2.a`, which only exists to be linked into `openrct2` and `openrct2-cli` and shouldn't have been included in the package itself. (It can also be built as a shared object, but again it's only used to share code between the two binaries, and I'm not going to try to reconcile that with Void policy over 10M of duplicated code.)
=> OpenRCT2: update to 0.3.4, enable tests

srcpkgs/bum/patches/mpd2-3.patch, srcpkgs/bum/template, srcpkgs/python3-mpd2/template
I tested almost all the dependants:
* sonata 1.7b1 and 1.7.0 - work fine
* mpdevil - works fine
* python3-mpdnotify - works fine
* bum - works with a small patch, then kind of works, but crashes in different places, but that's not related to a python3-mpd2 update
* mpDris2 - crashes for me, apparently that's an upstream bug specific to my configuration, but I think it's safe to assume it works, because alpine packages only one package which depends on python3-mpd2 - mpdris2, so it's probably well tested there. If someone could test this in a non-GNOME environment, that would be nice.
=> python3-mpd2: update to 3.0.4, fix bum

srcpkgs/wpa_supplicant/patches/roam-properties.patch, srcpkgs/wpa_supplicant/template
The current version of wpa_supplicant emits following error message on shutdown:
dbus: wpa_dbus_property_changed: no property SessionLength in object /fi/w1/wpa_supplicant1/Interfaces/0
This pull reqest adds a patch [stolen from Archlinux](https://github.com/archlinux/svntogit-packages/commit/73ce2847aec510861a041ac369054a9aed5c3406) that fixes the issue.
@Gottox
---
=> wpa_supplicant: fix wpa_dbus_property_changed

srcpkgs/xournalpp/INSTALL.msg, srcpkgs/xournalpp/patches/plugin-path.patch, srcpkgs/xournalpp/template
Also:
- add libsrvg-devel (new dependency)
- replace virtual?tex with texlive-latexextra
- remove INSTALL.msg (latexextra contains standalone).
=> xournalpp: update to 1.1.0.

srcpkgs/vivaldi/template
Also:
- remove i686 support - the upstream is not updating it.
=> vivaldi: update to 4.0.2312.41.

srcpkgs/ghc/patches/sphinx-unicode.patch
./srcpkg build ghc fails with current tools:
"inplace/bin/ghc-stage1" [...] /build/cbits/longlong.p_o
Running Sphinx v4.0.2
Configuration error:
There is a syntax error in your configuration file: (unicode error) 'unicodeescape' codec can't decode bytes in position 1-2: truncated \uXXXX escape (conf.py, line 87)
...
make: *** [Makefile:128: all] Error 2
According to https://gitlab.haskell.org/ghc/ghc/-/issues/19962
>> This fix is to use raw strings, as already done in master:
>> https://gitlab.haskell.org/ghc/ghc/-/blob/master/docs/users_guide/conf.py#L96
Sanitized from commit (only small parts apply)
https://gitlab.haskell.org/ghc/ghc/-/commit/83407ffc7acc00cc025b9f6ed063add9ab9f9bcc
[skip CI] build might take over 3 hours with a single CPU - local build/pkg tested
(Please choose at …
=> ghc: allow building with current Sphinx

srcpkgs/caps2esc/template, srcpkgs/interception-tools/files/udevmon/run, srcpkgs/interception-tools/template
=> New packages: interception-tools-0.6.7, caps2esc-0.3.2

srcpkgs/i3status-rust/template
Starting with v0.20.0 some formerly hard coded settings were moved into config files (see https://github.com/greshake/i3status-rust/blob/master/NEWS.md#breaking-changes-1).
=> i3status-rust: add missing files

srcpkgs/notcurses/template
Also:
- add zlib-devel to makedepends (new dep).
=> notcurses: update to 2.3.11.

srcpkgs/nushell/template
=> nushell: update to 0.34.0

Manual.md
All but 4 meta packages already use "Public Domain" for their licensing
instead of the original "BSD-2-Clause" recommendation.
=> Manual.md: fix license for meta packages.

srcpkgs/screen/template
This requires that the screen binary be suid.
=> [RFC] screen: don't enable multiuser mode by default.

srcpkgs/screen/files/20-screen.sh, srcpkgs/screen/template
When screen isn't suid, it can't create the directory under /run/screens
for sessions to sit in. We went with this approach instead of removing
--with-socket-dir so screen would default to using ~/.screen, becaise it
would require users with currently running screen sessions to launch the
screen client with SCREENDIR set correctly.
Since that approach would be more complicated for users and require
leaving an INSTALL.msg in the package for some time, we went with a
simpler one of always creating the directory at build time.
=> screen: fix launch.

srcpkgs/corectrl/template
=> corectrl: update to 1.1.4.

srcpkgs/screen/INSTALL, srcpkgs/screen/template
After 56db43e, the directory is created at boot time.
This means if one installs screen it won't work until
after the first reboot.
This commit fixes that by creating the directory also
at install time. Note that we still need to create the
directory at boot time, since /run is cleared (tmpfs).
=> screen: create /run/screens also at install time

srcpkgs/lollypop/template
=> lollypop: update to 1.4.22 and fix runtime deps

srcpkgs/dtc/template
Removes a huge dependency chain from cross toolchains. The git dependency is used for getting the version, but then the variable in the Makefile is never used. Maybe the package doesn't have to be revbumped?
=> dtc: remove git from hostmakedepends

srcpkgs/dnsdist/files/dnsdist/run, srcpkgs/dnsdist/template, srcpkgs/dnsdist/update
This is my second attempt (first one was #28109 ). Sorry for being such a newb, this is my first attempt at xbps packaging.  The original PR wanted to use the upstream .conf instead of my sample one, so I went with the upstream one this time. The reason I didn't use it originally was because it's entirely commented out, so it doesn't work out of the box. I wanted a better user experience by default.
=> New package: dnsdist-1.6.0

srcpkgs/libX11/patches/handle_new_xorgproto_symbols.patch, srcpkgs/libX11/template
Apply upstream merge request to handle the new _EVDEVK xorgproto symbols,
so that xkbcomp does not generate hundreds of warnings.
See https://gitlab.freedesktop.org/xorg/lib/libx11/-/merge_requests/79
This works for me, and it fixes 
https://github.com/void-linux/void-packages/issues/31870
=> libX11: patch for new symbols

srcpkgs/imlib2/template
=> imlib2: update to 1.7.2.

srcpkgs/emptty/template
[quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements)
confirm this PR works for me
=> emptty: update to 0.6.0.

srcpkgs/pylint/patches/fix-tests.patch, srcpkgs/pylint/template, srcpkgs/python3-astroid/template
* pylint doesn't install tests anymore, so we don't need to remove them
* manpages were old and so they were removed upstream
* moved distfiles from pypi to github, because pypi releases don't contain tests
* updated python3-astroid, because they are tightly coupled and pylint 2.9 needs astroid 2.6
* adopted both packages
=> pylint 2.9.6, astroid 2.6.5

srcpkgs/linux-base/template, srcpkgs/linux-lts/template, srcpkgs/linux/template
Our dances for installing a given kernel version but still having firmware and dracut are error prone and unnecessary. This PR aims to solve that.
If we want to split the `dracut` dependency for greater initramfs flexibility, we can discuss that here too.
=> Rework linux and linux-lts meta packages, also update linux-lts

srcpkgs/fail2ban/template
- this is second PR with this change. I messed up miserably when I tried to squash commits in a previous one, to the state I wasn't able fix, so I decided to close it and create a new one - sorry for the mess;
- `make_dirs` addition is because in previous version this directory was not created and fail2ban didn't start because it was not able to create database. This is just for convenience, now the package can be started right away after installation without any action from the user.
=> fail2ban: update to version 0.11.2

srcpkgs/shotcut/template
shotcut does not use webkit since
https://github.com/mltframework/shotcut/commit/a44fe75a4dc7410668935cd0d3470994f5997571.
no revbump because this is purely build-time change.
I have not tested this, but it should result in exactly the same package, which should be shown by CI. Not sure if no-revbump will still trigger CI though.
=> shotcut: remove qt5-webkit-devel dep

srcpkgs/nvidia/INSTALL, srcpkgs/nvidia/template
Proton sometimes errors out with:
The NVIDIA driver was unable to open
'libnvidia-glvkspirv.so.470.57.02'. This library is required at run
time.
This is caused by an out of date glibc cache, so we now run ldconfig in
INSTALL. This solution was pointed out by mvf.
Unfortunately, this isn't the entirely correct solution: ldconfig should
always be run after package installations that touch /usr/lib, to avoid
similar issues. Until there's a simple solution for it (maybe general
purpose XBPS hooks), this is the best we can do.
Fixes: #32222
=> nvidia: fix proton errors.

srcpkgs/timeshift/patches/d437358a.patch, srcpkgs/timeshift/template
----
Timeshift is virtually unusable due to a change in util-linux, see:
- https://github.com/teejee2008/timeshift/issues/425
- https://github.com/teejee2008/timeshift/issues/753
- https://github.com/teejee2008/timeshift/issues/755
This PR applies an [official patch](https://github.com/teejee2008/timeshift/commit/d437358ac3debf7625aefda4d0bd387a91b69df5) to make the package usable on Void until the next official release, presumably later [this year](https://github.com/teejee2008/timeshift/issues/648).
=> timeshift: fix compatibility with util-linux 2.37.1

srcpkgs/libid3tag/template
used mirror distfiles.exherbo.org doesn’t respond anymore
use original sourceforge download site
=> libid3tag: fix distfiles

srcpkgs/protonvpn-cli/template
After updating protonvpn-cli (#32299), I started getting `ModuleNotFoundError: No module named 'distro'`. Turns out it's because `protonvpn-cli` uses the new [`distro`](https://github.com/python-distro/distro) dependency starting from version 2.2.8 (see ProtonVPN/linux-cli-community@117f5972ab09d44b5df07ffb88b120db9392c515).
=> protonvpn-cli: add missing dependency

srcpkgs/ART/template
ART is a fork of RawTherapee with at least a dozen useful changes. It also takes some code from Darktable.
~~Chose ART as pkgname as art is too conventional (tar.gz has no name in it)~~
- Did not test on other platforms, but should run fine as the template is basically the same as RawTherapee's, the only difference being exiv2 as an additional dependency.
=> New package: ART-1.9.3

srcpkgs/portage/template
=> portage: update to 3.0.21.

srcpkgs/herbstluftwm/template
The new dependency to libXrender-devel is mentioned in upstream's changelog.
=> herbstluftwm: update to 0.9.3

srcpkgs/hydroxide/template
Bump hydroxide's version from 2.18 to 2.19
- [X ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
=> hydroxide: update to 0.2.20

srcpkgs/deluge/files/deluged/run, srcpkgs/deluge/patches/drop-priv.patch, srcpkgs/deluge/template
=> deluge: allow deluged to be run as different user

srcpkgs/retroarch/template
When both gles2 and opengl options are enabled, RetroArch will only
build with OpenGL ES support. This prevents OpenGL only cores from working.
Disable gles2 by default and use the glcore driver which provides OpenGL 3.2+
and OpenGL ES 3+ support. Fixes: #32246
libusb support is automatic and is currently pulled in when sdl2 is enabled.
Add it to makedepends to ensure it's always enabled.
RetroArch will call xdg-screensaver when it's built with X11 support.
Add xdg-utils to depends when the x11 option is enabled.
=> retroarch: disable gles2 by default, add libusb and xdg-utils deps

srcpkgs/c-ares/template
=> c-ares: update to 1.17.2.

srcpkgs/haproxy/files/haproxy.cfg, srcpkgs/haproxy/files/haproxy/run, srcpkgs/haproxy/template
Switch HAProxy to a master/worker (-W) model, allowing for correct
handling of HUP signals. To do listening FD handoff, a stats socket with
'expose-fd listeners' needs to be part of the configuration file.
=> haproxy: enable hitless reloads

srcpkgs/xdg-utils/template
`xdg-screensaver` will output the following when `xset` isn't installed manually or pulled in by another package.
```
/bin/xdg-screensaver: 900: xset: not found
/bin/xdg-screensaver: 908: [: Illegal number: 
/bin/xdg-screensaver: 647: xset: not found
```
=> xdg-utils: xdg-screensaver needs xset

srcpkgs/nginx/template
This change is required for dynamic modules to work, as mentioned in [this tutorial](https://www.nginx.com/blog/compiling-dynamic-modules-nginx-plus/):
"`--with-compat` ... creates a standard build environment supported by both NGINX Open Source and NGINX Plus."
=> nginx: configure with --with-compat for dynamic module support

common/shlibs, srcpkgs/giac/patches/pari_2_13.patch, srcpkgs/giac/template, srcpkgs/pari/patches/makefile.patch, srcpkgs/pari/template, srcpkgs/qcas/template
- enable pthreads build
- switch gp binary to static link libpari; this offsets the slowdown due to pthreads
- use -flto and -fno-semantic-interposition which improve speed a little bit more
- ship the static library, so external programs can static link
- change of maintainer agreed by sgn
- revbump giac and qcas
**Rationale:**
- pthreads gives an interesting functionality, and recent versions of giac require pari with tls; sagemath requires pari with pthreads.
- The cost for enabling pthreads is quite high, on the order of 30-40% for some tests; `-flto` saves maybe 1-2% at most, `-fno-semantic-interposition` saves 5-7%, but we are still about 25-30% behind.
- On the other hand, switching to static binary yields some savings on the order of 5-10%
- More important: the cost of enabling …
=> pari: update to 2.13.2.

srcpkgs/i3status-rust/template
0.20.3 contains several useful fixes, such as the NetworkManager block working for new versions of NM. For more details see https://github.com/greshake/i3status-rust/blob/master/NEWS.md#i3status-rust-0203
=> i3status-rust: update to 0.20.3.

srcpkgs/mesa/template
=> mesa: update to 21.1.7.

srcpkgs/haproxy/template
Move to using DEBUG_CFLAGS when passing CFLAGS to makefile, otherwise we
override their required CFLAGS, such as -fwrapv.
@zdykstra only tested that it starts at all, given the DEBUG_CFLAGS change.
=> haproxy: update to 2.4.3.

common/shlibs, srcpkgs/libpkgconf, srcpkgs/pkgconf-devel, srcpkgs/pkgconf/template
We used to ship a static library in the main package, which was
accidental. We now ship it in pkgconf-devel package.
=> pkgconf: update to 1.8.0, split -devel and libpkgconf.

srcpkgs/zoxide/template
Zoxide has a pending update (0.7.3 -> 0.7.4), however, it requires rust 1.54.0 to build.
=> zoxide: add shell completions

srcpkgs/R/template
According to the R 4.1.1 changelogs make check now works also without a LaTeX installation. Should we drop the texlive make depends or keep it as it is?
=> R: update to 4.1.1.

srcpkgs/planner/template, srcpkgs/planner/update
=> planner: update to 2.7

common/shlibs, srcpkgs/freerdp-server, srcpkgs/freerdp-server-devel, srcpkgs/freerdp/template, srcpkgs/gnome-remote-desktop/template, srcpkgs/gnome/template, srcpkgs/libfreerdp-server
gnome-remote-desktop adds a Screen Sharing option to GNOME Settings. It can use both RDP and VNC, but the GNOME Settings GUI allows configuring only VNC, so I disabled RDP support (it's still available under a build option).
=> New package: gnome-remote-desktop-40.1

srcpkgs/pipewire/patches/fix-hotplug-usb-devices.patch, srcpkgs/pipewire/template
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1478
I was bitten by this and patch solves it. Although a new release is probably coming soon
=> pipewire: add fix for usb devices from master

srcpkgs/gnome-remote-desktop/template
Static distfile is less stress for server.
Also, better for update-check.
=> gnome-remote-desktop: switch distfiles to GNOME_SITE

srcpkgs/haskell-language-server/template
I built this on i686 as well and did not run into any GHC panics.
=> haskell-language-server: update to 1.3.0

srcpkgs/docker-compose/template, srcpkgs/python-idna/template, srcpkgs/python-requests/template, srcpkgs/python3-charset-normalizer/template, srcpkgs/python3-idna, srcpkgs/python3-idna/template, srcpkgs/python3-websocket-client/template, srcpkgs/python3-websocket-client/update, srcpkgs/streamlink/template
python3-websocket-client:
* they changed their license to Apache2
* 0.58.0 was a breaking release, but some distributions didn't notice (alpine had 0.58 for a while), so the update should be without a problem, now they follow semver
* 1.0.0 dropped python2 support
docker-compose:
* I removed websocket-client from dependencies, because they don't use it since 2014, but they still list it in dependencies https://github.com/docker/compose/issues/8455
python3-requests (updated because streamlink needs requests>=2.26):
* python3-chardet was replaced by python3-charset-normalizer in the python3 package (upstream decision)
=> streamlink 2.3.0 and python3-websocket-client 1.2.1

srcpkgs/winetricks/template
Current winetricks, which is from February, is broken all over the place.
=> winetricks: update to 20210825.

srcpkgs/libslirp/template, srcpkgs/slirp4netns/template
- libslirp: update to 4.6.1
- slirp4netns: update to 1.1.12
=> slirp4netns 1.1.12

srcpkgs/podman/template
According to the changelog, the install.cni make target is now gone, and
podman will create the relevant CNI config when it first starts.
=> podman: update to 3.3.0

srcpkgs/fontmanager/template
=> fontmanager: update to 0.8.7 + minor fixes

srcpkgs/node_exporter/files/node_exporter/log/run, srcpkgs/node_exporter/files/node_exporter/run, srcpkgs/node_exporter/template
=> node_exporter: Send output to syslog.

srcpkgs/rssguard/template
Also add qt-multimedia-devel to makedepends
(new upstream dep).
- [Χ] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
=> rssguard: update to 4.0.1.

srcpkgs/libxfce4ui/template
Also add libgtop-devel to makedepends
(provide system info).
=> libxfce4ui: update to 4.16.1.

srcpkgs/sublime-text4/template
=> New package: sublime-text4-4107

srcpkgs/rc/template
`rc` seems pretty dead now. `tobold.org` and `static.tobold.org` are down. I have tried to contact the author, but his email seems to be down too. This package should maybe be removed rather than fixed.
This PR fixes dead links and modifies the build process.
@leahneukirchen I'm pinging you since you are the maintainer of `rc`. Do you have any comment on this?
=> rc: fix dead links

srcpkgs/upwork/template
The download subdomain changed from updates to upwork-usw2.
=> upwork: update to 5.6.8.0

srcpkgs/cdparanoia/patches/byteswap-null-check.diff, srcpkgs/cdparanoia/template
From upstream r15356, fixes a segfault when attempting to read discs
on big-endian systems. 
=> libcdparanoia: byteswap null check

srcpkgs/go/template
I removed --no-clean because it's deprecated, ignored and forcing this behavior now seems to be hard and probably not worth it.
```
=> go-1.17.1_1: running do_build ...
Building Go cmd/dist using /usr/lib/go1.12. (go1.12.17 linux/amd64)
warning: --no-clean is deprecated and has no effect; use 'go install std cmd' instead
Building Go toolchain1 using /usr/lib/go1.12.
```
=> go: update to 1.17.1.

common/hooks/post-install/14-fix-permissions.sh
Completions don't have to be executable and they almost never are. On my system only colord installs an executable bash completion file.
=> hooks/fix-permissions: add completion directories

srcpkgs/python3-binaryornot/patches/0001-fix-failing-test.patch, srcpkgs/python3-binaryornot/template, srcpkgs/python3-boolean.py/template, srcpkgs/python3-debian/patches/0001-Disable-apt_pkg-support.patch, srcpkgs/python3-debian/template, srcpkgs/python3-debian/update, srcpkgs/python3-license-expression/template, srcpkgs/reuse/template
See <https://reuse.software> for more info.
=> New package: reuse-0.13.0

srcpkgs/musca/template
Musca seems pretty dead now. Maybe it should be removed. The current `homepage` points to a shady site and the current `distfiles` isn't accessible. This PR fixes both issues.
=> musca: change distfiles and homepage

srcpkgs/R/template
R people assumes it's defined for musl libc.
=> R: define __MUSL__ when building for musl libc

srcpkgs/pipe-viewer/template
Since abb67212933b358f3f4f118a0aa9d94517181156 this must be explicit.
Previously it was implicit through
perl-LWP-Protocol-https -> perl-LWP -> perl-HTTP-Message -> perl-HTML-Parser.
=> pipe-viewer: depend on perl-HTML-Parser

srcpkgs/gns3-gui/patches/requirements.patch, srcpkgs/gns3-gui/template, srcpkgs/gns3-server/patches/requirements.patch, srcpkgs/gns3-server/template, srcpkgs/python3-py-cpuinfo/template, srcpkgs/python3-pytest-aiohttp/template, srcpkgs/python3-pytest-timeout/template
=> GNS3 2.2.25

srcpkgs/graphviz-gtk, srcpkgs/graphviz-x11, srcpkgs/graphviz/graphviz-gtk.INSTALL, srcpkgs/graphviz/graphviz-gtk.REMOVE, srcpkgs/graphviz/graphviz-x11.INSTALL, srcpkgs/graphviz/graphviz-x11.REMOVE, srcpkgs/graphviz/template
See #32826.
Arguably, the split of x11 is less important. It saves from `libXaw`, `libXmu` and `libXt`, but `libX11` and `libXrender` are deps via `cairo` anyway.
The split of `gtk` saves a lot of deps which are not usually installed on a server or chroot.
It is possible to make a smaller pkg without `gd`, `rsvg` and `webp` which seems good enough (renders svg and ps via core plugin, images and pdf via cairo), but probably not worth it.
Can't remove `pango` without disabling `cairo` as well; in this case one would want to keep `gd` for images. I wouldn't do this since the gd plugin is deprecated.
=> graphviz: separate x11 binaries and gtk plugin to reduce deps

srcpkgs/sbcl/template
=> sbcl: fix aarch64 sbcl binary checksum.

srcpkgs/fatsort/template
=> fatsort: update to 1.6.4.625.

srcpkgs/abiword/patches/fix-make-check.patch, srcpkgs/abiword/template
Configure flags --enable-goffice and --with-gtk3 are shown as unrecognized and not needed.
`libchamplain` pulls in clutter, which is kind of a bit much considering that, IMHO, the appeal of Abiword is that it doesn't come with the baggage of a complete office suite, so I made it a build option, enabled for now in the case that there are those who use the functionality.
=> abiword: update to 3.0.5

srcpkgs/pycharm-community/template
Also:
- remove the arm subdir from the bundled pty4j
- remove unneeded block rm commands.
=> pycharm-community: update to 2021.2.2.

srcpkgs/mercurial/template
=> mercurial: update to 5.9.1.

srcpkgs/latte-dock/template
This is a hotfix needed to fix a segfault between latte-dock 0.10.0 and Plasma Frameworks 5.86.
=> latte-dock: update to 0.10.2

srcpkgs/MultiMC/template
We are not allowed to use the MultiMC name, artwork or API endpoints for builds from source.
Marking this package as restricted so that we won't ship any binaries for it, users can either download binaries or build the package for personal use.
Also adding it to `removed-packages` so that anyone who has it installed will get it uninstalled instead of being stuck to the version they currently have installed.
https://github.com/void-linux/void-packages/issues/32950
=> MultiMC mark restricted

srcpkgs/discord-ptb/template
- Fix the dependencies (based on the discord package)
- Fix the EULA check (the terms webpage text was cut based on Discord's previous tagline)
- Fix a typo in the pixmap installation
- Update the EULA checksum
- Change the description based on the discord package
=> discord-ptb: unbreak and update to 0.0.26

srcpkgs/timelimit/template
timelimit is a tool to limit process run times which a few of my scripts, that were developed on other distributions, were using, and it's not very straightforward to implement the functionality otherwise.
=> New package: timelimit 1.9.2

srcpkgs/vivaldi/template
Added `xz` as dependency, so Vivaldi can install proprietary codecs to their directory with their `update-ffmpeg` script.
=> vivaldi: update to 4.2.2406.48

srcpkgs/tree/template
The `tree(1)` (or `/usr/share/man/man1/tree.1`) manpage is executable. This rebuild removes the executable permission.
=> tree: fix manpage permissions

srcpkgs/moreutils/template
`errno(1)` and some other manpages are broken. This PR fixes them.
=> moreutils: fix manpages

srcpkgs/LuaJIT/patches/aarch64-Fix-exit-stub-patching.patch, srcpkgs/LuaJIT/patches/e9af1abec542e6f9851ff2368e7f196b6382a44c.patch, srcpkgs/LuaJIT/template
without this e.g. luajit just crashes on native neovim builds and under
certain conditions also during runtime e.g. with nvim-cmp + nvim-cmp-lsp
=> LuaJIT: import upstream patches to fix crashes on aarch64 

srcpkgs/anope/template
I don't use anope anymore but I was asked if I could update it because of security fixes, I've bumped the version and confirmed it builds and runs but I don't have the setup anymore to test it more.
=> anope update to 2.0.10, orphan package

srcpkgs/arb/patches/450435a84a40acc1871cd84f1caf2ea47c11a18c.patch, srcpkgs/arb/template
I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
- Added a (temporary) patch to fix test on 32bit, already merged upstream, see https://github.com/fredrik-johansson/arb/issues/379
- conditional for musl not needed anymore after https://github.com/fredrik-johansson/arb/commit/c713d91280472d572fc43a64db43def73d650d11 (see https://github.com/fredrik-johansson/arb/pull/376)
=> arb: update to 2.21.0.

srcpkgs/vscode/template
=> vscode: update to 1.60.2

srcpkgs/discord-ptb/template
I recently updated and unbroke the discord-ptb package. It is an application I use everyday, which I now need this package for as I am moving to Void.
I am ready to take the responsibility of maintaining the package, and for the following reasons, I propose this change in maintainers:
- The current maintainer has only contributed to this package
- The current maintainer has [last contributed to the repository in early 2018](https://github.com/void-linux/void-packages/commits/master?author=abel@abelgraham.com) (before the current github repository)
- There is no github account associated with the address in the commits
- The package seems to break often, with long periods of time before fixes
(Metadata change)
=> discord-ptb: change the maintainer

srcpkgs/pulseaudio/template
`paprefs` relies on `org.freedesktop.pulseaudio.gschema.xml` being installed / compiled into `/usr/share/glib-2.0/schemas/` . 
```
(paprefs:8700): GLib-GIO-ERROR **: 13:13:47.730: Settings schema 'org.freedesktop.pulseaudio.module-group' is not installed
fish: Job 1, 'paprefs' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
=> pulseaudio: enable glib schema installation

srcpkgs/python3-networkx/template
=> python3-networkx: update to 2.6.3.

srcpkgs/OpenJK/files/OpenJK.desktop, srcpkgs/OpenJK/files/OpenJKMP.desktop, srcpkgs/OpenJK/files/OpenJO.desktop, srcpkgs/OpenJK/files/README.voidlinux, srcpkgs/OpenJK/files/openjk, srcpkgs/OpenJK/files/openjk_sp, srcpkgs/OpenJK/files/openjkded, srcpkgs/OpenJK/files/openjo, srcpkgs/OpenJK/patches/fix-sdl2-cross-compile.patch, srcpkgs/OpenJK/template
Possible Issue: OpenJK does not have tags or releases on GitHub, [and I don't think they will](https://github.com/JACoders/OpenJK/issues/1102). :/
I have built this successfully for i686 and x86_64.
https://github.com/JACoders/OpenJK
=> New package: OpenJK

srcpkgs/st/st-terminfo.REMOVE, srcpkgs/st/template
`st-terminfo.INSTALL` uses `tic`, but `st-terminfo` doesn't depend on `ncurses` (the provider of `tic`). This PR fixes that and it add some missing terminfo entries for removal to `st-terminfo.REMOVE`.
=> st: add ncurses to st-terminfo dependencies + minor fixes

srcpkgs/libsixel/patches/unistd.patch, srcpkgs/libsixel/template
=> libsixel: update to 1.10.3, switch upstream

srcpkgs/flintlib/template
Also: build without ntl when cross-compiling, since ntl is nocross.
=> flintlib: update to 2.8.1.

srcpkgs/ecm/template, srcpkgs/ecm/update
It seems gforge.inria.fr is down (for good?).
This project has moved to gitlab.inria.fr and the original tarball is available there.
=> ecm: update homepage and distfile url

srcpkgs/salt/template
=> salt: update to 3003.3.

srcpkgs/xfe/patches/POTFILES.skip.patch, srcpkgs/xfe/template
Also patch to ignore missing po file during check
I don't generally use this file manager, but I do sometimes put it on portable media installs to avoid installing a larger toolkit like gtk.  I can confirm that the new version runs and appears to behave as expected.
In case anyone does wonder, I changed the short description to be little more descriptive and so xlint doesn't complain.
=> xfe: update to 1.44

srcpkgs/gping/template, srcpkgs/gping/update
=> gping: update to 1.2.6

srcpkgs/stremio-shell/template
qt5-webengine needs to be in depends.
=> stremio-shell: fix dependencies.

srcpkgs/gifski/template
=> gifski: update to 1.5.1

srcpkgs/php/patches/php-enchant2.patch, srcpkgs/php/template
Motivation is #27710. I think this is the only thing stopping us from moving enchant to enchant2.
~~This still needs to be tested~~, I have briefly tested this, but any help in that area is still appreciated.
=> php: patch to use enchant2

srcpkgs/xcb-proto/patches/automake.patch, srcpkgs/xcb-proto/template
This fixes `xcb-proto.pc`, see #33559.
The patch is approved upstream, but not merged, yet.
=> xcb-proto: adjust to automake 1.16.4 changes

srcpkgs/opera/template
Also:
- change distfile to rpm (no need for do_extract() ).
@diogoleal
=> opera: update to 80.0.4170.72, adopt.

srcpkgs/nvimpager/template
Besides updating to 0.10.3, this fixes a problem that occurred for me recently (probably from the 0.10.2 update): the script is configured via the makefile, inserting the `PREFIX` to pass the right paths to nvim. But the `gnu-makefile` build style only passes `PREFIX` during `do_install`, not during `do_build`. As the first non-wildcard target in the makefile is `install`, I just skipped `do_build`.
=> nvimpager: update to 0.10.3

srcpkgs/kmod/template
This allows to compile kernel with `CONFIG_MODULE_COMPRESS_ZSTD=y` and load pre-compressed third-party modules.
=> kmod: add zstd module compression support

srcpkgs/qemu/template
Oops 🥴
addresses part of #33728
=> qemu: fix typo resulting in broken build when disabling Jack

srcpkgs/chroot-git/template
libcurl has been part of stage2 chroot from a long time ago due to:
binutils -> libdebuginfod -> libcurl
=> chroot-git: allow to fetch from http(s) remotes

srcpkgs/stress-ng/template
upstream moved to github.com and while at it updating to 0.13.06
=> stress-ng: update to 0.13.06

srcpkgs/firefox-esr/patches/fix-i686-ppc-musl.patch, srcpkgs/firefox/patches/fix-i686-ppc-musl.patch, srcpkgs/thunderbird/patches/fix-i686-ppc-musl.patch
Needed because of https://github.com/void-linux/void-packages/commit/7b4119df5cbc0cc37348164a10c88a32910009d8 
See also https://github.com/void-linux/void-packages/issues/33915
=> firefox, firefox-esr, thunderbird: fix patch whitespace

srcpkgs/gnome-tweaks/template
The newest version requires libhandy >= 1.0
=> gnome-tweaks: fix libhandy dependency

srcpkgs/hobbits/patches/python_version.patch, srcpkgs/hobbits/template
=> New package: hobbits-0.52.0

srcpkgs/g810-led/template
Installs udev rules so that the keyboard RGB profile is applied automatically.
=> g810-led: install udev rules

srcpkgs/rclone/template
=> rclone: update to 1.57.0

srcpkgs/python3-pikepdf/template
This is a major release since c++17 support is now a requirement and this is the first release to "officially" support python 3.10.
=> python3-pikepdf: update to 4.0.0.

common/shlibs, srcpkgs/libplacebo/template, srcpkgs/mpv/template, srcpkgs/vlc/template
Support for libplacebo older than v3.104.0 was dropped in https://github.com/mpv-player/mpv/commit/7c4465cefb27d4e0d07535d368febdf77b579566.
=> mpv: update to 0.34.0.

srcpkgs/fzf/template
This changes the installation path of additional files from `/usr/share/doc/fzf` to `usr/share/fzf`.
I'm not sure why they were originally installed in the `doc` folder, since these are not documentation files,
but if there is a reason, please feel free to close.
=> fzf: update installation path for completions and key-bindings

srcpkgs/vscode/patches/product.patch, srcpkgs/vscode/patches/ripgrep.patch, srcpkgs/vscode/template
=> vscode: update to 1.62.0

srcpkgs/procs/template
Procs prepend generated completion with following string if stdout
of `procs --completion` is redirected to file:
completion file is generated: ./procs.bash
=> procs: fix completion

srcpkgs/perl-SVG/template
Dependency for sage. I compiled sage-9.4 using this.
In fact, sage has a package named `perl_cpan_polymake_prereq` which checks a bunch of perl modules:
```
checking for perl module XML::Writer... ok
checking for perl module XML::LibXML... ok
checking for perl module XML::LibXSLT... ok
checking for perl module File::Slurp... ok
checking for perl module JSON... ok
checking for perl module SVG... ok
```
The first five are already present in void, the only one missing is `SVG`, but sage will install all 6 modules if only one is missing so there's extra credit for having this last one :-)
=> New package: perl-SVG-2.86

srcpkgs/pari-elldata-small, srcpkgs/pari-elldata/template, srcpkgs/pari-elldata/update, srcpkgs/pari-galdata/template, srcpkgs/pari-galdata/update, srcpkgs/pari-galpol-small, srcpkgs/pari-galpol/template, srcpkgs/pari-galpol/update, srcpkgs/pari-nflistdata/template, srcpkgs/pari-nflistdata/update, srcpkgs/pari-nftables/template, srcpkgs/pari-nftables/update, srcpkgs/pari-seadata-big/template, srcpkgs/pari-seadata-big/update, srcpkgs/pari-seadata-small, srcpkgs/pari-seadata/template, srcpkgs/pari-seadata/update, srcpkgs/pari/template
- update pari-elldata
- new pari package pari-nflistdata
- fix license
- change homepage and use https for downloads
- rename distfiles to include version in name
- ~keep the mtime from files in source~
- compress files for installed-size savings
- drop depends of packages on pari, add checkdepends of pari to packages (cf #29159, #32614)
- add a much smaller subpkg seadata-small as in upstream
- add update file for all packages
- skip slow post-install hooks for pari-galpol (14681 data files)
I'm also considering adding packages `pari-elldata-small` and `pari-galpol-small` with small versions of the databases that should be good for testing and small computations.
=> Update pari optional packages

srcpkgs/fwupd/template
drop dep on udisks2, add dep on dbus
drop -Dintrospection=true, which is default
built and checked on x86_64-musl
udisks2 brings in a lot of bloat, just to discover the ESP partition, but it actually does not do the job,
so it would be simpler to just let the user take care of that. (That's also what Alpine does btw.)
Notice even with udisks, I currently have to do
`mount -t efivarfs efivarfs /sys/firmware/efi/efivars`
otherwise fwupd does not find the bios to update.
Instead, dbus seems to be a needed dependency.
=> fwupd: change deps

.github/pull_request_template.md
Filling out the "Does it run and build successfully" section is
necessary only when the CI is skipped, but this is easy to miss.
Separate it from the rest of the text to make it clearer.
cc @ailiop-git
=> [RFC]: .github: improve the PR template

srcpkgs/m4ri/patches/m4ri-simd_cflags_in_tests.patch, srcpkgs/m4ri/template
@leahneukirchen we missed this, and now m4rie is not building without libgomp-devel.
I think the proper fix is to add libgomp-devel to depends for m4ri-devel, rather than add it to makedepends for m4rie, which is what this PR implements.
=> m4ri: add ${makedepends} to m4ri-devel depends

srcpkgs/bacon/template
=> bacon: update to 4.4.

srcpkgs/xorg-server/template
otherwise the build fails; it’s missing due to https://github.com/void-linux/void-packages/commit/32b3f0eab82a52fa37bef1a26a9a8d2afd6ccc92
@q66
=> xorg-server: needs libxshmfence-devel

srcpkgs/sylpheed/patches/fix-localedir.patch, srcpkgs/sylpheed/template
Current package has no locale files at all.
=> sylpheed: fix localedir

common/chroot-style/bwrap.sh
--dev-bind isn't necessary in any case it was being used for. We can
also use --ro-bind for /void-packages.
A possible future improvement would be to mount / read only during the
actual build.
=> common/chroot-style: clean up bwrap.sh.

srcpkgs/spandsp/template
upstream seems to be down, use fedora mirror (taken from the AUR pkgbuild)
also fix lint error
=> spandsp: fix distfiles

srcpkgs/ISOEnts/template
Right now installed files under `/usr/share/sgml/iso8879/` are only readable by root.
=> ISOEnts: install files with the right permissions

srcpkgs/dmd/template, srcpkgs/dtools/template
Also brings `dtools` up to date, as it is dependent on this version of `dmd`.
**Note:** even though the `dmd` template doesn't set `nocross`, the cross build is broken in the current void-packages version (and, by extension, this PR) due to a missing `libphobos2`, hence the draft status.
=> dmd: update to 2.098.0

srcpkgs/python3-jsonschema/template
- Change build style to python3-pep517 because of Julian/jsonschema@112c809e.
- Remove python3-six dependency since py2 support was dropped in Julian/jsonschema@027feac.
=> python3-jsonschema: update to 4.2.1.

srcpkgs/xiate/template
This fixes https://github.com/void-linux/void-packages/issues/3549;
upstream is no longer using config.h, so we can simplify pre_configure.
- [ X] I use the packages affected by the proposed changes on a regular basis and confirm this PR works for me
I had to set $version to v21.05 (notice the extra 'v') because the tarball extracts to xiate-v21.05;
please let me know if there's a cleaner way.
=> update xiate to new home and version

srcpkgs/gns3-gui/template, srcpkgs/gns3-server/patches/requirements.patch, srcpkgs/gns3-server/template
This change upgrades gns3-server and gns3-gui to 2.2.27.  It also updates requirements to work latest python3-Jinja2 package.
=> GNS3: upgrade to 2.2.27

srcpkgs/ulogd/files/ulogd.logrotate, srcpkgs/ulogd/template
The logrotate file is configured to rotate `/var/log/ulog.log` and `/var/log/ulog.pcap`, but the default `/etc/ulogd.conf` is configured for `/var/log/ulogd.log` and `/var/log/ulogd.pcap` so nothing will get rotated.
=> ulogd: move logs to subdir, update logrotate file, add conf_files

Manual.md
New text:
- `make_build_target` The build target. If `${build_style}` is set to `configure`, `gnu-configure` or `gnu-makefile`, this is the target passed to `${make_cmd}` in the build phase; when unset the default target is used.
The previous text incorrectly claims that it defaults to `all`
=> Manual.md: clarify default build target

common/environment/build-style/go.sh
Hasn't been necessary in Go for a long time [1], so we should take
advantage of that. For an example of the advantages, the 'micro' editor
went from 15MB to 11MB on disk.
[1] https://honnef.co/posts/2016/10/go-and-strip/
@the-maldridge
=> common/environment/build-style: remove nostrip from go.sh

srcpkgs/sympow/patches/sympow-2.023.6-no-pkgdatafilesbindir-warnings.patch, srcpkgs/sympow/template
Patch taken from sagemath, without it some sage doctests fail just
because of the extraneous output.
From the patch description:
The default "pkgdatafilesbindir" is something like /var/cache/sympow
that will never be writable by unprivileged users (and cannot safely
be made that way). There is already a fallback to $HOME in the code
that works perfectly well, but by default sympow emits a warning when
it realizes that it can't write to e.g. /var/cache/sympow on the first
try. Since that's completely expected, we hide the warnings behind an
additional level of verbosity (VERBOSE >= 2 instead of VERBOSE >= 1).
=> sympow: add a patch to avoid printing warnings

srcpkgs/mdnsd/template
mdnsd and mDNSResponder both provide /usr/bin/mdnsd, so they should be marked as conflicting.
Fixes #33762
=> mdnsd: Conflicts with mDNSResponder

srcpkgs/ETL/template, srcpkgs/synfig/patches/cflags-cxxflags.patch, srcpkgs/synfig/template, srcpkgs/synfigstudio/patches/cflags-cxxflags.patch, srcpkgs/synfigstudio/patches/fix-test-crash.patch, srcpkgs/synfigstudio/template
=> synfig + synfigstudio: update to 1.4.2

srcpkgs/libnftnl/template
pkgconfig complains about this otherwise.
See: /usr/lib/pkgconfig/libnftnl.pc
> Requires.private: libmnl
=> libnftnl: add libmnl as a dep to the devel subpkg

srcpkgs/valgrind/patches/str_tester.patch, srcpkgs/valgrind/patches/tc20_verifywrap_musl.patch, srcpkgs/valgrind/patches/test_statx.patch, srcpkgs/valgrind/patches/throw.patch, srcpkgs/valgrind/template
- aarch64-musl
This superseeds #30380.
To address remarks from the old PR:
- The musl.supp file is now upstream, no need to patch it in anymore.
- armv6 was not supported by valgrind in the past, I could not find any hint that this changed. If the code generation in valgrind asumes armv7 patching the configure script likely won't be enough.
=> valgrind: update to 3.18.1.

srcpkgs/vscode/template
=> vscode: update to 1.62.3

srcpkgs/pipe-viewer/template
Also add yt-dlp as a dependency.
Although not strictly required, it is more reliable than
the native parser and it is used by default if installed.
Supersedes #34062.
=> pipe-viewer: update to 0.1.7.

srcpkgs/python3-Flask-HTTPAuth/template
=> python3-Flask-HTTPAuth: update to 4.5.0, orphan.

srcpkgs/grabc/template
Old version number is from the tarball name, which appears to be a typo and should've been `1.0.1`, hence the revert. Let me know if this is the right approach to fix this.
~~xlint complains because the license changed from GPL2 to MIT, but there is no LICENSE or COPYING file to `vlicense`.~~
=> grabc: update to 1.0.2

srcpkgs/monitoring-plugins/template
net-snmp needs to be present for configure to include check_snmp
- aarch64-musl
- aarch64
=> monitoring-plugins: build with check_snmp

srcpkgs/soju/files/README.voidlinux, srcpkgs/soju/files/config, srcpkgs/soju/files/soju/run, srcpkgs/soju/template
=> New package: soju-0.3.0

srcpkgs/ecl/patches/fix-tests.patch, srcpkgs/ecl/template
The tests for ecl were not running as `make check` failed to find the binary (according to upstream one should install it before running tests).
OTOH, there's a bunch of tests that fail. Out of 18098 tests there are around 10 that fail on x86_64 and i686 (the number varies as some failures are kind of random. On x86_64-musl there are about 30 more failures but they all seem to be the same (something to do with acosh(-infinity))
I lack the energy to look at this and my lisp-fu is almost nil. I was hoping that everything would pass but... (what can we expect from a test suite that it's not easy to run...)
It's also the case that failures in the test suite will NOT stop make with an error, so packaging with -Q is not broken.
I'm not revbumping b/c this should not change anything at all in …
=> ecl: enable tests

srcpkgs/routinator/template
Also add /etc/routinator/routinator.conf to conf_files so it does not
get overwritten in future updates.
- aarch64-musl
- aarch64
=> routinator: update to 0.10.2

srcpkgs/rocksndiamonds/template
- I built this PR locally for these architectures :
- aarch64-musl
- armv7l
- armv6l-musl
I modified the build flags as the Makefile now only use BASE_PATH replacing both XX_GAME_DIR.
=> rocksndiamonds: update to 4.3.0.1

srcpkgs/lrcalc/patches/includes.patch, srcpkgs/lrcalc/template
In #34186 I forgot to `git add` a patch that is necessary for the include files to work properly.
=> lrcalc: add patch to fix includes

srcpkgs/poedit/template
Also:
- add pugixml-devel to makedepends.
=> poedit: update to 3.0.

srcpkgs/sympow/files/test, srcpkgs/sympow/files/test.out, srcpkgs/sympow/patches/first-try-without-messing-the-fpucw.patch, srcpkgs/sympow/template
It turns out doing that results in broken precision, and not doing it
fixes it.
A simple way to test it is to run
$ sympow -curve '[0,0,0,0,1]' -analrank
...
Analytic Rank is 0 : L-value 7.01091e-01
When broken this prints "7.01092e-01" instead.
The actual value computed to 128 bits with pari is:
$ echo 'elllseries(ellinit([0,0,0,0,1]),1)' | gp -q
0.70109105266272713058750953952514706773
so the glibc output is the correct one.
It seems to me that what is broken is not computing but printing, but
this is important since sagemath parses sympow output.
This affects sagemath doctests as in
$ sage -t src/sage/lfunctions/sympow.py
...
(3 failures)
After this commit, the doctest in question passes.
The corresponding doctest in sagemath passes on musl …
=> sympow: on musl, do not mess with fpu control word

srcpkgs/pcmanfm/template
Without lxmenu-data, pcmanfm won't show applications list within "Open with..." menu dialog.
=> pcmanfm: add lxmenu-data as dependency

srcpkgs/libpurple-facebook/template
More info here: https://www.reddit.com/r/voidlinux/comments/qxvs9z/purplefacebook/?utm_source=share&utm_medium=web2x&context=3
=> libpurple-facebook: update to 0.9.6.

srcpkgs/linbox/patches/remove-linboxsage-libs-from-pc.patch, srcpkgs/linbox/template
Current linbox.pc contains this line:
```
Libs: -L${libdir} -llinbox @LINBOXSAGE_LIBS@      
```
Which breaks programs trying to use linbox, for instance, this is necessary to use system linbox with sagemath.
=> linbox: fix broken linbox.pc

srcpkgs/autotiling/template
=> autotiling: update to 1.6

srcpkgs/handbrake/patches/fix-missing-x265-link-flag.patch, srcpkgs/handbrake/patches/remove-faac-dependency.patch, srcpkgs/handbrake/template
zimg-devel added as dependency for build to succeed.
template was changed in accordance.
Two patches needed to be rebased.
- I did some tests to determine functionality (transcoding .mkv files from h264 to h265)
=> handbrake: update to 1.4.2.

srcpkgs/delta/template
=> delta: update to 0.10.2

srcpkgs/font-sil-charis/template
Remove unzip hostdepend: bsdtar works just fine
=> font-sil-charis: update to 6.001

srcpkgs/tree-sitter/template
- I tested the changes in this PR: NO
=> tree-sitter: update to 0.20.1.

srcpkgs/aerc/template
The original upstream maintainer, Drew Devault, has stepped down and a
fork was created (with Drew's approval) under the same name. The fork
has patched in a large backlog of crashes and bug fixes and put out a
new version 0.6.0 recently. I think now that the aerc community has
consolidated on this fork it would be appropriate to update our package
to the new upstream.
More info about the fork and new maintainer can be found in this
discussion: https://lists.sr.ht/~sircmpwn/aerc/%3CCFBVJ3G1Y4YB.ZI6C02D0MS0S%40diabtop%3E
I built this PR locally for my native architecture, x86_64-libc
=> aerc: update to 0.6.0.

srcpkgs/go/template
Ping @the-maldridge
`VERSION` is installed to `/usr/lib/go` in other distros, [golds](https://go101.org/article/tool-golds.html) is borked without this file ¯\\\_(ツ)\_/¯
Feel free to include this changes in update to go1.17.4 if you prefer.
=> go: update URLs and install VERSION file

srcpkgs/dunst/template
Also:
* Enabled tests
* Added conf_files
* Set SYSCONFDIR to not default to /usr/etc
* Dunst doesn't require GTK3 anymore since quite some time so removed from makedepends
=> dunst: update to 1.7.2.

srcpkgs/nim/template
- I built this PR locally for my native architecture, (glibc)
- I cross-built it for a few things (aarch64 and arm all glibc)
I think it is about ready.
Old comments below this line.
---
I was mainly putting this up here to gather comments. For background, things which have changed between what is available in the repositories and 1.6.0:
- Nim no longer bundles fusion. It provides a koch command to nimble install it at a specific commit. It might be worth providing it as a separate package but maybe not worth it.
- Nim now uses csources_v1 instead of csources. This is now built with make. We used to pass --cpu to build.sh based on XBPS_TARGET_MACHINE. I removed this temporarily, I think it would have to be re-added setting the ucpu variable …
=> nim: update to 1.6.0, fix non-x86_64/i686 packages, improve template

srcpkgs/lighttpd/template
lighttpd: update to 1.4.63
use pcre2-devel instead of pcre-devel
- I tested the changes in this PR: **NO** (not on void-linux, but I have tested on other platforms)
=> lighttpd: update to 1.4.63

srcpkgs/gst-libav/template, srcpkgs/gst-omx/template, srcpkgs/gst-plugins-bad1/template, srcpkgs/gst-plugins-base1/template, srcpkgs/gst-plugins-good1/template, srcpkgs/gst-plugins-ugly1/template, srcpkgs/gst1-editing-services/template, srcpkgs/gst1-python3/template, srcpkgs/gstreamer-vaapi/template, srcpkgs/gstreamer1/template
Current `gst-plugins-base1` 1.18.4 fails to build right now; an update to 1.18.5 fixes this.
Not runtime-tested, yet.
=> gstreamer: update to 1.18.5

srcpkgs/lilypond-doc/template, srcpkgs/lilypond/template
The test on i686 fails like last time with
`.../color.scm:706:3: Wrong type argument in position 1 (expecting list of 3 or 4 numbers in [0.0,1.0]): -1.509384027e-8`
So I think we can ignore it. ;)
=> lilypond: update to 2.23.5

srcpkgs/python3-gobject/patches/restore_gtk_liststore_insert_with_valuesv_with_newer_gtk4.patch, srcpkgs/python3-gobject/template
* backport fix for GTK 4.1+ incompatibility
cherry-picked and slightly modified from #33337
=> python3-gobject: update to 3.42.0.

srcpkgs/linux5.15/patches/btusb-quirk-HCI_FLT_CLEAR_ALL.patch
The patch is taken verbatim from this particular comment:
https://gist.github.com/nevack/6b36b82d715dc025163d9e9124840a07#gistcomment-3818325
Note that there are several fake variants of this CSR dongle
(usb id 0a12:0001) that need different workarounds. The gist itself
mentions a workaround (force-suspend) that is already included in 5.15
and fixes some dongles but not mine.
The issue is also mentioned in kernel bugzilla at
https://bugzilla.kernel.org/show_bug.cgi?id=60824#c187
Starting at comment 187 there are several reports of dongles fixed by
that patch (or a variation / rediscovery of the workaround).
- I tested the changes in this PR: **YES** (I'm running 5.15.6 built with this PR on my main desktop)
NOTE: I didn't revbump since I don't think it's worth pushing an update for …
=> linux5.15: add patch to fix bluetooth dongle

srcpkgs/opensmtpd-extras/template
=> opensmtpd-extras: update to 6.7.1, orphan.

common/shlibs, srcpkgs/opensc/template
I have tested only under x86-glibc, the update is much needed for newer types of smart cards. I have successfully used the new version with older and newer cards.
=> opensc: update to 0.22.0

srcpkgs/element-desktop/patches/0001-Fixes-compilation-on-a-bunch-of-targets.patch, srcpkgs/element-desktop/template
- I built and used this PR locally for my native architecture, (x86_64-gnu)
Obsoletes #34382, this updates to a newer version than that PR.
Aside of the patching: We'll want to update before Monday, because there'll be a security release and the smaller the update on Monday is the less likely it'll be that something breaks then. I'd like to be prepared there :D
=> element-desktop: update to 1.9.6.

srcpkgs/libnice/template
this removes gssdp-igd from the dependencies of libnice, as gssdp will
switch to gtk4 with version 1.4.0. This will introduce a
new dependency loop which will be prevented by this commit:
gst-plugins-bad1-1.18.5_1 -> gtk4-4.4.0_2 -> gssdp-1.4.0.1_1
-> gupnp-igd-0.2.5_3 -> libnice-0.1.18_3 -> gst-plugins-bad1-1.18.5_1
-> ...
=> libnice: remove dep gssdp-igd

srcpkgs/python3-pycryptodomex/template
```
$ salt --versions | grep dome
pycryptodome: 3.12.0
```
Salt apply ran uneventfully.
=> python3-pycryptodomex: update to 3.12.0.

srcpkgs/qownnotes/template
=> qownnotes: update to 21.12.3

srcpkgs/1password/INSTALL, srcpkgs/1password/files/1password, srcpkgs/1password/template
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): YES
=> New package: 1password-8.4.1

srcpkgs/libdrm/template
wlroots master now requires `2.4.108` and the next wlroots release is just around the corner.
=> libdrm: update to 2.4.109.

srcpkgs/python3-mypy/template
=> python3-mypy: update to 0.920.

srcpkgs/haproxy/template
- I built this PR locally for my native architecture, (amd64-glibc)
=> haproxy: update to 2.4.9

srcpkgs/scummvm/template
Since this package replaces the residualvm package, those engines should be enabled in the SCUMMVM build.
=> scummvm: enable all engines

srcpkgs/miniflux/template
=> miniflux: update to 2.0.34.

srcpkgs/pango/template
=> pango: update to 1.50.2

srcpkgs/synapse/template
Installing them suddenly in target path triggered xbps bug
destroying previous configurations.
@paper42 @ericonr @freshprince
=> synapse: install example config files into examples dir

common/xbps-src/shutils/chroot.sh, etc/defaults.conf
Setting this variable will make xbps-src use an alternative mirror for remote repositories.
Using this variable one can change the remote repository for all architectures in a single setting and without the need to modify `etc/xbps.d/repos-remote*.conf`. This is much more convenient as it allows changing remote repos without a dirty worktree.
To use just add a line like the following to `etc/conf`:
XBPS_MIRROR=https://repo-us.voidlinux.org/
We also disable `00-repository-main.conf` for cross so we don't use the remote repo from the xbps package.
=> etc/conf: implement XBPS_MIRROR for remote repos

srcpkgs/sublime-text4/template
=> sublime-text4: update to version 4126

srcpkgs/toxcore/template
=> toxcore: update to 0.2.13.

srcpkgs/python3-crccheck/template
- I built this PR locally for my native architecture, x86_64, GLIBC
- aarch64-musl
- armv7l
- armv6l-musl
=> python3-crccheck: update to 1.1

srcpkgs/noto-fonts-emoji/template
This adds support for emojis from Unicode 14.0, like… a [JAR] 🫙, and [melting face] 🫠!
[JAR]: https://emojipedia.org/jar/
[melting face]: https://emojipedia.org/melting-face/
More new emojis can be found here: https://emojipedia.org/emoji-14.0/
=> noto-fonts-emoji: update to 2.034.

srcpkgs/python3-injector/template
This will fix an [issue with gwe not working on python 3.10](https://gitlab.com/leinardi/gwe/-/issues/162).
=> python3-injector: update to 0.19.0

srcpkgs/cgrep/template
- I tested the changes in this PR: *briefly*
=> cgrep: update to 6.7.1.

srcpkgs/mc/patches/mc-mksh-subshell-v2.patch, srcpkgs/mc/template
fixes CVE-2021-36370:
> sftpfs vfs: CVE-2021-36370: server fingerprint isn't verified
=> mc: update to 4.8.27.

srcpkgs/LibreCAD/template
Solved #32497
https://user-images.githubusercontent.com/45872139/147313649-5c5f7710-8f24-4e88-8f6b-b0d7e60a6aee.mp4
=> LibreCAD: fix missing built-in plugins menu

srcpkgs/linux5.15/patches/fix-lenovo7i-sound.patch
This issue was fixed for some devices in:
https://bugzilla.kernel.org/show_bug.cgi?id=208555
~~However, the subsystem_id for my machine is not in the list, so this just adds it temporarily until it can hopefully be resolved upstream.~~
The patch has since been merged upstream.
=> linux5.15: Add speaker fixup for some Yoga 15ITL5 devices

srcpkgs/dolphin-emu/template
the version detected when not building from a git repository is not
precise enough to allow netplay to work
I only tested if the version is embedded correctly, not if netplay works, @Hnaguski or @RhymeJob, could you test this?
Closes: #34691
=> dolphin-emu: embed correct version

srcpkgs/pan/template
Also:
- remove gtk+-devel from makedepends (not needed now).
=> pan: update to 0.149.

srcpkgs/python3-texttable/template
This is a dependency of sagemath, which requires `>= 1.6.3`
=> python3-texttable: update to 1.6.4.

srcpkgs/caddy/template
Without mime-types installed Caddy silently omits certain headers,
especially Content-Type.
=> caddy: add missing dependency

srcpkgs/lollypop/template
- I built this PR locally for my native architecture
- `Void 5.10.87-xanmod1_1 x86_64 AuthenticAMD notuptodate hold rrrmFFFFFFFF`
=> lollypop: update to 1.4.26

srcpkgs/nvidia/template
now properly linked:
```
masterdir/destdir/nvidia-libs-470.94
└── usr
└── lib
...
├── libnvoptix.so -> libnvoptix.so.470.94
├── libnvoptix.so.1 -> libnvoptix.so.470.94
├── libnvoptix.so.470.94
...
```
=> nvidia: fix linking libnvoptix.so and libnvoptix.so.1

srcpkgs/monitoring-plugins/template
also add bind-utils to hostmakedepends as nslookup is needed to build check_dns
- aarch64-musl
- aarch64
- armv6l-musl
=> monitoring-plugins: update to 2.3.1

srcpkgs/imv/template
Update and change the repo as imv moved to [sr.ht]
- armv7l
[sr.ht]: https://sr.ht/~exec64/imv/
=> imv: update to 4.3.1.

srcpkgs/libsigrokdecode/patches/python-3.10.patch, srcpkgs/libsigrokdecode/template
- I built this PR locally for my native architecture, x86_64-gnu
=> libsigrokdecode: fix python3.10 dependency

srcpkgs/tealdeer/template
---
According to the [changelog](https://github.com/dbrgn/tealdeer/blob/main/CHANGELOG.md), tealdeer switched to rustls for the 1.5.0 release. As such, the archs had to be restricted to those supported by rustls/ring.
=> tealdeer: update to 1.5.0

srcpkgs/vault/template
Dunno why I missed this before, but:
```
$ sudo -u _vault vault server -config=/etc/vault
Password:
error loading configuration from /etc/vault: open /etc/vault: permission denied
$ sudo chown _vault:_vault /etc/vault
$ sudo -u _vault vault server -config=/etc/vault
==> Vault server configuration:
<...>
```
=> vault: chown config dir to service user

srcpkgs/musikcube/template
=> musikcube: update to 0.96.10

srcpkgs/sbt/template
This is the latest release of `sbt` and the first to address recent log4j vulnerabilities.
- https://github.com/void-linux/void-packages/issues/34534
- https://github.com/sbt/sbt/releases/tag/v1.6.1
- I tested the changes in this PR: ~~briefly~~ **yes**
~~(Will try to do more testing later. Got some issue with libgomp when I tried updating my xbps-src bootstrap)~~
=> sbt: update to 1.6.1

Manual.md, common/hooks/post-install/06-strip-and-debug-pkgs.sh
The option `nostrip_files` takes a filename without path, in contrast to
option `nopie_files` which takes only full path.
This is inconvenient in a case where there are two binaries with the
same name and only one must be stripped.
Case in point: maxima contains executables
/usr/lib/maxima/5.45.1/binary-ecl/maxima
/usr/lib/maxima/5.45.1/binary-sbcl/maxima
The second one breaks if stripped, but the first one is ok to strip (desirable: 59M -> 13M).
See: https://github.com/void-linux/void-packages/issues/34861#issuecomment-1006197772
This commit makes it so that `nostrip_files` can take either the
filename or the full path.
=> nostrip_files: allow full path

srcpkgs/inkscape/template
need to add `python3-appdirs` to run menu `Extensions > Manage Extension` properly.
a warning like this will appear:
```
from appdirs import user_cache_dir
ModuleNotFoundError: No module named 'appdirs'
```
after installing `python3-appdirs`:
cc @ericonr
=> inkscape: add missing dependency

srcpkgs/logrotate/template
```
$ ./xbps-src pkg logrotate
$ xi !$
$ sudo logrotate -dv /etc/logrotate.conf
```
The above sequence of commands ran without error.
The [changelog](https://github.com/logrotate/logrotate/releases/tag/3.19.0) consists mostly of security fixes, the most interesting one being 427.
=> logrotate: update to 3.19.0.

srcpkgs/perl-MRO-Compat/template
=> perl-MRO-Compat: update to 0.15

srcpkgs/sbcl/template
Add the GNU Info manual for SBCL and its accompanying ASDF manual.
This package has an issue: it will install the manual with the `sbcl` package as well. This is due to the fact that the `do_install` function of the `sbcl` package runs `install.sh`, which will install the manual if it is available. There does not seem to be a way of suppressing that behaviour.
I tried to define a custom `do_build` function inside the subpackage, but it appears that it is not being run: 
```sh
sbcl-doc_package() {
short_desc+=" - documentation"
do_build() {
(cd ./doc/manual; make info)
}
pkg_install() {
vmkdir 'usr/share/info'
vcopy "doc/manual/*.info*" 'usr/share/info'
}
}
```
- This new package conforms to the [quality …
=> New package: sbcl-doc-2.1.11

common/travis/fetch_upstream.sh
As of today, everything fails on CI with:
```
Run common/travis/fetch_upstream.sh
Fetching upstream...
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Error: Process completed with exit code 128.
```
Switching `git://` to `https://` should fix this.
=> Fix CI since github no longer accepts git:// protocol

srcpkgs/ardour/template, srcpkgs/ci20-uboot/template, srcpkgs/darch/template, srcpkgs/rdis-git/template
As of today github no longer accepts `git://` so we switch templates that use git clone from `git://github.com/` to `https://github.com`.
=> Switch templates from git:// to https://

srcpkgs/ckb-next/template
As pipewire gets more common, it makes no sense to hard-depend on
pulseaudio anymore and it was a bad idea anyway.
=> ckb-next: get rid of pulseaudio dependency.

common/shlibs, srcpkgs/Clight/template, srcpkgs/bogofilter/template, srcpkgs/calligra/template, srcpkgs/dieharder/template, srcpkgs/enblend-enfuse/template, srcpkgs/giac/template, srcpkgs/gnuradio/patches/596c6495f3bdf579dae0c26531a16f6adcc7fb2f.patch, srcpkgs/gnuradio/patches/aa4b15d0b26b3c72fab736bcd28a67ab9d1404b7.patch, srcpkgs/gnuradio/patches/f259befbbe54e55fc4994899e92bcf5bf462fa2f.patch, srcpkgs/gnuradio/patches/skip-test-that-hangs-on-32bit.patch, srcpkgs/gnuradio/template, srcpkgs/gsl/template, srcpkgs/guvcview/template, srcpkgs/igt-gpu-tools/template, srcpkgs/inkscape/template, srcpkgs/ipe/template, srcpkgs/krita/template, srcpkgs/siril/template
The main change is a soname bump that apparently should have been done on 2.7.
This requires several revbumps. I took the chance to:
- giac: update to 1.7.0.43 (minor update, no surprises)
- dieharder: fix URL, since it was failing with a certificate error
- gnuradio: add missing checkdepends and patch from upstream so `do_check()` succeeds
- guvcview and siril: trivial fixes so `do_check()` succeeds
- krita: disable tests since they are broken (70 failures)
I tested pkg -Q on x86_64 and all passes with these fixes.
=> gsl: update to 2.7.1, adopt.

srcpkgs/lazydocker/template
=> lazydocker: update to 0.13.

srcpkgs/j4-dmenu-desktop/template
Since there is more than one dmenu implementation (e.g. bemenu for
Wayland) it makes no sense to depend on dmenu here.
=> j4-dmenu-desktop: remove dmenu dependency

srcpkgs/xfce4-panel/template
The Status Tray plugin then works properly for applications using the
StatusNotifier API. 
Fixes J-Lentz/iwgtk#21
Further background: https://forum.xfce.org/viewtopic.php?pid=65399#p65399
=> xfce4-panel: enable StatusNotifier support.

srcpkgs/Field3D/template
From the [homepage](https://github.com/imageworks/Field3D/wiki/Field3D-Home):
> # License
>  Field3D is distributed under the New BSD License.
Looking at the COPYING file, it's clauses (distribute notice in source, in binary, and don't use their name to promote stuff) make it a BSD-3-Clause license.
=> Field3D: fix license

srcpkgs/racket/template
* remove nocross
* expound precise arch support (based on Racket's Chez Scheme support)
* remove unneeded musl deps
* put documentation behind a switch (builds fine, takes too long for CI)
- aarch64-musl - native and cross
- x86_64-musl - native
Racket's architecture support is limited only by Chez Scheme. The Chez Scheme it uses supports all the architectures we do except MIPS and PowerPC64. However, when trying to cross-compile for PowerPC 32-bit musl, I found that an absolute boat load of dependencies had to be compiled first. This would make CI take way too long, so I've simply omitted all PowerPC platforms. It wasn't supported before anyway, so this is still progress.
I don't actually know …
=> racket: re-enable cross-compilation

srcpkgs/ristretto/template
Also add glib-devel to hostmakedepends (for gdbus-codegen).
=> ristretto: update to 0.12.2.

srcpkgs/starship/template
=> starship: update to 1.2.1

srcpkgs/github-cli/template, srcpkgs/github-cli/update
=> github-cli: update to 2.4.0.

srcpkgs/apache-jmeter/template
This update includes a fix for the log4j vulnerability.
- I tested the changes in this PR:  briefly 
Apache Jmeter starts successfully after package installation.
=> apache-jmeter: update to 5.4.3.

srcpkgs/python3-cvxopt/template
Dependency of sagemath.
Testsuite works and passes on all nocross arches. Using this package with sagemath seems to work ok.
Cc: @dkwo @leahneukirchen
=> New package: python3-cvxopt-1.2.7

srcpkgs/python3-memory_allocator/template
Dependency of sagemath.
Testsuite works and passes on all nocross arches. Using this package with sagemath seems to work ok.
Cc: @dkwo @leahneukirchen
=> New package: python3-memory_allocator-0.1.2

srcpkgs/python3-cypari2/template, srcpkgs/python3-cysignals/patches/fix-write.patch, srcpkgs/python3-cysignals/template, srcpkgs/python3-fpylll/template, srcpkgs/python3-pplpy/template, srcpkgs/python3-primecountpy/template
Dependencies of sagemath.
One PR since they all use cysignals; this also makes everything nocross. All testsuites work and pass.
I tested these with sagemath and everything seems to work ok.
Cc: @dkwo @leahneukirchen
=> New packages: python3-cysignals-1.11.2, python3-cypari2-2.1.2, python3-pplpy-0.8.7, python3-fpylll-0.5.6, python3-primecountpy-0.1.0

srcpkgs/blueman/template
=> blueman: add libappindicator dependency for blueman-applet.

srcpkgs/fail2ban/patches/python3.10.patch, srcpkgs/fail2ban/template
This minor change fixes fail2ban against python 3.10.
- I built this PR locally for my native architecture, x86-glibc.
=> fail2ban: add patch for python 3.10.

srcpkgs/apache-jmeter/template
This template no longer needs gradle as a dependency, but I failed to remove it when I updated it.
=> apache-jmeter: remove gradle dependency

srcpkgs/shared-mime-info/patches/meson-0.60.patch, srcpkgs/shared-mime-info/template
* remove build dependency on intltool and itstool
* add changelog
* enable parallel build
=> shared-mime-info: fix build with meson 0.60

srcpkgs/mumble/template
=> mumble: update to 1.4.230.

srcpkgs/flameshot/template
=> flameshot: update to 11.0.0

srcpkgs/bash-completion/patches/complete-xbps.patch, srcpkgs/bash-completion/template
Backported from upstream https://github.com/scop/bash-completion/pull/688
=> bash-completion: complete tar with xbps files

srcpkgs/jansson/patches/fix-run-suites.patch, srcpkgs/jansson/template
=> jansson: update to 2.14.

srcpkgs/mtr/template
Switched to gtk3 which was available since 0.94
=> mtr: update to 0.95.

srcpkgs/capstone-python, srcpkgs/capstone/template, srcpkgs/removed-packages/template
* capstone-python3: add missing python3 dependency
=> capstone-python: remove package

srcpkgs/cryptsetup/template
=> cryptsetup: update to 2.4.3.

srcpkgs/nbd/template
- aarch64-musl
- armv7l
- armv6l-musl
bison required, so I added it in `hostmakedepends` :
```
checking if bison is the parser generator... no
configure: error: bison is required
```
=> nbd: update to 3.23

srcpkgs/ghc/patches/Disable-unboxed-arrays.patch, srcpkgs/ghc/patches/ppc64-be-elfv2.patch, srcpkgs/ghc/patches/sphinx-unicode.patch
Add patch Disable-unboxed-arrays.patch for ghc issue #16998
https://gitlab.haskell.org/ghc/ghc/-/issues/16998.
This patch has been accepted upstream as
https://github.com/haskell/containers/commit/f5a511f1ff2cf16e710342948792cb8d7576e27c
Refresh patches ppc64-be-elfv2.patch, sphinx-unicode.patch so they apply cleanly again.
- I built this PR locally for my native architecture, (ppc64-glibc)
@q66 perhaps you would like to test this in your PowerPC environment?
=> ghc: fix build on big-endian architectures

srcpkgs/rpi-kernel/template, srcpkgs/rpi2-kernel/template, srcpkgs/rpi3-kernel/template, srcpkgs/rpi4-kernel/template
This enables support for the Raspberry Pi Zero 2 W (adds `/boot/bcm2710-rpi-zero-2.dtb`) as well as brings the kernels up to the latest stable merge commit on [raspberrypi/linux @ rpi-5.10.y](https://github.com/raspberrypi/linux/commit/1ef86d0084b5fcc6910f8e9aa9a6232457444e92).
- I tested the changes in this PR: **NO** (I'd like help here, I don't own any rpis)
[ci skip] [since everything already built successfully](https://github.com/void-linux/void-packages/actions/runs/1674011782)
=> rpi*-kernel: update to 5.10.92.

srcpkgs/nerdctl/template
Almost completely untested, mostly just pushed at the moment for the
CI run.
=> New package: nerdctl-0.16.1.

srcpkgs/sage-data-conway_polynomials/update, srcpkgs/sage-data-elliptic_curves/update
Two of these packages are picking up incorrect versions from an auxiliary site. This fixes it. No revbump necessary.
=> sage-data-*: fix update files

srcpkgs/nauty/template
The package currently shipped in void gives me illegal instructions in a
nehalem cpu.
This commit fixes the issue by disabling native compilation unless a build
option is given; also disable popcnt which, although available on nehalem, is
not available in baseline x86_64.
An easy way to spot the issue is to run something like:
```
$ geng 2
>A geng -d0D1 n=2 e=0-1
Illegal instruction
```
I compiled with `./xbps-src build nauty` on a cascade lake cpu, then run `./xbps-src check nauty` on a nehalem cpu. This breaks before the present PR, and works ok after.
I also tested sagemath: previously I was getting a lot of doctest failures which are now fixed.
Cc: @leahneukirchen please merge this before sagemath.
=> nauty: disable native code (illegal instructions)

srcpkgs/avidemux/template
By default, avidemux has used `org.avidux.avidux.desktop`. So, I try to delete `avidemux.desktop` because it could not be executed.
```
➜  ~ xbps-query --regex -Rf avidemux | grep desktop
/usr/share/applications/avidemux.desktop
/usr/share/applications/org.avidemux.Avidemux.desktop
```
=> avidemux: remove duplicate .desktop file

srcpkgs/abootimg/patches/no-initrd.patch, srcpkgs/abootimg/template
This makes abootimg usable for newer devices which can potentially have no ramdisk starting with Android 7.
Additionally fixes building the package from source.
=> abootimg: add no initrd patch

srcpkgs/xorg-server/patches/present-Check-for-NULL-to-prevent-crash.patch, srcpkgs/xorg-server/template
see:
- https://github.com/mate-desktop/mate-desktop/issues/505
- https://gitlab.freedesktop.org/xorg/xserver/-/issues/1275
=> xorg-server: fix MATE crash with nvidia

srcpkgs/mkvtoolnix/template
need mediainfo to run properly.
=> mkvtoolnix-gui: add mediainfo dependency

srcpkgs/retroarch/template
- Upstream dropped support for miniupnpc in favor of a built-in UPnP implementation
- Added libdecor dependency for Wayland
=> retroarch: update to 1.10.0

srcpkgs/gnupg/template
New LTS release : https://lists.gnupg.org/pipermail/gnupg-announce/2021q4/000467.html
=> gnupg: update to 2.2.34

srcpkgs/xkeyboard-config/template
Sorry, I missed the locales part @leahneukirchen
I added intltool again. I thought it was part of the autotools build system so I removed it... :/
=> xkeyboard-config: use intltool again.

srcpkgs/wine/template
This PR adds the `xshm` build option to control support for the X Shared Memory Extension (Xshm).
The reason for this change is that I run Wine in an LXD container that doesn't have access to the hosts shared memory (`/dev/shm`). Wine will print the error message
```
X Error of failed request:  BadValue (integer parameter out of range for operation)
Major opcode of failed request:  130 (MIT-SHM)
Minor opcode of failed request:  3 (X_ShmPutImage)
Value in failed request:  0xb40
Serial number of failed request:  535
Current serial number in output stream:  539
```
which results in corrupted graphics, making Wine applications unusable.
To work around this issue I disabled the Xshm extension on the host, but this can result in performance issues. The …
=> wine: add xshm build option

srcpkgs/topgrade/template
Version bump, + we're shipping the man page now
=> topgrade: update to 8.2.0.

srcpkgs/openocd/patches/libusb-1.0.25-segfault.patch, srcpkgs/openocd/template
See: https://github.com/libusb/libusb/issues/928
=> openocd: fix segfault with ST-Link and libusb-1.0.25

srcpkgs/libpwquality/template
This fixes an issue in which seahorse could not determine the strength of a password:
```
/usr/share/cracklib/pw_dict.pwd: No such file or directory
```
=> libpwquality: depend on cracklib

srcpkgs/syncthing-gtk/template
cc @paper42 
The new debian version scheme did throw errors like
```
/usr/lib/python3.10/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: v0.9.4.4-ds-git20220108-9023143f8b93 is an invalid version and will not be supported in a future release
```
This PR restores the old versioning scheme by adding the the following precautions:
* Users on `0.9.4.4` get upgraded to this version due to revision (last in this scheme was 3)
* Users on `0.9.4.4+ds+git20220108+9023143f8b93` get reverted to the old versioning scheme but on this revision
On top of that I added some `checkdepends` to make the checks succeed atleast to a certain point. I'm totally unsure why this wasn't an issue in the past, did anything change there? …
=> syncthing-gtk: restore sane versioning, fix tests

srcpkgs/webhook/files/hooks.json, srcpkgs/webhook/files/webhook/conf, srcpkgs/webhook/files/webhook/log/run, srcpkgs/webhook/files/webhook/run, srcpkgs/webhook/template
=> New package: webhook-2.8.0

srcpkgs/python3-psutil/template
=> python3-psutil: update to 5.9.0.

srcpkgs/tor/template
musl tests already failed in the old versions, shouldn't be a blocker. @ericonr ?
=> tor: update to 0.4.6.10.

common/shlibs, srcpkgs/intel-gmmlib/template, srcpkgs/intel-media-driver/template
- Revert "intel-media-driver: update to 22.1.1"
- Revert "intel-gmmlib: update to 22.0.1"
This works around a problem with firefox which crashes with the following message:
```
libva info: VA-API version 1.13.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_13
readlink -errno 13
```
=> Revert intel-media-driver

srcpkgs/google-chrome/template
I changed q66's package to replace @vscode/ripgrep to a far simpler version that only exposes the correct path and thus should never need to change and also removes the requirement to copy over files.
=> google-chrome: update to 98.0.4758.102

srcpkgs/mobile-config-firefox/template
This currently makes sense of the Firefox UI on phone-sized (e.g. 5.5") displays.
Supersedes #29131.
> 
=> New package: mobile-config-firefox-3.0.0

srcpkgs/docker-buildx/template
I had to use this command at work and it simply didn't exist. I had previously used it on Arch and didn't really know why it wasn't available on Void as well.
It happens that this command is a Docker CLI plugin, and comes bundled with Docker when distributed via DEBs or RPMs, but Arch also packages it along with their Docker package.
In my opinion, it makes more sense to package this just like Docker Compose (which since `v2` is also a Docker CLI plugin), that is, as a separate package, easy to install, and which will work out of the box once installed.
P.S.: I based this template off `docker-compose`'s.
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements) …
=> New package: docker-buildx-0.7.1

srcpkgs/libdrm/template
=> libdrm: update to 2.4.110.

srcpkgs/man-pages/template
The template file renames `rand.3` and `err.3` to `glibc-rand.3` and `glibc-err.3` to resolve conflict with openssl manpages, but it doesn't fix manpages linking to the old version. These manpages (`warnx(3)`, `srand(3)` ...) then won't know where the manpages are. This PR redirects them to the renamed version.
=> man-pages: fix links to moved manpages

srcpkgs/unrar/template
=> unrar: update to 6.1.5.

common/build-style/cmake.sh
Normally, we can add them into configure_args directly.
However, if we need to link with 2 or more libaries (e.g. -latomic
and -lexecinfo on armv6-musl), we have noway to do it properly:
- configure_args will be splited on whitespace
- cmake denies to recognise CMAKE_*_STANDARD_LIBRARIES as a list,
hence denies to split on semicolon (";")
Let's pass LIBS as CMAKE_*_STANDARD_LIBRARIES instead.
=> build-style/cmake: pass LIBS as CMAKE_*_STANDARD_LIBRARIES

srcpkgs/steam/template
This feature requires `lsof` to be installed, the following was printed when opening the context menu of someone in the friends list:
```
sh: 1: lsof: not found
```
=> steam: fix joining friends' games.

srcpkgs/flac/template
Checks pass locally for x86_64, x86_64-musl and i686.
=> flac: update to 1.3.4.

srcpkgs/kdepim-addons/template, srcpkgs/kitinerary/template, srcpkgs/kpkpass/template
=> kpkpass, kitinerary, kdepim-addons: update to 21.12.2.

srcpkgs/OTPClient/template, srcpkgs/libbaseencode/template, srcpkgs/libcotp/template
supersedes https://github.com/void-linux/void-packages/pull/35503
=> Update OTPClient, libcotp and libbaseencode

srcpkgs/mininet/template
the additional deps are based on what upstream's install scripts and other distros require.
=> mininet: update to 2.3.0, move to python 3, adopt.

srcpkgs/python3-frozendict/template, srcpkgs/python3-matrix-common/template, srcpkgs/python3-phonenumbers/template, srcpkgs/python3-saml2/template, srcpkgs/python3-treq/template, srcpkgs/synapse/template
- I tested the changes in this PR: **YES** (running on 1.53.0rc1 for 7 days)
=> synapse: update to 1.53.0.

srcpkgs/xf86-input-libinput/template
=> xf86-input-libinput: update to 1.2.1.

srcpkgs/python3-vint/template
Switch distfiles to Github source since it includes the tests.
Fixes error about missing 'PyYAML~=3.11' when running `vint`.
=> python3-vint: update to 0.3.21.

common/shlibs, srcpkgs/mtxclient/template, srcpkgs/nheko/template
quoting upstream:
> This release fixes a crash in Nheko if the Matrix server is updated to support the APIs v1.1 and up
- I built this PR locally for my native architecture, (x86_64 musl)
- aarch64-musl
- armv7l
- armv6l-musl
=> mtxclient: update to 0.6.2 for nheko crash

srcpkgs/fifengine/patches/remove_deprecated_getchildren.patch, srcpkgs/fifengine/template, srcpkgs/unknown-horizons/patches/collections_Iterable.patch, srcpkgs/unknown-horizons/patches/py39.patch, srcpkgs/unknown-horizons/template
=> fifengine + unknown-horizons: several patches from upstreams for Python 3.9+.

srcpkgs/bat/template
=> bat: update to 0.20.0.

srcpkgs/jamulus/template
```
libxml2-2.9.10_5: broken, unresolvable shlib `libicudata.so.69'
libxml2-2.9.10_5: broken, unresolvable shlib `libicui18n.so.69'
libharfbuzz-2.9.1_1: broken, unresolvable shlib `libicuuc.so.69'
libxml2-2.9.10_5: broken, unresolvable shlib `libicuuc.so.69'
Transaction aborted due to unresolved shlibs.
```
Build currently failing due to unresolved shlibs. According to the [docs](https://docs.voidlinux.org/xbps/troubleshooting/common-issues.html):
> If you get an error message saying:
>
> `Transaction aborted due to unresolved shlibs`
>
> the repositories are in the staging state, which can happen due to large builds. The solution is to wait for the builds to finish. You can view the builds' progress in the [Buildbot's Waterfall …
=> jamulus: update to 3.8.2

srcpkgs/python3-prompt_toolkit/patches/dont-handle-sigint.patch, srcpkgs/python3-prompt_toolkit/template
Fixes #35712
See also: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1576
=> python3-prompt_toolkit: don't handle sigint

srcpkgs/libgsm/template
Old distfiles are apparently not deleted, so I changed them to upstream.
I also cleaned up the template a little bit and do the install using the Makefile target instead of doing this manually.
Until now, libgsm-devel contained unnecessary header files, because all header files were just copied over.
Also includes manual pages now, which were not installed before.
=> libgsm: update to 1.0.19.

srcpkgs/tree-sitter/template
=> tree-sitter: fix cross

srcpkgs/python3-lxml/template
- I tested the changes in this PR: **YES** (tested with synapse)
Long list of dependent packages for this one:
=> python3-lxml: update to 4.8.0.

srcpkgs/python-openssl/template, srcpkgs/python3-openssl, srcpkgs/python3-openssl/template, srcpkgs/python3-openssl/update
- I tested the changes in this PR: **YES** (tested with synapse)
I had to do the same thing I did for Twisted--drop the python3 subpackage from python-openssl since versions >21.0.0 don't support python2 anymore.
Dependents to test:
=> python3-openssl: update to 22.0.0.

srcpkgs/freerdp/template
closes #35887
Feel free to test it, @hiltjo.
=> freerdp: update to 2.6.0.

srcpkgs/google-chrome/template
Google Chrome would crash without gtk+3.
=> google-chrome: add missing gtk+3 dependency

srcpkgs/zellij/template
=> New package: zellij-0.25.0

srcpkgs/spotify-qt/template
While the application does run without this dependency, a GUI client without icons is barely usable.
=> spotify-qt: add qt5-svg dependency

srcpkgs/openshot/template
It is not needed.
https://github.com/OpenShot/openshot-qt/issues/389
=> openshot: remove 'mlt' dependency.

srcpkgs/blueman/INSTALL.msg, srcpkgs/blueman/template
=> blueman: update to 2.2.4.

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 5.34

srcpkgs/OpenLP/patches/no_pytest_runner.patch, srcpkgs/OpenLP/patches/py310_applocation.patch, srcpkgs/OpenLP/template, srcpkgs/python3-Flask-Cors/template, srcpkgs/python3-QtAwesome/template, srcpkgs/python3-pymediainfo/template, srcpkgs/python3-vlc/template
Current version in repo is broken due to what I'm suspecting are just deprecation errors, and is also very old (March 31, 2017). This version is [technically an RC for 3.0](https://openlp.org/blog/2022/01/18/new-release-openlp-30-rc1-294-mighty-malachi) but since it works and the current version in repo doesn't, I figured I would open a PR.
=> OpenLP: update to 2.9.4.

srcpkgs/gitea/files/gitea/run, srcpkgs/gitea/template
- I built this PR locally for my native architecture, (X64-LIBC)
=> gitea: update to 1.16.3

common/shlibs, srcpkgs/fossil/patches/cross.patch, srcpkgs/fossil/template, srcpkgs/sqlite/template
Also remove -DSQLITE_ENABLE_JSON1 as JSON is now on by default.
https://sqlite.org/releaselog/3_38_0.html
=> sqlite: update to 3.38.0, fossil: update to 2.18.

srcpkgs/libjpeg-turbo/template
=> libjpeg-turbo: update to 2.1.3.

srcpkgs/hstr/template
=> hstr: update to 2.5

srcpkgs/dbus-glib/template
Additionally fix `xlint` and tests.
=> dbus-glib: update to 0.112.

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 5.35

srcpkgs/xterm/template
ci fails because of some stupid ratelimiting on xterm servers. Built succesfully for all platforms on my fork.
=> xterm: update to 372.

srcpkgs/execline/template, srcpkgs/s6-portable-utils/template, srcpkgs/s6/template, srcpkgs/skalibs/template
=> Skarnet update.

srcpkgs/tinyssh/template
This release contains a fix for
https://github.com/janmojzis/tinyssh/issues/63
=> tinyssh: update to 20220305.

srcpkgs/nbd/template
- aarch64-musl
- armv7l
- armv6l-musl
3.24 released : https://lists.debian.org/nbd/2022/03/msg00008.html
Fixing two security issues : CVE-2022-26495 / CVE-2022-26496
=> nbd: update to 3.24

srcpkgs/runit-void/files/os-release, srcpkgs/runit-void/template
- - -
This PR aims to bring the `os-release` file up to the same quality and standards as in other distributions.
There was a prior attempt to update `os-release` (#12160), but that included some fairly unusual departures; here I have made a point to change as little as possible while still providing useful and expected functionality.
I did leave the `DISTRIB_ID` variable intact, despite it not being part of the specification. Hopefully this will prevent any compatibility issues.
- - -
Special interest pings (for feedback):
@the-maldridge for Ansible compatibility.
@Vaelatern for Salt Stack compatibility.
=> runit-void: Standardise/improve os-release

srcpkgs/sublime-text3-bin/template, srcpkgs/sublime-text3/INSTALL.msg, srcpkgs/sublime-text3/template
from the [EULA](https://www.sublimehq.com/eula) 2b (emphasis mine):
> **You may not distribute** or sell license keys or **the SOFTWARE PRODUCT to third parties**. Licenses will be revoked if distributed or sold to third parties.
I followed the example of sublime-merge -> sublime-merge-bin
=> make sublime-text3 restricted

srcpkgs/nwg-launchers/template
Adding this dependancy makes nwg-launchers work better under sway and other wlroots-based compositors.
=> nwg-launchers: add makedepends to gtk-layer-shell

srcpkgs/vscode/patches/disable-crash-reporter.patch, srcpkgs/vscode/patches/product.patch, srcpkgs/vscode/patches/ripgrep.patch, srcpkgs/vscode/template
I changed q66's package to replace @vscode/ripgrep to a far simpler version that only exposes the correct path and thus should never need to change and also removes the requirement to copy over files.
=> vscode: update to 1.65.1

srcpkgs/python3-pikepdf/template
5.0.0 was a breaking release since it requires the latest release of qpdf, which is now in master.
The current version of pikepdf in void (4.4.1) is not compatible with qpdf >=10.6.0, according to the pikepdf release notes.
=> python3-pikepdf: update to 5.0.1.

srcpkgs/pyradio/template
- aarch64-musl
- armv7l
- armv6l-musl
**python3-psutil** is a new dependency
=> pyradio: update to 0.8.9.14

srcpkgs/vapoursynth/template, srcpkgs/zimg/template
@lemmi 
Since R55 many filters were removed from the source tree and moved into seperate repositories. That's the reason why this package contains less files and some dependencies are no longer needed.
**About disabling SIMD:**
It seems that [zimg](https://github.com/sekrit-twc/zimg/blob/d4e32eaf4612589aed9223577c9429ff4c3c8269/configure.ac#L66) enforces correctly `-march=armv7-a -mfpu=neon-vfpv4`, but we override it with `-mfpu=vfpv3` so it doesn't work for us.
This was already discussed in https://github.com/sekrit-twc/zimg/issues/140
=> vapoursynth: update to R57. 

srcpkgs/octoxbps/patches/0001-Fix-detection-of-Void-Linux-in-getLinuxDistro.patch, srcpkgs/octoxbps/template
Without this change, OctoXBPS fails to detect that it is running on Void
Linux which causes a password prompt to be shown every time OctoXBPS is
opened.
=> octoxbps: fix detection of Void Linux

srcpkgs/nsxiv/patches/no-rebuild-options.patch, srcpkgs/nsxiv/template
=> nsxiv: update to 29

srcpkgs/protontricks/template, srcpkgs/python3-language-server/template
fixes #36129 
fixes #36072
Grouped because they were suffering from the same issue. Both happened to have updates available.
=> protontricks, python3-language-server: update, add missing setuptools dependency

srcpkgs/autofs/files/autofs/log/run, srcpkgs/autofs/files/autofs/run, srcpkgs/autofs/patches/musl.patch, srcpkgs/autofs/template
the log service was essential for  successfully debugging my autofs setup
=> autofs: add log service, fix patch args

srcpkgs/python-dbus-devel, srcpkgs/python-dbus/template
Also drop python-dbus-devel, there is no value in carrying the metapkg.
Hopefully this fixes test-time detection of `python-dbus` in, *e.g.*, https://github.com/void-linux/void-packages/pull/36216.
=> python-dbus: include egg-info metadata

srcpkgs/libusb/patches/late-transfer-free.patch, srcpkgs/libusb/template
libusb/libusb#1073
fixes #35650
tested with LimeSuite/SoapyLMS7 (from #32573), which was affected by this issue.
=> libusb: fix segfault

srcpkgs/budgie-control-center-devel, srcpkgs/budgie-control-center/template, srcpkgs/budgie-desktop-view/template, srcpkgs/budgie-desktop/template, srcpkgs/budgie-screensaver/patches/musl.patch, srcpkgs/budgie-screensaver/template
musl patch sent upstream https://github.com/BuddiesOfBudgie/budgie-screensaver/pull/4
=> budgie-desktop: update to 10.6.

srcpkgs/zfs/template
- aarch64-musl
- x86_64-musl
ZFS 2.1.4 adds a fix for kernel 5.16 on [specific x86 CPUs](https://github.com/openzfs/zfs/issues/13210). I've booted my system with this package, but it could use wider real-world testing on Void systems.
=> zfs: update to 2.1.4.

srcpkgs/dendrite/files/dendrite-monolith-server/run, srcpkgs/dendrite/template
add MAX_OPEN_FILES variable with default set to value recommended by
upstream (65535).
=> dendrite: update to 0.7.0.

.github/pull_request_template.md
related #36263
Currently the PR template may be a bit confusing because we write [skip CI] as markdown syntax which is very similar to [ci skip].
This syntax in a comment which is not meant to be uncommented is unintuitive so I propose wording it differently.
=> .github: improve the PR template

srcpkgs/upterm/template
[upterm.dev](https://github.com/owenthereal/upterm/) alternative [tmate.io](https://github.com/tmate-io/tmate/) (tmux fork) for sharing terminal session.
=> New package: upterm-0.7.6

srcpkgs/helvum/patches/i686-pipewire.patch, srcpkgs/helvum/template
upstream released pipewire-rs v0.5.0 that fixes the underlying issue,
but the Cargo.toml version requirement didn't allow it to be updated.
=> helvum: clean up patch/template

srcpkgs/pijul/template, srcpkgs/rdedup/template
caused by me in #36125
don't think it's necessary to revbump, it should not change the output package at all
=> pijul, rdedup: remove unnecessary build_helper

srcpkgs/freerdp/template
=> freerdp: update to 2.6.1.

srcpkgs/micro/template
The package hasn't had any contribution from the maintainer since 2016, so I'l like to adopt it.
@diogoleal Since you are currently marked as the maintainer for the micro package, is that ok with you?
=> micro: adopt.

srcpkgs/nwipe/template
=> nwipe: update to 0.33.

srcpkgs/perl-Crypt-CBC/template, srcpkgs/perl-Math-Int128/template, srcpkgs/perl-Math-Int64/template
There is a change which requires the perl-Math-Int128 module when using 'ctr' (Counter Mode) as block chaining mode, because it’s much faster than the previsously used Math::BigInt (default mode is still 'cbc').
However, Math::Int128 is not available on 32-bit architectures, so this update would break such setups, though probably not many are using it, if anyone at all. But still I’m not sure how to proceed on this.
Tested on x86_64.
=> perl-Crypt-CBC: update to 3.04

srcpkgs/lilypond-doc/template, srcpkgs/lilypond/template
- tested on x86_64 and i686
- check on i686 fails again due to floating point stuff
=> lilypond: update to 2.23.6

.github/workflows/build.yaml
See https://github.com/sgn/void-packages/actions/runs/493766269
=> GitHub Action: build on push to non-master branches

srcpkgs/spotify-adblock/template
=> New package: spotify-adblock-1.0.1

srcpkgs/zlib/patches/CVE-2018-25032.patch, srcpkgs/zlib/template
https://www.openwall.com/lists/oss-security/2022/03/24/1
=> zlib: backport upstream fix for CVE-2018-25032.

srcpkgs/acme-client/files/acme-client.conf, srcpkgs/acme-client/template
portable acme-client existed previously with a different upstream, which
was unmaintained - switch to one that is maintained.
- x86_64 (cross)
=> New package: acme-client-1.3.0

.github/workflows/stale.yml
This PR adds the [stale action](https://github.com/actions/stale) to try and keep an eye on things that are stale due to inactivity.  It will not act on any PR or issue that is assigned.  Right now it won't even make any changes, I just want it to run so we can evaluate what the rough impact would be of switching on a stale PR minder.
=> .github/workflows: Add a workflow for dealing with stale issues/prs

srcpkgs/iwd/template
- aarch64-musl
- ppc64le-musl
---
[Changelog](https://git.kernel.org/pub/scm/network/wireless/iwd.git/plain/ChangeLog):
```
ver 1.26:
Fix issue with handling BSS that changed frequency.
Fix issue with handling frequencies in neighbor report.
Fix issue with operating classes for 802.11ax standard.
Fix issue with enforcing of MFPR for 6 GHz frequencies.
Add support for band defined in the WiFi 6E amendment.
Add support for scanning while in AP mode.
ver 1.25:
Fix issue with handling abort of periodic scans.
Fix issue with handling connection when link goes down.
Fix issue with handling operating …
```
=> iwd: update to 1.26.

srcpkgs/python3-sympy/patches/fix_integer_nthroot.patch, srcpkgs/python3-sympy/template
Also fix integer_nthroot(2, 10**10) in 32 bit, reported upstream (https://github.com/sympy/sympy/issues/18374#issuecomment-1081196879 and https://github.com/aleaxit/gmpy/issues/257#issuecomment-1073426165)
=> python3-sympy: update to 1.10.1.

srcpkgs/vte3/template
Required for gnome-terminal 3.44 and gnome-console 42
=> vte3: update to 0.68.0

srcpkgs/onboard/patches/fix-brokenformat.patch, srcpkgs/onboard/template
- A missing % operator was breaking a c-style format string, causing a
SyntaxWarning to be trown twice at package install time (during
byte-compilation).
- The tests were failing since they try to run 'killall' before executing
onboard in xautomation(7), both not being possible in xbps-src.
=> onboard: fix SyntaxWarnings and disable tests

srcpkgs/kodi-addon-pvr-zattoo/template, srcpkgs/kodi-addon-pvr-zattoo/update
=> kodi-addon-pvr-zattoo: update to 19.7.11.

srcpkgs/helix/template, srcpkgs/hex/template
This removes the conflict with `helix` by renaming the binary to the project's name.
=> hex: change binary name to avoid conflict with helix

Manual.md
The pre_/do_/post_check functions were not listed in the list of building
phase functions, and were not mentioned elsewhere (do_check was mentioned
once). This documents their existence.
=> Manual.md: document the check functions

srcpkgs/python3-shapely/template
- I built this PR locally for my native architecture, x64_glibc
Note: a few of the tests fail. Upstream is aware of this, but they won't address it in any future 1.8.X releases
https://github.com/shapely/shapely/issues/1207
=> python3-shapely: update to 1.8.1.

srcpkgs/python3-pycollada/template, srcpkgs/python3-trimesh/template
- I built this PR locally for my native architecture, x64_glibc
This PR also updates pycollada
The unit tests throw a few deprecation warnings from the dependencies (numpy, scipy, shapely)
=> Trimesh: update to 3.10.7

srcpkgs/python3-svg.path/template
- I built this PR locally for my native architecture, x64_glibc
One test fails because of cross-platform font rendering discrepancies, so I disabled it.
I opened an issue upstream https://github.com/regebro/svg.path/issues/84
=> python3-svg.path: update to 5.1.

srcpkgs/vpsm/patches/setuid-fix.patch, srcpkgs/vpsm/template
- The suid permission bit was incorrectly being set. It is now gone.
See #32156
- The upstream README indicates a move to a new GH account.
@sinetoami @sineto
=> vpsm: update upstream, clean suid bit

srcpkgs/wireplumber/template
- I built this PR locally for my native architecture, (aarch64-musl, x86_64)
This version fixes wireplumber for me on aarch64-musl.
=> wireplumber: update to 0.4.9

srcpkgs/emacs/template
Enable cairo and harfbuzz by default, as recommended by upstream.
Nativecomp can be enabled once libgccjit is packaged, we need to figure out if it can be made optional or we split it into a separate subpackage.
=> emacs: update to 28.1.

srcpkgs/apache-storm/template
See #34534, updates from vulnerable log4j
I'm not sure how to test this, but it builds.
=> apache-storm: update to 2.4.0.

srcpkgs/pipe-viewer/template
=> pipe-viewer: update to 0.2.0.

srcpkgs/dhcpcd/patches/revert-eloop.patch, srcpkgs/dhcpcd/template
fixes #36182 which was already reported upstream https://github.com/NetworkConfiguration/dhcpcd/issues/79
=> dhcpcd: fix 'dhcpcd_open: Bad File Descriptor' with dhcpcd-qt.

srcpkgs/base-files/files/group, srcpkgs/base-files/template, srcpkgs/openocd/template, srcpkgs/openrazer-meta/template, srcpkgs/wally-udev-rules/INSTALL.msg, srcpkgs/wally-udev-rules/template
Plugdev is used by many packages' udev rules for pluggable devices.
Currently, some of those packages use the system_groups trigger to add it, some forget to add it, and others patch it to "users" or "uaccess" (which breaks the packages on systems that don't use logind).
By adding plugdev to the default groups, we get rid of those problems.
This PR is needed for
- https://github.com/void-linux/void-packages/pull/34757
- https://github.com/void-linux/void-packages/pull/36144
While this pr deals with packages that had the `system_groups` hook to add plugdev, it does not deal with
1. packages that patch their rules to use `uaccess` instead (those packages are broken on systems that don't use logind)
I do not have the hardware to test any of those: `airspy hackrf libnfc openobex`
2. …
=> Add plugdev to default groups, drop server_group in templates

srcpkgs/libsigrok/template
Fixes #23580
Closes #23581 (obsoletes the PR)
=> libsigrok: fix missing udev rules

srcpkgs/python3-utils/template
- I built this PR locally for my native architecture, x64_glibc
=> python3-utils: update to 3.1.0.

srcpkgs/notion/patches/stdout.patch, srcpkgs/notion/template
- Fix homepage
- Fix musl
- Fix nonfree, upstream should be proper LGPL-2.1-or-later now
- Use Lua 5.4
cc @vtoc
=> notion: update to 4.0.2.

srcpkgs/findutils/template
Tests include a gnulib test that's broken on musl at least, so I need to fix that.
=> findutils: update to 4.9.0.

srcpkgs/font-ibm-plex-ttf/template
When there’s a choice between hinted and unhinted variants for a font family, this template chooses the former. This is more or less an arbitrary choice, since I’m unaware of any specific guidelines of this sort. It’s impossible to include both, as the files themselves overlap, and including neither (where applicable) would completely remove support for some languages.
=> font-ibm-plex-ttf: update to 6.0.0.

srcpkgs/musikcube-openmpt, srcpkgs/musikcube/patches/fix-install-locations.patch, srcpkgs/musikcube/patches/fix-mpris-detection.patch, srcpkgs/musikcube/template
- Update to 0.97.0
- Added MPRIS support
- Moved openmpt plugin to a separate package `musikcube-openmpt`
- I tested the changes in this PR: **YES** (it works properly)
=> musikcube: update to 0.97.0, adopt

srcpkgs/pre-commit/template, srcpkgs/pre-commit/update, srcpkgs/python3-identify/template
- I built this PR locally for my native architecture, (`x86_64`-`glibc`)
- This includes an update for `python3-identify` to version 2.4.12.
- Includes script to fix version update checking for `pre-commit`.
=> Pre commit 2.18.1

common/shlibs, srcpkgs/appmenu-gtk-module, srcpkgs/removed-packages/template, srcpkgs/vala-panel-appmenu/template
=> vala-panel-appmenu: remove gtk2 subpackage

srcpkgs/gitui/template
=> gitui: update to 0.20.1.

srcpkgs/PolyMC/files/README.voidlinux, srcpkgs/PolyMC/template, srcpkgs/PolyMC/update
Testing was done on my KDE workstation and also on a clean live booted environment (only manual packages were: base-system, xorg, PolyMC). Logging in with a Microsoft account was not tested, since I don't have one. Minecraft versions 1.16.5 and 21w18a were successfully tested with the system jdk and the latest Minecraft release 1.18.1 with jdk 17 from adoptium.
I wasn't too sure which license to pick, so I just tried to be as comprehensive as possible.
Closes #34933
=> New package: PolyMC-1.1.1

srcpkgs/ruby-build/template
- I built this PR locally for my native architecture, x86_64, glibc
=> ruby-build: update to 20211227.

srcpkgs/wireproxy/files/wireproxy/run, srcpkgs/wireproxy/template
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): YES
- I built this PR locally for my native architecture, `(x86_64-glibc)`
=> New package: wireproxy-1.0.1

common/hooks/do-patch/00-patches.sh, srcpkgs/chatterino2/patches/0001-fix-desktop-icon-name.patch, srcpkgs/chatterino2/patches/cmake.patch, srcpkgs/chatterino2/template, srcpkgs/wine/patches/musl-limits.patch, srcpkgs/wine/patches/musl-rpath.patch, srcpkgs/wine/patches/musl-uid-t.patch, srcpkgs/wine/template
`patch(1)` has a `-d/--directory` parameter which allows us to specify a directory where the patch will be applied.
This is especially useful when we have multiple distfiles and want to patch in $build_wrksrc because that's where the patch is usually applied. So far, these patches had to be updated if $build_wrksrc changes, which is suboptimal.
Problem is, that the `-i` parameter is also relative to the the `-d` parameter and thus fails to find the patch, when `-d` is set.
This PR tries to solve that by using standard input instead of `-i`.
Included are examples with wine and chatterino2 making use of that change.
=> [RFC] patch_args: allow use of --directory parameter

srcpkgs/goodvibes/template
=> goodvibes: update to 0.7.3.

srcpkgs/screenkey/template
I added missing dependencies from https://gitlab.com/screenkey/screenkey#from-source
=> screenkey: update to 1.5.

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 5.38.0.

srcpkgs/revive/template
=> revive: update to 1.2.0.

srcpkgs/python3-Jinja2/template, srcpkgs/python3-fastjsonschema/template, srcpkgs/python3-jupyter_nbconvert/template, srcpkgs/python3-jupyter_nbformat/template, srcpkgs/python3-jupyter_notebook/template
Updates:
- python3-jupyter_notebook: to 6.4.10.
- python3-jupyter_nbconvert: to 6.4.5.
- python3-jupyter_nbformat: to 5.3.0.
The new package python3-fastjsonschema is needed for nbformat.
This also restores the update of Jinja2 to 3.1.1 which was reverted because of incompatibility with nbconvert-6.0.7 (see 3d6eb58)
NOTES:
- For fastjsonschema I used the tarball from github, instead of pypi, because the latter doesn't include the testsuite.
- For nbconvert I had to add a PYTHONPATH setting to `do_check()` because the "old" nbconvert will be installed at check-time (circular dependency?) and without this the testsuite will be testing the old nbconvert (which fails!).
What should we do about maintainership? @dkwo I think you use jupyter much …
=> Jupyter notebook updates

srcpkgs/libmtp/template
Also add a group `_libmtp` with r/w permission to accesss mtp devices.
=> libmtp: update to 1.1.19, use plugdev group for r/w access to mtp devices.

srcpkgs/dbeaver/patches/force-jdk11.patch, srcpkgs/dbeaver/template
fixes #34857
based on the fix provided in that issue
=> dbeaver: force jdk11 regardless of alternatives setting

srcpkgs/threejs-sage/template
Adds a symlink in /usr/share/jupyter/nbextensions, so that the js is available in a jupyter notebook.
Otherwise, using 3d plots in the jupyter notebook will hit jsdelivr.net.
=> threejs-sage: make it available as a jupyter nbextension

srcpkgs/font-cozette/template
=> font-cozette: update to 1.13.0, build natively, provide python3-crayons for makedepends

.github/workflows/build.yaml
Currently, this workflow runs on every pr (and push to branches called `ci-*`). This doesn't give any useful information for changes that only affect other parts of the repo, like common, xbps-src, documentation, etc.
=> [RFC] .github/workflows/build.yaml: only run on changes in srcpkgs/

srcpkgs/tiptop/template
This is the last missing distfile due to the `gforge.inria.fr`  shutdown.
No changes, no revbump.
=> tiptop: fix homepage and distfiles

.github/workflows/stale.yml
By setting [`ascending`](https://github.com/actions/stale#ascending) to `true`, the most stale issues and PRs will be caught first. By increasing the operations limit from the default (30) to 250, more stale issues/PRs will be caught each run, increasing the speed of the burndown.
This implements some of the suggestions from #36657
=> .github/workflows/stale.yml: increase operations limit

common/travis/fetch_upstream.sh
The newest git versions require [safe.directory](https://git-scm.com/docs/git-config/2.35.2#Documentation/git-config.txt-safedirectory) to work properly for repos owned by others.
Tested by temporarily adding a commit that changed a package to this PR, and [it succeeded](https://github.com/void-linux/void-packages/actions/runs/2177619018).
=> common/travis/fetch_upstream.sh: fix CI for new git version

srcpkgs/gnome-settings-daemon/template, srcpkgs/mkchromecast/template, srcpkgs/pasystray/template
`pipewire-pulse` can be used instead of `pulseaudio`, so there is no need for these packages to depend on `pulseaudio`. This may break sound for people who run something like `xbps-remove -oy` every time, but that's their mistake. This is especially useful in the case of gnome-settings-daemon because this currently makes gnome depend on pulseaudio and it has to be explicitly disabled or people have to use `ignorepkg` and uninstall it.
=> {gnome-settings-daemon,mkchromecast,pasystray}: remove pulseaudio dependency

srcpkgs/kitinerary/patches/temporarily-disable-broken-test.patch
The tests were fixed upstream, so this shoul be able to be removed after the next update
These tests are already updated upstream, but it is over several commits and it is mixed with updates for supporting qt6, so it's probably best to just ignore it for now, I checked it and the tests do succeed with `kitinerary-22.03.80` so once that reaches stable, it can be removed.
Closes: https://github.com/void-linux/void-packages/issues/36734
=> kitinerary: temporarily ignore test failures

srcpkgs/yaboot/patches/0003-build-system.patch, srcpkgs/yaboot/template
The -fcommon is required for gcc10 to build yaboot.
Adding --build=$XBPS_TRIPLET seems to be a good idea in any case
according to the autoconf manual, see the document at:
https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Hosts-and-Cross_002dCompilation.html
Still gives an error for me trying to build for ppc-musl using any
x86 host environment, be it glibc or musl libc.
More patches required or something else may be wrong?
=> yaboot: fix build w/ gcc10 and host i686/x86_64

srcpkgs/texlive-latexmk, srcpkgs/texlive/template
This script only works if LaTeX and perl are installed.
- There are many providers for a LaTeX compiler (I assume) so I didn't list it as a dependency.
- As for perl, there are multiple ways of installing perl as well (e.g. via perlbrew into the user's home directory). I did include it as a dependency though.
Resolves https://github.com/void-linux/void-packages/issues/35626.
=> New package: latexmk-4.76

srcpkgs/openjdk10-bootstrap/template, srcpkgs/openjdk12-bootstrap/template, srcpkgs/openjdk13-bootstrap/template, srcpkgs/openjdk14-bootstrap/template, srcpkgs/openjdk15-bootstrap/template, srcpkgs/openjdk16-bootstrap/template, srcpkgs/openjdk9-bootstrap/template
Openjdk will compile for armv5* and armv6*, but it is not supported at runtime, at least in the configuration we ship.
See [here](https://forums.raspberrypi.com/viewtopic.php?t=232680), [here](https://forums.raspberrypi.com/viewtopic.php?t=323376), and [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255662) for evidence of the incompatibility.
This changes nothing for void's builds because these packages are nocross, but if someone wished to build it for arm natively, this will stop them.
[ci skip]
=> openjdk{9,10,12-16}-bootstrap: disable on armv5 and armv6

common/shlibs, srcpkgs/libfm-qt/template, srcpkgs/liblxqt/template, srcpkgs/libqtxdg/template, srcpkgs/lximage-qt/template, srcpkgs/lxqt-about/template, srcpkgs/lxqt-admin/patches/systemd.patch, srcpkgs/lxqt-admin/template, srcpkgs/lxqt-archiver/template, srcpkgs/lxqt-build-tools/template, srcpkgs/lxqt-config/template, srcpkgs/lxqt-globalkeys/template, srcpkgs/lxqt-notificationd/template, srcpkgs/lxqt-openssh-askpass/template, srcpkgs/lxqt-panel/template, srcpkgs/lxqt-policykit/template, srcpkgs/lxqt-powermanagement/template, srcpkgs/lxqt-qtplugin/template, srcpkgs/lxqt-runner/template, srcpkgs/lxqt-session/template, srcpkgs/lxqt-sudo/template, srcpkgs/lxqt-themes/template, srcpkgs/lxqt/template, srcpkgs/pavucontrol-qt/template, srcpkgs/pcmanfm-qt/template, srcpkgs/qps/template, srcpkgs/qterminal/template, srcpkgs/qtermwidget/template, srcpkgs/xdg-desktop-portal-lxqt/template
Update from installed 1.0.0
- I built this PR locally for my native architecture,
- x86_64
- x86_64-musl
---
On the pattern, I am not sure of adding `breeze-gtk`: none of the newly introduced palettes matches Breeze colors after all.
Runtime dependency on `lxmenu-data` was moved from pattern to `lxqt-panel`.
=> LXQt 1.1.0

common/hooks/pre-pkg/99-pkglint.sh
Message is useful, but when it is a warning, clueless people add *any* missing entry.
=> hooks/99-pkglint.sh: make missing shlib entry not a warning

srcpkgs/gtksourceview5/template
Required by gnome-text-editor-42.1
=> gtksourceview5: update to 5.4.1

srcpkgs/volta/template
=> volta: update to 1.0.7

srcpkgs/thefuck/template
- I built this PR locally for these architectures (if supported. mark crossbuilds):  
- armv7l
=> thefuck: update to 3.32.

srcpkgs/img2pdf/template
I enabled tests again and patched the remaining failing ones.
EDIT:
Oh well, scratch that about the tests. They still fail on anything but x86_64.
=> img2pdf: update to 0.4.4.

srcpkgs/ncmpc/template
Also, remove unneeded boost-devel dependency and
bump to pcre2.
=> ncmpc: update to 0.46.

srcpkgs/gst-plugins-base1/template
I noticed a dependency missing because it broke the gtk4 build.
=> gst-plugins-base1: fix -devel dependencies

srcpkgs/btrfs-progs/template
=> btrfs-progs: move .pc file to libbtrfsutil-devel

.github/workflows/cycles.yml, common/travis/fetch_upstream.sh
the cycles CI has been spitting out 50k lines of:
```
fatal: unsafe repository ('/__w/void-packages/void-packages' is owned by someone else)
To add an exception for this directory, call:
git config --global --add safe.directory /__w/void-packages/void-packages
```
This should fix that
=> .github/workflows/cycle.yml: fix error message related to git 2.35.2+

common/xbps-src/shutils/common.sh, common/xbps-src/shutils/pkgtarget.sh, xbps-src
helps to check if build can be fixed
=> xbps-src: add flag to build broken packages

srcpkgs/lazarus/template
I built it for x86_64 and am requesting testing from stevelitt.
Test packages are here:
https://devspace.voidlinux.org/maldridge/please-test/pr/36842/
=> lazarus: update to 2.2.0.

srcpkgs/inspircd/INSTALL.msg, srcpkgs/inspircd/template
---
This updates InspIRCd to v3.13.0 and fixes the following package problems:
- Fixed depending on geoip-devel instead of libmaxminddb-devel. This is a leftover from v2.
- Fixed not passing `--disable-auto-extras` to configure. Without this the previous call to `--enable-extras` would have been overridden and resulted in the enabled extra modules being based on what is installed on the build system.
- Fixed not explicitly enabling modules that would have otherwise been automatically enabled based on the dependent packages.
- Fixed using `--gid 0 --uid 0` instead of `--disable-ownership`. The latter is more appropriate for distribution packages.
- Fixed manually specifying directories …
=> inspircd: update to 3.13.0.

srcpkgs/oksh/template
@leahneukirchen following the practices suggested in [this reedit thread](https://www.reddit.com/r/voidlinux/comments/u0el6s/what_is_the_maintainer_of_the_package_template/), I went to the trouble of making a pull request to update the shell template oksh.
- I built this PR locally for my native architecture, (musl)
- I built this PR locally for architecture:
- x86_64
- i686
=> oksh: update to 7.1

srcpkgs/SDL2/template
- I built this PR locally for my native architecture, (x86_64, aarch64-musl)
This one will fail unless pipewire is at 0.3.51 (there was a fix in the headers): https://github.com/void-linux/void-packages/pull/36899
=> SDL2: update to 2.0.22, adopt

srcpkgs/spotify/template
The old (current) deb is already removed from the repo, so all new builds fail now.
=> spotify: update to 1.1.84.

srcpkgs/gettext/template
fixes this error when building:
```
make[2]: Entering directory '/builddir/gettext-0.21/libtextstyle'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /builddir/gettext-0.21/libtextstyle/build-aux/missing aclocal-1.16 -I m4 -I gnulib-m4
/builddir/gettext-0.21/libtextstyle/build-aux/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
You should only need it if you modified 'acinclude.m4' or
'configure.ac' or m4 files included by 'configure.ac'.
The 'aclocal' program is part of the GNU Automake package:
<https://www.gnu.org/software/automake>
It also requires GNU Autoconf, GNU m4 and Perl in order to run:
<https://www.gnu.org/software/autoconf>
<https://www.gnu.org/software/m4/>
<https://www.perl.org/> …
```
=> gettext: fix non-cross builds

srcpkgs/base-files/files/DIR_COLORS.256color, srcpkgs/base-files/template
this fixes empty `$LS_COLORS` in alacritty
=> base-files: add alacritty to DIR_COLORS.256color

srcpkgs/spotify-adblock/template
=> spotify-adblock: update to 1.0.2 (ignore the failing xlint test, it's a false alarm)

srcpkgs/kmonad/template
Fixes: 78955200f6
```
Name   Action    Version           New version            Download size
kmonad downgrade 65b501defdd0049563752f8af8c8c57f5a1ae38b_1 0.4.1.20220321_1       -
```
@q66 @slotThe
=> kmonad: correct version to 0.4.1.20220321.

Manual.md, common/build-style/cargo.sh, common/build-style/cmake.sh, common/build-style/configure.sh, common/build-style/gnu-configure.sh, common/build-style/gnu-makefile.sh, common/build-style/meson.sh, common/build-style/perl-ModuleBuild.sh, common/build-style/perl-module.sh, common/build-style/python-module.sh, common/build-style/python3-module.sh, common/build-style/python3-pep517.sh, common/build-style/raku-dist.sh, common/environment/setup/sourcepkg.sh, srcpkgs/totem/template
$make_check_pre can be used for wrapper commands like xvfb-run or
dbus-run-session which are common ways to make tests work. This way many
templates can avoid defining their own do_check function.
=> [RFC]: xbps-src: add make_check_pre

srcpkgs/flintlib/template
Also, enable openblas (used for matrix multiplication)
I ran sagemath long doctest suite with this. The update by itself is just a bugfix release, but I also took the chance to enable openblas for matrix multiplication so I wanted to make sure I didn't mess up (I had it disabled b/c of a misunderstanding on my part, it seems convenient to have it enabled.)
=> flintlib: update to 2.8.5.

.github/workflows/build.yaml, common/scripts/lint-conflicts
Report packages installing same file and not marked with conflicts or replaces.
=> Check file conflicts in x86_64 build job

common/scripts/lint-commits, common/scripts/lint2annotations.awk, common/travis/xlint.sh
This turns xlint, version lint, and commit lint messages into warning or error annotations.
Only annotations from the last CI run will show, except on the summary and logs of a run, where they are visible as long as the run exist.
A showcase of the changes can be seen [here](https://github.com/0x5c/void-packages/pull/3).
Ping @the-maldridge since you were interested in this
Inline lints (xlint and version lint)
Lints without line number show at line 1 (misplaced variables now have a line number since https://github.com/leahneukirchen/xtools/pull/240)
All lints show on the action run summary
and in the log
[ci skip]
=> common/travis/xlint.sh: print Github annotations

srcpkgs/git/template
This reverts commit 0a0487fc3090b5b96e507f4ee2019293f95dd0b3.
See: https://lore.kernel.org/git/xmqqlevfdbiq.fsf@gitster.g/
=> Revert "git: update to 2.36.0."

srcpkgs/freeplane/patches/jdk11-default.patch, srcpkgs/freeplane/template
- didn't build with jdk8, so updated the makedep to 11
- didn't run with jdk17, so hard-coded jdk11 as the default
cc @thypon
=> freeplane: update to 1.9.14, hard-code jdk11

srcpkgs/mupdf/template
I also switched from a `tar.gz` tarball to a `tar.xz` one since it's
smaller in size (87 MB vs 62 MB).
- I tested the changes in this PR: **briefly** (I tested the `mupdf` command on a PDF file)
=> mupdf: update to 1.19.1.

srcpkgs/activityrelay/files/activityrelay/log/run, srcpkgs/activityrelay/files/activityrelay/run, srcpkgs/activityrelay/template, srcpkgs/activityrelay/update
LitePub relay from the Pleroma project: https://git.pleroma.social/pleroma/relay
=> New package: activityrelay-0.2.0

.github/workflows/build.yaml, common/travis/xpkgdiff.sh
- common/travis/xpkgdiff.sh: add script to compare pkgs to previous version
- .github/workflows/build.yaml: add xpkgdiff CI step
See demo PR: classabbyamp/void-packages#3
=> add xpkgdiff to CI

srcpkgs/SPIRV-Headers/template, srcpkgs/SPIRV-Headers/update, srcpkgs/SPIRV-Tools/template, srcpkgs/Vulkan-Headers/template, srcpkgs/Vulkan-Headers/update, srcpkgs/Vulkan-Tools/template, srcpkgs/Vulkan-Tools/update, srcpkgs/Vulkan-ValidationLayers/template, srcpkgs/Vulkan-ValidationLayers/update, srcpkgs/robin-hood-hashing/template, srcpkgs/vulkan-loader/template, srcpkgs/vulkan-loader/update
=> Vulkan: update to 1.3.204.1

srcpkgs/pgcli/template, srcpkgs/python3-pgspecial/template
=> pgcli: update to 3.4.1, adopt.

srcpkgs/net-tools/template
Also cleaned up the template and made the build system behave slightly better.
=> net-tools: update to 2.10, adopt.

srcpkgs/nvidia/template, srcpkgs/nvidia470/template
- I built this PR locally for my native architecture: (x86_64-glibc)
Please test the update!  Nothing much on the Wayland front.
> Fixed an issue where NvFBC was requesting Vulkan 1.0 while using Vulkan 1.1 core features. This caused NvFBC to fail to initialize with Vulkan loader versions 1.3.204 or newer.
=> nvidia: update to 510.68.02.

srcpkgs/xf86-video-amdgpu/template
I have tested this for about a day now , no issues to complain about.
This is a small release: 
https://github.com/freedesktop/xorg-xf86-video-amdgpu/compare/xf86-video-amdgpu-21.0.0...xf86-video-amdgpu-22.0.0
=> xf86-video-amdgpu: update to 22.0.0.

srcpkgs/lazydocker/template
- I built this PR locally for my native architecture, x86_64 libc
=> lazydocker: update to 0.18.1

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 5.43.0, adopt.

srcpkgs/libslirp/template, srcpkgs/slirp4netns/template
- libslirp: update to 4.7.0
- slirp4netns: update to 1.2.0
- I built this PR locally for my native architecture, x86\_64
- x86\_64-musl
=> slirp4netns

srcpkgs/runc/template
=> runc: update to 1.1.2

srcpkgs/po4a/template
Two sgml tests fail because they invoke `onsgmls` from OpenSP to verify a test sgml file against a docbook DTD which errors out.
The `opensp` package adds a sgml catalog entry
`CATALOG /usr/share/OpenSP/catalog`
and in `/usr/share/OpenSP/catalog` there is a sgml declaration:
`SGMLDECL unicode.sd`
When this line or the catalog entry above is removed `onsgmls` falls back to its
default definition and succeeds and all tests are passed.
I’m not sure if the problem is related to Void’s `opensp` package or to `po4a`.
Any ideas are welcome! :)
I also asked upstream: https://github.com/mquinson/po4a/issues/327
=> po4a: update to 0.66

common/hooks/pre-pkg/04-generate-runtime-deps.sh
fixes #36641
by "reproducibility", I mean mostly for tools that compare versions/builds of packages.
The solution I have implemented is basically:
1. transform the space-separated list to newline-separated
2. sort
3. transform back to space-separated
=> common/hooks/pre-pkg/04-generate-runtime-deps.sh: sort deps for reproducibility

srcpkgs/node_exporter/template
=> node_exporter: update to 1.3.1.

srcpkgs/php8.0/template
@TinfoilSubmarine why did you decide to use curl for fetch? It doesn't seem necessary to me.
=> php8.0: update to 8.0.19.

common/xbps-src/shutils/update_check.sh
=> [WiP] xbps-src/shutils/update_check.sh: change gitlab check to handle subgroups

srcpkgs/kdenlive/template
- add opencv (for motion tracking)
- remove vlc (only as optional media player)
=> kdenlive: update to 22.04.1

srcpkgs/dolphin/template
=> dolphin: fix typo version

.github/workflows/build.yaml
- .github/workflows/build.yaml: switch to ubuntu-latest
- .github/workflows/build.yaml: auto-cancel in-progress workflows
follow-on to stale-closed #28481
Confirmed that re-pushing cancelled the older run, as expected
=> CI: cancel previous runs on re-push, update to ubuntu-latest

srcpkgs/q5go/patches/qgo.desktop.patch, srcpkgs/q5go/template
- This new package conforms to the [quality requirements](https://github.com/void-linux/void-packages/blob/master/Manual.md#quality-requirements): YES
- aarch64-musl
- armv7l
- armv6l-musl
=> New package: q5go-2.13

srcpkgs/act/template
=> New package: act-0.2.26

srcpkgs/python3-libtmux/template, srcpkgs/python3-tmuxp/template
Note: tmuxp cannot be updated to v1.11.1 because it depends on click v8.
=> Update tmuxp and libtmux

srcpkgs/NetworkManager/template
=> NetworkManager: update to 1.38.0

srcpkgs/recutils/template
Fixes #30546
Supercedes #30567
@loreb 
1.9 does indeed seem to fix the /tmp issue.
=> recutils: update to 1.9.

srcpkgs/python3-chardet/template
The current template is broken, and won't build a working package. Currently all works, just because there wasn't a revbump since the split.
I tested an update from the previous rev to this, there were no problems with the alternatives.
Also, as the python2 pkg still exists in the repos, I made them `conflict` to ensure there won't be any strange behaviour with alts.
=> python3-chardet: fix split with python2 pkg, revbump

srcpkgs/mutt/template
Built and briefly tested locally on `x86_64-musl`.
=> mutt: update to 2.2.5

srcpkgs/cni-plugin-dnsname/template, srcpkgs/cni-plugins/template, srcpkgs/cni/template
- cni: update to 1.0.1.
- cni-plugins: update to 1.1.1.
- New package: cni-plugin-dnsname-1.3.1
=> cni updates and new cni-plugin-dnsname package

srcpkgs/python3-psutil/template
=> python3-psutil: update to 5.9.1.

srcpkgs/android-tools/template
This is required by the `mkbootimg`, `repack_bootimg` & `unpack_bootimg` tools which this package contains.
=> android-tools: depend on python3

srcpkgs/SDL2_ttf/template
- I built this PR locally for my native architecture, `aarch64-musl`
Tested with `neverball`.
=> SDL2_ttf: update to 2.0.18, adopt

srcpkgs/erlang/template
- I tested the changes in this PR: **briefly** (https://github.com/elixir-desktop/desktop-example-app)
This package seems to have been missed by #2664
As an aside, `kerl`/`asdf-erlang` needed `KERL_CONFIGURE_OPTIONS=--with-wx-config=wx-config-gtk3` for wxWebView to work. Not sure where that should be fixed/documented
=> erlang: switch to wxWidgets-gtk3

srcpkgs/shfmt/template
=> shfmt: update to 3.5.1.

common/shlibs, srcpkgs/dqlite/template, srcpkgs/lxd-lts/INSTALL.msg, srcpkgs/lxd-lts/files/lxd/run, srcpkgs/lxd-lts/template, srcpkgs/lxd/files/lxd/run, srcpkgs/lxd/template, srcpkgs/raft/template
- raft: update to 0.13.0
- dqlite: update to 1.10.0
- lxd: update to 5.1
- lxd-lts: update to 5.0.0
I tested creating/launching an Ubuntu container, including a container created prior to the upgrade from LXD 4.19.
I tested on x86_64 only.
=> lxd: update

srcpkgs/python3-asttokens/template
* tests need a specific astroid version that we can't provide https://github.com/gristlabs/asttokens/issues/79
@ahesford
=> python3-asttokens: disable astroid tests

srcpkgs/ffmpeg/template, srcpkgs/svt-av1/template
Without revbumping ffmpeg, `ffmpeg -i in.mp4 -c:v libsvtav1 out.mkv` fails:
```
Svt[info]: -------------------------------------------
Svt[info]: SVT [version]:	SVT-AV1 Encoder Lib v1.1.0
Svt[info]: SVT [build]  :	GCC 10.2.1 20201203	 64 bit
Svt[info]: LIB Build date: May 24 2022 07:28:32
Svt[info]: -------------------------------------------
[libsvtav1 @ 0x56184b8c3500] Error setting encoder parameters: bad parameter (0x80001005)
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```
=> svt-av1: update to 1.1.0

common/environment/setup/sourcepkg.sh
When building dependencies of packages this has to be unset to avoid using e.g. `CMAKE_GENERATOR="Unix Makefiles"` for a package which expected to build with the default of `make_cmd=ninja`, and would subsequently fail with `ninja: error: loading 'build.ninja': No such file or directory` during `do_build()` if `do_configure()` generated a Makefile instead of a
build.ninja file.
=> common: unset CMAKE_GENERATOR before sourcing templates

srcpkgs/pipewire/template
* runtime dependency - pipewire-pulse runs "pactl load-module module-always-sink"
* optional check dependency
@st3r4g
=> pipewire: add pulseaudio-utils to dependencies

srcpkgs/scaleway-cli/template
The version reported by the CLI was "2.0.0-dev" due to a missing build option. It is now the correct version ($VERSION-$REVISION).
=> scaleway-cli: fix version in build

srcpkgs/nv-codec-headers/template
https://github.com/void-linux/void-packages/pull/36311#issuecomment-1100789567
=> nv-codec-headers: update to 11.1.5.1

common/build-style/python3-module.sh, common/build-style/python3-pep517.sh, srcpkgs/python3-execnet/template, srcpkgs/python3-pytest-forked/template, srcpkgs/python3-pytest-xdist/template
- New package: python3-execnet-1.9.0
- New package: python3-pytest-forked-1.4.0
- New package: python3-pytest-xdist-2.5.0
=> New package: python3-pytest-xdist and dependencies

srcpkgs/btrfs-progs/template
=> btrfs-progs: update to 5.18.1.

srcpkgs/composer8.0/template, srcpkgs/composer8.1/template, srcpkgs/php8.0/template, srcpkgs/php8.1/template, srcpkgs/xdebug8.0/template, srcpkgs/xdebug8.1/template
=> php 8.0.20, php 8.1.7, xdebug 3.1.5, composer 2.3.7

srcpkgs/php/template
Looks serious: https://mobile.twitter.com/cfreal_/status/1534940109434507264
> These two CVEs (CVE-2022-31626, CVE-2022-31625) are remotely exploitable [#PHP](https://mobile.twitter.com/hashtag/PHP?src=hashtag_click) bugs that I'll present at [@typhooncon](https://mobile.twitter.com/typhooncon)
later this month. Please update !
=> php: update to 7.4.30.

srcpkgs/rsyslog-clickhouse, srcpkgs/rsyslog/patches/disable-omfile-outchannel.patch, srcpkgs/rsyslog/patches/disable-omfile-read-only-errmsg.patch, srcpkgs/rsyslog/patches/disable-omfile-read-only.patch, srcpkgs/rsyslog/patches/disable-omfwd_fast_imuxsock.patch, srcpkgs/rsyslog/template
I've added in support for `omclickhouse`, which just requires `libcurl` to build.
8.2112 passes all tests locally, so we'll see what CI/CD brings. This package has been problematic with the past few bumps.
```
Testsuite summary for rsyslog 8.2112.0
============================================================================
```
=> rsyslog: update to 8.2204.1

srcpkgs/x42-plugins/template
=> x42-plugins: update to 20220605.

common/build-style/cargo.sh
This prevents `cargo install` from wasting time fetching the crate registry.
[CI skip]
=> common/build-style/cargo.sh: use offline install

srcpkgs/libseccomp/template
Without this `tracker3-miners-3.3.0` will fail with the following message:
```
/usr/libexec/tracker-extract-3 -f file.mp3
(tracker-extract-3:9677): Tracker-CRITICAL **: 00:38:18.118: Failed to load seccomp rules.
**
Tracker:ERROR:../src/tracker-extract/tracker-extract.c:707:tracker_extract_get_metadata_by_cmdline: code should not be reached
Bail out! Tracker:ERROR:../src/tracker-extract/tracker-extract.c:707:tracker_extract_get_metadata_by_cmdline: code should not be reached
Aborted
```
=> libseccomp: update to 2.5.4

srcpkgs/mariadb/template
mariadb-client consisted almost entirely of symlinks to the main package
and manpages, and did not depend on the main package, so the symlinks
were broken if mariadb was not also installed.
fixes #37282
=> mariadb: merge mariadb-client into mariadb

srcpkgs/starship/template
=> starship: update to 1.7.1.

srcpkgs/mdocml/template
fixes #37512
@lfdebrux, does this fix your issue?
=> mdocml: fix detection of pager

srcpkgs/i2c-tools/patches/py-smbus_fix-destdir.patch, srcpkgs/i2c-tools/patches/py-smbus_use-setuptools.patch, srcpkgs/i2c-tools/template, srcpkgs/python3-smbus
~~Things I am still unsure about:~~
- ~~The subpackage name and short_desc~~
- ~~How to ensure the subpackage's version is the version of the python module (it is versioned separately)~~
Closes #36156
=> i2c-tools: change upstream and add python subpkg

srcpkgs/tor/template
High severity security update: https://lists.torproject.org/pipermail/tor-packagers/2022-June/000133.html
Test failing on x86_64-musl is already known.
=> tor: update to 0.4.7.8.

xbps-src
This significantly speeds up the package building process for build scripts etc. that run `./xbps-src pkg ...` on a long list of packages that may already have up-to-date local packages built when configured with `XBPS_PRESERVE_PKGS` set.
~~I still have one question: what to do with the existing call to `check_existing_pkg` in [`common/xbps-src/libexec/build.sh`](https://github.com/void-linux/void-packages/blob/master/common/xbps-src/libexec/build.sh#L38)? The script appears to be executed from a [few](https://github.com/void-linux/void-packages/tree/master/common/xbps-src/shutils/cross.sh) [other](https://github.com/void-linux/void-packages/tree/master/common/xbps-src/shutils/build_dependencies.sh) …
=> xbps-src: check for existing packages before syncing chroot repodata

srcpkgs/rhash/patches/0001-Fix-version-macro.patch, srcpkgs/rhash/template
Note the vendor tarball misses the version change - exported the next commit from git to fix this as a patch, otherwise rhash -v will be confusing
=> rhash: update to 1.4.3

srcpkgs/ndhc/template
=> ndhc: update to 20220308.

srcpkgs/dua-cli/template
=> dua-cli: update to 2.17.7

srcpkgs/zfs/patches/0001-only-build-the-module-in-dkms.conf.patch, srcpkgs/zfs/template
This should clear a (the?) blocker for bumping `linux` to `linux5.18`. Should be tested on `linux5.18`.
cc: @Vaelatern @leahneukirchen @ericonr @zdykstra 
=> zfs: update to 2.1.5.

Manual.md, common/build-style/cmake.sh, common/build-style/configure.sh, common/build-style/gnu-configure.sh, common/build-style/gnu-makefile.sh, common/build-style/perl-module.sh, common/environment/setup/sourcepkg.sh, common/xbps-src/libexec/xbps-src-docheck.sh
- common: add disable_parallel_check
- common/build-style: make do_check run in parallel unless disabled
- Manual.md: document disable_parallel_check
Redux of #31811, incorporating some of the outstanding feedback when it was stale-closed.
Adds `-j$XBPS_MAKEJOBS` to do_check in several build-styles, with the option to disable it if it causes issues.
I did *not* change the `python3-{modules,pep517}` build-styles to opt-out of parallel checks, because they require a 3rd-party library to do it (and it only works with pytest tests). If a python3 package has tests that require `python3-pytest-xdist` to run, but have issues with parallel tests, parallel behaviour can still be disabled by `disable_parallel_check` (which would set the xdist equivalent of `-j1`).
- I tested the changes in this PR: …
=> enable running tests in parallel

srcpkgs/cdrtools/INSTALL, srcpkgs/cdrtools/template
---
Some programs of the `cdrtools` suite require certain special privileges to function properly - installing the `cdrtools` package from the Void repository, I'm not able to use for instance the `cdrecord` command obtaining "insufficient privileges" errors. It makes sense to me that it should be possible to use these commands as a normal user without requiring root access.
To achieve this without having to make the respective binaries SUID, [it is recommended](http://cdrtools.sourceforge.net/private/cdrecord.html) to make use of Linux capabilities. I have used the settings published in the [release notes](https://sourceforge.net/projects/cdrtools/files/AN-3.01/view) of `cdrtools` which is also what [Arch Linux …
=> cdrtools: set capabilities

srcpkgs/mpv-mpris/template
Having `bash` as a check dependency (both on my machine and in the CI) seems to really mess things up for reasons I don't know of, and running `./xbps-src check mpv-mpris` seems to work without having it there, so I removed it.
=> mpv-mpris: update to 0.8.1.

srcpkgs/fava/template, srcpkgs/python3-click-threading/template, srcpkgs/python3-click/template
<details>
<summary>python3-click tests pass</summary>
```
$ git log --oneline --decorate | head -2
72184752a3 (HEAD -> python3-click) python3-click: update to 8.1.3.
fce1ba0a35 (upstream/master, upstream/HEAD, master) riff: update to 2.17.0.
$ ./xbps-src check python3-click
=> xbps-src: updating repositories for host (x86_64)...
[*] Updating repository `https://repo-default.voidlinux.org/current/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/nonfree/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/debug/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/x86_64-repodata' ...
[*] Updating repository `https://repo-default.voidlinux.org/current/multilib/nonfree/x86_6 …
```
=> python3-click: update to 8.1.3.

srcpkgs/radeontop/template
Mostly just allows radeontop to detect and display the name of newer GPUs like the RX 6000 series.
- I built this PR locally for my native architecture (x86_64-musl)
=> radeontop: Update to 1.4

srcpkgs/maxima/template, srcpkgs/sbcl/template
- I tested the changes in this PR: **NO** (only build tested)
@tornaria not having sbcl support in maxima on some archs might break sagemath (?), but this is an overall improvement, the maxima package wasn't built at all for cross archs (arm, ~~ppc~~)
=> maxima: enable sbcl option only on supported archs

srcpkgs/seabios/template
=> seabios: update to 1.16.0.

srcpkgs/black/template
Supersedes https://github.com/void-linux/void-packages/pull/34520. As I mentioned in a comment there, I had to run the tests twice (with jupyter dependencies enabled/disabled) in accordance with the [upstream testing](https://github.com/psf/black/blob/ae2c0758c9e61a385df9700dc9c231bf54887041/tox.ini#L37). I don't know how to remove a dependency installed via `checkdepends` temporarily in `do_check()`. So I moved the module "manually" out of site-packages.
=> black: update to 22.3.0.

srcpkgs/font-awesome5/template, srcpkgs/font-awesome6/template
Not sure if that should be a new package or replace font-awesome5...
=> New package: font-awesome6-6.1.1

srcpkgs/hunspell-sl_SI/template, srcpkgs/hunspell-sl_SI/update
=> New package: hunspell-sl_SI-2020.12.31

srcpkgs/mupdf/template
In the 1.20.0 changelog:
> Cross compilation should no longer need a host compiler
Do I have to do anything to account for this change? (not that I understand what it means)
=> mupdf: update to 1.20.0.

srcpkgs/ibus/template
I also enabled gtk4 support. Just to address the concerns from a previous PR. Most distros enable it, it is required on X11. On Wayland with GNOME 42, it will not be required since the wayland backend will be preferred there over the gtk backends. I did test it on X11 and with gtk4 support enabled, it does work with gtk4 applications for me (and without it enabled, it does not work).
=> ibus: update to 1.5.26

srcpkgs/slock/template
=> slock: added line in build section of template to factor in config.h

srcpkgs/hatch-vcs/template, srcpkgs/hatch/template, srcpkgs/hatchling/template, srcpkgs/python3-tomli-w/template
- ~~As they aren't just libraries, but also CLI tools, do hatch/hatchling need the `python3-` prefix? I personally don't like it, and would argue in favor of removing it.~~ Considering no one commented on this bit, I've decided to just get rid of.
- ~~There's nearly no testing happening here, but that's due to the deps either requiring git checkouts with submodules, or themselves to be installed for testing. Any opinions on this? I'd prefer to have some amount of automatic testing here and not just a "JC has run this on his laptop once", considering that these are likely to be fairly central Python packages~~ there are a few tests failing now, but they are being run and there's a hundred times more tests that do work as intended. The ones …
=> New package: hatch-1.2.1

srcpkgs/xdg-desktop-portal/template
Explicitly disable systemd build, and bump fuse-devel version requirement, as fuse3 is now required to properly build xdg-desktop-portal.
- armv7l
- i686-libc
Note: xdp is a host make dependency for xdg-desktop-portal-gtk, I've build it locally too, but as I use xdg-desktop-portal-wlr I can't test it right away.
Note2: [xdp gtk/gnome reference](https://github.com/void-linux/void-packages/pull/36311#issuecomment-1144119094)
=> xdg-desktop-portal: update to 1.14.4

srcpkgs/libstrophe/template, srcpkgs/profanity/template
=> profanity: update to 0.12.1. libstrophe: update to 0.12.0.

srcpkgs/AusweisApp2/template
Use official tarball to better check hashsums and maybe the signature
someday.
=> ausweisapp2: update to 1.22.6

srcpkgs/flacon/template
Also:
- add taglib-devel to makedepends (new upstream default dep).
@travankor
=> flacon: update to 9.0.0.

srcpkgs/fontconfig/template
- I tested the changes in this PR: **YES** (with Firefox)
=> fontconfig: update to 2.14.0.

srcpkgs/paper-icon-theme/template
---
Closes: #21895
Have been using this template for close to 2 years (something broke then - symlinks/svgs metadata/both/something like that), after that never looked at upstream again - turns out development of the icons set got frozen and the upstream github repo is archived. 
I know Void usually doesn't include non tagged releases, but I think this falls under the exceptions.
For the record, if I recall just around 100-150 files got broken (so not a lot of icons, as they are included in several sizes) and probably not a lot of people use it, that can explain why there weren't more complains.
=> paper-icon-theme: update to 1.5.0.20200312.

srcpkgs/haskell-language-server/template
The `-dynamic` flag is needed, as with this release[1] we dynamically
compile against GHC and the relevant system libraries by default.
[1]: https://github.com/haskell/haskell-language-server/releases/tag/1.7.0.0
=> haskell-language-server: update to 1.7.0.0

srcpkgs/imlib2/template
When #31397 is merged I can enable the newly added JXL loader which would close #36415, but this PR is also mergeable in its current state and we can add JXL support later.
=> imlib2: update to 1.9.0.

srcpkgs/jitterentropy/template
explicitly disable building with optimizations
jitterentropy-rngd-1.2.7 raises error during build without `CFLAGS=-O0`
=> jitterentropy: update to 3.4.0, fix license, -O0.

srcpkgs/ibus/patches/src-Fix-refcounting-issues.patch, srcpkgs/ibus/template
Sorry, this is something I missed during the last ibus update.
=> ibus: fix memory leaks and double unref

srcpkgs/mobile-broadband-provider-info/template
=> mobile-broadband-provider-info: update to 20220511.

srcpkgs/unibilium/template
This PR also changes upstream to https://github.com/neovim/unibilium
=> unibilium: update to 2.1.1

srcpkgs/rebar3/template
=> rebar3: update to 3.19.0.

srcpkgs/Electron-Cash/template, srcpkgs/python3-pathvalidate/template
- I tested the changes in this PR: **briefly** (I'm not very familiar with this software, but all essential functionality seems to be present)
-----
The currently packaged version, 4.2.3, crashes at launch due to [this bug](https://github.com/Electron-Cash/Electron-Cash/issues/2368).
A new dependency, `python3-pathvalidate` is added ~~in #37549~~.
=> Electron-Cash: update to 4.2.10.

srcpkgs/kate5/template
Kate 22.04 shipped with a crash when opening the filesystem panel or settings (which accesses filesystem panel settings internally) would crash. There was an attempt to fix it in 22.04.1 (the current Void Linux Kate version), but it still crashed due to dereferencing a null-ish `KConfigPrivate` pointer ([bug report](https://bugs.kde.org/show_bug.cgi?id=453234)). 22.04.2 reverted the changes altogether, fixing the crash ([commits](https://invent.kde.org/utilities/kate/-/commits/v22.04.2/addons/filebrowser/katefilebrowserplugin.cpp)).
This PR updates kate5 to 22.04.2 to fix the crash.
- I tested the changes in this PR: (edit) **YES**
=> kate5: update to 22.04.2.

srcpkgs/nss/template
I needed this to be able to force Firefox to use a system-wide
nss certificate store.
=> nss: package libnsssysinit.so.

srcpkgs/conmon/template
Fixes CVE-2022-1708
Include manpage
Supersedes #37764
=> conmon: update to 2.1.2

srcpkgs/mpg123/template
Unless explicitly configured to use only the internal network code, it requires either `wget` (default) or `curl` to support HTTP streaming. It doesn't fallback on the internal code when neither are found. What should the package depend on?
=> mpg123: update to 1.30.0.

srcpkgs/hut/template
This is the official command line client for https://sourcehut.org/
It's basically the sourcehut equivalent to Github's hub or gh tools.
It's been in development for a while now, but they've put out their
first release earlier this month. I've been using it happily for a while
before this release.
=> New package: hut-0.1.0
