- srcpkgs/ansible-core/patches/0001-use-command-v-instead-of-which-in-Makefile.patch
- srcpkgs/ansible-core/patches/0002-Make-unit-test-for-missing-git-executable-more-gener.patch
- srcpkgs/ansible-core/template
- srcpkgs/ansible/template
- srcpkgs/python3-straight.plugin/template
First patch has been merged upstream and will become available in 2.14, second patch has been merged upstream and a backport attempt was started as well, so it might arrive in 2.13.2 already.
We finally have tests running on ansible-core again, which surfaced https://github.com/ansible/ansible/issues/78169, which was fixed in under half a day by upstream, so yay :)
> Ansible 6.0.0

- srcpkgs/gerbera/template
- srcpkgs/libupnp/template
This PR contains two updates because gerbera depends on libupnp with version of at least 1.14.6.
> libupnp: update to 1.14.12 + gerbera: update to 1.11.0

- srcpkgs/libopenraw-pixbuf-loader
- srcpkgs/libopenraw/template
Someone had this issue on the GNOME matrix, libopenraw-pixbuf-loader wasn't loading their CR2 file correctly and I can reproduce it.
Without the libopenraw pixbufloader, eog was able to load the CR2 file correctly. The pixbuf loader is currently apart of the libopenraw package which is a dependency of xfce thumbler.
Seeing as the pixbuf loader part isn't needed by xfce or eog and the pixbuf loader is considered deprecated upstream, probably best to split it into its own subpackage so people can install it if they really need it.
https://gitlab.freedesktop.org/libopenraw/libopenraw/-/issues/10
> libopenraw: split the pixbuf loader into subpackage

- .github/workflows/cycles.yml
- .github/workflows/stale.yml
closes #37612
requires changing the default workflow permissions in the [repository settings](https://github.com/void-linux/void-packages/settings/actions) to:
The default permissions are read-only, which works fine for the build/PR CI workflow. Cycles needed write access to issues to create them if a cycle is detected. Stale needs write access to issues and pull requests, as is [documented upstream](https://github.com/actions/stale#recommended-permissions). This is safe because both those workflows should only run on master.
> .github/workflows/: set token permissions

- srcpkgs/goatcounter/files/README.voidlinux
- srcpkgs/goatcounter/files/goatcounter/log/run
- srcpkgs/goatcounter/files/goatcounter/run
- srcpkgs/goatcounter/template
I added the service for convinience.
> goatcounter: update to 2.2.3, add service

- srcpkgs/RcloneBrowser/patches/do-not-check-for-updates.patch
- srcpkgs/RcloneBrowser/template
It checks once a day and this PR only changes the default = if you ran rclone-browser at least once, the settings are already written and this PR won't change anything for you.
@zdykstra
> RcloneBrowser: do not check for updates by default

- srcpkgs/routinator/template
in addition:
- upstream has removed doc/misc.md
- add changelog
- I built this PR locally for these architectures (crossbuilds last on 0.11.1):
- aarch64-musl
- armv7l
- armv6l-musl
> routinator: update to 0.11.2

- srcpkgs/gperftools/patches/ppc-musl.patch
Package no longer builds with the patch whitespace changes.
The patches which had any looseness have been regenerated
to ensure clean build.
Let me note that there are new recent versions.  As I can't
test most of those releases on the rest of Void architectures,
I'd rather have a clean build of the current state.
- no code changes are expected, just to make sure the patches
apply cleanly with stricter options
> gperftools: refresh patches

- srcpkgs/sigi/template
The ppc64 patch was introduced by @q66 here: https://github.com/void-linux/void-packages/commit/b3329ed67a20b00fdb630ff29f0da1249b96e243
And the fix (via updating dependencies) to `sigi` was contributed by @sunfishcode here: https://github.com/hiljusti/sigi/pull/20
Thanks to both!
> sigi: update to 3.4.2

- srcpkgs/jimtcl/template
- srcpkgs/openocd/template
> openocd: loosen jimtcl dep version restriction

- srcpkgs/musl/patches/gettid.patch
- srcpkgs/musl/patches/implement_realpath_directly_instead_of_using_procfs_readlink.patch
- srcpkgs/musl/patches/work_around_linux_bug_in_readlink_syscall_with_zero_buffer.patch
- srcpkgs/musl/template
Everything builds.
The realpath/readlink patches were stated to be working here (let me know if there are any issues though):
https://github.com/void-linux/void-packages/pull/33372
Afaict, nothing important related to how  `__pthread_self()->tid` works was changed between our version and when `gettid()` was introduced, but it should still be tested.
I'm not running musl atm though so its a little hard for me to test it currently so feedback would be appreciated.
https://github.com/void-linux/void-packages/pull/37628#issuecomment-1163607702
> musl: update realpath/readlink and add gettid

- srcpkgs/python3-dulwich/template
`xbps-query -RX python3-dulwich` gives `hg-git-0.9.0_3` and `radicale-3.1.7_1`. I tested the first one with the [update PR](https://github.com/void-linux/void-packages/pull/37865). The second one doesn't seem to [require](https://github.com/Kozea/Radicale/blob/v3.1.7/setup.py#L52) it anymore.
> python3-dulwich: update to 0.20.44.

- srcpkgs/pylint/template
It depends on both `tomlkit` and `tomli`:
```
$ printf 'print("hello")\n' > hello.py
$ pylint hello.py
[...]
pkg_resources.DistributionNotFound: The 'tomli>=1.1.0' distribution was not found and is required by pylint
$ sudo xbps-install python3-tomli
[...]
$ pylint hello.py
************* Module hello
hello.py:1:0: C0114: Missing module docstring (missing-module-docstring)
------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
$ sudo xbps-remove -F python3-tomlkit
[...]
$ pylint hello.py
[...]
ModuleNotFoundError: No module named 'tomlkit'
```
@paper42
> pylint: depend on python3-tomli; update homepage

- srcpkgs/iputils/template
---
Before:
```
$ LANG=ja_JP.UTF-8 ping ix.de
PING ix.de (193.99.144.80) 56(84) bytes of data.
64 bytes from redirector.heise.de (193.99.144.80): icmp_seq=1 ttl=242 time=57.5 ms
```
After:
```
$ LANG=ja_JP.UTF-8 ping ix.de
PING ix.de (193.99.144.80) 56(84) バイトのデータ
64 バイト応答 送信元 redirector.heise.de (193.99.144.80): icmp_seq=1 ttl=242 時間=64.7ミリ秒
```
> iputils: enable localization

- srcpkgs/budgie-desktop/template
- srcpkgs/gnome-shell/template
- srcpkgs/mutter/template
Not sure why we are running into this issue *now* since we have been patching it like this since forever, but typelibdir is just used for the rpath and currently it is returning stuff like `/usr/aarch64-linux-musl//usr/lib64/mutter-10` when cross compiling due to `pc_sysrootdir`.
> Fix mutter rpath when cross compiling

- srcpkgs/pipewire/files/pipewire-pulse/run
- srcpkgs/pipewire/template
Append "/pulse" to PULSE_RUNTIME_PATH, since pulse-server doesn't do it
anymore, see:
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/4821c7ca2fe5e25ba018e9f5d4967f08d6bb816f
@ftrvxmtrx @Johnnynator @paper42
> pipewire: fix pipewire-pulse runit service

- srcpkgs/gnome-chess/template
Fixes 
```
$ sudo xbps-install gnome-games-collection
MISSING: gnome-chess>=42.0
Transaction aborted due to unresolved dependencies.
```
> gnome-chess: update to 42.0.

- srcpkgs/polari/template
polari no longer builds with current gnome/glib.  Needs glib-devel
explicitly installed, otherwise won't find glib-compile-resources
Change only to compilation environment, no code/testing changes proposed.
> polari: allow build with new glib environment

- srcpkgs/gerbera/files/gerbera/log/run
- srcpkgs/gerbera/files/gerbera/run
- srcpkgs/gerbera/template
The `runit` service was missing `exec` and it did not generate a default config. Combined with the fact that there was no `log` service, it was a little inconvenient to get running.
I left the commits separate for now, but the should probably squashed before merge. 
@crater2150 @octeep
> gerbera: runit service fixes

- srcpkgs/vscode/patches/fix_dir.patch
- srcpkgs/vscode/patches/product.patch
- srcpkgs/vscode/patches/ripgrep.patch
- srcpkgs/vscode/template
+ take care of new tracking server
- I tested the changes in this PR: **YES**, but one error was found: at the moment, the internal terminal does not work.
> vscode: update to 1.69.0

- srcpkgs/aircrack-ng/patches/evalrev.patch
- srcpkgs/aircrack-ng/patches/python.patch
- srcpkgs/aircrack-ng/patches/sqlite3.patch
- srcpkgs/aircrack-ng/template
- I built this PR locally for my native architecture, (`x86_64`-`glibc`)
This patch rolls in all changes (AND supersedes!) as discussed in PR #34452. The extra scripts mentioned in that PR require non-cross builds (use of Python).
On an aside, there are some dependency issues with `libhwloc-devel` package that could be improved in the future. Namely, that `-devel` package requires extra packages for the `pkg-config` file to work. All of these extra dependencies are NOT included by the `-devel` package, nor the `libhwloc` package. It is only the main package `hwloc` that includes some, but still not all.
> aircrack-ng: update to 1.7.

- srcpkgs/xconsole/template
> xconsole: update to 1.0.8

- srcpkgs/libinput-debug-gui
- srcpkgs/libinput-debug-gui/template
- srcpkgs/libinput/template
gst-plugins-bad1 -> zbar -> qt5 -> libinput -> gtk4 -> gst-plugins-bad1
Closes #37948
Closes #37971
@sgn
> libinput: split libinput-debug-gui to avoid a cycle

- srcpkgs/gnupg/template
GnuPG has a few different development branches, and they do change their mind sometimes about what those are. They used to say this:
> We are pleased to announce the availability of a new GnuPG release:
> version 2.3.0.  This release marks the start of public testing releases
> eventually leading to a new stable version 2.4.
Source: https://lists.gnupg.org/pipermail/gnupg-announce/2021q2/000458.html
But with 2.3.3, they changed their mind:
> Three different series of GnuPG are actively maintained:
> 
> - Version 2.3 is the current stable version with a lot of new features
>   compared to 2.2.  This announcement is about the latest release of
>   this series.
> 
> - Version 2.2 is our LTS (long term support) version and guaranteed to
>   be maintained at least until the end of 2024.
> …
> gnupg: adopt, update to 2.3.7.

- srcpkgs/perl-Class-MethodMaker/template
- srcpkgs/perl-Data-Perl/template
- srcpkgs/perl-GnuPG-Interface/patches/0001-disables-version-check.patch
- srcpkgs/perl-GnuPG-Interface/patches/0002-Hardcode-path-to-usr-bin-gpg.patch
- srcpkgs/perl-GnuPG-Interface/template
- srcpkgs/perl-MooX-HandlesVia/template
- srcpkgs/perl-MooX-Types-MooseLike/template
- srcpkgs/perl-MooX-late/template
- srcpkgs/perl-Net-IDN-Encode/template
- srcpkgs/perl-Role-Hooks/template
- srcpkgs/perl-Sub-HandlesVia/template
- srcpkgs/perl-Type-Tiny/template
- srcpkgs/qprint/template
- srcpkgs/signing-party/patches/makefiles.patch
- srcpkgs/signing-party/template
> New package: signing party-2.11_1

- srcpkgs/perl-Mail-Box/template
- srcpkgs/perl-Mail-Message/template
- srcpkgs/perl-Mail-Transport/template
When trying to build `aerc`, I had to bump these packages, because the versions currently in the repo have been deleted off of CPAN and are only available on BackPAN.
- armv5tel-musl (crossbuild)
> Update perl-Mail-* packages 

- srcpkgs/vscode/template
**Note**
This should fix https://github.com/void-linux/void-packages/issues/38005 too because of a rebuilt with electron fixes from here https://github.com/void-linux/void-packages/commit/21cf64ec33e9516a7f14ce7c1b2b538342f4fbfb.
> vscode: update to 1.69.1.

- srcpkgs/anydesk/template
> anydesk: update to 6.2.0.

- srcpkgs/zsh-completions/template
`cheat` completions have been removed upstream, deletion no longer necessary.
> zsh-completions: update to 0.34.0.

- srcpkgs/bucklespring/template
> bucklespring: remove unused libinput-devel makedep

- srcpkgs/neatvnc/template
- srcpkgs/wayvnc/template
Tested under Sway (wayvnc server) and Sway (TigerVNC client).
> neatvnc 0.5.1 / wayvnc 0.5.0

- srcpkgs/monero/template
- srcpkgs/poppler-qt5/template
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1109/diffs
> monero+poppler: THREADS_PTHREAD_ARG is no longer needed

- srcpkgs/python3-regex/template
> python3-regex: update to 2022.7.9.

- srcpkgs/bearssl/template
I added the `do_check` part, which seems to run fine.
Previously it was skipped.
> bearssl: run tests

- Manual.md
> Manual.md: fix multiple typos

- srcpkgs/cups-filters/template
Have been testing this since the release of cups 2.4.2, it's been fine with my limited selection of printers.
> cups-filters: update to 1.28.15.

- srcpkgs/python3-pikepdf/template
Plain setuptools_scm is now used, so there's no need to patch out setuptools_scm_git_archive anymore. Since 5.1.4 the egg-info directory needs to be on PYTHONPATH to run tests, so I copy it to the correct location as a workaround. Also added new required and optional depends/checkdepends.
> python3-pikepdf: update to 5.4.0.

- srcpkgs/python3-shodan/template
> python3-shodan: update to 1.28.0.

- srcpkgs/python3-Pygments/patches/importlib_metadata.patch
- srcpkgs/python3-Pygments/template
solves crash with httpie's help (httpie/httpie#1418)
> python3-Pygments: backport move from pkg_resources to importlib.metadata

- srcpkgs/python3-zstandard/template
> python3-zstandard: use system libzstd

- srcpkgs/mitmproxy/template
> mitmproxy: remove unused python3-pyzstd dependency

- srcpkgs/python3-ansible-compat/template
> python3-ansible-compat: update to 2.2.0.

- srcpkgs/lua-language-server/files/lua-language-server
- srcpkgs/lua-language-server/patches/enable-cross-compilation.patch
- srcpkgs/lua-language-server/template
Fixes https://github.com/void-linux/void-packages/issues/34436. I couldn't figure out a predefined `build-style` that would work for this. So it's likely missing flags required for cross-compilation as there is no `do_configure()`. I didn't put a separate `do_test()` since the tests seem to be running during the build phase itself. I tested via `lspconfig` in neovim  and it works as expected.
> New package: lua-language-server-3.5.0

- srcpkgs/tor/files/tor/run
- srcpkgs/tor/template
The current max open files is still not quite enough when running a high speed relay. Raise to 65536 which is also the default in Debian.
Failing test on x86_64-musl is known.
cc @daniel-eys
> tor: raise max open files again

- srcpkgs/fossil/template
Also:
- take maintainership
- remove readline-devel (not used)
- add json compile option
> fossil: update to 2.19.

- srcpkgs/h2o/patches/link-against-system-libyaml.patch
- srcpkgs/h2o/patches/tests-force-TLSv1.2-on-s_client-invocations.patch
- srcpkgs/h2o/patches/use-etc-ssl-certs.patch
- srcpkgs/h2o/template
While we are at it, run make check.
> h2o: use system yaml, ca-certs

- .github/issue_template.md
This is only mentioned in the bug report issue template, so some people
miss it because they don't look at the bug report issue template and
just open an issue without a template.
> .github/issue_template: discourage update requests

- srcpkgs/docker-credential-pass/template
- Only checked that `xls` shows the right binary after packaging
This was broken [here](https://github.com/void-linux/void-packages/pull/38108/files#diff-7d968ebeea41e0a809c2ac3582c3d263703f1af61ec5b0d5a164660fad3638d9) because a `do_install` was renamed to `post_install` without merging the other `post_install`
> docker-credential-pass: Fix broken post_install

- srcpkgs/python3-pymediainfo/template
python3-importlib_metadata is a backport of new-ish importlib APIs for python
versions under 3.10 (3.8 in some cases). Since Void already has python 3.10,
the backport is completely unused and the package is already using the builtin
importlib.metadata (note the dot in place of the underscore).
https://github.com/sbraz/pymediainfo/commit/8af1511195f70ba2776bd9f1c15afbf6d2377b9b
@TinfoilSubmarine
`importlib.metadata` is mainly used to get the version, and that seems to be working perfectly. I used the library to get info on a png image and it seemed to work fine.
> python3-pymediainfo: remove unused dependency.

- srcpkgs/batsignal/patches/makefile.patch
- srcpkgs/batsignal/template
- I built this PR locally for my native architecture, x86_64{glibc,musl}
https://github.com/electrickite/batsignal/issues/21
> batsignal: update to 1.5.0.

- common/shlibs
- srcpkgs/libopensmtpd-devel
- srcpkgs/libopensmtpd/template
- srcpkgs/opensmtpd-filter-dkimsign/patches/cleanup-search-paths.patch
- srcpkgs/opensmtpd-filter-dkimsign/template
- Integration test with and a fully configured OpenSMTPD server: Passed DKIM test provided by https://appmaildev.com/en/dkim
- The software needs to be compiled
> New packages: libopensmtpd-0.7 opensmtpd-filter-dkimsign-0.5

- srcpkgs/ibus-anthy/patches/data-Update-era.t-with-2022.patch
- srcpkgs/ibus-anthy/patches/setup-Minimum-candidate-window-page-size-to-1.patch
- srcpkgs/ibus-anthy/template
- srcpkgs/python3-pycotap/template
+ This enables tests, although I can disable it again if you want.
+ swig is only needed when building with pygtk.
+ intltool is not needed by ibus-anthy.
+ This removes `--libexec=/usr/lib/ibus`. I'm not sure what it was needed for but most distros used to use it and have since removed it and the preferences popup doesn't work with it.
+ This uses `--with-layout=default` which is used by debian and fedora to tell ibus-anthy to use the default keyboard layout (otherwise it will always use JP).
+ This also moves ibus-anthy from Debian Anthy to anthy-unicode, this is what is also used by fcitx5-anthy.
In the basic testing I did, I didn't notice any issues, but please let me know if I missed something.
cc: @7185
> ibus-anthy: update to 1.5.14.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 5.52.0

- srcpkgs/gajim-omemo/template
- srcpkgs/gajim/template
- srcpkgs/python3-nbxmpp/template
> Update gajim, python3-nbxmpp, gajim-omemo

- srcpkgs/freerdp/template
the flag defaults to OFF even though cairo-devel was added as a makedep.
closes #38328
https://github.com/void-linux/void-packages/issues/38328#issuecomment-1197796758
> freerdp: add configure flag for cairo

- srcpkgs/qt5-speech/files/Qt5TextToSpeechConfig.cmake
- srcpkgs/qt5-speech/template
- srcpkgs/qt5-styleplugins/template
- srcpkgs/qt5/template
- qt5: update to 5.15.5+20220728.
- qt5-speech: update to 5.15.5.
[ci skip]
> qt5: update to 5.15.5

- srcpkgs/python3-mpv/template
- srcpkgs/python3-xvfbwrapper/template
python3-xvfbwrapper doesn't cross because [common/environment/build-style/python3-module.sh](https://github.com/void-linux/void-packages/blob/master/common/environment/build-style/python3-module.sh#L2) installs python3 as a makedepend instead of a hostmakedepend and I'm not sure if I should patch the build-style or add python3 to hostmakedepends and ignore that it's also in makedepends
> Update python3-mpv & fix tests

- srcpkgs/julius/template
> julius: update to 1.7.0

- srcpkgs/ImageMagick/template
- armv6l
It seems that upstream changed the way they pack the tarballs to 7.1.0-44, for version 7.1.0.44, so I created the var _release-prefix don't know if this was the best way.
> ImageMagick: update to 7.1.0.44.

- common/shlibs
- srcpkgs/mtxclient/template
- srcpkgs/nheko/template
- nheko: update to 0.10.0.
- mtxclient: update to 0.8.0.
> nheko: update to 0.10.0

- srcpkgs/gst-rtsp-server/template
As discussed on IRC, libcgroup-devel in makedepends is extraneous
> gst-rtsp-server: remove libcgroup-devel from makedepends

- srcpkgs/alacritty/template
- I tested the changes in this PR: Tested it with manually installing the two dependencies
Addresses issue #38391
> alacritty: Missing dependency libXcursor and libXrandr

- srcpkgs/kbd/template
- I built this PR locally for my native architecture, x86_64-{glibc,musl}
Not sure if I should keep the patches as it seems that lfs no longer uses ` kbd-2.0.2-backspace-1.patch` , but it applies fine so  I kept it. 
Shouldn't we try to get `fix-euro-symbol-es-keymap.patch` upstream ? I don't use a spanish keyboard so I am not sure if it is correct the keyboard that way or if it was a personal preference of whoever added the patch
> kbd: update to 2.5.1.

- Manual.md
Closes #32481
[ci skip]
- I tested the changes in this PR: **N/A**
> Manual.md: recommend keeping systemd units

- srcpkgs/micro/template
The v2.0.11 update changed the way resources are bundled, now requiring an
additional step to 'generate' the bundle. Since I happened to only test the
original update on files that I have custom syntax for, I only realised the
presence of the regression after the update got merged (#38402).
> micro: fix broken resource bundling.

- srcpkgs/mercury-libs
- srcpkgs/mercury-tools
- srcpkgs/mercury/template
- x86_64-musl
- i686-glibc
I have marked the parallel toolchain options disabled for musl, as in the last those have had issues and I have not tested that configuration enough to be sure it works properly.
> New package: mercury-22.01_1, mercury-libs-22.01_1, mercury-tools-22.01_1

- .github/workflows/stale.yml
We need a way to exclude issues form autoclosing. Or stop autoclosing any issues.
PR #36411 was built with excluding [`label:bug -label:needs-testing`](https://github.com/void-linux/void-packages/issues?q=is%3Aopen+is%3Aissue+label%3Abug+-label%3Aneeds-testing+) in mind, but this is not expressible with workflow. Let `bug` label make issues not stale.
> .github/workflows/stale.yml: do not close issues labelled as bug

- srcpkgs/scons/template
- x86_64-musl
I also 'adopted' the package as it was orphaned. I still use it for a few packages and would be willing to maintain it
> scons: update to 4.4.0

- srcpkgs/hatch/template
- srcpkgs/hatchling/template
- srcpkgs/python3-editables/template
I've tried building and testing all packages that depend on hatchling, and except for hatch everything went smoothly. The test failures in hatch don't look very problematic to me though. Should we just deselect those?
Log: https://pastebin.com/raw/uywdGiZY
> hatch-1.3.1/hatchling-1.6.0

- srcpkgs/php8.1/patches/fix-manpages.patch
- srcpkgs/php8.1/template
The changelog URL points to the changelog for $version because the
changelog in the master branch contains the details of many alpha and RC
releases, which makes it difficult to find the changelog corresponding
to the current pkgver.
I've also changed the `.so` directives in man pages to point to the
correct man pages. Previously they pointed to the man pages of php 7.4
> php8.1: update to 8.1.8, add changelog URL, fix man pages

- srcpkgs/wireless_tools/template
> wireless_tools: fix distfiles download

- srcpkgs/libxfce4ui/patches/vapi-deps.patch
- srcpkgs/libxfce4ui/template
- srcpkgs/xfce4-panel/patches/valadeps.patch
- I tested the changes in this PR: **briefly** only build tested
vala was added to its build deps somewhere in the dependency tree, and the build started failing
> libxfce4ui: generate vala bindings

- CONTRIBUTING.md
I've had to find these instructions time and time again for requesting testing from people, so I figured why not make it part of our documentation. Maybe it will help get more users involved with testing.
Open to suggestions on wording, grammar, missing info, etc.
> CONTRIBUTING.md: add instructions for testing PRs

- srcpkgs/apt/template
> apt: update to 2.5.2

- srcpkgs/swayimg/template
> New package: swayimg-1.8

- .github/workflows/stale.yml
#38272 used wrong format, and now the action is failing - https://github.com/void-linux/void-packages/actions/runs/2807256939
@Chocimier @classabbyamp
> .github/workflows/stale.yml: fix format of exempt-issue-labels

- srcpkgs/vscode/template
> vscode: update to 1.70.0.

- srcpkgs/libnotify/template
> libnotify: update to 0.8.1.

- srcpkgs/spacefm/template
- I tested the changes in this PR: **briefly** only build tested
> spacefm: remove unused gtk2 build dep

- srcpkgs/mumble/files/mumble-server/log/run
- srcpkgs/mumble/files/mumble-server/run
- srcpkgs/mumble/patches/config.patch
- srcpkgs/mumble/template
* add qt5-plugin-sqlite to dependencies
otherwise, running mumble-server with the default configuration fails
<F>2022-05-21 19:47:53.080 ServerDB: Database driver QSQLITE not available
* add a system service
* remove murmur-user-wrapper
> mumble: improve murmur package

- srcpkgs/luarocks-lua53/template
> luarocks-lua53: update to 3.9.1

- srcpkgs/python3-cached-property/template
> python3-cached-property: update to 1.5.2.

- srcpkgs/xarchiver/patches/doubleclick.patch
- srcpkgs/xarchiver/template
fixes #38487
- I tested the changes in this PR: **briefly** (built the package)
@TeusLollo, can you [test this](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#testing-pull-requests)?
> xarchiver: fix double-clicking regression

- srcpkgs/gnutls/template
- I built this PR locally for my native architecture, (Void 5.18.16_1 x86_64 GenuineIntel)
- x86_64
> gnutls: update to 3.7.7. (CVE-2022-2509)

- srcpkgs/claws-mail/template
Since `--disable-python-plugin` is set, this dependency isn't used (it should be python3 anyway).
> claws-mail: drop unused python-devel in hostmakedepends.

- srcpkgs/mate-settings-daemon/template
> mate-settings-daemon: remove alsa-plugins-pulseaudio dependency

- srcpkgs/lighttpd/template
**NO**
- I built lighttpd 1.4.66 for arm_cortex-a9 against OpenWrt master
> lighttpd: update to 1.4.66

- srcpkgs/python3-cairocffi/template
- srcpkgs/python3-xcffib/template
- srcpkgs/qtile/template
Closes #14373
I tried to build it for armv7l but failes with
```
armv7l-linux-gnueabihf-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -g -fdebug-prefix-map=/builddir/Python-3.10.5=. -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe -g -fdebug-prefix-map=/builddir/Python-3.10.5=. -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv7-a -mfpu=vfpv3 -mfloat-abi=hard -I/usr/armv7l-linux-gnueabihf/usr/include …
```
> New package: qtile-0.21.0

- common/build-style/go.sh
- srcpkgs/aws-vault/template
- srcpkgs/circleci-cli/template
- srcpkgs/coredns/template
- srcpkgs/gotify-cli/template
- srcpkgs/gotify-server/template
- srcpkgs/v2ray/template
- aws-vault: remove -w -s from go_ldflags
- added in #21634
- circleci-cli: remove -w -s from go_ldflags
- added in #25101
- coredns: remove -w -s from go_ldflags
- added in #23578
- gotify-cli: remove -w -s from go_ldflags
- added in #34653
- gotify-server: remove -w -s from go_ldflags
- added in #34653
- v2ray: remove -w -s from go_ldflags
- added in #31653
- not revbumping because of build issues with `quic-go` (see below)
- common/build-style/go.sh: error if -s/-w in go_ldflags
- this does not fit in an xlint because of multiline-string handling woes
These [go linker flags](https://pkg.go.dev/cmd/link) are:
-s   Omit the symbol table and debug information.
-w   Omit the DWARF symbol table.
both are not necessary because xbps-src should strip binaries itself
it's not necessary to check …
> [RFC] various: remove -s/-w from go_ldflags

- srcpkgs/gnome-nibbles/template
> gnome-nibbles: remove unused intltool makedep

- srcpkgs/lksctp-tools/template
- armv6l
Orphaning the package because git blame tells me that is pullmoll the creator of the package.
Updating the package to make it build with #38412
> lksctp-tools: update to 1.0.19.

- srcpkgs/signify/template
- srcpkgs/signify/update
Edit: I also added changelog and removed the UPDATE file, which doesn't seem correct anymore.
Add needed libmd makedepend and tar checkdepend,
use vsed instead of sed for the file patching,
and use sed instead of head to extract a nicer LICENSE file
> signify: update to 31.

- srcpkgs/python3-Werkzeug/template
> python3-Werkzeug: update to 2.2.2.

- srcpkgs/bluefish/template
> bluefish: build with python3-devel.

- srcpkgs/python3-Flask/template
This need `python3-Werkzeug >= 2.2.2` to check and run
> python3-Flask: update to 2.2.2.

- srcpkgs/ruby-thor/template
- srcpkgs/ruby-tmuxinator/patches/xdg.patch
- srcpkgs/ruby-tmuxinator/template
- srcpkgs/ruby-xdg/template
I've also updated the necessary dependencies and switched from gem to gemspec to apply the patch for xdg. 
That patch is copied from [AUR](https://aur.archlinux.org/cgit/aur.git/tree/xdg.patch?h=tmuxinator).
With the patch ruby-xdg versions >=4.5.0 are working properly with tmuxinator-3.0.5.
> ruby-tmuxinator: update to 3.0.5.

- CONTRIBUTING.md
- a few small formatting/grammar changes/corrections
- document cloning with https, github-cli
- document using non-fork-master branch for changes
- document not using web ui for commiting
- add example commits for non-package changes
- add xrevbump
- reorder so testing build locally is before committing (more chronological)
- update xtools URL
> CONTRIBUTING.md: add info about updating templates, misc other changes

- srcpkgs/android-udev-rules/template
> android-udev-rules: update to 20220611.

- srcpkgs/farstream/patches/fix_tests_with_gupnp_1.2.patch
- srcpkgs/farstream/patches/nice-agent-keep-main-context-alive.patch
- srcpkgs/farstream/template
- I tested the changes in this PR: **briefly** (ran extended tests)
python headers haven't been needed since Farstream 0.2: https://gitlab.freedesktop.org/farstream/farstream/-/commit/73891c28fa27d5e65a71762e826f13747d743588
The tests were already broken prior to this change, but the patch I added gets them building, but then they fail when they run...
> farstream: drop unused python-devel in *depends, fix tests.

- srcpkgs/ktoblzcheck/template
- builds fine, no difference in generated package except python lib location, revdeps build fine still
> ktoblzcheck: move to python3

- srcpkgs/gnome-desktop/template
- srcpkgs/gnome-shell/template
- srcpkgs/mutter/template
https://discourse.gnome.org/t/gnome-42-4-released/10694
> gnome-desktop, mutter, gnome-shell: update to 42.4

- srcpkgs/khal/patches/01-remove-unecessary-dependcy.patch
- srcpkgs/khal/template
Since version 0.10.5 there is no longer a `__khal` file. This is why I deleted line 26.
> khal: update to 0.10.5.

- srcpkgs/hplip/template
- I tested the changes in this PR: NO
> hplip: add missing build dependency

- srcpkgs/kubernetes/template
`kubeadm init` needs conntrack, otherwise this fatal error happens
```
error execution phase preflight: [preflight] Some fatal errors occurred:
[ERROR FileExisting-conntrack]: conntrack not found in system path
```
`xi conntrack-tools` fixes the error.
> kubernetes: depends+=conntrack-tools

- srcpkgs/jrnl/template
- aarch64-musl
- armv7l
- armv6l-musl
> jrnl: update to 3.0

- srcpkgs/qtile/template
This addition allow to select qtile in dm's like lightdm.
> qtile: Added .desktop file

- srcpkgs/fotoxx/template
- aarch64-musl
- armv7l
- armv6l-musl
> fotoxx: update to 22.30.

- srcpkgs/rofi/template
Adding @classabbyamp as the maintainer of the package as talked about in the irc ( current maintainer= of rofi is the upstream dev, who hasn't touched it since 2015)
> rofi: update to 1.7.4.

- srcpkgs/lxc/patches/01-meson-docbook2x.patch
- srcpkgs/lxc/template
- srcpkgs/meson/patches/10702.patch
- srcpkgs/meson/template
Switch to meson had a small casualty.
Rebuild with patched meson.
Also simplify the docbook2x patch.
https://github.com/mesonbuild/meson/pull/10702
https://github.com/lxc/lxc/pull/4177
Closes #38682
> backport meson patch to set lxc-user-nic suid bit

- srcpkgs/nutty/patches/use-system-speedtestcli.patch
- srcpkgs/nutty/template
Removes python2 remnants, see #38229
@LinArcX
> nutty: devendor speedtest-cli.

- srcpkgs/starship/template
> starship: update to 1.10.1

- srcpkgs/pex/template
This template effectively enforces `make_check=no` since this has `build_style=python3-pep517` with no explicit `checkdepends`. Running the tests as is requires [bootstrapping different python interpreters](https://github.com/pantsbuild/pex/blob/v2.1.103/pex/testing.py#L453-L459) by building them from source via `pyenv`. I couldn't figure out if there's a way to run the tests only with system installed python. Instead I installed it and run the commands mentioned in their quick start guide which seem to work as intended.
> pex: update to 2.1.103.

- srcpkgs/grip/template
Flask removed `safe_join` in their [2.1.0](https://flask.palletsprojects.com/en/2.2.x/changes/#version-2-1-0) release, which breaks the current version of grip.
- aarch64-musl
- armv7l
- armv6l-musl
- armv6l
- i686
- x86_64-musl
> grip: update to 4.6.1.

- srcpkgs/zellij/template
> zellij: update to 0.31.2

- srcpkgs/busybox/patches/0001-libbb-sockaddr2str-ensure-only-printable-characters-.patch
- srcpkgs/busybox/patches/0002-nslookup-sanitize-all-printed-strings-with-printable.patch
- srcpkgs/busybox/template
- This two patches are not upstream, made by Alpine Linux Team, but they are reported in https://bugs.busybox.net/show_bug.cgi?id=14811
- Source: https://git.alpinelinux.org/aports/plain/main/busybox/0002-nslookup-sanitize-all-printed-strings-with-printable.patch
- Source:  https://git.alpinelinux.org/aports/plain/main/busybox/0001-libbb-sockaddr2str-ensure-only-printable-characters-.patch
- Check CVE: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28391
>  busybox: add patches for CVE-2022-28391

- srcpkgs/dnscrypt-proxy/template
> dnscrypt-proxy: update to 2.1.2

- srcpkgs/zellij/template
> zellij: update to 0.31.3

- srcpkgs/dragon/template
- I built this PR locally for my native architecture (x86_64-musl)
- The description is misleading as the package also works under Wayland since it's build on top of GTK3. I confirmed that it's working under ``sway-1.7_1``
> dragon: improve description

- srcpkgs/gnome-software-devel
- srcpkgs/gnome-software/template
xbps doesn't support packagekit, so gnome-software currently only works with flatpaks, but I think it's still very useful.
> New package: gnome-software-42.4.

- srcpkgs/boinc/template
The `boinc` user is created for the boinc package, but not for boinc-nox which breaks it.
> boinc-nox: Add the boinc user to boinc-nox

- srcpkgs/prometheus/template
> prometheus: update to 2.38.0.

- srcpkgs/flrig/template
> New package: flrig-1.4.7

- srcpkgs/gopass/template
bumping the version to keep it up to date with upstream, 1.13.0 was released November 2021.
> gopass: update to 1.14.4.

- srcpkgs/ykpers/template
The current version which uses the nonexistent `releases` doesn't build.
> ykpers: fix distfile

- srcpkgs/libarchive/patches/fix-build-glibc-2.36.patch
> libarchive: fix build for glibc 2.36

- srcpkgs/ntp/patches/compat-glibc-2.34.patch
https://bugs.ntp.org/show_bug.cgi?id=3741
> ntp: fix build with glibc 2.34

- srcpkgs/samba/patches/fix-glibc-2.36.patch
> samba: fix build for glibc 2.36

- srcpkgs/qemu/patches/fix-compat-glibc-2.36.patch
> qemu: fix build for glibc 2.36

- common/travis/license.lst
- srcpkgs/spdx-licenses-list/template
Also:
- update common/travis/license.lst.
> spdx-licenses-list: update to 3.18.

- srcpkgs/python3-jaraco.functools/template
> python3-jaraco.functools: update to 3.5.1.

- common/shlibs
- srcpkgs/gbinder-python/template
- srcpkgs/libgbinder-devel
- srcpkgs/libgbinder/template
- srcpkgs/libglibutil-devel
- srcpkgs/libglibutil/template
- srcpkgs/python3-pyclip/template
- srcpkgs/waydroid/INSTALL
- srcpkgs/waydroid/files/README.voidlinux
- srcpkgs/waydroid/files/waydroid-container/finish
- srcpkgs/waydroid/files/waydroid-container/run
- srcpkgs/waydroid/template
- I built this PR locally for my native architecture
- `x86_64-glibc` / `x86_64-musl`
- `i686` (tested with `linux5.15` & `linux5-18`, both for some odd reason needed a rebuild twice, they failed on `cd ${DESTDIR}/usr/lib/modules/${_kernver}` in their templates initially)
- `aarch64` (tested by @CameronNemo and @Johnnynator, thanks!)
Test running Waydroid on the following supported archs:
- `armv7l` (glibc or musl)
Supersedes #33135 and closes #33133.
> New package: waydroid-1.3.0

- srcpkgs/schroot/patches/musl.patch
- srcpkgs/schroot/template
**Fix CVE-2022-2787 and update to Debian Bullseye package**
> schroot: update to 1.6.10-12+deb11u1. CVE-2022-2787

- common/shlibs
- srcpkgs/neomutt/template
- srcpkgs/rocksdb/patches/toku_time.patch
- srcpkgs/rocksdb/template
- I tested the changes in this PR: **Briefly** (recompiled neomutt and used it fine)
- I built this PR locally for my native architecture, x86_64-{glibc,musl}
I have also linked rockdb with others compression libraries.
Not sure if another packages need to be rebuilt as well because of the SONAME update, need help on a good way to find this. 
To find the packages that needed to be recompiled I simply used `grep -R rocksdb-devel srcpkgs/` not sure if this is the correct way to do it.
~Can't make armv6l work, going to need help on this arch.~
> rocksdb: update to 7.4.5.

- srcpkgs/chroot-grep/template
The regular grep package is 3.7, not sure if there is a specific reason to keep this on 3.3, so feel free to let me know.
> chroot-grep: update to 3.7.

- srcpkgs/fonttools/template
> fonttools: update to 4.36.0.

- srcpkgs/bindfs/template
> bindfs: update to 1.17.0.

- srcpkgs/glab/template
- srcpkgs/glab/update
> glab: update to 1.22.0.

- srcpkgs/libostree/patches/fix-compat-glibc-2.36.patch
> libostree: fix build for glibc 2.36

- srcpkgs/liburing/template
> liburing: update to 2.2.

- srcpkgs/gupnp/template
Fixes build failure due to missing dependency.
> gupnp: needs docbook-xsl in hostmakedepends

- common/xbps-src/shutils/update_check.sh
Exhaustive verification is cheap due to low volume
`grep -lr --include template codeberg srcpkgs/ | cut -d/ -f2 | xargs -n1 ./xbps-src update-check`
On current master `mdcat` and `nsxiv` reports `NO VERSION`.
> common/xbps-src/shutils/update_check.sh: tweak url and rx for codeberg

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 5.56.0.

- srcpkgs/strongswan/template
I personally use this package and have been using my locally built updated version for the last 3-4 days without noticing any difference.
This update also upgrades the python version in `hostmakedepends` to python3 as upstream [switched to it](https://github.com/strongswan/strongswan/commit/3e2841572bd6f5dfd0d3641472f00eefa4d83d7a) a few minor versions ago.
> strongswan: update to 5.9.7.

- srcpkgs/gnome/template
> gnome: remove network-manager-applet from -apps

- srcpkgs/ImageMagick/template
Added support for openexr
- armv6l
> ImageMagick: update to 7.1.0.46.

- srcpkgs/mate-themes/template
It's suck to pull the whole gtk+ in just to use Mate,
which is GTK+3 only.
This is not about minimalism or whatsoever, I just want to keep my system away from GTK+
> mate-themes: Don't pull gtk+ in

- srcpkgs/jamulus/template
`qt5-multimedia-devel` should now be explicitly listed in `makedepends`. I've also updated `maintainer` as I no longer use that email / go by that name anymore.
> jamulus: update to 3.9.0

- srcpkgs/plymouth/patches/fix-glibc-2.36.patch
- srcpkgs/plymouth/template
This adds a patch for fixing build for glibc 2.36.
> plymouth: update to 22.02.122.

- srcpkgs/libproxy/template
Fixes build with gcc12:
```
In file included from /builddir/libproxy-0.4.15/libproxy/extension_config.hpp:24,
from /builddir/libproxy-0.4.15/libproxy/proxy.cpp:28:
/builddir/libproxy-0.4.15/libproxy/url.hpp:53:32: error: ISO C++17 does not allow dynamic exception specifications
53 |         url(const string& url) throw (parse_error);
|                                ^~~~~
/builddir/libproxy-0.4.15/libproxy/url.hpp:56:36: error: ISO C++17 does not allow dynamic exception specifications
56 |         url& operator=(string url) throw (parse_error);
|                                    ^~~~~
/builddir/libproxy-0.4.15/libproxy/extension_config.hpp:34:61: error: ISO C++17 does not allow dynamic exception specifications
34 |         virtual …
```
> libproxy: update to 0.4.18.

- srcpkgs/libqrtr-glib/template
> libqrtr-glib: update to 1.2.2.

- srcpkgs/bootiso/patches/new-exfat.patch
- srcpkgs/bootiso/template
> bootiso: depends on exfatprogs

- common/build-helper/python3.sh
- common/build-style/python3-module.sh
- common/environment/build-style/python3-module.sh
- srcpkgs/brltty/template
- srcpkgs/i2c-tools/template
- srcpkgs/libpwquality/template
- srcpkgs/tlsh/template
- common/build-helper/python3.sh: add python3 helper
- common/{,environment}/build_style/python3.sh: use python3 build_helper
- brltty: use python3 build_helper, clean up
- i2c-tools: use python3 build_helper
- libpwquality: use python3 build_helper
- tlsh: use python3 build_helper
My hope with this is to help with cross-building non-python packages that have python3 bindings/modules, but it can be used similar to the `rust` `build_helper` for various common constants, if needed.
One thing I'm not sure on is the usage with the `python3-module` `build_style`. It would cut down on the need to keep those env var definitions up-to-date in multiple places, but I'm open to opinions about it.
There's probably more packages that are marked `nocross`/`broken` because of python3 cross stuff that I …
> [RFC] create build_helper for python3 cross-building

- srcpkgs/anydesk/template
- reported by Sun Saych @ voidlinux tg.
> anydesk: add missing run-time dependency on gtkglext.

- srcpkgs/gnome-software/patches/0001-only-associate-flatpak-mimetypes.patch
- srcpkgs/gnome-software/template
The gnome-software package can only be used for flatpaks, opening rpms,
debs and other package archives will only result in an error message.
- I tested the changes in this PR: **NO** (todo)
> gnome-software: don't open irrelevant mimetypes

- srcpkgs/fotoxx/template
- aarch64-musl
- armv7l
- armv6l-musl
> fotoxx: update to 22.31.

- srcpkgs/gc/template
Other cleanups:
* Remove --enable-mmap (which is the default configure option now)
* No longer depends on libatomic_ops (provided the compiler is gcc or clang)
* Fix license (it is MIT, not GPL)
* Remove unneeded CFLAGS
* Set maintainer
- I built this PR locally for my native architecture, (x64)
> gc: Update to 8.2.2

- srcpkgs/python3-pikepdf/template
> python3-pikepdf: update to 5.6.1.

- srcpkgs/nix/patches/0001-manual-build-without-nix-installation.patch
- srcpkgs/nix/patches/0002-manual-cross-build.patch
- srcpkgs/nix/template
While we're at it, cross compile
> nix: do not touch outside {build,dest}dir

- srcpkgs/python3-jsonschema/template
> python3-jsonschema: update to 4.15.0.

- srcpkgs/python3-ansible-lint/template
Another release, another deselected test case. This is not going good, I'll need to look deeper into what's going wrong here at some point. It's working great on my machine, and *most* of the test cases also work perfectly fine, but a few just don't.
I've tried the same approach as in `python3-jsonschema` for the issues failing due to not finding the ansiblelint module or ansible-lint binary, but it didn't help at all, just caused more tests that had to be ignored for other reasons.
> python3-ansible-lint: update to 6.5.2.

- srcpkgs/helix/template
> helix: update to 22.08.1

- srcpkgs/xsel/template
Fixing upstream and distfile download links
Found this as a possible "changelog":
- https://raw.githubusercontent.com/kfish/xsel/master/release_notes/xsel-1.2.0.txt
I wasn't sure if I should added it being a separate file per release
> xsel: fix dead distfile and upstream webpage

- srcpkgs/wireproxy/template
- I built this PR locally for my native architecture, amd64
> wireproxy: update to 1.0.5

- srcpkgs/liquidwar/patches/python3-conversion.patch
- srcpkgs/liquidwar/template
Added patch from debian (with small tweaks) to convert the documentation
generator script from python2 to python3. Related to #38229
Added texinfo to hostmakedeps. Somehow, something changed outside the template
since last version/revbump that caused info files to no longer be built.
Also fixed an xlint in the description.
> liquidwar: move to python3, cleanup.

- srcpkgs/fish-shell/template
> fish-shell: update to 3.5.1.

- srcpkgs/nerd-fonts/template
Explanation: I did not test every single font included in this package, but I did test several.
> nerd-fonts: update to 2.2.1

- srcpkgs/xkeyboard-config/patches/fix_backlashes.patch
- srcpkgs/xkeyboard-config/template
use backslashes instead of slashes for line continuation
This fixes 324
(https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/324)
- armv6l
> xkeyboard-config: fix upstream issue.

- srcpkgs/fonttools/template
> fonttools: update to 4.37.1.

- srcpkgs/rpi-firmware/template
- srcpkgs/rpi-kernel/template
- srcpkgs/rpi2-kernel/template
- srcpkgs/rpi3-kernel/template
- srcpkgs/rpi4-kernel/template
I've built rpi4-kernel and rpi-firmware, and created an image for my CM4. It boots, haven't tested anything more so far. I sadly don't have any other Pi products to test on right now, so I'd need some other people to help on this.
cc @Piraty as current maintainer
Resolves https://github.com/void-linux/void-mklive/issues/264
> rpi-kernel,rpi-firmware: update to 5.15.61. [ci skip]

- srcpkgs/stunnel/template
The 5.60 distfile no longer exists. This update makes stunnel buildable.
Ping maintainer: @Vaelatern
> stunnel: update to 5.65.

- common/shlibs
- srcpkgs/SPIRV-Headers/template
- srcpkgs/SPIRV-Tools/template
- srcpkgs/Vulkan-ValidationLayers/template
- srcpkgs/glslang/template
- srcpkgs/retroarch/template
- srcpkgs/shaderc/patches/fix-glslang-link-order.patch
- srcpkgs/shaderc/template
> SPIRV, glslang, shaderc: update to 2022.2.

- srcpkgs/ddcutil/template
Recently, this was removed from depends, and added to makedepends,
but (at least on x86_64-musl) it is not picked up automatically.
@lemmi
> ddcutil: add back depends on i2c-tools

- srcpkgs/srb2/template
This fixes a build failure introduced by:
https://github.com/void-linux/void-packages/commit/e14cf6cc7a85fcde7fb3fdb2cdba117bede8bb19
The previously failing line of code:
https://git.do.srb2.org/STJr/SRB2/-/blob/next/src/Makefile.d/util.mk#L72-73
> srb2: fix build with latest xbps-src

- srcpkgs/python3-psutil/template
> python3-psutil: update to 5.9.2.

- srcpkgs/blueprint-compiler/template
Tested with #37132, new giara build still works as expected when built with blueprint-compiler-0.4.0_1
> blueprint-compiler: update to 0.4.0.

- srcpkgs/python3-betamax-matchers/template
- srcpkgs/python3-betamax/template
- srcpkgs/python3-github3/template
- New package: python3-betamax-0.8.1
- New package: python3-betamax-matchers-0.4.0
- python3-github3: update to 3.2.0.
> python3-github3: update to 3.2.0.

- srcpkgs/phpMyAdmin/template
- srcpkgs/phpMyAdmin/update
> phpMyAdmin: update to 5.2.0, fix update check.

- srcpkgs/qtractor/template
> qtractor: update to 0.9.28

- srcpkgs/atf-rk3328-bl31/template
- srcpkgs/atf-rk3328-bl31/update
- srcpkgs/rock64-uboot/template
- atf-rk3328-bl31: update to 2.7
- rock64-uboot: update to 2022.07
> rock64 uboot

- srcpkgs/ejabberd/template
- srcpkgs/elixir/template
- srcpkgs/erlang/template
- srcpkgs/lfe/template
- srcpkgs/rebar3/template
Some tests fail due to rootdir = "/usr/lib64/erlang" but I don't think it matters. Workarounds welcome.
cc @Vaelatern due to ejabberd bump.
> erlang: update to 25.0.2.

- common/travis/xpkgdiff.sh
it works without this, but it uses repo-default by default, so this should maybe speed some things up.
see also leahneukirchen/xtools#261
> common/travis/xpkgdiff.sh: use newly-added arguments

- srcpkgs/vaultwarden-web/template
- srcpkgs/vaultwarden-web/update
- srcpkgs/vaultwarden/files/vaultwarden/log/run
- srcpkgs/vaultwarden/files/vaultwarden/run
- srcpkgs/vaultwarden/patches/config.patch
- srcpkgs/vaultwarden/template
> New packages: vaultwarden-web-2022.8.1, vaultwarden-1.25.1

- srcpkgs/python3-CherryPy/template
- srcpkgs/python3-jaraco.collections/template
- srcpkgs/python3-path/template
> python3-CherryPy: update to 18.8.0.

- srcpkgs/android-tools/template
CC @Johnnynator (maintainer)
* Added e2fsdroid and ext2simg
* Fixed build with GCC 12
* Bumped minimum required CMake version to 3.13
> android-tools: update to 31.0.3p2.

- srcpkgs/crispy-doom/template
- I tested the changes in this PR: **YES*
- I built this PR locally for my native architecture, (X86-64-LIBC)
- aarch64-musl
- armv7l
- armv6l-musl
> crispy-doom: update to 5.12.0.

- srcpkgs/rpi-firmware/template
This took some figuring out, there's no documentation anywhere except a couple commit messages and blog posts.
- https://picockpit.com/raspberry-pi/raspberry-pi-zero-2-w-wifi-chipset-speeds-monitor-mode/
- https://github.com/RPi-Distro/firmware-nonfree/issues/24
- https://github.com/RPi-Distro/firmware-nonfree/commit/bda9207acee945633464e89614f3717b856579b5
```
[  +0.105226] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43436-sdio for chip BCM43430/2
[  +0.001051] usbcore: registered new interface driver brcmfmac
[  +0.003262] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43436-sdio.raspberrypi,model-zero-2-w.bin failed with error -2
[  +0.030631] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43436-sdio for chip …
```
> rpi-firmware: add firmware for zero 2w

- srcpkgs/openjdk7-bootstrap/files/dist_patches_glibc.txt
- srcpkgs/openjdk7-bootstrap/files/dist_patches_musl.txt
- srcpkgs/openjdk7-bootstrap/files/icedtea-pointer-comparison-gcc12.patch
> openjdk7-bootstrap: fix build for gcc12

- srcpkgs/xf86-video-vmware/patches/fix-compat-gcc12.patch
- srcpkgs/xf86-video-vmware/template
Revbump since this is a bugfix from upstream and does slightly change behavior.
> xf86-video-vmware: fix build for gcc12

- srcpkgs/openssh/template
> openssh: relax warnings for gcc12

- srcpkgs/grub/patches/fix-compat-binutils-2.36.patch
- srcpkgs/grub/template
> grub: fix build for binutils 2.36

- srcpkgs/linux-tools/patches/binutils-add-compat-check.patch
- srcpkgs/linux-tools/patches/binutils-disasm-compat.patch
- srcpkgs/linux-tools/patches/bpf_jit_disasm-binutils-2.39.patch
- srcpkgs/linux-tools/patches/bpftool-binutils-2.39.patch
- srcpkgs/linux-tools/patches/perf-binutils-2.39.patch
> linux-tools: fix build for binutils 2.39

- srcpkgs/btrfs-progs/template
Seems to work fine for me, although let me know if there are any issues.
> btrfs-progs: update to 5.19.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 5.58.0.

- common/shlibs
- srcpkgs/libnpupnp/template
- srcpkgs/libupnpp/template
- srcpkgs/mpd/template
- srcpkgs/upmpdcli/template
> libnpupnp: update to 5.0.0

- srcpkgs/source-sans-pro/template
In addition to version update, the font repository seems to have been moved from `adobe-fonts/source-sans-pro` to `adobe-fonts/source-sans`. The change was applied to the template. The list of package files was checked to be identical with the previous version of the package.
Fixes one of the issues in #39072.
- x86_64-musl (masterdir)
> source-sans-pro: update to 3.046.

- srcpkgs/mdocml/files/void.css
- srcpkgs/mdocml/template
this has no meaning for void, so let's hide it
also http -> https for homepage/distfiles
> mdocml: hide architecture selector in void.css

- srcpkgs/go/template
See: https://go.dev/doc/devel/release#go1.19
> go1.19.1 (released 2022-09-06) includes security fixes to the net/http and net/url packages, as well as bug fixes to the compiler, the go command, the pprof command, the linker, the runtime, and the crypto/tls and crypto/x509 packages.
> go: update to 1.19.1.

- common/shlibs
- srcpkgs/mtxclient/template
- srcpkgs/nheko/template
- mtxclient: update to 0.8.1.
- nheko: update to 0.10.1.
> nheko: update to 0.10.1.

- srcpkgs/zellij/template
> zellij: update to 0.31.4

- srcpkgs/gtklock/template
> gtklock: update to 1.3.6

- srcpkgs/gtk4/template
* move more example applications to -demo
* move build tools to -devel
now the gtk4 package is 19MB when installed instead of 42MB
> gtk4: update to 4.8.0.

- srcpkgs/betterlockscreen/patches/use-loginctl.patch
- srcpkgs/betterlockscreen/template
betterlockscreen: update to 4.0.4
> betterlockscreen: update to 4.0.4.

- srcpkgs/polari/template
* remove mozjs78 from checkdepends - polari only needs mozjs because of gjs
and gjs already depends on mozjs (currently v91)
* add missing, drop unused dependencies
* use the gir build helper
> polari: fix dependencies

- common/hooks/pre-pkg/99-pkglint.sh
- srcpkgs/coturn/template
There is only a single package (`coturn`) using the directory because the `--manprefix` configure argument from the `gnu-configure` build style uses `/usr/share/man` while the configure script expected `/usr/share`.
> xbps-src: do not allow `/usr/share/man/man`

- srcpkgs/luakit/patches/Makefile.patch
- srcpkgs/luakit/template
I've updated the package version and recreated the makefile patch since the patching failed with the new version. x86_64 package file list was confirmed to be identical to the previous package version.
Update in response to #39072.
- x86_64-musl (masterdir)
> luakit: update to 2.3.1.

- srcpkgs/python3-jq/template
> python3-jq: update to 1.2.3.

- srcpkgs/gnome-bluetooth/template
> gnome-bluetooth: update to 42.2.

- common/shlibs
- srcpkgs/boost/patches/feature-test-macros.patch
- srcpkgs/boost/template
- srcpkgs/libtorrent-rasterbar/template
- srcpkgs/qbittorrent/template
- boost: fix segfault in asio+align module.
- libtorrent-rasterbar: rebuild to fix segfault.
> Fix qbittorrent crash on musl

- srcpkgs/mozjs91/update
This doesn't update the package from `91.7.1` to `91.13.0` but at least we know updates **are available** :)
> mozjs91: fix update-check

- srcpkgs/zfs/patches/0003-dracut-fix-typo-in-mount-zfs.sh.in.patch
- srcpkgs/zfs/template
- I built this PR locally for my native architecture, (x84_64-glibc)
#####
Without this patch the dracut module can failed to mount the root partition.
PS: I am not the author of the patch. I extracted it from the official zfs repo (`git format-patch -1 07f2793e869196fcbcd5057d9ada377674262fe3`)
> zfs: downstream patch (dracut fix typo in mount-zfs.sh)

- srcpkgs/base-files/files/90-usbmon.rules
- srcpkgs/base-files/files/group
- srcpkgs/base-files/template
this will be useful for wireshark users, whose official documentation says to manually set an ACL for /dev/usbmon* to use it with USB devices. This should make it easier.
Source: https://src.fedoraproject.org/rpms/wireshark/blob/rawhide/f/90-wireshark-usbmon.rules
> base-files: add usbmon group, udev rules

- srcpkgs/elogind/patches/polkit.patch
- srcpkgs/elogind/template
- armv6l
Going to test on a vm using seatd to see if the errors still occurs 
@Gottox in case you didn't see the message IRC could you check if the problem with libseat still occurs ? Ok my quick test it doesn't, but to be honest I don't have a lot of experience it with
> elogind: update to 246.10.

- srcpkgs/waydroid/template
> waydroid: update to 1.3.2.

- srcpkgs/rusty-diceware/template
> rusty-diceware: update to 0.3.9.

- srcpkgs/python3-yamllint/template
> python3-yamllint: update to 1.28.0.

- srcpkgs/xsecurelock/template
- I built this PR locally for my native architecture, glibc
> xsecurelock: update to 1.8.0

- srcpkgs/lsd/template
> lsd: update to 0.23.1

- srcpkgs/id3lib/patches/fix-abi.patch
- srcpkgs/id3lib/patches/test-fix.patch
- srcpkgs/id3lib/template
- srcpkgs/kid3/template
id3/globals.h has a typedef for bool which is incompatible with c99 stdbool.
This is a known issue, but upstream is effectively unmaintained.
See [this thread](https://sourceforege.net/p/id3lib/mailman/message/30500558/) from upstream.
This only seems to be an issue for castget while building, and they have already switched to using taglib for the next release.
Castget [issue](https://github.com/mlj/castget/issues/47).
> id3lib: patch for c99 bool

- srcpkgs/exiftool/template
- aarch64-musl
- armv7l
- armv6l-musl
> exiftool: update to 12.45.

- .github/workflows/cycles.yml
- common/scripts/lint-commits
- common/scripts/lint-version-change
- common/travis/changed_templates.sh
- common/travis/fetch_upstream.sh
> CI: check reverts

- srcpkgs/kcov/patches/0001-Fix-build-with-binutils-2.39.patch
This patch was submitted upstream: https://github.com/SimonKagstrom/kcov/pull/383
> kcov: fix build with binutils 2.39

- srcpkgs/qflipper/patches/fix-build-32-bit.patch
- srcpkgs/qflipper/template
- disable building on i686 and point to upstream bug: https://github.com/flipperdevices/qFlipper/issues/120
- add configure args that upstream recommends: https://github.com/flipperdevices/qFlipper#standalone-build
- add configure arg to disable update checker
> qflipper: update to 1.1.3.

- common/environment/configure/debug-debug-prefix-map.sh
Both of them build inside a builddir. This change ease the debugging
process.
> C{,XX}FLAGS: change -fdebug-prefix-map for cmake and meson

- srcpkgs/got/template
- I built this PR locally for my native architecture, aarch64-glibc
This update includes `gotwebd`, the FastCGI repository server, that's why now it needs libevent too.  Note that gotwebd in got-portable *at the moment* doesn't work in a chroot, future -portable version will be hopefully better in this regard.
> got: update to 0.75.1

- srcpkgs/iaito/template
(replacement for cutter which no longer uses r2 as a backend)
Should be merged after #39281 ideally.
> New package: iaito-5.7.2

- srcpkgs/dma/INSTALL
- srcpkgs/dma/template
Fixes https://github.com/void-linux/void-packages/issues/34431;
solution due to thenktor
- I built this PR locally for my native architecture, (x86-64-musl)
> dma: fix /etc/dma/*.conf permissions

- srcpkgs/libgweather/patches/0001-Fix-fallback-metric-unit-detection-logic.patch
- srcpkgs/libgweather/template
musl systems with metric locales displayed a lot of warnings because of a logic error
> libgweather: silence warnings on musl with metric

- srcpkgs/git-cliff/template
Motivation here is that running `git cliff --help` doesn't give any reasonable
output (just complains that there is man page on `git-cliff`), while `git-cliff
--help` does. The former is handled by git, which opens `man 1 git-cliff`,
where as the latter is handled by `git-cliff`, giving out the default help
output from clap.
With this change, `git cliff --help` and `git-cliff --help` still differ, but
at least they both give out a sensible result.
> git-cliff: generate and ship man page

- srcpkgs/python3-jsonschema/patches/0001-patch-out-hatch-fancy-pypi-readme.patch
- srcpkgs/python3-jsonschema/patches/0002-don-t-install-tests-and-benchmarks.patch
- srcpkgs/python3-jsonschema/template
> python3-jsonschema: update to 4.16.0.

- srcpkgs/nerd-fonts/template
Explanation: As before, I haven't tested all the fonts, just a cross section of them.
> nerd-fonts: update to 2.2.2

- srcpkgs/AppStream/patches/0001-ascli_refresh_cache-fix-NULL-pointer-dereference.patch
- srcpkgs/AppStream/template
> AppStream: fix segfault when updating the cache

- srcpkgs/btrfs-progs/template
> btrfs-progs: update to 5.19.1.

- srcpkgs/cups/template
This one contains a [CVE](https://github.com/advisories/GHSA-h495-hfpg-xw55) fix and I really should have opened it sooner.
> cups: update to 2.4.2.

- srcpkgs/python3-ansible-lint/template
- srcpkgs/python3-wcmatch/template
- python3-wcmatch: update to 8.4.1.
- python3-ansible-lint: update to 6.6.0, and update which test cases are failing
> python3-ansible-lint: update to 6.6.0.

- srcpkgs/docbook2mdoc/patches/Makefile.patch
- srcpkgs/docbook2mdoc/template
Use pkg-config to set flags for libbsd, add missing libmd depend, and install a license file
> docbook2mdoc: fix build and extract license file

- srcpkgs/sequoia-sop/template
- srcpkgs/sequoia-sq/template
- srcpkgs/sequoia-sq/update
- srcpkgs/sequoia-sqv/template
- ~~add shell completions~~ will be done after https://gitlab.com/sequoia-pgp/sequoia/-/issues/798 is fixed.
- ~~figure out building for armv7l (some lib stuff missing, see [log](https://web.archive.org/web/20220409160215/https://pipelines.actions.githubusercontent.com/serviceHosts/8d180b0e-8647-44ca-8431-6b9f11113866/_apis/pipelines/1/runs/49556/signedlogcontent/6?urlExpires=2022-04-09T16%3A02%3A59.1606901Z&urlSigningMethod=HMACV1&urlSignature=gkM%2FhddrZEYzNMnQZqSFJQcD3ARwMfWvTQLNQA30A9g%3D))~~ marked as nocross for armv7l for now, considering neither we nor upstream really know *why* it's failing to cross compile
> New Packages: sequoia cli utilities

- srcpkgs/gopass-jsonapi/template
- srcpkgs/gopass/template
> gopass{,-jsonapi}: update to 1.14.6.

- srcpkgs/cargo-update/template
This came up while using topgrade recently, so considering we're shipping topgrade, we should ship this too IMO.
-  ~~disable self-update~~ Considering that `cargo-update` uses the same way to update itself as it uses to update other applications, this doesn't matter. When `cargo-update` isn't installed using cargo by the user, it doesn't try to update itself. Therefore: Nothing to do here.
> New package: cargo-update-8.1.4

- srcpkgs/python3-freezegun/patches/fix-upstream-issue-396.patch
- srcpkgs/python3-freezegun/template
> python3-freezegun: update to 1.2.2.

- srcpkgs/caffeine-ng/template
> caffeine-ng: add libappindicator as a runtime dependency.

- srcpkgs/spectacle/template
support annotation mode (`kColorPicker-devel kImageAnnotator-devel`)
> spectacle: update to 22.08.1

- srcpkgs/haskell-language-server/template
> haskell-language-server: update to 1.8.0.0

- srcpkgs/rust-bindgen/template
- I built this PR locally for my native architecture, (x86_64-gnu, also aarch64)
- x86_64-musl
- armv6l
This is a command line tool that generates Rust bindings from C/C++ header files. It is also a build dependency of the new Mesa Rusticl OpenCL driver, so it will be needed in the future when that releases.
> New package: rust-bindgen-0.60.1

- srcpkgs/s6-dns/template
- srcpkgs/s6-networking/template
Haven't used these packages in years. But since they are usually released along a bunch of other skarnet packages, might make sense if someone more familiar with s6 could adopt them in the future.
> orphan s6 packages: s6-dns, s6-networking

- srcpkgs/swh-plugins/template
Extracted from #38978:
> `swh-plugins` was also on the remove list, since it hasn't been maintained for a while and there is `swh-lv2`. But there are still 2 other packages depending on it:
> 
> - flowblade is depending on it, but works without. @shizonic
> - I didn't try pulseaudio-equalizer-ladspa, but I guess it is a hard depencency there. @steinex
> 
> If those packages are updated, please check if `swh-plugins` is still needed and contact me or remove the package yourself.
> swh-plugins: orphan

- srcpkgs/python3-Flask-WTF/template
> python3-Flask-WTF: update to 1.0.1.

- srcpkgs/sigi/template
The bump from 3.4.2 to 3.4.3 here is pretty minor. Just some dependency updates and internal cleaning https://github.com/hiljusti/sigi/releases/tag/v3.4.3
> sigi: update to 3.4.3

- srcpkgs/ngspice/template
I **_think_** that the current version of kicad can handle the versioned libngspice object better now.  Here is the relevant [commit](https://gitlab.com/kicad/code/kicad/-/commit/b2fbf982a8c32d810dcfcf69b391e118217974f4) and [issue](https://gitlab.com/kicad/code/kicad/-/issues/8878) from kicad upstream  @ericonr, would you be able to verify?
> ngspice: update to 37.

- srcpkgs/pango/patches/fix-segfault-no-font.patch
- srcpkgs/pango/template
This patch has been submitted upstream: https://gitlab.gnome.org/GNOME/pango/-/merge_requests/639
> pango: fix gegl crash when no font is installed

- Manual.md
> Manual.md: correct reference to `etc/defaults.virtual`

- srcpkgs/dracut/template
- srcpkgs/mkinitcpio/files/kernel-hook-postinst
- srcpkgs/mkinitcpio/files/kernel-hook-postrm
- srcpkgs/mkinitcpio/template
- srcpkgs/xbps-triggers/files/initramfs-regenerate
- srcpkgs/xbps-triggers/template
Yes, I know that XBPS alternatives have some problems, but this seems to be the most sensible approach on balance. Rather than dealing with a bunch of potentially competing initramfs hooks, we can let all packages install custom hooks in `/usr/libexec` and use the alternatives system to symlink the preferred hooks in `/etc/kernel.d`. At that point, we can use the generic alternative script in the XBPS regenerator trigger and avoid the need for a conf file, although it falls back to legacy behavior if the alternative isn't set.
Another option I considered, but decided against, was creating a centralized `initramfs-kernel-hooks` package that installs a common hook and reads the `/etc/default/initramfs-regenerate` file used in the existing XBPS trigger to determine what to execute. All …
> [RFC] use alternatives to manage initramfs regeneration

- srcpkgs/waydroid/template
> waydroid: update to 1.3.3.

- srcpkgs/pilot-link/template
- I tested the changes in this PR: **briefly** (I don't have access to a palm device, but this is a simple change, so hopefully it should be ok)
> pilot-link: disable python2 support

- srcpkgs/miniserve/template
> miniserve: update to 0.22.0, add manpage, completions

- common/xbps-src/shutils/bulk.sh
- xbps-src
This makes it simple to bulk build all your outdated packages in the local repository, works with `-r` and branch repos.
There are two similar commands that already exist:
1. `update-sys` which builds outdated installed packages.
2. `update-bulk` which builds outdated packages in configured repositories, so depends on having synced the hosts repositories
and depends on builds already being finished in the remote repos.
With `update-local` you can instead just build a packages manually once and then update them with `./xbps-src update-local` without depending on the state of the host system or remote repositories.
> xbps-src: add update-local and show-local-updates

- srcpkgs/libsoup3/template
> libsoup3: update to 3.2.0.

- srcpkgs/rizin/template
Rizin 0.4.1 is a security fix release:
- https://github.com/rizinorg/rizin/releases/tag/v0.4.1
- https://repology.org/project/rizin/versions
> rizin: update to 0.4.1

- .github/workflows/stale.yml
This fixes a bug where a stale issue/PR that gets updated without a comment remains stale indefinitely and never gets closed (actions/stale#715).
The only "breaking" change in that update is that the default close reason has changed to "not planned". That seems like a more desirable default anyways.
A current example of the bug can be found in #37283.
> .github/workflows/stale.yml: update to v6

- srcpkgs/python3-certifi/template
- I built this PR locally for my native architecture, x64-glibc
> python3-certifi: update to 2022.09.24.

- srcpkgs/rtl8812au-dkms/template
- srcpkgs/rtl8812au-dkms/update
Old upstream stated their version was now obselete, and directed to this new upstream.
The old version also relied on headers that do not exist in 5.15+
- I tested the changes in this PR: **briefly** (dkms module builds, don't have the hardware)
@tsjk can you test this?
> rtl8812au-dkms: update to 20210629.

- srcpkgs/gnome/template
gnome-recipes is not regularly maintained and doesn't might be removed soon because of incompatibility with modern versions of libraries like libsoup 3 and rest 1.0.
> gnome: remove gnome-recipes from -apps

- srcpkgs/CPU-X/template
> CPU-X: disable tests, don't break base-chroot

- srcpkgs/xwinwrap/template
Updated checksum per IR #39072. added grep make depend to build.
- I built this PR locally for my native architecture, X86_64 glibc
i686
x86_64-musl
armv6l
armv6l-musl
aarch64
aarch64-musl
ppe64le
ppe64le-musl
> xwinwrap-0.9: update checksum

- srcpkgs/tcllib/template
updated checksum. re:  #39072
- aarch64
- armv6l-musl
- mips-musl
- i686
- armv7l
> tcllib: update checksum

- srcpkgs/python3-numpy-stl/template
- I built this PR locally for my native architecture, x64-glibc
> python3-numpy-stl: update to 2.17.1.

- srcpkgs/xdg-desktop-portal/template
> xdg-desktop-portal: update to 1.15.0.

- srcpkgs/xdg-desktop-portal-gnome/template
> xdg-desktop-portal-gnome: update to 43.0.

- srcpkgs/python3-executing/template
> python3-executing: update to 1.1.0.

- srcpkgs/python3-pytz/template
> python3-pytz: update to 2022.4.

- srcpkgs/python3-iso8601/template
> python3-iso8601: update to 1.1.0.

- srcpkgs/exiftool/template
- aarch64-musl
- armv7l
- armv6l-musl
> exiftool: update to 12.46.

- srcpkgs/flatpak/template
- srcpkgs/gdm/template
This doesn't affect `GDM -> gnome` due to: https://github.com/void-linux/void-packages/pull/9126
However it does affect `GDM -> <anything other than gnome>`
See: https://wiki.gnome.org/Initiatives/Wayland/SessionStart
(`/etc/profile` never gets loaded in GDM)
> flatpak: fix setting environment variables on gdm

- srcpkgs/rusty-diceware/template
> rusty-diceware: update to 0.5.3.

- srcpkgs/fluidsynth/template
> fluidsynth: update to 2.3.0

- srcpkgs/python3-pyacoustid/template
> python3-pyacoustid: update to 1.2.2, adopt.

- srcpkgs/freecad/template
to fix CI and help https://github.com/void-linux/void-packages/pull/36356/ build correctly
> freecad: evade vsed strict mode for flaky version info

- srcpkgs/arti/template
- srcpkgs/arti/update
The Tor Project is re-implementing Tor in Rust.
https://gitlab.torproject.org/tpo/core/arti
https://blog.torproject.org/arti_050_released/
Not yet production ready, nor feature-parity with C Tor but basic SOCKS proxy support via
```
$ arti proxy -p 9150
```
is usable.
When arti is production ready, I'm planning to add a proper runit service.
> New package: arti-1.0.0

- srcpkgs/xterm/template
CI just fails due to ratelimiting on xterm servers.
> xterm: update to 373.

- srcpkgs/biber/patches/0001-Adapt_to_Perl_5.36.patch
- srcpkgs/biber/template
With perl 5.36, biber now fails with a syntax error:
This patch was taken directly from biber upstream: https://github.com/plk/biber/commit/d9e961710074d266ad6bdf395c98868d91952088 . A clean fix would be updating biber, but as biber is released in lockstep with biblatex (and has strict version requirements going both ways), updating the TeXLive packages isn't really something I'm able to do.
Without this patch, invoking biber at all results in the following crash:
```
$ biber --help
Can't modify undef operator in scalar assignment at /usr/share/perl5/vendor_perl/Biber/Section.pm line 373, near "undef;"
Compilation failed in require at /usr/share/perl5/vendor_perl/Biber.pm line 24.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Biber.pm line 24.
Compilation failed in …
```
> biber: add patch to fix biber on perl 5.36

- srcpkgs/boinc/patches/boinc-am_conditional.patch
- srcpkgs/boinc/template
- srcpkgs/codeblocks/template
- srcpkgs/golly/template
> boinc: not depends on GTK+ anymore

- srcpkgs/nextcloud-client/template
Local build testing
- I built this PR locally for my native architecture, aarch64
> nextcloud-client: update to 3.6.0

- srcpkgs/python3-Werkzeug/template
[2.2.x added it in `install_requires`](https://github.com/pallets/werkzeug/blob/15fcb87d36f4ed45b127692d2d739266b918503c/setup.py#L6)
> python3-Werkzeug: add missing dependency python3-MarkupSafe.

- srcpkgs/python3-responses/template
> python3-responses: update to 0.21.0.

- srcpkgs/intellij-idea-community-edition/files/idea.desktop
- srcpkgs/intellij-idea-community-edition/template
Trying to run intellij with an openjdk will error on startup complaining about missing AWT modules which aren't in that distribution. Instead of depending on any java environment via the `java-environment` virtual package, depend explicitly on the jetbrains jdk and modify the desktop entry to launch intellij with that jdk.
With these changes, intellij is only launched with the jetbrains jdk by default when you use the desktop entry. You can still launch it using any java environment when using the executable directly by setting the `IDEA_JDK` variable on the command line.
> intellij-idea-community-edition: use jetbrains jdk

- srcpkgs/lua54-luaexpat/template
- I tested the changes in this PR: **briefly** ran the following example code sourced from the project's homepage and tested by writing a few xml tags to it's stdin.
```lua
lxp = require"lxp" -- added "lxp =" which was NOT IN the version on the homepage
local count = 0
callbacks = {
StartElement = function (parser, name)
io.write("+ ", string.rep(" ", count), name, "\n")
count = count + 1
end,
EndElement = function (parser, name)
count = count - 1
io.write("- ", string.rep(" ", count), name, "\n")
end
}
p = lxp.new(callbacks)
for l in io.lines() do  -- iterate lines
p:parse(l)          -- parses the line
p:parse("\n")       -- parses the end of line
end
p:parse()               -- finishes the document
p:close()               -- closes the parser
```
Then I ran:
```shell
echo '<asdf>one …
```
> lua54-luaexpat: update to 1.5.0

- srcpkgs/pkg-config/template
all bootstrap packages use pkgconf, so having pkg-config marked with bootstrap=yes doesn't make sense
> pkg-config: remove unused bootstrap=yes

- srcpkgs/redis/template
> redis: update to 7.0.4.

- srcpkgs/hackrf/patches/fix-device-acess-via-elogind.patch
- srcpkgs/hackrf/template
- armv6l
[39083](https://github.com/void-linux/void-packages/issues/39083)
> hackrf: fix udev rules directory

- srcpkgs/phonon-qt5-backend-gstreamer/template
- armv6l
https://github.com/void-linux/void-packages/issues/39083
> phonon-qt5-backend-gstreamer: add libxml2-devel makedepends

- srcpkgs/google-chrome/template
> google-chrome: update to 106.0.5249.61

- srcpkgs/python3-poetry-core/template
A couple of these fail some tests, same as https://github.com/void-linux/void-packages/pull/39136
> python3-poetry-core: update to 1.3.1.

- srcpkgs/igt-gpu-tools/patches/igt_edid-Allocate-raw-8-bytes-for-VSDB.patch
- srcpkgs/igt-gpu-tools/template
> igt-gpu-tools: fix buffer overflow

- srcpkgs/xcircuit/template
I might be dumb but honestly  I don't understand what tests is even running on the  `do_check()` by default ... So disabling the tests since upstream don't seem to have tests.
> xcircuit: update to 3.10.30.

- srcpkgs/zfs/template
This could use testing by users that do NOT have root-on-ZFS for their ZFS usage. Tested locally on x86_64, no native encryption, root-on-ZFS.
@ahesford @Vaelatern
> zfs: update to 2.1.6.

- srcpkgs/postfix/template
- aarch64-musl
- armv7l
- armv6l-musl
> postfix: update to 3.7.3.

- srcpkgs/qtractor/template
> qtractor: update to 0.9.29, switch to Qt6

- srcpkgs/cargo-outdated/template
> cargo-outdated: update to 0.11.1.

- srcpkgs/iwd/template
- armv6l
I tested by installing the new package, restarting iwd, confirming connection, using iwctl to disconnect and reconnect, and confirming connection again.
> iwd: update to 1.30.

- srcpkgs/python3-zope.hookable/template
- aarch64-musl
- armv7l
- armv6l-musl
> python3-zope.hookable: update to 5.2

- srcpkgs/psmisc/template
- I tested the changes in this PR: **briefly** - I checked basic functionality of `pstree` and `killall` specifically, as they were the only programs changed in 23.5, and also checked `fuser`.
- armv6l
> psmisc: update to 23.5.

- srcpkgs/python3-pikepdf/template
> python3-pikepdf: update to 6.2.0.

- common/shlibs
- srcpkgs/primecount/template
- srcpkgs/primesieve/template
Note: `primesieve` had a soname bump, but it's only used directly by `primecount`. The latter did not bump soname.
Moreover the only use of these libraries in our repo is in `sagemath`, and only through `python3-primecountpy` which does NOT need revbump. Everything can be tested directly in the cli:
```
$ sage -c 'print(prime_pi(10^15))'
29844570422669
$ python -c 'from primecountpy import prime_pi ; print(prime_pi(10**15))'
29844570422669
$ primecount $[10**15]
29844570422669
$ xbps-query --regex -s 'prime(count|sieve)|sagemath-'
[*] primecount-7.4_1             Fast prime counting function
[*] primecount-devel-7.4_1       Fast prime counting function - development files
[*] primesieve-8.0_1             Fast prime number generator
[*] …
```
> Update primesieve to 8.0 and primecount to 7.4.

- srcpkgs/xmoto/patches/fix_gettext_GNU-isms_musl.patch
- I tested the changes in this PR: **Yes** , opened the app on the glibc , didn't test on musl
- x86_64-glibc
- armv6l *
> xmoto: fix musl build

- srcpkgs/python3-memory_allocator/template
I'm running the testsuite of sagemath-9.5 (from our repo) with the updated memory_allocator and it works ok.
> python3-memory_allocator: update to 0.1.3.

- srcpkgs/python3-zope.cachedescriptors/template
> python3-zope.cachedescriptors: update to 4.4.

- srcpkgs/python3-sympy/template
Tested with sagemath-9.5, and with WIP sagemath-9.7. Can be safely updated independently of sagemath.
> python3-sympy: update to 1.11.1, adopt.

- srcpkgs/dqlite/template
- srcpkgs/lxd-lts/template
- srcpkgs/lxd-lts/update
- srcpkgs/lxd/template
- srcpkgs/raft/template
- raft: update to 0.15.0
- dqlite: update to 0.11.1
- lxd: update to 5.6
- lxd-lts: update to 5.0.1
> lxd: update to 5.6, lxd-lts: update to 5.0.1

- srcpkgs/tlpui/template
- armv6l
There is an already open PR with these package #36982  but the creator of that pr doesn't seem to respond ,,, So opening this since I use the app and want it to be on the main repos. 
make_check=no, since the tests seem to fail on my machine (on chroot `./xbps-src pkg -Q tlpui` with: 
> (setup.py:10388): Gdk-WARNING **: 18:09:04.398: Native Windows wider or taller than 32767 pixels are not supported
And seems to run forever.
> New package: tlpui-1.5.0.5

- srcpkgs/intellij-idea-community-edition/template
the i686 was essentially dead, since jetbrains-jdk-bin is x86_64 only,
also it was essentially untested and might have resulted in a broken pacakge either way
> intellij-idea-community-edition: Orphan package, remove i686 snippets

- srcpkgs/grml-zsh-config/template
With the last version (0.19.1), there is a grep warning on every startup: `grep: warning: stray \ before 0`
> grml-zsh-config: update to 0.19.4.

- srcpkgs/os-prober/template
- I tested the changes in this PR: **briefly**, it runs but I don't have any other OSs on my void machine to check if it still detects them.
> os-prober: update to 1.81.

- srcpkgs/cross-x86_64-w64-mingw32/template
[ci skip]
Resolves build failure with gcc 12 on musl: https://github.com/void-linux/void-packages/issues/39809
> cross-x86_64-w64-mingw32: update to 10.0.0.

- common/shlibs
- srcpkgs/DarkRadiant/template
- srcpkgs/Fritzing/template
- srcpkgs/calligra/template
- srcpkgs/geany-plugins/patches/0001-git-changebar-Simplify-libgit2-version-checks.patch
- srcpkgs/geany-plugins/patches/0002-git-changebar-Add-support-for-libgit2-1.4.patch
- srcpkgs/geany-plugins/template
- srcpkgs/git-absorb/template
- srcpkgs/git-series/template
- srcpkgs/gnome-builder/template
- srcpkgs/horizon/template
- srcpkgs/juCi++/template
- srcpkgs/kup/template
- srcpkgs/libgit2-glib/template
- srcpkgs/libgit2/patches/0001-clar-remove-ftrunacte-from-libgit2-tests.patch
- srcpkgs/libgit2/patches/disable-test-validate_current_user_ownership.patch
- srcpkgs/libgit2/template
- srcpkgs/slcp/template
- srcpkgs/stagit/template
bumping libgit2 is required to package [jami](https://git.jami.net/savoirfairelinux/jami-client-qt/)
- local build for
supersedes:
* https://github.com/void-linux/void-packages/pull/28456/
* https://github.com/void-linux/void-packages/pull/33535
> libgit2: update to 1.5.0.

- srcpkgs/exiftool/template
- aarch64-musl
- armv7l
- armv6l-musl
> exiftool: update to 12.48.

- srcpkgs/go/template
Update go 1.19.2, [release notes](https://go.dev/doc/devel/release#go1.19.2):
> go1.19.2 (released 2022-10-04) includes security fixes to the archive/tar, net/http/httputil, and regexp packages, as well as bug fixes to the compiler, the linker, the runtime, and the go/types package.
> go: update to 1.19.2.

- srcpkgs/cargo-outdated/template
- srcpkgs/cocogitto/template
- srcpkgs/exa/template
> cocogitto, exa, cargo-outdated: rebuild for libgit2

- srcpkgs/superd/patches/add-installmisc-target.patch
- srcpkgs/superd/template
~~Since I had to add a `do_check()` myself it made me wonder if the go build-style should have a default of some kind. Thoughts?~~ As per conversation on `#xbps` IRC we should `: ${make_check_target:=./...}` and `go test -v ${make_check_target}`, but I'll reserve that for another PR and tweak all `build_style=go` packages as needed.
> New package: superd-0.7

- srcpkgs/PolyMC/template
the person currently in control of the polymc meta server might not have the best intentions
> PolyMC: switch to a more trusted meta server

- srcpkgs/openjdk10-bootstrap/patches/fix-path-exception-glibc.patch
- srcpkgs/openjdk10-bootstrap/patches/fix-pointer-comparison-gcc12.patch
- srcpkgs/openjdk10-bootstrap/template
Revbump because the glibc fix requires a rebuild.
https://github.com/void-linux/void-packages/issues/39809
The distfiles address was changed on request to github since the official mirror tends to error out.
> openjdk10-bootstrap: fix build with gcc 12 and glibc 2.36

- srcpkgs/libgbinder/template
> libgbinder: update to 1.1.26.

- srcpkgs/python3-Babel/template
- srcpkgs/python3-Flask-Babel/template
> python3-Babel: update to 2.10.3.

- srcpkgs/libreoffice/patches/gpgme-2.18.0.patch
The clucene build failure was fixed by: https://github.com/void-linux/void-packages/commit/5aeb4c0ce0d27cfead4bcc9982cb249a48d48bf2
> libreoffice: fix build with gpgme 2.18

- srcpkgs/dmenu/template
- I tested the changes in this PR: **briefly** - installed and confirmed I could still run programs using `dmenu_run`.
- armv6l
> dmenu: update to 5.2.

- srcpkgs/citations/template
- aarch64-musl
- aarch64
- armv7l
> New Package: citations-0.5.1

- common/shlibs
- srcpkgs/libwebkit2gtk41
- srcpkgs/libwebkit2gtk41-devel
- srcpkgs/libwebkit2gtk50
- srcpkgs/libwebkit2gtk50-devel
- srcpkgs/webkit2gtk-common
- srcpkgs/webkit2gtk/patches/be-typedarray.patch
- srcpkgs/webkit2gtk/patches/fix_armv6l.patch
- srcpkgs/webkit2gtk/patches/reproducible.patch
- srcpkgs/webkit2gtk/template
[ci skip]
This splits webkit2gtk into 3 packages:
+ webkit2gtk40: GTK+3 and libsoup2
+ webkit2gtk41: GTK+3 and libsoup3
+ webkit2gtk50: GTK4 and libsoup3
This is necessary since libsoup2 and libsoup3 cannot be used by an application at the same time.
Ideally in the future, the packages using webkit2gtk40 would be moved to webkit2gtk41 or 50 (or be dropped).
I tested this PR with epiphany 42 and it seems to work (and it compiles sucessfully).
> webkit2gtk: update to 2.38.1.

- common/xbps-src/shutils/build_dependencies.sh
grep 3.8 now prints a warning that egrep is deprecated and we should use grep -E instead
> xbps-src: don't use deprecated egrep

- srcpkgs/libbsd/template
It is used in the pkgconfig Libs.private.
> libbsd-devel: depend on libmd-devel.

- srcpkgs/mupen64plus/patches/0001-Fix-wrong-pitch-argument-in-call-to-SDL_CreateRGBSur.patch
- srcpkgs/mupen64plus/template
Add a patch which applies the change from https://github.com/mupen64plus/mupen64plus-core/pull/970 so that mupen64plus still works after updating to SDL 2.24
The patch should be removed after the next release of mupen64plus since the fix will already be included.
> mupen64plus: Fix crash due to SDL_SetVideoMode in SDL 2 compatibility code

- srcpkgs/python3-mutagen/template
[Changelog](https://mutagen.readthedocs.io/en/latest/changelog.html#release-1-46-0): no breaking changes relevant to Void.
> python3-mutagen: update to 1.46.0

- srcpkgs/python3-Unidecode/template
[Changelog](https://github.com/avian2/unidecode/blob/414199246e4871669896756279e3460ff0364839/ChangeLog#L1): no breaking changes.
> python3-Unidecode: update to 1.3.6

- srcpkgs/python3-psutil/template
> python3-psutil: update to 5.9.3.

- srcpkgs/python3-pynacl/template
[Changelog](https://github.com/pyca/pynacl/blob/main/CHANGELOG.rst#150-2022-01-07): no breaking changes relevant to Void.
> python3-pynacl: update to 1.5.0

- srcpkgs/python3-chardet/template
[Changelog](https://github.com/chardet/chardet/releases/tag/5.0.0): no breaking changes relevant to Void.
> python3-chardet: update to 5.0.0

- srcpkgs/python3-blinker/template
[Changelog](https://blinker.readthedocs.io/en/stable/#version-1-5), [diff](https://github.com/pallets-eco/blinker/compare/rel-1.4...1.5): no breaking changes.
> python3-blinker: update to 1.5

- srcpkgs/python3-pip/template
> python3-pip: update to 22.3

- srcpkgs/pdf.js/template
The legacy build fixes the regression in #40061. I don't know whether there is a reason *not* to use the legacy build; if so, we'll need a separate package.
Closes #40061.
cc: @heittpr
> pdf.js: update to 2.16.105, switch to legacy build

- srcpkgs/cgit/template
Also don't use vendored regex engine on glibc.
> cgit: prepare for auto-create wrksrc, fix do_check

- .github/workflows/build.yaml
- common/scripts/lint-commits
- common/scripts/lint-version-change
- common/travis/changed_templates.sh
- common/travis/fetch_upstream.sh
This `PATH` change was introduced in #39309, and parts of it felt kind of hacked on. This streamlines it
- .github/workflows/build.yaml: add /usr/libexec/chroot-git to PATH
- common/: remove PATH adds from CI scripts
- I tested the changes in this PR: **YES** - https://github.com/void-linux/void-packages/actions/runs/3213065830
> CI: unify path handling

- srcpkgs/v4l2loopback/patches/0001-Backport-PR-477-1.patch
- srcpkgs/v4l2loopback/patches/0002-Backport-PR-485-1.patch
- srcpkgs/v4l2loopback/patches/dkms-patch.patch
- srcpkgs/v4l2loopback/template
Added the following patches:
- Backported dkms-patch from Ubuntu (support for kernel >= 5.18) [1]
- Limit v4l2_loopback_write calls to (streaming) writers [2]
- Reintroduce previous behavior for write call [3]
[1] https://github.com/umlaeute/v4l2loopback/commit/e7edf2f55b7eb71b69984110f3c8e31b8ac6285e
[2] https://github.com/umlaeute/v4l2loopback/pull/477/commits
[3] https://github.com/umlaeute/v4l2loopback/pull/485/commits
- armv7l
- i686-libc
> v4l2loopback: update to 0.12.7

- srcpkgs/webkit2gtk-common
- srcpkgs/webkit2gtk/template
[ci skip]
webkit2gtk generates unique locale files for each version so the common package is redundant.
The locale files also got installed to the wrong location in the common package, i.e. /usr/share/locale/locale instead of /usr/share/locale
> webkit2gtk: remove webkit2gtk-common subpackage

- srcpkgs/rusty-diceware/template
> rusty-diceware: update to 0.5.8.

- srcpkgs/mupen64plus/patches/0001-Fix-default-configuration-for-Logitech-F310.patch
- srcpkgs/mupen64plus/template
The default bindings for the Logitch F310 gamepad are incorrect in mupen64plus v2.5.9. This patch applies the corrected bindings from upstream: https://github.com/mupen64plus/mupen64plus-input-sdl/commit/ad2af4cff4909d341049c25b8d77be14c4bd16de
> mupen64plus: Fix default Logitech F310 controller bindings.

- srcpkgs/nextcloud-client/patches/check-for-updates-disabled-as-default.patch
- srcpkgs/nextcloud-client/patches/testfolderman-within-chroot.patch
- srcpkgs/nextcloud-client/template
Also:
- update testfolderman patch
- add patch to disable update check by default
this affects new installations only
- i686-libc
> nextcloud-client: update to 3.6.1

- srcpkgs/kwave/template
Fix: https://github.com/void-linux/void-packages/issues/37680
~~Error: [**CMakeOutput.log**](https://github.com/void-linux/void-packages/files/9228739/CMakeOutput.log)~~
> New package: kwave-22.08.2

- srcpkgs/just/template
> just: update to 1.7.0

- srcpkgs/hackrf/template
- x86_64-musl
- aarch64
- aarch64-musl
- armv6l
- armv6l-musl
- armv7l
- armv7l-musl
> hackrf: update to 2022.09.1, adopt.

- srcpkgs/lua54-lualdap/patches/c89-is-broken.patch
- srcpkgs/lua54-lualdap/patches/lua54.patch
- srcpkgs/lua54-lualdap/template
> lua54-lualdap: fix build for lua 5.4

- srcpkgs/mopidy-local/template
> mopidy-local: add missing dependency on uritools

- srcpkgs/superd/template
This is currently available in repos for all arches ([including `x86_64-musl`](https://voidlinux.org/packages/?arch=x86_64-musl&q=superd)), but [not x86_64-glibc](https://voidlinux.org/packages/?arch=x86_64&q=superd) which appears to have failed build for reasons unrelated to the packaging.
Ping @paper42 who already responded to me about this on `#xbps`:
> the build failed and the builder doesn't attempt it again for new pkgs
> failed because of transient resolver error iirc
> touching the template will help, not sure if there is a better way
> superd: touch template to build for x86_64-glibc

- srcpkgs/google-chrome/template
- I tested the changes in this PR: **YES** (on a machine without any `qt5*` packages)
---
This disables rdep scanning for `libqt5_shim.so`, as does upstream:
https://chromium.googlesource.com/chromium/src/+/8fcee9b26219683fb20bc51826629cac2e3584a0%5E%21/#F0
Otherwise it pulls in `qt5-widgets`, etc.:
```
Name                Action    Version           New version            Download size
double-conversion   install   -                 3.1.5_1                29KB
qt5-core            install   -                 5.15.5+20220728_1      2408KB
libevdev            install   -                 1.12.0_1               38KB
libwacom            install   -                 1.12_1                 92KB
mtdev               install   -                 1.1.6_1                12KB
libinput            install …
```
> google-chrome: don't depend on qt5-{core,gui,widgets}

- srcpkgs/lightdm/template
This was excluded way back in Qt4 days of early 2015 to enable cross-building of `lightdm` but doesn't appear to be a problem anymore.
> lightdm: enable cross-build of liblightdm-qt5

- srcpkgs/mobile-config-firefox/template
Also change license to `MPL-2.0` as per https://gitlab.com/postmarketOS/mobile-config-firefox/-/commit/75c57aa3.
> mobile-config-firefox: update to 3.1.0.

- srcpkgs/openpgp-card-tools/template
- srcpkgs/openpgp-card-tools/update
Splitting this out from #32480, as they are related, but don't depend on each
other, at least not necessarily and not in a way that xbps-src cares about.
<del>Aside of that, should I add a section to void-docs, about how to set this up,
next to https://docs.voidlinux.org/config/gnupg.html, as their setup sort-of
depends on each other if you want to use them in parallel? `opgp-card` requires
use of pcscd, which means you have to disable the built-in ccid driver in
GnuPGs scdaemon, install `pcsclite` and `pcsc-ccid` and enable the `pcscd`
service.</del> Added info in …
> New package: openpgp-card-tools-0.9.0

- srcpkgs/cargo-auditable/template
Allows the user to embed dependency information into the binary. This information can be read by a few different tools, for example `syft` (see https://github.com/void-linux/void-packages/pull/40264) and `rust-audit-info` (see https://github.com/void-linux/void-packages/pull/40266). I'd like to follow this PR up with a change to the cargo build style, so that we can include that dependency information in all rust binaries we ship.
> New package: cargo-auditable-0.5.2

- srcpkgs/66/template
It is not picked up as a dependency from s6-rc-devel in the makedepends array (thanks @NymanMatthias).
Also:
- change changelog and distfiles to the new gitlab instance,
- change the changelog path in the git repo.
> 66: revbump, add s6-rc to the depends array.

- srcpkgs/emacs/template
- srcpkgs/icu/template
- I tested the changes in this PR: **NO** (only build to confirm xbps-src still works)
> DO NOT MERGE: Check build for code cleanup for auto-create_wrksrc

- srcpkgs/rtl8822bu-dkms/patches/0001-void-arch-generic-plumbing-bits.patch
- srcpkgs/rtl8822bu-dkms/template
switch upstream (current one is archived), fixes build on newer kernels
fixes #40234
- I tested the changes in this PR: **briefly** (don't have the hardware, but the dkms module builds)
> rtl8822bu-dkms: update to 20221030.

- srcpkgs/eva/template
<del>Checksum changed since this was packaged. Does a revbump for stuff like this make sense? Probably not, right?</del>
Upstream re-released v0.3.0, so the builds fail with bad checksum right now.
> eva: bump revision and update checksum

- srcpkgs/fotoxx/template
- aarch64-musl
- armv7l
- armv6l-musl
> fotoxx: update to 22.40.

- common/build-style/cargo.sh
- common/environment/build-style/cargo.sh
- srcpkgs/cargo-auditable-bootstrap/template
- srcpkgs/cargo-auditable/template
In contrast to other distros like f.ex. Fedora, we don't ship each crate in the
dependency tree of a rust project as its own (source) package, which means that
xbps isn't aware of those dependencies. Recovering what versions of specific
libraries are used on a system is made very hard by this, which leaves people
clueless what to do in a situation when a library has a CVE for example.
This change embeds a table of dependencies that went into this binary into the
binary itself, which means recovering what binaries contain which libraries
becomes fairly trivial. Go does this by default, and the long-term goal is to
do the same with Rust, but we aren't there yet.
An example for how usage could look like:
```text
❯ syft packages --catalogers all …
```
> RFC: build-style/cargo: produce auditable binaries

- srcpkgs/libpng/template
> libpng: update to 1.6.38

- srcpkgs/i2pd/files/i2pd/run
- srcpkgs/i2pd/template
To run i2pd as a "floodfill" (special mode which contributes to the network more) we need a higher open files limit. 8192 is recommended by upstream but let's just double it to be on the safe side.
> i2pd: increase open files limit

- srcpkgs/wbg/template
> wbg: update to 1.1.0.

- srcpkgs/got/template
- I built this PR locally for my native architecture, (x86-64-musl)
> got: update to 0.78

- .github/workflows/stale.yml
I created a new label for tracking issues. it's logical that they should be excluded from stalebot.
If a tracking label isn't wanted, it can be removed.
Related: should the existing [`inactive`](https://github.com/void-linux/void-packages/labels/inactive) label be merged with the `stale` label? there's only one open issue with it
> .github/workflows/stale.yml: ignore tracking issues

- srcpkgs/rust-bindgen/template
- I built and tested this PR locally for my native architecture, (x86_64-gnu)
- I built this PR locally for these architectures (all crossbuilds):
- aarch64-musl
- armv6l
- i686
> rust-bindgen: update to 0.61.0.

- srcpkgs/php-ast/template
- srcpkgs/php-imagick/template
- srcpkgs/php8.0-apcu/template
- srcpkgs/php8.0-ast/template
- srcpkgs/php8.0-imagick/template
- srcpkgs/php8.1-apcu/template
- srcpkgs/php8.1-ast/template
- srcpkgs/php8.1-imagick/template
- srcpkgs/xdebug/template
- srcpkgs/xdebug8.0/template
- srcpkgs/xdebug8.1/template
> php: brokeness with the new extraction because they have a package.xml on top level

- srcpkgs/darktable/template
This library is not used by darktable.
cc: @lemmi
> darktable: remove libglade from makedepends

- srcpkgs/dropbox/template
libglade is not used by this package.
> dropbox: remove libglade from dependencies

- srcpkgs/gtk-sharp/template
libglade-devel is not used by this package.
cc: @Gottox
> gtk-sharp: remove libglade from makedepends, fix xlint

- srcpkgs/lingot/template
The package does not use this library.
> lingot: remove libglade-devel from makedepends

- srcpkgs/ogmrip/template
It would be used for building GTK2 GUI which is not enabled.
> ogmrip: remove libglade-devel from makedepends

- srcpkgs/jdupes/template
CFLAGS="-DENABLE_DEDUPE" is enough to enable --dedupe. See a92952dbd0aaa34b72792c362f002e9f19a3d84c and #32048.
- I tested the changes in this PR: **briefly** (I don't have a BTRFS filesystem to test it)
> jdupes: update to 1.21.0.

- srcpkgs/xdg-desktop-portal-gnome/template
> xdg-desktop-portal-gnome: update to 43.1.

- srcpkgs/arandr/patches/getfullargspec.patch
- srcpkgs/arandr/template
This change should fix this error:
```
File "/usr/bin/arandr", line 41, in <module>
from screenlayout.gui import main
File "/usr/lib/python3.11/site-packages/screenlayout/gui.py", line 76, in <module>
class Application:
File "/usr/lib/python3.11/site-packages/screenlayout/gui.py", line 185, in Application
@actioncallback
^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/screenlayout/gui.py", line 48, in actioncallback
argnames = inspect.getargspec(function)[0]
^^^^^^^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'getargspec'. Did you mean: 'getargs'?
```
> arandr: replace inspect.getargspec() with inspect.getfullargspec()

- srcpkgs/gns3-gui/template
- srcpkgs/gns3-server/patches/importlib.patch
- srcpkgs/gns3-server/template
Python 3.11 support was added to GNS3 2.2.35.
A new required library was added to 2.2.35 so a new Void package was created.
For reference, `gns3` 2.2.34 fails
> GNS3 2.2.35 - new version supports Python 3.11

- srcpkgs/dbeaver/patches/force-jdk17.patch
- srcpkgs/dbeaver/template
> dbeaver: update to 22.2.4.

- common/build-style/python3-pep517.sh
Fixes the following (missing newline) for this warning:
> common/build-style/python3-pep517: add missing \n for msg_warn

- srcpkgs/openssh/patches/ssh-musl-gssapi.patch
- srcpkgs/openssh/template
I noticed that openssh does not build with gssapi option on musl (or crosscompiled from glibc). Seems it's complaining about missing definition `MAXHOSTNAMELEN` in `gss-serv.c`. in the headers included in `mit-krb5-devel` it's defined in `/usr/include/gssrpc/types.h` (also included in `musl-devel` in `/usr/include/sys/param.h` but using that the build fails crosscompiling from glibc complaining of unresolvable shlibs and `mit-krb5-devel` is already a makedepend with gssapi option).
Patching `#include <gssrpc/types.h>` into `gss-serv.c` seems to fix the problem both for native musl compile and crosscompiling from glibc. I also confirmed that compiling natively on glibc still works.
Don't know if there's an issue in the configure script that causes this, seems to be checking for …
> openssh: fix broken gssapi on musl

- srcpkgs/linux-tools/template
They're build as part of tools/build.
fixdep will be built by HOSTCC anyway.
> linux-tools: correct the functional detection

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 5.63.1.

- srcpkgs/root/patches/python3.11_2.patch
- srcpkgs/root/template
Added patch taken from upstream to fix a breaking issue in pyroot from python 3.11. See root-project/root#11457
> root: add upstream patch to fix pyroot for python 3.11

- srcpkgs/python3-docstring-to-markdown/template
- srcpkgs/python3-lsp-server/template
- New package: python3-docstring-to-markdown-0.10 (new dependency)
- python3-lsp-server: update to 1.6.0
> python3 lsp server 1.6.0

- srcpkgs/lightdm-mini-greeter/template
When testing the build locally I noticed this overwrote the `/etc/lightdm/lightdm-mini-greeter.conf`. I don't know if this is an issue? If so how do I fix this behavior?
> lightdm-mini-greeter: update to 0.5.1.

- srcpkgs/gsfonts/template
- srcpkgs/lilypond-doc/template
- srcpkgs/lilypond/template
- x86_64-musl
- armv7l-musl
- i686
- aarch64
New font package urw-core35-fonts, because lilypond doesn’t bundle the required OTF fonts anymore and the URW++ ones are used in favour of the TeX Gyre fonts, see
https://git.savannah.gnu.org/cgit/lilypond.git/commit/?id=5689c2721530c6ded22b6291ebb06d10adb5bc28
There is no release, unfortunately, but I hope it is ok to make an exception in this case. :)
> lilypond: update to 2.23.80

- srcpkgs/discord-ptb/template
---
The EULA hash has been giving me trouble for weeks. Perhaps this is only an issue on my machine? The CI will confirm. Also, there is no need to `cat` into `w3m`, it can read files directly.
> discord-ptb: update to 0.0.35.

- srcpkgs/teeworlds/template
Build instructions in readme.md mention python 3 as a build dependency in section "Building on Linux or macOS (CMake)", subsection "Installing dependencies".
Related to void-linux/void-packages#38229.
cc: @leahneukirchen 
> teeworlds: replace python with python3 in hostmakedepends

- srcpkgs/godot/template
Enabling Godot's PulseAudio driver fixes audio playback on PipeWire. Previously, the package's only enabled audio driver was ALSA, but Godot on alsa-pipewire stutters, and Godot on HW ALSA devices prevents PipeWire apps from playing audio.
- none, `./xbps-src -a armv6l pkg godot` claims godot can't cross-compile and I didn't try native building
Fixes #39936.
> godot: update to 3.5.1 and enable PulseAudio backend

- srcpkgs/python3-jsonschema/template
> python3-jsonschema: update to 4.17.0.

- srcpkgs/python3-pathspec/template
> python3-pathspec: update to 0.10.2.

- srcpkgs/cargo-auditable-bootstrap/template
- srcpkgs/cargo-auditable/template
- cargo-auditable-bootstrap: update to 0.5.3.
- cargo-auditable: update to 0.5.3.
>     cargo-auditable: update to 0.5.3.

- srcpkgs/dbus-elogind/template
- srcpkgs/dbus/template
- dbus: update to 1.14.4
- dbus-elogind: update to 1.14.4
> dbus{,-elogind}: update to 1.14.4

- srcpkgs/zellij/template
> zellij: update to 0.33.0

- srcpkgs/vaultwarden-web/template
- srcpkgs/vaultwarden-web/update
- srcpkgs/vaultwarden/template
> vaultwarden-web: update to 2022.10.2; vaultwarden: update to 1.26.0.

- srcpkgs/cargo-auditable-bootstrap/template
- srcpkgs/cargo-auditable/template
- cargo-auditable-bootstrap: update to 0.5.4.
- cargo-auditable: update to 0.5.4.
> cargo-auditable: update to 0.5.4.

- srcpkgs/cryptsetup/template
- I tested the changes in this PR: **YES**, using it on my full disk encrypted system boot included (x86_64-glibc), and its working fine. 
I have also went ahead and compiled it on a VM with musl glibc (x86_64-musl) and cross compiled it with armv6l.
- I built this PR locally for my native architecture, x86_64-{musl,glibc}
- armv6l
Probably should be marked as tests needed as other people might have different setups than mine. ( and this update broke something).
> cryptsetup: update to 2.5.0.

- srcpkgs/libva-glx/template
- srcpkgs/libva-utils/template
- srcpkgs/libva/template
I tested it in my wayland machine with mpv, firefox, and vivaldi(xwayland). Having used my locally built version for the last couple days didn't notice any difference than before.
> libva{,-glx,-utils}: update to 2.16.0.

- srcpkgs/lazydocker/template
> lazydocker: update to 0.20.0.

- srcpkgs/linux/template
As discussed on IRC, there don't seem to be any known issues with moving to 6.0.
> linux: update to 6.0.

- srcpkgs/wezterm-terminfo
- srcpkgs/wezterm/patches/0001-32bit.patch
- srcpkgs/wezterm/patches/0002-remove-distro-fonts.patch
- srcpkgs/wezterm/patches/remove-libgit.patch
- srcpkgs/wezterm/template
- srcpkgs/wezterm/update
- I built this PR locally for my native architecture, (`x86_64`-`glibc`)
> New package: wezterm-20220905_1

- srcpkgs/libtool/patches/0002-rename-with-sysroot.patch
- srcpkgs/libtool/patches/fix-tests-grep-3.8.patch
- srcpkgs/libtool/template
Most of the testing for this was done as a part of the [gcc12 PR](https://github.com/void-linux/void-packages/pull/34902), this was split on request.
Most of the build failures experienced were due to hardcoded version-mismatches and the libtool files not getting regenerated properly.
This also defines `lt_cv_shlibpath_overrides_runpath=yes` on musl since it always searches LD_LIBRARY_PATH before RPATH and RUNPATH and not defining it causes some tests to fail which verify this behavior.
Please test this PR before merging.
> libtool: update to 2.4.7.

- srcpkgs/juCi++/template
This package was built with GCC 12. No errors to report.
[jucixx.txt](https://github.com/void-linux/void-packages/files/10026430/jucixx.txt)
Related to #39809.
> juCi++: update to 1.7.2.

- srcpkgs/nextcloud-client/template
> nextcloud-client: update to 3.6.2

- srcpkgs/python3-psutil/template
> python3-psutil: update to 5.9.4.

- srcpkgs/nano/template
> nano: update to 7.0.

- srcpkgs/containerd/template
> containerd: update to 1.6.10.

- srcpkgs/spice/template
Updated, and removed python 2 dependency (#38229).
I didn't do much testing other than making sure that the tests pass and that `qemu-system-x86_64` doesn't crash.
The python scripts as far as I can tell are only involved in unit testing; moreover, upstream [uses python3](https://gitlab.freedesktop.org/spice/spice/-/blob/master/.gitlab-ci.yml) in their CI. 
> spice: update to 0.15.1.

- srcpkgs/libnma/patches/remove-path-from-eap-schema.patch
- srcpkgs/libnma/template
The path in the EAP schema file is preventing people from creating new VPN connections.
> libnma: remove path from EAP schema

- srcpkgs/docker-cli/template
I've added the mechanism to build and install the manpages for docker.
> docker: install manpages

- srcpkgs/LimeSuite/template
holding off on merging until they make a full release, it seems they tag early sometimes
> LimeSuite: update to 22.09.1.

- common/hooks/do-extract/00-distfiles.sh
- srcpkgs/bitwig-studio/template
- srcpkgs/brother-brscan3/template
- srcpkgs/brother-dcp197c-cupswrapper/template
- srcpkgs/brother-dcp197c-lpr/template
- srcpkgs/clearlooks-phenix-darkpurpy-theme/template
- srcpkgs/debootstrap/template
- srcpkgs/fah/template
- srcpkgs/google-chrome/template
- srcpkgs/google-earth-pro/template
- srcpkgs/helden-software/template
- srcpkgs/msbuild-bin/template
- srcpkgs/openbazaar/template
- srcpkgs/parsec/template
- srcpkgs/protonmail-bridge/template
- srcpkgs/slack-desktop/template
- srcpkgs/spotify/template
- srcpkgs/teams-bin/template
- srcpkgs/vivaldi/template
- srcpkgs/xkb-qwerty-fr/template
- srcpkgs/yandex-disk/template
- I tested the changes in this PR: **YES** (tested extraction/installation works for all packages with debs, packages generated are sane and are the same as before, except where deliberately changed)
> common/hooks/do-extract/00-distfiles.sh: support deb files

- srcpkgs/glslViewer/patches/liblo.patch
- srcpkgs/glslViewer/template
This package was built with GCC 12. No errors to report.
[glslviewer.txt](https://github.com/void-linux/void-packages/files/10036481/glslviewer.txt)
In reference to #39809.
> glslViewer: update to 3.0.7.

- srcpkgs/coturn/template
> coturn: update to 4.6.0.

- srcpkgs/xdm/patches/glibc-2.36.patch
Refer to #39960.
[xdm.txt](https://github.com/void-linux/void-packages/files/10048371/xdm.txt)
- x86_64
> xdm: fix build with glibc 2.36

- srcpkgs/android-tools/template
- srcpkgs/android-tools/update
> android-tools: update to 33.0.3p1, fix update-check

- srcpkgs/toot/template
Also change maintainer to me, since Nathan no longer uses Void.
Note, I'm using it as my main client, but have only tested the musl version. I did test cross-builds for `i686`, `armv6l` and `x86_64` though, without problem. And xlint gave no errors (trivial change).
- I built this PR locally for my native architecture, (ARCH-MUSL)
- x86_64 (crossbuild)
> toot: update to 0.29.0

- srcpkgs/tailscale/template
This new release contains fixes for CVE-2022-41925/TS-2022-005.
> tailscale: update to 1.32.3.

- common/shlibs
- srcpkgs/readosm-devel
- srcpkgs/readosm/template
- srcpkgs/spatialite-tools/patches/spatialite-tools_lxml2.patch
- srcpkgs/spatialite-tools/template
> New package: spatialite-tools, readosm

- srcpkgs/docker-compose/template
Update to 2.12.2 is also necessary to fix a CVE.
> docker-compose: update to 2.12.2.

- srcpkgs/pmbootstrap/template
> pmbootstrap: update to 1.50.0.

- srcpkgs/python3-ansible-compat/template
- srcpkgs/python3-ansible-lint/template
- python3-ansible-compat: update to 2.2.5.
- python3-ansible-lint: update to 6.8.7.
> python3-ansible-lint: update to 6.8.7.

- srcpkgs/element-desktop/template
I'm a bit unhappy about the two `jq` lines. Working with `vsed` wouldn't have been any easier here, but checking that the file actually changes with something like `vjq` would make me a lot happier. Any opinions on that?
> element-desktop: update to 1.11.15.

- srcpkgs/exiftool/template
> exiftool: update to 12.51.

- srcpkgs/libssh/template
> libssh: update to 0.10.4, adopt

- srcpkgs/libjpeg-turbo/template
> libjpeg-turbo: update to 2.1.4.

- srcpkgs/python3-cypari2/template
Note that running pytest will run a few tests, but running `make check` will run many more tests (including all the pytest tests).
No need to revbump as there are no changes to package itself.
> python3-cypari2: reenable full testsuite

- srcpkgs/ccls/template
- I built this PR locally for these architectures (X) means crossbuilded:
- x86_64
- i686 
- aarch64-musl (X)
- aarch64 (X)
- armv7l-mus (X)l
- armv7l (X)
- armv6l-musl (X)
- armv6l (X)
> ccls: update to 0.20220729.

- srcpkgs/fcitx5-qt/template
added in #30714, but it seems to have never been necessary.
the test on this block always evaluates false because `XBPS_TARGET_NOATOMIC8` is never set, so it is never run (the variable is actually `XBPS_TARGET_NO_ATOMIC8`).
Because it was never active it should not change the resultant package on armv6 or other no atomic8 platforms.
> fcitx5-qt: remove unused conditional block

- srcpkgs/libbytesize/template
- I tested the changes in this PR: **NO**, small bump news  doesn't state anything that could change workflow, 
`https://github.com/storaged-project/libbytesize/blob/master/NEWS.rst` 
> libbytesize: update to 2.7.

- srcpkgs/cherrytree/template
---
To explain the changes, cherrytree now has tests that run as part of the build process right after building the program. These tests require access to an X server, and I don't think it would be good to run the entire build under `xvfb-run` or something like that. Cherrytree also uses a bundled version of gtest and will attempt to build it regardless of whether tests are enabled unless a configure arg is set and gtest is available in the environment.
> cherrytree: update to 0.99.51

- srcpkgs/linux-firmware-dvb/template
With the latest revision 5 I've removed firmware but forgot to remove the license files.
This PR does remove the no longer necessary files.
> linux-firmware-dvb: remove now unnecessary license files

- srcpkgs/EternalTerminal/patches/disable-tests.patch
- srcpkgs/EternalTerminal/patches/fix-cflags.patch
- srcpkgs/EternalTerminal/template
This package was built with GCC 12 unless noted otherwise. No errors to report.
* [eternalterminal-x86_64.txt](https://github.com/void-linux/void-packages/files/10057240/eternalterminal-x86_64.txt)
* [eternalterminal-x86_64-musl.txt](https://github.com/void-linux/void-packages/files/10057241/eternalterminal-x86_64-musl.txt)
* [eternalterminal-armv6l-musl-gcc10.txt](https://github.com/void-linux/void-packages/files/10057238/eternalterminal-armv6l-musl-gcc10.txt)
Refer to #39960.
- x86_64
- armv6l-musl (cross; GCC 10.2)
> EternalTerminal: update to 6.2.1.

- srcpkgs/docker-cli/template
- srcpkgs/moby/template
docker was updates to 20.10.21 but the docker server (moby) is still on 20.10.17. Also I found out that btrfs >= 5.19 as a storage driver is only supported by the newer version.
In the future it would make sense to update moby together with the other docker packages.
> moby: update to 20.10.21.

- srcpkgs/wezterm/patches/monospace.patch
- srcpkgs/wezterm/template
This patches Wezterm to always select the `monospace` font; as opposed to requiring the `JetBrains Mono` font.
I tested the modifications on Void x86_64-musl, ensured no user fonts were installed - which by proxy include no `JetBrains Mono`.
See: #40736
> wezterm: default to system monospace font

- srcpkgs/linux-firmware/template
> linux-firmware: update to 20221109

- srcpkgs/python3-ansible-lint/template
> python3-ansible-lint: update to 6.9.0.

- srcpkgs/rust-sccache/template
supersedes https://github.com/void-linux/void-packages/pull/39767
> rust-sccache: update to 0.3.1.

- srcpkgs/tracebox/template
Credits go to Duncan Overbruck for suggesting to use -std=c++14 (see #40751).
[tracebox.txt](https://github.com/void-linux/void-packages/files/10093587/tracebox.txt)
> tracebox: fix build with glibc 2.36

- srcpkgs/qsv/template
I was not quite sure whether to submit `qsv` as a new package or rename `xsv`. I went with the later option for now as their [README](https://github.com/jqnatividad/qsv/blob/0.70.0/README.md) states:
> NOTE: qsv is a fork of the popular [xsv](https://github.com/BurntSushi/xsv) utility, merging several pending PRs https://github.com/BurntSushi/xsv/issues/267. On top of xsv's 20 commands, it adds numerous new features, 28 additional commands, 6 apply subcommands & 33 apply operations (for a total of 87). See [FAQ](https://github.com/jqnatividad/qsv/discussions/categories/faq) for more details.
cc: @leahneukirchen
> New package: qsv-0.70.0.

- srcpkgs/libgbinder/template
> libgbinder: update to 1.1.28.

- srcpkgs/ruby-build/template
> ruby-build: update to 20221124.

- srcpkgs/blueprint-compiler/template
I updated #37132 and tested against that, still builds fine.
> blueprint-compiler: update to 0.6.0.

- srcpkgs/doomretro/template
The current version fails with:
```
The wrong version of SDL2.so was found. DOOM Retro requires v2.24.0.
```
> doomretro: recompile with newer SDL2

- srcpkgs/fotoxx/template
- aarch64-musl
- armv7l
- armv6l-musl
> fotoxx: update to 22.50.

- srcpkgs/budgie-screensaver/patches/fix-musl.patch
- srcpkgs/budgie-screensaver/template
Patch reported upstream: https://github.com/BuddiesOfBudgie/budgie-screensaver/pull/15
> budgie-screensaver: update to 5.1.0.

- srcpkgs/safeeyes/patches/fix-getargspec.patch
- srcpkgs/safeeyes/template
Also fix getargspec error with python 3.11. See https://github.com/slgobinath/SafeEyes/issues/491
> safeeyes: update to 2.1.4 and fix error.

- srcpkgs/retroarch/template
> retroarch: update to 1.13.0

- common/xbps-src/shutils/update_check.sh
...unless they use the update override file
> common/xbps-src/shutils/update_check.sh: ignore pkgs without distfiles

- srcpkgs/zfs/template
> zfs: do not ship autotools cache, ship initramfs-tools

- srcpkgs/coturn/INSTALL
- srcpkgs/coturn/template
In some cases (corporate firewalls, hospitals) it may be desirable to have a TURN service on 443 because this is open in every case.
To allow that, allow the turnserver to bind to ports below 1024.
cc @Vaelatern
> coturn: allow to bind to ports below 1024

- common/hooks/pre-pkg/04-generate-runtime-deps.sh
While we're at it, mark one more variables as local
> gen-runtime-deps: verify rdeps for shlib_requires too

- srcpkgs/ipp-usb/template
This release contains essentially just a single bug fix made in this commit: https://github.com/OpenPrinting/ipp-usb/commit/04d3e39d5b879eec57198de41356f05d62aaff7a
> ipp-usb: update to 0.9.23.

- srcpkgs/socat/template
The extra `configure_args` for musl is no longer necessary since this has been fixed upstream.
See: https://repo.or.cz/socat.git/commit/75cb44bc90577c3487458564ca803163681319f1
- x86_64 (crossbuild)
> socat: update to 1.7.4.4.

- srcpkgs/hplip/INSTALL
- srcpkgs/hplip/REMOVE
- srcpkgs/hplip/hplip-gui.INSTALL
- srcpkgs/hplip/hplip-gui.REMOVE
- srcpkgs/hplip/template
The `hplip-gui` package uses the exact same files as the regular `hplip` package, plus a few extra for the UI and three changes in the configuration file. Rather than copy the entire package contents and register `conflict=` and `provides=` to fool the package manager, we can make `hplip-gui` depend on `hplip` and just manage a symlink between two alternative configuration files.
The only really sophisticated part is handling the configuration symlink when removing `hplip-gui`. Because a  user might remove the GUI package and want to keep the non-GUI version installed, the remove hook should detect whether a) it owns the existing symlink (*i.e.*, the link points at the GUI configuration) and b) whether the non-GUI configuration exists (in which case the link should be moved to the non-GUI …
> hplip: prevent conflicts with the GUI package

- srcpkgs/alsa-lib/template
- srcpkgs/alsa-ucm-conf/template
- srcpkgs/alsa-utils/template
Currently successfully testing with the following audio devices on x86_64-GLIBC:
* Intel Corporation Comet Lake PCH-LP cAVS
* Intel Corporation Alder Lake PCH-P High Definition Audio Controller (rev 01)
> alsa-{lib,utils,ucm-conf}: update to 1.2.8

- srcpkgs/fakeroot/patches/cross-dont-run-sysv-ipc-test.patch
- srcpkgs/fakeroot/patches/do-not-redefine-id_t.patch
- srcpkgs/fakeroot/patches/fakeroot-stdint.patch
- srcpkgs/fakeroot/template
This package was built with GCC 12 unless noted otherwise. No errors to report.
* [fakeroot.x86_64.txt](https://github.com/void-linux/void-packages/files/10051287/fakeroot.x86_64.txt)
* [fakeroot.x86_64-musl.txt](https://github.com/void-linux/void-packages/files/10051288/fakeroot.x86_64-musl.txt)
* [fakeroot.armv6l-musl-gcc10.2.txt](https://github.com/void-linux/void-packages/files/10051289/fakeroot.armv6l-musl-gcc10.2.txt)
Refer to #39960.
- x86_64
- armv6l-musl (crossbuild; GCC 10.2)
> fakeroot: update to 1.29.

- srcpkgs/rawtherapee/patches/glibc-2.36.patch
This package was built with GCC 12. No errors to report.
* [rawtherapee-x86_64.txt](https://github.com/void-linux/void-packages/files/10068827/rawtherapee-x86_64.txt)
* [rawtherapee-x86_64-musl.txt](https://github.com/void-linux/void-packages/files/10068829/rawtherapee-x86_64-musl.txt)
Related to #39960.
- x86_64
> rawtherapee: fix build with glibc 2.36

- common/shlibs
- srcpkgs/cpp-hocon-devel
- srcpkgs/cpp-hocon/template
- srcpkgs/facter/patches/shared_cpp_hcon.patch
- srcpkgs/facter/template
- srcpkgs/leatherman/template
tests do not build with gcc 12
> cpp-hocon: add shared library, disable tests build

- srcpkgs/Cataclysm-DDA/patches/gcc-12.patch
- srcpkgs/Cataclysm-DDA/patches/no-werror.patch
- srcpkgs/Cataclysm-DDA/template
> [do not merge] cabbage: fix build for gcc 12

- srcpkgs/pass-import/patches/makedoc.patch
- srcpkgs/pass-import/template
> pass-import: update to 3.3.

- common/shlibs
- srcpkgs/igraph/template
- srcpkgs/rankwidth/patches/igraph-0.10.patch
- srcpkgs/rankwidth/template
I run sagemath testsuite with this update.
> igraph: update to 0.10.2.

- srcpkgs/tcc/template
> tcc: update to 0.9.27.20221203.1.

- srcpkgs/buku/patches/remove-cgi-warning.patch
- srcpkgs/buku/template
Followup of #40551.
Add the necessary patch to remove the DeprecationWarning `'cgi' is deprecated and slated for removal in Python 3.13` in buku caused by Python3 version update (3.11 as of writing).
- armv6l 
- `xlint` also reports no error.
> buku: fix cgi deprecation warning for python3>=3.11

- srcpkgs/cross-arm-none-eabi-gdb/template
- aarch (cross built from x86-64)
> cross-arm-none-eabi-gdb: update to 12.1, fix build for gcc-12

- srcpkgs/libgbinder/template
> libgbinder: update to 1.1.30.

- srcpkgs/kanshi/template
The most recent release of kanshi added an optional kanshictl utility, which
uses varlink. If libvarlink-devel is available at build time, meson will
automatically enable that functionality and provide both the binary and the man
page for it.
> kanshi: add dependency on libvarlink to enable building kanshictl

- srcpkgs/octave/template
- srcpkgs/rapidjson/patches/5d9d0f78b53dd8cd1ec757fd8ef07211ee114161.patch
- srcpkgs/rapidjson/template
- Fix cross build
- Use SuiteSparse
- Use rapidjson
- Use --disable-docs to skip building docs, instead install the docs in
the tarball. This way we don't need texlive/texinfo/gnuplot to build.
- Avoid warnings due to egrep deprecation
- xlint fixes
---
I wonder if we really want all those build options. I am tempted to remove almost all of them.
I also wonder if the choice of `GraphicsMagick` over `ImageMagick` is the best one.
NOTE: this PR includes #39846 for the current SuiteSparse. Could work with the current SuiteSparse, but I didn't try (#39846 is ready to merge IMO; the CI failures in that PR are addressed in the comments)
> octave: update to 7.3.0.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.0.1.

- srcpkgs/helix/template
> helix: update to 22.12

- srcpkgs/python3-gmpy2/template
> python3-gmpy2: update to 2.1.3.

- srcpkgs/discord-ptb/files/LICENSE
- srcpkgs/discord-ptb/template
Switch away from the janky EULA download setup in favour of a file that links to the actual current version of the terms, just like the discord package.
> discord-ptb: update to 0.0.38.

- srcpkgs/rust-cargo-bloat/template
> rust-cargo-bloat: update to 0.11.1.

- srcpkgs/SPIRV-LLVM-Translator/template
Fixes the following build error;
```
-- The CXX compiler identification is GNU 10.2.1
-- The C compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /builddir/.xbps-SPIRV-LLVM-Translator/wrappers/aarch64-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /builddir/.xbps-SPIRV-LLVM-Translator/wrappers/aarch64-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
CMake …
```
> SPIRV-LLVM-Translator: fix cross build

- srcpkgs/nextcloud-client/template
> nextcloud-client: update to 3.6.4

- srcpkgs/zellij/template
> zellij: update to 0.34.3

- srcpkgs/libmpc/template
I'm running full sagemath testsuite with this.
> libmpc: update to 1.3.0, adopt.

- srcpkgs/arti/template
> arti: update to 1.1.0.

- common/shlibs
- srcpkgs/flightgear/template
- srcpkgs/flightgear/update
- srcpkgs/simgear/template
> flightgear: update to 2020.3.17

- srcpkgs/python3-pycryptodomex/template
I tested the changes in this PR: **briefly**
```
~ ❯ salt --versions | ag '(Salt|dome):'
/usr/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
warnings.warn("Setuptools is replacing distutils.")
Salt: 3005
pycryptodome: 3.16.0
```
That stuff about distuils comes from Salt, not Cryptodome:
```
~ ❯ ag distutils /usr/lib/python3.11/site-packages/{Cryptodome,salt}
/usr/lib/python3.11/site-packages/salt/modules/virtualenv_mod.py
352:        "from distutils import sysconfig; print(sysconfig.get_python_lib())",
/usr/lib/python3.11/site-packages/salt/modules/puppet.py
9:from distutils import version  # pylint: disable=no-name-in-module
/usr/lib/python3.11/site-packages/salt/utils/pkg/win.py
78:    from distutils.version import …
```
> python3-pycryptodomex: update to 3.16.0.

- srcpkgs/spotify/template
Spotify onlys get a generic "X11" icon in the task manager. No window title is shown either.
The template moves the "icons" folder provided by spotify to /usr/share/spotify. However, it appears that spotify searches for the icons in /usr/libexec/spotify.
Create a symlink to /usr/share/spotify/icons so spotify finds the icons again.
This makes the spotify icon appear in the KDE taskbar. It also sets the title of the spotify window.
Fixes: #36615
> spotify: Fix missing icon in KDE task manager

- srcpkgs/rust-bindgen/template
- aarch64
- aarch64-musl
- armv6l
- armv6l-musl
- i686
- x86_64-musl
> rust-bindgen: update to 0.63.0.

- srcpkgs/miniflux/template
- I built this PR locally for my native architecture, amd64
[2.0.41](https://github.com/miniflux/v2/releases/tag/2.0.41) fixes "Refresh all feeds" crash, see [#1290](https://github.com/miniflux/v2/pull/1290) which made prior version unusable with multiple feeds.
> miniflux: update to 2.0.41

- common/shlibs
- srcpkgs/libplacebo/template
- srcpkgs/mpv/template
- srcpkgs/vlc/template
Checked that both `vlc` and `mpv` (my primary video player) still plays some MP4 I had around, this is being upgraded as per https://github.com/void-linux/void-packages/pull/40747#issuecomment-1346769173.
5.229.1 update PR (4.x -> 5.x major version): https://github.com/void-linux/void-packages/pull/40807
Cc. @paper42
> libplacebo: update to 4.208.0.

- srcpkgs/python3-pathspec/template
> python3-pathspec: update to 0.10.3.

- srcpkgs/buildah/template
- srcpkgs/containers.storage/template
- srcpkgs/podman/template
- srcpkgs/skopeo/template
Install the containers.storage configuration file so that the graph driver defaults to overlay, not vfs.
vfs uses too much storage.
https://gitlab.com/clickable/clickable/-/issues/390
- New package: containers.storage-1.37.3
- podman: add dependency on containers.storage
- buildah: update to 1.28.2, add dep on storage
- skopeo: add dependency on containers.storage
> containers storage

- srcpkgs/libutempter/INSTALL
- srcpkgs/libutempter/template
- srcpkgs/screen/template
- srcpkgs/tmux/template
utempter was not installed setgid `utmp`, so it didn't work.
Enable utempter for screen and tmux.
ping @sgn and @steinex.
- I tested the changes in this PR: **YES***
> Fix utempter

- srcpkgs/fifechan/template
- srcpkgs/libxkbfile/template
These two packages do not actually have a `maintainer` specified, not even the standard "Orphaned <orphan@voidlinux.org>" so lint on these two fails. This PR adds it.
> Explicitly orphan fifechan and libxkbfile

- srcpkgs/nwg-launchers/patches/disable-readme-generation.patch
- srcpkgs/nwg-launchers/template
> nwg-launchers: update to 0.7.1.1

- srcpkgs/vivaldi/template
> vivaldi: update to 5.6.2867.36

- srcpkgs/python3-ansible-lint/template
> python3-ansible-lint: update to 6.10.0.

- srcpkgs/pantalaimon/template
- srcpkgs/python3-importlib_metadata/template
- srcpkgs/python3-keyring/template
- srcpkgs/python3-zipp/template
- srcpkgs/removed-packages/template
I noticed that `importlib_metadata` got removed in https://github.com/void-linux/void-packages/pull/38287 but keyring again has it as a dependency. As per my understanding, `importlib_metadata` will always have backports from future python version(s) to the current one. For example, features introduced in `v5.*.*` are set to be merged in python3.12 stdlib.
> python3-keyring: update to 23.11.0.

- srcpkgs/go/template
> go: update to 1.19.4.

- srcpkgs/zellij/template
> zellij: update to 0.34.4

- srcpkgs/sagemath/patches/trac-33842-04-python3.11_fix_32_bit.patch
- srcpkgs/sagemath/template
After the upgrade to python 3.11, sagemath is completely broken (it won't even start).
See:  https://trac.sagemath.org/ticket/33842#comment:130
This revbump adds a fix taken from that trac ticket (https://trac.sagemath.org/ticket/33842#comment:137)
> sagemath: fix for 32 bit architectures

- srcpkgs/netdata-plugins-go/template
- srcpkgs/netdata-plugins-nodejs
- srcpkgs/netdata/template
- I tested the changes in this PR: **YES** (on `x86_64` and `x86_64-musl`)
- I built this PR locally for my native architecture
-  `x86_64{,-musl}`
- I built this PR locally for these architectures (all cross):
- `i686`
- `armv6l{,-musl}`
- `armv7l{,-musl}`
- `aarch64{,-musl}`
Nodejs subpackage got removed because upstream dropped `node.d` in 1.35 (following deprecation in 1.34).
Could be packaged separately using netdata's community repo but most likely not necessary anymore due to `go.d`.
`go.d` is packaged separately here because it looks to be an entirely separate project with it's own release cycle, only linked to the main netdata project through [this file](https://github.com/netdata/netdata/blob/v1.37/packaging/go.d.version). Assigned myself as the maintainer of `go.d` for now, …
> netdata v1.37.1

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.1.0.

- srcpkgs/delve/template
(I believe this build relies on the the newer gcc version that is still being built. Can test crosscompile in a few days if necessary.
> delve: update to 1.20.0.

- srcpkgs/ufetch/template
- I built this PR locally for these architectures (if supported. mark crossbuilds):  
- armv7l
> ufetch: update to 0.3.

- common/xbps-src/shutils/show.sh
previously, if there was a newline in some variables, it would not format
properly in `xbps-src show`. This fixes it by always splitting it by word
in some cases, like if there is a new line in the variable's value, and
removing internal commas in some cases.
This logic was split into a function for consistency.
fixes #40996
Example:
```
$ ./xbps-src show keepassxc
pkgname:	keepassxc
...
License(s):	GPL-3.0-or-later
License(s):	BSD-3-Clause
License(s):	CC0-1.0
License(s):	LGPL-2.0-only
License(s):	LGPL-2.1-only
License(s):	LGPL-3.0-or-later
License(s):	Nokia-Qt-exception-1.1
License(s):	MIT
License(s):	BSL-1.0
```
> common/xbps-src/shutils/show.sh: make show display consistent

- srcpkgs/waydroid/files/README.voidlinux
- srcpkgs/waydroid/files/waydroid-container/log/run
- srcpkgs/waydroid/template
> waydroid: update to 1.3.4.

- srcpkgs/praat/template
- aarch64
- armv7l-musl
- i686
- x86_64-musl
> praat: update to 6.3.03

- .github/workflows/build.yaml
- .github/workflows/cycles.yml
- common/travis/changed_templates.sh
- common/travis/fetch_upstream.sh
Summary:
- [use treeless fetches instead of `--depth`](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/)
- this is not supported by `actions/checkout`, so it was implemented as a short script (staying with `actions/checkout@v1` does not seem like a good idea because of its age, and updating to `actions/checkout@v3` would require adding `libstdc++` to any CI workflows that run in void containers because of node's requirements)
- This applies to the build and cycles CI workflows, and some additional cleanups were applied to the cycles workflow
- it can't be implemented as a script in `common/travis/` because the repo doesn't exist on the runner (yet!)
- `changed_templates.sh` had a small logic change, because we now have the complete commit history …
> ci: use treeless clone instead of actions/checkout

- srcpkgs/containers.storage/template
Based on feedback from @ahesford
ZFS does not support OverlayFS by default, so the fuse-overlayfs mount
program should be configured to workaround.
> containers.storage: improve ZFS compatibility

- srcpkgs/electron19/template
I didn't manage to apply a proper patch, but this at least fixes the build.
[ci skip]
depends on #40889
> electron19: fix build with gcc 12

- srcpkgs/rrdtool/patches/set_fallback_first_weekday_to_0.patch
- srcpkgs/rrdtool/template
- x86_64-musl
The test for https://github.com/void-linux/void-packages/pull/41228 fails with: 
> perl-rrdtool-1.7.2_13: broken, unresolvable shlib `libperl.so.5.36'
This can be reproduced by:
```
./xbps-src -m musl_temp binary-bootstrap x86_64-musl
./xbps-src -m musl_temp chroot
xbps-install perl-rrdtool
```
This is a due to missing "depends" on perl. 
This PR simply adds perl to the dependecy
CC @Gottox
> rrdtool: rebuild to fix unresolvable shlib, fix tests 

- srcpkgs/libsndfile/patches/identify-naked-mpeg-last.patch
- srcpkgs/libsndfile/template
This is the sequel to https://github.com/void-linux/void-packages/pull/36908, as the bug shown in musl is now fixed (see https://github.com/libsndfile/libsndfile/issues/830)
- x86_64-musl (only built, no test)
> libsndfile: update to 1.1.0 (v2)

- srcpkgs/act/template
Apache-2.0 licence added since upstream now includes some docker-cli code.
> act: update to 0.2.34.

- srcpkgs/python3-platformdirs/template
> python3-platformdirs: update to 2.6.0.

- srcpkgs/ccache/files/ccache.1
- srcpkgs/ccache/template
It doesn't link to zlib since [version 4.0](https://ccache.dev/releasenotes.html#_ccache_4_0).
I don't know why perl was in hostmakedepends but the build log is identical with and without it.
@Gottox 
> ccache: update to 4.7.4.

- srcpkgs/lmms/patches/fix-qt-crash-kwidgetsaddons-5.101.0.patch
- srcpkgs/lmms/template
Fixes the following segfault:
https://github.com/LMMS/lmms/issues/6587
Afaict the original workaround should already be fixed by:
https://invent.kde.org/frameworks/kxmlgui/-/commit/02b523bad09aab062355e46771889b0f3709692f
> lmms: remove broken KCheckAccelerators workaround

- srcpkgs/vivaldi/template
Tested as working on `aarch64-glibc` on a OnePlus 5T.
> vivaldi: update to 5.6.2867.50, build for aarch64 & armv7l

- srcpkgs/cpuburn/patches/02-m32.patch
- srcpkgs/cpuburn/template
The status quote of cpuburn is always built for 32bits on x86_64, which requires dynamic linker for 32 bit system.
On x86-64 system, we can workaround by depends on glibc-32bit. However, we don't have that luxury on x86_64-musl system.
Since `cpuburn` doesn't use any features from libc and/or dynamic linker, we can simply build static instead.
Fix #41307
> cpuburn: build statically

- srcpkgs/linux5.15/files/arm64-dotconfig
- srcpkgs/linux5.15/files/i386-dotconfig
- srcpkgs/linux5.15/files/ppc-dotconfig
- srcpkgs/linux5.15/files/ppc64-dotconfig
- srcpkgs/linux5.15/files/ppc64le-dotconfig
- srcpkgs/linux5.15/files/x86_64-dotconfig
- srcpkgs/linux6.0/files/arm64-dotconfig
- srcpkgs/linux6.0/files/i386-dotconfig
- srcpkgs/linux6.0/files/ppc-dotconfig
- srcpkgs/linux6.0/files/ppc64-dotconfig
- srcpkgs/linux6.0/files/ppc64le-dotconfig
- srcpkgs/linux6.0/files/x86_64-dotconfig
- srcpkgs/linux6.1/files/arm64-dotconfig
- srcpkgs/linux6.1/files/i386-dotconfig
- srcpkgs/linux6.1/files/ppc-dotconfig
- srcpkgs/linux6.1/files/ppc64-dotconfig
- srcpkgs/linux6.1/files/ppc64le-dotconfig
- srcpkgs/linux6.1/files/x86_64-dotconfig
I answered NO here since I don't run voids kernel config (but have my own with it enabled)
For landlock to be available CONFIG_SECURITY_LANDLOCK=y is not enough, it should also be added to CONFIG_LSM: https://docs.kernel.org/userspace-api/landlock.html#kernel-support
CC @sgn
> linux5.15+: Add landlock to CONFIG_LSM

- srcpkgs/python3-ansible-lint/template
> python3-ansible-lint: update to 6.10.1.

- srcpkgs/btrfs-progs/patches/fix-the-uuid-report-in-btrfs-subvolume-list--u.patch
- srcpkgs/btrfs-progs/template
```
pkg:btrfs-progs host:x86_64 target:x86_64 cross:n result:OK
pkg:btrfs-progs host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:btrfs-progs host:i686 target:i686 cross:n result:OK
pkg:btrfs-progs host:x86_64-musl target:aarch64-musl cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:aarch64 cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv7l-musl cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv7l cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv6l-musl cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv6l cross:y result:OK
```
> btrfs-progs: update to 6.1.

- srcpkgs/leafpad/template
- x86_64-musl
- aarch64
- armv7l
> leafpad: udpate to 0.8.19

- srcpkgs/gitea/template
> gitea: update to 1.18.0

- srcpkgs/python3-txtorcon/template
> python3-txtorcon: update to 22.0.0.

- srcpkgs/ipsvd/patches/cross.patch
- srcpkgs/ipsvd/template
- srcpkgs/socklog-ucspi/files/socklog-ucspi-tcp/log/run
- srcpkgs/socklog-ucspi/files/socklog-ucspi-tcp/run
- srcpkgs/socklog-ucspi/template
cc: @leahneukirchen (socklog's maintainer)
Closes #41300.
The build method is not much different from socklog (the same author).
> New packages: ipsvd, socklog-ucspi

- srcpkgs/tree/template
- x86_64-musl
- aarch64
- armv7l
> tree: update to 2.1.0

- srcpkgs/unzip/patches/CVE-2021-4217.patch
- srcpkgs/unzip/patches/CVE-2022-0529.patch
- srcpkgs/unzip/patches/CVE-2022-0530.patch
- srcpkgs/unzip/patches/series
- srcpkgs/unzip/patches/unzip-6.0-fix-false-overlap-detection-on-32bit-systems.patch
- srcpkgs/unzip/patches/unzip-zipbomb-part4.patch
- srcpkgs/unzip/patches/unzip-zipbomb-part5.patch
- srcpkgs/unzip/patches/unzip-zipbomb-part6.patch
- srcpkgs/unzip/template
Sync a number of (CVE-related) patches from other distros:
unzip-zipbomb-part{4,5,6}.patch: Fedora
CVE-2021-4217.patch: Archlinux
CVE-2022-0529.patch,CVE-2022-0530.patch: Ubuntu
> unzip: sync patches from Fedora etc.

- srcpkgs/seahorse/patches/musl.patch
- srcpkgs/seahorse/template
- x86_64-musl
- aarch64
- armv7l
- Patched for musl: https://gitlab.gnome.org/GNOME/seahorse/-/merge_requests/211
> seahorse: update to 43.0

- srcpkgs/profile-cleaner/template
Makefile shipped with the package shortens profile-cleaner to pc, thus causing conflict with the 'pc' package.
Discovered in #41298.
> profile-cleaner: resolve conflict with pc

- srcpkgs/ulozto-downloader/template
Uloz.to quick multiple sessions downloader.
<https://github.com/setnicka/ulozto-downloader>
> New package: ulozto-downloader-3.3.0

- .gitignore
This prevents git from picking up masterdirs that don't happen to be named the usual way and more custom and temporary files that should not be tracked by git.
> .gitignore: explicitly allow paths

- common/environment/setup/sourcepkg.sh
- common/xbps-src/shutils/chroot.sh
From `curl` manpage:
```
ENVIRONMENT
The environment variables can be specified in lower case or upper case.
The lower case version has precedence. http_proxy is an exception as it
is only available in lower case.
```
I have `http_proxy` and `https_proxy` set, and then `xbps-src update-check` would not use the proxy. With this commit, it works as expected.
> xbps-src: keep http_proxy and other lowercase proxy variables

- common/environment/configure/debug-debug-prefix-map.sh
- srcpkgs/python3/template
We're setting -fdebug-prefix-map to strip directory prefixes from debug info, which will help ccache and reproducibility.
However, -fdebug-prefix-map doesn't help with those macros like __FILE__ and __BASE_FILE__, which needs another flags: -fmacro-prefix-map.
Replaces -fdebug-prefix-map with -ffile-prefix-map which is an alias for both `-fdebug-prefix-map` and `-fmacro-prefix-map`. (This flag is available since GCC 8 and Clang 10)
> environment: set -ffile-prefix-map

- common/shlibs
- srcpkgs/gtest/template
Also moves `usr/lib/*.so` to `-devel` subpackage and drops the unversioned `SONAME`s from `common/shlibs` since there are now versioned symlinks in case something starts needing them (`xrevshlib gtest` currently returns nothing).
> gtest: update to 1.12.1.

- srcpkgs/libgbinder/template
> libgbinder: update to 1.1.31.

- srcpkgs/xfce4-screenshooter/template
> xfce4-screenshooter: update to 1.10.2.

- srcpkgs/powertop/update
As the project moved to GitHub, no `update` file is needed anymore.
> powertop: fix update-check

- srcpkgs/android-udev-rules/template
> android-udev-rules: update to 20230104.

- srcpkgs/mu4e/template
- x86_64-musl
- Users will have to re-initialize their message database manually (`mu-init(1)`). 
- Users may have to adapt their configuration (e.g. `make-mu4e-bookmark` doesn't exist anymore).
- Since this package hasn't been updated in a while, it might good someone else also tested this.
> mu4e: update to 1.8.13

- srcpkgs/btrfs-progs/template
```
SUMMARY
pkg:btrfs-progs host:x86_64 target:x86_64 cross:n result:OK
pkg:btrfs-progs host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:btrfs-progs host:i686 target:i686 cross:n result:OK
pkg:btrfs-progs host:x86_64-musl target:aarch64-musl cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:aarch64 cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv7l-musl cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv7l cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv6l-musl cross:y result:OK
pkg:btrfs-progs host:x86_64-musl target:armv6l cross:y result:OK
```
> btrfs-progs: update to 6.1.2.

- srcpkgs/python3-importlib_metadata/template
> python3-importlib_metadata: update to 6.0.0.

- srcpkgs/python3-ansicolors/template
- srcpkgs/ulozto-downloader/template
The original template had a wrong dependency `python3-ansicolor`, whereas the program needs `python3-ansicolors`. This new dependency has been added as a new package in a second commit.
> ulozto-downloader: update to 3.3.1, fix dependency

- srcpkgs/easyeffects/template
I updated this to see if an update fixed my issue and the newer version gave me a nice message saying the stereo tools didn't work because I didn't have `calf`.
Version 6.3.0 added an optional dependency on "Linux Studio Plugins" but I haven't packaged it in this PR.
@paper42
> easyeffects: update to 7.0.0

- common/travis/license.lst
- srcpkgs/spdx-licenses-list/template
Also:
- update common/travis/license.lst.
> spdx-licenses-list: update to 3.19.

- srcpkgs/lxpanel/patches/fix-panel-size.patch
- srcpkgs/lxpanel/template
The provided patch fixes panel width not taking size of the screen.
Fixes #41479.
> lxpanel: patch panel size under GTK3

- srcpkgs/mkinitcpio-nfs-utils/files/initcpio-hook-net
- srcpkgs/mkinitcpio-nfs-utils/files/initcpio-install-net
- srcpkgs/mkinitcpio-nfs-utils/template
The `net` hook for `mkinitcpio` shipped by this package uses a helper to do v2 or v3 mounts that support locking without the need for a local `lockd` in the initramfs. The helper does not support v4 mounts and v4 does not require a local `lockd`, so we can look for an NFS version requirement in the root spec and directly call `mount -t nfs4` instead of `nfsmount` to support v4 roots.
- I tested the changes in this PR: **in progress**
> mkinitcpio-nfs-utils: support NFSv4 roots

- srcpkgs/libcotp/template
Fixes regression introduced in libcotp 1.2.7: https://github.com/paolostivanin/libcotp/issues/33
> libcotp: update to 1.2.8

- srcpkgs/kdenlive/template
- srcpkgs/mlt7/template
- mlt7: update to 7.12.0.
- kdenlive: update to 22.12.1.
> kdenlive: update to 22.12.1.

- srcpkgs/bspwm/patches/fix-windows-not-appearing.patch
- srcpkgs/bspwm/template
Apparently gtk-based software is affected by this bug.
The upstream patch fixes the issue in question.
> bspwm: patch windows sometimes not appearing

- srcpkgs/flatpak/template
- srcpkgs/gnome-software/template
- srcpkgs/libostree/template
Also fixes a gnome-software crash related to libsoup2
(note: libostree still depends on libsoup2 even with `--with-curl`, but that should be fine https://github.com/ostreedev/ostree/blob/1fb9404612f3d98d329f0129ecbc6c8225823679/configure.ac#L137)
> gnome-software: update to 43.3.

- srcpkgs/cadaver/template
- x86_64-musl
- The homepage has moved
- `distfiles` now also points to the new homepage
> cadaver: update to 0.24

- srcpkgs/python3-jq/template
> python3-jq: update to 1.4.0

- srcpkgs/gotify-cli/template
- srcpkgs/gotify-server/template
- srcpkgs/up_rewrite/template
UnifiedPush [killed their fork of gotify-android with UnifiedPush support](https://github.com/UnifiedPush/gotify-android/#deprecated), so I have no use for this anymore. Reccomend ntfy as a similar alternative, currently in a PR here: https://github.com/void-linux/void-packages/pull/41427
EDIT: and [since ntfy has a built-in Matrix Push Gateway](https://docs.ntfy.sh/publish/?h=matrix#matrix-gateway), I no longer need up_rewrite either.
> gotify-cli, up_rewrite: orphan; gotify-server: update to 2.2.3, orphan.

- srcpkgs/routinator/files/routinator/log/run
- srcpkgs/routinator/files/routinator/run
- srcpkgs/routinator/template
Update to 0.12.0 and add runit service.
No longer relevant for now: 
- Build and include documentation
- Add missing python packages required for documentation
- python3-sphinx-tabs
- python3-sphinx-copybutton
Release notes at https://github.com/NLnetLabs/routinator/releases
- aarch64-musl
- armv7l
- armv6l-musl
- x86_64-musl
> routinator: update to 0.12.1 and add runit service.

- srcpkgs/perl-CGI/template
- I tested the changes in this PR: **YES** (they just removed a check-dependency on perl-Test-Deep)
- armv7l-musl
> perl-CGI: update to 4.55

- srcpkgs/chroot-grep/patches/efgrep-remove-warning.patch
- srcpkgs/chroot-grep/template
This mirrors the changes from grep in https://github.com/void-linux/void-packages/commit/ef5ffe4d696b31041c272be92e912fb454c075ac into chroot-grep.
> chroot-grep: patch out problematic warnings in egrep and fgrep.

- srcpkgs/libxkbcommon/template
- srcpkgs/sway/patches/7326.diff
- srcpkgs/sway/template
Setting these capabilities on the Sway binary breaks loading custom keymaps in user directories.
Relevant:
- https://github.com/swaywm/sway/pull/7326 (this commit can be reverted when this PR is merged in a future Sway release)
- https://github.com/xkbcommon/libxkbcommon/pull/312
> sway:  fix custom user keymaps.

- srcpkgs/enchant2/template
```
SUMMARY                                     
pkg       host         target        cross  result
enchant2  x86_64       x86_64        n      OK
enchant2  x86_64-musl  x86_64-musl   n      OK
enchant2  i686         i686          n      OK
enchant2  x86_64-musl  aarch64-musl  y      OK
enchant2  x86_64-musl  aarch64       y      OK
enchant2  x86_64-musl  armv7l-musl   y      OK
enchant2  x86_64-musl  armv7l        y      OK
enchant2  x86_64-musl  armv6l-musl   y      OK
enchant2  x86_64-musl  armv6l        y      OK
```
> enchant2: update to 2.3.3.

- srcpkgs/swirc/template
> swirc: update to 3.3.9.

- common/environment/build-style/go.sh
Change hard-coded value of `CGO_ENABLED` to allow reading a user configured value from a template file. This is required to fix a segmentation fault in #40919, derived from some kind of linking error. The default behavior is kept, i.e. cgo is still enabled by default, which shouldn't break any packages.
> common/environment/build-style/go.sh: allow setting CGO_ENABLED

- srcpkgs/batsignal/template
```
pkg:batsignal host:x86_64 target:x86_64 cross:n result:OK
pkg:batsignal host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:batsignal host:i686 target:i686 cross:n result:OK
pkg:batsignal host:x86_64-musl target:aarch64-musl cross:y result:OK
pkg:batsignal host:x86_64-musl target:aarch64 cross:y result:OK
pkg:batsignal host:x86_64-musl target:armv7l-musl cross:y result:OK
pkg:batsignal host:x86_64-musl target:armv7l cross:y result:OK
pkg:batsignal host:x86_64-musl target:armv6l-musl cross:y result:OK
pkg:batsignal host:x86_64-musl target:armv6l cross:y result:OK
```
Happy Holidays everyone !
> batsignal: update to 1.6.4.

- srcpkgs/openrgb/patches/musl.patch
- srcpkgs/openrgb/template
- I tested the changes in this PR: **YES** (but only on glibc)
- `musl.patch` removed as the relevant change is now incorporated in the release ([openrgb@48d1a4f7](https://gitlab.com/CalcProgrammer1/OpenRGB/-/commit/48d1a4f7b60198e13009ff32879d07986ca6a9ec))
> openrgb: update to 0.8

- srcpkgs/io.elementary.files/template
Orphan (due to disuse)
Add missing runtime dependencies
> io.elementary.files: update to 6.2.1

- srcpkgs/qutebrowser/template
I don't really use Qutebrowser nowadays.
- I tested the changes in this PR: **YES**?
> qutebrowser: orphan.

- srcpkgs/flatpak-builder/template
> flatpak-builder: update to 1.2.3.

- srcpkgs/discord/template
Updates Discord to 0.0.24. I removed the reference to chrome_crashpad_handler since it doesn't seem to exist, though given the discussion in #41609 I'm not sure what's up with that
> discord: Update to 0.0.24

- srcpkgs/gnupg/template
- srcpkgs/libgpg-error/template
- srcpkgs/libksba/template
I'd like others to test this as well. Last time, we've had problems with people
running into issues. <del>And we've got an additional problem this time, because
their test suite isn't passing, which at least some other distros are also
running into.</del> I'd like to keep this open as a draft for now, but I'm using it
for now.
EDIT: The problem with the test suite has been fixed by applying an upstream patch, thanks for the help with automake @kruceter
> gnupg: update to 2.4.0.

- srcpkgs/python3-ansible-lint/template
> python3-ansible-lint: update to 6.10.2.

- srcpkgs/zita-alsa-pcmi/template
- I tested the changes in this PR: **briefly** (tested with `jaaa`)
- aarch64
- armv7l-musl
- x86_64-musl
- i686
> zita-alsa-pcmi: update to 0.6.1

- srcpkgs/ImageMagick/template
```
pkg          host         target        cross  result
ImageMagick  x86_64       x86_64        n      OK
ImageMagick  x86_64-musl  x86_64-musl   n      OK
ImageMagick  i686         i686          n      OK
ImageMagick  x86_64-musl  aarch64-musl  y      OK
ImageMagick  x86_64-musl  aarch64       y      OK
ImageMagick  x86_64-musl  armv7l-musl   y      OK
ImageMagick  x86_64-musl  armv7l        y      OK
ImageMagick  x86_64-musl  armv6l-musl   y      OK
ImageMagick  x86_64-musl  armv6l        y      OK
```
> ImageMagick: update to 7.1.0.57.

- srcpkgs/devilutionX/template
Apparently upstream needs some tool to pack assets into one file.
If such a tool is not used within CMake, `do_install()` will not install the binary, icons, etc to `$DESTDIR`.
Pull request #39184 had encountered this behaviour and placed needed files manually as a result.
Packaging `smpq` is a little too much, hence `mpqtool` is used with little patching to address all issues listed above.
> devilutionX: update to 1.4.1.

- srcpkgs/v2ray/files/v2ray/run
- srcpkgs/v2ray/template
- x86_64-musl
- i686
- i686-musl
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- ppc64le
> v2ray: add `run` to launch command for v2ray>=5.1.0

- srcpkgs/python3-yamllint/template
> python3-yamllint: update to 1.29.0.

- srcpkgs/iputils/template
Relevant changelog entries for the template and xpkgdiff changes:
> removed tools: ninfod, rdisc
> Meson build system: enable NO_SETCAP_OR_SUID by default
> iputils: update to 20221126.

- srcpkgs/SDL2_ttf/template
```
SUMMARY
pkg       host         target        cross  result
SDL2_ttf  x86_64       x86_64        n      OK
SDL2_ttf  x86_64-musl  x86_64-musl   n      OK
SDL2_ttf  i686         i686          n      OK
SDL2_ttf  x86_64-musl  aarch64-musl  y      OK
SDL2_ttf  x86_64-musl  aarch64       y      OK
SDL2_ttf  x86_64-musl  armv7l-musl   y      OK
SDL2_ttf  x86_64-musl  armv7l        y      OK
SDL2_ttf  x86_64-musl  armv6l-musl   y      OK
SDL2_ttf  x86_64-musl  armv6l        y      OK
```
> SDL2_ttf: update to 2.20.1.

- srcpkgs/hunspell-pt_PT-preao/template
Related to #41623, don't know if I can do two packages in one PR. Let's hope my University's server doesn't decide to time out for GitHub Actions for this one.
> hunspell-pt_PT-preao: update to 20220621.

- srcpkgs/perl-Params-ValidationCompiler/template
- I tested the changes in this PR: **YES** (only change is that it checks for Class::XSAccessor 1.17+, we’re at 1.19)
- armv7l-musl
> perl-Params-ValidationCompiler: update to 0.31

- srcpkgs/dracut/template
Other changes:
- remove more systemd dependent modules
- network-manager module depends on the dbus dracut module, which in turn depends on the systemd dracut module
In case it helps to test and review - alpine dracut package has some similar changes - https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/dracut/APKBUILD#L34
> dracut: move network-legacy into dracut-network package

- srcpkgs/ncspot/template
Using the termion as the backend instead of ncurses-rs which doesn't crosscompile. See https://github.com/void-linux/void-packages/pull/23415
> New package: ncspot-0.11.2

- common/travis/xpkgdiff.sh
xbps-query in this script needs a target architecture specified
- I tested the changes in this PR: 
- https://github.com/void-linux/void-packages/actions/runs/3940693091/jobs/6742126472#step:9:9
- https://github.com/Chocimier/void-packages-org/actions/runs/3943107347/jobs/6747551877#step:9:9
> common/travis/xpkgdiff.sh: fix on cross build

- srcpkgs/devilutionX/template
One of the upstream maintainers (glebm) suggested[^1] to use the `src` tarball instead of `src-fully-vendored`, which does not bundle libraries already available in the repository (SDL2, SDL2_image, libfmt, bzip2, libsodium, googletest) without the need to specify dedicated configure flags for them.
gettext is used for generating `libdevilutionX.mpq` but not required here because it is shipped in the tarball.
`-DFETCHCONTENT_FULLY_DISCONNECTED=ON` now is globally used in 48dabfa86779c1b32d40055ffc5747ba36332152 after the previous update for this package, so it is not needed here anymore.
[^1]: https://github.com/diasurgical/devilutionX/issues/5664#issuecomment-1383685675
> devilutionX: switch to the -src tarball; drop gettext

- srcpkgs/borg/template
- srcpkgs/borg/update
- srcpkgs/python3-pyfuse3/template
cc: @leahneukirchen 
Notes on the changes:
* use setuptools_scm for versioning instead of the manual hack
* switch to pyfuse3 from unmaintained llfuse as [recommended](https://github.com/borgbackup/borg/blob/1.2.3/setup.py#L77-L79)
* enable compiling the [hashindex extension](https://github.com/borgbackup/borg/blob/1.2.3/setup.py#L214)
* fix update file which was reporting NO VERSION
> borg: update to 1.2.3.

- srcpkgs/logisim-evolution/files/logisim-evolution
- srcpkgs/logisim-evolution/patches/desktop-entry.patch
- srcpkgs/logisim-evolution/template
> New package: logisim-evolution-3.8.0

- srcpkgs/dracut/patches/network.patch
- srcpkgs/dracut/template
only network-legacy is supported by dracut-network.
Sadly https://github.com/void-linux/void-packages/pull/41031 introduced a regression, so until this PR lands, the regression is in place. Apologies . 
Upstream Dracut discussion - https://github.com/dracutdevs/dracut/issues/1756
Gentoo discussion - https://github.com/gentoo/gentoo/pull/28777
CC @classabbyamp
> dracut: patch dracut-network

- srcpkgs/mame/patches/musl-netlist.patch
- srcpkgs/mame/patches/pulse-sound.patch
- srcpkgs/mame/template
~~I am unable to build this package properly due to it hanging my machine in process.~~
Tested it on x86_64-musl by using its embedded sega genesis emulator along with some ROMs randomly picked out from my collection. No errors to report here.
> mame: update to 0251.

- srcpkgs/libluv/template
- srcpkgs/neovim/template
- libluv: add buildoption to build with lua5.1
- neovim: add buildoption to build with lua5.1
> neovim: add buildoption to build with lua5.1

- srcpkgs/go-mtpfs/template
Uses fusermount from the 'fuse' package to mount MTP devices.
Closes #41731. 
> go-mtpfs: depend on fuse

- srcpkgs/libXcursor/template
It's required as per `Requires.private` in `/usr/lib/pkgconfig/xcursor.pc` and e.g. the following seen during a project CMake configure:
```
-- Checking for module 'xcursor'
--   Package 'xrender', required by 'xcursor', not found
CMake Error at /usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:607 (message):
A required package was not found
Call Stack (most recent call first):
/usr/share/cmake-3.25/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
CMakeLists.txt:283 (pkg_check_modules)
```
> libXcursor: make -devel subpackage depend on libXrender-devel

- srcpkgs/rmapi/template
> rmapi: update to 0.0.25

- srcpkgs/python3-tempora/template
> python3-tempora: update to 5.2.1.

- srcpkgs/python3-pygame/template
> python3-pygame: rebuild for newer sdl version

- srcpkgs/rsyslog/template
Historically, the test suite hasn't played well with running in CI.
```
============================================================================                                                                 
Testsuite summary for rsyslog 8.2212.0                                                                                                       
============================================================================                                                                 
```
> rsyslog: update to 8.2212.0.

- srcpkgs/webkit2gtk/template
> webkit2gtk: update to 2.38.3.

- Manual.md
as is indicated in the configure/gnu-configure build_style scripts:
https://github.com/void-linux/void-packages/blob/c33c4b5974e14bc9bacf1b37a846a4633ec7cf80/common/build-style/configure.sh#L2-L3
> Manual.md: note that gnu-configure build_style should be for autotools

- srcpkgs/redis/patches/use-system-jemalloc.patch
- srcpkgs/redis/template
The primary reason for updating this package is due to the following CVEs being found and fixed:
* [CVE-2022-35977](https://www.cvedetails.com/cve/CVE-2022-35977) (Integer overflow in the Redis SETRANGE and SORT/SORT_RO commands can drive Redis to OOM panic)
* [CVE-2023-22458](https://www.cvedetails.com/cve/CVE-2023-22458) (Integer overflow in the Redis HRANDFIELD and ZRANDMEMBER commands can lead to denial-of-service)
The rest is as follows:
* `jemalloc-devel` and `libatomic-devel` now are included conditionally.
* **antirez/redis** has been moved to **redis/redis88** (antirez stepped down in 2020 and handed over his work to his colleagues).
* `do_check` can be executed by setting `make_check_target` to `"test"`.
* `V=1` is retained in `make_build_args`; `MALLOC` is defined outside the …
> redis: update to 7.0.8.

- srcpkgs/libpcap/template
SUMMARY
pkg:libpcap host:x86_64 target:x86_64 cross:n result:OK
pkg:libpcap host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:libpcap host:i686 target:i686 cross:n result:OK
pkg:libpcap host:x86_64 target:aarch64-musl cross:y result:OK
pkg:libpcap host:x86_64 target:aarch64 cross:y result:OK
pkg:libpcap host:x86_64 target:armv7l-musl cross:y result:OK
pkg:libpcap host:x86_64 target:armv7l cross:y result:OK
pkg:libpcap host:x86_64 target:armv6l-musl cross:y result:OK
pkg:libpcap host:x86_64 target:armv6l cross:y result:OK
> libpcap: update to 1.10.3.

- srcpkgs/nestopia/template
Also:
- remove non-existent configure args
- add fltk-devel in makedepends.
> nestopia: update to 1.52.0.

- srcpkgs/nextcloud-client/template
> nextcloud-client: update to 3.6.6

- srcpkgs/python3-ijson/template
- srcpkgs/python3-phonenumbers/template
- srcpkgs/python3-simplejson/template
- srcpkgs/synapse/template
> synapse: update to 1.75.0.

- srcpkgs/python3-spotipy/template
Fixes [CVE-2023-23608](https://github.com/spotipy-dev/spotipy/security/advisories/GHSA-q764-g6fm-555v)
> python3-spotipy: update to 2.22.1.

- common/xbps-src/shutils/chroot.sh
- srcpkgs/perl-Net-OpenSSH/template
Some software reads the shell from /etc/passwd and expects it to
implement standard flags like -c etc.
> common/xbps-src/shutils/chroot.sh: pass arguments to xbps-shell

- srcpkgs/xcb-util/template
- I tested the changes in this PR: **YES**, x86_64-glibc
```
SUMMARY
pkg:xcb-util host:x86_64 target:x86_64 cross:n result:OK
pkg:xcb-util host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:xcb-util host:i686 target:i686 cross:n result:OK
pkg:xcb-util host:x86_64 target:aarch64-musl cross:y result:OK
pkg:xcb-util host:x86_64 target:aarch64 cross:y result:OK
pkg:xcb-util host:x86_64 target:armv7l-musl cross:y result:OK
pkg:xcb-util host:x86_64 target:armv7l cross:y result:OK
pkg:xcb-util host:x86_64 target:armv6l-musl cross:y result:OK
pkg:xcb-util host:x86_64 target:armv6l cross:y result:OK
```
> xcb-util: update to 0.4.1;adopt.

- srcpkgs/xcb-util-keysyms/template
```
SUMMARY
pkg:xcb-util-keysyms host:x86_64 target:x86_64 cross:n result:OK
pkg:xcb-util-keysyms host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:xcb-util-keysyms host:i686 target:i686 cross:n result:OK
pkg:xcb-util-keysyms host:x86_64 target:aarch64-musl cross:y result:OK
pkg:xcb-util-keysyms host:x86_64 target:aarch64 cross:y result:OK
pkg:xcb-util-keysyms host:x86_64 target:armv7l-musl cross:y result:OK
pkg:xcb-util-keysyms host:x86_64 target:armv7l cross:y result:OK
pkg:xcb-util-keysyms host:x86_64 target:armv6l-musl cross:y result:OK
pkg:xcb-util-keysyms host:x86_64 target:armv6l cross:y result:OK
```
> xcb-util-keysyms: update to 0.4.1;adopt.

- srcpkgs/xcb-util-renderutil/template
```
SUMMARY
pkg:xcb-util-renderutil host:x86_64 target:x86_64 cross:n result:OK
pkg:xcb-util-renderutil host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:xcb-util-renderutil host:i686 target:i686 cross:n result:OK
pkg:xcb-util-renderutil host:x86_64 target:aarch64-musl cross:y result:OK
pkg:xcb-util-renderutil host:x86_64 target:aarch64 cross:y result:OK
pkg:xcb-util-renderutil host:x86_64 target:armv7l-musl cross:y result:OK
pkg:xcb-util-renderutil host:x86_64 target:armv7l cross:y result:OK
pkg:xcb-util-renderutil host:x86_64 target:armv6l-musl cross:y result:OK
pkg:xcb-util-renderutil host:x86_64 target:armv6l cross:y result:OK
```
> xcb-util-renderutil: update to 0.3.10;adopt.

- srcpkgs/gopass-jsonapi/template
Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>
> gopass-jsonapi: update to 1.15.2

- srcpkgs/libblockdev/template
> libblockdev: update to 2.28.
