void-linux/void-packages

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.3.0.

- srcpkgs/cargo-outdated/template
> cargo-outdated: update to 0.11.2.

- srcpkgs/bird/template
Most notably, this contains a fix in the memory allocation for a bug that in some cases could lead to memory bloating. More information in https://gitlab.nic.cz/labs/bird/-/commit/973aa37e1e28a9c508fe09c008196f64cd3966fd
- aarch64-musl
- armv7l
- armv6l-musl
- x86_64-musl
> bird: update to 2.0.12

- srcpkgs/monitoring-plugins/template
- aarch64-musl
- armv7l
- armv6l-musl
- x86_64-musl
> monitoring-plugins: update to 2.3.2

- srcpkgs/python3-phonenumbers/template
- srcpkgs/synapse/template
- python3-phonenumbers: update to 8.13.5.
- synapse: update to 1.76.0.
> synapse: update to 1.76.0.

- srcpkgs/stunnel/template
required to build with openssl3 #37681
> stunnel: update to 5.67

- srcpkgs/sbsigntool/patches/f12484869c9590682ac3253d583bf59b890bb826.patch
- srcpkgs/sbsigntool/patches/openssl3.patch
- srcpkgs/sbsigntool/template
needed to build with openssl3 #37681
> sbsigntool: patch for openss3, add CFLAG

- srcpkgs/iwd/template
I have used the new version for 2+ days; didn't seem to have any issues with wifi.
> iwd: update to 2.2.

- srcpkgs/seahorse/patches/allow-building-with-gpg-2.4.patch
This patch is taken from upstream but is not in any released version yet
- I tested the changes in this PR: see #41948
> seahorse: allow building with GnuPG-2.4.x

- srcpkgs/gspell/template
> gspell: update to 1.12.0.

- srcpkgs/babl/template
> babl: update to 0.1.98.

- srcpkgs/lswt/template
`lswt` will list all toplevels advertised by a Wayland server using the `foreign-toplevel-management-unstable-v1` protocol extension.
Closes https://github.com/void-linux/void-packages/issues/42057
> New package: lswt-1.0.4

- srcpkgs/virtualbox-ose/template
> virtualbox-ose: update to 7.0.6.

- common/shlibs
- srcpkgs/budgie-control-center/template
- srcpkgs/cinnamon-control-center/template
- srcpkgs/gnome-control-center/template
- srcpkgs/gnome-settings-daemon/template
- srcpkgs/kcm-wacomtablet/template
- srcpkgs/libinput/template
- srcpkgs/libwacom/template
- srcpkgs/muffin/template
- srcpkgs/mutter/template
- I tested the changes in this PR: **briefly** (tested with my Wacom Intuos Pro)
I checked locally and the `kcm-wacomtablet` test failures are present without this PR's changes, so it's an unrelated issue.
> libwacom: update to 2.5.0, adopt. 

- srcpkgs/python3-shapely/template
- I tested the changes in this PR: **pending**
@karl-nilsson This update embodies a major refactor of the `shapely` package, but the API used by `python3-trimesh` and `Uranium` does not seem to have changed. However, I can't meaningfully test those packages.
> python3-shapely: update to 2.0.1.

- srcpkgs/squid/template
seems to build fine with openssl 3 #37681
> squid: update to 5.7

- srcpkgs/python3-paramiko/template
Related to https://github.com/void-linux/void-packages/pull/41672#discussion_r1096588023
> python3-paramiko: add missing dependency

- srcpkgs/fotoxx/template
> fotoxx: update to 23.1.

- srcpkgs/FreeRADIUS/template
this now builds with openssl3, unlike before #37681
> FreeRADIUS: update to 3.0.26

- srcpkgs/vlna/template
Program for adding non-breaking spaces after non-syllabic prepositions to TeX and other files.
https://petr.olsak.net/ftp/olsak/vlna/
> New package: vlna-1.5

- srcpkgs/python3-ansible-compat/template
- srcpkgs/python3-ansible-lint/template
- python3-ansible-compat: update to 3.0.1.
- python3-ansible-lint: update to 6.12.0.
> python3-ansible-lint: update to 6.12.0.

- srcpkgs/gscreenshot/template
I think scrot shouldn't be a hard dependencny here since it has full [wayland compatibility](https://github.com/thenaterhood/gscreenshot#for-full-functionality-on-wayland-the-recommended-packages-are)
> gscreenshot: update to 3.3.0.

- srcpkgs/fontconfig/template
> fontconfig: update to 2.14.2.

- srcpkgs/umurmur/patches/remove-crypto-mem-ctrl.patch
- srcpkgs/umurmur/template
Add a patch to build with openssl3 #37681 @Duncaen
> umurmur: patch for openssl3

- srcpkgs/cargo-bootstrap/template
- srcpkgs/rust-bootstrap/template
- rust-boostrap: hardcode platform triplets
- cargo-bootstrap: hardcode platform triplets
Fixes #42100 
> {rust,cargo}-bootstrap: hardcode platform triplets

- srcpkgs/rustup/template
> rustup: update to 1.25.2

- srcpkgs/man-pages/template
---
_notify maintainer, @Gottox_
> man-pages: update to 6.02.

- srcpkgs/vsv/template
`vsv` was rewritten from Bash to Rust so this template reflects that change - the user-facing CLI interface has not changed.
- I built this PR locally for my native architecture, (x86_64-2.36)
---
I built the package locally:
```
./xbps-src pkg vsv # exited successfully
./xbps-src -a armv6l pkg vsv # exited succkssefully
```
I tested to make sure the package looked sane (had the files i expected):
```
$ xbps-query --repository=hostdir/binpkgs -f vsv
/usr/bin/vsv
/usr/share/licenses/vsv/LICENSE
/usr/share/man/man8/vsv.8
```
I installed the package on my system to make sure 1. it ran 2. was a compiled binary and not a bash script.
```
$ sudo xbps-install --repository …
```
> vsv: update to 2.0.0

- srcpkgs/caddy/template
> caddy: update to 2.6.3.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.5.1

- Manual.md
In accordance with the [xlint](https://github.com/leahneukirchen/xtools/blob/v0.64/xlint#L392-L394) check.
> Manual.md: add AGPL & X11 to list of licenses which needs to be included

- srcpkgs/exiftool/template
> exiftool: update to 12.56.

- srcpkgs/epy/template
> epy: update to 2023.2.8.

- srcpkgs/swirc/template
> swirc: update to 3.4.0.

- common/shlibs
- srcpkgs/fplll/template
- srcpkgs/python3-fpylll/template
> fplll: update to 5.4.4 / python3-fpylll: update to 0.5.9.

- srcpkgs/gap/template
> gap: update to 4.12.2

- srcpkgs/rankwidth/template
It turns out that rankwidth only depends on igraph for the binary, but we don't ship the binary anyway (for sagemath we only need the library).
> rankwidth: remove dependency on igraph

- srcpkgs/perl-Regexp-Grammars/template
Another mostly no-op upstream change. Is ... is Perl dying?
> perl-Regexp-Grammars: update to 1.058.

- srcpkgs/perl-Moo/template
Another mostly no-op upstream release - removing the dependency on `Test::Fatal` in checks.
> perl-Moo: update to 2.005005.

- srcpkgs/loki/patches/go1.20.patch
- srcpkgs/loki/template
- I tested the changes in this PR: **NO** (I only tested the build and that it no longer fails to run when built with go 1.20)
@the-maldridge
> loki: update to 2.7.3, fix build with go 1.20

- common/shlibs
- srcpkgs/kismet/template
- srcpkgs/libwebsockets/template
- srcpkgs/mosquitto/template
- srcpkgs/ttyd/template
- I built this PR locally for my native architecture, (ARCH-LIBC) : **x86_64-musl**
- [] aarch64-musl
- [] armv7l
- [] armv6l-musl
> libwebsockets: update to 4.3.2, revbump or upgrade dependencies

- common/xbps-src/shutils/common.sh
- srcpkgs/openocd/template
It is not possible to use version other than currently in template.
Specifying pattern breaks build if dependency isn't in binary repo
already. That it worked when in repo was a coincidence.
Closes #37837
> xbps-src: explicitly disallow pattern on build deps

- srcpkgs/haproxy/template
- srcpkgs/haproxy/update
- aarch64-musl
HAProxy 2.6 is the latest LTS release with some nice improvements over the 2.4 series. Until another LTS hits, it's reasonable to lock the package to 2.6.x.
> haproxy: update to 2.6.9.

- srcpkgs/Bear/template
made sure `/usr/bin/intercept` is no longer installed.
> Bear: update to 3.1.0.

- srcpkgs/python3-phonenumbers/template
- srcpkgs/synapse/template
- python3-phonenumbers: update to 8.13.6.
- synapse: update to 1.77.0.
> synapse: update to 1.77.0.

- srcpkgs/python3-chroot/template
- srcpkgs/python3-snakeoil-devel
- srcpkgs/python3-snakeoil/template
- srcpkgs/removed-packages/template
snakeoil is a pure python package now, so no more c-extension/-devel-subpackage
> python3-snakeoil: update to 0.10.5.

- srcpkgs/python3-docstring-to-markdown/template
> python3-docstring-to-markdown: update to 0.11.

- srcpkgs/tracker-miners/patches/sqlite-seccomp.patch
- srcpkgs/tracker-miners/template
RE: sqlite issue, an issue has been made upstream: https://gitlab.gnome.org/GNOME/tracker-miners/-/issues/254
> tracker-miners: update to 3.4.3.

- srcpkgs/python3-xlib/template
> python3-xlib: update to 0.33.

- srcpkgs/pjproject/template
required to build with openssl3 #37681
> pjproject: update to 2.13

- srcpkgs/dracut/patches/isoscan-udev-trigger.patch
- srcpkgs/dracut/template
This fixes a bug in the live images when booted from grub as loopback (https://github.com/void-linux/void-mklive/issues/294).
https://github.com/dracutdevs/dracut/issues/2183
https://github.com/dracutdevs/dracut/pull/2196
> dracut: backport fix for live images on linux 5.19+

- srcpkgs/ubridge/template
ubridge is not compiled with LINUX_RAW enabled so it cannot use `add_nio_linux_raw` to connect to network interfaces.
When ubridge is compiled with LINUX_RAW it works.
Below is the error I get in GNS3 when I use the current package of ubridge:
```
2023-01-25 09:17:20 ERROR route.py:221 Node error detected: UbridgeError
File "/usr/lib/python3.11/site-packages/gns3server/compute/base_node.py", line 660, in _ubridge_send
await self._ubridge_hypervisor.send(command)
File "/usr/lib/python3.11/site-packages/gns3server/utils/asyncio/__init__.py", line 164, in wrapper
return await f(oself, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/gns3server/ubridge/ubridge_hypervisor.py", line 259, in send
raise …
```
> ubridge: rebuild with LINUX_RAW

- srcpkgs/python3-typing_extensions/template
> python3-typing_extensions: update to 4.4.0.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.6.0.

- srcpkgs/kicad-doc/template
- srcpkgs/kicad-footprints/template
- srcpkgs/kicad-library/template
- srcpkgs/kicad-packages3D/template
- srcpkgs/kicad-symbols/template
- srcpkgs/kicad-templates/template
- srcpkgs/kicad/patches/disable-warnings.patch
- srcpkgs/kicad/template
Opened up some projects and exported gerbers without issues. 
I am seeing a lot of warnings in the build, mostly coming from the comes-with-kicad pybind11. Since there is already a patch for the Warnings.cmake file, this could be silenced further, but i am not sure if this wanted. 
New dependency on unixodbc, i hope i put it in the right places.
> kicad: update to 7.0.0

- srcpkgs/xkeyboard-config/template
```
SUMMARY
pkg               host         target  cross  result
xkeyboard-config  x86_64       x86_64  n      OK
xkeyboard-config  x86_64-musl  armv6l  y      OK
```
> xkeyboard-config: update to 2.38.

- srcpkgs/xca/patches/openssl3.patch
- srcpkgs/xca/template
update and patch to build with openssl3 #37681 @dutsky
> xca: update to 2.4.0, patch for openssl3

- srcpkgs/python3-pikepdf/template
> python3-pikepdf: update to 7.0.0.

- srcpkgs/netpgp/template
> netpgp: add cflag to build with openssl3

- srcpkgs/caddy/template
> caddy: update to 2.6.4.

- srcpkgs/python3-poetry-core/template
Only real blocker was synapse, which has been resolved [upstream](https://github.com/matrix-org/synapse/commit/64a631879c8be583efe47ca48e39f6cdf6115645) and merged [here](https://github.com/void-linux/void-packages/commit/404663e7968ec3e7c4ce67771639aebac0cf822d).
> python3-poetry-core: update to 1.5.0.

- srcpkgs/ipmiutil/template
Update so it builds with openssl3 #37681 @Vaelatern
> ipmiutil: update to 3.1.8

- srcpkgs/Clipboard/template
> New package: Clipboard-0.3.2

- srcpkgs/qtcreator/patches/6.0.2--backtrace.patch
- srcpkgs/qtcreator/patches/musl-no-malloc_trim.patch
- srcpkgs/qtcreator/template
- I built this PR locally for my native architecture, (x86-64*)
- aarch64-musl
- armv6l
> qtcreator: update to 9.0.1.

- srcpkgs/d2/template
\cc @Vaelatern I removed the `go_package` variable since it defaults to `go_import_path` anyway (according to `Manual.md`)
> d2: update to 0.2.0.

- srcpkgs/python3-pytest/template
- srcpkgs/tox/template
Tox was packaged for do_check, but it runs in virtualenv, thus not useful.
Maybe it could be made work with [sitepackages](https://tox.wiki/en/latest/config.html#sitepackages).
> tox: update to 3.28.0, orphan.

- srcpkgs/obs/template
Did a build and a quick check to see that it launched.  v29 pulls in libva, though this can likely be disabled if we really want.
> obs: update to 29.0.2

- srcpkgs/go/template
- I tested the changes in this PR: **YES** (compiled `syncthing`)
Go 1.20.1 includes a bunch of security fixes, so this should probably be merged
as soon as possible.
@the-maldridge
> go: update to 1.20.1.

- srcpkgs/libgit2/template
Fixes build cycle with cairo -> mesa -> rust -> libgit -> git -> gir -> cairo. git was added to hostmakedepends when the distfiles were obtained using git clone.
https://github.com/void-linux/void-packages/blob/237631485073e4883653b6a18e6fb141f1aa01d7/srcpkgs/libgit2/template
Fixes: https://github.com/void-linux/void-packages/issues/42378
> libgit2: remove git from hostmakedepends

- srcpkgs/sioyek/template
doesn't seem to be needed, as mupdf only available as a statically linkable library
cc maintainer @dkwo
> sioyek: don't depend on mupdf, fix cross

- srcpkgs/obs-plugin-browser-bin/template
I'm not sure this is a good idea.  It works, but its doing the same kind of stuff we do to make the google chrome package work.  It should probably work then as a result, but I suspect its pretty fragile.  I stuck GPL-2.0-ONLY on it which is the correct license for the source, but since this includes a full embedded chromium I suspect that isn't quite right.  Advice is appreciated.
> New package: obs-plugin-browser-bin-29.0.2

- srcpkgs/Signal-Desktop/template
- I built this PR locally for my native architecture, x86_64 glibc
> Signal-Desktop: update to 6.7.0.

- srcpkgs/lagrange/template
> lagrange: update to 1.15.2.

- srcpkgs/docker-buildx/template
- I built this PR locally for my native architecture, glibc, x86_64
> docker-buildx: update to 0.10.3.

- srcpkgs/python3-ansible-lint/template
There was a bug in a new feature that was introduced upstream, which I fixed and submitted upstream. Is it okay to include stuff like this downstream?
> python3-ansible-lint: update to 6.13.0.

- srcpkgs/haproxy/files/haproxy.cfg
- srcpkgs/haproxy/template
I missed updating the default configuration file when a configuration verb was retired in 2.6.x.
> haproxy: fix default configuration

- srcpkgs/spotify-tui/patches/openssl3.patch
- srcpkgs/spotify-tui/template
see https://github.com/Rigellute/spotify-tui/issues/1025
#37681 @abenson
> spotify-tui: fix build, patch for openssl3

- srcpkgs/exiv2/template
> exiv2: update to 0.27.6.

- srcpkgs/exiftool/template
> exiftool: update to 12.57.

- srcpkgs/libtool/template
@dkwo Can you test this? (whenever you are available ofc)
> libtool: fix include paths when cross compiling

- srcpkgs/safeeyes/template
@leahneukirchen is there a reason for borg to have pip in hostmakedepends?
> safeeyes: remove pip from build depends

- srcpkgs/cryptsetup/template
- I tested the changes in this PR: **YES** (booted into my FDE installation)
I'd appreciate anybody testing this PR.
ping @daniel-eys
> cryptsetup: update to 2.6.1.

- srcpkgs/kdevelop-pg-qt/template
- srcpkgs/kdevelop-php/template
- srcpkgs/kdevelop-python/patches/musl-headers-for-python3-devel.patch
- srcpkgs/kdevelop-python/template
- srcpkgs/kdevelop/template
- I built this PR locally for my native architecture: **x86_64-musl**
- aarch64-musl
- armv7l
- armv6l-musl
> kdevelop: update to 22.12.2, update kdevelop-pg-qt and re-enable kdevelop-python

- srcpkgs/libnitrokey/template
> libnitrokey: update to 3.8.

- common/build-style/qmake.sh
There's no `qt6-doc` package (compared to `qt5-doc`) or `qt6-examples` subpackage (compared to `qt5-examples`) but those could just be ignored I suppose
~~There's a big problem: cross-compiling any Qt6 `qmake` package quickly results in something like `make: *** No rule to make target '/usr/libexec/moc', needed by '.moc/main.moc'.  Stop.`~~
~~Native builds still work as expected however already. For a testing tree see [my `qt6-qmake-demo` tree](https://github.com/JamiKettunen/void-packages/commits/qt6-qmake-demo) and try e.g. `./xbps-src pkg qt6-qpa-hwcomposer-plugin` vs `./xbps-src pkg -a aarch64 qt6-qpa-hwcomposer-plugin` on a glibc masterdir.~~
~~As per https://forum.qt.io/topic/137300/qtpaths-return-incorrect-path `ln -s /usr/lib/qt6/libexec/moc /usr/libexec/moc` would probably work …
> build-style/qmake: add support for Qt6

- srcpkgs/clamav/template
This release contains very important fixes for some critical CVEs.
Here is the information: https://blog.clamav.net/
We should merge this PR ASAP.
> clamav: update to 0.103.8.

- srcpkgs/taplo/template
I've enabled a feature that should remove the arch restriction. If someone with ppc equipment could test, I'd be grateful.
> taplo: update to 0.8.0

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.8.0.

- srcpkgs/vdirsyncer/template
> vdirsyncer: update to 0.19.1

- srcpkgs/epson-inkjet-printer-escpr/template
Maintainer hasn't committed to this package since they adopted it in January 2020 (e7d4687296a973a9290db2af228b9b874d175e7b).
ping @Bridouz
> epson-inkjet-printer-escpr: update to 1.7.25, adopt.

- srcpkgs/chezmoi/template
> chezmoi: update to 2.31.1.

- srcpkgs/puzzles/template
> puzzles: update to 20230303.c0f715f.

- srcpkgs/python3-frozendict/template
This library does not build the C extension by default now so the workaround is unnecessary. I haven't removed the `makedepends` since a c extension for py3.11 is WIP upstream.
> python3-frozendict: update to 2.3.5.

- srcpkgs/libnfnetlink/template
```
SUMMARY
pkg:libnfnetlink host:x86_64 target:x86_64 cross:n result:OK
pkg:libnfnetlink host:x86_64-musl target:x86_64-musl cross:n result:OK
pkg:libnfnetlink host:i686 target:i686 cross:n result:OK
pkg:libnfnetlink host:x86_64 target:aarch64-musl cross:y result:OK
pkg:libnfnetlink host:x86_64 target:aarch64 cross:y result:OK
pkg:libnfnetlink host:x86_64 target:armv7l-musl cross:y result:OK
pkg:libnfnetlink host:x86_64 target:armv7l cross:y result:OK
pkg:libnfnetlink host:x86_64 target:armv6l-musl cross:y result:OK
pkg:libnfnetlink host:x86_64 target:armv6l cross:y result:OK
```
> libnfnetlink: update to 1.0.2.

- srcpkgs/miniserve/template
> miniserve: update to 0.23.0

- srcpkgs/fotoxx/template
> fotoxx: update to 23.2.

- srcpkgs/wayclip/template
<del>but it's broken. `waycopy` works, `waypaste` does not</del> problem was resolved in 0.4.1.
> wayclip: update to 0.4.1.

- srcpkgs/python3-ipython/template
- srcpkgs/python3-prompt_toolkit/template
- srcpkgs/python3-traitlets/template
Also updates prompt_toolkit and traitlets (the former is necessary: resolves a test failure in the new ipython)
I'm running sagemath with this update, everything seems ok. A couple doctests fail in sagemath due to a new warning, harmless ( see https://github.com/sagemath/sage/pull/35235).
> python3-ipython: update to 8.11.0.

- srcpkgs/gsoap/patches/libtool.patch
- srcpkgs/gsoap/patches/musl.patch
- srcpkgs/gsoap/template
The current version has no available tarball, so I'm unable to test it with openssl3.
@Gottox @motorto 
> gsoap: update to 2.8.124

- srcpkgs/iso-codes/template
> iso-codes: update to 4.13.0.

- srcpkgs/qt5-fsarchiver/patches/attr.h.patch
- srcpkgs/qt5-fsarchiver/patches/cross.patch
- srcpkgs/qt5-fsarchiver/patches/fix-install-target.patch
- srcpkgs/qt5-fsarchiver/patches/musl.patch
- srcpkgs/qt5-fsarchiver/template
> qt5-fsarchiver: update to 1.8.6pl1.

- common/hooks/do-extract/00-distfiles.sh
bsdtar is built with support for it, so this shouldn't cause issues
> common/hooks/do-extract/00-distfiles.sh: support .tar.zst

- srcpkgs/android-tools/template
> android-tools: update to 34.0.0.

- srcpkgs/composer8.0/template
- srcpkgs/composer8.1/template
- srcpkgs/php8.0-igbinary/template
- srcpkgs/php8.0/template
- srcpkgs/php8.1-igbinary/template
- srcpkgs/php8.1/template
- srcpkgs/xdebug8.0/template
- srcpkgs/xdebug8.1/template
- php8.0: update to 8.0.28.
- php8.1: update to 8.1.16.
- php8.0-igbinary: update to 3.2.14.
- php8.1-igbinary: update to 3.2.14.
- xdebug8.0: update to 3.2.0.
- xdebug8.1: update to 3.2.0.
- composer8.0: update to 2.5.4.
- composer8.1: update to 2.5.4.
> PHP 8.[01] updates

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.9.0.

- srcpkgs/libbraiding/template
I tested this with sagemath (full doctest suite).
> libbraiding: update to 1.2.

- srcpkgs/nextcloud-client/patches/revert-mandatory-webengine.patch
- srcpkgs/nextcloud-client/template
- I built this PR locally for my native architecture, (x86_64-lib)
- i686-libc
Also:
- Add `karchive` as dependency: https://github.com/nextcloud/desktop/pull/4768
- Add patch to revert mandatory WebEngine dependency: https://github.com/nextcloud/desktop/pull/4875
> nextcloud-client: update to 3.7.3

- srcpkgs/python3-markdown-it/template
python3-rich-13.3.2 needs this version of markdown-it-py
https://github.com/Textualize/rich/blob/v13.3.2/pyproject.toml#L33
> python3-markdown-it: update to 2.2.0 [unbreak python3-rich]

- srcpkgs/swirc/template
Today I released Swirc 3.4.3 which comes with code improvements and new translations.
No new bugs were fixed/found.
> swirc: update to 3.4.3.

- srcpkgs/zellij/template
> zellij: update to 0.35.2

- srcpkgs/gnumeric/template
> gnumeric: remove useless vsed.

- srcpkgs/redis/template
It's not a good idea to have /etc/redis/redis.conf world-readable since it may contain sensitive informations like passwords.
> redis: restrict /etc/redis permissions

- srcpkgs/hostapd/files/config
- srcpkgs/hostapd/template
I just sanity-checked by running locally, these are the salient parts of my `hostapd.conf`:
```
driver=nl80211
auth_algs=1
wpa=2
extended_key_id=1
wpa_key_mgmt=SAE
wpa_pairwise=CCMP
ieee80211w=2
```
> hostapd: support WPA3 (CONFIG_SAE flag)

- srcpkgs/rpi-usbboot/patches/0001-Use-PREFIX-and-DESTDIR-in-Makefile.patch
- srcpkgs/rpi-usbboot/template
> New package: rpi-usbboot-20221104.153421

- srcpkgs/glab/template
> glab: update to 1.26.0.

- srcpkgs/kicad-doc/template
- srcpkgs/kicad-footprints/template
- srcpkgs/kicad-library/template
- srcpkgs/kicad-packages3D/template
- srcpkgs/kicad-symbols/template
- srcpkgs/kicad-templates/template
- srcpkgs/kicad/template
Just a version bump following the 7.0.1 bug-fix release from last week. Opened and exported some projects, works just fine afaics.
> kicad: update to 7.0.1

- srcpkgs/opustags/template
> opustags: update to 1.8.0.

- common/travis/check-install.sh
- srcpkgs/cross-vpkg-dummy/template
this should fix issues with openjdk11-jre in makedepends and "verify repository state" CI on cross:
```
openjdk11-jre-11.0.12+7_4: broken, unresolvable shlib `libthread_db.so.1'
Transaction aborted due to unresolved shlibs.
```
before:
```
[DEBUG] xbps_transaction_check_shlibs: checking for `libthread_db.so.1': not found
```
after:
```
[DEBUG] xbps_transaction_check_shlibs: checking for `libthread_db.so.1': provided by `cross-vpkg-dummy-0.39_4'
```
> cross-vpkg-dummy: provide libthread_db.so.1 on glibc

- srcpkgs/liblangtag/template
> liblangtag: update to 0.6.4.

- srcpkgs/mandrel/template
- srcpkgs/openjdk11/template
- srcpkgs/openjdk11/update
- srcpkgs/openjdk17-static-libs
- srcpkgs/openjdk17/template
- openjdk11: remove useless nostrep from -static-libs
- openjdk17: static libs subpackage
> openjdk17: static-libs subpackage

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.10.0.

- srcpkgs/exiftool/template
> exiftool: update to 12.58.

- srcpkgs/fatsort/template
> fatsort: update to 1.6.5.640.

- srcpkgs/wpa_supplicant/files/config
- srcpkgs/wpa_supplicant/template
This allows to use an external file to store passwords.
> wpa_supplicant: add CONFIG_EXT_PASSWORD_FILE=y

- srcpkgs/gitea/template
Tagging the maintainer @fosslinux
It's just a version bump
- x86_64-musl
> gitea: update to 1.18.5

- srcpkgs/python3-jq/template
> python3-jq: update to 1.4.1

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.10.1.

- srcpkgs/imv/template
`WAYLAND_DISPLAY= imv-wayland` and `DISPLAY= imv-x11` segfault because assertions are used to check for errors in these cases and we build with `-Db_ndebug=true` by default.
By looking at the commit history, I see that similar problems occurred in the past for other meson projects.
Meson, unlike cmake, doesn't define NDEBUG by default for release build types, so it's possible that many meson projects rely on assertions being always enabled. I don't believe it's safe to have `-Db_ndebug=true` in our build style.
> imv: configure with -Db_ndebug=false

- srcpkgs/httpry/template
> httpry: Remove obsolete vsed

- srcpkgs/fltk/template
> fltk: Remove obsolete vsed

- srcpkgs/python3-importlib_metadata/template
> python3-importlib_metadata: update to 6.1.0.

- srcpkgs/kmymoney/template
> kmymoney: Fix ineffective vsed

- srcpkgs/fcitx/template
> fcitx: Remove obsolete vsed

- srcpkgs/eggdrop/template
Running the binary both before and after this change gives the following error:
$ eggdrop
LANG: No lang files found for section core.
Eggdrop v1.9.4 (C) 1997 Robey Pointer (C) 2010-2022 Eggheads
--- Loading eggdrop v1.9.4 (Sat Mar 18 2023)
* MSG534
I don't use *eggdrop* so I'm not sure how to test this further. Happy to take advice on this and retest if needed.
> eggdrop: Remove useless vsed

- srcpkgs/autofs/template
> autofs: Remove obsolete vseds

- srcpkgs/wl-mirror/template
Add 'pkg-config' as host dependency. See release notes
https://github.com/Ferdi265/wl-mirror/releases/tag/v0.13.1
for more detail.
> wl-mirror: update to 0.13.1.

- srcpkgs/netpbm/template
> netpbm: Remove ineffective vsed

- srcpkgs/mk-configure/template
> mk-configure: Remove ineffective vsed

- srcpkgs/ldns/template
> ldns: Removes ineffective vsed

- srcpkgs/kdeconnect/template
kdeconnect appears to depend on breeze-icons for it's icons
without breeze-icons installed:
with breeze-icons installed:
> kdeconnect: add breeze-icons & kpeoplevcard to depends

- srcpkgs/riff/template
This version has the fix for the [previous version's](https://github.com/void-linux/void-packages/pull/42868) race condition
Closes #42868
> riff: update to 2.23.2.

- srcpkgs/discord-ptb/template
Also add missing dlopen'd library (#42800).
> discord-ptb: update to 0.0.41.

- srcpkgs/ffuf/template
---
- **Briefly** means I ran `$ ffuf` and it didn't produce any stderr
- Fixes tracked package `ffuf` in #39072
> ffuf: updated checksum and fixed import path

- srcpkgs/libpeas/template
> libpeas: update to 1.36.0.

- srcpkgs/gnome-console/template
- I tested the changes in this PR:  **briefly**
Depends on: https://github.com/void-linux/void-packages/pull/42828
> gnome-console: update to 44.0.

- srcpkgs/python3-gobject/template
Built and used Solaar from this PR. Also built meld & xapps which went fine.
> python3-gobject: update to 3.44.0.

- srcpkgs/passt/template
- srcpkgs/passt/update
[podman-v4.4.0](https://github.com/containers/podman/releases/tag/v4.4.0) added support for [pasta](https://passt.top/passt/about/) with <https://github.com/containers/podman/pull/16141>. It's interesting for proper IPv6 forwarding with rootless containers.
There is an [open issue](https://bugs.passt.top/show_bug.cgi?id=4) for `musl` support.
> New package: passt-2023.03.09.7c7625d

- srcpkgs/xdg-desktop-portal-gnome/template
> xdg-desktop-portal-gnome: update to 44.0.

- srcpkgs/gnome-terminal/template
> gnome-terminal: update to 3.48.0.

- srcpkgs/giac/template
- I tested the changes in this PR: **briefly** (tested with sagemath)
> giac: update to 1.9.0.41.

- srcpkgs/openbox/patches/d41128e5a1002af41c976c8860f8299cfcd3cd72.patch
- srcpkgs/openbox/template
Fix crashes reported on other distros when using malloc instead of glib's custom allocator. Try as I might, I can't reproduce the crashes on Void, but this reportedly fixes the issue on other distros.
> openbox: fix use after free

- srcpkgs/xfce4-session/patches/911f5b8101dec6a6d28f7601768588a2f0fd4aaf.patch
- srcpkgs/xfce4-session/patches/cff23d0fadd502f7db9230f9ebbc02c00853f825.patch
- srcpkgs/xfce4-session/template
Fix crashes reported on other distros when using malloc instead of glib's custom allocator. Try as I might, I can't reproduce the crashes on Void, but this reportedly fixes the issue on other distros.
> xfce4-session: fix use after free

- srcpkgs/gnome-remote-desktop/template
Depends on: https://github.com/void-linux/void-packages/pull/43002
> gnome-remote-desktop: update to 44.0.

- srcpkgs/mdcat/template
mdcat has different behaviour if invoked as mdless. other distros package this symlink too.
cc maintainer @cinerea0
> mdcat: add mdless symlink

- srcpkgs/kirigami-addons/template
- I built this PR locally for my native architecture, (X86_64)
> kirigami-addons: update to 0.7.2

- srcpkgs/vips/template
Removed `desc_option_gir` which I added last time as it's already covered by [options.description](https://github.com/void-linux/void-packages/blob/master/common/options.description)
> vips: update to 8.14.2.

- srcpkgs/libass/template
- I tested the changes in this PR: **briefly** (tested with mpv)
> libass: update to 0.17.1, adopt.

- srcpkgs/faketime/template
---
By *briefly*, I mean the checks for `rsyslog`, the only package that depends on this, continue to pass with this update.
> faketime: update to 0.9.10

- srcpkgs/cargo-auditable-bootstrap/template
- srcpkgs/cargo-auditable/template
- cargo-auditable-bootstrap: update to 0.6.1
- cargo-auditable: update to 0.6.1
> cargo-auditable: update to 0.6.1

- srcpkgs/kops/template
- I built this PR locally for my native architecture, (amd64-glibc)
> kops: update to 1.26.2

- srcpkgs/primecount/template
This is a very minor update to fix the following:
```
$ python -c 'from primecountpy.primecount import prime_pi ; print(prime_pi(-1))'
File "<string>", line 1, in <module>
File "primecountpy/primecount.pyx", line 25, in primecountpy.primecount.prime_pi
File "primecountpy/primecount.pyx", line 47, in primecountpy.primecount.prime_pi
cysignals.signals.SignalError: Bus error
```
After the update
```
$ python -c 'from primecountpy.primecount import prime_pi ; print(prime_pi(-1))'
0
```
We can now sleep in the comfort that such an important calculation can be done in void linux with success.
As expected, other values of `π(x)` are still ok and quick:
```
$ python -c 'from primecountpy.primecount import prime_pi ; …
```
> primecount: update to 7.8.

- srcpkgs/prometheus/files/prometheus/run
- srcpkgs/prometheus/template
update run script to properly increase max open files limit
> prometheus: update to 2.43.0.

- srcpkgs/python3-dnsrecon/template
Doesn't work without setuptools.
```
File "/bin/dnsrecon", line 33, in <module>
sys.exit(load_entry_point('dnsrecon==1.1.3', 'console_scripts', 'dnsrecon')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/bin/dnsrecon", line 25, in importlib_load_entry_point
return next(matches).load()
^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
module = import_module(match.group('module'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen …
```
> python3-dnsrecon: add missing python3-setuptools dependency

- srcpkgs/acme.sh/template
Tagging the maintainer @Wesley-Chan 
- x86_64-musl
> acme.sh: update to 3.0.5, adopt

- srcpkgs/android-udev-rules/template
Maintainer did not touch package since June 2020, so adopting it.
> android-udev-rules: update to 20230303, adopt.

- srcpkgs/gscan2pdf/patches/tesseract.patch
- srcpkgs/gscan2pdf/template
> gscan2pdf: corrected a patch to make tesseract available

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.12.0

- srcpkgs/soju/template
- (plan on deploying this soon, will test then)
cc maintainer: @flupe
> soju: update to 0.6.0.

- srcpkgs/python3-ansible-lint/template
> python3-ansible-lint: update to 6.14.3.

- srcpkgs/gdk-pixbuf/patches/largejpeg-oom-test.patch
- srcpkgs/gdk-pixbuf/template
- srcpkgs/libjpeg-turbo/template
> gdk-pixbuf: update to 2.42.10.

- srcpkgs/openblas/template
Just staging here until the LLVM builds settle down...
Version 0.3.22 apparently breaks Octave:
https://github.com/xianyi/OpenBLAS/issues/3976
This reverts commit 0ef7a0ec7c6b126d63cfb9f485786f0ef772b516.
> Revert "openblas: update to 0.3.22."

- srcpkgs/Komikku/template
- srcpkgs/python3-emoji/template
- srcpkgs/python3-piexif/patches/pillow-7.2.patch
- srcpkgs/python3-piexif/template
> Komikku: update to 1.17.0

- srcpkgs/libpanel/template
> libpanel: update to 1.2.0.

- srcpkgs/helix/template
> helix: update to 23.03

- srcpkgs/xorg-server-xwayland/template
Fixed https://github.com/void-linux/void-packages/issues/43174
> xorg-server-xwayland: update to 23.1.1

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2023.03.27.

- srcpkgs/python3-resolvelib/template
Going from 0.9.0 to 1.0.1 sounds a bit scary, but the changelog is super short and I've tried a few packages that rely on it which still work as expected, so I'm not too worried about it.
> python3-resolvelib: update to 1.0.1.

- srcpkgs/cargo-deny/template
> cargo-deny: update to 0.13.7.

- common/build-style/cargo.sh
- common/environment/build-style/cargo.sh
> build-style/cargo: use env var to select sparse index mode

- srcpkgs/xorg-server/template
Fixed https://github.com/void-linux/void-packages/issues/43174
> xorg-server: update to 21.1.8

- srcpkgs/bottom/template
When building locally, this failed due to dependency resolution problems, which are caused by our inconsistent use of the `--locked` and `--offline` flags for cargo. Once we've got #43233 in, this will build just fine though.
EDIT: heh, I'm confused. Now this built just fine in CI without `--locked`, maybe this was just a random local failure.
> bottom: update to 0.8.0.

- srcpkgs/vaultwarden-web/template
- srcpkgs/vaultwarden/template
- vaultwarden: update to 1.28.1.
- vaultwarden-web: update to 2023.3.0b.
> vaultwarden: update to 1.28.1.

- srcpkgs/puzzles/template
> puzzles: update to 20230404.2499eb4.

- srcpkgs/babashka/template
- srcpkgs/jet/template
@leahneukirchen I updated mandrel [earlier](https://github.com/void-linux/void-packages/commit/9781d3805e4a0fb3eafcad404ca604a66697474a) and these are the packages that needed to be rebuilt. I had to disable babashka's tests temporarily till someone updates openjdk17 in the repos due to the linked issue in comment.
> mandrel: update revdeps

- common/build-style/go.sh
makes sure the go mod cache is not read only and ./xbps-src zap can properly remove it
If someone wants to test this, try to build go-ipfs which fails and then zap the masterdir. Without this change, you will get a lot of error messages about not removing a read only file.
cc @the-maldridge
> common/build-style/go.sh: use -modcacherw

- srcpkgs/git-brws/template
> git-brws: fix build on Rust 1.64+

- srcpkgs/river/template
- srcpkgs/waylock/template
- I tested the changes in this PR: yes. been running them for months, built with zig-static
> update river and waylock

- common/build-helper/rust.sh
- srcpkgs/nushell/patches/0001-use-system-libraries.patch
- srcpkgs/nushell/template
- common/build-helper/rust.sh: dynamic linking to zstd
- nushell: update to 0.78.0.
> nushell: update to 0.78.0.

- srcpkgs/rustypaste-cli/template
- srcpkgs/rustypaste/files/rustypaste/run
- srcpkgs/rustypaste/template
> New packages: rustypaste-0.8.4, rustypaste-cli-0.3.0

- srcpkgs/exiftool/template
> exiftool: update to 12.60.

- srcpkgs/fotoxx/template
> fotoxx: update to 23.32.

- srcpkgs/python3-typing_extensions/template
> python3-typing_extensions: update to 4.5.0.

- srcpkgs/libinput/template
> libinput: update to 1.23.0.

- srcpkgs/tinyramfs/files/config
- srcpkgs/tinyramfs/files/kernel-hook-postinst
- srcpkgs/tinyramfs/files/kernel-hook-postrm
- srcpkgs/tinyramfs/template
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): yes
one has to edit the config file; I did not add eudev, cryptsetup, etc to depends, as this can vary.
> new package: tinyramfs

- common/build-helper/rust.sh
- srcpkgs/comrak/template
> comrak: update to 0.18.0.

- srcpkgs/epiphany/template
Depends on: https://github.com/void-linux/void-packages/pull/41698
> epiphany: update to 44.0.

- srcpkgs/aqemu/patches/widgets.patch
- srcpkgs/aqemu/template
A repeated error in a UI layout file ceased to be accepted in recent-ish QT versions.
Closes #39101
> aqemu: fix segfault

- srcpkgs/lagrange/template
> lagrange: update to 1.15.8.

- srcpkgs/python3-importlib_metadata/template
> python3-importlib_metadata: update to 6.3.0.

- srcpkgs/libgcrypt/template
> libgcrypt: update to 1.10.2.

- common/travis/check-install.sh
The CI has `base-chroot` installed, but sometimes this script would try to install `base-system,` causing conflicts. This PR fixes that issue by using a brand-new rootdir.
How should I test this?
> common/travis: make check-install use new rootdir.

- srcpkgs/ReText/template
Fixes #43323.
There's ReText 8.0.0, but it migrates to Qt 6 and I don't have the time to do the migration at the moment.
> ReText: update to 7.2.3.

- srcpkgs/evolution/template
The package 'evolution-ews' cannot neither be installed nor updated because cannot resolve a shared lib.
In the [evolution: update to 3.48.0](https://github.com/void-linux/void-packages/commit/e8be9699344508280a43193b9a7e20b2632e4aae) an evolution lib was included in common/shlibs but is not exposed in the package template, thus 'evolution-ews' cannot find the package that provides it.
> evolution: fix expose shared lib

- srcpkgs/taplo/patches/0001-handle-lsp-shutdown-request.patch
- srcpkgs/taplo/template
The language server hangs till timeout while quitting Helix with a `toml` buffer. This patch was sent upstream by Helix primary author.
\cc @cinerea0
> taplo: Handle LSP shutdown request

- srcpkgs/fzf/template
- aarch64
- i686
- x86_64-musl
> fzf: update to 0.39.0.

- srcpkgs/tpm2-totp/template
Avoids using pandoc or doxygen altogether
> tpm2-totp: switch to prebuilt source destfile

- srcpkgs/python3-ldap/template
Build was failing after revbump in #41948 
- remove unnecessary sed expression
- simplify distfile url
- I tested the changes in this PR: test suite passes, I don't use this package directly
- aarch64-musl
- armv7l
- armv6l-musl
- i686
> python3-ldap: update to 3.4.3

- srcpkgs/electron19/patches/python-3.11.patch
- srcpkgs/electron19/patches/sql-relax-constraints-on-VirtualCursor-layout.patch
[ci skip]
- I tested the changes in this PR: **NO** (but yes? because it's for the build)
While checking ffmpeg5/6 changes I was having trouble building `electron19`. There have been a few big changes lately and the last build fix was months ago, so I'm not sure what changed. (Looks like a lot of active patching or something in the template?)
~~Going to verify non-ffmpeg change build tonight if I remember.~~
part https://github.com/void-linux/void-packages/issues/39083 (not on list)
question: revbump?
> electron19: fix build

- common/xbps-src/shutils/build_dependencies.sh
Messages like "building [rust] for <platform>" could lead to mild panic as they might be read as "building [large toolchain] on your laptop".
Simply adding "with" before the style/helpers should solve that.
It works for build_style, build_helper, both, and none.
```
=> ircdog-0.4.0_2: building with [go] for x86_64...
=> firefox-111.0.1_1: building with [rust] for x86_64...
=> riff-2.23.2_1: building with [cargo] [rust] for x86_64...
=> discord-0.0.26_1: building for x86_64...
```
> shutils/build_dependencies.sh: print "with" before build style/helper names

- srcpkgs/bandwhich/patches/0001-upgrade-resolv-conf-pnet-and-ipnetwork.patch
- srcpkgs/bandwhich/template
I've upgraded the dependencies in here, which fixes the compile error for 1.64 and also a runtime problem (https://github.com/imsnif/bandwhich/issues/263). The changes are also in a PR upstream (https://github.com/imsnif/bandwhich/pull/265), but I currently wouldn't assume that upstream will merge this, as the project is largely unmaintained.
> bandwhich: fix build on Rust 1.64+

- srcpkgs/servy/template
I'm a bit torn on this one: The upstream git repo is gone, so we'd have to pull this from crates.io?
> servy: update to 1.0.1.

- srcpkgs/python3-yamllint/template
> python3-yamllint: update to 1.30.0.

- srcpkgs/runit/patches/chpst-pwd.patch
- srcpkgs/runit/template
from https://github.com/void-linux/runit/commit/2b8000f1ebd07fd68ee0e3c32737d97bcd1687fb
> runit: add chpst -C patch

- srcpkgs/linux6.2/patches/v3-wireless-mt76-mt7921-Fix-use-after-free-in-fw-features-query.diff
- srcpkgs/linux6.2/template
+ backport of patch for mt62 wireless driver - I had recurring issues with this free-after-use error that led to a crash in the network driver
> linux6.2: update to 6.2.10

- srcpkgs/aide/template
~~~
pkg      host         target        cross  result
aide     x86_64       x86_64        n      OK
aide     x86_64-musl  x86_64-musl   n      OK
aide     i686         i686          n      OK
aide     x86_64       aarch64-musl  y      OK
aide     x86_64       aarch64       y      OK
aide     x86_64       armv7l-musl   y      OK
aide     x86_64       armv7l        y      OK
aide     x86_64       armv6l-musl   y      OK
aide     x86_64       armv6l        y      OK
~~~
> Aide 0.18.2

- srcpkgs/newsboat/template
Not longer using as I fully switched to newsraft #42998
- I tested the changes in this PR: nothing to test
> newsboat: orphan

- srcpkgs/miniserve/template
> miniserve: update to 0.23.1

- srcpkgs/teeworlds/patches/CVE-2021-43518.patch
- srcpkgs/teeworlds/template
- I tested the changes in this PR: **briefly** (just playing the game, not the vulnerability)
- armv7l-glibc (crossbuild)
- aarch64b-glibc (crossbuild)
> teeworlds: fix CVE-2021-43518

- srcpkgs/cargo-license/template
> cargo-license: generate missing lockfile

- srcpkgs/cups/template
- I built this PR locally for my native architecture, (x86_64-libc) (print client)
- aarch64 (print server)
The latest version of CUPS default to build against OpenSSL. Before that it was defaulting to GnuTLS. The template is written with GnuTLS in mind (dpes). This change brings back GunTLS as TLS backend.
I was having issues with IPPS (TLS over 631 port) with cups as a print server and as a client (IPP Everywhere). The server compiled against OpenSSL would fail when TLS client was connecting in with error pointing to issue with certificate generation. Also when provided with custom certificate cupsd would crash. 
After this patch for client and server it all …
> cups: reverting to GnuTLS backend (fix broken new CUPS OpenSSL default IPPS issues)

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.15.0.

- srcpkgs/python3-psutil/template
> python3-psutil: update to 5.9.5.

- srcpkgs/musl-legacy-compat/files/tree.h
- srcpkgs/musl-legacy-compat/template
Fix <sys/tree.h> usage of __unused.
Fixes #41769.
> musl-legacy-compat: update to 0.6.

- srcpkgs/etcd/template
The original package contains no binaries:
```
$ xls etcd
/etc/sv/etcd/conf
/etc/sv/etcd/log/run
/etc/sv/etcd/run
/etc/sv/etcd/log/supervise -> /run/runit/supervise.etcd-log
/etc/sv/etcd/supervise -> /run/runit/supervise.etcd
```
Looks like the name of the Go import path was changed.
With this fix:
```
$ xls etcd
/etc/sv/etcd/conf
/etc/sv/etcd/log/run
/etc/sv/etcd/run
/usr/bin/etcd
/usr/bin/etcdctl
/etc/sv/etcd/log/supervise -> /run/runit/supervise.etcd-log
/etc/sv/etcd/supervise -> /run/runit/supervise.etcd
```
I set it up and it is running; I can put and get a value form it.
> etcd: fixed go_import_path

- srcpkgs/booster/patches/fix-target-dir.patch
- srcpkgs/booster/patches/symlink.patch
- srcpkgs/booster/template
> booster: update to 0.10.

- srcpkgs/btrfs-progs/template
> btrfs-progs: update to 6.2.2.

- srcpkgs/python3-importlib_metadata/template
> python3-importlib_metadata: update to 6.6.0.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.16.0.

- srcpkgs/python3-phonenumbers/template
- srcpkgs/synapse/template
- python3-phonenumbers: update to 8.13.10.
- synapse: update to 1.82.0.
> synapse: update to 1.82.0.

- srcpkgs/tachyon/template
I've been using this version for a while. I didn't PR before because the homepage was down and I thought it was transient.
Many months after the fact, the webpage is still down, so I moved the homepage to sagemath mirror (https://mirrors.mit.edu/sage/spkg/upstream/tachyon/index.html). Note that this package is essential for sagemath (for 3d plots) and so this mirror should be good for long.
The file in the mirror is exactly the same one that was originally distributed by upstream. You can see arch is shipping the same version and the same sha256 here: https://github.com/archlinux/svntogit-community/blob/packages/tachyon/trunk/PKGBUILD.
> tachyon: update to 0.99.5.

- srcpkgs/eclib/template
Tested with sagemath 9.8 (current void pkg) and with sagemath 10.0.rc0 (rc for next version).
> eclib: update to 20230424.

- srcpkgs/mu4e/patches/fix-root-test.patch
- srcpkgs/mu4e/template
- I tested the changes in this PR: **Yes**
- x86_64-musl  (crossbuild)
- changed build style to `meson` as it is the primary build option of `mu`
- removed `guile` build option because it depends on `guile-3.x`.
- users will have to re-initialize their database (`mu-init(1)`)
> mu4e: update to 1.10.3

- srcpkgs/libpsl/template
> libpsl: update to 0.21.2.

- srcpkgs/qutebrowser/template
> qutebrowser: update to 2.5.4, adopt

- srcpkgs/mpv-mpris/template
Maintainer hasn't committed to void-packages since September 2020 (60442441bb48b513110fda775d4914f49c62c426).
@subosito is this fine with you?
> mpv-mpris: update to 1.0, adopt.

- srcpkgs/mpvpaper/template
- I built this PR locally for these architectures (all crossbuilds):
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- i686
- x86_64-musl
Closes https://github.com/void-linux/void-packages/issues/42359
It builds fine on all of the above, but I tested the package only on x86_64-gnu.
> New package: mpvpaper-1.3

- srcpkgs/python3-Babel/template
Using sphinx with current version of `python3-Babel` gives the following deprecation warning :
```
$ python -Wonce -c 'import sphinx.application'
/usr/lib/python3.11/site-packages/babel/messages/catalog.py:13: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
from cgi import parse_header
```
The update fixes this. I had to include https://github.com/python-babel/babel/pull/998 so tests pass, since it only touches test code I think its safe to include.
I found this while doctesting sagemath. A bunch of tests fail because of this deprecation warning, and after this update everything passes.
Cc: @sgn, since this affects `python3-Sphinx`.
> python3-Babel: update to 2.12.1.

- srcpkgs/ibus/patches/497f0c74230a65309e22ce5569060ce48310406b.patch
- srcpkgs/ibus/patches/7c8abbe89403c2fcb08e3fda42049a97187e53ab.patch
- srcpkgs/ibus/patches/8f706d160631f1ffdbfa16543a38b9d5f91c16ad.patch
- srcpkgs/ibus/patches/a4007f7d0bdfb98457487c85304188c411e6d991.patch
- srcpkgs/ibus/template
> ibus: fix emoji selection and key order

- srcpkgs/linux-firmware/template
based on https://github.com/chimera-linux/cports/blob/339c0eef5be61397707170c6789e09fa4c3b5810/main/firmware-linux/template.py#L83-L86
this shouldn't break anything because `linux-firmware` depends on `linux-firmware-network` already
fixes #43515 
fixes void-linux/void-mklive#224
- I tested the changes in this PR: **briefly** (the intended packages have the intended files)
> linux-firmware: move all mediatek WLAN/BT drivers to -network subpkg

- srcpkgs/disklow/template
Addresses #42403.
I tried finding any precedence for an alive distfile but with broken certs and could only find #7512. Don't know if this is still the right way to workaround this 4 years later.
> disklow: workaround distfiles cert error.

- srcpkgs/restic/template
> restic: update to 0.15.2.

- srcpkgs/libgusb/template
> libgusb: update to 0.4.5.

- srcpkgs/rsClock/template
> rsClock: update to 0.1.9.

- srcpkgs/libmtp/template
I have it installed, works ok with my garmin watch via `gmtp`.
> libmtp: update to 1.1.21.

- srcpkgs/python3-bitstring/template
> python3-bitstring: update to 4.0.2.

- srcpkgs/python3-curio/template
> python3-curio: update to 1.6.

- srcpkgs/python3-ipython/template
sagemath works and its testsuit passes with this update.
Some tests in ipython were skipped before, but it seems now they pass.
Cc: @ahesford
> python3-ipython: update to 8.13.1.

- srcpkgs/aerc/template
> aerc: update to 0.15.1

- srcpkgs/postfix/template
- aarch64-musl
- armv7l
- armv6l-musl
> postfix: update to 3.8.0.

- srcpkgs/gptfdisk/patches/fix-sgdisk-crash.patch
- srcpkgs/gptfdisk/template
Fixes #43677.
@atweiden can you see if this PR fixes the issue for you?
> gptfdisk: fix sgdisk crashing with popt-1.19.

- srcpkgs/python3-pygit2/template
> python3-pygit2: fix cross build.

- srcpkgs/python3-yapf/template
Fixes https://github.com/void-linux/void-packages/issues/43726
> python3-yapf: fix egg-info permission

- srcpkgs/puzzles/template
- srcpkgs/puzzles/update
Fixes https://github.com/void-linux/void-packages/issues/43759
> puzzles: update to 20230505.63346a8.

- srcpkgs/python3-ipython/template
This is a hotfix to make right arrow work again! It's broken since the update 8.12.0 -> 8.13.1.
```
IPython 8.12.2 and 8.13.2 contain UI fixes, with respect to right arrow not
working in some case in the terminal, and 8.12.2 contain also a requested
backport of :ghpull:`14029` (Allow safe access to the ``__getattribute__``
method of modules) for tab completion.
```
@ahesford
> python3-ipython: update to 8.13.2.

- srcpkgs/vivaldi/files/redistribution-permission.eml
- srcpkgs/vivaldi/patches/support-user-flags.patch
- srcpkgs/vivaldi/template
will now read the contents of `$XDG_CONFIG_HOME/vivaldi-stable.conf` and pass that to the underlying binary
patch comes from arch
for example, to force `prefers-color-scheme: dark` and work on wayland:
```
$ cat ~/.config/vivaldi-stable.conf
--force-dark-mode --ozone-platform-hint=auto
```
missing dependencies libnotify and xdg-utils also added
permission to redistribute has now been granted, see `srcpkgs/vivaldi/files/redistribution-permission.eml`
> vivaldi: update to 6.0.2979.18, unrestrict, support user flags, adopt.

- srcpkgs/dracut/template
Follow-up to https://github.com/void-linux/void-packages/pull/41716#issuecomment-1451141356
Other changes:
- remove connman as it depends on systemd
- move more network dependent modules to dracut-network package
CC @zdykstra @classabbyamp
> dracut: remove ifcfg dracut module

- srcpkgs/mumble/patches/pipewire-fix.patch
- srcpkgs/mumble/template
Currently due to a libpipewire change (most likely >= 0.3.68) the Mumble client segfaults when trying to change any setting. This backported patch fixes the issue (small change).
- I built this PR locally for my native architecture, x86_68-glibc
> mumble: backport fix for segfault with pipewire

- common/shlibs
- srcpkgs/Waybar/template
The libevdev-devel dependency was missing, and was needed for the keyboard-state module to work.
> Waybar: Update to 0.9.17 & add libevdev-devel necessary for keyboard-module

- common/environment/setup/install.sh
`vman out/foo.fr.UTF-8.1` should install `usr/share/man/fr.UTF-8/man1/foo.1`, not `usr/share/man/fr/man1/foo.UTF-8.1`
> common/environment/setup/install.sh: support encoding in vman

- srcpkgs/glibmm2.68/template
- srcpkgs/glibmm2.68/update
- srcpkgs/telegram-desktop/template
Local build testing
I built this PR locally for my native architecture, glibc, x64
Note: PR depends on PR https://github.com/void-linux/void-packages/pull/43231 to build
> telegram-desktop: update to 4.8.0.

- common/build-style/python3-pep517.sh
- srcpkgs/python3-trustme/template
some tests change cwd which causes relative tmpdir to point to a non-existent location, this PR also includes a trustme update which is affected by this
cc @ahesford @icp1994
> common/build-style/python3-pep517: use absolute path for check temp dir + trustme update

- srcpkgs/gtklock/template
> gtklock: update to 2.1.0

- srcpkgs/font-adobe-100dpi/template
- srcpkgs/font-adobe-75dpi/template
- srcpkgs/font-adobe-utopia-100dpi/template
- srcpkgs/font-adobe-utopia-75dpi/template
- srcpkgs/font-adobe-utopia-type1/template
- srcpkgs/font-alias/template
- srcpkgs/font-bh-100dpi/template
- srcpkgs/font-bh-75dpi/template
- srcpkgs/font-bh-lucidatypewriter-100dpi/template
- srcpkgs/font-bh-lucidatypewriter-75dpi/template
- srcpkgs/font-bh-ttf/template
- srcpkgs/font-bh-type1/template
- srcpkgs/font-bitstream-100dpi/template
- srcpkgs/font-bitstream-75dpi/template
- srcpkgs/font-bitstream-speedo/template
- srcpkgs/font-bitstream-type1/template
- srcpkgs/font-cursor-misc/template
- srcpkgs/font-daewoo-misc/template
- srcpkgs/font-dec-misc/template
- srcpkgs/font-ibm-type1/template
- srcpkgs/font-isas-misc/template
- srcpkgs/font-jis-misc/template
- srcpkgs/font-misc-misc/template
- srcpkgs/font-mutt-misc/template
- updated various X.org fonts with minor version bump
- updated the URLS from bz2 to gz
> X.org fonts: updated font versions and source URLs

- srcpkgs/exiftool/template
> exiftool: update to 12.62.

- srcpkgs/bash-language-server/template
- i686
- x86_64-musl
- aarch64
> New package: bash-language-server-4.9.1

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.17.0.

- srcpkgs/python3-cvxopt/template
- I tested the changes in this PR: **briefly** (tested with sagemath 9.8 and 10.0.rc2)
> python3-cvxopt: update to 1.3.1.

- srcpkgs/giac/template
- I tested the changes in this PR: **briefly** (tested with sagemath 9.8 and 10.0.rc2)
> giac: update to 1.9.0.49.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.17.1.

- srcpkgs/bash-language-server/template
> bash-language-server: update to 4.9.2.

- srcpkgs/obconf/template
patches are downloaded directly from the source because they are so large.
closes #40398
progress on libglade removal (for #38229) and gtk2 removal
- I tested the changes in this PR: **NO** (I don't run openbox)
> obconf: move to gtk3

- srcpkgs/zig/template
Since zig 0.10.1 the cmake build system will produce a binary with the equivalent of -march=native by default. To produce a binary portable across cpu versions we must target the baseline cpu.
> zig: target baseline cpu

- srcpkgs/vale/template
> vale: update to 2.26.0.

- srcpkgs/fotoxx/template
> fotoxx: update to 23.50.

- srcpkgs/aerc/template
> aerc: update to 0.15.2

- srcpkgs/Thunar/template
> Thunar: update to 4.18.6

- srcpkgs/python3-sympy/template
Works fine with sagemath. A few tests need to be fixed as in https://github.com/sagemath/sage/pull/35635 but it's all cosmetic, nothing critical, so this can be merged just fine. We will fix those dooctests when the next release of sagemath is ready (10.0, prerelease in #43659).
> python3-sympy: update to 1.12.

- srcpkgs/pounce/template
> pounce: update to 3.1, build pounce-notify and pounce-palaver.

- srcpkgs/hidapi/template
- armv6l-musl
The autotools build method is deprecated upstream, cmake is recommended instead
> hidapi: update to 0.13.1.

- srcpkgs/rustypaste/template
> rustypaste: update to 0.9.0.

- srcpkgs/python3/template
As discussed in https://github.com/void-linux/void-packages/pull/43659 this is checked by compiling and running a program that won't work in cross, but we know `sem_gevalue` is ok at least on `aarch64` (to be more conservative, I could also only enable it there, rather than all arches).
cc @ahesford
> python3: force sem_gevalue for all cross arches

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.18.0.

- srcpkgs/ffmpeg/template
> ffmpeg: update to 4.4.4.

- srcpkgs/python3-pycryptodome/template
The package size decreased by an order of magnitude with this bump, I've yet to investigate why this happened and if it might cause issues.
> python3-pycryptodome: update to 3.17.

- srcpkgs/libfontenc/template
> libfontenc: update to 1.1.7.

- srcpkgs/android-tools/template
> android-tools: update to 34.0.1.

- srcpkgs/libfcitx-qt5/template
Fixes private symbol issue in `libfcitx-qt6`:
```
symbol lookup error: libfcitxplatforminputcontextplugin-qt6.so: undefined symbol: _ZN22QWindowSystemInterface22handleExtendedKeyEventEP7QWindowmN6QEvent4TypeEi6QFlagsIN2Qt16KeyboardModifierEEjjjRK7QStringbtb, version Qt_6_PRIVATE_API
```
---
> libfcitx-qt*: rebuild for qt 6.5.0

- srcpkgs/python3-Sphinx/template
currently checks fail with `ModuleNotFoundError: No module named 'filelock'`. Just adding `python3-filelock` to `checkdepends` fixes it.
> python3-Sphinx: fix check, add changelog

- srcpkgs/certbot-apache/template
- srcpkgs/certbot-nginx/template
- srcpkgs/certbot/template
- srcpkgs/python3-acme/template
- I built this PR locally for my native architecture, (x86_64, GLIBC)
- aarch64-musl
- armv7l
- armv6l-musl
> certbot: update to 2.6.0

- srcpkgs/libssh/template
> libssh: update to 0.10.5.

- srcpkgs/mkvtoolnix/template
---
Sticking with Qt5 since `QMediaPlayer` used by `mkvtoolnix-gui` is broken on Qt 6.5.0 (on all platforms, not just Windows as [QTBUG-111951](https://bugreports.qt.io/browse/QTBUG-111951) incorrectly suggests).
> mkvtoolnix: update to 76.0

- srcpkgs/i2pd/template
It's not a good idea to have /etc/i2pd/*.conf world-readable since it may contain sensitive information
> i2pd: restrict /etc/i2pd permissions

- srcpkgs/tuxedo-keyboard/template
> tuxedo-keyboard: update to 3.2.5

- srcpkgs/Signal-Desktop/template
-----
This uses a hacky `vsed` command to build with our version of node (16.19.0). It works for me, but it'd be much better if #41239 was merged soon.
> Signal-Desktop: update to 6.19.0.

- srcpkgs/wireplumber/template
This fixes a warning from pipewire complaining that the folder does not exist.
> wireplumber: create /var/lib/wireplumber

- srcpkgs/bzip2/files/bzip2.pc
- srcpkgs/bzip2/template
Adapted from [Arch Linux](https://github.com/archlinux/svntogit-packages/commit/e2cc08098f31fc7110131782626d22939731b7d5)
Context: upstream has been unresponsive about requests for pkgconfig files in the past, but Arch and Alpine include their own, at least.
Also, the experimental future development project added the file back in 2019: https://gitlab.com/bzip2/bzip2/-/commit/70ec984159c8263fdd4aac7c4670977aff0fe5b3
> bzip2-devel: add pkgconfig file

- srcpkgs/qca-qt5/template
> qca-qt5: update to 2.3.6.

- srcpkgs/Komikku/template
> Komikku: update to 1.21.1

- srcpkgs/gtk4/patches/4a187d7f1d0f1aea8a5697a50299594ef523faf7.patch
- srcpkgs/gtk4/template
This also fixes an issue in nautilus where removed items appear at the front of the file list.
> gtk4: fix TreeList item order

- srcpkgs/go/template
This version update has 3 security fixes for go:
- https://github.com/golang/go/issues/59720 - CVE-2023-24539
- https://github.com/golang/go/issues/59721 - CVE-2023-24540
- https://github.com/golang/go/issues/59722 - CVE-2023-29400
> go: update to 1.20.4.

- srcpkgs/evince/template
- armv7l  (crossbuild)
- aarch64  (crossbuild)
> evince: update to 44.1

- srcpkgs/coredns/template
There have been a bunch of security fixes since 1.8.6, so it's a good idea to get this in soon.
@nilium
> coredns: update to 1.10.1.

- srcpkgs/librepcb/template
> librepcb: add missing qt5-plugin-sqlite dependency.

- srcpkgs/elfutils/template
> elfutils: update to 0.189.

- srcpkgs/fselect/template
Fix for https://github.com/void-linux/void-packages/pull/44220#issuecomment-1575510972
> fselect: fix for rust 1.70

- srcpkgs/puzzles/template
> puzzles: update to 20230606.4227ac1.

- srcpkgs/libssh2/template
> libssh2: update to 1.11.0

- srcpkgs/pnpm/template
cc @fnogcps
The 7.x branch of pnpm is no longer maintained (according to https://pnpm.io/versions), and I couldn't find any reasons to not switch to the 8.x branch. 
pnpm 8 dropped support for nodejs 14, but since we're already using nodejs 16 that shouldn't be an issue.
> pnpm: update to 8.6.0

- srcpkgs/helix/files/hx
- srcpkgs/helix/template
Allows users to set their own `HELIX_RUNTIME` variable and also autodetect the system runtime dir `/usr/lib/helix/runtime`
> helix: switch from launcher script to symlink

- srcpkgs/rpi-imager/template
> rpi-imager: update to 1.7.5.

- srcpkgs/peru/template
> peru: update to 1.3.1.

- srcpkgs/exiftool/template
> exiftool: update to 12.63.

- srcpkgs/muon/template
https://github.com/void-linux/void-packages/commit/e78571c047ddc9fdcf1ebcdc079fcf60eee42a94 says "New package: muon-0.2.0" but it was actually `v0.1.0`.
> muon: update to 0.2.0.

- srcpkgs/quickjs/patches/patch-gh-issue-178-cve-2023-31922.patch
- srcpkgs/quickjs/template
- 
https://github.com/bellard/quickjs/issues/178
> quickjs: Fix stack overflow in CVE-2023-31922

- srcpkgs/curl/template
Now that libssh2 builds with cmake, enabling SSH support in curl introduces a build cycle:
binutils -> elfutils -> curl -> libssh2 -> cmake -> curl
Because SSH support in curl seems superfluous anyway, just disable it.
The other alternative is to go back to autotools for libssh2. I don't know if that's a long-term solution, but it seems possible for now.
> curl: disable ssh option to break build cycle

- srcpkgs/fluidsynth/template
> fluidsynth: update to 2.3.2.

- srcpkgs/moosefs/template
> moosefs: update to 3.0.117

- srcpkgs/man-db/template
It's just a version bump.
- x86_64-musl
> man-db: update to 2.11.2

- srcpkgs/wlrctl/patches/fix-ascii-check.patch
- srcpkgs/wlrctl/template
> New package: wlrctl-0.2.2

- srcpkgs/gwe/template
- I tested the changes in this PR: **briefly** (just checked that the app launches properly on a non-nVidia system, so testing from nVidia users is appreciated)
@LegoLivesMatter
Related to https://github.com/void-linux/void-packages/pull/43699 (I was checking python-urllib3 dependents and found that gwe doesn't use it anymore).
> gwe: update to 0.15.5.

- srcpkgs/activityrelay/files/activityrelay/run
- srcpkgs/activityrelay/template
- srcpkgs/python3-aputils/template
- srcpkgs/python3-aputils/update
- New package: python3-aputils-0.1.4
This one might be a gamebreaker, not sure about this license...
- activityrelay: update to 0.2.4.
> activityrelay: update to 0.2.4.

- srcpkgs/syft/template
> syft: update to 0.83.0

- srcpkgs/haproxy/template
> haproxy: update to 2.6.14.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.21.0.

- srcpkgs/linux-wifi-hotspot/patches/makefile.patch
- srcpkgs/linux-wifi-hotspot/template
`linux-wifi-hotspot` is the successor of `create_ap`, which got discontinued in 2021.
`linux-wifi-hotspot` additionally provides a gtk interface for creating hotspots, but it does contain a more updated version of `create_ap` too.
> New package: linux-wifi-hotspot-4.5.0

- srcpkgs/python-cffi/template
- srcpkgs/python3-cffi
- srcpkgs/python3-cffi/template
> python-cffi: split python3-cffi to a new package

- srcpkgs/python3-dateutil
- srcpkgs/python3-dateutil/patches/pytest8.patch
- srcpkgs/python3-dateutil/template
> python-dateutil: split python3-dateutil to a new package

- srcpkgs/python3-constantly
- srcpkgs/python3-constantly/template
> python-constantly: split python3-constantly to a new package

- srcpkgs/PrismLauncher/template
- Updated Openjdk in the template as the compatibility with prism is verified up until openjdk 20. Also added a QT5 argument as building Prism using QT6 will cause issues. It should be kept as is up until QT6-cmake is available in void repos.
> PrismLauncher: update to 7.1.

- srcpkgs/libheif/template
> libheif: move thumbnailer to tools subpackage.

- srcpkgs/hackrf/template
- x86_64-musl
- aarch64
- aarch64-musl
- armv7l
- armv6l
- i686
> hackrf: update to 2023.01.1.

- srcpkgs/putty/template
> putty: update to 0.78

- srcpkgs/kdenlive/template
mediainfo-cli is an optional dependency of Kdenlive.
On other distros the `mediainfo` package provides the cli application and the `mediainfo-gui` package provides the gui application. On void, the `mediainfo` package installs the gui application and `mediainfo-cli` installs the cli application.
The package was updated to install the gui package instead of the cli package, when only the cli application is used afaict.
> kdenlive: depend on mediainfo-cli instead of mediainfo-gui

- srcpkgs/libgbinder/template
> libgbinder: update to 1.1.34.

- srcpkgs/cargo-outdated/template
> cargo-outdated: update to 0.13.1.

- srcpkgs/a4/template
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l-musl
> New package: a4-0.2.1

- srcpkgs/libde265/template
Fixes a couple of security issues: https://github.com/strukturag/libde265/releases/tag/v1.0.12
> libde265: update to 1.0.12.

- srcpkgs/tuxedo-keyboard/template
- I built this PR locally for my native architecture, (x84_64)
> tuxedo-keyboard: update to 3.2.6

- srcpkgs/libgusb/template
> libgusb: update to 0.4.6.

- srcpkgs/android-udev-rules/template
> android-udev-rules: update to 20230614.

- srcpkgs/pnpm/template
pnpm reverted pnpm-lock v6.1 to v6.0 https://github.com/pnpm/pnpm/issues/6648 it's suggested to upgrade to v8.6.2
> pnpm: update to 8.6.2

- srcpkgs/gogglesmm/template
- Adds new dependency : libxml2-devel
> gogglesmm: update to 1.2.3

- srcpkgs/python3-Markdown/template
> python3-Markdown: update to 3.4.3

- srcpkgs/zellij/template
> zellij: update to 0.37.2

- srcpkgs/nyxt/patches/002-webkit2gtk.patch
- srcpkgs/nyxt/template
- Updated 002-webkit2gtk.init.lisp patch. The patch itself is the same, but the structure of the source file to be patched changed.
- Included "pkg-config" into hostmakedepends.
- I built this PR locally for my native architecture, x86_64*
> nyxt: update to 3.2.0

- srcpkgs/bird/template
Security update, from changelog:
o BGP: Fix role check when no capability option is present
o Filter: Fixed segfault when a case option had an empty block
> bird: update to 2.13.1

- srcpkgs/apache/template
Tested by running `httpd -V` to show the compile configuration (did this for x86\_64 and aarch64)
- x86\_64-musl
- aarch64
- armv6l
(CC @ologantr)
> apache: Update to 2.4.56

- common/shlibs
- srcpkgs/gst-libav/template
- srcpkgs/gst-omx/template
- srcpkgs/gst-plugins-bad1/template
- srcpkgs/gst-plugins-base1/template
- srcpkgs/gst-plugins-good1/template
- srcpkgs/gst-plugins-ugly1/template
- srcpkgs/gst-rtsp-server/template
- srcpkgs/gst1-editing-services/template
- srcpkgs/gst1-python3/template
- srcpkgs/gstreamer-vaapi/template
- srcpkgs/gstreamer1/template
- I tested the changes in this PR: **YES** **partially**
not installed:
- gst-omx
- gst-rtsp-server
- gst1-editing-services
- gst1-python3
- I built this PR locally for my native architecture **x86_64**
Change distfiles to vars for rtsp like the other packages.
I see `shlibs` has some libgst* links to 1.0 versions and then what I assume are leftover 1.18.3_2 versions? should those be removed? I don't see anything like a 1.xx on my box, only 2023 and 1.0s. It's a relatively new build and gst* is getting bumped from 1.20.3.
> Gstreamer 1.22.2

- srcpkgs/mu4e/template
> mu4e: update to 1.10.4

- srcpkgs/drm_info/template
~~This builds with meson so the checks are going to be broken until python 3.11 is done.~~
> New package: drm_info-2.4.0

- srcpkgs/dhcpcd/patches/Linux-Improve-learning-IPv6-address-flags.patch
- srcpkgs/dhcpcd/template
Adds https://github.com/NetworkConfiguration/dhcpcd/commit/1a70f1b51c453c66993fab8172e57924059bd34b to solve https://github.com/NetworkConfiguration/dhcpcd/issues/149
> dhcpcd: fix dhcpv6-pd for pppoe

- srcpkgs/solo2-cli/template
Companion software for solo v2 security keys. Successfully updated two keys' firmware. Bash and zsh completions work, didn't try fish.
> New package: solo2-cli-0.2.2

- srcpkgs/selene/template
We have a [Lua LSP](https://github.com/void-linux/void-packages/tree/master/srcpkgs/lua-language-server) and a [Lua formatter](https://github.com/void-linux/void-packages/tree/master/srcpkgs/StyLua) but no Lua linter afaics. I'm submitting this one since I use it personally.
> New package: selene-0.25.0

- srcpkgs/mazter/template
> New package: mazter-0.4.1

- srcpkgs/xone/files/README.voidlinux
- srcpkgs/xone/template
`curl` and `cabextract` depends are used by `xone-update-firmware`
> New package: xone-0.3

- srcpkgs/nextdns/files/nextdns/run
- srcpkgs/nextdns/patches/Don't touch files managed by xbps.patch
- srcpkgs/nextdns/template
Closes #19905
Based on #30603, which replaced #20022
> New package: nextdns-1.39.4

- srcpkgs/flavours/template
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): YES
> New package: flavours-0.6.1

- srcpkgs/hg-evolve/template
[evolve](https://www.mercurial-scm.org/wiki/EvolveExtension) is a Mercurial extension for faster and safer mutable history. It implements the [changeset evolution](https://www.mercurial-scm.org/doc/evolution/#changeset-evolution) concept for Mercurial.
This version of evolve finally ships the stabilized (v1.0.0) version of the [topics extension](https://www.mercurial-scm.org/doc/evolution/tutorials/topic-tutorial.html).
> New package: hg-evolve-11.0.1

- srcpkgs/hurl/template
[Hurl](https://hurl.dev) is a CLI tool that runs HTTP requests defined in a simple plain text format. It can chain requests, capture values and evaluate queries on headers and body response. It can be used for both fetching data and testing HTTP sessions.
> New package: hurl-3.0.0

- srcpkgs/tarpaulin/patches/0.20.1-tests.patch
- srcpkgs/tarpaulin/patches/0.25.0-tests.patch
- srcpkgs/tarpaulin/template
update so that it builds with openssl3 #37681 , patch out a few tests.
> tarpaulin: update to 0.25.0, patch tests

- srcpkgs/librsvg/template
- srcpkgs/librsvg/update
> librsvg: update to 2.56.1.

- srcpkgs/timidity/template
> timidity: build on musl without broken alsa audio

- srcpkgs/k3d/template
> k3d: update to 5.5.1.

- srcpkgs/hcloud/template
> hcloud: update to 1.36.0.

- srcpkgs/krita/template
Required by the Krita JPEG-XL filter
> krita: enable JPEG XL support

- srcpkgs/python3-ansible-lint/template
Tagging the maintainer: @jcgruenhage
- x86_64-musl
> python3-ansible-lint: update to 6.17.1

- srcpkgs/libaio/template
- I tested the changes in this PR: not yet
> libaio: update to 0.3.113.

- srcpkgs/vice/template
> vice: update to 3.7.1.

- srcpkgs/openjdk17/template
Also fix openjdk17-jmods depending on itself instead of openjdk17.
@classabbyamp
[ci skip]
> openjdk17: update to 17.0.8+6.

- srcpkgs/osc/template
[OSC (Open Build Service Commander)](https://github.com/openSUSE/osc) is a command line interface for [OBS](https://openbuildservice.org/).
> New package: osc-1.1.4

- srcpkgs/yaydl/template
> new package: yaydl-0.13.0

- srcpkgs/memray/template
[Memray](https://bloomberg.github.io/memray/) is a memory profiler for Python. It can track memory allocations in Python code, in native extension modules, and in the Python interpreter itself. It can generate several different types of reports to help you analyze the captured memory usage data.
> New package: memray-1.7.0

- srcpkgs/libspnav/template
Using a SpaceMouse Pro Wireless with the latest upstream versions of `spacenavd`, `spnavcfg`, and the latest version of FreeCAD in the repository.
* The upstream sources are now accessible on GitHub (for all three related packages). The 1.1 version is not on SourceForge so I switched the `distfiles` to GitHub.
* I dropped the `do_build()` section as it doesn't seem to be necessary when using the `gnu-configure` build style. If there's something I missed here for why this should be kept in please let me know.
* The library supports a non-X11 build but I'm not sure how to expose that. Does XBPS support variants like that? If it matters to someone and you can point me to the relevant …
> libspnav: update to 1.1, minor fixes

- srcpkgs/swayfx/INSTALL
- srcpkgs/swayfx/patches/7326.diff
- srcpkgs/swayfx/template
I basically just adapted the existing ```sway``` package to this fork. I've run this for a few days on my machine.
> New package: swayfx

- srcpkgs/clifm/template
> Clifm is a Command Line Interface File Manager: all input and interaction is performed via commands. This is its main feature and strength.
<https://github.com/leo-arch/clifm>
- x86\_64-musl
- i686
- aarch64
> New package: clifm-1.11

- srcpkgs/aardvark-dns/template
- srcpkgs/netavark/template
podman 4.0's new network stack.
Some more information if anybody is interested: https://www.redhat.com/sysadmin/podman-new-network-stack
https://github.com/containers/netavark
https://github.com/containers/aardvark-dns
> New packages: netavark-1.6.0, aardvark-dns-1.6.0

- srcpkgs/singular/patches/8d54773d6c9e2f1d2593a28bc68b7eeab54ed529.patch
- srcpkgs/singular/template
Tested with sagemath testsuite, needs #44624 merged first.
> singular: update to 4.3.2p2.

- common/build-style/go.sh
Without this check, calling `go install` with a wrong go_import_path
might end up downloading the source code for said package (using git,
for example), instead of building from the provided tarball. The first
line of go.mod should be "module $go_import_path" for Go to not try and
download source code instead of using what it has locally.
Fixes #27690.
I have yet to test if this catches mismatches correctly.
> common/build-style: check if go_import_path matches go.mod.

- srcpkgs/maxima/template
- srcpkgs/sagemath/patches/35619-maxima_5.46.0.patch
- srcpkgs/sagemath/patches/35707-maxima_5.47.0.patch
- srcpkgs/sagemath/patches/35825-singular_4.3.2p2.patch
- srcpkgs/sagemath/patches/35826-numpy_1.25.0.patch
- srcpkgs/sagemath/patches/35831-setuptools_68.0.0.patch
- srcpkgs/sagemath/patches/get_patches
- srcpkgs/sagemath/template
This updates maxima to 5.47.0, which needs a patch and rebuild for sagemath (https://github.com/sagemath/sage/pull/35707/).
Also:
- patch sagemath to support singular 4.3.2p2 (https://github.com/sagemath/sage/pull/35825)
- patch sagemath to support numpy 1.25.0 (https://github.com/sagemath/sage/pull/35826)
This PR can be safely merged before updating singular and numpy. Afther this is merged numpy  (#44529) and singular updates can be merged.
> maxima: update to 5.47.0, patch and rebuilds sagemath for maxima, singular, numpy updates. 

- srcpkgs/python3-numpy/patches/fix-pytest-warning.patch
- srcpkgs/python3-numpy/template
I enabled check, and I'm currently testing with sagemath to see what fails and fix it. So far I've only tried x86_64.
I didn't change the build-style to pep517 because that won't allow parallel build. For testing, a custom `do_check()` is needed in any case. Moreover, it seems numpy will soon move to meson for building so we may as well wait for that.
@ahesford
> python3-numpy: update to 1.25.0.

- srcpkgs/ZMusic/template
Little update for the zmusic package that might be required for gzdoom.
- I tested the changes in this PR: **briefly (i tested on x64)**
> Updating ZMusic to 1.1.12

- srcpkgs/transmission/files/transmission-daemon/run
- srcpkgs/transmission/template
Even though the man page for transmission-daemon was not updated to reflect the change, `--log-error` has been deprecated by `--log-level=error` (see `transmission-daemon --help`).
A warning is logged if the old flag is used.
> transmission: don't use deprecated --log-error

- srcpkgs/preload/patches/qemu-help2man.patch
- srcpkgs/preload/template
If `help2man` isn't available at build time then the contents of man8/preload.8 are:
> help2man is required to generate this file.
Apparently `makewhatis` has to run after the new file is installed so `man` knows to run the file through the formatter but I'd rather not add a post-install script.
This also adds psmisc to checkdepends because the test script uses `( sleep 1; killall ./preload 2>/dev/null ) &` to ensure the test ends.
> preload: generate manpage when not cross

- srcpkgs/pan/template
I don't know why, but sha256 in package's template was incorrect.
Also, I added `gcr-devel` which in turn (when combined with `libsecret-devel`) enabled secret storage
> pan: updated checksum, enabled libsecret

- srcpkgs/python3-docstring-to-markdown/template
> python3-docstring-to-markdown: update to 0.12.

- srcpkgs/nix/files/nix-daemon/run
- srcpkgs/nix/template
The new value is the same as the one of NixOS:
<https://github.com/NixOS/nix/blob/601849b95afc3d173ea34ff5dba6353f9b71b495/misc/systemd/nix-daemon.service.in#L12>
> nix: increase open files limit.

- srcpkgs/usbguard/patches/musl.patch
- srcpkgs/usbguard/template
Most of musl.patch appears to have been merged upstream with modifications
> usbguard: update to 1.1.2.

- srcpkgs/1password/INSTALL
- srcpkgs/1password/files/EULA
- srcpkgs/1password/template
- I built this PR locally also for aarch64-glibc (cross-build)
- Added 1Password icons and 1password.desktop file to template
- Extended INSTALL post action to create and install custom policy file
- Added aarch64 as a supported architecture
- Revised the license handling as per commit 1527238
> 1password: update to 8.10.7.

- srcpkgs/hardinfo/patches/fix-runtime.patch
- srcpkgs/hardinfo/template
Clicking on the `sensors` page gave `hardinfo: symbol lookup error: /usr/lib64/hardinfo/modules/devices.so: undefined symbol: remove_linefeed`
Copied what was in current `fix-runtime.patch`. Not how it worked before, last updated 2020.
> hardinfo: revbump for remove_linefeed fixes

- srcpkgs/bash-language-server/template
> bash-language-server: update to 4.10.1.

- srcpkgs/libbytesize/patches/musl-fix-test.diff
- srcpkgs/libbytesize/template
> libbytesize: update to 2.8.

- srcpkgs/ghex/template
> ghex: update to 44.1

- srcpkgs/exiftool/template
> exiftool: update to 12.64.

- srcpkgs/autorestic/template
[Autorestic](https://github.com/cupcakearmy/autorestic) is a wrapper for [restic](https://restic.net/) similar to what [borgmatic](https://torsion.org/borgmatic/) is for [borg](https://www.borgbackup.org/).
- x86_64-musl
> New package: autorestic-1.7.7

- srcpkgs/fend/template
> New package: fend-1.2.0

- srcpkgs/gspell/template
> gspell: update to 1.12.1.

- srcpkgs/thrift/patches/network-tests.patch
- srcpkgs/thrift/patches/skip-old-tls-tests.patch
- srcpkgs/thrift/template
required to build with openssl3 #37681
> thrift: update (openssl3)

- srcpkgs/git-cola/template
Without python3-packaging, git-cola doesn't start.
> git-cola: Add python3-packaging to depends

- srcpkgs/io.elementary.videos/template
> io.elementary.videos: update to 2.9.1

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.23.0.

- srcpkgs/checkbashisms/template
Although this version doesn't change the `checkbashisms` script itself (as per the changelog), I wanted to add the bash completions.
> checkbashisms: update to 2.23.5.

- srcpkgs/osv-scanner/template
> osv-scanner: update to 1.3.5.

- srcpkgs/system-monitoring-center/template
> system-monitoring-center: update to 2.17.0

- srcpkgs/arpack-ng/patches/b3fe4ad7.patch
- srcpkgs/arpack-ng/template
- srcpkgs/arpack-ng/update
The update was masked since it caused test failures in igraph (https://github.com/igraph/igraph/issues/2311 and https://github.com/opencollab/arpack-ng/issues/401).
Since then a PR fixing the issues has been proposed at https://github.com/opencollab/arpack-ng/pull/414 (that's the added `b3fe4ad7.patch` here).
I've checked the test suite of igraph now passes.
> arpack-ng: update to 3.9.0.

- common/shlibs
- srcpkgs/Field3D/template
- srcpkgs/alembic/template
- srcpkgs/blender/template
- srcpkgs/calligra/template
- srcpkgs/darktable/template
- srcpkgs/gmic/template
- srcpkgs/hugin/template
- srcpkgs/imath/template
- srcpkgs/kimageformats/template
- srcpkgs/krita/template
- srcpkgs/libgdal/template
- srcpkgs/opencolorio/template
- srcpkgs/openexr/template
- srcpkgs/openimageio/template
- srcpkgs/synfig/template
- srcpkgs/synfigstudio/template
- srcpkgs/vigra/template
[ci-skip] [ci skip]
- **Review**. (If someone could do a rebuild of everything changed here would be highly appreciated, I am currently
leaving my laptop overnight compiling everything with xxbuild for a specific arch, see below what I have already tested, getting some crossbuilding testing would be nice)
- x86_64  (native)
- I tested the changes in this PR: **briefly**, as in didn't test some package that were revbumped.
Previously closed the imath 3.1.8 update because of the changed shlib and the high number of packages that would need to be revbumped. Waited for openexr to release a new version and re-opened this.
> Imath 3.1.9 + Openexr 3.1.9.

- srcpkgs/newsboat/template
> newsboat: update to 2.32

- srcpkgs/SuiteSparse/template
- srcpkgs/octave/patches/fix-suitesparse-7.1.patch
octave seems to work ok with this, even the testsuite passes.
However, due to a (minor) change in `cs_complex_t` octave ftbfs which is fixed by the patch in the second commit. Rebuild of octave is not necessary IMO.
> SuiteSparse: update to 7.1.0.

- srcpkgs/gdm/template
- srcpkgs/lightdm/patches/1.32.0--adjust-PATH-for-usrmerge.patch
- srcpkgs/lightdm/template
- srcpkgs/linux-driver-management/template
- srcpkgs/lxdm/patches/default-PATH.patch
- srcpkgs/lxdm/template
- srcpkgs/openssh/template
- srcpkgs/sddm/patches/0.19.0--default-path.patch
- srcpkgs/sddm/template
- srcpkgs/slim/patches/1.3.6--adjust-PATH-for-usrmerge.patch
- srcpkgs/slim/template
- srcpkgs/util-linux-common/template
- srcpkgs/util-linux/patches/default-PATH.patch
- srcpkgs/util-linux/template
- srcpkgs/xdm/template
/bin is still added to PATH by /etc/profile, but after /usr/bin.
This makes `which` return real file instead of symlink.
> *dm, util-linux, openssh: adjust PATH for usrmerge

- srcpkgs/wayland-protocols/template
cc @ifreund (sorry for pinging the second time today)
> wayland-protocols: update to 1.32.

- srcpkgs/juliaup/template
This package should allow Julia to be installed since it was [removed](https://github.com/void-linux/void-packages/pull/39919).
Package only supports x86_64, i686, and aarch64
- i686-glibc (crossbuild)
- aarch64-glibc (crossbuild)
> New package: juliaup-1.8.16

- srcpkgs/python3-markdown-it/template
> python3-markdown-it: update to 3.0.0.

- srcpkgs/libsoup3/template
> libsoup3: update to 3.4.2.

- srcpkgs/qflipper/template
---
Tagging the maintainer, @Vaelatern
---
Updated the build to Qt6, as well.
> qflipper: update to 1.3.2.

- srcpkgs/yt-dlp/template
> yt-dlp: security update to 2023.07.06

- srcpkgs/dolphin-emu/patches/0001-Add-musl-fix.patch
- srcpkgs/dolphin-emu/template
- x86_64-musl
I've added a patch to fix builds on musl, as well as removing the i686 target (Dolphin stopped supported i686).
> dolphin-emu: update to 5.0.19368.

- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.6.23.

- srcpkgs/pipewire/template
Fixes audio resume-after-supend issue.
> pipewire: update to 0.3.73.

- srcpkgs/gnupg/patches/0002-Revert-gpg-Merge-rfc4880bis-features-into-gnupg.patch
- srcpkgs/gnupg/template
- srcpkgs/libgpg-error/template
- srcpkgs/libksba/template
- libksba: update to 1.6.4.
- libgpg-error: update to 1.47.
- gnupg: update to 2.4.3.
- gnupg: add a patch to do RFC conform PGP by default again, stolen from alpine
> gnupg: update to 2.4.3.

- srcpkgs/inkscape/update
The old Regex also detects development releases (1.3), although it's not an official release yet. (Current should be 1.2.2).
cc @atk
> inkscape: fix update-check

- srcpkgs/puzzles/template
> puzzles: update to 20230707.ad7042d.

- srcpkgs/python3-lsp-server/template
> python3-lsp-server: update to 1.7.4.

- srcpkgs/vale/template
> vale: update to 2.28.0.

- srcpkgs/pkgconf/template
dereferenced.org has been hijacked, see https://social.treehouse.systems/@ariadne/110643909699308207.
> pkgconf: move to new domain

- srcpkgs/python3-typing_extensions/template
> python3-typing_extensions: update to 4.7.1.

- srcpkgs/nss/template
ClearKey plugins need to dlopen(2) this shared object. ClearKey will run into crash if it's not found.
> nss: ship libfreeblpriv3.so

- srcpkgs/python3-trove-classifiers/template
> python3-trove-classifiers: update to 2023.7.6.

- srcpkgs/rust-bindgen/template
- I built this PR locally for these architectures: (crossbuilds)
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- i686
- x86_64-musl
> rust-bindgen: update to 0.66.1.

- srcpkgs/maddy/files/maddy/run
- srcpkgs/maddy/template
This is the same software we already run as our internal mail server, but I'd like to have it packaged so we can create a Void specific container.  I believe this will lead to a generally cleaner configuration and will of course allow the underlying container to share blocks with other void containers on the same host.
> New package: maddy-0.7.0.

- srcpkgs/mu4e/template
> mu4e: update to 1.10.5

- srcpkgs/rustypaste-cli/template
> rustypaste-cli: update to 0.6.0.

- srcpkgs/sssd/template
nsupdate has been moved from bind to bind-utils in #42866. Noticed the build failure while building revbumps for #41948.
> sssd: fix build (wrong hostmakedepend)

- srcpkgs/SweetHome3D/template
As reported in repology
> 2023-07-11 22:22:53   SweetHome3D: ERROR: homepage: "www.sweethome3d.com" does not look like an URL (schema missing)
ref: https://repology.org/log/934775
[skip ci] 
- I tested the changes in this PR:**NO**
> SweetHome3D: add missing https:// schema

- srcpkgs/xorg-docs/template
As reported in repology:
> 2023-07-11 22:22:53 SweetHome3D: ERROR: homepage: "www.sweethome3d.com" does not look like an URL (schema missing)
ref: https://repology.org/log/934775
[skip ci]
> xorg-docs: add missing https:// schema

- srcpkgs/interception-tools/template
Startup messages from the udevmon service were polluting the TTY at boot, adding a logging service fixes this.
- aarch64
- aarch64-musl
> interception-tools: add logging service

- srcpkgs/remmina-kwallet
- srcpkgs/remmina/template
- x86_64-musl
- aarch64
Adds compile flag and dependency to support *KWallet* in Remmina so passwords can be stored.
> remmina: compile with kwallet support

- srcpkgs/OTPClient/template
> OTPClient: update to 3.1.9

- srcpkgs/musl/patches/avoid-set-id-setrlimit-misbehavior-and-hang-in-vfork.patch
- srcpkgs/musl/template
Patch from https://git.musl-libc.org/cgit/musl/commit/?id=a5aff1972c9e3981566414b09a28e331ccd2be5d
Fixes https://github.com/void-linux/void-packages/issues/37382 and afaik shouldn't break anything (I tried rebooting, upgrading, browsing...)
> musl: backport patch to fix #37382

- srcpkgs/vscode/template
The new version tests the checksum of the electron package; since we are using our own build of electron, we need to disable this check.
> vscode: update to 1.80.1

- srcpkgs/swayimg/template
- armv6l-musl
I added dependencies for other image formats (EXR, on this new version, and TIFF, already supported on previous versions). I would like to know if this is OK or if it'd be better to add build options for build customization.
> swayimg: update to 1.12.

- srcpkgs/go/template
go1.20.6 (released 2023-07-11) includes a security fix to the net/http package, as well as bug fixes to the compiler, cgo, the cover tool, the go command, the runtime, and the crypto/ecdsa, go/build, go/printer, net/mail, and text/template packages. See the [Go 1.20.6 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.20.6+label%3ACherryPickApproved) on our issue tracker for details.
> go: update to 1.20.6.

- srcpkgs/docker-compose/template
> docker-compose: update to 2.20.2.

- srcpkgs/sane/template
Building with libpng allows to use `scanimage --format=png`.
@Piraty
> sane: update to 1.2.1

- srcpkgs/gst-plugins-bad1/template
---
```
17:55:12 $ gst-inspect-1.0 va
Plugin Details:
Name                     va
Description              VA-API codecs plugin
Filename                 /usr/lib/gstreamer-1.0/libgstva.so
Version                  1.22.2
License                  LGPL
Source module            gst-plugins-bad
Documentation            https://gstreamer.freedesktop.org/documentation/va/
Source release date      2023-04-11
Binary package           GStreamer Bad Plug-ins source release
Origin URL               https://voidlinux.org
vacompositor: VA-API Video Compositor
vadeinterlace: VA-API Deinterlacer
vah264dec: VA-API H.264 Decoder
vah264enc: VA-API H.264 Encoder
vah265dec: VA-API H.265 Decoder …
```
> gst-plugins-bad1: enable 'va' plugin

- srcpkgs/dotool/template
```
SUMMARY
pkg      host         target        cross  result
dotool   x86_64       x86_64        n      OK
dotool   x86_64-musl  x86_64-musl   n      OK
dotool   i686         i686          n      OK
dotool   x86_64       aarch64-musl  y      OK
dotool   x86_64       aarch64       y      OK
dotool   x86_64       armv7l-musl   y      OK
dotool   x86_64       armv7l        y      OK
dotool   x86_64       armv6l-musl   y      OK
dotool   x86_64       armv6l        y      OK
```
> dotool: update to 1.3;adopt.

- srcpkgs/goreleaser/template
- aarch64-musl
- aarch64
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l
- i686-musl
- i686
> goreleaser: update to 1.19.2.

- srcpkgs/nvidia/template
This should fix the PRIME Synchronization issue that's been reported by a few people in #voidlinux.
> nvidia: update to 535.86.05.

- srcpkgs/openjdk11/files/musl_patches/arm.patch
- srcpkgs/openjdk11/patches/fix-musl-detection.diff
- srcpkgs/openjdk11/template
- I tested the changes in this PR: **NO** (just tested build)
> openjdk11: fix armv7l-musl build.

- srcpkgs/xf86-input-libinput/template
> xf86-input-libinput: update to 1.3.0.

- srcpkgs/neochat/template
Otherwise it exits with this error:
```
qrc:/RoomListPage.qml:11:1: module "org.kde.kitemmodels" is not installed
```
- I tested the changes in this PR: **NO** (didn't build the package locally, just tested that it works correctly with kitemmodels)
> neochat: add missing kitemmodels runtime dep.

- srcpkgs/wxPython4/template
Various programs relying on wxPython, including KiCad, complain about an ABI mismatch between wxPython and the system wxWidgets binaries; as wxPython was never revbumped when [wxWidgets: update to 3.0.5.1](../commit/5464524f084cce8b41d9d22e6ff6b20cd39a8a46) (and possibly earlier) happened.
> wxPython4: revbump for wxWidgets-3.0.5.1

- srcpkgs/btdu/template
enable musl builds - tested on `x86_64-musl`
> btdu: update to 0.5.1.

- srcpkgs/opencl2-headers/template
Switched to cmake provided by upstream.
I couldn't build some software that uses opencl due to pkg-config complaining about missing OpenCL-Headers. This fixed the issue for me.
Ping @ahesford WDYT?
> opencl2-headers: install pkg-config and cmake cfg.

- srcpkgs/tinyssh/template
As of this version, upstream license has changed from Public Domain to CC0.
> tinyssh: update to 20230101.

- srcpkgs/python3-pikepdf/template
> python3-pikepdf: update to 8.2.0.

- srcpkgs/kaboom/template
- I tested the changes in this PR: **YES** (installed the `x86_64-glibc` package and made sure it matches what I just built - given that it's my own CLI utility and all :smile:)
> New package: kaboom-0.1.0

- srcpkgs/lua-language-server/patches/fix-musl.patch
- srcpkgs/lua-language-server/patches/fix-stupid-broken-tests.patch
- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.6.24.

- srcpkgs/gcsf/template
- aarch64-musl
- armv7l
- armv6l-musl
> gcsf: update to 0.2.3.

- srcpkgs/python3-pikepdf/template
> python3-pikepdf: update to 8.2.1.

- srcpkgs/wine/patches/musl-ipx.patch
- srcpkgs/wine/template
> wine: update to 8.13.

- Manual.md
- common/environment/setup/options.sh
I didn't check this against every template where the pattern appears, but it works in the test cases I tried.
---
This helper function reduces boilerplate for [Meson's "feature" build options](https://mesonbuild.com/Build-options.html#features). Right now these are handled using the pattern `-D<property>=$(vopt_if <option> enabled disabled)`, which occurs 78 times in our templates.
Note that this does *not* allow you to set the property to "auto", but I can't think of any situation where that would be desirable.
> xbps-src: new vopt_feature helper

- srcpkgs/knot-resolver/files/kres-cache-gc/run
- srcpkgs/knot-resolver/template
In the default installation the default config file (/etc/knot-resolver/kresd.conf)  is not read: so making changes to it, did nothing.
Per https://github.com/void-linux/void-packages/blob/master/Manual.md#writing_runit_services
you _could_ change CLI flags in **conf** file in the service directory, but I think this option should be enabled by default because the file /etc/knot-resolver/kresd.conf is also installed and otherwise it's confusing.
Added working directory to kresd service file, otherwise it uses the service directory itself.
change: in default CLI variable:
```
-f 1 
```
to
```
--noninteractive
```
because _-f 1_ will be deprecated per warning on command line.
knot-resolver comes with a garbage collector (kres-cache-gc).
I added a …
> knot-resolver: config fixes + add garbage collector service

- srcpkgs/PolyMC
- srcpkgs/PrismLauncher/template
- srcpkgs/removed-packages/template
It's a year since we removed it.
Let's be honest and declare that we don't have PolyMC.
Close: #45292
> PolyMC: drop package

- srcpkgs/openssh/template
---
I currently have a use for this feature so it would be helpful if it could be built by default.
> openssh: enable gssapi build option by default

- srcpkgs/mit-krb5/template
- update changed upstream mirror
- move configure options to configure_args
- add build options
- ldap: enable LDAP database backend, enabled by default
- lmdb: enable LMDB database backend, disabled by default
- remove --without-tcl (not recognized by configure)
- remove vsed that doesn't do anything
- change sed to vsed and restrict it to files which need the changes
- remove unnecessary do_build
- aarch64-musl
- armv7l
- armv6l-musl
- x86_64-musl
> mit-krb5: update to 1.21.1

- srcpkgs/gst-plugins-ugly1/template
- srcpkgs/photofilmstrip/patches/no-img2py.patch
- srcpkgs/photofilmstrip/template
> gst-plugins-ugly1: enable GPL plugins, New package: photofilmstrip.

- srcpkgs/linux-base/files/50-bootsize.postinst
- srcpkgs/linux-base/template
<leah2> we should make a kernel install hook check that prints a big
warning if /boot is full after running it...
Thoughts:
1. Change the threshold size? Make it configurable?
2. Change the threshold to a percentage? I think that's less useful.
3. Change what package this is shipped with? I'm not sure if it applies to all configurations we support/consider.
4. Wording of the message?
> [RFC] base-files: add kernel hook for /boot freespace

- srcpkgs/cinnamon-control-center/template
- srcpkgs/cinnamon-desktop/template
- srcpkgs/cinnamon-menus/template
- srcpkgs/cinnamon-screensaver/template
- srcpkgs/cinnamon-session/template
- srcpkgs/cinnamon-settings-daemon/template
- srcpkgs/cinnamon-translations/template
- srcpkgs/cinnamon/template
- srcpkgs/cjs/patches/fb480aae4eff422c3acd275c0108e970eafcdcb9.patch
- srcpkgs/cjs/patches/ignore-encoding-test.patch
- srcpkgs/cjs/template
- srcpkgs/muffin/template
- srcpkgs/nemo-audio-tab/template
- srcpkgs/nemo-compare/template
- srcpkgs/nemo-emblems/template
- srcpkgs/nemo-extensions/template
- srcpkgs/nemo-fileroller/template
- srcpkgs/nemo-image-converter/template
- srcpkgs/nemo-preview/template
- srcpkgs/nemo-python/template
- srcpkgs/nemo-terminal/template
- srcpkgs/python3-xapp/template
- srcpkgs/xapps/template
- srcpkgs/xreader/template
- I tested the changes in this PR: **briefly** (I don't use Cinnamon but did briefly test the DE)
Testing from actual Cinnamon users would be appreciated.
> Cinnamon 5.8.x

- srcpkgs/R-cran-svglite/template
Saw the following error while using an R script:
```
> ggsave('bones_line.svg', plot=pt_line, width=24, height=12, units='cm')
Error in svglite_(filename, bg, width, height, pointsize, standalone,  :
Versión API gráfica incompatible
Calls: ggsave -> dev -> <Anonymous> -> svglite_
Ejecución interrumpida
```
Rebuilt and updated the package, and the error went away.
Not sure what triggered it. I run updates not so often, and this script less often.
> R-cran-svglite: rebuild to fix error

- common/shlibs
- srcpkgs/mimalloc-devel
- srcpkgs/mimalloc/patches/unify-library-name.patch
- srcpkgs/mimalloc/template
- srcpkgs/mold/patches/test-target-machine.patch
- srcpkgs/mold/template
- x86_64-musl
- i686-glibc
- aarch64-musl
- armv7l-glibc
- armv7l-musl
- armv6l-glibc
- armv6l-musl
Note:
- I left /usr/lib/libmimalloc.so in the main package because one of the suggested ways to use mimalloc is
`LD_PRELOAD=/usr/lib/libmimalloc.so  myprogram`
> New packages: mimalloc-2.1.2, mold-1.11.0

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.27.0.

- srcpkgs/font-inter/template
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES?**
If one would like to reduce some of the absolute pinnacle of screen specific typeface into "aesthetics", well that's under appreciating something like Inter. An absolute beast of a typeface within the space it exists. Anyone should be able to enjoy the detail and work that's gone into this typeface. Check out the website, it provides far more justice and detail as to why it exists, it's goals and strengths than I'm able to provide here.
I'd like it to be merged because:
- The insane quality this typeface offers. I'm gonna use it for GTK applications, for PDF exports through pandoc …
> New package: font-inter-3.19

- srcpkgs/font-latinmodern-math/template
- srcpkgs/font-latinmodern/template
- New package: font-latinmodern-2.004
- New package: font-latinmodern-math-1.959
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES** and **MAYBE**
I believe that `font-latinmodern-math` definitely meets package requirements, because it provides a font that allows things like MathML in browsers to render properly, without having fontconfig know about the font from texlive's dirs.
`font-latinmodern` is a maybe: it's just a version of the default text fonts from LaTeX, so I'm not sure it provides any value beyond the aesthetics.
> New packages: font-latinmodern, font-latinmodern-math

- srcpkgs/Signal-Desktop/template
- I built this PR locally for my native architecture, x86_64 (glibc)
> Signal-Desktop: update to 6.27.1.

- srcpkgs/go/template
See: https://go.dev/doc/devel/release#go1.20.7
- go1.20.7 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler
> go: update to 1.20.7.

- srcpkgs/iproute2/patches/include-limits-h.patch
- srcpkgs/iproute2/template
> iproute2: update to 6.4.0.

- srcpkgs/gobject-introspection/patches/fix-leaks.patch
- srcpkgs/gobject-introspection/template
They cause Meson's checks to fail.
Needed for #44306.
- I tested the changes in this PR: **NO** (just tested that they make Meson's tests pass)
> gobject-introspection: fix leaks.

- srcpkgs/carapace/template
> carapace: update to 0.26.0.

- srcpkgs/lvm2/template
- I tested the changes in this PR: **briefly** - my disks are all in LVM; I installed the update, rebooted, and all is still well.
- armv6l
- aarch64-musl
- x86_64-musl
I don't have the experience to update to 2.03.x, but the latest 2.02.x release seems smart.  Here are the changes: https://mirrors.kernel.org/sourceware/lvm2/WHATS_NEW-2.02
> lvm2: update to 2.02.188.

- srcpkgs/mpg123-extras/template
- srcpkgs/mpg123-extras/update
- srcpkgs/mpg123/template
- I tested the changes in this PR: **briefly** (not mpg123-extras and its subpackages though, because I couldn't find any package that depends on them)
> mpg123{,-extras}: update to 1.31.3.

- srcpkgs/babl/template
> babl: update to 0.1.106.

- srcpkgs/e16/template
libXdamage-devel was added in order to enable compositing
- x86_64
- i686
- armv6l-musl
> e16: update to 1.0.28.

- srcpkgs/fotoxx/template
> fotoxx: update to 23.60.

- srcpkgs/virglrenderer/template
Adds support for H.264 video encoding and OpenGL 4.5/Vulkan 1.2
> virglrenderer: update to 0.10.4

- srcpkgs/seatd/template
cc maintainer @ifreund (seems a pretty standard update)
> seatd: update to 0.8

- srcpkgs/osc/template
> osc: update to 1.2.0

- srcpkgs/usbredir/template
Should I orphan this package?  Its maintainer seems to not be active for a long time.
> usbredir: update to 0.13.0.

- srcpkgs/otter-browser/template
> otter-browser: update to 1.0.03.

- common/shlibs
- srcpkgs/aqbanking/template
- srcpkgs/gwenhywfar-gtk
- srcpkgs/gwenhywfar/patches/qt5-cross.patch
- srcpkgs/gwenhywfar/template
- srcpkgs/removed-packages/template
I tested this as part of the gnucash update, and everything seems to work fine. I did **not** test against the older version of gnucash, so this should only be merged after https://github.com/void-linux/void-packages/pull/43386.
Please let me know if I handled anything incorrectly with removing the `gwenhywfar-gtk` subpackage. Nothing depends on it and it's GTK2, so it should be fine to remove.
> gwenhywfar: update to 5.10.2, remove -gtk; aqbanking: update to 6.5.4

- srcpkgs/libofx/template
I tested this as part of the gnucash update, and everything seems to work. I did **not** test against the older version of gnucash, so this should only be merged after #43386.
> libofx: update to 0.10.9

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.28.0.

- srcpkgs/grafana/files/grafana/run
- srcpkgs/grafana/template
- armv6l-glibc
Grafana is on a rather old version on Void Linux - the 8 series.
Going to the 9 series has no breaking changes as far as I can see.
Going to the 10 series has some: https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v10-0/ but nothing too fancy imho.
One notable change is a new executable _grafana_ which will deprecate _grafana-cli_ **and** _grafana-server_. For now they are included all 3 for compatibility.
> grafana: update to 10.0.3

- srcpkgs/cherrytree/template
- srcpkgs/gtksourceviewmm/template
> cherrytree: update to 1.0.0; gtksourceviewmm: enable deprecated API

- srcpkgs/sandbar/template
- I tested the changes in this PR: yes, been using it for several weeks
```
#!/bin/bash
FIFO="$XDG_RUNTIME_DIR/sandbar-0"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"
while cat "$FIFO"; do :; done | sandbar -font Terminus:size=32
while true
do
echo "all status $(print_bat) $(print_date)" > $XDG_RUNTIME_DIR/sandbar-0
sleep 1
done
```
> New package: sandbar-0.1

- common/build-style/go.sh
- srcpkgs/chezmoi/template
this is still verbose (prints each module being compiled), but build logs should be more readable (for finding things like errors) now
> [RFC] common/build-style/go: use -x -> -v so go build logs are readable

- srcpkgs/wiki-tui/template
- I built this PR locally for these architectures (crossbuilds, **both glibc and musl** where possible):
- x86_64
- i686
- aarch64
- armv7l
- armv6l
*This is my first package for any distribution. I'm particularly eager to suggestions if I got anything wrong! (Specifically, I'm not sure if I needed to add compilation options, since the package allows [multiple possible ncurses-like backends](https://builditluc.github.io/wiki-tui/0.8/getting-started/installation/#cargo). I couldn't find anything about having mutually …
> New package: wiki-tui-0.8.2

- srcpkgs/chirp/template
- srcpkgs/python3-suds/template
- srcpkgs/python3-yattag/template
This PR adds CHIRP, utility for programming amateur radios, and needed python3 dependencies. This package has been requested and packaged in the past, but was rejected due to upstream not supporting python3 and was postponed until then. The software is now running well on python3.
Related: #14681, #9018, #12072
> New package: chirp and dependencies

- srcpkgs/flake8/template
Switch `distfiles` to GH due to upstream changes.
Ref: https://github.com/PyCQA/flake8/pull/1761
cc @paper42
> flake8: update to 6.1.0.

- srcpkgs/python3-cvxopt/template
> python3-cvxopt: update to 1.3.2.

- srcpkgs/singular/template
Works with sagemath. With the current version in repo (10.0_2) it gives a few doctest failures because output format changes. Not worth updating sagemath now IMO, since 10.1 will be coming out soon (if need arises, the relevant PR are https://github.com/sagemath/sage/pull/35977, https://github.com/sagemath/sage/pull/35980, https://github.com/sagemath/sage/pull/36018; also https://github.com/sagemath/sage/pull/36006 fixes a doctest after gmp 6.3.0 but it's not really necessary).
@dkwo
> singular: update to 4.3.2p7.

- srcpkgs/mu4e/template
- I tested the changes in this PR: **YES, with emacs 28.2 and very briefly with 29.1**
> mu4e: update to 1.10.6

- Manual.md
The current description might be a bit difficult to understand for new contributors due to some grammatical things that could result in it to be understood in the wrong way.
`[...] which make it necessary to quote them` somewhat could be interpreted that you actually should quote them.
The rest are just minor grammar changes.
> Manual.md: make section concerning quoting version and pkgname clearer

- srcpkgs/docker-compose/template
> docker-compose: update to 2.20.3.

- srcpkgs/less/template
> less: update to 643.

- srcpkgs/osc/template
> osc: update to 1.3.0

- srcpkgs/runc/template
> runc: update to 1.1.9.

- srcpkgs/qca-qt5/template
> qca-qt5: update to 2.3.7.

- srcpkgs/exiftool/template
> exiftool: update to 12.65.

- srcpkgs/WindowMaker/template
Updated WindowMaker to 0.96.0. It required the distfiles url, version, revision, and checksum to be changed.
> WindowMaker: update 0.96.0

- srcpkgs/tuxedo-keyboard/template
> tuxedo-keyboard: update to 3.2.10

- srcpkgs/power-profiles-daemon/files/power-profiles-daemon/run
- srcpkgs/power-profiles-daemon/template
- I built this PR locally for my native architecture, (x86_64-Glibc)
> power-profiles-daemon: add startup dependency

- srcpkgs/chirp/template
> chirp: update to 20230816

- srcpkgs/mit-krb5/template
Changes from previous release:
- Fix double-free in KDC TGS processing [CVE-2023-39975]
> mit-krb5: update to 1.21.2

- srcpkgs/google-chrome/template
- I tested the changes in this PR: **YES** (on a machine without any `qt*` packages)
---
Same as #40239, just for Qt6.
This disables rdep scanning for `libqt6_shim.so`, as does upstream:
https://chromium.googlesource.com/chromium/src/+/75f4b48eb71d4872ba3ac6c9fc3662a60eb4175d/chrome/installer/linux/BUILD.gn#106
Otherwise it pulls in `qt6-widgets`, etc.:
```
Name                Action    Version           New version            Download size
double-conversion   install   -                 3.3.0_1                31KB
libb2               install   -                 0.98.1_1               16KB
qt6-core            install   -                 6.5.0_3                2200KB
libevdev            install   -                 1.13.0_1               36KB
libwacom            install   - …
```
> google-chrome: don't depend on qt6-{core,gui,widgets}

- srcpkgs/qmk/template
```
(woods) qmk_firmware  » klardotsh/main » qmk compile -kb boardsource/unicorne -km default
Could not find module pyserial!
Would you like to install the required Python modules? [y/n] n
Please run `/usr/bin/python3 -m pip install -r /home/j/src/mine/qmk_firmware/requirements.txt` to install required python dependencies.
(woods) qmk_firmware  » klardotsh/main » qmk compile -kb boardsource/unicorne -km default
Ψ Compiling keymap with make --jobs=1 boardsource/unicorne:default
...
```
> qmk: depend on python3-pyserial

- srcpkgs/syft/template
> syft: update to 0.87.1

- srcpkgs/restic/template
> restic: update to 0.16.0.

- srcpkgs/dnscrypt-proxy/INSTALL.msg
- srcpkgs/dnscrypt-proxy/files/dnscrypt-proxy/run
- srcpkgs/dnscrypt-proxy/template
---
I'm using this as an opportunity to pick up where #34517 left off. `dnscrypt-proxy` installs all of its supplemental files (that it periodically refreshes from upstream) into the same directory as its main config file. Currently this is `/etc`, which means we get a bunch of ambiguously-named files like "relays.md" polluting that directory. This change would group all those files together, at the expense of users having to move their config files to the new location.
Other changes:
* The files previously being installed as documentation were actually examples, so they are now installed with `vsconf`.
* The `generate-domains-blocklist` python helper script is now installed.
* The log directory is no longer needed after the mass switch to …
> dnscrypt-proxy: update to 2.1.5, move config file

- srcpkgs/qutebrowser/template
We can make Qt6 a (default, when possible) build option to allow people to build Qt5 versions if desired, and also force the WebKit backend (which implies Qt5) when WebEngine is unavailable.
- I tested the changes in this PR: **briefly** (I'm using it now)
cc: @daniel-eys
> qutebrowser: update to 3.0.0, use Qt6 by default

- common/build-profiles/riscv64-musl.sh
- common/build-style/cmake.sh
- common/cross-profiles/riscv64-musl.sh
- common/environment/build-style/go.sh
- common/environment/configure/autoconf_cache/riscv64-linux
- common/environment/configure/gnu-configure-args.sh
- common/xbps-src/shutils/common.sh
- srcpkgs/go/template
- go: add riscv64
- build-style/cmake.sh: add riscv64 arch
- [WIP] add configure/autoconf_cache/riscv64-linux
- add riscv64 profiles
> xbps-src/common: add riscv64 profiles

- srcpkgs/python-dbus/template
- srcpkgs/python3-dbus
- srcpkgs/python3-dbus-devel
- srcpkgs/python3-dbus/template
> python-dbus: split python3-dbus subpackage, update python3-dbus to 1.3.2.

- srcpkgs/ecryptfs-utils-python
- srcpkgs/ecryptfs-utils/template
- srcpkgs/removed-packages/template
python2, upstream is pretty dead so no chance of py3 update
> ecryptfs-utils: remove -python subpackage

- srcpkgs/giac/patches/fix-fgamma.patch
- srcpkgs/giac/template
As reported in https://github.com/void-linux/void-packages/pull/45708#issuecomment-1688333569, including <giac/giac.h> fails in musl because the HAVE_TGAMMAF macro from autotools is not available at this time.
Here we include a patch adapted from https://github.com/geogebra/giac/commit/618a5de3349f8def5bdb909fea42fb447b6aad4a which is the solution upstream will include in next release of giac.
We need to fix this now so we can build sagemath in musl!
> giac: fix `#include <giac/giac.h>` in musl

- srcpkgs/metalog/files/metalog/run
- srcpkgs/metalog/template
This fixes issue #45653 [1].
[1]
https://github.com/void-linux/void-packages/issues/45653
> metalog: fix bleeding logs onto tty1

- srcpkgs/zstd/patches/dynamic-pzstd.patch
- srcpkgs/zstd/template
The zstd template had multiple issues:
- Since not all targets where built in do_build, compilation happened in do_install.
- Both zstd(1) and pzstd(1) statically linked libzstd.
- The libzstd.a library was meant to have multi-threading support, but was overwritten by a single-threaded version as a side-effect.
We patch pzstd to use dynamic linking and use "zstd-dll" for zstd.
In the future we may want to consider using cmake or ninja, but as it's a bootstrap package I've kept it on make.
> zstd: clean up template.

- srcpkgs/fdm/template
Most of the documentation for this program are in the plaintext MANUAL file. If we're including the examples, the MANUAL is just as helpful to have around if not more so.
> fdm: add MANUAL file.

- srcpkgs/chrony/template
tagging the maintainer @paper42 
It's just a version bump
- x86_64-musl
> chrony: update to 4.4

- srcpkgs/system-monitoring-center/template
> system-monitoring-center: update to 2.21.2

- srcpkgs/python3-pathspec/template
> python3-pathspec: update to 0.11.2.

- srcpkgs/python3-jq/template
I ran the tests but the computer that has the urlwatch config I use to test updates is offline for a while (the CPU cooked itself somehow.)
> python3-jq: update to 1.5.0

- srcpkgs/python3-trove-classifiers/template
> python3-trove-classifiers: update to 2023.8.7.

- srcpkgs/nerdctl/template
> nerdctl: update to 1.5.0.

- srcpkgs/encfs/patches/openssl-3.patch
- srcpkgs/encfs/template
> encfs: fix crash with blowfish

- .github/workflows/build.yaml
- Manual.md
- common/travis/prepare.sh
- common/travis/verify-update-check.sh
- common/travis/xlint.sh
- common/xbps-src/shutils/update_check.sh
runs update-check on all changed templates, then errors only if there was an issue with the update-check. does not error if further updates are available, as there may be a good reason not to update to those versions
example output: 
> ci: add step to verify the functionality of update-check

- srcpkgs/openntpd/patches/fix-time_t-overflow.patch
- srcpkgs/openntpd/template
- I built this PR locally for my native architecture, (i686)
On i686, `time_t` is a 32 bit integer. In `openntpd`, an addition of two `time_t`s is performed, leading to an integer overflow. This code is part of the constraints logic of openntpd. When the bug triggers, all time sources will be marked invalid.
Upstream pull request: https://github.com/openntpd-portable/openntpd-portable/pull/74
> openntpd: fix integer overflow on i686

- srcpkgs/procps-ng/template
> procps-ng: update to 4.0.4.

- srcpkgs/puzzles/template
- srcpkgs/puzzles/update
> puzzles: update to 20230909.67496e7.

- srcpkgs/xf86-input-libinput/template
> xf86-input-libinput: update to 1.4.0.

- srcpkgs/sq/patches/32-bit.patch
- srcpkgs/sq/template
> New package: sq-0.42.0

- srcpkgs/isl/template
> isl: update to 0.26.

- srcpkgs/mhash/patches/fix-cpp-bools.patch
- srcpkgs/mhash/patches/fix-tests-use-after-free.patch
- srcpkgs/mhash/template
- `x86_64-musl` (crossbuild)
- `i686` (crossbuild)
mhash uses `_Bool` directly for `#define mhash_boolean _Bool`. [musl C++ doesn't define `_Bool`](https://www.openwall.com/lists/musl/2017/07/28/1), so any C++ projects that include it will fail to build on musl. This fixes that without impacting any C projects
> mhash: make boolean usage musl C++ portable.

- srcpkgs/avfs/template
...also enable lzip support and fix avfs-devel dependencies,
I noticed the issue with the avfs-devel dependencies when packaging worker: #45807 
> avfs: update to 1.1.5.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.30.1

- srcpkgs/cargo-deny/template
> cargo-deny: update to 0.14.2.

- srcpkgs/vale/template
> vale: update to 2.28.3.

- common/shlibs
- srcpkgs/Quaternion/template
- srcpkgs/libQuotient/patches/testolmaccount.patch
- srcpkgs/libQuotient/template
- srcpkgs/neochat/patches/delegatesizehelpertest_fix.patch
- srcpkgs/neochat/patches/empty_image.source_crash.patch
- srcpkgs/neochat/template
This version of neochat requires libQuotient >=0.7, and the only versions of Quaternion that support libQuotient >=0.7 are the 0.0.96 beta versions.
neochat also requires libQuotient to be built with E2EE enabled now.
> libQuotient 0.8.1.2 and client updates

- srcpkgs/zellij/template
> zellij: update to 0.38.1

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.30.2.

- common/environment/setup/git.sh
- common/hooks/do-fetch/00-distfiles.sh
- common/xbps-src/shutils/common.sh
- common/xbps-src/shutils/cross.sh
- common/xbps-src/shutils/pkgtarget.sh
- common/xbps-src/shutils/purge_distfiles.sh
This lets xbps-src work in non-GNU environments.
> setup/git.sh: fix non-portable sed invocation

- srcpkgs/SDL2/template
@devlocalhost please test
fixes #44829
- I tested the changes in this PR: **NO** (but `-msse3` is no longer added to `EXTRA_CFLAGS` on i686)
> SDL2: fix sigill on some i686

- srcpkgs/alsa-lib/patches/fix-segfault-32bit.patch
- srcpkgs/alsa-lib/template
I did experience segfault in some programs on i686 after upgrading to 1.2.10.  This patch from upstream addresses the issue.
> alsa-lib: fix for segfault on 32-bit

- srcpkgs/libdisplay-info-devel
- srcpkgs/libdisplay-info/template
Will be used by `kwin` in the future.
closes #43888
> New package: libdisplay-info-0.1.1

- srcpkgs/lf/template
> lf: update to r31.

- srcpkgs/system-monitoring-center/template
> system-monitoring-center: update to 2.22.1

- srcpkgs/zellij/template
> zellij: update to 0.38.2

- srcpkgs/SDL2/template
> SDL2: update to 2.28.3.

- srcpkgs/go/template
> go: update to 1.21.1.

- srcpkgs/exiftool/template
> exiftool: update to 12.67.

- srcpkgs/rofi-emoji/template
> rofi-emoji: update to 3.2.0

- srcpkgs/cargo-bootstrap/template
- srcpkgs/rust-bootstrap/template
- srcpkgs/rust/template
- rust-bootstrap: update to 1.72.1
- cargo-bootstrap: update to 1.72.1
- rust: update to 1.72.1
> Rust 1.72.1

- srcpkgs/qt5-webengine/update
> qt5-webengine: ignore versions other than 5.x in update check.

- srcpkgs/mu4e/template
> mu4e: update to 1.10.7

- srcpkgs/qutebrowser/patches/fix-wayland-egl-drag-and-drop.patch
- srcpkgs/qutebrowser/template
Proper fix coming in Qt 6.5.3.
@daniel-eys
> qutebrowser: work around drag-and-drop crash on wayland-egl.

- Manual.md
- common/build-helper/meson.sh
- common/build-style/meson.sh
- common/environment/build-style/meson.sh
- srcpkgs/python3-scikit-image/template
- srcpkgs/python3-scipy/template
The `python3-scipy` package now builds with `python3-meson-python`, with some more coming down the pike. The Python build process is necessary to include Python package metadata. For SciPy, this is accomplished by using the `meson` build style to configure a build directory, then overriding `do_build` and `do_install` to build things the PEP517 way (using the pre-configured build directory).
It might be helpful to define a `meson` build helper that can write out the standard cross file for builds, allowing packages like SciPy to use the `python3-pep517` build style with the `meson` helper. There are some issues to be worked out:
1. It seems like the `xbps_meson.cross` is written before `CFLAGS`, *et al.* are properly defined, so this cross file is actually broken. (This is the process by …
> [RFC] common/build-helper/meson.sh: new build helper, used by meson build style

- srcpkgs/fbpdf/template
- srcpkgs/mupdf/template
- srcpkgs/sioyek/template
- srcpkgs/zathura-pdf-mupdf/template
Fixes: #46184
I have a pdf that cannot be loaded before / can be loaded after.
Maybe sioyek and fbpdf also have to be rebuilt.
> mupdf and zathura-mupdf-pdf: rebuild for jbig2dec

- srcpkgs/gopass-jsonapi/template
- srcpkgs/gopass/template
> gopass{,-jsonapi}: update to 1.15.8.

- srcpkgs/btrfs-progs/template
I built this PR locally for these architectures (if supported. mark crossbuilds):
> btrfs-progs: update to 6.5.1.

- srcpkgs/vale/template
> vale: update to 2.29.0.

- common/shlibs
- srcpkgs/libgdal/template
- srcpkgs/netcdf/template
- srcpkgs/pymol/template
- srcpkgs/vtk/template
> netcdf: update to 4.9.2. 

- srcpkgs/gbinder-python/template
> gbinder-python: update to 1.1.2.

- srcpkgs/grafana/template
No breaking changes compared to v10.0.3 (previous in repos).
> grafana: update to 10.1.1

- srcpkgs/dbus/template
> dbus: update to 1.14.10, adopt.

- srcpkgs/wf-recorder/template
> wf-recorder: update to 0.4.0.

- srcpkgs/nim/template
Confirmed that compiler runs and used it to compile one of my projects.
- I built this PR locally for my native architecture, (amd64-glibc)
They are still trying to pull git repos from masters during a build--even in the stable release. I've patched around this by adding the latest checkout as of today (20230816) and the Github download links for those. This gets us what appears to be a working copy but I will need to bonk the devs up there to stop doing this.
> nim: update to 2.0.0

- srcpkgs/glib/patches/gthreadedresolver-Fix-race-between-source-callbacks.patch
- srcpkgs/glib/template
- srcpkgs/glibmm2.68/template
- srcpkgs/libsigc++3/template
- libsigc++3: update to 3.4.0.
- glib: update to 2.78.0.
- glibmm2.68: update to 2.78.0.
> glib,glibmm2.68: update to 2.78.0.

- srcpkgs/ART/template
the mimalloc commit is taken from #37688, updated and fixed
cc @wangp
> ART: update to 1.20, New package: mimalloc-2.1.2

- srcpkgs/newsboat/template
> newsboat: update to 2.33

- srcpkgs/python3-ipyparallel/template
> python3-ipyparallel: enable check

- srcpkgs/maxima/template
- srcpkgs/removed-packages/template
remove the dummy package, as discussed, cc @tornaria , so we can build maxima on aarch64 without emacs.
> maxima-emacs: remove package

- common/build-helper/rust.sh
- srcpkgs/python3-jsonpointer/template
- srcpkgs/python3-jsonschema-spec/template
- srcpkgs/python3-jsonschema-specifications/template
- srcpkgs/python3-jsonschema/patches/0001-patch-out-hatch-fancy-pypi-readme.patch
- srcpkgs/python3-jsonschema/template
- srcpkgs/python3-openapi-core/template
- srcpkgs/python3-openapi-schema-validator/template
- srcpkgs/python3-openapi-spec-validator/template
- srcpkgs/python3-referencing/template
- srcpkgs/python3-rpds-py/template
> Update jsonschema and openapi related python pkgs

- srcpkgs/python3-adblock/template
- srcpkgs/python3-bcrypt/template
- srcpkgs/python3-cryptography/template
- srcpkgs/python3-mitmproxy_wireguard/template
> Refactor PYO3_CROSS_* in rust build-helper

- srcpkgs/cocogitto/template
> cocogitto: update to 5.6.0

- srcpkgs/blueprint-compiler/template
@jcgruenhage 
- aarch64-musl
- armv7l
- armv6l-musl
Newer `libadwaita` apps require the updated `blueprint-compiler` due to the new syntax in blueprints.
> blueprint-compiler: update to 0.10.0

- common/shlibs
- srcpkgs/android-studio/template
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **Not sure, template already exist** 
This PR is based on #41215
> android-studio: update to 2022.3.1.18, orphan

- srcpkgs/refind/patches/python3.patch
- srcpkgs/refind/template
@sgn
compared the output and generated files of each script before with python 2 to after with python 3, all were identical except for a missing copyright notice in the generated header file.
> refind: convert scripts to python3

- srcpkgs/cups/template
> cups: update to 2.4.7.

- srcpkgs/slack-desktop/template
> slack-desktop: update to 4.34.120

- srcpkgs/galene/files/galene/run
- srcpkgs/galene/template
I'm not 100% sure on the args format, I'd like some feedback on if we want to use arrays for service arguments.  I'd also appreciate testing on this since I typically build galene from source at `HEAD` wherever that happens to be at the time.
> New package: galene-0.7.2.

- common/shlibs
- srcpkgs/TheForceEngine/patches/musl.patch
- srcpkgs/TheForceEngine/template
- srcpkgs/furnace/template
- srcpkgs/giada/template
- srcpkgs/milkytracker/template
- srcpkgs/rtmidi/template
https://github.com/luciusDXL/TheForceEngine
* Requires `rtmidi` to get bumped to `5.0.0`, but I went ahead and bumped it to `6.0.0`. The license changed, but I think most of the other changes are features.
* I revbumped the other packages that require `rtmidi`. `milkytracker` needed `pkg-config` added to `hostmakedepends`, otherwise it would fail. I packaged all of them, but I only installed milkytracker and played around with it a little.
* 32bit seems to not be available for now for this package. According to some github issues, ARM support may be possible with some patches. I also tested musl x86_64 and it failed, but possibly would work with some patches.
* Notably during testing the shareware version of Dark Forces will not work with TheForceEngine, you must use the full game.
- I …
> New package: TheForceEngine-1.09.530

- srcpkgs/rpi-eeprom/template
- srcpkgs/rpi-firmware/template
- srcpkgs/rpi-kernel/template
- srcpkgs/rpi-userland/template
- rpi-kernel: update to 6.1.54.
- rpi-firmware: update to 20230920.
- rpi-userland: update to 20230920.
continuation of #43600, made a new PR to clean things up
builds for testing: https://devspace.voidlinux.org/abby/updates/rpi/
Still getting the DKMS/headers issue:
When building `fixdep` and `modpost` in `/etc/kernel.d/post-install/10-dkms`, it gets stuck in an infinite makefile loop:
https://github.com/void-linux/void-packages/blob/5b18878cc72b410bc076ac15218f4c5fa0c3fcbf/srcpkgs/dkms/files/kernel.d/dkms.postinst#L22-L24
```
rpi-kernel: configuring ...
Executing post-install kernel hook: 10-dkms ...
SYNC    include/config/auto.conf
HOSTCC  scripts/basic/fixdep
HOSTCC  scripts/kconfig/conf.o
HOSTCC  scripts/kconfig/confdata.o
HOSTCC …
```
> rpi-kernel: update to 6.1.54 (and rpi-firmware, rpi-userland, rpi-eeprom)

- srcpkgs/virtiofsd/template
- I tested the changes in this PR: **YES** (x86_64 glibc host, Windows 11 guest)
- I built this PR locally for these architectures (note: this package is 64-bit only):
- x86_64-musl
---
QEMU 8 dropped its `virtiofsd` in favor of the package in this PR ([ChangeLog](https://wiki.qemu.org/ChangeLog/8.0#Removed_features_and_incompatible_changes)). Just installing it fixes Virt Manager VMs with `virtiofs` shares. Since #44822 these don't power on due to:
```
Error starting domain: operation failed: Unable to find a satisfying …
```
> New package: virtiofsd-1.8.0 (QEMU regression fix)

- srcpkgs/vale/template
> vale: update to 2.29.1.

- srcpkgs/imlib2/template
This release fixes a segfault on i686 introduced in 1.12.0.
Tested with nsxiv
> imlib2: update to 1.12.1.

- srcpkgs/duperemove/patches/add_dev_t_include.patch
- srcpkgs/duperemove/template
I have switched the template to `gnu-makefile` build style. The makefile looks well behaved regarding environmental variables, so I have set `make_use_env`. Hash files generated with the older release (most likely) won't be compatible with the new release. This is to be expected, the manpage and documentation say that the hash file format isn't stable.
ping mainainer: @Gottox
> duperemove: update to 0.13.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 6.32.0.

- srcpkgs/dkms/files/dkms.default
- srcpkgs/dkms/files/kernel.d/dkms.postinst
- srcpkgs/dkms/template
- srcpkgs/linux6.1/template
- srcpkgs/linux6.3/template
- srcpkgs/linux6.5/template
- srcpkgs/xbps-triggers/files/dkms
- srcpkgs/xbps-triggers/template
- dkms: allow limiting jobs, add missing dep
- some less-powerful platforms may be overwhelmed by the default `-j$(nproc)`. Allow overriding this by setting `DKMS_JOBS` in `/etc/default/dkms`
- `bc` is needed for `make prepare0` on kernel 6.1+, which is run on cross.
- see also: https://github.com/void-linux/void-packages/pull/46152#issuecomment-1741479613
- linux6.1: include files necessary for dkms on cross
- linux6.5: include files necessary for dkms on cross
The same fix could be applied to linux6.3 and linux6.4, but with the impending zfs 2.1.13 bump (#46304), I don't see much point.
fixes #44807
- I tested the changes in this PR: **YES** (tested in an aarch64-musl VM on 6.3 with several dkms modules)
@moabeat-berlin, @r-ricci, @Calandracas606: please test
[ci skip]
> cross-built kernel/dkms improvements

- srcpkgs/adguardian/template
- aarch64-musl
- armv7l
- armv6l-musl
> adguardian: update to 1.6.0

- srcpkgs/Clipboard/template
> Clipboard: update to 0.8.2, orphan

- srcpkgs/gzdoom/template
Addendum:
Hey guys !
Just a pull request to update GZdoom to its latest release.
I added `libwebp-devel` as a make dependency as it makes an error without it, it is a new requirement since this release.
That's about it tho, have a nice day ! 👋
> gzdoom: update to version 4.11.0.

- srcpkgs/tuigreet/template
It's needed for `--remember*` options
> tuigreet: add /var/cache/tuigreet to make_dirs

- srcpkgs/labwc/template
> labwc: update to 0.6.5
