void-linux/void-packages

srcpkgs/got/template
- I built this PR locally for my native architecture, (amd64-musl)
for this time I've left gotd out.  I'd like to revisit it in the future, but I need to see how the alternatives works to provide a gotsh-backed `git-{upload,receive}-pack`.
=> got: update to 0.93.

srcpkgs/gocryptfs/template
go-fuse supports both `fusermount` and `fusermount3` ([relevant code](https://github.com/hanwen/go-fuse/blob/22567ce3f39cc9dd6b30249282227d4c41f9a193/fuse/mount_linux.go#L248))
Tested by adding `ignorepkg=fuse` to xbps.conf, removing it and mounting a directory with `gocryptfs`.
=> gocryptfs: switch dependency to fuse3

srcpkgs/routinator/template
- aarch64-musl
- armv7l
- armv6l-musl
- x86_64-musl
=> routinator: update to 0.13.0

srcpkgs/nerd-fonts-symbols-ttf, srcpkgs/nerd-fonts/template
cc maintainer @cinerea0, interested party @chrysos349
- "gets rid of the bloat", if the user desires to only have the symbol font
- doesn't break existing installs (`-ttf` depends on `-symbols-ttf` to preserve continuity best, doesn't enable the fontconfig conf by default, doesn't remove other patched nerd-fonts)
- doesn't create more maintainer burden by having 2 templates
=> nerd-fonts: split symbols font

srcpkgs/tuxedo-keyboard/template
=> tuxedo-keyboard: update to 3.2.11

srcpkgs/linux-lts/template, srcpkgs/linux/template
linux:
linux-lts:
- 6.1 is the [latest lts branch](https://kernel.org)
=> linux: update to 6.5, linux-lts: update to 6.1.

srcpkgs/python3-cairocffi/template, srcpkgs/python3-pywlroots-0.16/template, srcpkgs/python3-pywlroots-0.16/update, srcpkgs/python3-xcffib/template, srcpkgs/qtile/INSTALL.msg, srcpkgs/qtile/template
- I tested the changes in this PR: **YES**, expect the Wayland part since I run X11.
=> qtile: update to 0.23.0, python3-xcffib: update to 1.5.0, python3-cairocffi: update to 1.6.1 and new package: python3-pywlroots-0.16-0.16.5

srcpkgs/fotoxx/template
=> fotoxx: update to 23.70.

srcpkgs/VeraCrypt/template
```
pkg        host         target        cross  result
VeraCrypt  x86_64       x86_64        n      OK
VeraCrypt  x86_64-musl  x86_64-musl   n      OK
VeraCrypt  i686         i686          n      OK
VeraCrypt  x86_64       aarch64-musl  y      OK
VeraCrypt  x86_64       aarch64       y      OK
VeraCrypt  x86_64       armv7l-musl   y      OK
VeraCrypt  x86_64       armv7l        y      OK
VeraCrypt  x86_64       armv6l-musl   y      OK
VeraCrypt  x86_64       armv6l        y      OK
```
=> VeraCrypt: update to 1.25.9.

srcpkgs/tor/template
zstd is autodetected, configure_args not necessary
=> tor: update to 0.4.8.7.

srcpkgs/blender/template
=> blender: update to 3.6.4.

srcpkgs/xdg-desktop-portal/files/portals.conf, srcpkgs/xdg-desktop-portal/template
Without this, `xdg-desktop-portal` cannot do anything as of 1.18.0. DEs and WMs should probably ship their own if they want to use a specific frontend, but this should be good enough for now.
This conf file is put in the lowest precedence location, and generic `portals.conf` is overriden if `XDG_CURRENT_DESKTOP-portals.conf` is found, so this should be fairly safe.
Additionally, this `portals.conf` does not require any specific frontend, just the special value `*`, which means the first one found in lexicographical order.
See [portals.conf(5)](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst) for more details. This manpage is also installed now by adding `python3-docutils` to `hostmakedepends`.
fixes #46317
=> xdg-desktop-portal: include a default portals.conf

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.33.0.

srcpkgs/aardvark-dns/template, srcpkgs/netavark/template
- netavark: update to 1.8.0.
- aardvark-dns: update to 1.8.0.
=> netavark: update to 1.8.0, aardvark-dns: update to 1.8.0.

srcpkgs/pdfcpu/template
```
pkg      host         target        cross  result
pdfcpu   x86_64       x86_64        n      OK
pdfcpu   x86_64-musl  x86_64-musl   n      OK
pdfcpu   i686         i686          n      OK
pdfcpu   x86_64       aarch64-musl  y      OK
pdfcpu   x86_64       aarch64       y      OK
pdfcpu   x86_64       armv7l-musl   y      OK
pdfcpu   x86_64       armv7l        y      OK
pdfcpu   x86_64       armv6l-musl   y      OK
pdfcpu   x86_64       armv6l        y      OK
```
=> New package: pdfcpu-0.5.0

srcpkgs/pinktrace/template, srcpkgs/sydbox/patches/missing-include.patch, srcpkgs/sydbox/template
- pinktrace: use python3
- sydbox: update to 2.2.0.
cc maintainer @thypon
=> pinktrace, sydbox: use python 3

srcpkgs/ncurses/template
fixes #42007
- I tested the changes in this PR: **briefly** (generated package seems to be correct)
=> ncurses: reënable libtinfo 32bit pkgs

srcpkgs/freedroidRPG/template
=> freedroidRPG: update to 1.0.

srcpkgs/trollock/template, srcpkgs/xtrlock/template
cc @thypon @leahneukirchen
tested: builds
=> xtrlock, trollock: work around ancient python configure script

srcpkgs/mc/files/README.voidlinux, srcpkgs/mc/patches/extfs-python3.patch, srcpkgs/mc/template
Takes care of python2 scripts, and documents what packages are needed for each "extfs" backend script.
It is impossible to test the s3 backend without an AWS S3 account, but the patch is used in other distros.
=> mc: update to 4.8.29, cleanup, adopt.

srcpkgs/libcue/patches/fdf72c8bded8d24cfa0608b8e97f2eed210a920e.patch, srcpkgs/libcue/template, srcpkgs/tracker-miners/template, srcpkgs/tracker/template
See here for more details: https://github.blog/2023-10-09-coordinated-disclosure-1-click-rce-on-gnome-cve-2023-43641/
The public example file only tests libcue, so that was all I could test, but the tracker update should also fix the sandbox escape issue.
=> Update tracker and libcue for CVE-2023-43641.

srcpkgs/aerc/patches/makefile-only-install.patch, srcpkgs/aerc/template
=> aerc: update to 0.16.0.

srcpkgs/power-profiles-daemon/template
@oreo639 
Fixes the following warning, that spams the log:
```
daemon.notice: Oct  8 17:58:12 power-profiles-daemon: ** (power-profiles-daemon:833): WARNING **: 17:58:12.124: Could not save configuration file '/var/lib/power-profiles-daemon/state.ini': Failed to create file ?/var/lib/power-profiles-daemon/state.ini.AKGIC2?: No such file or directory
```
=> power-profiles-daemon: create /var/lib/power-profiles-daemon

srcpkgs/python3-Cython/patches/5690.patch, srcpkgs/python3-Cython/patches/5725.patch, srcpkgs/python3-Cython/template
https://github.com/cython/cython/pull/5690
https://github.com/cython/cython/pull/5725
Both are merged in cython 3.0.3, however that release breaks scipy.
The memory leak was detected due to 3 doctest failures in sagemath (when built with cython 3) and this PR fixes it.
The debug output issue symptom is that sagemath can't be built unless one sets `SAGE_DEBUG=no` (however, this only triggers when `python3-lxml` is installed).
cc: @ahesford
=> python3-Cython: fix memory leak + debug output for generators

srcpkgs/tecla/template
depends on: #46507
will be necessary for GNOME 45
=> New package: tecla-45.0

srcpkgs/gallery-dl/template
Was just bumping the macports port and was going to do this anyway so I though I'd submit the PR for it.
=> gallery-dl: update to 1.26.0.

srcpkgs/puzzles/template
=> puzzles: update to 20231010.2d9e414.

srcpkgs/pnpm/template
=> pnpm: update to 8.9.0.

srcpkgs/python3-pikepdf/template
Fixes a new test failure with python 3.12, among other things.
=> python3-pikepdf: update to 8.5.1.

srcpkgs/deja-dup/template, srcpkgs/duplicity/template
The duplicity update shoudl fix #46572, and I updated deja-dup while I was at it. The current version of deja-dup fails 41 tests and passes 16, but the new version fails 39 and passes 19.
I don't use either of these and can't meaningfully test them.
cc: @dkwo @Johnnynator 
=> duplicity, deja-dup: update

srcpkgs/libuecc/template
Only a minor edit of the template file is included in this pull request.
=> libuecc: use SPDX identifier for license

srcpkgs/hikari/patches/restack_xwayland_windows.patch, srcpkgs/hikari/template
hikari currently doesn't restack xwayland windows when a new one is focused, which can cause dialog boxes in xwayland applications to not accept mouse input. this patch comes from [a fork of hikari](https://hub.darcs.net/holycow/hikari/patch/de3817572a6c3ba5b51614fe31151d2c63fe1fd4), and it seems that unfortunately [the origin repo](https://hub.darcs.net/raichoo/hikari/changes) isn't quite updated anymore. [I've reported it there as well nonetheless](https://hub.darcs.net/raichoo/hikari/issue/48)
=> hikari: add xwayland restacking patch, adopt

srcpkgs/tuxpaint/template
- `maketuxfont.py` is impossible to easily port to python 3 because there is no equivalent to `string.letters` (set of all letters, locale-dependent). It is also probably not very useful in the modern era; it was created in 2005 when a "more then 13 MB" font file was considered huge.
- `mkTuxpaintIM.py` seems to be just for updating documentation (so probably not useful for users ever)
@Chocimier
=> tuxpaint: remove python 2 scripts

common/hooks/post-install/80-prepare-32bit.sh
=> common/hooks/post-install/80-prepare-32bit.sh: use dot to reference directory content instead of wildcard

srcpkgs/anki/patches/fix_distutils_not_found.patch, srcpkgs/anki/template
=> anki: fix 'distutils' not found in Python 3.12

common/wrappers/cross-cc
=> wrappers/cross-cc: drop -isystem /usr/include, too

srcpkgs/gcc6/template, srcpkgs/pdftk/template
- I tested the changes in this PR: **YES** (built revdeps)
this will require removing `*gcc6*` from the main repos after merge
=> gcc6: remove python 2 scripts, move to bootstrap

common/build-style/cmake.sh, srcpkgs/VirtualGL/template, srcpkgs/kodi-platform/template, srcpkgs/libjpeg-turbo/template
specifying the full path in INSTALL_LIBDIR will result in it being
hardcoded in the Targets-none.cmake instead of being repalce with
_IMPORT_PREFIX
=> libjpeg-turbo: ensure that libjpeg-turboTargets-none.cmake is relocatable

srcpkgs/vale/template
=> vale: update to 2.29.4.

srcpkgs/rsClock/template
=> rsClock: update to 0.1.10.

srcpkgs/vscode/template
I had to add python3-pip, because the installation failed otherwise, since distutils could not be found.
=> vscode: update to 1.83.1

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.34.0.

srcpkgs/bats/template
=> bats: update to 1.10.0.

srcpkgs/hplip/patches/python312.patch, srcpkgs/hplip/template
Fixes: #46684.
This does not suppress syntax warnings, which are not a behavior change from prior Python versions. (The warnings are just more vocal.)
=> hplip: update to 3.23.8.

srcpkgs/variety/patches/Jumble_importlib_3.12_fix.patch, srcpkgs/variety/template
`imp` is no longer available so I had to patch it to use `importlib`.
=> variety: patch to fix for Python 3.12.

srcpkgs/godot/template
It's a minor change that makes debugging and reporting issues for our package easier.
Instead of ".custom_build" the suffix is ".voidlinux".
=> godot: add correct build name

srcpkgs/maxima/patches/use-shared-library.patch, srcpkgs/maxima/template
This is the default for aarch64.
Rework the patch `use-shared-library.patch` so the ecl binaries work as built, no need to use `patchelf` anymore. This way there should be no problem if maxima is needed to build the documentation.
OTOH, the documentation is currently shipped in the tarball, so we touch the correct files so that it won't be rebuilt.
This won't change the binary package, no need to revbump.
Cc: @dkwo 
Fixes: #46293
=> maxima: fix build with -o ~sbcl

srcpkgs/python3-httplib2/template
@ahesford the previously failing test is now passing (at least locally on `x86_64`).
=> python3-httplib2: update to 0.22.0

srcpkgs/system-monitoring-center/template
=> system-monitoring-center: update to 2.25.0

srcpkgs/exiftool/template
=> exiftool: update to 12.68.

srcpkgs/connman/INSTALL.msg, srcpkgs/connman/template
Allows using `iwd` instead of `wpa_supplicant` for wireless connections.
=> connman: build with iwd support

srcpkgs/bitcoin/template, srcpkgs/bitcoin/update
Also changes update to point to bitcoincore.org, as that is the most regularly updated source of binaries/source code.
=> bitcoin: update to 25.1

srcpkgs/salt/patches/requirements.patch, srcpkgs/salt/template
Update to fix `contextvars` version issue again.  See https://github.com/saltstack/salt/issues/60483 and https://github.com/void-linux/void-packages/pull/33331
This also adds a couple dependencies I found.
Salt runs now but I am having problems with connectivity between the master and minions.  I am not sure if it's caused by the upgrade or not.
=> salt: update dependencies

srcpkgs/ymir/template
This is a void-centric tool for large bulk package builds. I've used it to do `build_style=cargo` rebuilds for Rust PRs.
Disclaimer: I am the author of this project.
=> New package: ymir-0.0.5

srcpkgs/go/template
- I built this PR locally for my native architecture, (amd64)
- armv7l
- aarch64
- i686
Changes, see https://go.dev/doc/devel/release#go1.21.minor
- go1.21.2 (released 2023-10-05) includes one security fixes to the cmd/go package, as well as bug fixes to the compiler, the go command, the linker, the runtime, and the runtime/metrics package. See the [Go 1.21.2 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.21.2+label%3ACherryPickApproved) on our issue tracker for details.
- go1.21.3 (released 2023-10-10) includes a security fix to the net/http package. See the [Go 1.21.3 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.21.3+label%3A …
=> go: update to 1.21.3.

srcpkgs/python3-dbus-next/template
- I built this PR locally for my native architecture, x86_64.
- armv6l
closes #46495
=> New package: python3-dbus-next-0.2.3

srcpkgs/python3-argcomplete/template
Seems to include some kind of Python 3.12 fix (https://github.com/kislyuk/argcomplete/pull/448).
=> python3-argcomplete: update to 3.1.2.

srcpkgs/postgresql14/template
I think this change will resolve the failing tests in https://github.com/void-linux/void-packages/pull/45532
=> postgresql14: Fix postgresql14-libs-devel dependencies

srcpkgs/nginx/template, srcpkgs/openssl/template
- tested nginx with the new openssl version and confirmed ktls works
- still testing openssl itself (seems fine, only thing in the changelog affects windows)
cc @duncaen (nginx maintainer), @Johnnynator (openssl maintainer)
=> openssl: update to 3.1.3.

srcpkgs/fotoxx/template
=> fotoxx: update to 23.72.

srcpkgs/lazydocker/template
=> lazydocker: update to 0.23.1.

srcpkgs/xfsprogs/template
=> xfsprogs: update to 6.5.0.

srcpkgs/libnotify/template
>This release contains a critical stability/minor security update which affects
Electron applications that utilize Portal notifications (eg, through Flatpak).
It is highly recommended that all users of libnotify 0.8.x update to this
release.
=> libnotify: update to 0.8.3.

srcpkgs/python3-pyasn1/template
=> python3-pyasn1: update to 0.5.0.

srcpkgs/containerd/template
=> containerd: update to 1.7.8, adopt.

srcpkgs/exiftool/template
=> exiftool: update to 12.69.

srcpkgs/lighttpd/template
lighttpd: update to 1.4.73
I tested the changes in this PR: NO
(build-tested elsewhere: on openwrt)
=> lighttpd: update to 1.4.73

srcpkgs/fuse3/template
=> fuse3: update to 3.16.2, adopt.

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.37.0.

srcpkgs/bCNC/template, srcpkgs/python3-shxparser/template, srcpkgs/python3-svgelements/patches/fix_assert.patch, srcpkgs/python3-svgelements/template
- I built this PR locally for my native architecture, (x86_64_glibc)
- python3-shxparser
- python3-svgelements
=> Update: bCNC to 0.9.15, add  python3-shxparser-0.0.2, python3-svgelements-1.9.6 as dependency

srcpkgs/spicy/template, srcpkgs/zeek/template
```
pkg      host         target        cross  result
spicy    x86_64       x86_64        n      OK
zeek     x86_64       x86_64        n      OK
spicy    x86_64-musl  x86_64-musl   n      OK
zeek     x86_64-musl  x86_64-musl   n      OK
spicy    i686         i686          n      OK
zeek     i686         i686          n      OK
spicy    x86_64       aarch64-musl  y      OK
zeek     x86_64       aarch64-musl  y      OK
spicy    x86_64       aarch64       y      OK
zeek     x86_64       aarch64       y      OK
spicy    x86_64       armv7l-musl   y      OK
zeek     x86_64       armv7l-musl   y      OK
spicy    x86_64       armv7l        y      OK
zeek     x86_64       armv7l        y      OK
spicy    x86_64       armv6l-musl   y      OK
zeek …
```
=> zeek: update to 6.1.0.

srcpkgs/python3-Cython/template
=> python3-Cython: update to 3.0.5.

srcpkgs/python3-pyasn1-modules/template
=> python3-pyasn1-modules: update to 0.3.0.

srcpkgs/ghostscript/template
- I tested the changes in this PR: **NO**, will get around to it
=> ghostscript: update to 10.02.1.

srcpkgs/opensmtpd-filter-rspamd/template
- I built this PR locally for my native architecture, (amd64-musl)
This brings in a rather important IMHO security fix: it's possible to crash filter-rspamd by attempting to log in as a user with a "|" character in it.  Doing so will also quit opensmtpd since it dies once a filter exits.
Furthermore, this update will also be needed for the next opensmtpd version since it'll bump the protocol version.
I haven't actually run this on void linux, but I'm using it on other systems and the [diff is quite small](https://github.com/poolpOrg/filter-rspamd/compare/v0.1.7...v0.1.8), I don't expect actual breakages.
(edit: I've mailed the maintainer since I don't know their github account)
=> opensmtpd-filter-rspamd: update to 0.1.8

common/shlibs, srcpkgs/ImageMagick/template, srcpkgs/blender/template, srcpkgs/darktable/template, srcpkgs/gimp/template, srcpkgs/gmic/template, srcpkgs/hugin/template, srcpkgs/kimageformats/template, srcpkgs/kio-extras/template, srcpkgs/krita/template, srcpkgs/libgdal/template, srcpkgs/libjxl/template, srcpkgs/opencv/template, srcpkgs/openexr/template, srcpkgs/openimageio/template, srcpkgs/swayimg/template, srcpkgs/synfig/template, srcpkgs/synfigstudio/template, srcpkgs/vigra/template, srcpkgs/vips/template
-  Cross build - aarch64
Disabling the tests for *-musl (https://github.com/AcademySoftwareFoundation/openexr/issues/1556)
Currently failing, because this templates are broken: 
<details>
<summary>Build Status</summary>
```
SUMMARY
pkg            host    target  cross  result
openexr        x86_64  x86_64  n      OK
ImageMagick    x86_64  x86_64  n      OK
gimp           x86_64  x86_64  n      OK
opencv         x86_64  x86_64  n      OK
synfig         x86_64  x86_64  n      OK
libjxl         x86_64  x86_64  n      OK
vigra          x86_64  x86_64  n      OK
gmic           x86_64  x86_64  n      OK
openimageio    x86_64  x86_64  n      OK
vips           x86_64  x86_64  n      OK …
```
=> openexr: update to 3.2.1.

srcpkgs/python3-contourpy/template, srcpkgs/python3-cycler/template, srcpkgs/python3-matplotlib/INSTALL.msg, srcpkgs/python3-matplotlib/template
Also included here a couple of dependencies:
- python3-cycler: update to 0.12.1.
- python3-contourpy: update to 1.2.0, adopt.
=> python3-matplotlib: update to 3.8.1.

srcpkgs/schilytools/template
also clean up template and move siconv tables back into cdrtools, as they are only used there
- I tested the changes in this PR: **YES** (on aarch64-musl)
=> schilytools: fix cross

srcpkgs/rio/template
=> rio: update to 0.0.27

srcpkgs/zellij/template
=> zellij: update to 0.39.0

srcpkgs/fotoxx/template
=> fotoxx: update to 23.74.

srcpkgs/android-udev-rules/template
=> android-udev-rules: update to 20231104.

srcpkgs/python3-zope.interface/template
=> python3-zope.interface: update to 6.1.

srcpkgs/python3-typing_extensions/template
=> python3-typing_extensions: update to 4.8.0, adopt.

srcpkgs/python3-pyserial/template
=> python3-pyserial: update to 3.5.

srcpkgs/fbpdf/template, srcpkgs/mupdf/template, srcpkgs/sioyek/patches/mupdf-1.23.patch, srcpkgs/sioyek/template, srcpkgs/zathura-pdf-mupdf/template
=> mupdf: update to 1.23.4.

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.38.0.

srcpkgs/swirc/template
=> swirc: update to 3.4.6.

srcpkgs/surfraw/template
=> surfraw: fix dead distfiles

srcpkgs/libqalculate/template, srcpkgs/qalculate-gtk/template, srcpkgs/qalculate-qt/template
- `x86_64-musl`
[the previous maintainer](https://github.com/ashpool37) has not contributed to void [in two years](https://github.com/void-linux/void-packages/pulls?q=is%3Apr+author%3Aashpool37+), and I actively use this software, so I feel keen on maintaining it for the forseeable future
=> qalculate: update to 4.8.1, adopt.

srcpkgs/zellij/template
=> zellij: update to 0.39.1

srcpkgs/go/template
- I built this PR locally for my native architecture, (amd64)
- armv7l
- i686
- aarch64
=> go: update to 1.21.4.

srcpkgs/vlc/template
vlc: update to 3.0.19
- I tested the changes in this PR: **YES** -- vlc runs and I can confirm that FLAC playback is fixed (the main reason I sought this update)
=> vlc: update to 3.0.19.

srcpkgs/python3-openssl/template
=> python3-openssl: update to 23.3.0.

srcpkgs/qmk/template
QMK requirements: https://github.com/qmk/qmk_firmware/blob/ca4541699915b37cd1f253bbed51854627efd2ce/requirements.txt#L13
=> qmk: depend on python3-Pillow

srcpkgs/syncplay/patches/python3-12-compatibility.patch, srcpkgs/syncplay/template
Since Void Linux now uses Python 3.12 as default, Syncplay broke. This backports the fix to make it work under Python 3.12.
Source: https://github.com/Syncplay/syncplay/pull/636
=> syncplay: backport fix for Python 3.12 support

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.39.0.

srcpkgs/mkinitcpio/template
=> mkinitcpio: add zstd dependency

srcpkgs/gzdoom/patches/pk3location.patch, srcpkgs/gzdoom/template
Hey everyone!
This PR focuses on updating GZDoom, to v4.11.3, but it also brings a patch to fix gzdoom not being able to find pk3 files.
=> gzdoom: update to version 4.11.3 + patch fixing missing pk3files.

srcpkgs/neomutt/template
=> neomutt: update to 20231023

srcpkgs/gajim/template, srcpkgs/python3-nbxmpp/template
=> gajim: update to 1.8.3.

srcpkgs/exiftool/template
=> exiftool: update to 12.70.

srcpkgs/python3-pikepdf/template
=> python3-pikepdf: update to 8.7.1.

srcpkgs/docker-buildx/template
=> docker-buildx: update to 0.12.0.

srcpkgs/python3-stevedore/template
Fixes subliminal on python3.12
=> python3-stevedore: update to 5.1.0.

srcpkgs/zfs/template
Adds linux6.6 support, disables block cloning by default until the issues are fixed. It would be a good idea to get this merged quickly.
- I tested the changes in this PR: **YES** (zfs on root with zfsbootmenu, linux6.1, pool fully upgraded, x86_64-glibc)
cc: @Vaelatern @zdykstra
=> zfs: update to 2.2.1.

srcpkgs/python3-Levenshtein/template, srcpkgs/python3-rapidfuzz/template, srcpkgs/python3-scikit-build/patches/patch-out-hatch-fancy-pypi-readme.patch, srcpkgs/python3-scikit-build/template, srcpkgs/rapidfuzz-cpp/template
fixes #46581
fixes #46545
- armv7l x
=> python3-Levenshtein: update to 0.23.0

srcpkgs/waydroid/template
=> waydroid: update to 1.4.2.

srcpkgs/python3-ffmpeg-python/patches/remove-future.patch, srcpkgs/python3-ffmpeg-python/template
```
pkg                    host         target        cross  result
python3-ffmpeg-python  x86_64       x86_64        n      OK
python3-ffmpeg-python  x86_64-musl  x86_64-musl   n      OK
python3-ffmpeg-python  i686         i686          n      OK
python3-ffmpeg-python  x86_64       aarch64-musl  y      OK
python3-ffmpeg-python  x86_64       aarch64       y      OK
python3-ffmpeg-python  x86_64       armv7l-musl   y      OK
python3-ffmpeg-python  x86_64       armv7l        y      OK
python3-ffmpeg-python  x86_64       armv6l-musl   y      OK
python3-ffmpeg-python  x86_64       armv6l        y      OK
```
This fixes `ytmdl`.
=> python3-ffmpeg-python: fix for py3.12

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.39.1.

common/shlibs
Found when testing wlroots 0.17
cc @Johnnynator
=> libdisplay-info: add missing shlib

.gitignore, README.md, common/xbps-src/shutils/chroot.sh
When packages in `hostdir/binpkgs` are signed, it causes `xbps-src` to annoyingly request to import the associated key (every time, in the case of automation tools like `xxbuild` or `ymir`). This allows the user to add their personal public key `.plist` to `etc/repo-keys/` so this prompting does not happen.
=> common/xbps-src/shutils/chroot.sh: support importing other keys

srcpkgs/backblaze-b2/patches/tqdm_ver.patch, srcpkgs/backblaze-b2/template
Allows package to build with newer version of tqdm in void-packages. Upstream has a dependabot pull that passed all their tests, but is not merged yet.
Closes #47348
=> Backblaze-b2: Patch TQDM version

srcpkgs/zfs-lts/patches/default-zfs_dmu_offset_next_sync-to-off.patch, srcpkgs/zfs-lts/template, srcpkgs/zfs/patches/default-zfs_dmu_offset_next_sync-to-off.patch, srcpkgs/zfs/template
While OpenZFS tracks down providing files with a surplus of zeros, we should disable a relevant tunable by default that mitigates the damage.
=> zfs/zfs-lts: please do not eat my data

common/build-helper/rust.sh
libgit2 upstream: https://github.com/rust-lang/git2-rs/commit/59a81cac9ada22b5ea6ca2841f5bd1229f1dd659
libsqlite3 upstream: https://github.com/rusqlite/rusqlite/commit/b4604f2421315040133717f48f616200e10507a8
Neither crates has a release since inclusion of these overrides so don't know what the testing strategy here. Probably one or two packages will have broken builds which needs the respective `-devel` packages in the `makedepends`.
=> common/build-helper/rust.sh: link to libgit2 and libsqlite3 dynamically

srcpkgs/libjpeg-turbo/template
=> libjpeg-turbo: update to 3.0.1.

srcpkgs/elfutils/template
=> elfutils: update to 0.190.

common/build-helper/rust.sh
Some rust pacakges (e.g. eza and bat) do set strip = true
in their release profile which removes the debug symbols
before xbps-src can split them.
closes #47459
=> build-helper/rust.sh: prevent stripping by cargo

srcpkgs/rio/template
=> rio: update to 0.0.28

srcpkgs/zellij/template
=> zellij: update to 0.39.2

srcpkgs/libblockdev/template
=> libblockdev: update to 3.0.4.

srcpkgs/awsume/template, srcpkgs/python3-boto3/template, srcpkgs/python3-botocore/template
Note: awsume test requires, update for both `python3-boto3` and `python3-botocore`
=> awsume: fix tests ; python3-boto3: update to1.29.6, fix tests ; python3-botocore: update to 1.32.6 

srcpkgs/runc/template
=> runc: update to 1.1.10.

srcpkgs/reuse/template
- Switched to `pep517`
- Removed dependency `setuptools`
- All tests are passing
=> reuse: update to 2.1.0, fix tests

srcpkgs/spotify-adblock/template
=> spotify-adblock: upgrade to 1.0.3

srcpkgs/buildah/template, srcpkgs/cni-plugins/template, srcpkgs/conmon/template, srcpkgs/containers-common/template, srcpkgs/containers.image/template, srcpkgs/containers.storage/template, srcpkgs/fuse-overlayfs/template, srcpkgs/podman/template, srcpkgs/runc/template, srcpkgs/slirp4netns/template
- runc: update to 1.1.10
- conmon: update to 2.1.8
- cni-plugins: update to 1.3.0
- fuse-overlayfs: update to 1.13
- slirp4netns: update to 1.2.2
- containers.image: update to 5.28.0
- containers.storage: update to 1.50.2
- containers-common: update to 0.56.0
- podman: update to 4.7.2
- buildah: update to 1.32.2
=> podman, buildah, and containers-dependency updates

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.40.0.

srcpkgs/python3-Cython/template
I've been testing this with #46832 (sagemath 10.2 rc) without issues.
=> python3-Cython: update to 3.0.6.

srcpkgs/aardvark-dns/template, srcpkgs/netavark/template
- netavark: update to 1.9.0.
- aardvark-dns: update to 1.9.0.
=> netavark: update to 1.9.0, aardvark-dns: update to 1.9.0.

srcpkgs/osc/template
=> osc: update to 1.5.0

srcpkgs/libxml2/template
=> libxml2: update to 2.12.1.

srcpkgs/linux-firmware/template
The next tagged version of linux-firmware can do away with `rdfind` and `which` as makedepends - https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/log/copy-firmware.sh .
=> linux-firmware: update to 20231111.

srcpkgs/gajim/template, srcpkgs/python3-nbxmpp/template
Also updated `python3-nbxmpp` to 4.5.3
=> gajim: update to 1.8.4.

srcpkgs/lapack/template
=> lapack: update to 3.12.0.

srcpkgs/labwc/template
=> labwc: update to 0.6.6

srcpkgs/libgusb/template
- I tested the changes in this PR:**briefly**
=> libgusb: update to 0.4.8.

srcpkgs/flashrom/template
- aarch64-musl
- armv7l
- armv6l-musl
=> flashrom: update to 1.3.0.

srcpkgs/dooble/template
=> dooble: update to 2023.11.30 migrate to qt6

srcpkgs/platformio/template, srcpkgs/python3-ajsonrpc/template, srcpkgs/python3-starlette/template, srcpkgs/python3-uvicorn/template
This is a rather large PR which updates `platformio` to the latest version and adds new python3 modules as dependencies.
=> platformio: update to 6.1.1, adopt, add new dependencies

srcpkgs/tor/template, srcpkgs/torsocks/template
- tor: update to 0.4.8.9.
- torsocks: depends on tor, adopt.
Enable Proof of Work DoS mitigation module, this needs `--enable-gpl`.
More information here: https://blog.torproject.org/introducing-proof-of-work-defense-for-onion-services/
Also make `torsocks` depend on `tor` and not the other way round.
=> tor: update to 0.4.8.9, torsocks: depends on tor, adopt.

srcpkgs/python3-ansible-compat/template, srcpkgs/python3-ansible-lint/template
- x86_64-musl
- i686
@jcgruenhage are you okay with this? This skips your PR and also updates lint to the latest version.
=> Python3 Ansible: lint 6.22.1 and compat 4.1.10 update to newest versions.

srcpkgs/mu4e/template
=> mu4e: update to 1.10.8

srcpkgs/python3-cairo/template
=> python3-cairo: update to 1.25.1.

srcpkgs/libopenal/template
=> libopenal: update to 1.23.1.

srcpkgs/python3-pulsectl-asyncio/template
Required by built in optional widget [PulseVolume](https://docs.qtile.org/en/latest/manual/ref/widgets.html#pulsevolume) in [Qtile](https://github.com/void-linux/void-packages/blob/master/srcpkgs/qtile/template)
=> New package: python3-pulsectl-asyncio-1.1.1

srcpkgs/yggdrasil/INSTALL.msg, srcpkgs/yggdrasil/template
Yggdrasil is now on v0.5, a breaking change from v0.4.
https://yggdrasil-network.github.io/2023/10/22/upcoming-v05-release.html
=> yggdrasil: update to 0.5.2.

srcpkgs/acr/template
Tagging the maintainer @fnogcps 
It's just a version bump
- x86_64-musl
=> acr: update to 2.1.2

srcpkgs/android-udev-rules/template
=> android-udev-rules: update to 20231124.

srcpkgs/fish-shell/template
- x86_64-musl
fixes [CVE-2023-49284](https://github.com/fish-shell/fish-shell/security/advisories/GHSA-2j9r-pm96-wp4f)
=> fish-shell: update to 3.6.3.

srcpkgs/e2fsprogs/template
=> e2fsprogs: use awk with compile_et

srcpkgs/rustypaste/template
=> rustypaste: update to 0.14.2.

srcpkgs/android-studio/template
=> android-studio: update to 2023.1.1.26.

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.41.0.

srcpkgs/ccache/template
=> ccache: update to 4.8.3, add more compiler symlinks

srcpkgs/curl/template, srcpkgs/libpsl/template, srcpkgs/public-suffix/template
=> curl: enable libpsl+libidn2; libpsl: switch from icu to libidn2, allow external public-suffix-list

srcpkgs/go/template
- I built this PR locally for my native architecture, (amd64)
- i686
- armv7l
- aarch64
--------------------------------------------
go1.21.5 (released 2023-12-05) includes security fixes to the go command, and the `net/http` and `path/filepath` packages, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/rand, net, os, and syscall packages. See the [Go 1.21.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.21.5+label%3ACherryPickApproved) on our issue tracker for details.
See: https://go.dev/doc/devel/release#go1.21.minor
=> go: update to 1.21.5.

srcpkgs/android-udev-rules/template
=> android-udev-rules: update to 20231207.

srcpkgs/godot/template
- I tested the changes in this PR: **YES** (As far as I could think of)
- x86_64-musl
- i686
Since we provide icu and brotli now in correct versions I've setup godot to use our packages instead of builtin variants.
=> godot: update to 4.2.1.

srcpkgs/python3-immutabledict/template, srcpkgs/synapse/template
=> synapse: update to 1.98.0.

srcpkgs/qpdf/template
=> qpdf: update to 11.6.4. Move cmake files to libqpdf-devel

srcpkgs/pnpm/template
=> pnpm: update to 8.12.0.

common/shlibs, srcpkgs/calibre/patches/python-3.12.patch, srcpkgs/calibre/template, srcpkgs/horizon/template, srcpkgs/krename/patches/podofo-0.10.patch, srcpkgs/krename/template, srcpkgs/libpodofo0.9.7-devel, srcpkgs/libpodofo0.9.7/template, srcpkgs/podofo/template, srcpkgs/scribus/template
- I tested the changes in this PR: **YES** (only calibre)
=> Calibre update to 7.1.0

srcpkgs/transmission/template
=> transmission: update to 4.0.5, adopt.

srcpkgs/yggdrasil/template
=> yggdrasil: update to 0.5.4.

srcpkgs/font-iosevka/template
- I built this PR locally for my native architecture, (x86_64-gblic)
=> font-iosevka: update to 28.0.0.

srcpkgs/eclib/template
Tested with sagemath in #47712.
=> eclib: update to 20231212.

srcpkgs/python3-pikepdf/template
=> python3-pikepdf: update to 8.10.0.

srcpkgs/python3-typing_extensions/template
=> python3-typing_extensions: update to 4.9.0.

srcpkgs/zenity/template
=> zenity: update to 3.44.2.

srcpkgs/python3-charset-normalizer/template
=> python3-charset-normalizer: update to 3.3.2.

srcpkgs/python3-wcmatch/template
=> python3-wcmatch: update to 8.5.

srcpkgs/gallery-dl/template
=> gallery-dl: update to 1.26.4.

srcpkgs/python3-future/template
=> python3-future: update to 0.18.3, adopt

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.42.0.

srcpkgs/watchexec/template
=> watchexec: update to 1.24.1

srcpkgs/font-iosevka/template
=> font-iosevka: update to 28.0.1.

common/shlibs, srcpkgs/OTPClient/template, srcpkgs/libcotp/template
OTPClient needs to be rebuilt, since the internal API in libcotp has changed, hence the revision bump.
=> libcotp: update to 3.0.0

srcpkgs/spectrwm/template
I built this PR locally for my native architecture, (x86_64-glibc)
=> spectrwm: update to 3.5.1, orphan

srcpkgs/senpai/template
The repository has been moved, as https://git.sr.ht/~taiite/senpai/tree/5e771831a3196f49d4417e0f913da64a251e8cb5/item/README.md shows.
@realcharmer
=> senpai: update homepage and distfiles URL.

srcpkgs/girara/template, srcpkgs/zathura-cb/template, srcpkgs/zathura-djvu/template, srcpkgs/zathura-pdf-mupdf/template, srcpkgs/zathura-pdf-poppler/template, srcpkgs/zathura-ps/template, srcpkgs/zathura/template
---
I noticed past zathura updates did not require revbumps for the support plugins, but when I tried to load a pdf prior to the revbumps I got a "symbol not found" error.
=> zathura: update to 0.5.4; revbump support plugins

srcpkgs/rclone/template
`mime-types` is used by Go's `mime.TypeByExtension`. A test fails without it.
=> rclone: update to 1.65.0.

srcpkgs/carapace/template
=> carapace: update to 0.28.5.

srcpkgs/python3-urwidgets/template, srcpkgs/toot/template
- New package: python3-urwidgets-0.1.1.
- toot: update to 0.39.0.
=> toot: update to 0.39.0

srcpkgs/osc/template
=> osc: update to 1.5.1

srcpkgs/rpi-imager/template
=> rpi-imager: update to 1.8.3.

srcpkgs/python3-regex/template
=> python3-regex: update to 2023.10.3.

srcpkgs/fish-shell/template
=> fish-shell: update to 3.6.4.

srcpkgs/libheif/template
=> libheif: update to 1.17.5.

srcpkgs/python3-txtorcon/template
=> python3-txtorcon: update to 23.11.0.

srcpkgs/libwacom/template
=> libwacom: update to 2.9.0.

srcpkgs/kvantum/patches/lib32.patch, srcpkgs/kvantum/template
Allows kvantum to handle qt5 and qt6 themes under qt5ct and qt6ct.
Their install guide says to 'disable' qt5 but it works fine for both.
Switches build to cmake over qmake
https://github.com/tsujan/Kvantum/blob/master/Kvantum/INSTALL.md#with-cmake
=> kvantum: update to 1.0.10.

srcpkgs/linux/template
we can probably do this now. zfs-2.2.2 supports 6.6, and i think nvidia is supported too (@abenson?)
=> linux: update to 6.6.

srcpkgs/android-file-transfer-linux/template
android-file-transfer-linux doesn't depend on its icons, which can be confusing if someone doesn't have them. This is not a problem when the user is running Kde, but if someone (like me) is using aft "standalone", `qt5-svg` doesn't get pulled.
=> android-file-transfer-linux: Add missing dependency

srcpkgs/base-files/template
Multilib on Void is [already only supported on glibc](https://docs.voidlinux.org/xbps/repositories/index.html#subrepositories) and as per the musl libc FAQ [there is no ldconfig](https://wiki.musl-libc.org/faq.html) (`/bin/ldconfig: symbolic link to true`).
=> base-files: don't include lib32 files for musl

srcpkgs/python3-ipython/patches/fix-sagemath-prompt.patch, srcpkgs/python3-ipython/template
@ahesford nasty bug in ipython that makes (interactive) sagemath unusable.
See: https://github.com/ipython/ipython/pull/14223#issuecomment-1869776898
=> python3-ipython: fix sagemath prompt

srcpkgs/wt/template
Fixes https://github.com/epoupon/lms/issues/384
- I built this PR locally for my native architecture, (x86_64-glib)
=> wt: add build dependencies

srcpkgs/busybox/template
The upgrade to 2.38 brought a very sad performance regression in sagemath:
```
$ time python -c 'from sage.graphs.generators.distance_regular import DoubleGrassmannGraph; print(DoubleGrassmannGraph(2,2))'
<string>:1: UserWarning: Resolving lazy import GF during startup
<string>:1: UserWarning: Resolving lazy import VectorSpace during startup
Double Grassmann graph (5, 2, 2)
real	0m30.101s
user	0m29.959s
sys	0m0.060s
```
while the same thing in 2.36 (or after this PR) takes ~ 1-2 seconds.
Thanks to @oreo639 for figuring out it was https://sourceware.org/bugzilla/show_bug.cgi?id=30723
Indeed, all the performance regressions I was seeing are gone now.
=> [ci skip] glibc: fix memalign performance regression

srcpkgs/llvm12/patches/llvm-gcc13.patch
No revbump since this just adds a missing include.
=> llvm12: fix build for gcc13

srcpkgs/python3-imagesize/template, srcpkgs/python3-snowballstemmer/template, srcpkgs/python3-sphinx-automodapi/template, srcpkgs/python3-sphinxcontrib-serializinghtml/template
tarball from github is lacking the version
needed for setup tools. The module was crashing
immediately since it was unable to source the version.
=> python3-sphinx-automodapi: update to 0.16.0, fix runtime crash.

srcpkgs/gcc/patches/fix-pretty-printer-warnings.patch, srcpkgs/gcc/template
Every time a C++ program is debugged under gdb, the following message is printed:
```
/usr/lib/../share/gcc-12.2.0/python/libstdcxx/v6/printers.py:1201: SyntaxWarning: invalid escape sequence '\d'
self.typename = re.sub('^std::experimental::fundamentals_v\d::', 'std::experimental::', self.typename, 1)
/usr/lib/../share/gcc-12.2.0/python/libstdcxx/v6/printers.py:1219: SyntaxWarning: invalid escape sequence '\w'
mgrname = re.sub("std::string(?!\w)", str(gdb.lookup_type('std::string').strip_typedefs()), m.group(1))
/usr/lib/../share/gcc-12.2.0/python/libstdcxx/v6/printers.py:1249: SyntaxWarning: invalid escape sequence '\d'
self.typename = re.sub('^std::(experimental::|)(fundamentals_v\d::|)(.*)', r'std::\1\3<%s>' % valtype, typename, 1) …
```
=> libstdc++: Fix pretty printer warnings

srcpkgs/gcc/patches/d7bead833631486e337e541e692d9b4a1ca14edd.patch, srcpkgs/gcc/template
[ci skip]
This fixes compiling with glibc 2.38+. crypt.h was used for getting the size of `struct crypt_data` in the crypt interceptor. The interceptor has since been removed in LLVM and gcc upstreams. This just backports the patch for gcc 12.
Revbump since this changes the behavior of sanitizers.
=> gcc: remove crypt interceptor for sanitizers

srcpkgs/composer8.1/template, srcpkgs/composer8.2/template, srcpkgs/composer8.3/files/composer8.3, srcpkgs/composer8.3/template, srcpkgs/php/template, srcpkgs/xdebug8.1/template, srcpkgs/xdebug8.2/template, srcpkgs/xdebug8.3/files/README.voidlinux, srcpkgs/xdebug8.3/template, srcpkgs/xdebug8.3/update
- composer8.1: update to 2.6.6.
- composer8.2: update to 2.6.6.
- New package: composer8.3-2.6.6
- xdebug8.1: update to 3.3.1.
- xdebug8.2: update to 3.3.1.
- New package: xdebug8.3-3.3.1
- php: update to 8.3.
=> update xdebug and composer and add PHP 8.3 packages

srcpkgs/google-chrome/template, srcpkgs/google-chrome/update
Update `google-chrome` to latest stable version.
This also updates the site and pattern used to check for new releases as omahaproxy.appspot.com has been shut down. There is no replacement for the CSV release history, instead the recommendation [here](https://groups.google.com/a/chromium.org/g/chromium-dev/c/uH-nFrOLWtE/m/PhUj_inyAQAJ) is to use Google's version history API to get the released version data in JSON form.
=> google-chrome: update to 120.0.6099.129.

srcpkgs/perl/template
Fixes build for https://github.com/void-linux/void-packages/pull/47977
=> perl: depends on libxcrypt-devel

common/environment/setup/sourcepkg.sh
Easy way to reproduce: `./xbps-src show-build-deps xyz | cat` which should not print colors, in fact prints colors.
=> xbps-src: fix NOCOLORS

srcpkgs/allegro5/template
Currently, running an allegro5 application with a system using pipwire as a replacement for pulseaudio results in all applications not being able to output audio with `snd_pcm_avail after recover: Broken pipe`. Enabling pulseaudio fixed this issue for me.
You can test this using the `opensurge` which uses allegro5. As soon as you open the application, no applications (including opensurge) will be able to output audio until opensurge is closed.
=> allegro5: enable pulseaudio support and fix audio in pipewire

srcpkgs/postgrest/template
Newer versions depend on newer GHC than we have.
cc @Anachron
closing #23118
=> New package: postgrest-10.2.0

srcpkgs/glibc/template
if a partial upgrade occurs that includes glibc but not libxcrypt, libcrypt.so.1 will disappear and things like PAM will fail to work. This is only solvable by chrooting in and downgrading glibc or installing libxcrypt.
- I tested the changes in this PR: **NO** (currently away from other systems I can test on)
=> glibc: depend on libxcrypt to ensure partial upgrades work

srcpkgs/wstunnel/patches/build-on-1.74.patch, srcpkgs/wstunnel/patches/fix-test.patch, srcpkgs/wstunnel/template
=> wstunnel: update to 8.5.4

srcpkgs/php8.1/files/apache.conf, srcpkgs/php8.1/template, srcpkgs/php8.2/files/apache.conf, srcpkgs/php8.2/template, srcpkgs/php8.3/files/apache.conf, srcpkgs/php8.3/template
=> php-apache: fix module name

common/shlibs, srcpkgs/libxcrypt/template
this fixes the dependency cycle when installing e.g. `base-system` on an empty root:
```
$ mkdir /tmp/testroot
$ xbps-install -SdR https://repo-default.voidlinux.org/current -r /tmp/testroot base-system
...
[DEBUG] Error checking glibc>=2.36_1 for rundeps: Too many levels of symbolic links
[DEBUG] Error checking libxcrypt-compat>=0 for rundeps: Too many levels of symbolic links
...
```
After this change, there should be no special user intervention needed or error to resolve.
- I tested the changes in this PR: **YES** (on both systems with glibc 2.36 and empty roots)
=> libxcrypt: noverifyrdeps on libxcrypt-compat to prevent a cycle

srcpkgs/openblas/template, srcpkgs/python3-numpy/template
Tested with sagemath
- with our current binary package 10.2_1 (run testsuite without recompilation)
- with the draft PR for 10.3.beta4 in #47712
@ahesford this should be ready to go once CI on #47712 passes.
=> openblas: update to 0.3.26, numpy: update to 1.26.3

srcpkgs/python-tkinter/template
Like python3-tkinter, python-tkinter no longer builds/pkgs correctly since the libxcrypt separation
- I built this PR locally for these architectures (crossbuild)
- aarch64
- i686
- riscv64
=>  python-tkinter: glibc build requires libxcrypt-devel

srcpkgs/libsasl/template
disable rm'd applications that depend on crypt()
The `cyrus-sasl` package was updated to use libxcrypt-devel, however here, the application that depends on it isn't needed so just disable it, along with some other rm'd applications.
=> libsasl: fix build with glibc 2.38

common/xbps-src/shutils/build_dependencies.sh, common/xbps-src/shutils/common.sh, xbps-src
~~This PR adds a new config variable `XBPS_FORCE_COLORS`, which overrides the "is this not a tty" and `NO_COLOR` checks, and adds it to config entries for CI.~~
**EDIT** Github has changed the way CI is run; xbps-src now thinks it is running in a terminal and prints with colour. This part of the PR has been removed.
The `msg_normal()` colour is changed from "bold" (`1`) to "bright white, bold" (`97`, `1`) since Github workflows render `1` as bold letters of the current colour. This should have no effect on the vast majority of terminals setups, as `1` is already rendered as bright white with or without bolded font.
I also setup [a demo](https://github.com/0x5c/void-packages/pull/4/checks) on my fork.
=> Fix xbps-src colours in CI

common/shlibs, srcpkgs/boxed-cpp/template, srcpkgs/contour-shell-integration, srcpkgs/contour-terminfo, srcpkgs/contour/patches/0000-phtread_musl.patch, srcpkgs/contour/template, srcpkgs/guidelines-support-library/template, srcpkgs/libunicode-devel, srcpkgs/libunicode/template
Fixes #34513
~~`libunicode` provides a tool, currently packaged in `-devel`, should it be somewhere else? It's a simple tool that provides info on characters passed as argument.~~ With feedback, the tool is now left in the main package.
~~I'm also not a fan of the way I have to download the Unicode UCD archive manually. The `linunicode` build system tries to do it, but it fails locally in xbps-src.~~ While having it as a distfile is still a but annoying, it's way less clunky.
=> New package: contour-0.4.0.6245

srcpkgs/ferium/template
- I tested the changes in this PR: **briefly**.
Apologies for the quick revision, but I only realized after the merge that the package compiles with the GUI `xdg-desktop-portal` integration by default, which results in an inability to change some options through the TUI interface on systems without `xdg-desktop-portal`. This commit opts to make the `nogui` option the default and provide a build option for the GUI integration instead.
=> ferium: don't use portal-based gui

srcpkgs/jmol/template
The main change here is to depend on java-runtime instead of java-environment.
=> jmol: update to 16.1.47, fix dep.

srcpkgs/openjdk-common/files/java.sh, srcpkgs/openjdk-common/files/profile.sh, srcpkgs/openjdk-common/template
adds /usr/bin/java script to bridge the gap between fully profile-based and fully /usr/bin symlinks
=> openjdk-common: update to 2.

srcpkgs/profanity/template
Fixes the following error when running `/omemo qrcode`:
```
This version of Profanity has not been built with libqrencode
```
=> profanity: Add qrcode support

srcpkgs/file-roller/patches/fix-symlink-handling-7zip.patch, srcpkgs/file-roller/template
p7zip and 7zip use different flags for link handling options, which causes errors in file-roller which assumes 7z is p7zip.
This fixes so that 'follow symlinks' works when enabled, and does not follow symlinks when the option is disabled.
Currently it follows symlinks when the option is disabled and errors when the option is enabled.
=> file-roller: fix for inconsistencies between p7zip and 7zip

srcpkgs/llvm15/patches/compiler-rt-sanitizer-nocrypt.patch, srcpkgs/llvm15/patches/libcxx-gcc13.patch, srcpkgs/llvm15/patches/libomp-gcc13.patch, srcpkgs/llvm15/template
[ci skip]
This fixes compiling with glibc 2.38+. crypt.h was used for getting the size of `struct crypt_data` in the crypt interceptor. The interceptor has since been removed in LLVM and gcc upstreams.
Revbump since this changes the behavior of sanitizers and modifies a public libc++ header.
=> llvm15: remove crypt interceptor for sanitizers and fix build with gcc13

srcpkgs/i3status-rust/template
Update the version of `i3status-rust`
- I built this PR locally for my native architecture, amd64/x86_64-libc
- `xbps-src -Q pkg i3status-rust` completes with no errors
Glad to update anything else if needed!
=> i3status-rust: update to 0.32.3

srcpkgs/blackbox_exporter/template
Same version flag fix as https://github.com/void-linux/void-packages/pull/47935 .
=> blackbox_exporter: update to 0.24.0.

common/xbps-src/shutils/show.sh, srcpkgs/bcachefs-tools/template, srcpkgs/python3-QtPy/template, srcpkgs/python3-google-api-python-client/template, srcpkgs/qgis/template
Split up from #47888 to avoid long CI in that PR.
This fixes dependencies in four packages and also fixes handling of `*-32bit` deps.
Before this change:
```
$ for p in bcachefs-tools brother-dcp197c-lpr gcc-multilib nvidia nvidia470 python3-QtPy python3-google-api-python-client qgis ; do ./xbps-src show-build-deps -K $p > /dev/null; done
=> ERROR: bcachefs-tools-1.3.6_1: dependency 'libudev-devel' does not exist!
=> ERROR: brother-dcp197c-lpr-1.1.3_6: dependency 'glibc-32bit' does not exist!
=> ERROR: gcc-multilib-12.2.0_2: dependency 'glibc-32bit' does not exist!
=> ERROR: nvidia-535.146.02_1: dependency 'glibc-32bit' does not exist!
=> ERROR: nvidia470-470.223.02_1: dependency 'glibc-32bit' does not exist!
=> ERROR: python3-QtPy-2.4.1_1: dependency 'font-liberation-ttf' does not exist! …
```
=> Fix dependencies so show-build-deps won't fail 

srcpkgs/ucspi-tcp6/template
=> ucspi-tcp6: provide ucspi-tcp for tinyssh and twoftpd

srcpkgs/Signal-Desktop/template
=> signal-desktop: update to 6.43.1

srcpkgs/factor/template
- I tested the changes in this PR: **briefly** - CLI runs basic factor programs, GUI does as well and allows debugging.
Note: I also switched homepage/distfiles to https, which is now supported upstream, and moved `nostrip_files` after `checksum` per the warning from `xlint`.
---
Update notes: https://re.factorcode.org/2023/08/factor-0-99-now-available.html
=> factor: update to 0.99.

srcpkgs/alacritty/template
=> alacritty: update to 0.13.1

srcpkgs/libwacom/template
`libwacom-devel-2.9.0` requires `libevdev-devel` as a dependency.
`mutter` which  depends on `libwacom-devel` fails to build and spits out this error:
```
meson.build:284:17: ERROR: Dependency lookup for libwacom with method 'pkgconfig' failed: Could not generate cflags for libwacom:
Package libevdev was not found in the pkg-config search path.
Perhaps you should add the directory containing `libevdev.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libevdev', required by 'libwacom', not found
```
=> libwacom: add missing dep for -devel subpkg

srcpkgs/bats-assert/template, srcpkgs/bats-support/template
without this, there are errors like this when running a bats test suite that needs these modules:
```
Could not find library 'bats-assert' relative to test file or in BATS_LIB_PATH
Could not find library 'bats-support' relative to test file or in BATS_LIB_PATH
```
@ahesford 
=> bats-*: install in bats search path

srcpkgs/OTPClient/template
=> OTPClient: update to 3.3.0

srcpkgs/iso-codes/template
=> iso-codes: update to 4.16.0.

srcpkgs/python3-janus/template
Tested locally on x86_64-glibc. All tests pass. Also briefly tested dependent pantalaimon and didn't find any issues. Tests passed.
=> python3-janus: update to 1.0.0.

srcpkgs/meson/template
- I built this PR locally for my native architecture, **x86_64**, **i686**
need this and [libdrm-2.4.119](https://github.com/void-linux/void-packages/pull/48170) for mesa-24 soonish
@SpidFightFR fyi
=> meson: update to 1.3.1

srcpkgs/brother-brscan5/INSTALL, srcpkgs/brother-brscan5/REMOVE, srcpkgs/brother-brscan5/files/README.voidlinux, srcpkgs/brother-brscan5/template
Using a Brother ADS-1200 scanner over USB. I did not test the `brsaneconfig5` utility nor IP scanning.
EDIT: Someone else tested part of the network functionality (see https://github.com/void-linux/void-packages/pull/44235#issuecomment-1694736834).
=> New package: brother-brscan5-1.2.13

srcpkgs/dust/template
=> dust: update to 0.9.0.

srcpkgs/github-cli/template
=> github-cli: update to 2.42.1

common/environment/setup/archive.sh
Extract archive in the destination directory instead of the source directory.
=> setup/archive: fix extraction of non-tar gz/bz2/xz/zst archives

srcpkgs/Signal-Desktop/template
=> signal-desktop: update to 6.44.1

srcpkgs/python3-process-tests/patches/fix-test.patch, srcpkgs/python3-process-tests/template
~Second commit should not be merged, it's only to trigger check of `python3-pytest-cov` for CI.~
=> python3-process-tests: update to 3.0.0.

common/build-style/python3-module.sh, common/build-style/python3-pep517.sh, srcpkgs/python3-keyring/template
Python packages which enables pytest's `--doctest-modules` flag fails while testing against an installed package - ref. https://github.com/pytest-dev/pytest/issues/2042#issuecomment-381309723. Currently it's worked around in `python3-keyring` & `python3-fpylll` but is needed for `python3-path`, `python3-inflect`, `python3-zipp` etc - basically anything that follows https://github.com/jaraco/skeleton and there's quite a few of those in our repos.
=> common/build-style/python3-{module,pep517}.sh: enable `PY_IGNORE_IMPORTMISMATCH` for testing

srcpkgs/miniserve/template
=> miniserve: update to 0.26.0.

srcpkgs/ffmpeg/patches/binutils-2.41.patch, srcpkgs/ffmpeg/template
=> ffmpeg: fix building with binutils 2.41

srcpkgs/vala/template
Update to fix buffer overflow crash when building NetworkManager.
See: https://gitlab.gnome.org/GNOME/vala/-/issues/1485
=> vala: update to 0.56.14.

srcpkgs/perl-IO-Compress-Brotli/patches/no-bundled-brotli.patch, srcpkgs/perl-IO-Compress-Brotli/template
- `x86_64-musl`
- `i686-glibc`
noticed that this package is required for viewing jpeg xl brotli-compressed exif data using `exiftool`
I include the `no-bundled-brotli.patch` from [fedora](https://src.fedoraproject.org/rpms/perl-IO-Compress-Brotli/blob/rawhide/f/IO-Compress-Brotli-0.004001-Use-pkgconfig-instead-of-bundled-libbrotli.patch) since the old bundled brotli has a security vulnerability
=> New package: perl-IO-Compress-Brotli-0.004001

README.md, srcpkgs/xbps/patches/xbps-src-comp.patch, srcpkgs/xbps/template, xbps-src
- default masterdir naming now includes the host `XBPS_ARCH`, e.g. `masterdir-x86_64`
- setting the host `XBPS_ARCH` can be done with `-A <arch>`
- This will create a new masterdir per host arch automatically
- using an arbitrary masterdir is still supported via `-m <masterdir>`, and overrides whatever `-A` would set
- the invocation of `[binary-]bootstrap` no longer (ab)uses `$XBPS_TARGET_PKG` for setting the masterdir's host architecture
*default:*
```
$ ./xbps-src binary-bootstrap
$ ls
... masterdir ...
```
*nondefault masterdir:*
```
$ ./xbps-src -m masterdir-idk binary-bootstrap
$ ls
... masterdir-idk ...
```
*specific host arch:*
```
$ ./xbps-src -m masterdir-musl binary-bootstrap x86_64-musl
$ ls
... masterdir-musl ...
```
*cross with …
=> [RFC] xbps-src: add -A flag for host arch, create masterdir per host arch

srcpkgs/newsboat/template
=> newsboat: update to 2.34

srcpkgs/rz-ghidra/template
Rebuild `rz-ghidra` to support the latest `cutter` release in the repositories, built against `qt6`. Currently, `cutter` fails to load the Ghidra plugin because it's being built against `qt5`.
=> rz-ghidra: rebuild for qt6

srcpkgs/astroid/patches/attachements.patch, srcpkgs/astroid/template
This update is applying a non-release upstream patch to prevent crashes while adding attachments.
See astroidmail/astroid/issues/726 for more information.
- I built this PR locally for my native architecture, (x68_64-glibc)
=> astroid: apply upstream patch to prevent crashes while adding attachments

srcpkgs/rsClock/template
=> rsClock: update to 0.1.11.

srcpkgs/wlroots0.15/template, srcpkgs/wlroots0.16/template, srcpkgs/wlroots0.17/template
=> wlroots: reduce the maintanance burden on future release

srcpkgs/fuzzel/template
=> fuzzel: adopt

srcpkgs/libsass/template
=> libsass: update to 3.6.6.

srcpkgs/python3-keyring/template
=> python3-keyring: update to 24.3.0.

srcpkgs/batsignal/template
Tested on x86_64-glibc - dell P5520
=> batsignal: update to 1.8.0

srcpkgs/python3-fpylll/template
=> python3-fpylll: update to 0.6.1.

srcpkgs/prometheus/template
The current package of Prometheus in the repos has missing version information. Pointing Version flags to github.com/prometheus/common sets things correctly:
```
prometheus, version 2.48.1 (branch: 2.48.1, revision: 2.48.1)
build user:       VoidLinux
build date:       20231228-02:47:53
go version:       go1.21.5
platform:         linux/amd64
tags:             netgo,builtinassets
```
=> prometheus: update to 2.49.0.

srcpkgs/vale/template
=> vale: update to 3.0.5.

srcpkgs/zathura/patches/0001-The-function-file_valid_extension-should-return-True.patch, srcpkgs/zathura/template
Without this patch, it is not possible to use completion for zathura's
`:open` command as it will only list files which zathura cannot open and
exclude all other, instead of doing it the other way around.
---
=> zathura: add patch to fix valid file detection

srcpkgs/lziprecover/template
=> lziprecover: update to 1.24.

srcpkgs/lcms2/template
Plugins were enabled in https://github.com/void-linux/void-packages/commit/b9b9189c8a7c6f2e8e600958dbc298b7c69c7417
The plugins get linked to applications (`dlopen()` is not used). However they were not added to `common/shlibs` causing packages to link against the plugins but error due to the shlibs not having an associated package.
The plugins don't have a soversion, however, as this is inconsistent between configuring with autoconf vs meson, I assume this is a mistake. As such, disable until the following is addressed: https://github.com/mm2/Little-CMS/issues/432
Fixes building gimp, Krita, libraw, etc.
cc: @sgn
=> lcms2: disable plugins for now

srcpkgs/babashka/template, srcpkgs/jet/template, srcpkgs/mandrel/template
One `babashka` test fail, couldn't figure out why exactly.
=> mandrel: update to 23.1.2.0.

srcpkgs/SuiteSparse/template, srcpkgs/python3-cvxopt/template
I built and checked `octave` and `python3-cvxopt` on top of this (#47887 would be nice to do this on CI as well).
While doing this I discovered building cvxopt is broken on i686, so I fixed it. It just happens that suitesparse moved header files in 7.4.0 to `/usr/include/suitesparse` and cvxopt figures this out for 64 bit but not for 32 bit). No need to rebuild cvxopt since our current binary is fine (it was last built with suitesparse 7.3.1).
=> SuiteSparse: update to 7.6.0.

srcpkgs/docker-buildx/template
=> docker-buildx: update to 0.12.1.

srcpkgs/python3-pytest-aiohttp/template, srcpkgs/python3-pytest-timeout/template
=> pytest-aiohttp and pytest-timeout updates

srcpkgs/shared-mime-info/template
`Warning: program compiled against libxml 212 using older 211` was getting printed on every invocation of `update-mime-database` during both `xbps` and `flatpak` commands.
Test: `update-mime-database /usr/share/mime`
=> shared-mime-info: rebuild to hide libxml warning

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.45.1.

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.46.0.

srcpkgs/etckeeper/template
- I built this PR locally for my native architecture, (`x86_64-musl`)
A couple of tests fail, likely due to `fakeroot` or similar.
=> etckeeper: update to 1.18.21, support xbps, run tests

srcpkgs/virtiofsd/template
- I tested the changes in this PR: **YES** (Windows 11 guest)
=> virtiofsd: update to 1.10.1

common/environment/configure/hardening.sh
=> environment/configure/hardening.sh: fix copy-paste error with nopie=yes

srcpkgs/texlive/patches/relax-zlib-version-check.patch, srcpkgs/texlive/template
Bump for `zlib-1.3.1`: 
```bash
lualatex
```
```
PANIC: unprotected error in call to Lua API (zlib library version does not match - header: 1.3, library: 1.3.1)
```
=> texlive: rebuild vor zlib-1.3.1

srcpkgs/gogglesmm/template
=> gogglesmm: update to 1.2.5

srcpkgs/runc/template
=> runc: update to 1.1.12

srcpkgs/python3-natsort/template
@autrimpo 
the version in the repo is too old (5 years old). newer apps require the current version.
- armv7l x
=> python3-natsort: update to 8.4.0, adopt

srcpkgs/python3-aioresponses/template, srcpkgs/python3-matrix-nio/template, srcpkgs/python3-urwid_readline/template, srcpkgs/python3-zulip/template, srcpkgs/zulip-term/template
=> New package: zulip-term-0.7.0

common/build-style/texmf.sh, common/environment/build-style/texmf.sh, common/environment/build-style/texmf/ownership.txt, srcpkgs/texlive-basic/template, srcpkgs/texlive-bibtexextra/template, srcpkgs/texlive-core/template, srcpkgs/texlive-fontsextra/template, srcpkgs/texlive-formatsextra/template, srcpkgs/texlive-full/template, srcpkgs/texlive-games/template, srcpkgs/texlive-humanities/template, srcpkgs/texlive-lang/template, srcpkgs/texlive-langchinese/template, srcpkgs/texlive-langcyrillic/template, srcpkgs/texlive-langextra/template, srcpkgs/texlive-langgreek/template, srcpkgs/texlive-langjapanese/template, srcpkgs/texlive-langkorean/template, srcpkgs/texlive-latexextra/template, srcpkgs/texlive-minimal/template, srcpkgs/texlive-most/template, srcpkgs/texlive-music/template, srcpkgs/texlive-pictures/template, srcpkgs/texlive-pstricks/template, srcpkgs/texlive-publishers/template, srcpkgs/texlive-science/template, srcpkgs/texlive/files/remove-himktables.patch, srcpkgs/texlive/patches/luajit-arch-fixes.patch, srcpkgs/texlive/patches/tlmgr.patch, srcpkgs/texlive/template
<strike>A few consideration's I'm 100% sure about.
1. I'm not certain about our current ownerships - a lot of things from `texmf-dist` come from the texlive package, whereas most other distributions appear to have the primary texlive package as compiled binaries-only and then place all the `texmf-dist` binaries symlinked to scripts in their texlive-core package (obviously different names but same idea). Should we be doing this?
2. What do I do about the ppc64 patches, should they be dropped or left?</strike>
*all considered now*
=> Texlive 2023

srcpkgs/gramps/patches/1411.patch, srcpkgs/gramps/template
Patch Gramps with https://github.com/gramps-project/gramps/pull/1411 to allow imports to work when running with Python 3.12.
=> gramps: Replace deprecated imp by importlib

srcpkgs/lutris/template
=> lutris: update to 0.5.16

srcpkgs/python3-openssl/template
=> python3-openssl: update to 24.0.0

srcpkgs/libgit2/template
A security patch release while #45976 is in progress
=> libgit2: update to 1.6.5

srcpkgs/incus/template
First contribution, be aware. Simple version update.
Running this on an incus/lxc server established with the prior version (4.0); no issues noted. 
- I built this PR locally for my native architecture, (x86-64 glibc)
- I built this PR locally (with -Q) for these architectures (if supported. mark crossbuilds):
- aarch64-musl
- armv7l
- armv6l-musl
=> incus: update to 0.5.1

srcpkgs/tectonic/template
=> tectonic: update to 0.15.0.

srcpkgs/libusb/template
=> libusb: update to 1.0.27.

srcpkgs/swayimg/template
- armv6l-musl
This PR also solves `swayimg --version` showing `0.0.0`. ~~Could some more experienced maintainer provide a way of solving this issue without a patch? Would using `sed` be preferred?~~
=> swayimg: update to 2.1.

srcpkgs/caddy/template
=> caddy: update to 2.7.6.

srcpkgs/ol/patches/http.patch, srcpkgs/ol/patches/ppcxx.patch, srcpkgs/ol/patches/xxd.patch, srcpkgs/ol/template
- I built and tested this PR locally for my native architecture, **x86_64**
- I built and tested (using **proot** and **qemu**) this PR locally for these architectures:
- :heavy_check_mark: x86_64, :heavy_check_mark: x86_64-musl
- :heavy_check_mark: aarch64, :heavy_check_mark: aarch64-musl
- :heavy_check_mark: armv5te, :heavy_check_mark: armv5te-musl
- :heavy_check_mark: armv5tel, :heavy_check_mark: armv5tel-musl
- :heavy_check_mark: armv6l, :heavy_check_mark: armv6l-musl
- :heavy_check_mark: armv6hf, :heavy_check_mark: armv6hf-musl
- :heavy_check_mark: armv7l, :heavy_check_mark: armv7l-musl
- :heavy_check_mark: armv7hf, :heavy_check_mark: armv7hf-musl
- :heavy_check_mark: i686, :heavy_check_mark: i686-musl
- :heavy_check_mark: mips-musl, …
=> ol: update to 2.5.1.

srcpkgs/base-files/files/_vkpurge, srcpkgs/base-files/template
completes subcommands, versions and all for `rm`, and says it expects a version glob for `list` (without completing anything because that would be hard)
=> base-files: add zsh completions for vkpurge

srcpkgs/discord/template
=> discord: update to 0.0.43

srcpkgs/picom/template
=> picom: update to 11.2.

srcpkgs/python3-websocket-client/template
discoverd this with `xbps-pkgdb -a`, and while at it also updated.
cc @tornaria @ahesford 
`/usr/bin/wsdump` was broken, now it works.
=> python3-websocket-client: fix alternatives, update to 1.7.0

srcpkgs/cups-filters/template, srcpkgs/fbpdf/template, srcpkgs/mupdf/template, srcpkgs/sioyek/template, srcpkgs/zathura-pdf-mupdf/template
With this mupdf version, which includes https://git.ghostscript.com/?p=mupdf.git;h=9c9ae0f6ef3ef45cb9ee8add96c6ee598b5f3080 , sioyek correctly parses the TOC of certain documents, see https://github.com/ahrm/sioyek/issues/856
cc #48182
=> mupdf: update to 1.23.10

srcpkgs/dracut/patches/silence-setfont.patch, srcpkgs/dracut/template
This error has been here for years, but unreported by setfont until recently. Throw it away as it's not actionable.
=> dracut: silence spurious setfont stderr warning

srcpkgs/github-cli/template
- **github-cli: update to 2.44.0**
=> github-cli: update to 2.44.0

srcpkgs/rust-bindgen/template
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- i686
- x86_64-musl
=> rust-bindgen: update to 0.69.4.

common/shlibs, srcpkgs/gamescope/template, srcpkgs/gamescope/update, srcpkgs/libliftoff-devel, srcpkgs/libliftoff/template
Add Valve's Gamescope as requested in #36869. If this is merged, `steamos-compositor` should probably be removed from the repository at some point.
This PR also adds `libliftoff` as a dependency. Gamescope also vendors some dependencies, but I believe I've handled this correctly.
=> New package: gamescope-3.14.1

srcpkgs/tmux/template
A [basic support for sixel](https://github.com/tmux/tmux/commit/dfbc6b1888c110cf0ade66f20188c57757ee1298) was added on this [release](https://github.com/tmux/tmux/blob/608d113486835515e7a89b1511704440c68ae817/CHANGES#L13) (enabled with `--enable-sixel`), so it would be good if more people can test it.
A list of terminal emulators that do support sixel is available [here](https://www.arewesixelyet.com/).
=> tmux: update to 3.4

srcpkgs/wlroots0.17/template
- **wlroots0.17: add libliftoff dependency**
cc @ahesford
=> wlroots0.17: add liblitftoff dependency

srcpkgs/podman/template, srcpkgs/slirp4netns/template
- podman: update to 4.9.3
- slirp4netns: update to 1.2.3
=> podman: update to 4.9.3

common/xbps-src/shutils/common.sh, common/xbps-src/shutils/update_check.sh, srcpkgs/xbps/patches/xbps-src-comp.patch, srcpkgs/xbps/template, xbps-src
having to define/type out `XBPS_UPDATE_CHECK_VERBOSE` every time you want more diagnostics for `update-check` is really annoying (i even made a [wrapper](https://github.com/classabbyamp/xX_tools_Xx/blob/tools/xupcheck) for it previously, heh)
currently, this only applies to `update-check`, but if someone wants to add something later that can have higher verbosity, this would enable that.
=> xbps-src: add flag to show verbose messages

srcpkgs/rxvt-unicode/patches/fix-for-tmux-34.patch, srcpkgs/rxvt-unicode/template
@leahneukirchen 
closes #48807 
- armv7l x
=> rxvt-unicode: fix for tmux-3.4

common/shlibs, srcpkgs/gedit-plugins/template, srcpkgs/gedit/template, srcpkgs/gnome-latex/template, srcpkgs/libgedit-amtk-devel, srcpkgs/libgedit-amtk/template, srcpkgs/libgedit-gtksourceview-devel, srcpkgs/libgedit-gtksourceview/template, srcpkgs/tepl/template
- New package: libgedit-amtk-5.8.0
- New package: libgedit-gtksourceview-299.0.5
These versions depend on the new packages:
- tepl: update to 6.8.0.
- gedit: update to 46.1.
- gedit-plugins: update to 46.0.
- gnome-latex: update to 3.46.0.
gedit-plugins no longer carries the zeitgeist plugin.
Gedit and friends now depend on new packages libgedit-amtk and libgedit-gtksourceview: https://gedit-technology.net/
=> gedit: update to 46.1 and add new dependencies

xbps-src
=> xbps-src: don't mess with masterdir set in argv

srcpkgs/puzzles/template
=> puzzles: update to 20240102.7a93ae5d.

srcpkgs/cookiecutter/template
=> cookiecutter: update to 2.6.0

srcpkgs/Signal-Desktop/template
=> Signal-Desktop: update to 6.48.1

srcpkgs/acpid/files/handler.sh, srcpkgs/acpid/template
Previously handler.sh would unconditionally fork/exec 'cat' twice to read these files on any invocation, though their values are only used for ac_adapter events.  Tidy it up to only read them when handling that case.
=> acpid: Only read cpuinfo_{min,max}_freq when needed

srcpkgs/gthumb/template
Relies on libwebkit2gtk-4.0, which is becoming increasingly burdensome. Also relies on libsoup2.
Re-enable when upstream fixes that:
https://gitlab.gnome.org/GNOME/gthumb/-/issues/244
cc: @Bnyro
=> gthumb: update to 3.12.5, disable Flickr integration

srcpkgs/badwolf/template
- I built this PR locally for my native architecture, (`x86_64`)
Crossbuilt for: `armv6l`
~~GNOME [recommends using libsoup3](https://discourse.gnome.org/t/please-build-against-libsoup-3-by-default/10190) instead of libsoup2. build worked fine with 41.~~
what really should have been said above ^ is that GNOME is moving away from libsoup2 for their software. badwolf doesn't explicitly support libsoup3, but it does support `GUri`. it's probably better in the long term to use the compatible libwebkitgtk41+GUri build
=> badwolf: update to 1.3.0, adopt.

srcpkgs/telegram-desktop/template
@Johnnynator webkit2gtk currently is not a rundep for `telegram-desktop` package.
Would you like it to stay that way (since there are multiple versions of webkit2gtk and if you don't have it installed telegram-desktop displays a message telling you to install it), otherwise I can add either libwebkitgtk60 or libwebkit2gtk41, either are supported: https://github.com/desktop-app/lib_webview/blob/4fce8b1971721da739619acf36da0fe79d614a23/webview/platform/linux/webview_linux_webkitgtk_library.cpp#L14-L16
=> telegram-desktop: remove unused makedeps

srcpkgs/yaydl/template
=> yaydl: update to 0.14.0

srcpkgs/gtk4/template
split into a separate pr, according to @oreo639's recommendation (https://github.com/void-linux/void-packages/pull/48752#issuecomment-1968076680).
- armv7l x
=> gtk4: update to 4.12.5

srcpkgs/at-spi2-core/template
split into a separate pr, according to @oreo639's recommendation (https://github.com/void-linux/void-packages/pull/48752#issuecomment-1968076680).
- armv7l x
=> at-spi2-core: update to 2.50.1

srcpkgs/evolution-data-server/template, srcpkgs/evolution-ews/template, srcpkgs/evolution/template
split into a separate pr, according to @oreo639's recommendation (https://github.com/void-linux/void-packages/pull/48752#issuecomment-1968076680).
- armv7l x
=> evolution-ews: update to 3.50.3, evolution{,-data-server}: update to 3.50.4

srcpkgs/geoclue2/template
=> geoclue2: update to 2.7.1.

srcpkgs/grilo-plugins/template, srcpkgs/grilo/patches/fix-pc-file.patch, srcpkgs/grilo/template
split into a separate pr, according to @oreo639's recommendation (https://github.com/void-linux/void-packages/pull/48752#issuecomment-1968076680).
- armv7l x
=> grilo{,-plugins}: update to 0.3.16

srcpkgs/foliate/template
When libadwaita is not installed, foliate crashes on launch with the following error:
```
JS ERROR: Error: Requiring Adw, version 1: Typelib file for namespace 'Adw', version '1' not found require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28 @gi://Adw?version=1:3:25
```
- I tested the changes in this PR: **briefly** (foliate stopped crashing after I installed libadwaita)
=> foliate: add missing libadwaita dependency

srcpkgs/python3-psutil/template
=> python3-psutil: update to 5.9.8.

srcpkgs/python3-vlc/template
Needs dependency on libvlc, otherwise the package cannot function and throws errors:
```
>>> import vlc
>>> vlc.get_default_instance()
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.12/site-packages/vlc.py", line 271, in get_default_instance
_default_instance = Instance()
^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/vlc.py", line 1814, in __new__
return libvlc_new(len(args), args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/vlc.py", line 4990, in libvlc_new
_Cfunction('libvlc_new', ((1,), (1,),), class_result(Instance),
File "/usr/lib/python3.12/site-packages/vlc.py", line 302, in _Cfunction
raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_new'
```
- I tested the changes in this PR: …
=> python3-vlc: update to 3.0.20123.

srcpkgs/pari/template
=> pari: update to 2.15.5.

srcpkgs/rio/template
=> rio: update to 0.0.35

srcpkgs/pmbootstrap/template
Without this update it is not possible to install postmarketOS  v23.12.
=> pmbootstrap: update to 2.2.0, adopt

srcpkgs/osc/template
=> osc: update to 1.6.0

srcpkgs/urh/template
=> urh: update to 2.9.6

srcpkgs/gocryptfs/template
--- 
Enabling OpenSSL fixes `gocryptfs -speed` crashing. Before:
```
$ gocryptfs -speed
gocryptfs v2.3.1 without_openssl; go-fuse [vendored]; 2023-10-02 go1.21.1 linux/amd64
cpu: AMD EPYC 7702P 64-Core Processor; with AES acceleration
AES-GCM-256-OpenSSL       	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5aab40]
goroutine 7 [running]:
testing.(*common).decorate(0x40f2c5?, {0xc00001a210, 0x2a}, 0x83d801?)
/usr/lib/go/src/testing/testing.go:772 +0xa0
testing.(*common).logDepth(0xc000140280, {0xc00001a210, 0x2a}, 0x3)
/usr/lib/go/src/testing/testing.go:1035 +0x1dd
testing.(*common).log(...)
/usr/lib/go/src/testing/testing.go:1004 …
```
=> gocryptfs: update to 2.4.0, enable OpenSSL

srcpkgs/rpi-imager/template
rpi-imager: update to 1.8.5
- armv6l
- armv7l-musl
=> rpi-imager: update to 1.8.5.

srcpkgs/kbd/template
- x86_64-musl
- i686
Changed the homepage because there is currently an outdated SSL certificate.
=> kbd: update to 2.6.4.

srcpkgs/gnome-sudoku/template
split into a separate pr (https://github.com/void-linux/void-packages/pull/48752#issuecomment-1976568640).
- armv7l x
=> gnome-sudoku: update to 45.5

srcpkgs/gtksourceview5/template
=> gtksourceview5: update to 5.10.0

srcpkgs/libmediaart/template
=> libmediaart: update to 1.9.6

srcpkgs/gssdp/template
=> gssdp: update to 1.6.3

srcpkgs/cheese/template
=> cheese: update to 44.1

srcpkgs/orca/template
=> orca: update to 45.2

srcpkgs/mm-common/template
=> mm-common: update to 1.0.6

srcpkgs/polari/template
=> polari: update to 45.0

srcpkgs/rygel/template
=> rygel: update to 0.42.5

srcpkgs/gnome-weather/template
=> gnome-weather: update to 45.0

srcpkgs/ghex/template
=> ghex: update to 45.1

srcpkgs/gnote/template
=> gnote: update to 45.1

srcpkgs/libmusicbrainz5/patches/libxml2-2.12.patch, srcpkgs/libxml2/patches/0b5650067b4ba37dc0dc1a889a17e96dc1610799.patch, srcpkgs/libxml2/patches/387a952bdb7a4364100f009043e94e1bf44c6197.patch, srcpkgs/libxml2/patches/4365a5e1153dd5ed7d269d00f8f14daee0fac5c8.patch, srcpkgs/libxml2/template, srcpkgs/osinfo-db-tools/patches/fix-libxml2-2.12.patch, srcpkgs/qt5-webengine/patches/fix-libxml2-2.12.patch, srcpkgs/qt6-pdf/patches/fix-libxml2-2.12.patch, srcpkgs/recoll/patches/musl.patch, srcpkgs/recoll/template, srcpkgs/squid/template, srcpkgs/xmlsec1/template
I tested building all packages depending on libxml2.
~~The only other build failure not addressed is vtk, which is gcc 13 related.~~
This depends on https://github.com/void-linux/void-packages/pull/48824
cc: @classabbyamp
=> libxml2: update to 2.12.5.

srcpkgs/dnsdist/template
No longer needs/uses libh2o
- aarch64-musl
=> dnsdist: update to 1.9.0

srcpkgs/tbb/template
Installing as an egg is deprecated and, without a path inclusion, makes the package un-importable anyway. The easiest path seems to be just unpacking the egg.
=> tbb: fix Python module installation

.editorconfig, .gitignore
This PR adds an [EditorConfig](https://editorconfig.org) file to help following the general style used in the repo, along with xlint.
EditorConfig is supported by many editors (see previous link), and automatically adjusts editor settings for indentation, line endings, encoding, etc for a file based on rules. Editors that support it don't act as reformatters when saving; they only use the settings for additions and new files (just as if you has manually changed those settings), which should help new lines and new files follow basic style without user intervention and without generating large "reformat" git diffs[^1].
The exact rules in this PR are just what I surmised to be "the style", namely:
- utf-8, `lf` line-endings, no trailing whitespace at end of lines, and final newline for all …
=> [RFC] add EditorConfig file

srcpkgs/xfce4-weather-plugin/patches/0003-parsers-Generalise-input-to-array-of-gchar.patch, srcpkgs/xfce4-weather-plugin/patches/0004-libsoup-Port-to-libsoup-3.0.patch, srcpkgs/xfce4-weather-plugin/template
Carry patches for libsoup-3.0 because upstream wants to wait until  Xfce 4.20 is released  or  late 2024 - early 2025,
https://gitlab.xfce.org/panel-plugins/xfce4-weather-plugin/-/merge_requests/28
=> xfce4-weather-plugin: update to 0.11.1.

srcpkgs/autoconf-archive/patches/0001-AX_C_FLOAT_WORDS_BIGENDIAN-Fix-bug-AX_C_FLOAT_WORDS_.patch, srcpkgs/autoconf-archive/template, srcpkgs/python3/template
`autoreconf` can be dropped once upstream generates configure from the not-yet-released autoconf-archive
ping @ahesford
=> python3: fix lto build

srcpkgs/gphoto2/template
- I tested hardware: Ricoh Theta Z1
=> gphoto2: update to 2.5.28

srcpkgs/compiz-core/patches/gcc14.patch, srcpkgs/compiz-core/patches/libxml2-2.12.patch, srcpkgs/compiz-core/template
=> compiz-core: fix xml handling and fix building with gcc14

srcpkgs/font-cozette/template
- armv6l-glibc
Note: new to this and accidentally closed previous PR when squashing commits. Sorry for that; this one I tested more thoroughly and fixed an upstream bug, so no revisions should be needed.
=> font-cozette: update to 1.23.2.

srcpkgs/hunspell-en_GB-ize/template, srcpkgs/hunspell-fr_FR/template, srcpkgs/hunspell-pt_PT-preao/template, srcpkgs/hunspell-ru_RU-ieyo/template
This PR expands the work of #49189 
- `pt_PT-preao` nows provides `pt_PT`, too, not sure if this is correct though.
- `fr_FR` nows provides spelling check for `fr_BE`, `fr_CA`, `fr_CH`, `fr_LU`, `fr_MC`, to the best of my knowledge, these regions also use French French spelling rules. But with different format for other things. (The list obtained by Libre Office).
- #49030 should be done with this PR.
=> hunspell-*: provides bdic for qtwebengine (and Chromium like browsers).

srcpkgs/routinator/template
- aarch64-musl
- armv7l
- armv6l-musl
=> routinator: update to 0.13.2

srcpkgs/qbe/template
=> qbe: update to 1.2.

common/shlibs, srcpkgs/darktable/template, srcpkgs/highway/template, srcpkgs/imlib2/template, srcpkgs/kimageformats/template, srcpkgs/krita/template, srcpkgs/libjxl/template, srcpkgs/swayimg/template
- built only: `swayimg`, `kimageformats`
- built and tested: `darktable`, `imlib2`, `krita`, `libjxl-*`
- built `libjxl` for `x86_64-musl` and `i686-glibc`, didn't build any of the other packages
I also went from using a `build_wrksrc` to a `skip_extraction` -> `vsrcextract` in the `libjxl` package since [I was told to do that before](https://github.com/void-linux/void-packages/pull/48828#issuecomment-1974843065) so it's probably the correct way of doing this kinda thing now
=> libjxl: update to 0.10.2.

srcpkgs/OTPClient/template
=> OTPClient: update to 3.5.2

srcpkgs/autorestic/template
```
$ autorestic --version
autorestic version 1.7.10
$ autorestic check
Using config: 	 /home/em/.autorestic.yaml
Using env:	 /home/em/.autorestic.env
Using lock:	 /home/em/.autorestic.lock.yml
Everything is fine.
```
=> autorestic: update to 1.8.0

common/hooks/pre-pkg/04-generate-runtime-deps.sh, srcpkgs/base-chroot/template, srcpkgs/base-container-full/template, srcpkgs/base-container/template, srcpkgs/base-system/template
- common/hooks/pre-pkg/04-generate-runtime-deps: partially revert sorting
- base-system: rebuild for dep sorting
- base-container: rebuild for dep sorting
- base-container-full: rebuild for dep sorting
- base-chroot: rebuild for dep sorting
=> fix dependency sorting

common/hooks/pre-pkg/99-pkglint.sh, srcpkgs/glibc/template
We should really provide the `C.UTF-8` locale by default. I believe that the best way to do so is by removing it entirely from `/etc/default/libc-locales` processing and install it, as part of the main `glibc` package, in `/usr/lib/locales` like Arch does.
This currently trips the package linter, so either
- We can make an exception for glibc in the linter, or
- Rather than include the locale files in the package, we can add an `INSTALL` script to the base package to write the `C.utf-8` locale outside of an archive, where it will always be reachable.
I favor the first because it is less wasteful; why should everybody have to generate a locale that we expect everybody to have available by default?
A third option is to modify the `glibc-locales` `INSTALL` script to either add a separate, …
=> glibc: clean up install, add C.UTF-8 by default

srcpkgs/python3-cairo/template
=> python3-cairo: update to 1.26.0.

srcpkgs/autorestic/template
Quick regression test:
```
$ autorestic --version
autorestic version 1.8.1
$ autorestic check
Using config: 	/home/em/.autorestic.yaml
Using env:	/home/em/.autorestic.env
Using lock:	/home/em/.autorestic.lock.yml
Everything is fine.
$ autorestic backup --all
Using config: 	/home/em/.autorestic.yaml
Using env:	/home/em/.autorestic.env
Using lock:	/home/em/.autorestic.lock.yml
...
Done
```
=> autorestic: update to 1.8.1

srcpkgs/python3-uvicorn/template
=> python3-uvicorn: update to 0.28.0

srcpkgs/evince/template
=> evince: update to 45.0

srcpkgs/gcab/template
=> gcab: update to 1.6

srcpkgs/gnome-system-monitor/template
=> gnome-system-monitor: update to 45.0.2

srcpkgs/gnome-maps/template
=> gnome-maps: update to 45.5

srcpkgs/libhtp/template, srcpkgs/suricata/patches/fix-missing-syscalls.patch, srcpkgs/suricata/template
=> suricata: update to 7.0.1

srcpkgs/rust/template
Without it rust-analyzer doesn't expand macros.
=> rust: build rust-analyzer-proc-macro-srv

srcpkgs/rofi-emoji/template
=> rofi-emoji: update to 3.3.0

srcpkgs/libsigc++/template
=> libsigc++: update to 2.12.1

srcpkgs/gnome-boxes/template
=> gnome-boxes: update to 45.0

srcpkgs/gnome-calculator/template
=> gnome-calculator: update to 45.0.2

srcpkgs/gnome-characters/template
=> gnome-characters: update to 45.0

srcpkgs/gnome-clocks/template
=> gnome-clocks: update to 45.0

srcpkgs/aisleriot/template
=> aisleriot: update to 3.22.30

srcpkgs/baobab/template
=> baobab: update to 45.0

srcpkgs/gnome-disk-utility/template
=> gnome-disk-utility: update to 45.1

srcpkgs/gupnp/template
=> gupnp: update to 1.6.6

srcpkgs/rtl8812au-dkms/template
=> rtl8812au-dkms: move head to  compile with 6.7.x, bump revision

srcpkgs/miniserve/template
=> miniserve: update to 0.27.1.

srcpkgs/python3-paho_mqtt/template
Still kind of exploring this, but might actually start using it for real work and, if so, will want to make it available. It seems like this is the most popular MQTT client for Python.
The name `paho.mqtt.python` is horrible, leaving me with choices like `python3-paho.mqtt` or `python3-paho.mqtt.python`, so I opted for the PyPI name and settled on `python3-paho_mqtt` instead.
- I tested the changes in this PR: **in progress**
=> New package: python3-paho_mqtt-2.0.0

srcpkgs/hydroxide/template
=> hydroxide: update to 0.2.28

srcpkgs/eog/template
=> eog: update to 45.2

srcpkgs/gnome-font-viewer/patches/gcc14.patch, srcpkgs/gnome-font-viewer/template
=> gnome-font-viewer: update to 45.0

srcpkgs/folks/template
https://github.com/void-linux/void-packages/pull/48752#issuecomment-2005911423
- armv7l x
=> folks: update to 0.15.8

srcpkgs/jujutsu/template
Both tests and runtime expect `ssh-keygen` for signing features.
=> jujutsu: add openssh dependency

srcpkgs/glycin-loaders/template, srcpkgs/loupe/template
this app is a part of gnome-45 #48762
- armv7l x
=> New package: loupe-46.0

srcpkgs/gnome-tour/template
=> gnome-tour: update to 45.0

srcpkgs/p11-kit/template
Fixes issue where the wrong C_GetInterface may get loaded. https://github.com/p11-glue/p11-kit/pull/535
(this causes test failures for glib-networking)
=> p11-kit: update to 0.25.3.

srcpkgs/gdm/patches/pam-turnstile-elogind.patch, srcpkgs/gdm/template, srcpkgs/lightdm/patches/pam-turnstile-elogind.patch, srcpkgs/pam-base/files/system-login, srcpkgs/pam-base/template, srcpkgs/polkit/patches/turnstile.patch, srcpkgs/polkit/template, srcpkgs/turnstile/files/README.voidlinux, srcpkgs/turnstile/files/dbus.run, srcpkgs/turnstile/files/turnstiled/run, srcpkgs/turnstile/patches/defer-rundir.patch, srcpkgs/turnstile/patches/dummy.patch, srcpkgs/turnstile/patches/fix-chdir.patch, srcpkgs/turnstile/patches/runit.patch, srcpkgs/turnstile/template
WIP while i create the runit backend upstream ([mostly done](https://github.com/chimera-linux/turnstile/compare/master...classabbyamp:runit-backend))
=> New package: turnstile-0.1.8

common/xbps-src/shutils/update_check.sh
The `python3` and `python3.11` update-check keeps failing because python.org is returning a compressed response that thwarts pattern matching. Adding `--compressed` to the arguments for curl will allow the client to request compressed responses and, more importantly, will attempt to decompress them when received. This fixes the Python update checks.
=> xbps-src: allow curl to request compressed responses in update-check

srcpkgs/dwm/template
- x86_64-musl
- i686
- aarch64
I use dwm on a daily basis. Now I'm gonna make custom dwm build based on xbps-src to always test it. Already subscribed to suckless rss so I won't skip update. I know that I did strange things in this repo: PR'd single bash script, PR'd synth with questionable licensing (my apologies ahesford. You're right about that). But as for dwm: I understand how it works as a program, how it works together with xbps-src and I can maintain it efficently, even make patches/rebuilds if it's needed. And I do want to help my with favorite distro the way I can.
=> dwm: update to 6.5.

srcpkgs/lsd/template
=> lsd: update to 1.1.1

srcpkgs/gnome-console/template
=> gnome-console: update to 46.0.

srcpkgs/nvidia/template
- I tested the changes in this PR: **briefly** (Currently only tested on a machine with Nvidia 2080 Super)
* Fixed a bug that could cause the GPU driver to hang when running some Vkd3d games, such as F1 2021.
* Fixed a bug that caused eglExportDMABUFImageQueryMESA() to return invalid DRM formats for the images that use the sRGB color space.
* Fixed a bug that caused wgpu applications to hang on Wayland.
* Fixed a bug that caused "Flip event timeout" messages to be printed to the system log when the system is suspended without using /usr/bin/nvidia-sleep.sh when nvidia-drm is loaded with the `fbdev=1` kernel module parameter.
* Updated the nvidia-settings control panel to ensure that the entire Display Configuration page …
=> nvidia: update to 550.67.

srcpkgs/bird/template
This release fixes a regression related to OSPF PtP links introduced in 2.15 among other things.
- aarch64-musl
- armv7l
- armv6l-musl
=> bird: update to 2.15.1

srcpkgs/praat/template
=> praat: update to 6.4.07

srcpkgs/linux6.6/template, srcpkgs/linux6.7/template, srcpkgs/linux6.8/template
`sign-file` needs `pkg-config` to find libcrypto: https://github.com/torvalds/linux/blob/2dde18cd1d8fac735875f2e4987f11817cc0bc2c/scripts/Makefile#L25-L26
On cross, it is removed by `make _mrproper_scripts`, so copy it to `XBPS_WRAPPERDIR` before running it.
failure symptom:
```
/void-packages/srcpkgs/linux6.8/files/mv-debug: line 7: /builddir/linux6.8-6.8.1/scripts/sign-file: No such file or directory
```
[ci skip]
=> linux6.{6..8}: fix module signing

srcpkgs/palp/template, srcpkgs/python3-cypari2/template, srcpkgs/python3-cypari2/update, srcpkgs/python3-memory_allocator/template, srcpkgs/python3-memory_allocator/update, srcpkgs/python3-pplpy/patches/dont-depend-on-sphinx.patch, srcpkgs/python3-pplpy/template, srcpkgs/python3-pplpy/update
- python3-pplpy: update to 0.8.10.
- python3-memory_allocator: update to 0.1.4.
- python3-cypari2: update to 2.1.5.
- palp: update to 2.21.
This does not require sagemath rebuild. I run the full testsuite with our current binary package to make sure.
=> Update a few sagemath dependencies

srcpkgs/lsd/template
=> lsd: update to 1.1.2

srcpkgs/python3-bitarray/template, srcpkgs/python3-bitstring/template
- python3-bitstring >= 4.1.0 depends on python3-bitarray >= 2.8.0
=> python3-bitstring: update to 4.1.4; python3-bitarray: update to 2.9.2.

srcpkgs/xz/template
This reverts commit ba6c7f1ffc6012148b0deea038c23794cb93c6c5.
See: https://www.openwall.com/lists/oss-security/2024/03/29/4
=> Revert "xz: update to 5.6.0."

srcpkgs/scons/template
- x86_64-musl
Note that i switched the distfile to sourceforge as SCons devs are no longer cutting releases on github and now the main scons website points to sourceforge to get an official tarball.
Tested it on building godot as well without issue
=> scons: update to 4.7.0

srcpkgs/muon/template
muon started segfaulting after the recent pkgconf update:
```
~/src/sqsh-tools (main ✗) muon setup "build"
detected compiler gcc '13.2.0' (['cc']), linker ld.bfd
configuring 'sqsh-tools', version: 1.3.0
dependency threads found
found dependency threads
[1]    997 segmentation fault  muon setup "build"
```
Rebuild it fixed the issue.
=> muon: rebuild against libpkgconf.so.4

srcpkgs/swirc/template
=> swirc: update to 3.4.7.

srcpkgs/autorestic/template
```
$ autorestic --version
autorestic version 1.8.2
$ autorestic check
Using config: 	/home/em/.autorestic.yaml
Using env:	/home/em/.autorestic.env
Using lock:	/home/em/.autorestic.lock.yml
Everything is fine.
```
=> autorestic: update to 1.8.2

srcpkgs/refind/files/kernel.post-install, srcpkgs/refind/files/refind-kernel-hook.conf, srcpkgs/refind/template
- I built this PR locally for my native architecture: (x86_64-glibc)
When using loader and initrd entries in refind.conf one needs to either avoid using quotation marks whatsoever or use backslashes to satisfy the EFI stub bootloader. Otherwise the manual stanzas won't boot. I tested revision 3 which had been merged yesterday and experienced this bug.
More on this issue here: https://wiki.archlinux.org/title/REFInd#For_manual_boot_stanzas
@sgn @ahesford ping
=> refind: make loader and initrd entires bootable again

srcpkgs/libvncserver/template
=> libvncserver: add missing buildepends (fixes broken functionality of vnc apps using encryption)

srcpkgs/amdvlk/patches/fix-musl-build.patch, srcpkgs/amdvlk/template
=> amdvlk: update to 2024.Q1.3.

srcpkgs/slack-desktop/template
Slack seems to [disable screen sharing on Wayland](https://forums.slackcommunity.com/s/question/0D53a00009BSEGACA5/when-will-slack-support-wayland-screen-sharing-does-anyone-have-workarounds-or-hacks-to-make-it-work), this commit allow the use of WebRTCPipeWireCapturer.
Final user still needs to add the flag on the command line to make use of it:
`--enable-features=WebRTCPipeWireCapturer --ozone-platform-hint=auto`.
Note: just tested on Wayland, it would be great if someone tested it on x11 too.
Note2: As discussed below with @dataCobra, I'm adopting this package.
=> slack-desktop: allow the use of WebRTCPipeWireCapturer flag, adopt

common/shlibs, srcpkgs/KDSingleApplication/template, srcpkgs/libre-graph-api-cpp-qt-client/template, srcpkgs/owncloudclient/patches/skip-root-test.patch, srcpkgs/owncloudclient/template, srcpkgs/qtkeychain-qt6-devel, srcpkgs/qtkeychain-qt6/files/README.voidlinux, srcpkgs/qtkeychain-qt6/patches/fix-cross-qt6.patch, srcpkgs/qtkeychain-qt6/patches/use-kwallet-dbus-def.patch, srcpkgs/qtkeychain-qt6/template
I've been using 5.0.0 for a while, and now updated to 5.1.0.
Note that kde integration (#45352) has been removed.
There is an external project: https://github.com/owncloud/client-desktop-shell-integration-dolphin but I don't use kde and I wouldn't be able to test at all.
It was necessary to build `qtkeychain-qt6` which I copied with obvious changes from `qtkeychain-qt5`. Should this new pkg keep @yopito as maintainer?
=> owncloudclient: update to 5.2.1.

srcpkgs/docker-compose/template
=> docker-compose: update to 2.26.1

srcpkgs/newsboat/template
=> newsboat: update to 2.35.

common/scripts/xbps-cycles.py, common/travis/build.sh, common/xbps-src/shutils/build_dependencies.sh, common/xbps-src/shutils/show.sh, xbps-src
As it is now, if `pkgA` checkdepends on `pkgB`, sort-dependencies will still print `pkgA` before `pkgB`. This causes CI to build `pkgB` twice: first build `pkgA` which forces implicit build of `pkgB`; then build of `pkgB` (explicit, so it will ignore the package is already built).
A concrete example:
```
$ ./xbps-src sort-dependencies python3-process-tests python3-pytest-cov
python3-pytest-cov
python3-process-tests
```
The example above causes `python-process-tests` to be built twice, as shown in:
https://github.com/void-linux/void-packages/actions/runs/7107346278/job/19348602412?pr=47610
After this commit one can do
```
$ ./xbps-src -Q sort-dependencies python3-process-tests python3-pytest-cov
python3-process-tests
python3-pytest-cov
```
The CI issue is fixed by pasing -Q to …
=> Accept -Q / -K in show-build-deps, sort-dependencies, xbps-cycles.py

srcpkgs/pdfpc/template
Build with webkit2gtk-4.1, which provides an identical api to webkit2gtk-4.0 except it uses libsoup3.
The REST server functionality requires libsoup2. libsoup2 and libsoup3 cannot be loaded in the same process at the same time.
One of the maintainers recommended just disabling the rest server and building the markdown presentation notes viewer with webkit2gtk-4.1 stating that as far as he knows, he is the only one that actually uses the rest server function. https://github.com/pdfpc/pdfpc/issues/671#issuecomment-1552713117
I was wondering if anyone here that uses pdfpc uses the rest server function?
=> pdfpc: disable REST server

srcpkgs/libsoup/template
Note: Updating to this version adds checks such that applications mixing libsoup3 and libsoup2 will abort with an error message.
=> libsoup: update to 2.74.3.

srcpkgs/python3-keyring/template
=> python3-keyring: update to 25.1.0.

srcpkgs/python3-networkx/template
=> python3-networkx: update to 3.3.

srcpkgs/OTPClient/template
=> OTPClient: update to 3.6.0

srcpkgs/python3-rapidfuzz/template, srcpkgs/rapidfuzz-cpp/template
=> python3-rapidfuzz: update to 3.8.0

srcpkgs/UEFITool/patches/musl_defs.patch, srcpkgs/UEFITool/template
=> UEFITool: update to A68, adopt.

srcpkgs/gnome-calendar/template
=> gnome-calendar: update to 46.0.

srcpkgs/gnome-clocks/template
=> gnome-clocks: update to 46.0.

srcpkgs/openssl-doc, srcpkgs/openssl/template
* move c_rehash manpage to its package
* move dev docs to their own subpackage. there's a huge amount of them and they don't need to be installed for building packages with openssl-devel
=> openssl: update to 3.3.0.

common/shlibs, srcpkgs/qt6-declarative/template, srcpkgs/qt6-languageserver-devel, srcpkgs/qt6-languageserver/template
QML language server, new in qt6.6. requires qt6-languageserver, a new package
=> qt6-declarative: build qmlls tool

srcpkgs/qt5/template
on `arm*`/`aarch64*`, qt5 defaults to the `eglfs` QPA platform, which is designed for embedded devices. because this is probably a less-common use-case on Void, it's more sane to default to `xcb`, like `x86_64*` does.
=> qt5: use a sane default platform

srcpkgs/python3-uvicorn/template
=> python3-uvicorn: update to 0.29.0

srcpkgs/iperf/template
=> iperf: update to 2.2.0.

srcpkgs/delve/template
`dlv exec` on a go program works fine, can break on main.main and step thru the program.
=> delve: update to 1.22.1.

srcpkgs/tree-sitter/template
- I built this PR locally for my native architecture: x86-64_libc
=> tree-sitter: update to 0.22.5

srcpkgs/gnome-characters/template
=> gnome-characters: update to 46.0.

srcpkgs/gnome-font-viewer/template
=> gnome-font-viewer: update to 46.0.

srcpkgs/zellij/template
=> zellij: update to 0.40.0

srcpkgs/gtk+3/template, srcpkgs/gtk4/template
cc: @sgn 
Upstream, both gtk3-icon-browser and gtk4-icon-browser are considered demos and are are disabled if `-Dbuild-demos=false` is passed. For reference, Arch puts it in gtk4-icon-browser gtk4-demos, Fedora puts it in gtk4-devel-tools, Debian puts it in gtk-4-examples. The same is the case for gtk+3 (although Fedora puts the gtk+3 demos in gtk3-devel).
If moving them is an issue though, please let me know.
=> gtk{+3,4}: move gtk-icon-browser to demo subpackage

srcpkgs/lighttpd/template
lighttpd: update to 1.4.76
I tested the changes in this PR: NO
(build-tested elsewhere: on openwrt)
(release tag built and automated tests run on many platforms: https://github.com/lighttpd/lighttpd1.4/actions)
=> lighttpd: update to 1.4.76

srcpkgs/wineasio/files/README.voidlinux, srcpkgs/wineasio/patches/fix-install-paths.patch, srcpkgs/wineasio/template
=> wineasio: update to 1.2.0.

srcpkgs/gtk4/patches/wmspec.patch, srcpkgs/gtk4/template
=> gtk4: fix grabbing X11 check window before 15s after boot

srcpkgs/dunst/template
As [completions are considered official](https://github.com/dunst-project/dunst/releases/tag/v1.11.0) now, they are included in the install process.
=> dunst: update to 1.11.0

srcpkgs/gnome-keyring/template
=> gnome-keyring: update to 46.1.

srcpkgs/inkscape/update
Inkscape download page changed again so that update version links have now the same format as release ones; this detects the version based on a different feature of the page.
=> inkscape: do not detect dev releases as updates

srcpkgs/hunspell-fr_FR/template
discollete.org used to be the domain for Grammalecte, they moved to the grammalecte.net domain in 2019, and discollete.org became a redirect. Currently the domain is just spam.
The dictionary files in the 7.0 libreoffice plugin are identical to the ones in the old zip.
=> hunspell-fr_FR: fix homepage and distfiles location

srcpkgs/atop/template
=> atop: update to 2.10.0.

srcpkgs/rsstail/patches/fix-1779.patch, srcpkgs/rsstail/template
More info: https://github.com/folkertvanheusden/rsstail/issues/1
Had to rework patch file for a bit. Original GNU dialect from new 2.1 version remained
https://github.com/void-linux/void-packages/issues/42403
=> rsstail: fix distfile

srcpkgs/flatpak/template
@Duncaen 
1.15.8 fixes [CVE-2024-32462](https://www.openwall.com/lists/oss-security/2024/04/18/5)
=> flatpak: update to 1.15.8

srcpkgs/ostree/template
soup is only really required for tests since curl is the default backend when enabled, but soup2 isn't necessary anymore.
=> ostree: build with soup3 instead of soup2

srcpkgs/gnome-text-editor/template
=> gnome-text-editor: update to 46.1

srcpkgs/gcr/patches/Fix-FTBFS-on-x32.patch, srcpkgs/gcr/template, srcpkgs/gcr4/template
p.s. all tests pass locally.  tests below fail in ci
**x86_64, i686**
`22/47 gcr:gck / object                  FAIL            0.16s   killed by signal 11 SIGSEGV`
**x86_64-musl**
`43/47 gcr:gcr-base / gnupg-collection   FAIL            0.17s   killed by signal 6 SIGABRT`
=> gcr: update to 3.41.2, gcr4: update to 4.3.0

srcpkgs/gnome-connections/template
Note: this might also depend on https://github.com/void-linux/void-packages/pull/49572 in the future, similar to `gnome-remote-desktop>=46.0`
For now, build and runtime works fine with `freerdp<=3.0.0`
=> gnome-connections: update to 46.0.

srcpkgs/inkscape/template
=> inkscape: drop libsoup requirement

common/shlibs, srcpkgs/gtk-session-lock-devel, srcpkgs/gtk-session-lock/template, srcpkgs/gtklock/template
I was unsure if the new dependency should be a separate commit, I can squash if needed.
=> gtklock: update to 3.0.0

srcpkgs/stfl/template
- I did build for x86_64-glibc
https://github.com/void-linux/void-packages/issues/42403
The only reliable source is in alpine archive
=> stfl: fix distfile

srcpkgs/certbot-apache/template, srcpkgs/certbot-nginx/template, srcpkgs/certbot/template
- I built this PR locally for my native architecture, (x86-64 GLIBC)
- aarch64-musl
- armv7l
=> certbot: update to 2.10.0

srcpkgs/strongswan/template
libsoup is used for soup-fetcher, but strongswan has another fetcher, which is curl-fetcher.
=> strongswan: disable libsoup

srcpkgs/hugo/template
**NOTE: This fixes an [XSS vulnerability](https://github.com/gohugoio/hugo/releases/tag/v0.125.3) in certain configurations.**
=> hugo: update to 0.125.3.

srcpkgs/mpv/template
- x86_64-musl
- aarch64-musl
About shaderc disabling: https://github.com/mpv-player/mpv/commit/60a31a8a284e539043c47a33ff90f3d55aade6a8
=> mpv: update to 0.38.0.

Manual.md, common/hooks/post-install/04-create-xbps-metadata-scripts.sh, common/hooks/pre-pkg/03-rewrite-python-shebang.sh, srcpkgs/ghidra/template
Ghidra's embedded jython contains scripts with shebangs like `#!/usr/bin/env python`. These seem to be designed to be run by jython, *not* the system python, and as such, they should not have their shebangs changed to `#!/usr/bin/python2`. This adds support for disabling that hook in cases like this.
=> common: support disabling python shebang rewriting

srcpkgs/python3-peewee/template
This gets rid of the following warnings upon install:
```
usr/lib/python3.12/site-packages/playhouse/migrate.py:673: SyntaxWarning: invalid escape sequence '\('
column_re = re.compile('(.+?)\((.+)\)')
usr/lib/python3.12/site-packages/playhouse/migrate.py:830: SyntaxWarning: invalid escape sequence '\]'
if re.match('%s(?:[\'"`\]]?\s|$)' % column_to_update, column):
usr/lib/python3.12/site-packages/playhouse/reflection.py:421: SyntaxWarning: invalid escape sequence '\['
begin = '(?:["\[\(]+)?'
usr/lib/python3.12/site-packages/playhouse/reflection.py:422: SyntaxWarning: invalid escape sequence '\]'
end = '(?:["\]\)]+)?'
usr/lib/python3.12/site-packages/playhouse/reflection.py:424: SyntaxWarning: invalid escape sequence '\s'
'(?:FOREIGN KEY\s*)?' …
```
=> python3-peewee: update to 3.17.3.

common/shlibs, srcpkgs/sagemath/patches/37763-scipy_1.13.patch, srcpkgs/sagemath/patches/get_patches, srcpkgs/sagemath/template, srcpkgs/singular/template
This needed bumping sagemath, so its testsuite is fully run here for a good test that singular works fine for us. One test fails due to the update of scipy to 1.13, so I added an easy fix (backported, already merged upstream).
@dkwo may want to test on aarch64.
=> singular: update to 4.4.0.

srcpkgs/tcl/template
=> tcl: remove sqlite builtin bundle (use sqlite-tcl instead)

srcpkgs/got/patches/landlock.patch, srcpkgs/got/template
- I built this PR locally for my native architecture, (x86_64-muslc)
I'm not sure why I have to include `linux/unistd.h` to get `__NR_landlock_create_ruleset`, while for e.g. on alpine it's not needed.  This was the reason holding me to submit updates.
=> got: update to 0.98.2

srcpkgs/libtool/template
=> libtool: sed and grep should be available in base-files

common/shlibs, srcpkgs/gsasl/template, srcpkgs/jreen/template, srcpkgs/msmtp/template, srcpkgs/mutt/template
- **gsasl: update to 2.2.1.**
- **mutt: revbump for libgsasl**
- **jreen: revbump for libgsasl**
- **msmtp: update to 1.8.26.**
- **msmtp: add changelog**
---
- I have tested msmtp, the other two packages (`mutt` and `jreen`) I only built for my architecture but did not try running them.
=> msmtp 1.8.26

srcpkgs/hexchat-devel, srcpkgs/hexchat/template
they're not useless, they're needed for compiling C plugins
@0x5c
=> hexchat: don't remove pkgconfig/headers

srcpkgs/chroot-git/template, xbps-src
=> xbps-src: stop invoking chroot-git explicitly 

srcpkgs/python3-mpv/template
=> python3-mpv-1.0.6_1

srcpkgs/zellij/template
=> zellij: update to 0.40.1

srcpkgs/python3-contourpy/template
Works fine with sagemath
Cc: @misuchiru03
=> python3-contourpy: update to 1.2.1.

common/shlibs, srcpkgs/libcss/template, srcpkgs/libdom/template, srcpkgs/libhubbub/template, srcpkgs/libnsbmp/template, srcpkgs/libnsgif/template, srcpkgs/libnsutils/template, srcpkgs/libparserutils/template, srcpkgs/netsurf-buildsystem/template, srcpkgs/netsurf/template, srcpkgs/nsgenbind/template
In addition to updating netsurf and its dependencies, changes include:
- http -> https where needed
- libnsutils: fix package description
- libcss: workaround for targets being rebuilt during install phase
- netsurf: remove some unused makedepends
=> netsurf: update to 3.11 and update deps.

srcpkgs/runit-void/patches/blkdev-write-mounted.patch, srcpkgs/runit-void/template
see #50124
backport of https://github.com/void-linux/void-runit/pull/115
@dkwo can you test this?
=> runit-void: fix issue with fsck on mounted partitions

srcpkgs/python3-zstandard/patches/fix-hardcoded-version-number.patch, srcpkgs/python3-zstandard/template
=> python3-zstandard: update to 0.22.0.

srcpkgs/stig/template
=> stig: update to 0.12.8a0, adopt

srcpkgs/evince/template
=> evince: update to 46.1

srcpkgs/catch2/template
The `catch2` package is really weird by the way. It ships a _static_ library. It also doesn't have `catch2-devel`
because of this. I guess this is for developers only. I know Catch2 doesn't really like to be packaged, it prefers to be managed by the project's build system, but it still isn't standard to ship static libraries like this. Correct me if I'm wrong.
ping @DBLouis 
=> catch2: fix deceiving description

srcpkgs/sequoia-chameleon-gnupg/template
- ~~gnupg1: add alternatives for gpg and gpgv~~
- ~~gnupg: add alternatives for gpg and gpgv~~
- New package: sequoia-chameleon-gnupg-0.6.0
revival of https://github.com/void-linux/void-packages/pull/41306
~~@sgn, you had comments in the previous PR about the alternatives groups. I've set `--enable-gpg-is-gpg2` for `gnupg`, so I believe that fixes your broken scenario:~~
```
$ gpgconf --check-programs
gpg:OpenPGP:/usr/bin/gpg2:1:1:
gpgsm:S/MIME:/usr/bin/gpgsm:1:1:
keyboxd:Public Keys:/usr/libexec/keyboxd:1:1:
gpg-agent:Private Keys:/usr/bin/gpg-agent:1:1: …
```
=> New package: sequoia-chameleon-gnupg-0.7.0

common/build-helper/meson.sh
When you try to build anything using the `meson` build style, this will appear as the first line of output in the `do_configure` step:
```
DEPRECATION: "pkgconfig" entry is deprecated and should be replaced by "pkg-config"
```
This PR follows the warning's advice and replaces `pkgconfig` with `pkg-config`. I have tested building a meson package using both `meson-1.3.2_1` and using `meson-1.4.0_1` from #49288
=> common/build-helper/meson.sh: Fix deprecation warn

srcpkgs/meson/patches/rust-proc-macro.patch, srcpkgs/meson/template
Fixes an issue causing mesa to fail when cross-compiling 
https://github.com/mesonbuild/meson/issues/12973
- x86_64-musl
- i686
=> meson: fix build with rust proc-macro

common/shlibs, srcpkgs/kaccounts-integration/template, srcpkgs/kf6-kaccounts-integration-devel, srcpkgs/kf6-kaccounts-integration/template, srcpkgs/signon-kwallet-extension/template, srcpkgs/signon-plugin-oauth2/template, srcpkgs/signon-ui/template, srcpkgs/signond/patches/cross.patch, srcpkgs/signond/template
=> singond Build with Qt6, keep Qt5 for backward compatibility

common/chroot-style/uchroot.sh
...and show a friendly error message
This can be a common failure mode when using `-t` if not in the group `xbps-uchroot` is owned by, because it is SUID. Previously, the error was the cryptic message `ERROR: prctl SECBIT_NOROOT (Operation not permitted)`.
=> common/chroot-style/uchroot.sh: check if xbps-uchroot is executable

srcpkgs/inxi/template
```
$ inxi --version
inxi 3.3.34-00 (2024-04-13)
Copyright (C) 2008-2024 Harald Hope aka h2
Forked from Infobash 3.02: 
Copyright (C) 2005-2007 Michiel de Boer aka locsmif. 
Using Perl version: 5.038002
Program Location: /usr/sbin
Website: https://codeberg.org/smxi/inxi or https://smxi.org/
IRC: irc.oftc.net channel: #smxi
Forums: https://techpatterns.com/forums/forum-33.html
This program is free software; you can redistribute it and/or modify it under 
the terms of the GNU General Public License as published by the Free Software 
Foundation; either version 3 of the License, or (at your option) any later 
version. (https://www.gnu.org/licenses/gpl.html) 
$ inxi
CPU: 6-core Intel …
```
=> inxi: update to 3.3.34.1

srcpkgs/osc/template
=> osc: update to 1.6.2

srcpkgs/xpadneo/template
=> xpadneo: update to 0.9.6

srcpkgs/vpcs/patches/ldflags.patch, srcpkgs/vpcs/template
Fixes #43766 
- x86_64-musl (xbuild)
- i686-musl (xbuild)
- i686-libc (xbuild)
=> vpcs: update to 0.8.3 (GNS3's continuation fork)

srcpkgs/luarocks-lua53/template
=> luarocks-lua53: update to 3.11.0

srcpkgs/intel-ucode/template
Void is a couple of ucode verions behind. This updated fixes a few vulnerabilities
=> intel-ucode: update to 20240514.

srcpkgs/librtlsdr/template
=> librtlsdr: update to 2.0.2.

srcpkgs/libgbinder/template, srcpkgs/libglibutil/template
=> Waydroid updates (libglibutil 1.0.79 & libgbinder 1.1.39)

srcpkgs/haproxy/template, srcpkgs/haproxy/update
2.8.x is the latest LTS branch.
cc @zdykstra
=> haproxy: update to 2.8.9.

srcpkgs/digikam/template
adds dependancies on qt6-plugin-{sqlite,mysql} because digikam needs at least one of those to function.
- 86_64-musl
cannot be built on other archs because of webengine
=> digikam: update to 8.3.0, add dependancies on mysql and sqlite plugins

srcpkgs/netavark/template
=> netavark: update to 1.10.3.

srcpkgs/kakoune/template
- I built this PR locally for my native architecture: x86_64
- `build_wrksrc="src"` was removed because of [this change](https://github.com/mawww/kakoune/commit/b05295637e7dbe5239a1142a72afe8265e5d77c3#diff-3e2513390df543315686d7c85bd901ca9256268970032298815d2f893a9f0685)
=> kakoune: update to 2024.05.18.

common/hooks/pre-pkg/04-generate-runtime-deps.sh, common/shlibs, srcpkgs/lua54-lpeg/template, srcpkgs/neovim/patches/cmake-allow-build-type-none.patch, srcpkgs/neovim/patches/cross-build.patch, srcpkgs/neovim/patches/disable-parser-download.patch, srcpkgs/neovim/template
Neovim now depends on lua-lpeg as a library and dynamically links to it, but we don't serve it as a shlib.
=> neovim: update to 0.10.0

srcpkgs/tbb/template
- I built this PR locally for my native architecture, **aarch64-musl**
- x86_64
- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l-msul (cross)
This fixes a linker error when trying to build a project with tbbmalloc_proxy on musl systems
=> tbb: fix tbbmalloc_proxy on musl

srcpkgs/igraph/template
=> igraph: update to 0.10.12.

srcpkgs/libgcrypt/template
=> libgcrypt: update to 1.10.3.

srcpkgs/libwacom/template
Reverse dependencies built for all archs.
=> libwacom: update to 2.11.0.

srcpkgs/zk/template
Unfortunately they haven't made a new release since switching to the new org, so the `go_import_path` will be weird until the next release.
---
Closes #50398
=> New package: zk-0.14.0

srcpkgs/filelight/template
Without `kirigami-addons`, parts of the application (such as its about page) don't work properly. `kirigami-addons` already depends on `kf6-kirigami`, so `kf6-kirigami` it can be removed as an explicit dependency
-
=> filelight: add kirigami-addons as dependency

srcpkgs/curl/patches/install-curl-config-manpage.patch, srcpkgs/curl/template
=> curl: update to 8.8.0

srcpkgs/ferium/template
=> ferium: update to 4.5.2.

srcpkgs/rmilter/template
Currently calling `rmilter` will result in the following
```
[eater@named void-packages-2]$ rmilter
rmilter: symbol lookup error: rmilter: undefined symbol: ucl_object_iterate
```
Revbump fixes this
- I tested the changes in this PR: **YES*
=> rmilter: revbump for libucl

srcpkgs/evince/template
=> evince: update to 46.3

srcpkgs/rust-cargo-bloat/template
=> rust-cargo-bloat: update to 0.12.0.

srcpkgs/ntdsextract2/patches/no-cygwin-fs.patch, srcpkgs/ntdsextract2/template
- x86_64-musl
- aarch64
- armv7l
- i686
=> ntdsextract2: update to 1.2.1.

srcpkgs/sane/template
eSCL-speaking scanners that produce PDF-formatted output scan properly, but completion is only met with `sane_start: Invalid argument` expressed in various forms depending on front-end.
This is due to SANE being built without PDF support, provided by poppler-glib; this commit enables that as a default-on option, fixing support for those scanners.
- I tested the changes in this PR: **YES** (using an EPSON XP-325)
=> sane: fix PDF-producing eSCL scanners failing with `Invalid argument`

srcpkgs/lua51-luasocket/template, srcpkgs/lua51-unbound, srcpkgs/lua52-luasocket, srcpkgs/lua52-unbound, srcpkgs/lua53-luasocket, srcpkgs/lua53-unbound, srcpkgs/lua54-luasocket, srcpkgs/lua54-unbound/template, srcpkgs/lua54-unbound/update, srcpkgs/prosody/files/prosody.cfg.lua, srcpkgs/prosody/files/prosody/run, srcpkgs/prosody/template
- **New package: lua-unbound-1.0.0**
- **prosody: add lua51-unbound as a dependency**
- aarch64-musl
Crossbuilt from x86\_64-glibc and tested on aarch64-musl
Fixes the following warning that shows up when using prosodyctl (any
command):
```
**************************
Prosody was unable to find lua-unbound
This package can be obtained in the following ways:
Debian/Ubuntu | sudo apt install lua-unbound
luarocks | luarocks install …
```
=> prosody: update to 0.12.4.

srcpkgs/gnome-calendar/template
=> gnome-calendar: update to 46.1.

srcpkgs/chrony/template, srcpkgs/chrony/update
The chrony project has moved from tuxfamily to chrony-project.org
The update file is not needed since no distfile matches that ignore pattern.
~~feedback needed:~~
- ~~Would a URL the NEWS file on Gitlab be prefered over the existing news page? 
https://gitlab.com/chrony/chrony/-/raw/master/NEWS?ref_type=heads~~
- ~~Is pulling distfiles from gitlab preferable?~~
=> chrony: update URLs, remove update file.

srcpkgs/geteltorito/template
uni-koblenz.de has removed the page and/or all userpages; now redirects to a network status page and instructions to setup campus VPN.
There is no clear new homepage and no new distfiles, so using archive.org for now. The archived version has the same checksum.
The last build of the package was so long ago that the distfile was never saved by distfiles.voidlinux.org
=> geteltorito: update distfile and homepage URLs.

srcpkgs/stig/template
=> stig: update to 0.12.9a0

srcpkgs/docker-buildx/template
=> docker-buildx: update to 0.14.1.

srcpkgs/lsp-plugins-clap, srcpkgs/lsp-plugins-ladspa, srcpkgs/lsp-plugins-libs, srcpkgs/lsp-plugins-lv2, srcpkgs/lsp-plugins-vst2, srcpkgs/lsp-plugins-xdg, srcpkgs/lsp-plugins/template
Tested by me and @slimjimsoftware 
This helps unclutter things. @leahneukirchen can you take a look?
=> lsp-plugins: split subpkgs

srcpkgs/lv2/template
Drop the dependence on `gtk`, see https://gitlab.com/lv2/lv2/-/issues/57
@slimjimsoftware Can you also check this does not break audio in asahi?
=> lv2: do not makedepend on gtk2

srcpkgs/thunderbird/update
Before that change, `./xbps-src update-check thunderbird` returned `125.0` as version. Apart from that the previously used mozilla site just redirected to thunderbird.net anyways.
cc @dataCobra
=> thunderbird: fix update-check

srcpkgs/nasa-wallpaper/template
=> nasa-wallpaper: update to 2.1.0, adopt

srcpkgs/gnome-text-editor/template
- I tested the changes in this PR: **NOt yet**
- aarch64-musl
- armv7l-musl
=> gnome-text-editor: update to 46.3.

srcpkgs/gnome-calculator/template
=> gnome-calculator: update to 46.1.

srcpkgs/buku/template
=> buku: update to 4.9

srcpkgs/qt5/patches/qtbase-5.15.9-work-around-pyside2-brokenness.patch, srcpkgs/qt5/template
[ci skip]
python3-pyside2 was fixed a while back with qt 5.15.10/11 and then broke again over the past months.
The patch from OpenMandriva allows python3-pyside2 to build again (required for qt5-webengine / ffmpeg6).
A quick build and install on another machine with base void packages does not appear to affect qt5 programs from running.
=> qt5: patch to fix python3-pyside2 build. closes#50673

srcpkgs/weston/template
=> weston: update to 13.0.3.

srcpkgs/PrusaSlicer/template
=> PrusaSlicer: don't build tests when unneeded

srcpkgs/zathura/patches/fix_type_mismatch.patch, srcpkgs/zathura/template
zathura-0.5.6 crashes with `*** stack smashing detected ***: terminated` on i686.  This brings in the upstream fix.
Tested on i686
=> zathura: import fix for 32-bit

srcpkgs/ruby-thor/template, srcpkgs/ruby-tmuxinator/patches/xdg.patch, srcpkgs/ruby-tmuxinator/template
- x86_64-musl
- i686
Also adopting the package.
=> ruby-tmuxinator: update to 3.2.1 and let it work with tmux 3.4

srcpkgs/opera/template
=> opera: update to 110.0.5130.66

srcpkgs/perl-CGI/template
- I tested the changes in this PR: **briefly** (nothing to test here actually: fixing a test for older Perls)
- x86_64-musl
- i686
=> perl-CGI: update to 4.65

srcpkgs/python3-uvicorn/template
=> python3-uvicorn: update to 0.30.1

srcpkgs/stig/template
=> stig: update to 0.12.10a0

srcpkgs/python3-cairocffi/template, srcpkgs/python3-pywayland/template, srcpkgs/python3-pywlroots-0.16/update, srcpkgs/python3-pywlroots/template, srcpkgs/python3-pywlroots/update, srcpkgs/python3-qtile-extras/template, srcpkgs/qtile/template
Except the Wayland packages since I'm using xorg.
The new package is requirement to run Qtile on Wayland.
=> qtile and dependencies: update

srcpkgs/ruby-erubi/template, srcpkgs/ruby-tmuxinator/template
- x86_64-musl
- i686
After the last PR I forgot to change the dependency from ruby-erubis to ruby-erubi.
With this PR tmuxinator is finally working.
=> ruby-tmuxinator: not working because of wrong dependency

srcpkgs/python3-rapidfuzz/template
=> python3-rapidfuzz: update to 3.9.3

common/environment/setup/install.sh
also quote, fix tabs, and shellcheck the file
revival of #42850
re: @Chocimier's comment:
> How about pushing setting IFS down to cp call? We may need word splitting later on for vsv's LN_OPTS.
this does not work, it still splits the arguments if done at that level. also, `LN_OPTS` is a single word (either `-s` or `-sf`).
can be tested with, e.g.:
```diff
diff --git a/srcpkgs/chezmoi/template b/srcpkgs/chezmoi/template
index 1b5d674c14a..50e5b113e0a 100644
--- a/srcpkgs/chezmoi/template
+++ b/srcpkgs/chezmoi/template
@@ -21,6 +21,9 @@ pre_build() {
_date="$(date --utc --date "@$SOURCE_DATE_EPOCH" "+%Y-%m-%d")"
go_ldflags+=" -X main.date=${_date}"
fi
+       mkdir "foo bar"
+       for i in 1 2 3 4 5; do touch "foo bar/idk$i.bleh"; done
+ …
```
=> common/environment/setup/install.sh: fix v* funcs for paths with spaces

srcpkgs/apparmor/patches/libapparmor-basename.patch, srcpkgs/apparmor/template
=> apparmor: update to 3.1.7.

srcpkgs/radicale/INSTALL, srcpkgs/radicale/template
- Update to 3.2.1
- https://github.com/void-linux/void-packages/issues/38923
- x86_64-musl
- armv7l
This superseeds https://github.com/void-linux/void-packages/pull/46357.
=> radicale: update to 3.2.1, fix conf file permissions

srcpkgs/openldap/template
I have been using this package for long enough to feel confident in adopting it.
New since 2.6.6 (#48823 for 2.6.7 was not merged):
- fixes build for GCC 14
- a few OpenSSL 3 related fixes
- Other fixes can be seen at https://www.openldap.org/software/release/changes.html
- Have been using this version for the servers in my setup for a little over a week, no obvious issues
- I built this PR locally for my native architecture, (x86_64, x86_64-musl)
- aarch64-musl
- armv7l
- armv6l-musl
- i686
=> openldap: update to 2.6.8, adopt

srcpkgs/btop/template
=> btop: Update to 1.3.2

srcpkgs/biboumi/files/biboumi/run, srcpkgs/biboumi/patches/remove-git.patch, srcpkgs/biboumi/template
- This new package conforms to the package requirements: YES
Crossbuilt from x86_64-glibc to aarch64-musl and tested with
prosody-0.12.4 (packaged on #48919).
Resubmission after stalebot caught me slacking in #49051
=> New package: biboumi-9.0.

srcpkgs/python3-codespell/template
=> python3-codespell: update to 2.3.0.

srcpkgs/lc0/template
=> lc0: update to 0.31.0

srcpkgs/catch2/template
=> catch2: update to 3.6.0.

common/shlibs, srcpkgs/libopenrazer-devel, srcpkgs/libopenrazer/template, srcpkgs/razergenie/template
I received a report that the current `razergenie` is showing errors or not working. Here's an update. Since I don't use it, I'm keeping the packages labeled as "Orphaned".
---
- libopenrazer got split into a standalone project 
- This (libopenrazer) new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**
=> razergenie: update to 1.1.0

srcpkgs/astroid/patches/webkit2gtk41.patch, srcpkgs/astroid/template
@bitmeise Can you test this and verify if it works for you?
=> astroid: build with guri and webkit2gtk-4.1

srcpkgs/chatty/files/chatty, srcpkgs/chatty/patches/config_dir.patch, srcpkgs/chatty/patches/disable_version_check.patch, srcpkgs/chatty/template
- with the existence of the `java` alternatives group, I removed the setting of `$PATH` in the binary script. I tested that chatty works and runs on both jre8 and jre17.
- updated the patches to work on latest. the rationale for keeping the `config_dir` patch despite it not being required for the software to work is due to existing setups already using `.config/chatty` as the config dir from previous updates (as the patch has existed since this package's inception), thus preserving compatibility with them. if this is undesirable, let me know
=> chatty: update to 0.26.

srcpkgs/gnome-builder/template
=> gnome-builder: update to 46.2.

srcpkgs/tmux/template
Copying to the X11 clipboard from tmux has been failing since I updated to ncurses-6.5.
In ncurses 6.5, the `tparm` function fails if called with capability strings that do not come from the terminal description loaded by ncurses itself (see https://invisible-island.net/ncurses/announce.html#h4-fixes-library). This breaks tmux's use of terminfo overrides. Tmux 3.4 uses the new `tiparm_s` function (introduced in ncurses 6.5) to get around this, however this is only used if tmux is compiled against ncurses 6.5.
- aarch64  (crossbuild)
- armv6l-musl  (crossbuild)
- armv6l …
=> tmux: rebuild against ncurses-6.5

srcpkgs/rawtherapee/template
The application fails to start on my aarch64-musl device. I discovered that this is likely caused by tcmalloc.
Using tcmalloc doesn't seem to make a significant difference on other platforms, and its not enabled by default `CMakeLists.txt` so I think its best to remove it on all platforms
- I built this PR locally for my native architecture, x86_64-glibc, aarch64-musl
- x86_64-musl
- i686
- aarch64 (native + cross)
- aarch64-musl (native + cross)
=> rawtherapee: remove tcmalloc to fix crash on aarch64-musl

srcpkgs/eza/patches/downgrade-git2.patch, srcpkgs/eza/patches/fix-zsh-completions.patch, srcpkgs/eza/template
=> eza: update to 0.18.20

srcpkgs/dool/template
---
Fixes:
```sh
$ dool
zsh: /usr/bin/dool: bad interpreter: /usr/bin/python3: no such file or directory
```
=> dool: depend on python3

srcpkgs/xfce4-panel-profiles/template
Adapted from #40454 and would close #40306. Version, license are updated. I hope I get changelog section right.
Also, regarding the request change in https://github.com/void-linux/void-packages/pull/40454#discussion_r1103340631, it does not work with a warning complaining about `--sysconfdir=/etc` as it's not defined in gnu-configure build-style (but I'm not sure how other packages using the same build style get away  with it even though they include this configure argument).
=> New package: xfce4-panel-profiles-1.0.14

srcpkgs/openssh/patches/musl-connect.patch, srcpkgs/openssh/template
fixes CVE-2024-6387
> OpenSSH plans to remove support for the DSA signature algorithm in early 2025. This release disables DSA by default at compile time.
do we reënable it?
=> openssh: update to 9.8p1.

srcpkgs/virtualbox-ose/template
I'm updating it as support to kernel 6.9 was added on [7.0.16](https://www.virtualbox.org/wiki/Changelog-7.0#v16).
=> virtualbox-ose: update to 7.0.18

srcpkgs/rtl8812au-dkms/template
Allows building with 6.9.x
Built and installed on my machine with 6.9.7_1, plugged in dongle and wifi worked.
copied package to another machine on network with 6.9.6_1, installed.  driver loaded but didn't associate with a station, rebooted to 6.9.7_1 and automatically initialized and connected.
- x86_64
=> rtl8812au-dkms update to 20210820_1

srcpkgs/winegui/files/README.voidlinux, srcpkgs/winegui/template
Introducing WineGUI package. At last, a user-friendly Wine graphical interface. Follow up of: https://github.com/void-linux/void-packages/pull/48642 (I don't know why you closed it already, but OK. I hope you give others a bit more time).
I'm the developer of [WineGUI](https://gitlab.melroy.org/melroy/winegui).
I added a `README.voidlinux`, just like the Steam package. However, I hope there will be a **better solution** in the neat future. 
=> New package: winegui-2.5.0

srcpkgs/VirtualGL/template
=> VirtualGL: add aarch64 to list of supported archs

Manual.md, common/build-helper/qmake6.sh, srcpkgs/mkvtoolnix/template
=> mkvtoolnix: update to 85.0

srcpkgs/llvm18/template
=> llvm18: disable lto

srcpkgs/znc/template
=> znc: update to 1.9.1.

common/shlibs, srcpkgs/cpp-utilities/template, srcpkgs/syncthingtray/template
- **cpp-utilities: update to 5.25.0.**
- **syncthingtray: update to 1.5.5.**
=> syncthingtray

srcpkgs/nullmailer/template
=> nullmailer: bump to build with default log service

srcpkgs/MangoHud/template
Without this, using MangoHud-32bit on x86_64 hosts prevents some 32bit games from starting (E.g. Black Mesa). See [this issue][1] for details.
[1]: https://github.com/flightlessmango/MangoHud/issues/991
=> MangoHud: Adds missing multilib-32bit vulkan layer

common/shlibs, srcpkgs/digikam/template, srcpkgs/removed-packages/template
- **x86_64-musl**
Part of ffmpeg6 migration. digikam will need revbump for opencv-4.7.0 and ffmpeg6
=> qtav: remove for digikam 8.0.0+

srcpkgs/xfce4-panel-profiles/template
Solved this error in `.xsession-errors`, did not notice this before as I always have this dependency locally:
```python
File "/usr/share/xfce4-panel-profiles/xfce4-panel-profiles/xfce4-panel-profiles.py", line 44, in <module>
from panelconfig import PanelConfig
File "/usr/share/xfce4-panel-profiles/xfce4-panel-profiles/panelconfig.py", line 19, in <module>
import psutil
ModuleNotFoundError: No module named 'psutil'
```
=> xfce4-panel-profiles: fix missing depends

srcpkgs/python3-MyST-Parser/template
=> python3-MyST-Parser: update to 3.0.1.

srcpkgs/kqtquickcharts/template
- I built this PR locally for my native architecture, (x6_64-GLIBC)
=> kqtquickcharts: fix installation path (Fixes broken ktouch)

srcpkgs/syncthingtray/template
fixes error:
`Unable to load certificate "/home/$USER/.local/state/syncthing/https-cert.pem" when restoring settings`
@classabbyamp
=> syncthingtray: depend on qt6-plugin-tls-openssl

srcpkgs/python3-cairocffi/template, srcpkgs/python3-qtile-extras/template, srcpkgs/qtile/template
- I tested the changes in this PR: **YES** - except from qtile-wayland
=> qtile: update to 0.27.0, python3-qtile-extras: update to 0.27.0 and python3-cairocffi: update to 1.7.1

srcpkgs/helix/template
=> helix: specify installation runtime path explicitly

srcpkgs/xorg-video-drivers/template
xf86-video-intel is generally not recommended anymore
fixes #28864
on aarch64, it's probably very uncommon to have amd/nvidia gpu
=> xorg-video-drivers: prune dependencies

srcpkgs/folks/template
I had to disable tests for now,  because they fail with glib-2.80. see [here](https://gitlab.gnome.org/GNOME/folks/-/issues/140)
=> folks: update to 0.15.9

srcpkgs/virtiofsd/template
- I tested the changes in this PR: **YES** (Windows 11 guest)
=> virtiofsd: update to 1.11.1

srcpkgs/python3-python-multipart/template, srcpkgs/synapse/template
- **New package: python3-python-multipart-0.0.9**
Named with redundant `python-` to avoid potential future problems with
packaging https://pypi.org/project/multipart/
- **synapse: update to 1.111.0.**
=> synapse: update to 1.111.0.

srcpkgs/coq/template
Since https://github.com/void-linux/void-packages/commit/a69760e180448c31998369902b8524f476548f76, `coqide-server` is being built, but not installed. 
"`coqide-server` provides the `coqidetop` language server, an implementation of Coq's XML protocol which allows clients to interact with Coq in a structured way". It is essential to use Coq with an external editor such as [Coqtail](https://github.com/whonore/Coqtail) in vim.
=> coq: install coqide-server

srcpkgs/sx/template
I have tried to figure out whether there is a major difference between versions 3.0 and 3.0.0, because the checksum differs. The original source is [thankfully cached in sources.voidlinux.org](https://sources.voidlinux.org/sx-3.0.0/3.0.0.tar.gz), so I was able to diff the two archives. Although the archives themselves are different, their contents seem to be identical, so it should be safe to use the 3.0.0 version.
I am not sure whether XBPS will register `3.0.0 -> 3.0` as an update or not, but I don't think it matters.
=> sx: fix dead distfile

srcpkgs/flowblade/files/flowblade-wayland, srcpkgs/flowblade/template, srcpkgs/python3-libusb1/template
=> Flowblade update to 2.16.3

srcpkgs/python3-pyinfra/template
- Switched the `build_style` to `python3-pep517` because of the deprecation warning.
- Updated the dependencies from `setup.py`.
- Tried installing the shell completions, but at least the bash completion hung most of the time.
=> python3-pyinfra: update to 3.0.1

srcpkgs/gamescope/patches/0001-Include-limits.h-in-Process.cpp.patch, srcpkgs/gamescope/template
Gamescope upstream has made it very clear that they explicitly want distros to use their vendored dependencies, not system packages. This commit respects all their vendored dependencies.
This PR depends on #51341 as the latest gamescope depends on a newer version of libdecor than is currently packaged.
Thanks to @CaitCatDev for starting off the updated template. I've made some corrections to the dependencies and set `-Wno-error` specifically for the warnings that were causing problems building libliftoff and wlroots rather than turning off werror entirely.
=> gamescope: update to 3.14.24.

srcpkgs/cloud-guest-utils/template, srcpkgs/cloud-image-utils, srcpkgs/cloud-utils, srcpkgs/cloud-utils-ec2metadata
This is a pile of shell scripts and python scripts, but they're annoying to obtain if we don't package them.  The most important one in this bundle is growpart.
=> New package: cloud-utils-0.33.

srcpkgs/clojure-lsp/patches/remove-pgo.patch, srcpkgs/clojure-lsp/template, srcpkgs/clojure-lsp/update
[Clj-kondo](https://github.com/clj-kondo/clj-kondo) performs static analysis on Clojure, ClojureScript and EDN, without the need of a running REPL.
=> New package: clojure-lsp-2024.04.22

srcpkgs/stegseek/patches/portable-types.patch, srcpkgs/stegseek/template
=> New package: stegseek-0.6

srcpkgs/efm-langserver/template
[efm-langserver](https://github.com/mattn/efm-langserver) is a general purpose Language Server that can use specified error message format generated from specified command.
=> New package: efm-langserver-0.0.52

srcpkgs/cpufetch/template
- I built this PR locally for my native architecture, (x84_64-glibc)
- x86_64-musl (X)
- i686 (X)
- i686-musl (X)
Follows #32612, closes #32305. In theory it should work on `ppc*` and `arm*`, but it won't build successfully for me due to the `-mavx*` flag.
=> New package: cpufetch-1.05

srcpkgs/gping/template, srcpkgs/gping/update
=> gping: update to 1.17.3.

srcpkgs/UxPlay/files/README.voidlinux, srcpkgs/UxPlay/template
Spiritual successor to #33191.
- x86_64-musl
> UxPlay's GPLv3 license does not have an added "GPL exception" explicitly allowing it to be distributed in compiled form when linked to OpenSSL versions prior to v. 3.0.0 (older versions of OpenSSL have a license clause incompatible with the GPL unless OpenSSL can be regarded as a "System Library", which it is in *BSD). Many Linux distributions treat OpenSSL as a "System Library", but some …
=> New package: UxPlay-1.68.3

srcpkgs/river/template
- I tested the changes in this PR: **NOT YET**
- x86_64-musl
- i686
=> river: update to 0.3.5.

srcpkgs/cloud-guest-utils/files/10-resize-root.sh, srcpkgs/cloud-guest-utils/files/README.voidlinux, srcpkgs/cloud-guest-utils/files/growpart.default, srcpkgs/cloud-guest-utils/template
- I tested the changes in this PR: **YES** (with mklive packer)
doesn't have deps on f2fs-tools or xfsprogs but `base-{container-full,system}` both do so probably not an issue
=> cloud-guest-utils: add core-service for resizing rootfs

common/shlibs, srcpkgs/breeze-icons/template, srcpkgs/kf6-kiconthemes/template, srcpkgs/libbreeze-icons, srcpkgs/libbreeze-icons-devel
kf6-kiconthemes is required by many packages and requires libKF6BreezeIcons.so.6. On the other hand I do ignorepkg breeze-icons for some time.
Split so they can be installed separately.
cc @Johnnynator 
=> libbreeze-icons: split from breeze-icons

srcpkgs/SPIRV-Headers/template, srcpkgs/SPIRV-Tools/template
- **SPIRV-Headers: update to 1.3.290.0.**
- **SPIRV-Tools: update to 2024.3.**
- x86_64-musl
- i686
=> SPIRV-Tools: Update to 2024.3.

srcpkgs/btrfs-progs/template
=> btrfs-progs: update to 6.9.2.

srcpkgs/gopass/template
run tests
disable unexistent path (otherwise it produces a warning)
build as pie (as it's done in the upstream makefile)
cc @fnogcps
=> gopass: run tests, remove useless path, build as pie

srcpkgs/chirp/template
The currently-packaged version of chirp is broken due to python3.12's removal of `imp`. The latest version resolves that (and no longer depends on `python3-future`)
cc @realcharmer 
=> chirp: update to 20240706.

srcpkgs/ruby-tmuxinator/template, srcpkgs/zsh-completions/template
=> ruby-tmuxinator: fix naming of completion file

srcpkgs/libavif/template
`pkg-config` errors out for `libavif` otherwise because `libaom` is required
=> libavif: add missing libaom dependecy to -devel

srcpkgs/libjxl/template
cc @joshuakraemer
`pkg-config` errors out for `libjxl` otherwise because `highway` is required
=> libjxl: add missing highway dependency to -devel

srcpkgs/afl++/template
- I built this PR locally for my native architecture, x86_64-glibc, aarch64-musl
- x86_64-musl
- i686
- aarch64 (cross + native)
- aarch64-musl (cross + native)
=> afl++: build with llvm18, add aarch64

common/shlibs, srcpkgs/btdu/template, srcpkgs/gtkd/template, srcpkgs/ldc/template, srcpkgs/onedrive/template, srcpkgs/tilix/patches/disable-appstream-test.patch, srcpkgs/tilix/template
- **ldc: update to 1.39.0**
- **btdu: rebuild for ldc**
- **gtkd: rebuild for ldc**
- **onedrive: rebuild for ldc**
- **tilix: rebuild for ldc**
=> ldc: update to 1.39.0

srcpkgs/rootlesskit/template
=> rootlesskit: update to 2.2.0.

srcpkgs/wiki-tui/template
For #51458
Future versions of this package appear not to depend on `time-rs`.
=> wiki-tui: update time-rs for rust 1.80

srcpkgs/tuxedo-drivers/template
Built for kernels 5.15, 5.16, 5.18, 5.19, 6.0–6.9; running on 6.9.11.
=> tuxedo-drivers: update to 4.6.1

srcpkgs/newsboat/template
=> newsboat: update to 2.36.

srcpkgs/python3-openpyxl/template
Notes:
- Mostly bugfixes according to [changelog](https://openpyxl.readthedocs.io/en/stable/changes.html#id1). Checks passed locally.
- Adjusted template a bit.
- BTW, it's also an optional dep for visidata to read from XLSX files (see [setup.py](https://github.com/saulpw/visidata/blob/v3.0.2/setup.py)), but as visidata template seems to miss a lot of extra deps, I'm not adding it explicitly.
=> python3-openpyxl: update to 3.1.3.

srcpkgs/osc/template
=> osc: update to 1.8.3

srcpkgs/nasa-wallpaper/template
=> nasa-wallpaper: update to 2.1.1

srcpkgs/tuxedo-drivers/patches/kernel6.10.patch, srcpkgs/tuxedo-drivers/template
- x86_64-musl
- i686
@newbluemoon 
Added a patch from the AUR package which is maintained by a TuxedoComputers employee.
=> tuxedo-drivers: fix building on kernel 6.10

srcpkgs/lite-xl/template
Default one eats 100% cpu just from mouse movement.
- I built this PR locally for my native architecture, (ARCH-LIBC) amd64
=> lite-xl: enable SDL renderer
