void-linux/void-packages

srcpkgs/qownnotes/template
=> qownnotes: update to 24.2.1

srcpkgs/attract/patches/Makefile.patch, srcpkgs/attract/patches/string.patch, srcpkgs/attract/template
=> attract: update to 2.7.0.

srcpkgs/oil/template
=> oil: update to 0.20.0.

srcpkgs/guake/template
- aarch64-musl **cross**
- armv7l **cross**
=> guake: update to 3.10.

srcpkgs/numbat/template
=> numbat: update to 1.10.1

srcpkgs/terraform-ls/template
=> terraform-ls: update to 0.32.6.

srcpkgs/SwayNotificationCenter/template
=> SwayNotificationCenter: update to 0.10.0

srcpkgs/OpenCL-CLHPP/template
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **Maybe?** (its mostly just header files)
=> New package: OpenCL-CLHPP-2023.12.14

srcpkgs/srain/template
=> srain: update to 1.6.0.

srcpkgs/hg-evolve/template
=> hg-evolve: update to 11.1.1.

srcpkgs/expat/template
=> expat: add changelog

srcpkgs/xz/template, srcpkgs/xz/update
=> xz: update to 5.4.6.

srcpkgs/just/template
=> just: update to 1.24.0

srcpkgs/vte3/template, srcpkgs/vte3/update
=> vte3: update to 0.74.2.

srcpkgs/zsh-syntax-highlighting/template
Tested this on x86_64 glibc, but its a shell script, should work on everything
=> zsh-syntax-highlighting: update to 0.8.0.

srcpkgs/moar/template
=> moar: update to 1.23.5

srcpkgs/crun/template
=> crun: update to 1.14.1

srcpkgs/neovim-qt/template
=> neovim-qt: update to 0.2.18.

srcpkgs/vscode/template
=> vscode: update to 1.86.1

srcpkgs/nemo/template
I cannot maintain `nemo` since it's stuck with zero feedback on #47725 (Cinnamon 6.0) and my interest starting to shift away from tiling window managers/nemo to other things.
If someone else is interested in maintaining it you're welcome to adopt :)
=> Orphan nemo

srcpkgs/desktop-file-utils/template
=> desktop-file-utils: update to 0.27

srcpkgs/python3.11/files/EXTERNALLY-MANAGED, srcpkgs/python3.11/template, srcpkgs/python3/files/EXTERNALLY-MANAGED, srcpkgs/python3/template
=> python3: fix path virtual environment message

srcpkgs/slack-desktop/template
Also fixed a typo I made for my email address.
=> slack-desktop: update to 4.36.140.

srcpkgs/limine/template
=> limine: update to 7.0.4.

srcpkgs/python3-platformdirs/template
=> python3-platformdirs: update to 4.2.0.

srcpkgs/python3-path/template
=> python3-path: update to 16.10.0.

srcpkgs/rust-analyzer/template
=> rust-analyzer: update to 2024.02.05.

srcpkgs/openshot/template
=> openshot: update to 3.1.1.

srcpkgs/python3-parse/template
=> python3-parse: update to 1.20.1.

srcpkgs/python3-openai/template
=> python3-openai: update to 1.12.0

srcpkgs/platformio/template
=> platformio: update to 6.1.13

srcpkgs/vimb/template
=> vimb: update to 3.7.0

srcpkgs/python3-phonenumbers/template, srcpkgs/synapse/template
=> synapse: update to 1.101.0.

srcpkgs/gitea/template
=> gitea: update to 1.21.5

srcpkgs/python3-starlette/template
=> python3-starlette: update to 0.37.1

srcpkgs/fwupd/template
=> fwupd: update to 1.9.13

srcpkgs/eza/template
=> eza: update to 0.18.3

srcpkgs/mercurial/template
=> mercurial: update to 6.6.3.

srcpkgs/pcsc-cyberjack/template
=> New package: pcsc-cyberjack-3.99.5

srcpkgs/file-roller/patches/fix-7zip-asking-password.patch, srcpkgs/file-roller/template
@Gottox 
closes #48737 
- I tested the changes in this PR: **YES** (without patch) and **briefly** (with patch)
- armv7l x
=> file-roller: update to 43.1, fix 7zip

srcpkgs/fwupd-efi/patches/cc-as-ld.patch, srcpkgs/fwupd-efi/template, srcpkgs/gnu-efi-libs/patches/no-werror.patch, srcpkgs/gnu-efi-libs/template
=> fwupd-efi: update to 1.4.

srcpkgs/cliphist/template
=> cliphist: update to 0.5.0

srcpkgs/gvfs/template
=> gvfs: update to 1.52.2

srcpkgs/lychee/template
=> lychee: update to 0.14.3.

srcpkgs/python3-jaraco.logging/template
=> python3-jaraco.logging: update to 3.3.0.

srcpkgs/pre-commit/template
=> pre-commit: update to 3.6.1.

srcpkgs/offpunk/template
=> offpunk: update to 2.2.

srcpkgs/webp-pixbuf-loader/template
=> webp-pixbuf-loader: update to 0.2.7.

srcpkgs/ristretto/template
=> ristretto: update to 0.13.2.

srcpkgs/xfce4-whiskermenu-plugin/template
=> xfce4-whiskermenu-plugin: update to 2.8.3.

srcpkgs/ca-certificates/template, srcpkgs/nss/template
=> nss: update to 3.98.

srcpkgs/mousepad/template
=> mousepad: update to 0.6.2.

srcpkgs/opera/template
=> opera: update to 107.0.5045.21.

srcpkgs/libxfce4util/template
=> libxfce4util: update to 4.18.2.

srcpkgs/qemu-user-static/template, srcpkgs/qemu/patches/mmap-mremap-efault.patch, srcpkgs/qemu/template
=> qemu: update to 8.1.5.

srcpkgs/gscreenshot/template
=> gscreenshot: update to 3.4.2.

srcpkgs/cargo-about/template
=> cargo-about: update to 0.6.1.

srcpkgs/docker-compose/template
=> docker-compose: update to 2.24.6, adopt

srcpkgs/neomutt/template
=> neomutt: update to 20240201.

srcpkgs/xsecurelock/template
=> xsecurelock: update to 1.9.0

srcpkgs/yq-go/template
=> yq-go: update to 4.41.1.

srcpkgs/git-cliff/patches/downgrade-git2.patch, srcpkgs/git-cliff/template
=> git-cliff: update to 2.0.2

srcpkgs/pex/template
=> pex: update to 2.2.1.

srcpkgs/libgssglue/template
=> libgssglue: update to 0.9

srcpkgs/gdu/template
=> gdu: update to 5.27.0.

srcpkgs/ast-grep/template
=> ast-grep: update to 0.19.0.

srcpkgs/gping/template
=> gping: update to 1.16.1.

srcpkgs/xerces-c/patches/fix-configure-cross.patch, srcpkgs/xerces-c/template
=> xerces-c: update to 3.2.5.

srcpkgs/wl-mirror/template
=> wl-mirror: update to 0.16.1.

srcpkgs/gifsicle/template
=> gifsicle: update to 1.95

srcpkgs/mise/template
=> mise: update to 2024.2.5.

srcpkgs/openconnect/template
=> openconnect: update to 9.12

srcpkgs/udiskie/template
=> udiskie: update to 2.5.2.

srcpkgs/liburing/template
=> liburing: update to 2.5.

srcpkgs/sysdig/patches/falcosecurity-libs-stdint.patch, srcpkgs/sysdig/template
=> sysdig: fix build on musl

srcpkgs/gogs/template
=> gogs: update to 0.13.0.

srcpkgs/trurl/template
=> trurl: update to 0.10

srcpkgs/ruff/template
=> ruff: update to 0.2.2.

srcpkgs/ibus-chewing/template
=> New package: ibus-chewing

srcpkgs/intellij-idea-community-edition/template
=> intellij-idea-community-edition: update to 2023.3.4.

srcpkgs/beancount/template, srcpkgs/fava/template
=> fava: update to 1.27.2.; beancount: fix deps.

srcpkgs/zfs/patches/0002-fix-seektest-musl.patch, srcpkgs/zfs/template
=> zfs: update to 2.2.3.

srcpkgs/pango/template
=> pango: update to 1.51.2

srcpkgs/dasel/template
=> dasel: update to 2.6.0.

srcpkgs/eza/template
=> eza: update to 0.18.4

srcpkgs/fend/template
=> fend: update to 1.4.3

srcpkgs/hyperrogue/template
=> hyperrogue: update to 13.0b

srcpkgs/pre-commit/template
=> pre-commit: update to 3.6.2.

srcpkgs/tailscale/template
@nilium mind if I adopt this package?
=> tailscale: update to 1.60.0.

srcpkgs/meson/template
=> meson: update to 1.3.2.

srcpkgs/stockfish/patches/makefile.patch, srcpkgs/stockfish/template
=> stockfish: update to 16.1

srcpkgs/librsvg/template
=> librsvg: update to 2.57.1.

srcpkgs/lighttpd/template
lighttpd: update to 1.4.74
I tested the changes in this PR: NO
(build-tested elsewhere: on openwrt)
=> lighttpd: update to 1.4.74

srcpkgs/rawtherapee/template
=> rawtherapee: update to 5.10, adopt

srcpkgs/texlab/template
=> texlab: update to 5.12.4

srcpkgs/gitui/template
=> gitui: update to 0.25.1

srcpkgs/opera/template
=> opera: update to 107.0.5045.36.

srcpkgs/foliate/template
=> foliate: update to 3.1.0.

srcpkgs/balsa/patches/gtk-iconcache.patch, srcpkgs/balsa/patches/libwebkit2gtk41.patch, srcpkgs/balsa/template
=> balsa: update to 2.6.4.

srcpkgs/gfeeds/patches/fix-for-blueprint-0.8.patch, srcpkgs/gfeeds/patches/upgrade-blueprint-0.8-syntax.patch, srcpkgs/gfeeds/template, srcpkgs/python3-syndom/patches/add-author-extraction-for-feed-item.patch, srcpkgs/python3-syndom/template
=> gfeeds: update to 2.2.0, adopt

srcpkgs/autotiling/template
=> autotiling: update to 1.9.1.

srcpkgs/jd/template
=> jd: update to 1.8.1.

srcpkgs/atuin/template
=> atuin: update to 18.0.2

srcpkgs/iwd/template
=> iwd: update to 2.15

srcpkgs/fcft/template
=> fcft: update to 3.1.8

srcpkgs/pango/template
=> pango: update to 1.52.0

srcpkgs/NetworkManager/patches/fix-cross-gir.patch, srcpkgs/NetworkManager/patches/no-gtk-doc.patch, srcpkgs/NetworkManager/template
=> NetworkManager: update to 1.46.0

srcpkgs/tbb/template
=> tbb: remove libatomic-devel makedepends

srcpkgs/sakura/template
=> sakura: update to 3.8.7, adopt

srcpkgs/python3-syndom/update
=> python3-syndom: fix update-check

srcpkgs/zfs-lts/patches/0003-fix-seektest-musl.patch, srcpkgs/zfs-lts/template
=> zfs-lts: update to 2.1.15.

srcpkgs/tbb/template
=> tbb: fix configure_args on x86_64*/aarch64*.

srcpkgs/nushell/patches/0001-use-system-libraries.patch, srcpkgs/nushell/template
=> nushell: update to 0.90.1

srcpkgs/python3-watchdog/template
=> python3-watchdog: update to 4.0.0.

srcpkgs/zoxide/template
=> zoxide: update to 0.9.4

srcpkgs/tree-sitter/template
=> tree-sitter: update to 0.21.0

srcpkgs/azote/template
=> azote: update to 1.12.5

srcpkgs/nwg-look/template
=> nwg-look: update to 0.2.7

srcpkgs/vivaldi/template
=> vivaldi: update to 6.6.3271.45

srcpkgs/gopls/template
=> gopls: update to 0.15.1.

srcpkgs/emptty/template
=> emptty: update to 0.12.0

srcpkgs/czkawka/template
=> czkawka: update to 7.0.0

srcpkgs/broot/template
=> broot: update to 1.34.0

srcpkgs/ast-grep/template
=> ast-grep: update to 0.19.3.

srcpkgs/chess-tui/template
=> chess-tui: update to 1.2.0.

srcpkgs/tlpui/template
=> tlpui: update to 1.6.4.

srcpkgs/pnpm/template
=> pnpm: update to 8.15.4.

srcpkgs/pdf.js/template
This update reorganizes some things, and I'm not sure if some clients will break.
- I tested the changes in this PR: **YES** (for Qutebrowser)
=> pdf.js: update to 4.0.379.

srcpkgs/xz/template
=> xz: update to 5.6.0.

srcpkgs/sq/template
=> sq: update to 0.47.4.

srcpkgs/git-absorb/template
=> git-absorb: update to 0.6.12.

srcpkgs/eza/template
=> eza: update to 0.18.5

srcpkgs/gns3-gui/template, srcpkgs/gns3-server/template
- I built this PR locally for my native architecture, (x84_64-glibc)
=> GNS3 2.2.46

srcpkgs/remind/template
=> remind: update to 04.03.01, add changelog

srcpkgs/hyperrogue/template
=> hyperrogue: update to 13.0c

srcpkgs/cargo-modules/template
=> cargo-modules: update to 0.13.6.

srcpkgs/vale/template
=> vale: update to 3.1.0.

srcpkgs/rust-analyzer/template
=> rust-analyzer: update to 2024.02.26.

srcpkgs/gallery-dl/template
=> gallery-dl: update to 1.26.8.

srcpkgs/hexchat/patches/url_delim.patch, srcpkgs/hexchat/patches/whox_colon.patch, srcpkgs/hexchat/template
=> hexchat: update to 2.16.2.

srcpkgs/rust-sccache/template
=> rust-sccache: update to 0.7.7.

srcpkgs/limine/template
=> limine: update to 7.0.5.

srcpkgs/feh/template
Tagging the maintainer @steinex 
=> feh: update to 3.10.2

srcpkgs/gradle/template
=> gradle: update to 8.6.

srcpkgs/OpenRCT2/template
=> OpenRCT2: update to 0.4.8.

srcpkgs/k9s/template
=> k9s: update to 0.31.7.

srcpkgs/python3-cssutils/template
- I tested the changes in this PR: **BRIEFLY**
=> python3-cssutils: update to 2.9.0.

srcpkgs/fwupd/template
=> fwupd: update to 1.9.14.

srcpkgs/wps-office/template
Also:
- change the homepage (old no longer available).
=> wps-office: update to 11.1.0.11719.

srcpkgs/SDL2_image/template
- I built this PR locally for my native architecture,x86_64-glibc
=> SDL2_image: update to 2.8.2.

srcpkgs/composer8.1/template, srcpkgs/composer8.2/template, srcpkgs/composer8.3/template
- composer8.1: update to 2.7.1.
- composer8.2: update to 2.7.1.
- composer8.3: update to 2.7.1.
=> composer*: update to 2.7.1.

srcpkgs/qgis/template
=> qgis: update to 3.34.4.

srcpkgs/remind/template
=> remind: update to 04.03.02.

srcpkgs/carapace/template
=> carapace: update to 0.30.2.

srcpkgs/python3-virtualenv/template
=> python3-virtualenv: update to 20.25.1.

srcpkgs/nvtop/template
=> nvtop: update to 3.1.0

srcpkgs/qtractor/template
=> qtractor: update to 0.9.39

srcpkgs/steamguard-cli/template
- I built this PR locally for my native architecture, ( x86_64-glibc)
=> steamguard-cli: update to 0.12.6

srcpkgs/speech-dispatcher/template
=> speech-dispatcher: update to 0.11.5.

srcpkgs/postgis-postgresql15/template, srcpkgs/postgis-postgresql16/template, srcpkgs/postgresql15/template, srcpkgs/postgresql16/template
=> postgresql16: update to 16.2.

srcpkgs/elvish/template
=> elvish: update to 0.20.1.

srcpkgs/orc/template
=> orc: update to 0.4.38

srcpkgs/xournalpp/template
=> xournalpp: update to 1.2.3.

srcpkgs/xkeyboard-config/template
=> xkeyboard-config: update to 2.41.

srcpkgs/pex/template
=> pex: update to 2.2.2.

srcpkgs/ruff/template
=> ruff: update to 0.3.0.

srcpkgs/xarchiver/template
=> xarchiver: update to 0.5.4.23.

srcpkgs/igraph/template
=> igraph: update to 0.10.10.

srcpkgs/giac/template
=> giac: update to 1.9.0.93.

srcpkgs/tox/patches/fix-testing.patch, srcpkgs/tox/template
=> tox: update to 4.13.0.

srcpkgs/SuiteSparse/template
=> SuiteSparse: update to 7.6.1.

srcpkgs/vale/template
=> vale: update to 3.2.1.

srcpkgs/git-cliff/template
=> git-cliff: update to 2.1.2

srcpkgs/iwd/template
=> iwd: update to 2.16

srcpkgs/github-cli/template
=> github-cli: update to 2.45.0

srcpkgs/libshumate/template
=> libshumate: update to 1.1.3

srcpkgs/snapshot/template
**MERGE FIRST:**
- #48884
This app is a part of `gnome-45.4` #48762
- armv7l x
=> New package: snapshot-45.2

srcpkgs/mqttcli/template
=> New package: mqttcli-0.2.0.

srcpkgs/python3-annotated-types/template, srcpkgs/python3-dirty-equals/patches/no-pytest-filterwarnings.patch, srcpkgs/python3-dirty-equals/template, srcpkgs/python3-email-validator/template, srcpkgs/python3-inflect/patches/fix-test.patch, srcpkgs/python3-inflect/template, srcpkgs/python3-pydantic-core/template, srcpkgs/python3-pydantic/patches/drop-fancy-pypi-readme-dep.patch, srcpkgs/python3-pydantic/template, srcpkgs/python3-pydantic/update
Need to test these packages depending on python3-pydantic:
=> python3-pydantic: update to 2.4.2.

srcpkgs/gnome-music/template
=> gnome-music: update to 45.1

srcpkgs/direnv/template
=> direnv: update to 2.34.0.

srcpkgs/dk/template
- aarch64
- aarch64-musl
- armv6l
- armv6l-musl
=> dk: update to 2.0.

srcpkgs/fend/template
=> fend: update to 1.4.4

srcpkgs/halloy/template
=> halloy: update to 2024.3

srcpkgs/stremio-shell/template
=> stremio-shell: update to 4.4.165.

srcpkgs/vscode/template
=> vscode: update to 1.87.0

srcpkgs/broot/template
=> broot: update to 1.35.0

srcpkgs/citations/template
=> citations: update to 0.6.2

srcpkgs/crun/template
=> crun: update to 1.14.4

srcpkgs/texinfo/patches/fix-configure-on-cross.patch, srcpkgs/texinfo/template
=> texinfo: update to 7.1.

common/shlibs, srcpkgs/gnome-builder/patches/fix-gtk4-4.12.5.patch, srcpkgs/gnome-builder/template, srcpkgs/libdex/template, srcpkgs/libdex/update, srcpkgs/libpanel/template, srcpkgs/libpanel/update, srcpkgs/libpeas/update, srcpkgs/libpeas2-devel, srcpkgs/libpeas2/template, srcpkgs/libpeas2/update, srcpkgs/libsysprof, srcpkgs/sysprof-cli, srcpkgs/sysprof/patches/musl-missing-include.patch, srcpkgs/sysprof/template
=> gnome-builder: update to 45.0.

srcpkgs/PrismLauncher/template
=> PrismLauncher: update to 8.2.

srcpkgs/openpgp-card-tools/template
=> openpgp-card-tools: update to 0.10.0.

srcpkgs/pango/template
=> pango: update to 1.52.1

srcpkgs/pixman/template
=> pixman: update to 0.43.4.

srcpkgs/ddgr/template
=> ddgr: update to 2.2.

srcpkgs/easyeffects/template
=> easyeffects: update to 7.1.4

srcpkgs/eza/template
=> eza: update to 0.18.6

srcpkgs/ImageMagick/template, srcpkgs/php8.1-imagick/template, srcpkgs/php8.2-imagick/template, srcpkgs/php8.3-imagick/template
=> ImageMagick: update to 7.1.1.29.

srcpkgs/pipe-viewer/template
=> pipe-viewer: update to 0.5.0.

srcpkgs/SDL2/template
=> SDL2: update to 2.30.1.

srcpkgs/xkbcomp/template
=> xkbcomp: update to 1.4.7.

srcpkgs/synapse/patches/setuptools_rust_upperbound.patch, srcpkgs/synapse/template
=> synapse: update to 1.102.0.

srcpkgs/wmutils-core/patches/install-pdw-manpage.patch, srcpkgs/wmutils-core/template
=> wmutils-core: update to 1.7.

srcpkgs/ascii/template
=> ascii: update to 3.20, adopt

srcpkgs/rust-analyzer/template
=> rust-analyzer: update to 2024.03.04.

srcpkgs/leiningen/template
=> leiningen: update to 2.11.2.

srcpkgs/android-studio/template
=> android-studio: update to 2023.2.1.23.

srcpkgs/mold/patches/test-target-machine.patch, srcpkgs/mold/template
Use system tbb now that we have a recent enough version.
---
cc @wangp
=> mold: update to 2.4.1

srcpkgs/grex/template
=> grex: update to 1.4.5.

srcpkgs/rust-cargo-audit/template
=> rust-cargo-audit: update to 0.20.0.

srcpkgs/procs/template
=> procs: update to 0.14.5

srcpkgs/bemenu/template
=> bemenu: update to 0.6.20

srcpkgs/grype/template, srcpkgs/syft/template
=> syft: update to 1.0.1; grype: update to 0.74.7

srcpkgs/uacme/patches/fix-cross.patch, srcpkgs/uacme/template
=> uacme: update to 1.7.5

srcpkgs/osv-scanner/template
=> osv-scanner: update to 1.7.0.

srcpkgs/riff/template
=> riff: update to 3.0.0.

srcpkgs/vivaldi/template
=> vivaldi: update to 6.6.3271.48

srcpkgs/inkscape/update
=> inkscape: improve update detection

srcpkgs/ntfy/template
=> ntfy: update to 2.9.0.

srcpkgs/steamguard-cli/template
=> steamguard-cli: update to 0.13.0

srcpkgs/revive/template
=> revive: update to 1.3.7.

srcpkgs/fonttools/template
=> fonttools: update to 4.49.0.

srcpkgs/sof-firmware/template
=> sof-firmware: update to 2023.12.1

srcpkgs/difftastic/template
=> difftastic: update to 0.56.1.

srcpkgs/qsv/template
=> qsv: update to 0.123.0.

srcpkgs/vscode/template
=> vscode: update to 1.87.1

srcpkgs/zoom/template
=> zoom: update to 5.17.11.3835

srcpkgs/pidgin/template
=> pidgin: update to 2.14.13.

srcpkgs/xonsh/template
=> xonsh: update to 0.15.1

srcpkgs/broot/template
=> broot: update to 1.36.0

srcpkgs/ddclient/files/ddclient/run, srcpkgs/ddclient/template
=> ddclient: update to 3.11.2.

srcpkgs/hg-evolve/template
=> hg-evolve: update to 11.1.2.

srcpkgs/sq/template
=> sq: update to 0.48.1.

srcpkgs/texlab/template
=> texlab: update to 5.13.0

srcpkgs/ruff/template
=> ruff: update to 0.3.2.

srcpkgs/wslu/template
=> wslu: update to 4.1.2

srcpkgs/numbat/template
=> numbat: update to 1.11.0

srcpkgs/just/template
=> just: update to 1.25.2

srcpkgs/sddm/template
=> sddm: update to 0.21.0.

common/shlibs, srcpkgs/AppStream-compose, srcpkgs/AppStream-compose-devel, srcpkgs/AppStream-qt-devel, srcpkgs/AppStream/template, srcpkgs/debugedit/template, srcpkgs/flatpak-builder/template, srcpkgs/flatpak/template, srcpkgs/gnome-software/patches/0001-port-to-appstream1.patch, srcpkgs/gnome-software/template, srcpkgs/libadwaita/template
=> flatpak-builder: update to 1.4.2.

srcpkgs/atuin/template
=> atuin: update to 18.1.0

srcpkgs/tree-sitter/template
=> tree-sitter: update to 0.22.1

srcpkgs/mdcat/template
=> mdcat: update to 2.1.2

srcpkgs/acme-client/template
=> acme-client: update to 1.3.3

srcpkgs/joker/template
=> joker: update to 1.3.5.

srcpkgs/python3-lsp-server/template
=> python3-lsp-server: update to 1.10.0.

srcpkgs/discord/template
=> discord: update to 0.0.45

srcpkgs/typstfmt/template
=> typstfmt: update to 0.2.9

srcpkgs/gopass-jsonapi/template, srcpkgs/gopass/template
=> gopass{,-jsonapi}: update to 1.15.11.

srcpkgs/rustup/template
=> rustup: update to 1.27.0

srcpkgs/flake8/template, srcpkgs/python3-pycodestyle/template, srcpkgs/python3-pyflakes/template
=> flake8: update to 7.0.0.

srcpkgs/gthumb/template
=> gthumb: update to 3.12.6, orphan.

srcpkgs/fend/template
=> fend: update to 1.4.5

srcpkgs/linux-firmware/template
=> linux-firmware: update to 20240312.

srcpkgs/Clight/template, srcpkgs/Clightd/template
=>  Clightd: update to 5.9; Clight: update to 4.11.

srcpkgs/rclone/template
=> rclone: update to 1.66.0.

srcpkgs/lighttpd/template
lighttpd: update to 1.4.75
I tested the changes in this PR: NO
(build-tested elsewhere: on openwrt)
=> lighttpd: update to 1.4.75

srcpkgs/geeqie/patches/fix-musl.patch, srcpkgs/geeqie/template
=> geeqie: update to 2.3.

srcpkgs/cocogitto/patches/downgrade-git2.patch, srcpkgs/cocogitto/template
=> cocogitto: update to 6.1.0

srcpkgs/eza/template
=> eza: update to 0.18.7

srcpkgs/python3-starlette/template
=> python3-starlette: update to 0.37.2

srcpkgs/composer8.1/template, srcpkgs/composer8.2/template, srcpkgs/composer8.3/template
=> composer*: update to 2.7.2.

srcpkgs/fuzzypkg/template
=> fuzzypkg: update to 1.0.11.

srcpkgs/bemenu/template
=> bemenu: update to 0.6.21

srcpkgs/scdoc/template
=> scdoc: update to 1.11.3

srcpkgs/nghttp2/template
=> nghttp2: update to 1.60.0.

srcpkgs/vale-style-microsoft/template
=> vale-style-microsoft: update to 0.13.0.

srcpkgs/bird/template
- aarch64-musl
- armv7l
- armv6l-musl
=> bird: update to 2.15

srcpkgs/diffoscope/template
=> diffoscope: update to 260.

srcpkgs/fzf/template
=> fzf: install fzf-tmux.1 manual

srcpkgs/clojure/template, srcpkgs/clojure/update
=> clojure: update to 1.11.2.1446.

srcpkgs/wget/template
=> wget: update to 1.24.5

srcpkgs/libxcb/template
=> libxcb: update to 1.16.1.

srcpkgs/n/files/README.voidlinux, srcpkgs/n/template
=> n: update to 9.2.1

srcpkgs/halloy/template
=> halloy: update to 2024.4

srcpkgs/lynis/template
=> lynis: update to 3.0.9.

srcpkgs/lynis/template
=> lynis: update to 3.1.0.

srcpkgs/mkinitcpio-nfs-utils/files/initcpio-install-net, srcpkgs/mkinitcpio-nfs-utils/template
=> mkinitcpio-nfs-utils: fix hook on musl

srcpkgs/AppStream/patches/cross.patch, srcpkgs/AppStream/template
=> AppStream: fix library path in cmake files

srcpkgs/uv/template
~~**TODO:** devendor some `-sys` crates? (noticed a few in the log, like libz, libssh2, libgit2)~~
=> New package: uv-0.1.21

srcpkgs/delta/patches/downgrade-git2.patch, srcpkgs/delta/template
=> delta: update to 0.17.0

srcpkgs/sq/template
=> sq: update to 0.48.3.

srcpkgs/dialog/template
=> dialog: update to 1.3.20240307.

srcpkgs/rio/template
=> rio: update to 0.0.36

srcpkgs/ncspot/template
=> ncspot: update to 1.1.0.

srcpkgs/clifm/template
=> clifm: update to 1.17.

srcpkgs/fx/template
=> fx: update to 33.0.0.

srcpkgs/carapace/template
=> carapace: update to 1.0.0.

srcpkgs/units/template
=> units: update to 2.23.

srcpkgs/ruff/template
=> ruff: update to 0.3.3.

srcpkgs/black/template
=> black: update to 24.3.0.

srcpkgs/qsv/template
=> qsv: update to 0.124.1.

common/shlibs, srcpkgs/libnpupnp/template, srcpkgs/libupnpp/template, srcpkgs/mpd/template, srcpkgs/upmpdcli/template
=> upmpdcli: update to 1.8.9

srcpkgs/Waybar/template
=> Waybar: update to 0.10.0

srcpkgs/dua-cli/template
=> dua-cli: update to 2.29.0, adopt

srcpkgs/texlab/template
=> texlab: update to 5.13.1

srcpkgs/rink/template
=> rink: update to 0.7.0

srcpkgs/eqonomize/template
- armv7l
- armv6l-musl
- aarch64-musl
=> eqonomize: update to 1.5.6

srcpkgs/OpenLP/patches/no_pytest_runner.patch, srcpkgs/OpenLP/template, srcpkgs/python3-QtAwesome/template, srcpkgs/python3-pypng/template, srcpkgs/python3-qrcode/files/README.voidlinux, srcpkgs/python3-qrcode/patches/qrcode_assert-has-calls.patch, srcpkgs/python3-qrcode/template
Pretty big set of things needing to be updated so I figured I'd open this one up early to make sure I get everything.
I still need to go through and see what additional dependents these changes might affect.
=> OpenLP: update to 3.1.1.

srcpkgs/discord/template
=> discord: update to 0.0.46

srcpkgs/ruplacer/template
=> ruplacer: update to 0.8.3

srcpkgs/gnome-contacts/template
=> gnome-contacts: update to 45.0

srcpkgs/gtksourceview4/template
https://github.com/void-linux/void-packages/pull/48752#issuecomment-2005911423
- armv7l x
=> gtksourceview4: update to 4.8.4

srcpkgs/moreutils/template
=> moreutils: update to 0.69.

srcpkgs/tmux-xpanes/template
=> tmux-xpanes: update to 4.2.0.

srcpkgs/passt/template
=> passt: update to 2024.03.19.d35bcbe.

srcpkgs/python3-anyio/template, srcpkgs/python3-cachetools/template, srcpkgs/python3-comm/template, srcpkgs/python3-coverage/template, srcpkgs/python3-flaky/template, srcpkgs/python3-json5/template, srcpkgs/python3-referencing/template, srcpkgs/python3-time-machine/template, srcpkgs/python3-urwid_readline/template
=> A few python packages minor updates

common/shlibs, srcpkgs/libdatachannel/template, srcpkgs/obs/template
=> obs: update to 30.1.0.

srcpkgs/ast-grep/template
=> ast-grep: update to 0.19.4.

srcpkgs/gtk4/template
=> gtk4: update to 4.14.1.

srcpkgs/limine/template
=> limine: update to 7.1.0.

srcpkgs/pciutils/template
=> pciutils: update to 3.11.1.

srcpkgs/Solaar/template
=> Solaar: update to 1.1.11.

srcpkgs/libadwaita/template
Depends on: https://github.com/void-linux/void-packages/pull/49369
=> libadwaita: update to 1.5.0.

srcpkgs/snapshot/template
=> snapshot: update to 46.0

srcpkgs/go-md2man/template
=> go-md2man: update to 2.0.4.

srcpkgs/nextcloud-client/template
=> nextcloud-client: update to 3.12.2

srcpkgs/mise/template
=> mise: update to 2024.3.7.

srcpkgs/wofi/template
=> wofi: update to 1.4.1.

srcpkgs/autopep8/template
=> autopep8: update to 2.1.0.

srcpkgs/dk/template
- x86_64-musl
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
=> dk: update to 2.1.

srcpkgs/ttyplot/template
=> ttyplot: update to 1.6.2

srcpkgs/pipectl/template
=> pipectl: update to 0.4.2

srcpkgs/wl-mirror/template
=> wl-mirror: update to 0.16.2

srcpkgs/halloy/INSTALL.msg, srcpkgs/halloy/template
=> halloy: update to 2024.5

srcpkgs/fbpdf/template, srcpkgs/mupdf/template, srcpkgs/sioyek/template, srcpkgs/zathura-pdf-mupdf/template
=> mupdf: update to 1.24.0, revbump dependents

srcpkgs/eza/template
=> eza: update to 0.18.8

srcpkgs/starship/template
=> starship: update to 1.18.0

srcpkgs/sslscan/template
=> sslscan: update to 2.1.3.

srcpkgs/scrcpy/template
=> scrcpy: update to 2.4.

srcpkgs/bfs/template
=> bfs: update to 3.1.3.

srcpkgs/gnome-terminal/template, srcpkgs/vte3/template
=> gnome-terminal: update to 3.52.0

srcpkgs/gnome-chess/template
=> gnome-chess: update to 46.0.

srcpkgs/osv-scanner/template
=> osv-scanner: update to 1.7.1.

srcpkgs/lsd/patches/downgrade-git2.patch, srcpkgs/lsd/template
=> lsd: update to 1.1.0

srcpkgs/platformio/template
=> platformio: update to 6.1.14

srcpkgs/glab/template
=> glab: update to 1.37.0.

srcpkgs/hyprpicker/template
=> hyprpicker: update to 0.2.0

srcpkgs/cherrytree/template
=> cherrytree: update to 1.1.0

srcpkgs/qownnotes/template
=> qownnotes: update to 24.3.5

srcpkgs/gitui/template
=> gitui: update to 0.25.2

srcpkgs/hatch-jupyter-builder/template, srcpkgs/hatchling/template, srcpkgs/jupyterlab/template, srcpkgs/python3-jupyter_client/template, srcpkgs/python3-jupyter_core/template, srcpkgs/python3-jupyter_events/template, srcpkgs/python3-jupyter_ipywidgets/template, srcpkgs/python3-jupyter_nbconvert/template, srcpkgs/python3-jupyter_nbformat/template, srcpkgs/python3-jupyter_notebook/template, srcpkgs/python3-jupyter_server/template, srcpkgs/python3-jupyter_server_terminals/template, srcpkgs/python3-jupyter_widgetsnbextension/template, srcpkgs/python3-jupyterlab_server/patches/openapi-core.patch, srcpkgs/python3-jupyterlab_server/template, srcpkgs/python3-nbclient/template, srcpkgs/python3-notebook_shim/template, srcpkgs/python3-pytest-jupyter/template, srcpkgs/python3-traitlets/template
=> jupyterlab: update to 4.1.5.

srcpkgs/ruff/template
=> ruff: update to 0.3.4.

srcpkgs/protontricks/template
=> protontricks: update to 1.11.1

srcpkgs/toot/template
=> toot: update to 0.42.0.

srcpkgs/octave/template
=> octave: update to 9.1.0.

srcpkgs/easyeffects/template
- I tested the changes in this PR: **daily**
=> easyeffects: update to 7.1.5, adopt

srcpkgs/lazygit/template
=> lazygit: update to 0.41.0

srcpkgs/vips/template
=> vips: update to 8.15.1.

srcpkgs/synapse/template
=> synapse: update to 1.103.0.

srcpkgs/fossil/template
=> fossil: update to 2.23

srcpkgs/wine/template
=> wine: update to 9.5.

srcpkgs/emacs/template
=> emacs: update to 29.3

srcpkgs/perl-Spreadsheet-ParseXLSX/template
- I tested the changes in this PR:**briefly**
- x86_64-musl
- i686
=> perl-Spreadsheet-ParseXLSX: update to 0.35

srcpkgs/font-spleen/template
=> font-spleen: update to 2.1.0.

srcpkgs/fish-shell/template
=> fish-shell: update to 3.7.1

srcpkgs/moar/template
=> moar: update to 1.23.9

srcpkgs/exiftool/template
=> exiftool: update to 12.76

srcpkgs/texlab/template
=> texlab: update to 5.14.0

srcpkgs/gifski/template
=> gifski: update to 1.14.4

srcpkgs/discord/template
=> discord: update to 0.0.47

srcpkgs/inspircd/template
=> inspircd: update to 3.17.0

srcpkgs/anope/template
=> anope: update to 2.0.15

srcpkgs/evince/template
=> evince: update to 46.0.

srcpkgs/gnome-music/template, srcpkgs/python3-gobject/template
=> gnome-music: update to 46.0.

srcpkgs/ironbar/template
=> New-package: ironbar-0.14.1

srcpkgs/spotify/template
- I built this PR locally for my native architecture, (x86-64 glibc)
I sincerely apologize for opening another pull request, I could not figure out how to squash the previous commits.
=> spotify: update to 1.2.31

srcpkgs/zstd/patches/ldflags.patch, srcpkgs/zstd/template
=> zstd: update to 1.5.6.

srcpkgs/rustypaste-cli/template, srcpkgs/rustypaste/template
=> rustypaste: update to 0.15.0, rustypaste-cli: update to 0.9.0

srcpkgs/st/template
=> st: update to 0.9.1.

srcpkgs/incus/template
=> incus-client: fix bash completion filename

srcpkgs/electron24/patches/fix-include.patch, srcpkgs/electron24/patches/libxml2.patch, srcpkgs/electron24/template
=> electron24: s/libgnome-keyring/libsecret/

srcpkgs/qflipper/template
---
Tagging the maintainer, @Vaelatern
=> qflipper: update to 1.3.3.

srcpkgs/nss/template
=> nss: update to 3.99.

srcpkgs/calibre/template
=> calibre: update to 7.7.0.

srcpkgs/pango/template
=> pango: update to 1.52.2

srcpkgs/dasel/template
=> dasel: update to 2.7.0.

srcpkgs/eza/template
=> eza: update to 0.18.9

srcpkgs/amp/template
=> amp: update to 0.7.0

srcpkgs/Tuba/template
=> Tuba: update to 0.7.1.

srcpkgs/pnpm/template
=> pnpm: update to 8.15.5.

srcpkgs/android-studio/template
=> android-studio: update to 2023.2.1.24.

srcpkgs/git-cliff/template
=> git-cliff: update to 2.2.0

srcpkgs/fend/template
=> fend: update to 1.4.6

srcpkgs/kak-lsp/template
=> kak-lsp: update to 16.0.0.

srcpkgs/gopls/template
=> gopls: update to 0.15.2.

srcpkgs/lf/template
=> lf: update to r32.

srcpkgs/clifm/template
=> clifm: update to 1.18.

srcpkgs/ntfy/template
=> ntfy: update to 2.10.0.

srcpkgs/vaultwarden-web/template
=> vaultwarden-web: update to 2024.3.0.

srcpkgs/syft/template
=> syft: update to 1.1.0, adopt

srcpkgs/gnutls/template
=> gnutls: update to 3.8.4

common/shlibs, srcpkgs/gvfs/template, srcpkgs/libgdata/template, srcpkgs/msgraph-devel, srcpkgs/msgraph/template, srcpkgs/uhttpmock/template
---
I tested that gvfs works properly. However, I don't use OneDrive, so I can't verify that part works correctly.
=> gvfs: update to 1.54.0, recursive cleanup

srcpkgs/mercurial/files/tests_blacklist, srcpkgs/mercurial/template
- I tested the changes in this PR: **briefly** (Workflow)
- x86_64-musl
- i686
All builds have been run with `-Q` for testing.
=> mercurial: update to 6.7.2.

srcpkgs/containerd/template
=> containerd: update to 1.7.14.

srcpkgs/intellij-idea-community-edition/template
=> intellij-idea-community-edition: update to 2023.3.6.

srcpkgs/hyperrogue/template
=> hyperrogue: update to 13.0d

srcpkgs/chess-tui/template
=> chess-tui: update to 1.2.1.

srcpkgs/mise/template
=> mise: update to 2024.4.0.

srcpkgs/sheldon/template
=> sheldon: add libgit2 dependency

srcpkgs/cargo-modules/template
=> cargo-modules: update to 0.15.1.

srcpkgs/gitui/template
=> gitui: depend on system libgit2

srcpkgs/vale/template
=> vale: update to 3.3.1.

srcpkgs/ast-grep/template
=> ast-grep: update to 0.20.2.

srcpkgs/forkstat/template
=> forkstat: update to 0.03.02

srcpkgs/liblc3/template
=> liblc3: update to 1.1.0

srcpkgs/taplo/template, srcpkgs/taplo/update
=> taplo: update to 0.9.1

srcpkgs/texlab/template
=> texlab: update to 5.14.1

srcpkgs/starship/template
=> starship: update to 1.18.2

srcpkgs/upx/template
=> upx: update to 4.2.3

srcpkgs/gradle/template
=> gradle: update to 8.7.

srcpkgs/hugo/template
=> hugo: update to 0.124.1

srcpkgs/fava/template
=> fava: update to 1.27.3.

srcpkgs/python3-utils/template
=> python3-utils: update to 3.8.2.

srcpkgs/python3-pytest-mock/template, srcpkgs/python3-time-machine/template, srcpkgs/tox/template
=> tox: update to 4.14.2.

srcpkgs/github-cli/template
=> github-cli: update to 2.47.0

srcpkgs/fx/template
=> fx: update to 34.0.0.

srcpkgs/dust/template
=> dust: update to 1.0.0.

srcpkgs/pueue/template
=> pueue: update to 3.4.0

srcpkgs/prs/template
=> prs: update to 0.5.1.

srcpkgs/nextcloud-client/template
=> nextcloud-client: update to 3.12.3

srcpkgs/intellij-idea-community-edition/template
=> intellij-idea-community-edition: update to 2024.1.

srcpkgs/python3-pycountry/template
=> python3-pycountry: update to 23.12.11.

srcpkgs/difftastic/template
=> difftastic: update to 0.57.0.

srcpkgs/ruff/template
=> ruff: update to 0.3.5.

srcpkgs/glycin-loaders/template, srcpkgs/loupe/template
- I tested the changes in this PR: **YES**<
- armv7l x
=> loupe: update 46.1

srcpkgs/slack-desktop/template
=> slack-desktop: update to 4.37.94

srcpkgs/vscode/template
=> vscode: update to 1.88.0

srcpkgs/q/template
=> New package: q-0.19.2

srcpkgs/cargo-watch/template
=> New package: cargo-watch-8.5.2

srcpkgs/wine/template
=> wine: update to 9.6

common/shlibs, srcpkgs/catgirl/template, srcpkgs/libtls/template, srcpkgs/litterbox/template, srcpkgs/openntpd/template, srcpkgs/pounce/template, srcpkgs/sacc/template
=> libtls: update to 3.9.1.

srcpkgs/gnutls/template
=> gnutls: update to 3.8.5

srcpkgs/comrak/template
=> comrak: update to 0.22.0

srcpkgs/nushell/template
=> nushell: update to 0.92.1

srcpkgs/borgmatic/template
=> borgmatic: update to 1.8.9.

srcpkgs/spotify-player/template
=> spotify-player: update to 0.17.2

srcpkgs/i3status-rust/template
=> i3status-rust: update to 0.33.0.

srcpkgs/testdisk/template
Tested by restoring deleted files on ext4 partition
- x86_64-musl
=> testdisk: update to 7.2.

srcpkgs/synapse/patches/setuptools_rust_upperbound.patch, srcpkgs/synapse/template
=> synapse: update to 1.104.0.

srcpkgs/halloy/template
=> halloy: update to 2024.6

srcpkgs/bluetuith/template
=> bluetuith: update to 0.2.2.

srcpkgs/git-absorb/template
=> git-absorb: update to 0.6.13.

srcpkgs/OpenRCT2/template
=> OpenRCT2: update to 0.4.10.

srcpkgs/discord/template
=> discord: update to 0.0.48

srcpkgs/sqlite/template
=> sqlite: update to 3.45.2.

srcpkgs/discord/template
=> discord: update to 0.0.49

srcpkgs/dk/template
- x86_64-musl
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
=> dk: update to 2.2.

srcpkgs/lms/template
=> lms: update to 3.51.1

common/shlibs, srcpkgs/lms/template, srcpkgs/wt/template
=> wt: update to 4.10.4

srcpkgs/glab/template
=> glab: update to 1.38.0.

srcpkgs/glances/template
=> glances: update to 3.4.0.5.

srcpkgs/ast-grep/template
=> ast-grep: update to 0.20.4.

srcpkgs/unflac/template
=> unflac: update to 1.3.

srcpkgs/gallery-dl/template
=> gallery-dl: update to 1.26.9.

srcpkgs/newsraft/template
Also update project location.
Cc: @BryceVandegrift
=> newsraft: update to 0.24

srcpkgs/cloudflared/template
- I built this PR locally for my native architecture: aarch64-libc
=> cloudflared: update to version 2024.3.0

srcpkgs/perl-Clipboard/template
=> perl-Clipboard: update to 0.29.

srcpkgs/igraph/template
=> igraph: update to 0.10.11.

srcpkgs/giac/template
=> giac: update to 1.9.0.97.

srcpkgs/vaultwarden-web/template
=> vaultwarden-web: update to 2024.3.1.

srcpkgs/wslu/template
=> wslu: update to 4.1.3

srcpkgs/citations/template
=> citations: update to 0.6.4

srcpkgs/blueprint-compiler/template
=> blueprint-compiler: update to 0.12.0

srcpkgs/power-profiles-daemon/template
=> power-profiles-daemon: update to 0.21.

srcpkgs/terraform-ls/template
=> terraform-ls: update to 0.33.0.

srcpkgs/golangci-lint/template
=> golangci-lint: update to 1.57.2

srcpkgs/freeorion/patches/musl.patch, srcpkgs/freeorion/template
=> freeorion: update to 0.5.

srcpkgs/gitea/template
=> gitea: update to 1.21.10

srcpkgs/icewm/template
- I built this PR locally for these architectures (if supported. mark crossbuilds):  
- armv7l
=> icewm: update to 3.4.7.

srcpkgs/instaloader/template
=> instaloader: update to 4.11.

srcpkgs/yggdrasil/template
=> yggdrasil: update to 0.5.5.

srcpkgs/eza/template
=> eza: update to 0.18.10

srcpkgs/loupe/template
=> loupe: update to 46.2

srcpkgs/snapshot/template
=> snapshot: update to 46.2

srcpkgs/yt-dlp/template
=> yt-dlp: update to 2024.04.09.

srcpkgs/powerstat/template
=> powerstat: update to 0.04.03.

srcpkgs/python3-path/template
=> python3-path: update to 16.13.0.

srcpkgs/vale/template
=> vale: update to 3.4.1.

srcpkgs/python3-zipp/template
=> python3-zipp: update to 3.18.1.

srcpkgs/riff/template
=> riff: update to 3.1.0.

srcpkgs/rofi-calc/template
=> rofi-calc: update to 2.2.1

common/shlibs, srcpkgs/libpdal/template, srcpkgs/qgis/template
=> qgis: update to 3.36.1; libpdal: update to 2.7.1

srcpkgs/gnome-maps/template, srcpkgs/libshumate/template
=> gnome-maps: update to 46.0.

srcpkgs/gnome-calculator/template
=> gnome-calculator: update to 46.0.

srcpkgs/xh/template
=> xh: update to 0.22.0

srcpkgs/gitoxide/template
=> gitoxide: update to 0.35.0

srcpkgs/atuin/template
=> atuin: update to 18.2.0

srcpkgs/vhs/template
=> vhs: update to 0.7.2

srcpkgs/pantalaimon/template
Really only tested the manpage changes, not pantalaimon itself
=> pantalaimon: add man pages.

srcpkgs/memray/template, srcpkgs/python3-textual/template
=> memray: update to 1.12.0.

srcpkgs/syft/template
=> syft: update to 1.2.0

srcpkgs/fastmod/template
=> fastmod: update to 0.4.4

srcpkgs/upower/template
=> upower: update to 1.90.4

srcpkgs/wstunnel/template
=> wstunnel: update to 9.2.5

srcpkgs/black/template
=> black: update to 24.4.0.

srcpkgs/neomutt/template
=> neomutt: update to 20240329.

srcpkgs/gtk4/template
=> gtk4: update to 4.14.2.

srcpkgs/vala/template, srcpkgs/valadoc/template
Closes: https://github.com/void-linux/void-packages/issues/49831
=> vala: update to 0.56.16.

common/shlibs, srcpkgs/libgnome-games-support2-devel, srcpkgs/libgnome-games-support2/template, srcpkgs/swell-foop/template
=> swell-foop: update to 46.0

srcpkgs/slack-desktop/template
=> slack-desktop: update to 4.367.101

srcpkgs/discord/template
- I built this PR locally for my native architecture,**x86_64**
=> discord: update to 0.0.50

srcpkgs/rust-analyzer/template
=> rust-analyzer: update to 2024.04.15.

srcpkgs/ast-grep/template
=> ast-grep: update to 0.20.5.

srcpkgs/grype/template
=> grype: update to 0.76.0

srcpkgs/oil/template
=> oil: update to 0.21.0

srcpkgs/i2pd/template
=> i2pd: update to 2.51.0.

srcpkgs/d2/template
=> d2: update to 0.6.4.

common/shlibs, srcpkgs/filezilla/template, srcpkgs/libfilezilla/template
=> libfilezilla: update to 0.47.0; filezilla: update to 3.67.0

srcpkgs/gnome-power-manager/template
=> gnome-power-manager: update to 43.0.

srcpkgs/gnome-sudoku/template
=> gnome-sudoku: update to 46.0.

srcpkgs/gitui/template
=> gitui: update to 0.26.1

srcpkgs/synapse/template
=> synapse: update to 1.105.0.

srcpkgs/telegram-desktop/template
=> telegram-desktop: update to 4.16.6.

common/shlibs, srcpkgs/Endeavour/template, srcpkgs/bijiben/template, srcpkgs/evolution-data-server/patches/d845d321532ea80a8e204c0d97dd06771c9d4646.patch, srcpkgs/evolution-data-server/template, srcpkgs/evolution-ews/template, srcpkgs/evolution/patches/a7fe0ab7cdf74ac73e4e3448e4fb29d4e7731f74.patch, srcpkgs/evolution/patches/e290cf27cd8a903acdf9c6ed7b746903bbda9e6d.patch, srcpkgs/evolution/template, srcpkgs/gnome-calendar/template, srcpkgs/gnome-panel/template, srcpkgs/gnome-shell/template, srcpkgs/io.elementary.calendar/template, srcpkgs/planify/template
=> evolution: update to 3.52.0.

srcpkgs/gnome-contacts/template
=> gnome-contacts: update to 46.0.

srcpkgs/gnome-disk-utility/template
=> gnome-disk-utility: update to 46.0.

srcpkgs/mutt/template
=> mutt: update to 2.12.13

srcpkgs/sushi/template
- I built this PR locally for my native architecture. (x86_64-glibc)
=> sushi: update to 46.0.

srcpkgs/nautilus/template
=> nautilus: update to 46.0.

srcpkgs/borgmatic/template
=> borgmatic: update to 1.8.10.

srcpkgs/trurl/template
=> trurl: update to 0.12.

srcpkgs/grype/template
=> grype: update to 0.77.0

srcpkgs/qtractor/template
=> qtractor: update to 0.9.90

srcpkgs/gitea/template
=> gitea: update to 1.21.11

srcpkgs/eog/template
=> eog: update to 45.3

srcpkgs/baobab/template
=> baobab: update to 46.0

srcpkgs/gtksourceview5/template
=> gtksourceview5: update to 5.12.0

srcpkgs/gnome-weather/template
=> gnome-weather: update to 46.0.

srcpkgs/gnote/template
=> gnote: update to 46.0

srcpkgs/libgnome-games-support2/update
=> libgnome-games-support2: fix update-check

srcpkgs/ghex/template
=> ghex: update to 46.0

common/shlibs, srcpkgs/gnome-flashback/patches/fix-non-systemd.patch, srcpkgs/gnome-flashback/template, srcpkgs/gnome-panel/template, srcpkgs/metacity/template
=> gnome-flashback: update to 3.52.1.

srcpkgs/gnome-nibbles/template
=> gnome-nibbles: update to 4.0.4

srcpkgs/gnome-mahjongg/template
=> gnome-mahjongg: update to 3.40.1

srcpkgs/lightsoff/template
=> lightsoff: update to 46.0

srcpkgs/orca/template
=> orca: update to 46.0.

srcpkgs/iio-sensor-proxy/patches/fr_FR_locale-test.patch, srcpkgs/iio-sensor-proxy/template
=> iio-sensor-proxy: update to 3.5.

srcpkgs/gst-libav/template, srcpkgs/gst-plugins-bad1/template, srcpkgs/gst-plugins-base1/template, srcpkgs/gst-plugins-good1/template, srcpkgs/gst-plugins-ugly1/template, srcpkgs/gst-rtsp-server/template, srcpkgs/gst1-editing-services/template, srcpkgs/gst1-python3/template, srcpkgs/gstreamer-vaapi/template, srcpkgs/gstreamer1/template
=> Gstreamer: update to 1.24.2

common/shlibs, srcpkgs/grilo-plugins/template, srcpkgs/libdmapsharing/template, srcpkgs/libdmapsharing/update, srcpkgs/rhythmbox/template
=> libdmapsharing

srcpkgs/simple-scan/template
=> simple-scan: update to 46.0

srcpkgs/wine/template
@Hoshpak @iFoundSilentHouse  Opening this but maybe we should wait first for #49943 to be merged first!
=> wine: update to 9.7

srcpkgs/mpvpaper/template
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- i686
- x86_64-musl
=> mpvpaper: update to 1.5.

srcpkgs/primecount/template, srcpkgs/primesieve/template
=> primecount: update to 7.13,  primesieve: update to 12.3. 

srcpkgs/python3-pywlroots-0.16/template, srcpkgs/python3-qtile-extras/template, srcpkgs/qtile/template
- I tested the changes in this PR: **YES** (have not tested qtile-wayland or python3-qtile-extras)
=> qtile: update to 0.25.0, python3-pywlroots-0.16: update to 0.16.7, python3-qtile-extras: update to 0.25.0

srcpkgs/liblc3/template
=> liblc3: update to 1.1.1

srcpkgs/wezterm/template
@jbenden 
added missing nautilus extension.
=> wezterm: add nautilus extension

srcpkgs/zoom/template
=> zoom: update to 6.0.2.4680

common/shlibs, srcpkgs/libcamera-devel, srcpkgs/libcamera/template, srcpkgs/pipewire/template
---
I decided to split off the redesign of the subpackages into its own RFC so as not to hold up this update any more.
=> New package: libcamera-0.2, pipewire: update to 1.0.5

common/shlibs, srcpkgs/Waybar/patches/wireplumber-0.5.patch, srcpkgs/Waybar/template, srcpkgs/wireplumber/INSTALL.msg, srcpkgs/wireplumber/patches/test.patch, srcpkgs/wireplumber/template
=> wireplumber: update to 0.5.2; revbump Waybar

srcpkgs/watchexec/template
=> watchexec: update to 2.0.0

srcpkgs/texlab/template
=> texlab: update to 5.15.0

srcpkgs/wstunnel/template
=> wstunnel: update to 9.3.0

srcpkgs/kak-lsp/template
- I tested the changes in this PR: briefly (running it for 24 hrs against kakoune master branch)
=> kak-lsp: update to 17.0.1

srcpkgs/yq-go/template
=> yq-go: update to 4.43.1.

srcpkgs/hg-evolve/template
=> hg-evolve: update to 11.1.3.

srcpkgs/carapace/template
=> carapace: update to 1.0.1.

srcpkgs/ruff/template
=> ruff: update to 0.4.1.

srcpkgs/python3-dnsrecon/patches/requirements.txt.diff, srcpkgs/python3-dnsrecon/template
=> python3-dnsrecon: update to 1.2.0.

srcpkgs/cargo-modules/template
=> cargo-modules: update to 0.15.5.

srcpkgs/qt5-webengine/patches/qt5-webengine-chromium-python3.patch, srcpkgs/qt5-webengine/patches/qt5-webengine-python3.patch, srcpkgs/qt5-webengine/template
=> qt5-webengine: build with python3.11

srcpkgs/discord/template
- I built this PR locally for my native architecture, **x86-64**
=> discord: update to 0.0.51

srcpkgs/pnpm/template
=> pnpm: update to 9.0.5.

srcpkgs/gdu/template
=> gdu: update to 5.28.0.

srcpkgs/docker-buildx/template
=> docker-buildx: update to 0.14.0.

srcpkgs/greetd/files/greetd.pam, srcpkgs/greetd/template
=> greetd: update to 0.10.0

srcpkgs/wlgreet/template
=> New package: wlgreet-0.5.0

srcpkgs/qownnotes/template
=> qownnotes: update to 24.4.2

common/shlibs, srcpkgs/libopenshot-audio/template, srcpkgs/libopenshot/patches/musl.patch, srcpkgs/libopenshot/template
No idea how to test, openshot can start
#49973 
=> Libopenshot

srcpkgs/dinit/template
- I tested the changes in this PR: yes, I tested user services with dinit+turnstile
=> dinit: update to 0.18.0

srcpkgs/PrismLauncher/template
=> PrismLauncher: update to 8.3.

srcpkgs/io.elementary.files/template
=> io.elementary.files: update to 6.5.3.

srcpkgs/google-earth-pro/template
=> google-earth-pro: update to 7.3.6.9796.

srcpkgs/python3-peewee/template
=> python3-peewee: update to 3.17.3.

srcpkgs/osv-scanner/template
=> osv-scanner: update to 1.7.2.

srcpkgs/glab/template
=> glab: update to 1.40.0.

srcpkgs/fuzzel/template
=> fuzzel: update to 1.10.2

srcpkgs/weston/template
=> weston: update to 13.0.1.

srcpkgs/synapse/template
=> synapse: update to 1.105.1.

srcpkgs/hcloud/template
=> hcloud: update to 1.43.1.

srcpkgs/cpuid/template
=> cpuid: update to 20240409.

srcpkgs/pgweb/template
=> pgweb: update to 0.15.0.

srcpkgs/eza/template
=> eza: update to 0.18.13

srcpkgs/lua-language-server/template
=> lua-language-server: update to 3.8.3.

srcpkgs/lutris/template
**YES**
- I built this PR locally for my native architecture, (x86_64-glib)
=> lutris: update to 0.5.17

srcpkgs/podman-compose/template
=> podman-compose: update to 1.1.0.

srcpkgs/n/template
=> n: update to 9.2.3

srcpkgs/neomutt/template
=> neomutt: update to 20240416.

srcpkgs/conduit/template
=> conduit: update to 0.7.0.

srcpkgs/linux-firmware/template
=> linux-firmware: update to 20240410.

srcpkgs/swayimg/template
- I built this PR locally for my native architecture: x86-64_libc
- armv7l (crossbuilds)
=> swayimg: update to 2.2

srcpkgs/nextcloud-client/template
=> nextcloud-client: update to 3.12.4

srcpkgs/nvidia/template
Please help me test in other configurations!
=> nvidia: update to 550.76.

srcpkgs/grype/template, srcpkgs/syft/template
=> Anchore tools update

srcpkgs/git-extras/template
=> git-extras: update to 7.2.0.

srcpkgs/ruff/template
=> ruff: update to 0.4.2.

srcpkgs/oxipng/template
=> oxipng: update to 9.1.1.

srcpkgs/root/template
=> root: update to 6.30.06

srcpkgs/cozy/template
=> cozy: update to 1.3.0
