- srcpkgs/broot/template
> broot: update to 1.37.0

- srcpkgs/watchexec/template
> watchexec: update to 2.1.0

- srcpkgs/comrak/template
> comrak: update to 0.23.0

- srcpkgs/black/template
> black: update to 24.4.2.

- srcpkgs/ast-grep/template
> ast-grep: update to 0.21.1.

- srcpkgs/discord/template
- I built this PR locally for my native architecture, **x86-64-glibc**
> discord: update to 0.0.52

- srcpkgs/vivaldi/template
> vivaldi: update to 6.7.3329.21

- srcpkgs/gcovr/template
- srcpkgs/python3-colorlog/template
> Gcovr 6.8.2

- srcpkgs/github-cli/template
> github-cli: update to 2.49.0

- srcpkgs/rink/template
> rink: update to 0.8.0

- srcpkgs/gum/template
> gum: update to 0.14.0

- srcpkgs/clojure/template
> clojure: update to 1.11.3.1456.

- srcpkgs/google-chrome/template
> google-chrome: update to 124.0.6367.118.

- srcpkgs/schismtracker/template
> schismtracker: update to 20240426

- srcpkgs/musikcube/patches/musl.patch
- srcpkgs/musikcube/template
> musikcube: update to 3.0.2.

- srcpkgs/praat/template
> praat: update to 6.4.11

- srcpkgs/mate-desktop/template
> mate-desktop: update to 1.28.2.

- srcpkgs/calibre/template
> calibre: update to 7.9.0.

- srcpkgs/git/template
> git: update to 2.45.0.

- srcpkgs/texlab/template
> texlab: update to 5.16.0

- srcpkgs/eza/template
> eza: update to 0.18.14

- srcpkgs/furnace/template
> furnace: update to 0.6.3

- srcpkgs/platformio/template
> platformio: update to 6.1.15

- srcpkgs/borgmatic/template
> borgmatic: update to 1.8.11.

- srcpkgs/android-studio/template
> android-studio: update to 2023.3.1.18.

- srcpkgs/intellij-idea-community-edition/template
> intellij-idea-community-edition: update to 2024.1.1.

- srcpkgs/rofimoji/template
> rofimoji: update to 6.3.0

- srcpkgs/azote/template
> azote: update to 1.12.7

- srcpkgs/clipman/template
> clipman: update to 1.6.4

- srcpkgs/wayclip/template
> wayclip: update to 0.4.2

- srcpkgs/grype/template
> grype: update to 0.77.2

- srcpkgs/watchexec/template
> watchexec: update to 2.1.1

- srcpkgs/MoarVM/template
- srcpkgs/nqp/template
- srcpkgs/rakudo/template
> rakudo: update to 2024.04.

- srcpkgs/mate-panel/template
jobs should pass after merging https://github.com/void-linux/void-packages/pull/50148
> mate-panel: update to 1.28.1.

- srcpkgs/vscode/patches/fix_dir.patch
- srcpkgs/vscode/template
> vscode: update to 1.89.0

- srcpkgs/hydrus/template
> hydrus: update to 566, adopt.

- srcpkgs/fend/template
> fend: update to 1.4.7

- srcpkgs/rio/patches/drop-rust-version-patch.patch
- srcpkgs/rio/template
> rio: update to 0.0.37

- srcpkgs/codeberg-cli/template
> codeberg-cli: update to 0.4.0

- srcpkgs/wbg/patches/musl-mfd-noexec-seal.patch
- srcpkgs/wbg/template
> wbg: update to 1.2.0

- srcpkgs/lychee/template
> lychee: update to 0.15.1.

- srcpkgs/python3-virtualenv/template
> python3-virtualenv: update to 20.26.1.

- srcpkgs/fnott/template
> fnott: update to 1.6.0

- srcpkgs/wine/patches/musl-ntdll.patch
- srcpkgs/wine/template
> wine: update to 9.8

- srcpkgs/zfs/template
> zfs: update to 2.2.4.

- srcpkgs/fd/patches/drop-rust-version-patch.patch
- srcpkgs/fd/template
> fd: update to 10.0.0

- srcpkgs/broot/template
> broot: update to 1.38.0

- srcpkgs/halloy/template
> halloy: update to 2024.7

- srcpkgs/fend/template
> fend: update to 1.4.8

- srcpkgs/schismtracker/template
> schismtracker: update to 20240503

- srcpkgs/discord/template
> discord: update to 0.0.53

- srcpkgs/mame/template
> mame: update to 0265.

- srcpkgs/ruff/template
> ruff: update to 0.4.3.

- srcpkgs/Solaar/template
> Solaar: update to 1.1.12.

- srcpkgs/nghttp2/template
> nghttp2: update to 1.61.0.

- srcpkgs/blueman/template
> blueman: update to 2.4.1

- srcpkgs/vivaldi/template
> vivaldi: update to 6.7.3329.24

- srcpkgs/zet/patches/fix-rust178.patch
- srcpkgs/zet/template
> zet: fix for rust-178

- srcpkgs/mate-themes/template
> mate-themes: update to 3.22.26.

- srcpkgs/docker-compose/template
> docker-compose: update to 2.27.0

- srcpkgs/ecm/update
> ecm: fix update-check

- srcpkgs/github-cli/template
> github-cli: update to 2.49.1

- srcpkgs/fd/template
> fd: update to 10.1.0

- srcpkgs/rizin/template
> rizin: update to 0.7.3

- srcpkgs/vivaldi/template
> vivaldi: update to 6.7.3329.26

- srcpkgs/gnucash/template
> gnucash: update to 5.6

- srcpkgs/ibus-array/template
> ibus-array: update to 0.2.3.

- srcpkgs/labwc/template
> labwc: update to 0.7.2

- srcpkgs/mesa/template
> mesa: update to version 24.0.7.

- srcpkgs/grub/patches/devicetree-loading.patch
- srcpkgs/grub/template
useful for #49615 but generally applicable for arm uefi devices
> grub: support loading devicetrees

- srcpkgs/cronie/template
> cronie: update to 1.7.2.

- srcpkgs/clojure/template
> clojure: update to 1.11.3.1463.

- srcpkgs/discord/template
> discord: update to 0.0.54

- srcpkgs/pipe-viewer/template
> pipe-viewer: update to 0.5.1.

- srcpkgs/onefetch/template
> onefetch: update to 2.21.0

- srcpkgs/grype/template
- srcpkgs/syft/template
> Update anchore tools

- srcpkgs/swaykbdd/template
> swaykbdd: update to 1.4.

- srcpkgs/upx/template
> upx: update to 4.2.4

- srcpkgs/Waybar/template
> Waybar: update to 0.10.3

- srcpkgs/mimalloc/template
- srcpkgs/mold/patches/fix-arm-yield.patch
- srcpkgs/mold/template
> Mimalloc & Mold

- srcpkgs/neomutt/template
> neomutt: update to 20240425.

- srcpkgs/hyperrogue/template
> hyperrogue: update to 13.0i

- srcpkgs/git-cliff/template
> git-cliff: update to 2.2.2

- srcpkgs/rofimoji/template
> rofimoji: update to 6.3.1

- srcpkgs/github-cli/template
> github-cli: update to 2.49.2

- srcpkgs/sigi/template
> sigi: update to 3.6.4

- srcpkgs/sublime-merge/template
> sublime-merge: update to 2096.

- srcpkgs/uriparser/template
> uriparser: update to 0.9.8.

- srcpkgs/rssguard/template
> rssguard: update to 4.7.0.

- srcpkgs/CopyQ/template
> CopyQ: update to 8.0.0.

- srcpkgs/vaultwarden/template
> vaultwarden: update to 1.30.5.

- srcpkgs/s/template
> s: update to 0.7.0.

- srcpkgs/i3status-rust/template
I made this PR to include the sample configuration in the package. I've also updated the package while I was at it.
> i3status-rust: update to 0.33.1.

- srcpkgs/python3-nose2/template
> python3-nose2: add changelog

- srcpkgs/bfs/template
> bfs: update to 3.2.

- srcpkgs/vale/template
> vale: update to 3.4.2.

- srcpkgs/srain/template
> srain: update to 1.7.0.

- srcpkgs/pnpm/template
> pnpm: update to 9.1.1.

- srcpkgs/yq-go/template
cc @steinex 
Updated description taken from repository description at https://github.com/mikefarah/yq.
> yq-go: update to 4.44.1.

- srcpkgs/mako/template
> mako: update to 1.9.0.

- srcpkgs/pre-commit/template
> pre-commit: update to 3.7.1.

- srcpkgs/perl-File-MimeInfo/template
> perl-File-MimeInfo: update to 0.35.

- srcpkgs/ruff/template
> ruff: update to 0.4.4.

- srcpkgs/calibre/template
> calibre: update to 7.10.0.

- srcpkgs/python3-regex/template
> python3-regex: update to 2024.5.10.

- srcpkgs/osinfo-db/template
> osinfo-db: update to 20240510.

- srcpkgs/xev/template
> xev: update to 1.2.6.

- srcpkgs/python3-immutabledict/template
- srcpkgs/python3-netaddr/template
- srcpkgs/python3-phonenumbers/template
- srcpkgs/synapse/template
- **python3-immutabledict: update to 4.2.0.**
- **python3-phonenumbers: update to 8.13.35.**
- **python3-netaddr: update to 1.2.1.**
- **synapse: update to 1.106.0.**
> synapse: update to 1.107.0.

- srcpkgs/nghttp2/template
> nghttp2: update to 1.62.0.

- srcpkgs/python3-nose2/template
> python3-nose2: update to 0.14.2

- srcpkgs/homebank/template
> homebank: update to 5.8.

- srcpkgs/qtforkawesome/template
- srcpkgs/qtutilities/template
- srcpkgs/syncthingtray/template
- srcpkgs/tageditor/template
> martchusware qt6

- srcpkgs/font-iosevka/template
- I built this PR locally for my native architecture, (x86_64-gblic)
> font-iosevka: update to 30.0.1.

- srcpkgs/gtk4/template
> gtk4: update to 4.14.4

- srcpkgs/lego/template
> lego: update to 4.15.0.

- common/shlibs
- srcpkgs/libqalculate/template
- srcpkgs/plasma-workspace/template
- srcpkgs/qalculate-gtk/template
- srcpkgs/qalculate-qt/template
> qalculate: update to 5.1

- srcpkgs/eza/template
> eza: update to 0.18.16

- srcpkgs/unrar/template
> unrar: update to 7.0.9.

- srcpkgs/trurl/template
> trurl: update to 0.13.

- srcpkgs/anydesk/template
> anydesk: update to 6.3.2.

- srcpkgs/eww/template
> New package: eww-0.6.0

- srcpkgs/corectrl/template
> corectrl: update to 1.3.1

- srcpkgs/SoapyRTLSDR/template
> SoapyRTLSDR: update to 0.3.3.

- srcpkgs/gns3-gui/template
- srcpkgs/gns3-server/template
> GNS3 2.2.47

- srcpkgs/nicotine+/template
> nicotine+: update to 3.3.4

- srcpkgs/butt/patches/0001-limits.h-patch.patch
- srcpkgs/butt/template
- I built this PR locally for my native architecture, X86_64
- armv7l
> butt: update to 1.41.1.

- srcpkgs/mdBook/template
> mdBook: update to 0.4.40

- srcpkgs/starship/template
> starship: update to 1.19.0

- srcpkgs/ast-grep/template
> ast-grep: update to 0.22.3.

- srcpkgs/catgirl/template
> catgirl: update to 2.2a

- srcpkgs/xonsh/template
- armv7l
- armv6l-musl
- aarch64-musl
> xonsh: update to 0.16.0

- srcpkgs/rawtherapee/template
> rawtherapee: enable sse2 and LTO

- srcpkgs/jsonnet-language-server/template
> jsonnet-language-server: update to 0.13.1

- srcpkgs/nextcloud-client/template
> nextcloud-client: update to 3.13.0

- srcpkgs/golangci-lint/template
It is my second commit for golangci-lint package. I have > 10 years experience in Go language and use Void GNU/Linux > 3 years. I offer myself as a package maintainer for golangci-lint. I added my email to this commit. Say if it is inappropriate for any reason and I'll repush commit with email for orphaned packages.
> golangci-lint: update to 1.58.2

- srcpkgs/i2pd/template
> i2pd: update to 2.52.0, adopt

- srcpkgs/kopia/template
> kopia: update to 0.17.0.

- srcpkgs/cava/template
> cava: update to 0.10.2.

- srcpkgs/python3-regex/template
> python3-regex: update to 2024.5.15.

- srcpkgs/zoom/template
> zoom: update to 6.0.10.5325

- srcpkgs/vaultwarden-web/template
> vaultwarden-web: update to 2024.5.0.

- srcpkgs/dropbox/template
> dropbox: update to 2024.04.17.

- srcpkgs/comrak/template
> comrak: update to 0.24.1

- srcpkgs/just/template
> just: update to 1.26.0

- common/build-style/go.sh
- srcpkgs/docker-cli/template
This change also modifies the `go` build-style.
> Docker cli update

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 7.10.0

- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.9.1.

- srcpkgs/lswt/template
> lswt: update to 2.0.0.

- srcpkgs/gitoxide/template
> gitoxide: update to 0.36.0

- srcpkgs/wstunnel/template
> wstunnel: update to 9.5.2

- srcpkgs/arti/patches/fix-32bit-tests.patch
- srcpkgs/arti/template
> arti: update to 1.2.3.

- srcpkgs/chroma/template
> chroma: update to 2.14.0.

- srcpkgs/libblockdev/template
> libblockdev: update to 3.1.1.

- srcpkgs/nghttp2/template
> nghttp2: update to 1.62.1.

- srcpkgs/libcap/template
> libcap: update to 2.70.

- srcpkgs/fribidi/template
> fribidi: update to 1.0.14.

- srcpkgs/rio/template
> rio: update to 0.0.39

- srcpkgs/crun/template
> crun: update to 1.15.

- srcpkgs/gparted/template
> gparted: update to 1.6.0.

- srcpkgs/mednafen/template
- aarch64
- armv7l
- x86_64-musl
> mednafen: update to 1.32.1.

- srcpkgs/mednaffe/template
- aarch64
- armv7l
- x86_64-musl
> mednaffe: update to 0.9.3.

- srcpkgs/websocat/template
> websocat: update to 1.13.0

- srcpkgs/pipewire/template
- srcpkgs/pipewire/update
> pipewire: update to 1.0.6

- srcpkgs/strace/template
> strace: update to 6.9.

- srcpkgs/Solaar/template
> Solaar: update to 1.1.13.

- srcpkgs/osv-scanner/template
> osv-scanner: update to 1.7.3.

- srcpkgs/mpvpaper/template
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- i686
- x86_64-musl
> mpvpaper: update to 1.6.

- srcpkgs/SweetHome3D/template
> SweetHome3D: update to 7.3.

- srcpkgs/schismtracker/template
> schismtracker: update to 20240515

- srcpkgs/qpwgraph/template
This changes are to update version of qpwgraph
**Testing the changes**
-  I tested the changes in this PR: YES
**Local build testing**
-  I built this PR locally for my laptop (Lenovo IdeaPad 5 14ARE05)
-  x86_64-glibc
> qpwgraph: update to 0.7.2

- srcpkgs/openttd/template
> openttd: update to 14.1.

- srcpkgs/pandoc/patches/fix-musl-build.patch
- srcpkgs/pandoc/template
I suggest build with #49526 to experiment; the first build will take the same time but subsequent builds will be much faster.
> pandoc: update to 3.1.11.1.

- srcpkgs/discord-ptb/template
> discord-ptb: update to 0.0.85.

- srcpkgs/riff/template
> riff: update to 3.2.0.

- srcpkgs/ircdog/template
> ircdog: update to 0.5.3.

- srcpkgs/ruff/template
> ruff: update to 0.4.5.

- srcpkgs/rustup/template
> rustup: update to 1.27.1

- srcpkgs/cargo-auditable-bootstrap/template
- srcpkgs/cargo-auditable/template
> cargo-auditable: update to 0.6.4

- srcpkgs/rust-audit-info/template
> rust-audit-info: update to 0.5.4

- srcpkgs/OpenRCT2/template
> OpenRCT2: update to 0.4.11.

- srcpkgs/osinfo-db/template
> osinfo-db: update to 20240523.

- srcpkgs/calibre/template
> calibre: update to 7.11.0.

- srcpkgs/schismtracker/template
> schismtracker: update to 20240523

- srcpkgs/lynis/template
> lynis: update to 3.1.1.

- srcpkgs/yambar/template
> yambar: update to 1.11.0

- srcpkgs/babashka/template
- srcpkgs/mandrel/template
> mandrel: update to 23.1.3.1; babashka: update to 1.3.190.

- srcpkgs/libXcursor/template
> libXcursor: update to 1.2.2.

- srcpkgs/i3lock/template
> i3lock: add changelog

- srcpkgs/ansible/template
> ansible: update to 9.4.0

- srcpkgs/glances/patches/no-check-update.patch
- srcpkgs/glances/template
> glances: update to 4.0.5.

- srcpkgs/rust-sccache/template
> rust-sccache: update to 0.8.0.

- srcpkgs/usql/template
> usql: update to 0.19.1.

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2024.05.13.

- srcpkgs/pciutils/template
> pciutils: update to 3.12.0.

- srcpkgs/pass-import/template
> pass-import: update to 3.5.

- srcpkgs/gscreenshot/template
> gscreenshot: update to 3.5.0.

- srcpkgs/fonttools/template
> fonttools: update to 4.51.0.

- srcpkgs/cargo-deny/template
> cargo-deny: update to 0.14.19.

- srcpkgs/pgpdump/template
> pgpdump: update to 0.36.

- srcpkgs/ymir/template
> ymir: update to 0.0.7

- srcpkgs/slack-desktop/template
> slack-desktop: update to 4.38.125

- srcpkgs/strongswan/patches/0001-fix-musl.patch
- srcpkgs/strongswan/patches/0002-fix-musl.patch
- srcpkgs/strongswan/template
> strongswan: update to 5.9.14.

- srcpkgs/pavucontrol/template
> pavucontrol: update to 6.0.

- srcpkgs/intellij-idea-community-edition/template
> intellij-idea-community-edition: update to 2024.1.2.

- srcpkgs/autotiling/template
> autotiling: update to 1.9.3

- srcpkgs/azote/template
> azote: update to 1.12.9

- srcpkgs/eqonomize/template
- armv7l
- armv6l-musl
- aarch64-musl
> eqonomize: update to 1.5.7

- srcpkgs/qsv/template
> qsv: update to 0.128.0.

- srcpkgs/hurl/template
> hurl: update to 4.3.0.

- srcpkgs/selene/template
> selene: update to 0.27.1.

- srcpkgs/librsvg/template
> librsvg: update to 2.58.1.

- srcpkgs/logiops/template
> logiops: update to 0.3.4.

- srcpkgs/optipng/template
> optipng: update to 0.7.8.

- srcpkgs/just/template
> just: update to 1.27.0

- srcpkgs/texlab/template
> texlab: update to 5.16.1

- srcpkgs/numbat/template
> numbat: update to 1.12.0

- srcpkgs/golangci-lint/template
> golangci-lint: update to v1.59.0

- srcpkgs/vscode/template
> vscode: update to 1.89.1

- srcpkgs/adwaita-icon-theme/template
> adwaita-icon-theme: update to 46.2.

- srcpkgs/pipewire/template
> pipewire: update to 1.0.7

- srcpkgs/LGOGDownloader/template
> LGOGDownloader: update to 3.13

- srcpkgs/k9s/template
> k9s: update to 0.32.4

- srcpkgs/gnome-tour/template
> gnome-tour: update to 46.0.

- srcpkgs/polari/template
> polari: update to 46.0.

- srcpkgs/autofirma/files/autofirma
- srcpkgs/autofirma/template
> autofirma: fix passing arguments to app

- srcpkgs/nano/template
> nano: update to 8.0.

- srcpkgs/gnome-maps/template
> gnome-maps: update to 46.11.

- srcpkgs/snapshot/template
> snapshot: update to 46.3

- srcpkgs/gnome-boxes/template
> gnome-boxes: update to 46.1.

- srcpkgs/pnpm/template
> pnpm: update to 9.1.3.

- srcpkgs/git-delete-merged-branches/template
> git-delete-merged-branches: update to 7.4.1.

- srcpkgs/lazygit/template
> lazygit: update to 0.42.0.

- srcpkgs/msgraph/template
- srcpkgs/uhttpmock/patches/add-http2-support.patch
- srcpkgs/uhttpmock/template
> msgraph: update to 0.2.2

- srcpkgs/gvfs/template
> gvfs: update to 1.54.1.

- srcpkgs/zk/template
> zk: update to 0.14.1

- srcpkgs/autofirma/template
> autofirma: Add .desktop file to pkg

- srcpkgs/UEFITool/update
> UEFITool: fix broken update-check pattern.

- srcpkgs/git-toolbelt/template
> git-toolbelt: update to 1.9.2.

- srcpkgs/sigi/template
---
Just a handful of non-breaking additive changes
* https://github.com/sigi-cli/sigi/releases/tag/v3.7.0
* https://github.com/sigi-cli/sigi/releases/tag/v3.7.1
> sigi: update to 3.7.1

- srcpkgs/bfs/template
> bfs: update to 3.3.

- srcpkgs/github-cli/template
> github-cli: update to 2.50.0

- srcpkgs/wstunnel/template
> wstunnel: update to 9.6.1

- srcpkgs/limine/template
> limine: update to 7.5.3.

- srcpkgs/python3-term-image/template
- srcpkgs/python3-urwidgets/template
- srcpkgs/toot/template
> toot: update to 0.43 & add shell completion.

- srcpkgs/poezio/template
- srcpkgs/python3-potr/template
- srcpkgs/python3-slixmpp/template
- **New package: python3-potr-1.0.2**
- **python3-slixmpp: update to 1.8.5.**
- **poezio: fix missing dependencies**
> poezio: fix missing dependencies

- srcpkgs/glslViewer/patches/liblo.patch
- srcpkgs/glslViewer/template
> glslViewer: update to 3.2.4.

- srcpkgs/godot/template
> godot: update to 4.2.2

- srcpkgs/python3-netaddr/template
- srcpkgs/python3-phonenumbers/template
- srcpkgs/synapse/template
> synapse: update to 1.108.0.

- srcpkgs/git-cliff/template
> git-cliff: update to 2.3.0

- srcpkgs/7zip/template
> 7zip: update to 24.06.

- srcpkgs/osv-scanner/template
> osv-scanner: update to 1.7.4.

- srcpkgs/sympow/template
> sympow: update to 2.023.7.

- srcpkgs/Tuba/template
> Tuba: update to 0.7.2.

- srcpkgs/containerd/template
> containerd: update to 1.7.17.

- srcpkgs/gradle/template
> gradle: update to 8.8.

- srcpkgs/rot8/template
> rot8: update to 1.0.0.

- srcpkgs/iwd/template
> iwd: update to 2.18

- srcpkgs/wireplumber/template
> wireplumber: update to 0.5.3

- srcpkgs/todoman/template
---
If someone was kind enough to package `python3-sphinx-click`, I would be happy to add the manual page.
> todoman: update to 4.4.0.

- srcpkgs/broot/template
> broot: update to 1.39.0

- srcpkgs/fragments/template
> fragments: update to 3.0.1

- srcpkgs/gitui/template
> gitui: update to 0.26.3

- srcpkgs/tuigreet/template
> tuigreet: update to 0.9.1

- srcpkgs/ruff/template
> ruff: update to 0.4.7.

- srcpkgs/autopep8/template
> autopep8: update to 2.2.0.

- srcpkgs/carapace/template
> carapace: update to 1.0.3.

- srcpkgs/cargo-deny/template
> cargo-deny: update to 0.14.24.

- srcpkgs/nvimpager/template
> nvimpager: update to 0.13.0.

- srcpkgs/python3-peewee/template
> python3-peewee: update to 3.17.5.

- srcpkgs/loksh/template
- aarch64-glibc (crossbuild)
- riscv64 (crossbuild)
> loksh: update to 7.5

- srcpkgs/yggdrasil/template
> yggdrasil: update to 0.5.6

- srcpkgs/oil/template
> oil: update to 0.22.0

- srcpkgs/bc-gh/template
> bc-gh: update to 6.7.5

- common/shlibs
- srcpkgs/gst-libav/template
- srcpkgs/gst-plugins-bad1/template
- srcpkgs/gst-plugins-base1/template
- srcpkgs/gst-plugins-good1/template
- srcpkgs/gst-plugins-ugly1/template
- srcpkgs/gst-rtsp-server/template
- srcpkgs/gst1-editing-services/template
- srcpkgs/gst1-python3/template
- srcpkgs/gstreamer-vaapi/template
- srcpkgs/gstreamer1/template
> Gstreamer: update to 1.24.4

- srcpkgs/gnome-podcasts/template
> gnome-podcasts: update to 0.7.1

- srcpkgs/swirc/template
> swirc: update to 3.4.8.

- srcpkgs/zoom/template
> zoom: update to 6.0.12.5501

- srcpkgs/fuzzypkg/template
> fuzzypkg: update to 1.0.12.

- srcpkgs/kirigami-addons/template
> kirigami-addons: update to 1.2.0.

- srcpkgs/discord/template
> discord: update to 0.0.55

- srcpkgs/incus/files/README.voidlinux
- srcpkgs/incus/patches/32bit.patch
- srcpkgs/incus/template
> incus: update to 6.2

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2024.06.03.

- srcpkgs/eza/template
> eza: update to 0.18.17

- srcpkgs/file-roller/template
> file-roller: update to 44.3

- srcpkgs/gallery-dl/template
> gallery-dl: update to 1.27.0

- srcpkgs/calibre/template
> calibre: update to 7.12.0.

- srcpkgs/mimalloc/template
> mimalloc: update to 2.1.7

- srcpkgs/just/template
> just: update to 1.28.0

- srcpkgs/xz/template
> xz: update to 5.6.2.

- srcpkgs/intellij-idea-ultimate-edition/files/EULA
- srcpkgs/intellij-idea-ultimate-edition/files/README.voidlinux
- srcpkgs/intellij-idea-ultimate-edition/template
- srcpkgs/intellij-idea-ultimate-edition/update
> intellij-idea-ultimate-edition: update to 2024.1.2

- srcpkgs/python3-rapidfuzz/template
> python3-rapidfuzz: update to 3.9.1

- srcpkgs/emptty/template
> emptty: update to 0.12.1

- srcpkgs/spotify-player/template
> spotify-player: update to 0.18.2

- srcpkgs/virtiofsd/template
- I tested the changes in this PR: **YES** (Windows 11 guest)
> virtiofsd: update to 1.11.0

- srcpkgs/davmail/template
> davmail: update to 6.2.2.

- srcpkgs/glances/template
> glances: update to 4.0.7.

- srcpkgs/gdown/template
> gdown: update to 5.2.0.

- srcpkgs/fonttools/template
> fonttools: update to 4.53.0.

- srcpkgs/greetd/template
> greetd: update to 0.10.3

- srcpkgs/blueman/template
> blueman: update to 2.4.2

- srcpkgs/poweralertd/template
> poweralertd: update to 0.3.0

- srcpkgs/rygel/template
> rygel: update to 0.42.6.

- srcpkgs/mesa/template
> mesa: update to version 24.1.1.

- srcpkgs/gtkwave/template
> gtkwave: update to 3.3.119

- srcpkgs/google-chrome/template
> google-chrome: update to 125.0.6422.141.

- srcpkgs/vscode/template
> vscode: update to 1.90.0

- common/shlibs
- srcpkgs/gnubg/template
- srcpkgs/libcanberra-gtk
- srcpkgs/libcanberra/template
> gnubg gtk 3

- srcpkgs/opam/template
> opam: Update to 2.1.6

- srcpkgs/nvidia/template
> nvidia: update to 550.90.07.

- srcpkgs/vis/template
- I built this PR locally for architecture:
- x86_64
- i686
> vis: update to 0.9, adopt

- srcpkgs/hyperrogue/template
> hyperrogue: update to 13.0o

- srcpkgs/mercurial/template
> mercurial: update to 6.7.3.

- srcpkgs/arti/template
> arti: update to 1.2.4.

- srcpkgs/bfs/template
> bfs: update to 3.3.1.

- srcpkgs/qutebrowser/template
> qutebrowser: update to 3.2.0.

- srcpkgs/discord/template
> discord: update to 0.0.56

- srcpkgs/lemonbar/template
- I built this PR locally for my native architecture: **x86_64-musl**
- I built this PR locally for architecture:
- x86_64
- i686
> lemonbar: update to 1.5

- srcpkgs/exiftool/template
- I built this PR locally for my native architecture: **x86_64-musl**
- I built this PR locally for architecture:
- x86_64
- i686
> exiftool: update to 12.86

- srcpkgs/golangci-lint/template
> golangci-lint: update to 1.59.1

- srcpkgs/orca/template
- I tested the changes in this PR: NO
- armv7l-musl
> orca: update to 46.1.

- srcpkgs/wstunnel/template
> wstunnel: update to 9.6.2

- srcpkgs/pueue/template
> pueue: update to 3.4.1

- srcpkgs/rosegarden/template
> rosegarden: update to 24.06

- srcpkgs/ETL/template
- srcpkgs/synfig/template
- srcpkgs/synfigstudio/template
> synfigstudio (and dependencies): update to 1.4.5

- srcpkgs/praat/template
> praat: update to 6.4.13

- srcpkgs/ferium/template
- I built this PR locally for my native architecture, (`x86-64_glibc`)
tests may fail here if github api is malevolent on the ci runners. have confirmed that the tests complete on my local machine with my own github personal access token
> ferium: update to 4.7.0.

- srcpkgs/mercurial/template
Fix for https://lists.mercurial-scm.org/pipermail/mercurial/2024-June/106436.html
> mercurial: update to 6.7.4.

- srcpkgs/fwupd/template
> fwupd: update to 1.9.20.

- srcpkgs/conduit/patches/config.patch
- srcpkgs/conduit/template
> conduit: update to 0.8.0.

- srcpkgs/postgresql15/template
- srcpkgs/postgresql16/template
> postgresql16: update to 16.3.

- srcpkgs/ast-grep/template
> ast-grep: update to 0.22.6.

- srcpkgs/limine/template
> limine: update to 7.7.2.

- common/shlibs
- srcpkgs/audacious-base/template
- srcpkgs/audacious-plugins/template
- srcpkgs/audacious/template
> audacious: update to 4.4.

- srcpkgs/rpi-eeprom/template
- srcpkgs/rpi-firmware/template
- srcpkgs/rpi-kernel/template
- srcpkgs/rpi-utils/template
[ci skip]
will be building packages for testing soon, taking requests for kernel config items to add
fixes #50669
> rpi update

- srcpkgs/pipewire/template
> pipewire: drop unused graphviz build dependency

- srcpkgs/e16/template
> e16: update to 1.0.29

- srcpkgs/astyle/patches/enable-cpp17.patch
- srcpkgs/astyle/template
> astyle: update to 3.5.

- srcpkgs/frp/template
> frp: update to 0.58.1.

- srcpkgs/yazi/template
> New package: yazi-0.2.5

- common/shlibs
- srcpkgs/mtxclient/template
- srcpkgs/nheko/template
- **mtxclient: update to 0.10.0.**
- **nheko: update to 0.12.0.**
- I tested the changes in this PR: Basic usage, not calls.
> nheko 0.12.0

- srcpkgs/intellij-idea-community-edition/files/idea.desktop
- srcpkgs/intellij-idea-community-edition/template
> intellij-idea-community-edition: removing unvendored desktop file

- srcpkgs/codec2/template
- srcpkgs/dcadec/template
- srcpkgs/font-libre-hebrew/template
- srcpkgs/fsv/template
- srcpkgs/gnunet/template
- srcpkgs/gsoap/template
- srcpkgs/iotop/template
- srcpkgs/lbzip2/template
- srcpkgs/libx86/template
- srcpkgs/par/template
- srcpkgs/pingus/template
- srcpkgs/python3-pychm/template
- srcpkgs/qt5-webkit/template
- srcpkgs/taglib-extras/template
follows https://github.com/leahneukirchen/xtools/pull/324
> srcpkgs/: use ${version} in distfiles

- srcpkgs/tuir/patches/0001-Adjust-for-python-3.12-method-removal.patch
- srcpkgs/tuir/template
> tuir: adjust for python 3.12 method removal

- srcpkgs/xmldiff/template
> xmldiff: update to 2.7.0.

- srcpkgs/docker-compose/template
> docker-compose: update to 2.27.1

- srcpkgs/gajim/files/README.voidlinux
- srcpkgs/gajim/patches/remove_broken_test.patch
- srcpkgs/gajim/template
- srcpkgs/python3-nbxmpp/template
Python3-nbxmpp is here too, as dependency
> gajim: update to 1.9.0, adopt.

- srcpkgs/python3-parse/template
> python3-parse: update to 1.20.2.

- srcpkgs/libical/template
> libical: update to 3.0.18.

- srcpkgs/gdu/template
> gdu: update to 5.29.0.

- srcpkgs/libfontenc/template
> libfontenc: update to 1.1.8.

- srcpkgs/discord/template
> discord: update to 0.0.57

- srcpkgs/schismtracker/template
> schismtracker: update to 20240614

- srcpkgs/xsm/template
> xsm: update to 1.0.6.

- srcpkgs/haproxy/template
> haproxy: update to 2.8.10.

- srcpkgs/vscode/template
> vscode: update to 1.90.1

- srcpkgs/pyradio/template
> pyradio: update to 0.9.3.9

- srcpkgs/zoom/template
- I built this PR locally for my native architecture, (**x86_64 glibc**)
> zoom: update to 6.1.0.198

- srcpkgs/swww/template
- aarch64-musl
- armv7l
- armv6l-musl
> New package: swww-0.9.5

- srcpkgs/audit/patches/strndupa.patch
- srcpkgs/audit/template
> audit: update to 3.1.4

- srcpkgs/xonsh/template
- armv7l
- armv6l-musl
- aarch64-musl
> This release is highly recommended. Please update your xonsh.
> xonsh: update to 0.17.0

- srcpkgs/epiphany/template
> epiphany: update to 46.1.

- srcpkgs/tecla/template
> tecla: update to 46.0

- srcpkgs/liferea/patches/libwebkit2gtk41.patch
- srcpkgs/liferea/template
> liferea: update to 1.14.6.

- srcpkgs/goodvibes/template
> goodvibes: update to 0.8.0.

- srcpkgs/bookworm/template
> bookworm: simplify patch

- srcpkgs/at-spi2-core/template
> at-spi2-core: update to 2.52.0.

- srcpkgs/gmime/template
> gmime: update to 3.2.15.

- srcpkgs/tracker-miners/template
- srcpkgs/tracker/template
> tracker{,-miners}: update to 3.7.3

- srcpkgs/GPaste/template
> GPaste: update to 45.1.

- srcpkgs/python3-zipp/template
> python3-zipp: update to 3.19.2.

- srcpkgs/python3-Levenshtein/template
> python3-Levenshtein: update to 0.25.1

- srcpkgs/python3-rapidfuzz/patches/scikit-build-ver.patch
- srcpkgs/python3-rapidfuzz/template
- srcpkgs/python3-scikit-build/template
> python3-scikit-build: update to 0.18.0

- srcpkgs/linux-mainline/template
> linux-mainline: update to 6.9.

- srcpkgs/discord/template
> discord: update to 0.0.58

- srcpkgs/github-cli/template
> github-cli: update to 2.52.0

- srcpkgs/vivid/template
> vivid: update to 0.10.1

- srcpkgs/zola/template
> zola: update to 0.19.1

- srcpkgs/dbeaver/patches/force-jdk17.patch
- srcpkgs/dbeaver/template
> dbeaver: update to 24.1.1.

- srcpkgs/Tuba/template
> Tuba: update to 0.8.1.

- srcpkgs/gopls/template
> gopls: update to 0.16.0.

- srcpkgs/k3d/template
> k3d: update to 5.6.3.

- srcpkgs/dialog/template
> dialog: update to 1.3.20240619.

- srcpkgs/osv-scanner/template
> osv-scanner: update to 1.8.1.

- srcpkgs/vale/template
> vale: update to 3.6.0.

- srcpkgs/gallery-dl/template
> gallery-dl: updated to 1.27.1

- srcpkgs/wmenu/template
> wmenu: update to 0.1.9, switch upstream

- srcpkgs/pdfarranger/template
> pdfarranger: update to 1.11.0.

- srcpkgs/pmbootstrap/template
> pmbootstrap: update to 2.3.1.

- srcpkgs/keepassxc/template
> keepassxc: update to 2.7.9

- srcpkgs/orca/template
> orca: update to 46.2.

- srcpkgs/PrismLauncher/template
> PrismLauncher: update to 8.4

- srcpkgs/python3-Faker/template
> python3-Faker: update to 25.9.1.

- srcpkgs/pango/template
> pango: update to 1.54.0

- srcpkgs/just/template
> just: update to 1.29.1

- srcpkgs/libshumate/template
> libshumate: update to 1.2.2

- srcpkgs/cargo-modules/template
> cargo-modules: update to 0.16.3.

- srcpkgs/clifm/template
- I built this PR locally for my native architecture, x86-64-glibc
> clifm: update to 1.19.

- srcpkgs/gajim/template
- srcpkgs/python3-nbxmpp/template
- **python3-nbxmpp: update to 5.0.1.**
- **gajim: update to 1.9.1.**
>  gajim: update to 1.9.1. 

- srcpkgs/cherrytree/template
> cherrytree: update to 1.1.3

- srcpkgs/wstunnel/template
> wstunnel: update to 9.7.1

- srcpkgs/ruby-erubi/template
- srcpkgs/ruby-tmuxinator/template
> ruby-tmuxinator: update to 3.3.0.

- srcpkgs/gnome-sudoku/template
> gnome-sudoku: update to 46.2

- srcpkgs/aisleriot/template
> aisleriot: update to 3.22.33

- srcpkgs/gnome-online-accounts/template
> gnome-online-accounts: add libadwaita-devel to subpkg's depends

- srcpkgs/NetworkManager-openconnect/template
Fixes: https://github.com/void-linux/void-packages/issues/50867
> NetworkManager-openconnect: update to 1.2.10.

- srcpkgs/ClusterSSH/patches/15config.diff
- srcpkgs/ClusterSSH/template
- armv7l
- armv6l-musl
- aarch64-musl
> ClusterSSH: update to 4.16

- srcpkgs/codeberg-cli/template
> codeberg-cli: update to 0.4.2

- srcpkgs/git-cliff/patches/downgrade-git2.patch
- srcpkgs/git-cliff/template
> git-cliff: update to 2.4.0

- srcpkgs/gtksourceview5/template
> gtksourceview5: update to 5.12.1

- srcpkgs/memray/template
- srcpkgs/python3-textual/template
> python3-textual: update to 0.70.0; memray: update to 1.13.0.

- srcpkgs/autopep8/template
- srcpkgs/python3-pycodestyle/template
> python3-pycodestyle: update to 2.12.0; autopep8: update to 2.3.1.

- srcpkgs/python3-platformdirs/template
> python3-platformdirs: update to 4.2.2.

- srcpkgs/python3-virtualenv/template
> python3-virtualenv: update to 20.26.3.

- srcpkgs/limine/template
> limine: update to 7.9.0.

- srcpkgs/perl-CGI/template
> perl-CGI: update to 4.66

- srcpkgs/ntpd-rs/patches/fix-tests.patch
- srcpkgs/ntpd-rs/template
> ntpd-rs: update to 1.1.3

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2024.06.24.

- srcpkgs/akonadi-mime/template
- srcpkgs/kf6-kguiaddons/template
- srcpkgs/kf6-kidletime/template
- srcpkgs/kf6-kwayland/template
- srcpkgs/kf6-kwindowsystem/template
- srcpkgs/kguiaddons/template
- srcpkgs/kidletime/template
- srcpkgs/kpipewire/template
- srcpkgs/krfb/template
- srcpkgs/kwayland-integration/template
- srcpkgs/kwayland/template
- srcpkgs/kwin/template
- srcpkgs/libkf6screen/template
- srcpkgs/libplasma/template
- srcpkgs/plasma-desktop/template
- srcpkgs/plasma-integration/template
- srcpkgs/plasma-wayland-protocols/template
- srcpkgs/plasma-workspace/template
- srcpkgs/xdg-desktop-portal-kde/template
> [DO NOT MERGE] plasma-wayland-protocols update

- srcpkgs/limine/template
> limine: update to 7.9.1.

- srcpkgs/instaloader/template
> instaloader: update to 4.12.

- srcpkgs/tuxedo-drivers/template
- builds on kernels 5.15, 5.16, 5.18, 5.19, 6.0 through 6.9, running on 6.9.6
> tuxedo-drivers: update to 4.5.3

- srcpkgs/font-sarasa-gothic/template
> font-sarasa-gothic: update to 1.0.15.

- srcpkgs/fx/template
> fx: update to 35.0.0.

- srcpkgs/ast-grep/template
> ast-grep: update to 0.24.1.

- srcpkgs/ergo/template
> ergo: update to 2.14.0.

- srcpkgs/python3-plotly/template
I've tested using a few scripts I wrote and they work perfectly after tweaking to new syntax in the new version.
> python3-plotly: update to 5.22.0.

- srcpkgs/gscreenshot/template
> gscreenshot: update to 3.5.1.

- srcpkgs/feh/template
> feh: update to 3.10.3

- srcpkgs/python3-pylast/template
Basically a revival  of #43161, but I did check https://github.com/pylast/pylast/blob/main/pyproject.toml a bit to make sure the deps are still in line with current version.
> python3-pylast: update to 5.3.0.

- srcpkgs/yaru/template
> yaru: update to 24.04.3

- srcpkgs/llvm/template
- srcpkgs/llvm18/template
> llvm18 fix docs, trigger build

- srcpkgs/libadwaita/template
> libadwaita: update to 1.5.2

- srcpkgs/calibre/template
> calibre: update to 7.13.0.

- srcpkgs/gopls/template
> gopls: update to 0.16.1.

- common/shlibs
- srcpkgs/btfs/template
- srcpkgs/libtorrent-rasterbar/template
- srcpkgs/qbittorrent/template
> qbittorrent: update to 4.6.5, libtorrent-rasterbar: update to 1.2.19, btfs: revbump

- srcpkgs/zoom/template
> zoom: update to 6.1.1.443

- common/hooks/post-install/15-qt-private-api.sh
> hooks/post-install: check for -private-devel if PRIVATE_API is used

- srcpkgs/borg/template
> borg: update to 1.4.0.

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2024.07.01.

- srcpkgs/flare-engine/template
- srcpkgs/flare-game/template
> flare-game: update to 1.14

- srcpkgs/discord/template
> discord: update to 0.0.59

- srcpkgs/texlab/template
> texlab: update to 5.19.0

- srcpkgs/iwd/template
> iwd: update to 2.19

- srcpkgs/bemenu/template
> bemenu: update to 0.6.22

- srcpkgs/sops/template
> sops: update to 3.9.0

- srcpkgs/broot/template
> broot: update to 1.39.2

- srcpkgs/just/template
> just: update to 1.30.1

- srcpkgs/spotify-player/template
> spotify-player: update to 0.19.1

- srcpkgs/swayimg/template
- I built this PR locally for my native architecture: x86-64_libc
- armv7l (crossbuilds)
> swayimg: update to 2.3

- srcpkgs/halloy/template
> halloy: update to 2024.8

- srcpkgs/watchexec/template
> watchexec: update to 2.1.2

- srcpkgs/wstunnel/template
> wstunnel: update to 9.7.2

- srcpkgs/imhex/patches/cross.patch
- srcpkgs/imhex/template
> imhex: update to 1.35.3.

- srcpkgs/warzone2100/template
It looks nicer with word-wrap off (not an option in FF), their changelog has very long lines and wrapping breaks the formatting
@Hoshpak
> warzone2100: add changelog 

- srcpkgs/yt-dlp/template
> yt-dlp: update to 2024-07-09

- srcpkgs/audex/template
> audex: update to 24.05.2.

- srcpkgs/pnpm/template
> pnpm: update to 9.5.0.

- srcpkgs/xh/template
> xh: update to 0.22.2

- srcpkgs/OpenRCT2/template
> OpenRCT2: update to 0.4.12.

- srcpkgs/neochat/template
> neochat: update to 24.05.2.

- srcpkgs/joker/template
> joker: update to 1.4.0.

- srcpkgs/carapace/template
> carapace: update to 1.0.4.

- srcpkgs/gvfs/template
> gvfs: update to 1.54.2

- srcpkgs/fend/template
> fend: update to 1.5.0

- srcpkgs/retroarch/template
> retroarch: update to 1.19.1.

- common/shlibs
- srcpkgs/filezilla/template
- srcpkgs/libfilezilla/template
> libfilezilla: update to 0.48.1; filezilla: update to 3.67.1

- srcpkgs/chathistorysync/template
> chathistorysync: update to 0.2.1.

- srcpkgs/python3-mdit-py-plugins/template
> python3-mdit-py-plugins: update to 0.4.1.

- srcpkgs/linux-wifi-hotspot/template
> linux-wifi-hotspot: update to 4.7.2.

- srcpkgs/yamlfmt/template
> New package: yamlfmt-0.13.0

- srcpkgs/kubernetes-helm/template
> kubernetes-helm: update to 3.15.3

- srcpkgs/pipewire/patches/fix-conflicting-meson-deps.patch
- srcpkgs/pipewire/template
- srcpkgs/pipewire/update
- srcpkgs/wireplumber/template
> pipewire: update to 1.2.0; wireplumber: update to 0.5.5

- srcpkgs/wcm/template
- I tested the changes in this PR: **YES** (and it fixes a crash when setting a bunch of options)
> wcm: update to 0.8.0.

- srcpkgs/nvidia/template
> nvidia: update to 550.100.

- srcpkgs/gns3-gui/template
- srcpkgs/gns3-server/template
> GNS3: update to 2.2.48

- srcpkgs/VVVVVV/patches/data-zip-path.diff
- srcpkgs/VVVVVV/template
> New package: VVVVVV-2.3.6.

- common/shlibs
- srcpkgs/SPIRV-Headers/template
- srcpkgs/SPIRV-LLVM-Translator/template
- srcpkgs/SPIRV-Tools/template
- srcpkgs/libclc/template
- srcpkgs/mesa/template
>  mesa: update to 24.1.3, build with llvm18. 

- srcpkgs/labwc/template
> labwc: update to 0.7.3

- srcpkgs/opam/template
> opam: upgrade to 2.2.0

- srcpkgs/gopass-jsonapi/template
- srcpkgs/gopass/template
> gopass{,-jsonapi}: update to 1.15.13

- srcpkgs/gnucash/template
> gnucash: update to 5.8

- srcpkgs/python3-humanize/template
> python3-humanize: update to 4.10.0.

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2024.07.08.

- srcpkgs/osinfo-db/template
> osinfo-db: update to 20240701.

- srcpkgs/libdrm/template
> libdrm: update to 2.4.122

- srcpkgs/diffuse/template
> diffuse: update to 0.9.0

- srcpkgs/lite-xl/template
> lite-xl: update to 2.1.5

- srcpkgs/osv-scanner/template
> osv-scanner: update to 1.8.2.

- srcpkgs/limine/template
> limine: update to 7.10.1.

- srcpkgs/python3-importlib_metadata/template
> python3-importlib_metadata: update to 8.0.0.

- srcpkgs/vale/template
> vale: update to 3.6.1.

- srcpkgs/limine/template
> limine: update to 7.10.2.

- srcpkgs/helix/template
> helix: update to 24.07

- srcpkgs/libreoffice-dictionaries/template
it causes xbps-src-make to panic when encountered
cc @sgn
> libreoffice-dictionaries: don't use alias

- srcpkgs/libedit/template
> libedit: update to 20240517.3.1.

- srcpkgs/gscreenshot/template
> gscreenshot: update to 3.6.1.

- srcpkgs/oxipng/template
> oxipng: update to 9.1.2.

- srcpkgs/geary/template
> geary: update to 46.0

- srcpkgs/limine/template
> limine: update to 7.10.3.

- srcpkgs/discord-ptb/template
> discord-ptb: update to 0.0.94.

- srcpkgs/ircdog/template
> ircdog: update to 0.5.4.

- srcpkgs/nano/template
> nano: update to 8.1.

- srcpkgs/gnutls/template
> gnutls: update to 3.8.6

- srcpkgs/alsa-lib/template
- srcpkgs/alsa-ucm-conf/template
- srcpkgs/alsa-utils/template
> alsa-{lib,ucm-conf,utils}: update to 1.2.12

- srcpkgs/pipewire/template
> pipewire: update to 1.2.1

- srcpkgs/swayimg/template
> swayimg: update to 2.4.

- srcpkgs/geckodriver/template
> geckodriver: update to 0.34.0

- srcpkgs/ghidra/patches/protoc.patch
- srcpkgs/ghidra/template
I also briefly tested Ghidrathon with this version.
> ghidra: update to 11.1.2.

- srcpkgs/dk/template
- x86_64-musl
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
> dk: update to 2.3.

- srcpkgs/github-cli/template
> github-cli: update to 2.53.0

- srcpkgs/llvm18/template
> llvm18: fix cycle on graphviz

- srcpkgs/font-inter-variable
- srcpkgs/font-inter/template
> font-inter: update to 4.0.

- srcpkgs/eza/template
> eza: update to 0.18.22

- srcpkgs/wayland/template
> wayland: update to 1.23.0

- srcpkgs/ntpd-rs/template
> ntpd-rs: update to 1.2.2

- srcpkgs/python3-aiohappyeyeballs/template
- srcpkgs/python3-aiohttp/template
- I tested the changes in this PR: **in progress**
cc: @the-maldridge
> python3-aiohttp: update to 3.9.5

- srcpkgs/limine/template
> limine: update to 7.11.0.

- srcpkgs/labwc/template
> labwc: update to 0.7.4

- srcpkgs/atlantis/template
Updating to 0.28.5 and changing my email address.
- aarch64-musl
- aarch64
> atlantis: update to 0.28.5

- srcpkgs/mise/template
> mise: update to 2024.7.4.

- srcpkgs/unpaper/template
> unpaper: update to 7.0.0.

- srcpkgs/cmus/template
> cmus: update to 2.11.0

- srcpkgs/handbrake/patches/fix-missing-x265-link-flag.patch
- srcpkgs/handbrake/patches/libhb-vpl-include.patch
- srcpkgs/handbrake/template
> handbrake: update to 1.6.1

- srcpkgs/guvcview/template
> guvcview: revbump for ffmpeg6

- srcpkgs/discord/template
> discord: update to 0.0.61

- srcpkgs/swayr/template
- srcpkgs/swayrbar/template
> New package: swayr & swayrbar

- srcpkgs/soft-serve/files/soft-serve/run
- srcpkgs/soft-serve/template
- I built this PR locally for my native architecture, x64 glibc
> New package: soft-serve-0.7.4

- srcpkgs/treefmt/template
> New package: treefmt-2.0.1

- srcpkgs/python3-pillow_heif/template
> New package: python3-pillow_heif-0.17.0

- srcpkgs/typstyle/template
> New package: typstyle-0.11.28

- srcpkgs/swaysome/template
> New package: swaysome-2.1.1.

- srcpkgs/handbrake/template
Unfortunately it seems they primarily use GitHub releases as their changelog, so xchangelog will have to open a browser
> handbrake: add changelog

- srcpkgs/i2pd/template
> i2pd: update to 2.53.0

- srcpkgs/strawberry/template
> strawberry: update to 1.1.1

- srcpkgs/clojure-lsp/template
> clojure-lsp: set graal as java distribution

- srcpkgs/vhs/template
> vhs: depend on ffmpeg6

- srcpkgs/xq/template
XQ is a parser for XML and HTML similar to what JQ does for JSON.
https://github.com/sibprogrammer/xq
> New package: xq-1.2.4

- srcpkgs/heisenbridge/files/heisenbridge/run
- srcpkgs/heisenbridge/template
- srcpkgs/python3-mautrix/template
Crossbuilt in x86-glibc and tested on aarch64-musl with conduit.
> New package: heisenbridge-1.14.6

- srcpkgs/libvirt-python3/template
- srcpkgs/libvirt/template
- srcpkgs/qemu-user-static/template
- srcpkgs/qemu/template
> qemu(-user-static): update to 9.0.2, libvirt(-python3): update to 10.5.0

- srcpkgs/zoom/template
> zoom: update to 6.1.5.871

- srcpkgs/shotman/template
> shotman: update to 0.4.6.

- srcpkgs/librsvg/template
> librsvg: update to 2.58.2.

- srcpkgs/libsecret/template
> libsecret: update to 0.21.4

- srcpkgs/RyzenAdj/template
> RyzenAdj: update to 0.15.0.

- srcpkgs/ruby-build/template
Can I also become new maintainer of this package?
> ruby-build: update to 20240722

- common/shlibs
- srcpkgs/deadbeef/patches/musl_strdupa.patch
- srcpkgs/deadbeef/patches/patch_skip_glade_translations.patch
- srcpkgs/deadbeef/template
- srcpkgs/libdispatch-devel
- srcpkgs/libdispatch/patches/musl.patch
- srcpkgs/libdispatch/patches/werror.patch
- srcpkgs/libdispatch/template
- **x86_64-musl**
Runs, plays music
> deadbeef: update to 1.9.6

- srcpkgs/neovim/template
> neovim: update to 0.10.1

- srcpkgs/mandrel/template
> mandrel: update to 23.1.4.0.

- srcpkgs/way-displays/template
> way-displays: update to 1.11.0.

- srcpkgs/rbenv/template
> rbenv: update to 1.3.0

- srcpkgs/uni/template
> uni: update to 2.7.0.

- srcpkgs/Waybar/template
> Waybar: update to 0.10.4

- srcpkgs/python3-pluggy/template
- I tested the changes in this PR: **YES** (with pytest 8)
> python3-pluggy: update to 1.5.0.

- srcpkgs/calibre/template
> calibre: update to 7.15.0.

- common/shlibs
- srcpkgs/benchmark/template
> benchmark: update to 1.8.5.

- srcpkgs/python3-regex/template
> python3-regex: update to 2024.7.24.

- srcpkgs/swayimg/template
> swayimg: update to 2.5.

- srcpkgs/orc/template
> orc: update to 0.4.39

- srcpkgs/mercurial/template
> mercurial: update to 6.8.

- srcpkgs/darktable/patches/0001-define-target_clones-attribute-only-for-glibc.patch
- srcpkgs/darktable/template
- srcpkgs/libosmgpsmap/patches/libsoup-3.patch
- srcpkgs/libosmgpsmap/template
Includes the libosmgpsmap update #49955
> darktable: update to 4.8.1. 

- srcpkgs/ncdc/template
> ncdc: update to 1.24.1

- srcpkgs/difftastic/template
> difftastic: update to 0.59.0.

- srcpkgs/dbeaver/template
> dbeaver: update to 24.1.3

- srcpkgs/gnome-sudoku/template
> gnome-sudoku: update to 46.3.

- srcpkgs/strace/template
> strace: update to 6.10.

- srcpkgs/croc/template
Maintainer @benalb haven't updated croc in a long time
> croc: update to 10.0.10

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2024.07.22.

- srcpkgs/cargo-modules/template
> cargo-modules: update to 0.16.6.

- srcpkgs/tflint/template
- I built this PR locally for my native architecture, **x86-64-libc**
- aarch64
- aarch64-musl
> tflint: update to 0.52.0

- srcpkgs/opentofu/template
> New package: opentofu-1.7.3

- srcpkgs/limine/template
> limine: update to 7.12.1.

- srcpkgs/python/template
see https://github.com/ActiveState/cpython/pull/35
> python: unbreak hashlib

- srcpkgs/python3-apprise/template
- srcpkgs/python3-sabctools/patches/cross.patch
- srcpkgs/python3-sabctools/template
- srcpkgs/sabnzbd/template
- **sabnzbd: update to 4.3.2.**
- **New package: python3-sabctools-8.2.4**
- **New package: python3-apprise-1.8.1**
> sabnzbd: update to 4.3.2

- srcpkgs/yaydl/template
> yaydl: update to 0.14.1

- srcpkgs/ast-grep/template
> ast-grep: update to 0.25.4.

- srcpkgs/vale/template
> vale: update to 3.7.0.

- srcpkgs/trash-cli/template
> trash-cli: update to 0.24.5.26.

- srcpkgs/exiftool/template
> exiftool: update to 12.92

- srcpkgs/gscreenshot/template
> gscreenshot: update to 3.6.2.

- srcpkgs/treefmt/template
> treefmt: update to 2.0.3.

- srcpkgs/wvkbd/template
> wvkbd: update to 0.15.

- srcpkgs/mdcat/template
> mdcat: update to 2.3.0

- srcpkgs/jdupes/template
- srcpkgs/libjodycode/template
> libjodycode: update to 3.1.1; jdupes: update to 1.28.0

- srcpkgs/nushell/template
> nushell: update to 0.96.1

- srcpkgs/wine/template
> wine: Update to 9.14

- srcpkgs/halloy/template
> halloy: update to 2024.9

- srcpkgs/ruby-build/template
> ruby-build: update to 20240727

- srcpkgs/qmk/template
> qmk: update to 1.1.5.

- srcpkgs/claws-mail/template
> claws-mail: update to 4.3.0

- srcpkgs/discord/template
> discord: update to 0.0.62

- srcpkgs/pylint/template
- srcpkgs/python3-astroid/template
> pylint: update to 3.2.6

- srcpkgs/buildah/template
> buildah: update to 1.37.0

- srcpkgs/podman-tui/template
> podman-tui: update to 1.1.0

- srcpkgs/zoom/template
> zoom: update to 6.1.6.1013

- srcpkgs/nerd-fonts/template
> nerd-fonts: update to 3.2.1

- srcpkgs/gocloc/template
> gocloc: update to 0.5.2

- srcpkgs/swaybg/template
> swaybg: update to 1.2.1

- srcpkgs/gst-libav/template
- srcpkgs/gst-plugins-bad1/template
- srcpkgs/gst-plugins-base1/template
- srcpkgs/gst-plugins-good1/template
- srcpkgs/gst-plugins-ugly1/template
- srcpkgs/gst-rtsp-server/template
- srcpkgs/gst1-editing-services/template
- srcpkgs/gst1-python3/template
- srcpkgs/gstreamer-vaapi/template
- srcpkgs/gstreamer1/template
> Gstreamer: update to 1.24.6

- srcpkgs/ghdl/template
- srcpkgs/mozjs102/template
-  x86_64-musl
-  i686
-  aarch64 (cross)
-  aarch64-musl (cross)
-  armv7l (cross)
-  armv7l-musl (cross)
-  armv6l (cross)
-  armv6l-musl (cross)
> Rebuild final llvm12 packages

- srcpkgs/codeberg-cli/patches/downgrade-git2.patch
- srcpkgs/codeberg-cli/template
> codeberg-cli: update to 0.4.3
