void-linux/void-packages

srcpkgs/rio/template

rio: update to 0.1.3

---

srcpkgs/nvidia/template

nvidia: update to 550.107.02

---

srcpkgs/trurl/template

trurl: update to 0.14.

---

srcpkgs/synapse/template

synapse: update to 1.112.0.

---

srcpkgs/NetworkManager/template

NetworkManager: update to 1.48.6

---

srcpkgs/Thunar/template

Thunar: update to 4.18.11

---

srcpkgs/docker-compose/template

docker-compose: update to 2.29.1

---

srcpkgs/github-cli/template

github-cli: update to 2.54.0

---

srcpkgs/sysstat/template
srcpkgs/sysstat/update

@leahneukirchen pulling from GH to fix broken update-check

sysstat: update to 12.7.6.

---

srcpkgs/calibre/template

calibre: update to 7.16.0.

---

srcpkgs/fwupd/template

fwupd: add changelog

---

srcpkgs/limine/template

limine: update to 8.0.0.

---

srcpkgs/eza/template

eza: update to 0.18.24

---

srcpkgs/spotify/template

spotify: update to 1.2.42.

---

srcpkgs/halloy/template

halloy: update to 2024.10

---

srcpkgs/swayimg/template

swayimg: update to 3.0.

---

srcpkgs/cpuid/template

cpuid: update to 20240716.

---

srcpkgs/hcloud/template

hcloud: update to 1.46.0.

---

srcpkgs/rest-server/template

rest-server: update to 0.13.0.

---

srcpkgs/pgmetrics/template

pgmetrics: update to 1.17.0.

---

srcpkgs/dbeaver/template

dbeaver: update to 24.1.4

---

srcpkgs/MoarVM/template
srcpkgs/nqp/template
srcpkgs/rakudo/template

rakudo: update to 2024.07.

---

srcpkgs/OpenRCT2/template

OpenRCT2: update to 0.4.13.

---

srcpkgs/limine/template

limine: update to 8.0.1.

---

common/shlibs
srcpkgs/acfgfs/template
srcpkgs/aclip/template
srcpkgs/aloadimage/template
srcpkgs/arcan/template
srcpkgs/xarcan/template

I'm CI building then I'll try on aarch64-musl

Arcan 6.3.3

---

srcpkgs/fuse-overlayfs/template

fuse-overlayfs: update to 1.14

---

srcpkgs/libslirp/template
srcpkgs/slirp4netns/template

libslirp: update to 4.8.0; slirp4netns: update to 1.3.1

---

srcpkgs/cni-plugins/template
srcpkgs/cni/template

cni: update to 1.2.3; cni-plugins: update to 1.5.1

---

srcpkgs/yggdrasil/template

yggdrasil: update to v0.5.7

---

srcpkgs/difftastic/template

difftastic: update to 0.60.0.

---

srcpkgs/python3-path/template

python3-path: update to 17.0.0.

---

srcpkgs/discord/template

discord: update to 0.0.63

---

srcpkgs/beancount/template
srcpkgs/python3-pytest-import-check/template
srcpkgs/python3-pytest/patches/man-remove-sphinx-deps.patch
srcpkgs/python3-pytest/template
srcpkgs/python3-rx/template

- I tested the changes in this PR: **YES** (WIP)

update python3-pytest, new package: python3-pytest-import-check

---

srcpkgs/rio/template

rio: update to 0.1.4

---

srcpkgs/qutebrowser/template

qutebrowser: update to 3.2.1

---

srcpkgs/qsv/template

qsv: update to 0.130.0.

---

srcpkgs/mise/template

mise: update to 2024.8.5.

---

srcpkgs/curl/patches/fix-sigpipe.patch
srcpkgs/curl/template

curl: update to 8.9.1

---

srcpkgs/python3-curl/template

python3-curl: update to 7.45.3.

---

srcpkgs/rockpro64-base/INSTALL
srcpkgs/rockpro64-base/template
srcpkgs/rockpro64-base/update
srcpkgs/rockpro64-uboot/template
srcpkgs/rockpro64-uboot/update

PR based on https://github.com/void-linux/void-packages/pull/33556

New packages: rockpro64-base and rockpro64-uboot

---

srcpkgs/terraform-docs/template

terraform-docs: update to 0.18.0.

---

srcpkgs/waifu2x-converter-cpp/patches/fix-cross.patch
srcpkgs/waifu2x-converter-cpp/patches/fix-cstdio.patch
srcpkgs/waifu2x-converter-cpp/template

waifu2x-converter-cpp: update to 5.3.4.

---

srcpkgs/mpvpaper/template

- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- i686
- x86_64-musl

mpvpaper: update to 1.7.

---

srcpkgs/k3d/template

k3d: update to 5.7.3.

---

srcpkgs/qtractor/template

qtractor: update to 1.1.1

---

srcpkgs/glab/template

glab: update to 1.45.0.

---

srcpkgs/keyd/template

keyd: update to 2.5.0.

---

common/shlibs
srcpkgs/grpc/patches/revert-find-protobuf.patch
srcpkgs/grpc/template
srcpkgs/protonmail-bridge/patches/no-gui-tester.patch
srcpkgs/protonmail-bridge/patches/no-vcpkg.patch
srcpkgs/protonmail-bridge/patches/protobuf-cmake.patch
srcpkgs/protonmail-bridge/patches/system-gtest.patch
srcpkgs/protonmail-bridge/patches/system-icu.patch
srcpkgs/protonmail-bridge/template
srcpkgs/sentry-native-devel
srcpkgs/sentry-native/template

[WIP] protonmail-bridge: update to 3.12.0.

---

srcpkgs/butt/template

butt: update to 1.43.0.

---

srcpkgs/openvpn/template

openvpn: update to 2.6.12.

---

srcpkgs/spectrwm/template

spectrwm: update to 3.6.0.

---

srcpkgs/extension-manager/patches/f3768fb0227c714d7ed0613a28142613aa4a9c6b.patch
srcpkgs/extension-manager/template

extension-manager: update to 0.5.1

---

srcpkgs/sbctl/template

sbctl: update

---

srcpkgs/fossil/template

fossil: update to 2.24.

---

srcpkgs/jupyterlab/template
srcpkgs/python3-ipython_ipykernel/patches/pytest8.patch
srcpkgs/python3-ipython_ipykernel/template
srcpkgs/python3-jupyter_client/template
srcpkgs/python3-jupyter_ipywidgets/patches/pytest8.patch
srcpkgs/python3-jupyter_ipywidgets/template
srcpkgs/python3-jupyter_notebook/template
srcpkgs/python3-jupyter_server/template
srcpkgs/python3-jupyter_widgetsnbextension/template
srcpkgs/python3-jupyterlab_server/template
srcpkgs/python3-nbclassic/patches/fix-warning.patch
srcpkgs/python3-nbclassic/template

Jupyter and jupyterlab updates
- **python3-jupyter_client: update to 8.6.2.**
- **python3-ipython_ipykernel: update to 6.29.5.**
- **python3-jupyter_server: update to 2.14.2.**
- **python3-jupyterlab_server: update to 2.27.3.**
- **jupyterlab: update to 4.2.4.**
- **python3-nbclassic: update to 1.1.0.**
- **python3-jupyter_notebook: update to 7.2.1.**
- **python3-jupyter_widgetsnbextension: update to 4.0.11.**
- **python3-jupyter_ipywidgets: update to 8.1.3.**

jupyter update

---

srcpkgs/opentyrian/template

opentyrian: update to 2.1.20221123, adopt

---

srcpkgs/eza/template

eza: update to 0.19.0

---

srcpkgs/libnvidia-container/patches/nogit.patch
srcpkgs/libnvidia-container/template
srcpkgs/nvidia-container-toolkit/template
srcpkgs/nvidia/template

nvidia-container-toolkit: update to 1.16.1.

---

srcpkgs/cargo-bootstrap/template
srcpkgs/rust-bootstrap/template
srcpkgs/rust/template

rust: update to 1.80.1

---

srcpkgs/loki/template

loki: update to 3.1.1.

---

srcpkgs/vaultwarden-web/template

vaultwarden-web: update to 2024.6.2b.

---

srcpkgs/clojure/template

clojure: update to 1.11.4.1474.

---

srcpkgs/clojure-lsp/template

clojure-lsp: update to 2024.08.03.

---

srcpkgs/python3-Faker/template

python3-Faker: update to 26.2.0.

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2024.08.05.

---

common/shlibs
srcpkgs/armadillo/template
srcpkgs/libgdal/template

armadillo: update to 14.0.2

---

srcpkgs/terraform-ls/template

terraform-ls: update to 0.34.2.

---

srcpkgs/limine/template

limine: update to 8.0.3.

---

srcpkgs/python3-rapidfuzz/template

python3-rapidfuzz: update to 3.9.6

---

srcpkgs/DSView/template

DSView: update to 1.3.2.

---

srcpkgs/php8.2/patches/ac_fn_c_try_run_cross.patch
srcpkgs/php8.2/patches/php-cross-config.patch
srcpkgs/php8.2/template
srcpkgs/php8.3/patches/ac_fn_c_try_run_cross.patch
srcpkgs/php8.3/patches/php-cross-config.patch
srcpkgs/php8.3/template

Use `qemu-user-static` to run the test executables built to probe `gd` for which formats it supports.
fixes https://github.com/void-linux/void-packages/issues/51237

php8.[23]: update and fix gd image support on cross builds

---

srcpkgs/tellico/template

tellico: update to 3.5.5.

---

srcpkgs/fend/template

fend: update to 1.5.1

---

srcpkgs/sqsh-tools/template

sqsh-tools: add missing pkg-config

---

srcpkgs/i2pd/template

i2pd: update to v2.53.1

---

Manual.md

Manual.md: Fix critical flaw in documentation

---

srcpkgs/amfora/template

amfora: update to 1.10.0

---

srcpkgs/pnpm/template

pnpm: update to 9.7.0.

---

srcpkgs/ruff/template

ruff: update to 0.5.7.

---

srcpkgs/lua-language-server/template

lua-language-server: update to 3.10.3.

---

srcpkgs/mold/template

mold: update to 2.33.0

---

srcpkgs/font-sarasa-gothic/template

font-sarasa-gothic: update to 1.0.18.

---

srcpkgs/vaultwarden/template

vaultwarden: update to 1.32.0.

---

srcpkgs/minetest/template

minetest: update to 5.9.0.

---

srcpkgs/remind/template

remind: update to 05.00.02.

---

srcpkgs/gns3-gui/template
srcpkgs/gns3-server/template

GNS3 update to 2.2.49

---

srcpkgs/lc0/template

lc0: update to 0.31.1

---

srcpkgs/instaloader/template

instaloader: update to 4.13.

---

srcpkgs/bacula-common/template

bacula-common: update to 13.0.3.

---

srcpkgs/7zip/template

7zip: update to 24.08.

---

srcpkgs/gitoxide/template

gitoxide: update to 0.37.0

---

srcpkgs/rio/template

rio: update to 0.1.6

---

srcpkgs/dufs/template

New package: dufs-0.41.0

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.19.1.

---

srcpkgs/UxPlay/template

UxPlay: update to 1.69.

---

srcpkgs/discord/template

discord: update to 0.0.64

---

srcpkgs/chirp/template

chirp: update to 20240807

---

srcpkgs/ijq/template

ijq: update to 1.1.1.

---

srcpkgs/ast-grep/template

ast-grep: update to 0.26.1.

---

srcpkgs/scrcpy/template

- **scrcpy: update to 2.6.1.**

scrcpy 2.6.1

---

srcpkgs/ansible-core/template

ansible-core: update to 2.17.3

---

srcpkgs/d2/template

d2: update to 0.6.6.

---

srcpkgs/zola/template

zola: update to 0.19.2

---

srcpkgs/rclone/template

- i686
- x86_64
- armv6l
@r-ricci

rclone: update to 1.67.0

---

srcpkgs/bandwhich/template

bandwhich: update to 0.23.0

---

srcpkgs/shfmt/template

shfmt: update to 3.9.0.

---

srcpkgs/mise/template

mise: update to 2024.8.6.

---

srcpkgs/praat/template

praat: update to 6.4.17

---

srcpkgs/limine/template

limine: update to 8.0.5.

---

common/build-style/meson.sh
common/environment/build-style/meson.sh

common/build-style/meson: use meson test/install instead of ninja

---

srcpkgs/linux-firmware/template

linux-firmware: update to 20240811.

---

srcpkgs/xfburn/template

xfburn: update to 0.7.2, adopt

---

srcpkgs/opera/template

opera: update to 112.0.5197.53.

---

srcpkgs/rssguard/template

rssguard: update to 4.7.3.

---

srcpkgs/mtpaint/template

mtpaint: update to 3.50.10.

---

srcpkgs/font-sarasa-gothic/template

font-sarasa-gothic: update to 1.0.19.

---

srcpkgs/godot/template

godot: update to 4.3.

---

srcpkgs/sqsh-tools/template

- **sqsh-tools: update to 1.5.1.**

sqsh tools 1.5.1

---

srcpkgs/github-cli/template

github-cli: update to 2.55.0

---

srcpkgs/pan/template

- I built this PR locally for these architectures: 
armv7l
armv6l
armv6l-musl

pan: update to 0.160.

---

srcpkgs/kak-lsp/template

kak-lsp: update to 17.1.2, adopt package.

---

srcpkgs/mise/template

mise: update to 2024.8.12.

---

srcpkgs/zoom/template

zoom: update to 6.1.10.1400

---

srcpkgs/dbeaver/template

dbeaver: update to 24.1.5.

---

srcpkgs/rio/template

rio: update to 0.1.8

---

srcpkgs/godot/files/godot.desktop
srcpkgs/godot/template

Removing desktop file as per #49164 .

godot: remove desktop file.

---

srcpkgs/qlog/template

New package: qlog-0.37.2

---

srcpkgs/jd/template

jd: update to 1.9.1.

---

srcpkgs/ruff/template

ruff: update to 0.6.1.

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2024.08.19.

---

srcpkgs/steamguard-cli/template

steamguard-cli: update to 0.14.2

---

srcpkgs/xfburn/template

xfburn: add changelog

---

srcpkgs/discord/template

discord: update to 0.0.65

---

srcpkgs/fd/template

fd: update to 10.2.0, adopt

---

srcpkgs/git-cliff/template

git-cliff: update to 2.5.0

---

srcpkgs/NetworkManager/template

NetworkManager: update to 1.48.8

---

srcpkgs/pipe-viewer/template

pipe-viewer: update to 0.5.3.

---

srcpkgs/intellij-idea-community-edition/template

intellij-idea-community-edition: update to 2024.2.0.2.

---

srcpkgs/CopyQ/template

CopyQ: update to 9.0.0.

---

srcpkgs/volta/template

volta: update to 2.0.1

---

srcpkgs/wine/template

wine: update to 9.16

---

srcpkgs/sheldon/template

sheldon: update to 0.8.0

---

srcpkgs/font-sarasa-gothic/template

font-sarasa-gothic: update to 1.0.20.

---

srcpkgs/gendesk/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

gendesk: update to 1.0.10.

---

srcpkgs/chroot-gawk/patches/fix-str2wstr.patch
srcpkgs/chroot-gawk/template
srcpkgs/gawk/patches/fix-str2wstr.patch
srcpkgs/gawk/template

gawk: update to 5.3.0

---

srcpkgs/glow/template

glow: update to 2.0.0

---

srcpkgs/rofimoji/template

rofimoji: update to 6.4.0

---

srcpkgs/rio/template

rio: update to 0.1.10

---

srcpkgs/RubyMine/template

rubymine: update to 2024.2.0.1

---

srcpkgs/discord/template

discord: update to 0.0.66

---

srcpkgs/zfs/template

zfs: update to 2.2.5.

---

srcpkgs/eza/template

eza: update to 0.19.1

---

srcpkgs/furnace/template

furnace: update to 0.6.7

---

srcpkgs/yazi/template

yazi: update to 0.3.2.

---

srcpkgs/fwupd/template

fwupd: update to 1.9.24.

---

srcpkgs/nextcloud-client/template

nextcloud-client: update to 3.13.3

---

srcpkgs/nnn/template

nnn: update to 5.0.

---

srcpkgs/python3-term-image/template
srcpkgs/toot/template

 toot: update to 0.44.1. 

---

srcpkgs/cpufetch/template

- aarch64
- i686
- x86_64-musl

cpufetch: update to 1.06

---

srcpkgs/pnpm/template

pnpm: update to 9.9.0.

---

srcpkgs/mercurial/template

mercurial: update to 6.8.1.

---

srcpkgs/python3-pulsectl/template

python3-pulsectl: update to 24.8.0.

---

srcpkgs/python3-pulsectl-asyncio/template

python3-pulsectl-asyncio: update to 1.2.0.

---

srcpkgs/python3-pwntools/template

python3-pwntools: update to 4.13.0.

---

srcpkgs/golangci-lint/template

golangci-lint: update to 1.60.3

---

srcpkgs/yaydl/template

yaydl: update to 0.15.4

---

srcpkgs/geckodriver/template

geckodriver: update to 0.35.0

---

srcpkgs/nushell/template

nushell: update to 0.97.1

---

srcpkgs/treefmt/template

treefmt: update to 2.0.5.

---

srcpkgs/osv-scanner/template

osv-scanner: update to 1.8.4.

---

srcpkgs/lua-language-server/template

lua-language-server: update to 3.10.5.

---

srcpkgs/swayimg/template

swayimg: update to 3.2.

---

srcpkgs/benchmark/template

benchmark: update to 1.9.0.

---

srcpkgs/pipewire/template

pipewire: update to 1.2.3

---

srcpkgs/NetworkManager/template

NetworkManager: update to 1.48.10

---

srcpkgs/tml/template

tml: update to 0.7.0

---

srcpkgs/fbpdf/template
srcpkgs/mupdf/template
srcpkgs/mupdf/update
srcpkgs/sioyek/template
srcpkgs/zathura-pdf-mupdf/template

mupdf: update to 1.24.9; revbump dependents

---

srcpkgs/hyperrogue/template

hyperrogue: update to 13.0t

---

srcpkgs/edk2-ovmf/template

edk2-ovmf: update to 202408.

---

srcpkgs/trurl/template

trurl: update to 0.15.

---

srcpkgs/limine/template

limine: update to 8.0.7.

---

srcpkgs/discord/template

discord: update to 0.0.67

---

srcpkgs/vhs/template

vhs: update to 0.8.0

---

srcpkgs/eza/template

eza: update to 0.19.2

---

srcpkgs/halloy/template

halloy: update to 2024.11

---

srcpkgs/dufs/template

dufs: update to 0.42.0

---

srcpkgs/hurl/template

hurl: update to 5.0.1.

---

srcpkgs/slack-desktop/template

slack-desktop: update to 4.39.95

---

srcpkgs/rawtherapee/template

rawtherapee: update to 5.11.

---

srcpkgs/schismtracker/template

schismtracker: update to 20240809

---

srcpkgs/keybase-desktop/template

keybase-desktop: update to 6.4.0.

---

srcpkgs/fuzzel/patches/fix-border-radius.patch
srcpkgs/fuzzel/template

fuzzel: update to 1.11.0

---

srcpkgs/openjdk11/patches/system-public-suffix.patch
srcpkgs/openjdk11/template
srcpkgs/openjdk17/patches/system-public-suffix.patch
srcpkgs/openjdk17/template
srcpkgs/openjdk21/patches/system-public-suffix.patch
srcpkgs/openjdk21/template

Openjdk use system public suffix

---

srcpkgs/github-cli/template

github-cli: update to 2.56.0

---

srcpkgs/font-iosevka/template

font-iosevka: update to 31.6.1.

---

common/shlibs
srcpkgs/bcg729/template
srcpkgs/bctoolbox/template
srcpkgs/belle-sip/template
srcpkgs/bzrtp/template
srcpkgs/dislocker/patches/cross.patch
srcpkgs/dislocker/patches/mbedtls3.patch
srcpkgs/dislocker/template
srcpkgs/dolphin-emu/template
srcpkgs/godot/template
srcpkgs/hiawatha/template
srcpkgs/imhex/template
srcpkgs/librist/template
srcpkgs/mbedtls/template
srcpkgs/mbedtls2-devel
srcpkgs/mbedtls2/template
srcpkgs/mediastreamer/template
srcpkgs/monkey/template
srcpkgs/obs/template
srcpkgs/openrgb/template
srcpkgs/openvpn/template
srcpkgs/retroarch/patches/mbedtls3.patch
srcpkgs/retroarch/template
srcpkgs/rvault/template
srcpkgs/shadowsocks-libev/template
srcpkgs/tpm2-tss/template

mbedtls: update to 3.6.0, new package: mbedtls2-2.28.8

---

srcpkgs/rio/patches/fix-cross.patch
srcpkgs/rio/template

rio: update to 0.1.12

---

srcpkgs/corectrl/template

corectrl: update to 1.4.1

---

srcpkgs/chafa/template

chafa: update to 1.14.4

---

srcpkgs/discord/template

discord: update to 0.0.68

---

srcpkgs/kdiff3/template

kdiff3: update to 1.11.3

---

srcpkgs/gc/template

gc: update to 8.2.8

---

srcpkgs/ruff/template

ruff: update to 0.6.4.

---

srcpkgs/qsv/template

qsv: update to 0.133.1.

---

srcpkgs/vale/template

vale: update to 3.7.1.

---

srcpkgs/stockfish/template

stockfish: update to 17

---

srcpkgs/rr/template

rr: update to 5.8.0, adopt

---

common/build-style/go.sh
srcpkgs/NetAuth-localizer/template
srcpkgs/carapace/template
srcpkgs/chroma/template
srcpkgs/fscrypt/template
srcpkgs/fx/template
srcpkgs/gopass/template
srcpkgs/gops/template
srcpkgs/immortal/template
srcpkgs/incus/template
srcpkgs/jd/template
srcpkgs/lf/template
srcpkgs/minio/template
srcpkgs/mmark/template
srcpkgs/moar/template
srcpkgs/rclone/template
srcpkgs/revive/template
srcpkgs/sbctl/template
srcpkgs/shfmt/template
srcpkgs/superd/template
srcpkgs/uni/template
srcpkgs/xq/template
srcpkgs/xurls/template
srcpkgs/yq-go/template

common/build-style/go: add a default do_check function

---

srcpkgs/gromit-mpx/template

gromit-mpx: update to 1.7.0

---

srcpkgs/eza/template

eza: update to 0.19.3

---

srcpkgs/dbeaver/template

dbeaver: update to 24.2.0.

---

srcpkgs/cryptsetup/template

cryptsetup: update to 2.7.5

---

srcpkgs/zoxide/template

zoxide: update to 0.9.5

---

srcpkgs/rofimoji/template

rofimoji: update to 6.5.0

---

srcpkgs/fend/template

fend: update to 1.5.2

---

srcpkgs/zoom/template

zoom: update to 6.2.0.1855

---

srcpkgs/intel-ucode/template

intel-ucode: update to 20240910, adopt.

---

srcpkgs/github-cli/template

github-cli: update to 2.57.0

---

srcpkgs/trurl/template

trurl: update to 0.15.1.

---

srcpkgs/yaydl/patches/cargo-lock.patch
srcpkgs/yaydl/template

yaydl: update to 0.15.5

---

srcpkgs/clifm/template

- x86_64-musl
- aarch64
- armv7l

clifm: update to 1.20.

---

srcpkgs/minetest/template

minetest: update to 5.9.1.

---

common/build-style/go.sh

common/build-style/go.sh: support $make_check_pre

---

.github/workflows/build.yaml

fix PATH in CI

---

srcpkgs/SweetHome3D/template

SweetHome3D: update to 7.5.

---

srcpkgs/gradle/template

gradle: update to 8.10.1.

---

srcpkgs/Tuba/template

Tuba: update to 0.8.4.

---

srcpkgs/gopls/template

gopls: update to 0.16.2.

---

srcpkgs/golangci-lint/template

golangci-lint: update to 1.61.0

---

srcpkgs/crun/template

crun: update to 1.17.

---

srcpkgs/inxi/template
srcpkgs/inxi/update

inxi: update to 3.3.36.1.

---

srcpkgs/n/template

n: update to 10.0.0

---

srcpkgs/mkvtoolnix/template

mkvtoolnix: update to 87.0

---

srcpkgs/schismtracker/template

schismtracker: update to 20240909

---

srcpkgs/duckdb/template

duckdb: update to 1.1.0.

---

srcpkgs/lazygit/template

lazygit: update to 0.44.0.

---

srcpkgs/OpenLP/template
srcpkgs/pyotherside/template
srcpkgs/python3-Flask-Cors/template
srcpkgs/python3-QtAwesome/template

OpenLP: update to 3.1.3.

---

srcpkgs/OpenRCT2/template

OpenRCT2: update to 0.4.14.

---

srcpkgs/intellij-idea-community-edition/template

intellij-idea-community-edition: update to 2024.2.1.

---

srcpkgs/cargo-modules/template

cargo-modules: update to 0.17.0.

---

srcpkgs/m17n-db/template

- I tested the changes in this PR: **NO** (have no setup to really test it)
- i686
- x86_64-musl

m17n-db: update to 1.8.7

---

srcpkgs/gallery-dl/template

gallery-dl: update to 1.27.4

---

srcpkgs/havoc/template

- I built this PR locally for my native architecture, musl-x86_64
- armv6l

havoc: update to 0.6.0

---

srcpkgs/carapace/template

carapace: update to 1.0.6.

---

srcpkgs/autorestic/template

autorestic: update to 1.8.3

---

srcpkgs/yewtube/template

yewtube: update to 2.12.0.

---

srcpkgs/ansible-core/template

ansible-core: update to 2.17.4

---

srcpkgs/perl-CryptX/template

perl-CryptX: update to 0.081

---

srcpkgs/python3-pillow_heif/template

python3-pillow_heif: update to 0.18.0

---

srcpkgs/pyradio/template

pyradio: update to 0.9.3.11

---

srcpkgs/instaloader/template

instaloader: update to 4.13.1.

---

srcpkgs/synapse/template

synapse: update to 1.114.0.

---

srcpkgs/python3-apprise/template

python3-apprise: update to 1.9.0.

---

srcpkgs/nghttp2/template

nghttp2: update to 1.63.0.

---

srcpkgs/pycharm-community/update

pycharm-community: ignore win releases

---

srcpkgs/python3-rapidfuzz/template

python3-rapidfuzz: update to 3.9.7

---

srcpkgs/i3status/template

i3status: update to 2.15, adopt.

---

srcpkgs/mise/template

mise: update to 2024.9.0.

---

srcpkgs/restic/template

restic: update to 0.17.1.

---

srcpkgs/eza/template

eza: update to 0.19.4

---

srcpkgs/halloy/template

halloy: update to 2024.12

---

srcpkgs/curl/template

curl: update to 8.10.1

---

srcpkgs/zfs/template

Test on x86_64 / glibc / Linux 6.10.7 / ZFSBootMenu.

zfs: update to 2.2.6.

---

srcpkgs/zoxide/template

zoxide: update to 0.9.6

---

srcpkgs/limine/template

limine: update to 8.0.13.

---

srcpkgs/ntpd-rs/files/ntpd-rs-metrics/run
srcpkgs/ntpd-rs/template

ntpd-rs: update to 1.3.0

---

srcpkgs/ansible/template

ansible: update to 10.4.0

---

srcpkgs/go-md2man/template

go-md2man: update to 2.0.5.

---

srcpkgs/android-studio/template

android-studio: update to 2024.1.2.12.

---

srcpkgs/synapse/template

synapse: update to 1.115.0.

---

srcpkgs/lua-language-server/template

lua-language-server: update to 3.10.6.

---

srcpkgs/ruff/template

ruff: update to 0.6.5.

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.25.0.

---

srcpkgs/tryton/template

tryton: update to 7.2.6

---

srcpkgs/cloudflared/template

- I built this PR locally for my native architecture, aarch64-libc

cloudflared: update to version 2024.9.1

---

srcpkgs/croc/template

croc: update to 10.0.12.

---

srcpkgs/engrampa/template

engrampa: update to 1.28.2.

---

srcpkgs/borgmatic/template
srcpkgs/python3-flexmock/template

borgmatic: update to 1.8.14.

---

srcpkgs/pylint/template

pylint: update to 3.2.7

---

srcpkgs/PhpStorm/template

phpstorm: update to 2024.2.1

---

srcpkgs/vaultwarden-web/template

vaultwarden-web: update to 2024.6.2c.

---

srcpkgs/WebStorm/template

webstorm: update to 2024.2.1

---

srcpkgs/s/template

s: update to 0.7.1.

---

srcpkgs/python3-qtile-extras/template
srcpkgs/qtile/template

- I tested the changes in this PR: **YES** - except from qtile-wayland

qtile: update to 0.28.1 and python3-qtile-extras: update to 0.28.1

---

srcpkgs/python3-scikit-build/template

python3-scikit-build: update to 0.18.1

---

srcpkgs/wf-shell/template

wf-shell: update to 0.8.1

---

srcpkgs/qtractor/template

qtractor: update to 1.2.0

---

srcpkgs/qmidiarp/patches/cross.patch
srcpkgs/qmidiarp/template

qmidiarp: update to 0.7.1

---

srcpkgs/atlantis/template

atlantis: update to 0.29.0.

---

srcpkgs/opentofu/template

opentofu: update to 1.8.1.

---

srcpkgs/arti/template

arti: update to 1.2.6.

---

srcpkgs/dosbox-staging/template

dosbox-staging: update to 0.81.2

---

srcpkgs/json-glib/template

json-glib: update to 1.10.0.

---

srcpkgs/winegui/template

winegui: update to 2.6.1

---

srcpkgs/ktouch/template

ktouch: update to 24.08.1.

---

srcpkgs/wlroots0.18/template

wlroots0.18: update to 0.18.1

---

srcpkgs/mepo/template

- I built this PR locally for the following non-native architectures: armv7l-libc, armv6l-musl

New package: mepo-1.3.3.

---

srcpkgs/git-cliff/template

git-cliff: update to 2.6.0

---

srcpkgs/nvidia/template

Unfortunately, this does not seem to fix the current issues on linux6.10.

nvidia: update to 550.120.

---

srcpkgs/cargo-about/template

cargo-about: update to 0.6.4.

---

srcpkgs/lazygit/template

lazygit: update to 0.44.1.

---

srcpkgs/got/template

a very late update :(
- I built this PR locally for my native architecture, (amd64-musl)

got: update to 0.103

---

srcpkgs/font-sarasa-gothic/template

font-sarasa-gothic: update to 1.0.21.

---

srcpkgs/rclone/template

rclone: update to 1.68.0.

---

srcpkgs/strace/template

strace: update to 6.11.

---

srcpkgs/ast-grep/template

ast-grep: update to 0.27.1.

---

srcpkgs/osv-scanner/template

osv-scanner: update to 1.8.5.

---

srcpkgs/glab/template

glab: update to 1.46.1.

---

srcpkgs/pazi/patches/fix-cargo-lock.patch
srcpkgs/pazi/template

pazi: update to 0.5.0

---

srcpkgs/monolith/template

monolith: update to 2.8.3

---

srcpkgs/comrak/template

comrak: update to 0.28.0

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2024.09.16.

---

srcpkgs/lms/template

lms: update to 3.58.0.

---

srcpkgs/YACReader/template

YACReader: update to 9.14.2.

---

srcpkgs/qgis/template

qgis: update to 3.38.3.

---

srcpkgs/vpn-ws/template

vpn-ws: fix description

---

srcpkgs/intellij-idea-community-edition/template

intellij-idea-community-edition: update to 2024.2.2.

---

srcpkgs/discord/template

discord: update to 0.0.69

---

srcpkgs/dbeaver/template

dbeaver: update to 24.2.1.

---

srcpkgs/bash/template
srcpkgs/chroot-bash/template

bash: update to 5.2.32

---

srcpkgs/nano/template

nano: update to 8.2

---

srcpkgs/mise/template

mise: update to 2024.9.7.

---

srcpkgs/spotify/template

spotify: update to 1.2.45.

---

srcpkgs/rio/template

rio: update to 0.1.16

---

srcpkgs/eza/template

eza: update to 0.20.0

---

srcpkgs/python3-jaraco.classes/template
srcpkgs/python3-jaraco.collections/patches/random.patch
srcpkgs/python3-jaraco.collections/template
srcpkgs/python3-jaraco.context/template
srcpkgs/python3-jaraco.stream/template
srcpkgs/python3-jaraco.text/template
srcpkgs/python3-portend/template

I bumped some orphaned packages
Needs https://github.com/void-linux/void-packages/pull/52316 first

Jaraco's python packages

---

README.md

Never having used distcc this took me a moment to figure out.
Might be worth mentioning to save others some headache. ;)

README.md: add updating distcc compiler whitelist

---

srcpkgs/ast-grep/template

ast-grep: update to 0.27.3.

---

srcpkgs/geeqie/patches/disable-ancillary-files-test.patch
srcpkgs/geeqie/template

geeqie: update to 2.5.

---

srcpkgs/uni/template

uni: update to 2.8.0.

---

common/shlibs
srcpkgs/libsfdo-devel
srcpkgs/libsfdo/template

New package: libsfdo-0.1.3

---

srcpkgs/git-cliff/template

git-cliff: update to 2.6.1

---

srcpkgs/bkt/template

bkt: update to 0.8.2

---

srcpkgs/ncdu2/template

ncdu2: update to 2.6

---

srcpkgs/ruff/template

ruff: update to 0.6.8.

---

srcpkgs/revive/template

revive: update to 1.4.0.

---

srcpkgs/gnome-desktop/template
srcpkgs/gnome-shell/template
srcpkgs/mutter/template

gnome-shell: update to 46.5.

---

srcpkgs/plantuml/template

- New distfiles location.
- Fixes PDF generation

plantuml: update to 1.2024.7.

---

srcpkgs/biblesync/template

biblesync: orphan.

---

srcpkgs/blueprint-compiler/template

blueprint-compiler: update to 0.14.0

---

srcpkgs/libadwaita/template

libadwaita: update to 1.6.0

---

srcpkgs/gnome-sudoku/template

gnome-sudoku: update to 47.0.

---

srcpkgs/logiops/template

logiops: update to 0.3.5.

---

srcpkgs/protontricks/template

protontricks: update to 1.12.0

---

srcpkgs/slack-desktop/template

slack-desktop: update to 4.40.128.

---

srcpkgs/dkms/template

dkms: update to 3.0.13.

---

srcpkgs/sakura/template

sakura: update to 3.8.8

---

srcpkgs/gum/template

gum: update to 0.14.5

---

srcpkgs/chicken/template

chicken: update to 5.4.0.

---

srcpkgs/python3-virtualenv/template

python3-virtualenv: update to 20.26.5.

---

srcpkgs/python3-platformdirs/template

python3-platformdirs: update to 4.3.6.

---

srcpkgs/skate/template

skate: update to 1.0.0

---

srcpkgs/mise/template

mise: update to 2024.9.13.

---

srcpkgs/discord/template

discord: update to 0.0.70

---

srcpkgs/github-cli/template

github-cli: update to 2.58.0

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2024.09.30.

---

srcpkgs/eza/template

eza: update to 0.20.1

---

srcpkgs/cargo-update/template

cargo-update: update to 15.0.0

---

srcpkgs/neovim/patches/cross-build.patch
srcpkgs/neovim/template

neovim: update to 0.10.2

---

srcpkgs/zf/template

New package: zf-0.10.0

---

srcpkgs/cpuid/template

- I tested the changes in this PR: **YES**|**briefly**

cpuid: update to 20240916.

---

srcpkgs/fend/template

fend: update to 1.5.3

---

srcpkgs/topgrade/template

topgrade: update to 16.0.0

---

srcpkgs/strawberry/template

strawberry: update to 1.1.3

---

srcpkgs/gtk4/template

gtk4: update to 4.16.3

---

srcpkgs/bandwhich/template

bandwhich: update to 0.23.1

---

srcpkgs/ROCm-SMI-devel
srcpkgs/ROCm-SMI/patches/cflags.patch
srcpkgs/ROCm-SMI/template
srcpkgs/ROCm-SMI/update

New package: ROCm-SMI-6.2.2

---

srcpkgs/eza/template

eza: update to 0.20.2

---

srcpkgs/python3-ropgadget/template

python3-ropgadget: add missing dep

---

srcpkgs/tealdeer/template

- I built this PR for these architectures (crossbuilds):
- x86_64-musl
- i686
- armv7l-musl
- armv7hf

tealdeer: update to 1.7.0

---

common/shlibs
srcpkgs/kmahjongg/template
srcpkgs/libkmahjongg-devel
srcpkgs/libkmahjongg/template

New package: kmahjongg-24.08.2

---

srcpkgs/picmi/template

New package: picmi-24.08.2

---

srcpkgs/bovo/template

New package: bovo-24.08.2

---

srcpkgs/gscreenshot/template

gscreenshot: update to 3.6.3.

---

srcpkgs/topgrade/template

topgrade: update to 16.0.1

---

srcpkgs/numbat/template

numbat: update to 1.14.0

---

srcpkgs/xh/template

xh: update to 0.23.0

---

srcpkgs/librsvg/template

librsvg: disable relocatable pkgconfig file

---

srcpkgs/hyperrogue/template

hyperrogue: update to 13.0v

---

srcpkgs/clifm/template

clifm: update to 1.21.

---

srcpkgs/slack-desktop/template
srcpkgs/slack-desktop/update

slack-desktop: update to 4.40.133, fix update file.

---

srcpkgs/Waybar/patches/fix-tray-icons.patch
srcpkgs/Waybar/template

Fixes missing tray icons in Waybar (Alexays/Waybar#3597) through a [patch](https://github.com/Alexays/Waybar/commit/0d02f6877d88551ea2be0cd151c1e6354e208b1c.patch).

Waybar: fix tray icons

---

srcpkgs/json-c/template

json-c: update to 0.18.

---

srcpkgs/mpv/template

- aarch64 \*
- x86_64-musl
- aarch64-musl \*

mpv: update to 0.39.0.

---

srcpkgs/intel-gmmlib/template
srcpkgs/intel-media-driver/template

Intel media driver 24.3.4

---

srcpkgs/zeek/template

zeek: update to 7.0.3.

---

common/shlibs
srcpkgs/libfm-qt5-devel
srcpkgs/libfm-qt5/template
srcpkgs/libqt5xdg-devel
srcpkgs/libqt5xdg/template
srcpkgs/lxqt-build-tools-qt5/template
srcpkgs/lxqt-qt5plugin/template

LXQt Qt5 Plugin

---

srcpkgs/font-sarasa-gothic/template

font-sarasa-gothic: update to 1.0.22.

---

common/build-style/meson.sh
srcpkgs/librsvg/template

common/build-style/meson.sh: disable relocatable pkgconfig

---

common/shlibs
srcpkgs/libcamera/template
srcpkgs/pipewire/template

pipewire, libcamera: update

---

srcpkgs/limine/template

limine: update to 8.1.2.

---

srcpkgs/librsvg/template
srcpkgs/swayimg/template

- armv6l-musl
Extra dependencies had to be added to fix `librsvg-2.0` not being found by `pkgconfig`.

swayimg: update to 3.3.

---

srcpkgs/xmag/template

- armv7l
- armv6l-musl
- aarch64-musl

xmag: update to 1.0.8

---

srcpkgs/dpp/template

dpp: update to 10.0.32.

---

srcpkgs/nss/template

nss: update to 3.105.

---

srcpkgs/github-cli/template

github-cli: update to 2.59.0

---

common/shlibs
srcpkgs/catgirl/template
srcpkgs/got/template
srcpkgs/libtls/template
srcpkgs/litterbox/template
srcpkgs/openntpd/template
srcpkgs/pounce/template
srcpkgs/sacc/template

libtls: update to 4.0.0.

---

srcpkgs/eza/template

eza: update to 0.20.3

---

srcpkgs/eza/template

eza: update to 0.20.4

---

common/shlibs
srcpkgs/linux-firmware/patches/no-whence.patch
srcpkgs/linux-firmware/template
srcpkgs/qtforkawesome/template
srcpkgs/syncthingtray/template
srcpkgs/tailscale/template
srcpkgs/typst/template
srcpkgs/uv/template

various updates

---

srcpkgs/libuv/template

libuv: update to 1.49.2

---

srcpkgs/libgit2-1.8/template

libgit2-1.8: update to 1.8.2

---

srcpkgs/PrismLauncher/template

PrismLauncher: update to 9.0

---

srcpkgs/qemu-user/template
srcpkgs/qemu/template

- **qemu-user: update to 9.1.1.**
- **qemu: update to 9.1.1.**

qemu: update to 9.1.1.

---

srcpkgs/python3-pillow_heif/template

python3-pillow_heif: update to 0.20.0

---

srcpkgs/python3-importlib_metadata/template

python3-importlib_metadata: update to 8.5.0.

---

srcpkgs/python3-Faker/template

python3-Faker: update to 30.6.0.

---

srcpkgs/comrak/template

comrak: update to 0.29.0

---

srcpkgs/gitoxide/template

gitoxide: update to 0.38.0

---

srcpkgs/nghttp2/template

nghttp2: update to 1.64.0.

---

srcpkgs/discord/template

discord: update to 0.0.72.

---

srcpkgs/github-cli/template

github-cli: update to 2.60.0

---

srcpkgs/eza/template

eza: update to 0.20.5

---

srcpkgs/gnome-authenticator/template

gnome-authenticator: update to 4.5.0.

---

srcpkgs/git-extras/template

git-extras: update to 7.3.0.

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.30.0.

---

srcpkgs/direnv/template

direnv: update to 2.35.0.

---

srcpkgs/mandrel/template

mandrel: update to 23.1.5.0.

---

srcpkgs/ast-grep/template

ast-grep: update to 0.28.0.

---

srcpkgs/libgit2-1.8/template

libgit2-1.8: update to 1.8.3

---

srcpkgs/poedit/template

poedit: update to 3.5.1.

---

srcpkgs/amberol/template

amberol: update to 2024.2

---

srcpkgs/swayimg/template

swayimg: update to 3.4.

---

srcpkgs/mate-notification-daemon/template

mate-notification-daemon: update to 1.28.1.

---

srcpkgs/mate-panel/template

mate-panel: update to 1.28.4.

---

srcpkgs/instaloader/template

instaloader: update to 4.13.2.

---

srcpkgs/neomutt/patches/disable-failing-test.patch
srcpkgs/neomutt/template

- x86_64-musl
- i686
Patch copied from alpine package.
@Vaelatern please take a look. I've also added pcre2 and zstd features to the update.

neomutt: update to 20241002.

---

.mailmap

mailmap: add myself

---

srcpkgs/sway/template

sway: update to 1.10

---

common/shlibs
srcpkgs/libblockdev/template
srcpkgs/libnvme/template
srcpkgs/nvme-cli/template

- x86_64-musl (build)
- aarch64 (cross build)

nvme-cli: update to 2.10.2, libnvme: update to 1.10

---

srcpkgs/xrefresh/template

- armv7l
- armv6l-musl
- aarch64-musl

xrefresh: update to 1.1.0

---

srcpkgs/xwallpaper/template

- armv7l
- armv6l-musl
- aarch64-musl

xwallpaper: update to 0.7.5

---

srcpkgs/MoarVM/template
srcpkgs/nqp/template
srcpkgs/rakudo/template

rakudo: update to 2024.10.

---

srcpkgs/factor/template

factor: update to 0.100.

---

srcpkgs/perl-Crypt-DES_EDE3/template

perl-Crypt-DES_EDE3: update to 0.03

---

srcpkgs/perl-CryptX/template

perl-CryptX: update to 0.084

---

srcpkgs/ruff/template

ruff: update to 0.7.0.

---

srcpkgs/chroot-util-linux/template
srcpkgs/util-linux-common/template
srcpkgs/util-linux/template

util-linux: update to 2.40.2.

---

srcpkgs/perl-rename/template

- I built this PR locally for my native architecture, (ARCH-LIBC) x86_64-glibc
- x86_64-musl
- (cross) aarch64-musl
- (cross) armv7l
- (cross) armv6l-musl

perl-rename: update to 1.14

---

srcpkgs/xq/INSTALL.msg
srcpkgs/xq/template

xq: update to 1.2.5, add INSTALL.msg

---

srcpkgs/cronie/template

cronie: Add missing config file

---

srcpkgs/codeberg-cli/template

codeberg-cli: update to 0.4.4

---

srcpkgs/halloy/template

halloy: update to 2024.14

---

srcpkgs/github-cli/template

github-cli: update to 2.60.1

---

srcpkgs/nvidia/template

nvidia: update to 550.127.05.

---

srcpkgs/bup/template

add missing dependencies
fixes #52763

bup: update to 0.33.4.

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2024.10.28.

---

srcpkgs/picom/patches/arm32-build-failures.patch
srcpkgs/picom/template

This *should* be the full changeset for that update, but I'm doing some extended testing since that update has been a bit chaotic (3rd patch release in two weeks), also it's not a pressing package to update.

picom: update to 12.3.

---

srcpkgs/black/template

black: update to 24.10.0.

---

srcpkgs/difftastic/template

difftastic: update to 0.61.0.

---

srcpkgs/crun/template

crun: update to 1.18.1.

---

srcpkgs/mercurial/template

mercurial: update to 6.8.2.

---

srcpkgs/libgit2-1.8/template

libgit2-1.8: update to 1.8.4

---

srcpkgs/python3-sympy/template

python3-sympy: update to 1.13.3.

---

srcpkgs/primesieve/template

primesieve: update to 12.5.

---

srcpkgs/python3-Faker/template

python3-Faker: update to 30.8.1.

---

common/shlibs
srcpkgs/snapper/patches/0001-disable-locale-tests.patch
srcpkgs/snapper/patches/fix-missing-include-musl.patch
srcpkgs/snapper/template

- I tested the changes in this PR: **YES** (I'm daily driving it and basic functionality works.)

snapper: update to 0.11.2.

---

srcpkgs/GraphicsMagick/template

GraphicsMagick: update to 1.3.45.

---

srcpkgs/python3-networkx/template

python3-networkx: update to 3.4.2.

---

srcpkgs/python3-cachetools/template
srcpkgs/python3-pyproject-api/template
srcpkgs/python3-time-machine/template
srcpkgs/tox/template

- **python3-cachetools: update to 5.5.0.**
- **python3-pyproject-api: update to 1.8.0.**
- **python3-time-machine: update to 2.16.0.**
- **tox: update to 4.23.2.**

tox: update to 4.23.2.

---

srcpkgs/Clipboard/template

Clipboard: update to 0.9.1.

---

srcpkgs/chirp/template

chirp: update to 20241025

---

srcpkgs/libbraiding/template

libbraiding: update to 1.3.

---

srcpkgs/cropgui/template

- I built this PR locally for my native architecture, (x86_&4-glibc)

cropgui: update to 0.9.

---

srcpkgs/intel-ucode/template

intel-ucode: update to 20241029.

---

srcpkgs/shfmt/template

shfmt: update to 3.10.0.

---

srcpkgs/kak-lsp/template

kak-lsp: update to 18.0.2.

---

srcpkgs/gtklock/template

gtklock: update to 4.0.0.

---

srcpkgs/python3-msgpack/template

python3-msgpack: update to 1.1.0.

---

srcpkgs/python3-regex/template

python3-regex: update to 2024.9.11.

---

srcpkgs/wego/template

wego: update to 2.3.

---

srcpkgs/mise/template

mise: update to 2024.10.13.

---

srcpkgs/tryton/template

tryton: update to 7.2.8

---

srcpkgs/swaysome/template

swaysome: update to 2.1.2.

---

srcpkgs/python3-rapidfuzz/template
srcpkgs/rapidfuzz-cpp/template

python3-rapidfuzz: update to 3.10.1

---

srcpkgs/radicale/template

radicale: update to 3.3.0, adopt.

---

srcpkgs/python3-Markdown/template

python3-Markdown: update to 3.6.

---

srcpkgs/python3-cups/template

python3-cups: update to 2.0.4.

---

srcpkgs/nicotine+/template

nicotine+: update to 3.3.6

---

srcpkgs/python3-chess/template

python3-chess: update to 1.11.1.

---

srcpkgs/SuiteSparse/template

SuiteSparse: update to 7.8.3.

---

srcpkgs/nim/template

nim: fix missing dist packages

---

srcpkgs/twitch-cli/template

twitch-cli: update to 1.1.24

---

srcpkgs/pyradio/template

pyradio: update to 0.9.3.11.1

---

srcpkgs/oh/template

- x86_64-glibc
- i686
@knusbaum could you please review the changes ??
And thanks for your time

oh: update to 0.8.3

---

srcpkgs/gnome-nibbles/template

- armv7l
- armv6l-musl
- aarch64-musl

gnome-nibbles: update to 4.1.0

---

srcpkgs/visidata/template

visidata: update to 3.1.1.

---

srcpkgs/ansible-core/template
srcpkgs/ansible/template

ansible: update to 10.5.0; ansible-core: update to 2.17.5.

---

srcpkgs/python3-qtile-extras/template
srcpkgs/qtile/template

- I tested the changes in this PR: **YES**, except for wayland.
- I built this PR locally for my native architecture,  x86-64-LIBC

qtile: update to 0.29.0 and python3-qtile-extras: update to 0.29.0

---

srcpkgs/yggdrasil/template

yggdrasil: update to 0.5.9.

---

srcpkgs/pmars/template

pmars: update to 0.9.4

---

srcpkgs/mkvtoolnix/template

mkvtoolnix: update to 88.0

---

srcpkgs/lc0/template

lc0: update to 0.31.2

---

srcpkgs/io.elementary.code/template

io.elementary.code: update to 7.3.0

---

srcpkgs/calibre/template

calibre: update to 7.20.0.

---

srcpkgs/dbeaver/patches/force-jdk17.patch
srcpkgs/dbeaver/template

dbeaver: update to 24.2.3.

---

srcpkgs/wps-office/template

wps-office: update to 11.1.0.11723.

---

srcpkgs/opera/template

opera: update to 114.0.5282.21.

---

srcpkgs/rssguard/template

rssguard: update to 4.7.4.

---

srcpkgs/roxterm/template

roxterm: update to 3.15.2.

---

srcpkgs/weston/template

weston: update to 14.0.0.

---

srcpkgs/tilda/template

tilda: update to 2.0.0

---

srcpkgs/bluefish/template

bluefish: update to 2.2.16

---

srcpkgs/gucharmap/template

gucharmap: update to 16.0.1

---

srcpkgs/lua-language-server/template

lua-language-server: update to 3.11.0.

---

srcpkgs/pnpm/template

pnpm: update to 9.12.1.

---

srcpkgs/qbittorrent/template

- x86_64-glibc
- i686
@ericonr could you please review the changes and thanks for your time

qbittorrent: update to 5.0.0

---

srcpkgs/lms/template

lms: update to 3.59.1.

---

srcpkgs/geomyidae/template

geomyidae: update to 0.96.

---

srcpkgs/qutebrowser/template

qutebrowser: update to 3.3.1.

---

srcpkgs/qtractor/template

qtractor: update to 1.3.0

---

srcpkgs/freeciv-qt6
srcpkgs/freeciv/template

- I built this PR locally for my native architecture, (x86-64-GLIBC)

freeciv: update to 3.1.3.

---

srcpkgs/vaultwarden/template

vaultwarden: update to 1.32.3.

---

srcpkgs/libadwaita/template

libadwaita: update to 1.6.1

---

srcpkgs/xonsh/template

- x86_64-glibc
- i686
@SolitudeSF could please review the changes??
And thanks for your time

xonsh: update to 0.18.3

---

srcpkgs/tlp/template

tlp: udpate to 1.7

---

srcpkgs/lagrange/template

lagrange: update to 1.18.3.

---

srcpkgs/sqlitebrowser/template

sqlitebrowser: update to 3.13.0.

---

srcpkgs/swirc/template

swirc: update to 3.5.0.

---

srcpkgs/gcompris-qt/template

gcompris-qt: update to 4.2

---

srcpkgs/cliphist/template

cliphist: update to 0.6.1.

---

srcpkgs/mobile-config-firefox/template

mobile-config-firefox: update to 4.3.2.

---

srcpkgs/betterlockscreen/patches/use-loginctl.patch
srcpkgs/betterlockscreen/template

- aarch64
- armv7l
- x86_64-musl
- i686

betterlockscreen: update to 4.4.0.

---

srcpkgs/eza/template

eza: update to 0.20.6

---

srcpkgs/font-sarasa-gothic/template

font-sarasa-gothic: update to 1.0.23.

---

srcpkgs/libcap/template

libcap: update to 2.71.

---

srcpkgs/libqalculate/template
srcpkgs/qalculate-gtk/template
srcpkgs/qalculate-qt/template

qalculate: update to 5.3.0

---

srcpkgs/duckdb/template

duckdb: update to 1.1.2.

---

srcpkgs/discord/template

discord: update to 0.0.73

---

srcpkgs/slack-desktop/template

slack-desktop: update to 4.41.96.

---

srcpkgs/limine/template

limine: update to 8.3.2.

---

srcpkgs/lua-language-server/template

lua-language-server: update to 3.12.0.

---

srcpkgs/curl/template

curl: update to 8.11.0

---

srcpkgs/google-chrome/template

google-chrome: update to 130.0.6723.116

google-chrome: update to 130.0.6723.116

---

srcpkgs/eza/template

eza: update to 0.20.7

---

srcpkgs/github-cli/template

github-cli: update to 2.61.0

---

srcpkgs/unibilium/template

unibilium: update to 2.1.2

---

srcpkgs/curl/patches/fix-netrc.patch
srcpkgs/curl/template

curl: add netrc fix

---

srcpkgs/curl/patches/fix-content-encoding.patch
srcpkgs/curl/template

curl: add content encoding fix

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2024.11.04.

---

srcpkgs/font-iosevka/template

- x86_64
<br/>
@josegpt could you please review the changes??
And thanks for your time!

font-iosevka: update to 32.0.1

---

srcpkgs/moar/template

- x86_64
<br/>
@DiegoMagdaleno could you please review the changes??
And thanks for your time!

moar: update to 1.28.2

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.32.0

---

srcpkgs/ruff/template

ruff: update to 0.7.2.

---

srcpkgs/ranger/template

ranger: update to 1.9.4

---

srcpkgs/kak-lsp/template

kak-lsp: update to 18.0.3.

---

srcpkgs/yamlfmt/template

yamlfmt: update to 0.14.0.

---

srcpkgs/lf/template

lf: update to r33.

---

srcpkgs/yabasic/template

(Tested some basic programs like fibonacci series and factorial)
- i686
- x86_64-glibc

yabasic: update to 2.90.4

---

srcpkgs/restic/template

restic: update to 0.17.3.

---

srcpkgs/matterbridge/files/matterbridge/run
srcpkgs/matterbridge/template

Tested on aarch64-musl by making a bridge between matrix and an API
gateway.

New package: matterbridge-1.26.0.

---

srcpkgs/python3-urwidgets/template
srcpkgs/toot/template

- **python3-urwidgets: update to 0.2.1.**
- **toot: update to 0.45.0.**

toot: update to 0.45.0.

---

srcpkgs/git-absorb/template

git-absorb: update to 0.6.16.

---

srcpkgs/ast-grep/template

ast-grep: update to 0.29.0.

---

srcpkgs/chezmoi/template

chezmoi: update to 2.54.0.

---

srcpkgs/cargo-auditable-bootstrap/template
srcpkgs/cargo-auditable/template

cargo-auditable: update to 0.6.5

---

srcpkgs/ircdog/template

ircdog: update to 0.5.5.

---

srcpkgs/micro/template

micro: update to 2.0.14.

---

srcpkgs/dufs/template

dufs: update to 0.43.0

---

srcpkgs/intel-ucode/template

intel-ucode: update to 20241112.

---

srcpkgs/hyperfine/template

hyperfine: update to 1.19.0

---

srcpkgs/ethtool/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l

ethtool: update to 6.11.

---

srcpkgs/zf/template

zf: update to 0.10.2

---

srcpkgs/codeberg-cli/template

codeberg-cli: update to 0.4.5

---

srcpkgs/vaultwarden/template

vaultwarden: update to 1.32.4.

---

srcpkgs/cantata/patches/migrate.patch
srcpkgs/cantata/template

cantata: update to 3.2.0.

---

srcpkgs/eza/template

eza: update to 0.20.8

---

srcpkgs/grype/template
srcpkgs/syft/template

syft: update to 1.16.0; grype: update to 0.84.0

---

srcpkgs/fcft/template

fcft: update to 3.1.9

---

srcpkgs/orc/template

orc: update to 0.4.40

---

srcpkgs/gst-libav/template
srcpkgs/gst-plugins-bad1/template
srcpkgs/gst-plugins-base1/template
srcpkgs/gst-plugins-good1/template
srcpkgs/gst-plugins-ugly1/template
srcpkgs/gst-rtsp-server/template
srcpkgs/gst1-editing-services/template
srcpkgs/gst1-python3/template
srcpkgs/gstreamer-vaapi/template
srcpkgs/gstreamer1/template

- Packages that I didn't installed therefore didn't tested:
- gst-rtsp-server
- gst1-editing-services
- gstreamer-vaapi
- gst1-python3
- x86_64

gstreamer1, gst{1,}-*: update to 1.24.9

---

srcpkgs/qsv/template

qsv: update to 0.138.0.

---

srcpkgs/backintime/template

backintime: update to 1.5.3

---

srcpkgs/cpuid/template

- x86_64
<br/>
@arete could you please review the changes??

cpuid: update to 20241023

---

srcpkgs/ffmpeg6/template

you never had a bread sandwich from petes ?
closes #52730

ffmpeg6: enable libharfbuzz, fontconfig and freetype. 

---

srcpkgs/fuse-9pfs/template

fuse-9pfs: update to 0.4.

---

srcpkgs/OpenLP/template

OpenLP: update to 3.1.4.

---

srcpkgs/OpenRCT2/template

OpenRCT2: update to 0.4.16.

---

srcpkgs/sqlitebrowser/template

sqlitebrowser: update to 3.13.1.

---

srcpkgs/peru/template

peru: update to 1.3.2.

---

srcpkgs/swaylock/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

swaylock: update to 1.8.0.

---

srcpkgs/cmus/template

cmus: update to 2.12.0.

---

srcpkgs/github-cli/template

github-cli: update to 2.62.0

---

srcpkgs/pre-commit/template

pre-commit: update to 4.0.1.

---

srcpkgs/python3-virtualenv/template

python3-virtualenv: update to 20.27.1.

---

srcpkgs/python3-plotly/template

- Tested against https://github.com/Vinfall/usage-direct-viz/blob/main/visualize.py#L34-L75

python3-plotly: update to 5.24.1.

---

srcpkgs/docker-buildx/patches/fix-tests.patch
srcpkgs/docker-buildx/template

docker-buildx: update to 0.18.0.

---

srcpkgs/ascii/template

ascii: update to 3.30.

---

srcpkgs/n/template

n: update to 10.1.0

---

srcpkgs/bovo/template

bovo: update to 24.08.3

---

srcpkgs/citations/template

citations: update to 0.7.0

---

srcpkgs/czkawka/template

czkawka: update to 8.0.0

---

srcpkgs/weston/template

weston: update to 14.0.1.

---

srcpkgs/nushell/template

nushell: update to 0.100.0

---

srcpkgs/borgmatic/template

borgmatic: update to 1.9.1.

---

srcpkgs/xonsh/template

- x86_64
<br />
@SolitudeSF could you please review the changes??
And thanks for your time!

xonsh: update to 0.18.4

---

srcpkgs/python3-dnsrecon/template

python3-dnsrecon: update to 1.3.1.

---

srcpkgs/python3-Faker/template

python3-Faker: update to 33.0.0.

---

srcpkgs/qtractor/template

qtractor: update to 1.4.0

---

srcpkgs/slack-desktop/template

slack-desktop: update to 4.41.97.
