srcpkgs/incus/files/incus-user/check
srcpkgs/incus/template

The line `exec 2>&1` in the beginning of `incus-user/check` would stop the execution of the script right there, and would return a non-zero value, making `sv restart incus-user` show a timeout (after 7 seconds), like this:
```
-bash-5.2# sv start incus-user
timeout: run: incus-user: (pid 9181) 7s
```
Placing `2>&1` at the right point, the execution of `sv restart incus-user` is like this:
```
-bash-5.2# sv restart incus-user
ok: run: incus-user: (pid 9370) 0s
```
...in less than a second.

incus: fix check script

---

srcpkgs/leftwm/patches/fix_32bit_builds.patch
srcpkgs/leftwm/template

- armv7l
There is already a PR #48571 open since months to update leftwm to the same version but I prefered to open a new one based on a more recent version of the repository.
2 issues encountered during the build
- as in the original PR, leftwm does not compile on 32 bit architecture due to a small bug in the code. The patch `fix_32bit_builds.patch` fixes that based on upstream commit
- new issue, one of the leftwm dependencies (time crate) does not compile in the version defined in the project using rust 1.80. The second patch `cargo_update_time.patch` fixes this and I also opened an …

leftwm: update to 0.5.1.

---

srcpkgs/tiff/template

tiff: fix cycle by disabling webp support by default

---

srcpkgs/libwebp/template

makedepends are only used for the tools, not for the library

libwebp: fix -devel depends

---

srcpkgs/docker-buildx/template

docker-buildx: update to 0.16.2.

---

srcpkgs/librespeed-cli/template

- I built this PR locally for my native architecture, (x86_64-musll)
- aarch64-musl
- armv7l
- armv6l-musl

New package: librespeed-cli-1.0.10

---

srcpkgs/ffmpeg/template

- I built this PR locally for my native architecture: x86_64-musl
- x86_64
- i686
- i686-musl
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl

ffmpeg: strip static libs fix for i686-musl

---

srcpkgs/magic-wormhole/template

---
Fixes breakage (ImportError crash) caused by the recent `python3-attrs` update (see magic-wormhole/magic-wormhole#492).
Cc: @travankor as the listed maintainer
Cc: @ahesford as the commiter of the attrs update

magic-wormhole: update to 0.15.0, add changelog

---

srcpkgs/flatpak/template

This add missing `libxml2-devel` an `libXau-devel` dependencies to `flatpak-devel` to satisfy pkg-config

flatpak: add missing -devel packages to depends

---

srcpkgs/skanpage/template

The problem: skanpage won't launch without explicitly installing kquickimageeditor. In terminal, skanpage shows the following error and the window never shows up 
`ATTENTION: default value of option vblank_mode overridden by environment.
QQmlApplicationEngine failed to load component
qrc:/qml/MainWindow.qml:361:26: Type ContentView unavailable
qrc:/qml/ContentView.qml:67:13: Type DocumentPage unavailable
qrc:/qml/DocumentPage.qml:14:1: module "org.kde.kquickimageeditor" is not installed` 
For context, you might want to see:
- https://github.com/KDE/skanpage/blob/master/.kde-ci.yml
- https://bugzilla.redhat.com/show_bug.cgi?id=2241499
- …

skanpage: add kquickimageeditor to depends

---

srcpkgs/glibc/update

this way `update-check` works again

glibc: fix update check

---

srcpkgs/fdupes/template

- I built this PR locally for my native architecture: **x86_64-musl**
- x86_64
- aarch64
- aarch64-musl
- i686
- i686-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
- armv5te
- armv5te-musl

fdupes: update to 2.3.2

---

srcpkgs/smpeg/template

- I built this PR locally for these architectures (all crossbuilds):
- aarch64{,-musl}
- armv6l{,-musl}
---
the oregonstate.edu ftp server does not contain a vectorlinux mirror anymore, so the distfile link is broken.
while other mirrors of this exact file exist (for example at [nluug.nl](https://ftp.nluug.nl/os/Linux/distr/vectorlinux/VL64-7.0/source/sourceVL/smpeg/0.4.5/src) and [princeton.edu](https://mirror.math.princeton.edu/pub/vectorlinux/VL64-7.0/source/sourceVL/smpeg/0.4.5/src/)), it seems that icculus have moved the project from svn to github in late 2021, so i'd suggest just taking the sources from there directly.
the hash differs, but the sources are effectively …

smpeg: update distfile url

---

srcpkgs/cpuset/template

- upstream has migrated to new repo / ownership; updated accordingly
- removed dependency on python3-future per upstream's changes
- should fix failing python3 check in #46170
- x86_64-musl (xbuild)
- i686 (xbuild)
- armv6l (xbuild)

cpuset: update to 1.6.2 for python3.12

---

srcpkgs/cargo-deny/template

cargo-deny: update to 0.16.1.

---

srcpkgs/carapace/template

carapace: update to 1.0.5.

---

srcpkgs/cropgui/template

The current version has this bug, and this PR solves it:
```
/usr/bin/cropgui:33: DeprecationWarning: 'imghdr' is deprecated and slated for removal in Python 3.13
import imghdr
File "/usr/bin/cropgui", line 223, in <module>
wa = display.get_primary_monitor().get_workarea()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_workarea'
/usr/bin/cropgui:45: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "parent, flags, message_type, buttons, message_format" or use a class specific constructor. See: …
```

cropgui: update to 0.8, adopt.

---

common/shlibs
srcpkgs/ffmpeg/template
srcpkgs/ffmpeg6/template
srcpkgs/handbrake/template
srcpkgs/svt-av1/template

- cross builds: **i686**, **aarch64-musl**
After 2.1.0 they removed the decoder library. I guess most just use other libs https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/2182
Out of date, also fixes 32bit build, remove svt use flag in ffmpeg, and handbrake 32bit builds with it for https://github.com/void-linux/void-packages/pull/51706

svt-av1: 2.1.2

---

srcpkgs/caddy/template

- I built this PR locally for my native architecture, aarch64 as well as aarch64-musl

caddy: update to 2.8.4.

---

srcpkgs/wireless-regdb/template

cc @sgn I removed the `vsed`, not sure I understood why it's needed. Can you please review?

wireless-regdb: update to 2024.07.04

---

srcpkgs/wine/template

wine: make wow64 a buildoption

---

srcpkgs/hexchat/patches/url-percent-escape.patch
srcpkgs/hexchat/template

hexchat: fix escaping of % in uris

---

srcpkgs/terragrunt/template

As we have `opentofu` merged, we can remove `terraform` dependency from `terragrunt`. `terragrunt` can work with both `opentofu` and `terraform`, it even defaults to `opentofu` (at least on my machine).
@thypon, what do you think?

terragrunt: removed terraform dependency

---

srcpkgs/python3-yattag/template

python3-yattag: update to 1.16.0

---

srcpkgs/python3-Cython/patches/fix-regression.patch
srcpkgs/python3-Cython/template

See: https://github.com/cython/cython/issues/6335
@ahesford
Without this, sagemath FTBS.
With this, sagemath builds and check (tested on x86_64).

python3-Cython: fix regression in cython 3.0.11.

---

srcpkgs/libcaca/template

- I built this PR locally for my native architecture: x86_64-musl
- x86_64
- aarch64
- aarch64-musl
- i686
- i686-musl
- armv7
- armv7l-musl
There is no need for the `vsed` part in `pre_configure()`, it has been corrected upstream.

libcaca: update to 0.99.beta20

---

srcpkgs/strawberry/template

- x86_64-musl: build
- aarch64: cross build
- aarch64-musl: cross build
- armv7l: cross build
- armv6l-musl: cross build
- i686: cross build
Please advise whether `desc_option_qt6` should belong here or perhaps in _common/options.description_

strawberry: default to qt6

---

srcpkgs/android-file-transfer-linux-cli
srcpkgs/android-file-transfer-linux-libs
srcpkgs/android-file-transfer-linux/template

cc @Vaelatern 
This is so that we don't have to bring in gui stuff to use cli tools.

android-file-transfer-linux: update to 4.3, split cli and libs

---

srcpkgs/labwc/template

labwc: update to 0.8.0

---

srcpkgs/papis/template

Not really an update, just to add a missing dependency, `python3-typing_extensions`.

papis: update to 0.13.

---

srcpkgs/lsd/template

lsd: update to 1.1.5

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.21.0.

---

srcpkgs/wine/template

- I tested the changes in this PR: **YES** (but not staging)
https://github.com/void-linux/void-packages/pull/51541
https://bugs.winehq.org/show_bug.cgi?id=57016
Someone noticed in IRC that `staging` option doesn't build anymore. This seems to be related to `git` not being installed which is used in wine-staging's patching scripts. Not sure when that quit working but I guess no one here built staging in a while.

wine: fix staging patch scripts [ci skip]

---

srcpkgs/tmux/patches/sixelcrash.patch
srcpkgs/tmux/template

Fixes crash in terminals that support SIXEL, for more info see https://github.com/tmux/tmux/issues/3983.
In order to avoid the crash without having to wait for the release of 3.5 this PR pathces v3.4 with tmux commit https://github.com/tmux/tmux/commit/aa17f0e0c1c8b3f1d6fc8617613c74f07de66fae

tmux: fix crash in SIXEL

---

srcpkgs/golangci-lint/template

Void has got go 1.23.0 recently. For properly working with new compiler golangci-lint should be compiled with the same version -- 1.23.0 (generally the same or above). Check https://github.com/golangci/golangci-lint/issues/4837 I hope CI of Void Linux takes this rule in account.

golangci-lint: update to 1.60.2

---

srcpkgs/LGOGDownloader/template

LGOGDownloader: update to 3.14

---

srcpkgs/flintlib/patches/2027.patch
srcpkgs/flintlib/template
srcpkgs/python3-numpy/template
srcpkgs/python3-scipy/template
srcpkgs/sagemath/patches/numpy_2.1a.patch
srcpkgs/sagemath/patches/numpy_2.1b.patch
srcpkgs/sagemath/template

After the update, there's a conflict with flintlib headers which causes
trouble, for instance when building sagemath.
A patch to flintlib is included here (from https://github.com/flintlib/flint/pull/2027, already merged upstream).
@ahesford : I'm testing sagemath locally and here as well.

python3-numpy: update to 2.1.0.

---

srcpkgs/rpcbind/template

Tested specifically with nfs4 and it works as expected.
- i686
- x86_64-musl
- aarch64-{glibc,musl} (cross build)
- armv7l (cross build)
- armv6l-musl (cross build)

rpcbind: update to 1.2.7

---

srcpkgs/iproute2/template
srcpkgs/removed-packages/template

Support for ipt and xt in tc was removed in v6.8.0
https://git.kernel.org/pub/scm/network/iproute2/iproute2.git/commit/?id=45dc10463dd5a51eef944b110a4f046feb1b46db

iproute2: update to 6.10.0.

---

srcpkgs/GraphicsMagick/template
srcpkgs/SuiteSparse/template
srcpkgs/octave/template

I cross built the package for aarch64 before and after and the log shows clearly that qt5 was broken before and claims to be working now. But I don't have an aarch64 box to actually test if this fixes #51602.
Closes: #51602 (hopefully)

octave: switch to qt6, fix cross-build

---

srcpkgs/workrave/template

- x86_64-musl
- i686
- aarch64
I didn't see any reason to have GNOME disabled, so I removed that flag. If there's some good reason that I'm missing, let me know.

workrave: update to 1.10.52

---

srcpkgs/keybase/template

Hi, as discussed in #48036 (and encourage by @classabbyamp  to begin to work through them) I am attempting to start resolving breaking changes in updating the template for the keybase client. Unfortunately, I have no prior experience programming in Go. 
When attempting to package this new version of the Keybase client I get the error
```
=> ERROR: keybase-6.4.0_1: do_build: 'go install -p "$XBPS_MAKEJOBS" -v -tags "${go_build_tags}" -ldflags "${go_ldflags}" ${go_package}' exited with 1
=> ERROR:   in do_build() at common/build-style/go.sh:59
```
I think this is a permissions error but I'm not sure how to get more useful info from this error.
Any help majorly appreciated.

keybase: update to 6.4.0.

---

srcpkgs/svt-av1/template

- I tested the changes in this PR: **briefly** (encoded one video using ffmpeg and SvtAv1EncApp using mostly standard settings)
- `armv6l-glibc` (crossbuild)
- `i686-glibc`

svt-av1: update to 2.2.1.

---

srcpkgs/eclipse/template

- I built this PR locally for my native architecture, x86_64.
- I built this PR locally for other architectures: aarch64 (xbuild, untested)
EDIT: thanks @classabbyamp for the assist fixing this one :3
Eclipse is shipping libs for all supported platforms in their tarballs now, and this was causing dependency problems. Deleting the offending libraries from the build dir fixes the issue.
~~Package builds successfully but cannot be installed:~~
~~eclipse-4.32.0_1: broken, unresolvable shlib `ld-linux-riscv64-lp64d.so.1'~~
~~Transaction aborted due to unresolved shlibs.~~
~~Requesting assistance resolving.~~

eclipse: update to 4.32 and add aarch64 support

---

srcpkgs/scapy/template

got some error
```
File "/tmp/./25s.py", line 4, in <module>
from scapy.all import *
File "/usr/lib/python3.12/site-packages/scapy/all.py", line 10, in <module>
from scapy.base_classes import *
File "/usr/lib/python3.12/site-packages/scapy/base_classes.py", line 32, in <module>
from scapy.modules.six.moves import range
ModuleNotFoundError: No module named 'scapy.modules.six.moves'
```
realized it hasn't been updated in a while, works fine on 2.5.0

scapy: update to 2.5.0

---

common/shlibs
srcpkgs/godot/template

- x86_64-musl
- i686
Godot 4.3 supports embree version 4.x and so we can get rid of builtin embree.
Might need some more testing from different people.

godot: switch from builtin embree to package

---

srcpkgs/ndhc/patches/ldflags.patch
srcpkgs/ndhc/template

Patch Makefile to respect LDFLAGS, which has the extra benefit of fixing the static build option.
cc: @Duncaen

ndhc: update to 20240524.

---

srcpkgs/mosquitto/template

mqtt_protocol.h was in the main package, not the devel
the C++ devel pkg needs to depend on the C devel pkg because one of its
headers includes mosquitto.h

mosquitto: move headers to devel pkg, fix deps

---

srcpkgs/libssh/template

libssh: update to 0.11.1.

---

srcpkgs/gimp/patches/libheif-1.18-compat.patch
srcpkgs/gimp/template

libheif commit cf0d89c6e0809427427583290547a7757428cf5a removes the definitions for the `builtin_h265_decoder`, `builtin_h265_encoder`, `builtin_avif_decoder`, and `builtin_avif_encoder` pkg-config variables. This commit is included in libheif 1.80.0 and newer. gimp 2.10.38 depends on these pkg-config variables in its autoconf morass, and as a result is built without support for importing or exporting avif and heic. This commit "fixes" this by forcefully setting these feature detection flags to "yes" if any version of libheif is present. Technically this logic should only apply to libheif 1.80.0 and above, but I don't think there's really any good reason to bother with that additional complication for a patch meant specifically for compiling gimp in a rolling release distribution.
Some …

gimp: reenable avif/heic

---

common/shlibs
srcpkgs/btfs/template
srcpkgs/libtorrent-rasterbar-python/template
srcpkgs/libtorrent-rasterbar/template
srcpkgs/qbittorrent/template
srcpkgs/removed-packages/template

ping @ericonr @slymattz @zen0bit

libtorrent-rasterbar-2.0.10 ,  qbittorrent-4.6.6 , remove libtorrent-rasterbar-python

---

srcpkgs/godot/template

- x86_64-musl
- i686
1. Fixing `mbedtls` with using `mbedtls2` version instead.
2. Remove update check feature.
This PR fixes: https://github.com/void-linux/void-packages/issues/52164.

godot: use mbedtls2 package

---

srcpkgs/librsvg/template

librsvg: update to 2.58.3.

---

srcpkgs/kodi/patches/cross-udfread.patch
srcpkgs/kodi/template

Having TexturePacker once ought to be enough, we already depend on a host kodi and set `-DWITH_TEXTUREPACKER=<path>` for it.
The `--host`/`--build` configure_args had missing quotation marks, which resulted in having nonsense at the end. Removed them.
Replaced the `post_configure` `vsed` with a patch to the `FindUdfread.cmake`

kodi: cleanup template, fix cross

---

srcpkgs/qemu-user/template

It seems that https://github.com/void-linux/void-packages/issues/51804 breaks [void-mklive](https://github.com/void-linux/void-mklive).  With this change I was able to run `mkrootfs.sh aarch64` without errors.  With the current `qemu-user-static` package it complained about missing files when reconfiguring `base-files`.  Apparently the `--static` parameter wasn't included in the new `qemu-user` package.  There may be other flags that need to be updated too.
Error:
```
base-files: configuring ...
ERROR: base-files: [configure] INSTALL script failed to execute the post ACTION: No such file or directory
Failed to reconfigure `base-files': No such file or directory
chroot: failed to run command ‘sh’: No such file or directory
chroot: failed to run command ‘sh’: No such file or directory …
```

qemu-user: Make qemu-user-* binaries static

---

srcpkgs/musl/patches/fgetws.patch
srcpkgs/musl/template

musl: backport patch to fix fgetws

---

srcpkgs/yazi/template

closes https://github.com/void-linux/void-packages/issues/52176
closes https://github.com/void-linux/void-packages/pull/52116

yazi: update to 0.3.3, fix missing ya binary

---

srcpkgs/godot/template

Godot 4.3 has added native support to wayland on its 4.3 release. This PR adds it on build time (the user still needs to enable it using [command line or on the Settings screen](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-3/#wayland-support-for-linux)). 
This PR fixes #52200.

godot: enable wayland support

---

common/build-style/cargo.sh

I'm working on a template for a package that is not yet in the repository and I noticed that the `do_build` function from the `cargo` build-style is missing the `make_build_args` variable. I don't know whether this omission is intentional or not but seeing that both `do_check` and `do_install` have `make_check_args` and `make_install_args` respectively makes me think that it isn't intentional, let me know otherwise.
My use case for this is I need to add the `--package <spec>` option to the `cargo auditable build` action and I can't do that without manually rewriting the `do_build` function.

common/build-style/cargo.sh: add make_build_args to build

---

srcpkgs/python3-starlette/template

python3-starlette: update to 0.38.5

---

srcpkgs/docker-buildx/template

docker-buildx: update to 0.17.0.

---

srcpkgs/ghdl/template

So, I think the last proper update for GHDL outside of it needing to compile for llvm>12 was #45643, and I'm not quite sure if they even tested this situation then, but the current template removes the `/usr/lib/ghdl/src` directory for seemingly no reason.
This means that any designs that use the standard ieee packages just... don't work, since all the definitions for those are in said `src/` directory:
```
$ ghdl -m -Wno-hide --workdir=. adder_8b_tb
adder_8b_tb.vhd:8:10:error: cannot load package "std_logic_1164"
use ieee.std_logic_1164.all;
```
Not removing this directory doesn't appear to affect anything--tested with both the llvm backend and the mcode backend, even …

ghdl: don't remove src/ directory when installing

---

srcpkgs/Signal-Desktop/template

Using `yarn` to build the package resulted in many errors, so I decided to use `npm` instead (I copied the commands from the way Arch Linux does it). I also added a desktop that I copied from `/usr/share/applications`, since I got a build error saying that it was not found without it.
This still needs some testing,
People who might know about this more than me, any suggestions are welcome. Thanks

Signal-Desktop: update to 7.24.1.

---

srcpkgs/pcsc-ccid/template

pcsc-ccid: update to 1.6.1.

---

srcpkgs/papirus-icon-theme/template

- I built this PR locally for my native architecture, x86_64_glibc
It's probably not updated previously as [20240501](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/releases/tag/20240501) targets Plasma 6. As the transition is over it should be fine to upgrade.

papirus-icon-theme: update to 20240501.

---

srcpkgs/stress/template

Changed to the upstream that Debian uses, instead of the Debian package.
- armv6l-musl

stress: move to new upstream

---

srcpkgs/scaleway-cli/template

scaleway-cli: update to 2.33.0, adopt.

---

srcpkgs/flatpak/template
srcpkgs/ostree/patches/fix-ostree-flatpak.patch
srcpkgs/ostree/template

- x64-musl
source of the patch: https://github.com/ostreedev/ostree/pull/3307
Fixes https://github.com/void-linux/void-packages/issues/52273
Peace. :v:

ostree: fix flatpak error (fixes #52273)

---

srcpkgs/scaleway-cli/template

- x86_64-musl
- i686
- armv7l
- armv6l
I disabled the tests as they currently fail when the shell of the build user is set to /usr/bin/sh. I opened an issue uptream to fix this if possible --> https://github.com/scaleway/scaleway-cli/issues/4133

scaleway-cli: update to 2.34.0.

---

srcpkgs/nushell/template

(Installed and ran it as shell, works as expected)
- I built this PR locally for my native architecture, (x86-64-musl)
- i686
- x86_64-glibc

nushell: update to 0.98.0

---

srcpkgs/OpenRCT2/template

- I tested the changes in this PR: **briefly** (the game launches to title screen still, on `x86_64-musl`. that's the extent of today's testing)
Almost exactly 1hr after upstream release... probably my fastest package bump, by luck of having checked my GitHub feed this afternoon :smiley:

OpenRCT2: update to 0.4.14.

---

srcpkgs/python3-keyring/template

python3-keyring: update to 25.3.0.

---

srcpkgs/heisenbridge/template

Note: also adds a missing runtime dependency.
- armv6l
- armv6l-musl

heisenbridge: update to 1.15.0

---

srcpkgs/libavif/template

The options to enable additional codecs require either LOCAL for the vendored copy, or SYSTEM for the system libraries. Our version of libavif was getting built without any support for dav1d, rav1e or svt.
---
Noticed this when running `xbps-remove -o`.
- I tested the changes in this PR: **YES** (only at build time, and it does add the dependencies which were previously missing)

libavif: fix usage of system codecs.

---

common/build-helper/gir.sh
common/build-helper/qemu.sh
srcpkgs/aravis/template
srcpkgs/glib/template
srcpkgs/gobject-introspection-bootstrap/template
srcpkgs/gobject-introspection/template
srcpkgs/libgpg-error/template
srcpkgs/libportal/template
srcpkgs/php8.2/template
srcpkgs/php8.3/template
srcpkgs/umockdev/template

now that the package is split, we don't have to install every emulator under the sun. also, clean up templates that explicitly hostmakedepend on qemu-user.

common/build-helper/qemu: only install the relevant user emulator

---

srcpkgs/python3-peewee/template

python3-peewee: update to 3.17.6.

---

srcpkgs/socat/template

- aarch64 (crossbuilt)
- x86_64-musl (crossbuilt)
- armv6l-musl (crossbuilt)
- As stated on the socat website, this "small" update fixes a couple of regressions in version 1.8.0.0.

socat: update to 1.8.0.1

---

srcpkgs/pylint/template

pylint: update to 3.3.0

---

srcpkgs/amberol/template

amberol: update to 2024.1

---

srcpkgs/LuaJIT/template

LuaJIT: update to 2.1.1724512491.

---

srcpkgs/chromium/files/chromium.sh
srcpkgs/chromium/patches/sndio.patch
srcpkgs/chromium/template

Quickly tested on x86_64-musl with `--js-flags="--jitless --wasm_jitless"`, all the jits are still horribly broken on musl.
- I built this PR locally for my native architecture, `x86_64. x86_64-musl`
https://void.johnnynator.dev/dev/chromium/
[skip ci]
[ci skip]

chromium: update to 129.0.6668.58.

---

srcpkgs/python3-Faker/template

Notes:
- Tests are broken for a while, finally bothered me enough to do the fix
- I've been updating this for a while so maybe adopting it makes checking updates easier via `xcheckmypkgs`

python3-Faker: update to 29.0.0, adopt.

---

Manual.md

see also:
- https://github.com/void-linux/void-packages/issues/48303
- https://github.com/void-linux/void-packages/issues/11240
xlint supports parsing this since leahneukirchen/xtools#322
SPDX expressions are more expressive and accurate than the comma-separated format, and WITH has already been usable for a long time.
I propose that existing multi-licence strings be changed in batches (if someone wants to spend the time) or as templates are modified.
@void-linux/pkg-committers
there are also a few `qt6-*` packages that already use this notation

[RFC] Manual.md: use SPDX expressions for license=

---

srcpkgs/xinput_calibrator/patches/no-update-desktopdb.patch
srcpkgs/xinput_calibrator/template

xinput_calibrator: update to 0.8.0, fix distfile

---

srcpkgs/obs/template

The absolute path results in obs trying to load plugin data from
/usr/usr/share which can't work for obvious reasons

obs: change CMAKE_INSTALL_DATAROOTDIR to relative path

---

srcpkgs/pimcommon/template

Needed for the runtme network reachability check.
Further investigation needed on why qt6-network segfaults without this
(instead of only having missing functionality)

pimcommon: depend on qt6-plugin-networkinformation

---

srcpkgs/wine/template

wine: update to 9.18

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.16, 5.18, 5.19, 6.0–6.11; running on 6.11.0.

tuxedo-drivers: upate to 4.7.0

---

srcpkgs/gst-rtsp-server/template

- I tested the changes in this PR: **YES

gst-rtsp-server: update to 1.24.8.

---

srcpkgs/musl-nscd/files/nscd/run
srcpkgs/musl-nscd/template
srcpkgs/nss-pam-ldapd/patches/nss-pam-ldapd-0.9.12-netdb-defines.patch
srcpkgs/nss-pam-ldapd/template

Don't disable nss in configure. Grab patch from Gentoo for defines missing in musl netdb.h. Disable netgroup_lookup test for musl.
Also remove -F flag in runit script for musl-nscd as it's not recognized.
Tested against my ldap servers and can confirm that it fetches the data defined by nsswitch.conf. Have been running this for a few months and have seen no obvious issues.
- aarch64-musl
- armv7l
- armv6l-musl

nss-pam-ldapd: build libnss_ldap.so.2 for musl

---

srcpkgs/python3-ansible-compat/template
srcpkgs/python3-ansible-lint/template

- I built this PR locally for my native architecture, x86_64-glibc, x86_64-musl
Basically a dep refresh, and I adapted template to fit the new upstream versioning scheme.
- ansible-lint
- [requirements.in](https://github.com/ansible/ansible-lint/blob/v24.9.2/.config/requirements.in) & [requirements-test.in](https://github.com/ansible/ansible-lint/blob/v24.9.2/.config/requirements-test.in)
- [large diff](https://github.com/ansible/ansible-lint/compare/v6.22.1...v24.9.2#diff-c339908dfbcdd2133009c338990a2cb3e73d9c32aa9cf41d3a4469d589e8a176)
- like previous comment in template said, test suite does not work well, but most tests pass so it should be fine.
<details><summary>Test summary with `make_check=ci-skip`</summary>
<p>
```python …
```

python3-ansible-lint: update to 24.9.2; python3-ansible-compat: update to 24.9.1.

---

srcpkgs/python3-keyring/template

python3-keyring: update to 25.4.1.

---

common/build-style/zig-build.sh

ATM, the only way to inspect what zig does during build is the `--verbose` flag, especially since it displays most build info in a TUI style that only works in a tty.

common/build-style/zig-build.sh: add --verbose flag

---

srcpkgs/gtk4/patches/remove-failing-tests.patch
srcpkgs/gtk4/template
srcpkgs/tracker/template

`mesa-24.2.2` (#51881) needs to be merged first. see the note below.
```
Note: This release changes the default GSK renderer to be Vulkan,
on Wayland. Other platforms still use ngl. The intent of this change
is to use the best available platform APIs. You can still override
the renderer choice using the GSK_RENDERER environment variable.
We believe that most of the problems reported with the new renderers
during the 4.13 and 4.15 development cycles have been addressed by now.
But the new renderers and dmabuf support are using graphics drivers
in different ways than the old gl renderer, and trigger new driver bugs.
Therefore, it is recommended to use the latest mesa release (24.2)
with …
```

gtk4: update to 4.16.2

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.26.0.

---

srcpkgs/android-udev-rules/template

android-udev-rules: update to 20240829.

---

srcpkgs/oil/template

oil: update to 0.23.0

---

srcpkgs/musikcube/template

Simple update, things seemed to compile fine. It targets ffmpeg7 but works correctly with void ffmpeg. 
- I've been listening to music both from local files, and from a remote musikcubed 
-  I've tested the built in pulseaudio and the pipewire plugin.
- I built this PR locally for my native architecture
x86_64 
- x86_64-musl
- (cross) aarch64-musl
- (cross) armv7l
- (cross) armv6l-musl

musikcube: update to 3.0.4

---

srcpkgs/sysstat/template

Prior to this change the `sar` command would not show temperature values.  When running `sar -m TEMP` the following message would be displayed:
```
Requested activities not available in file /var/log/sa/sa30
```
After this change and running the following commands `sar` reported temperature values.
```
sudo rm /var/log/sa/sa30
sudo /usr/lib/sa/sa1 1 1
sudo /usr/lib/sa/sa1 1 1
sar -m TEMP
```

sysstat: fix sensors support

---

srcpkgs/onefetch/template

onefetch: update to 2.22.0

---

srcpkgs/mate-panel/patches/musl-strftime.patch
srcpkgs/mate-panel/template

mate-panel: fix strftime on musl

---

srcpkgs/cross-x86_64-w64-mingw32/template
srcpkgs/cross-x86_64-w64-mingw32ucrt
srcpkgs/cross-x86_64-w64-mingw32ucrt-crt

Updates mingw to 12.0.0: https://sourceforge.net/p/mingw-w64/mailman/message/58776404/
Adds `cross-x86_64-w64-mingw32ucrt`: https://www.msys2.org/docs/environments/#msvcrt-vs-ucrt

cross-x86_64-w64-mingw32: update to 12.0.0, build mingw32ucrt package

---

srcpkgs/btop/template

btop: update to 1.4.0

---

srcpkgs/wayfire-plugins-extra/template
srcpkgs/wayfire/template
srcpkgs/wcm/template
srcpkgs/wf-config/template
srcpkgs/wf-recorder/template
srcpkgs/wf-shell/template

- I tested the changes in this PR: **YES**, but want to daily drive it for a bit first.
I don't know what caused the gvc config error in wf-shell, so accepting suggestions... A more complete log (their meson assumes libpulse found means gvc was found, that's why the error at the bottom happens):
```
Executing subproject gvc
gvc| Project name: gvc
gvc| Project version: undefined
gvc| C compiler for the host machine: cc (gcc 13.2.0 "cc (GCC) 13.2.0")
gvc| C linker for the host machine: cc ld.bfd 2.41
gvc| Build-time dependency glib-2.0 found: YES 2.82.1
gvc| Program /usr/bin/glib-mkenums found: NO
gvc| subprojects/gvc/meson.build:30:21: Exception: Dependency 'glib-2.0' tool variable 'glib_mkenums' contains erroneous value: '/usr/bin/glib-mkenums'
gvc| This is a distributor issue -- please …
```

Wayfire 0.9.0

---

srcpkgs/kde-baseapps/template
srcpkgs/kde-plasma/template
srcpkgs/kde5
srcpkgs/kde5-baseapps

kde is now kde 6, so this is misleading
cc @johnnynator

kde5, kde5-baseapps: rename 

---

srcpkgs/pax-utils/template

fixes:
```
lddtree /usr/bin/gcc
File "/usr/bin/lddtree", line 64, in <module>
from elftools.common import exceptions  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'elftools'
```

pax-utils: depend on python3-pyelftools

---

common/shlibs
srcpkgs/emacs/template
srcpkgs/neovim/template
srcpkgs/rizin/template
srcpkgs/tree-sitter/template

tree-sitter: update to 0.24.3, revbump of neovim, emacs, rizin.

---

srcpkgs/iso-codes/template

iso-codes: update to 4.17.0.

---

srcpkgs/fyi/template

[FYI](https://codeberg.org/dnkl/fyi) is a command line utility to send desktop notifications to the user via a notification daemon implementing XDG desktop notifications.

New package: fyi-1.0.4

---

srcpkgs/spotify/template

Fixes: https://github.com/void-linux/void-packages/issues/52693

spotify: add missing dependency

---

srcpkgs/android-udev-rules/template

android-udev-rules: update to 20241019.

---

srcpkgs/python3-peewee/template

Tested using the following script.
```
#!/usr/bin/python
import peewee
import datetime
db = peewee.SqliteDatabase('test.db')
class Note(peewee.Model):
text = peewee.CharField()
created = peewee.DateField(default=datetime.date.today)
class Meta:
database = db
db_table = 'notes'
Note.create_table()
note1 = Note.create(text='Went to the cinema')
note1.save()
note2 = Note.create(text='Exercised in the morning',
created=datetime.date(2018, 10, 20))
note2.save()
note3 = Note.create(text='Worked in the garden',
created=datetime.date(2018, 10, 22))
note3.save()
note4 = Note.create(text='Listened to music')
note4.save()
data = [
{ 'text': 'Tai chi in the morning', 'created': …
```

python3-peewee: update to 3.17.7.

---

srcpkgs/musl/patches/pthread_0001-deduplicate-TP_ADJ-logic-out-of-each-arch-replace-wi.patch
srcpkgs/musl/patches/pthread_0002-deduplicate-__pthread_self-thread-pointer-adjustment.patch
srcpkgs/musl/patches/pthread_0003-remove-redundant-pthread-struct-members-repeated-for.patch
srcpkgs/musl/template

musl: update struct_pthread to musl 1.2 layout
our tid caching implementation in chromium was depending on internal
musl ABI from musl 1.2.4, but we stil have musl 1.1.x by default.
Adding patches to get the same struct_pthread layout from mus 1.2 to get
our chromium builds compatible with both musl 1.1 and 1.2

musl: update struct_pthread to musl 1.2 layout

---

srcpkgs/spotify/template

This also fixes the creation of the `explicit_filter.restore` file.

spotify: update to 1.2.48.

---

srcpkgs/labwc/template

labwc: update to 0.8.1

---

srcpkgs/PrismLauncher/template

- x64-MuslC
Just a little patch in upstream, to fix a Windows installer bug.
I also noticed minor changes in the code, refactoring, alongside the addition of a new "savefile" for the launcher.
Everything's clear.

PrismLauncher: update to 9.1

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.16, 5.18, 5.19, 6.0–6.11; running on 6.11.5.
Note: Build failed for 5.16.20 and 6.2.15, but they are obsolete, anyway.

tuxedo-drivers: update to 4.9.0

---

srcpkgs/CPU-X/patches/disable_tests.patch
srcpkgs/CPU-X/patches/fix_musl.patch
srcpkgs/CPU-X/template

CPU-X: update to 5.0.4.

---

srcpkgs/cage/template

cage: update to 0.2.0

---

srcpkgs/dhcpcd/template

DHCPCD v 10.0.10 was released with some very serious IPv6 bugs, causing IPv6 addresses to be deleted from interfaces before the lease expired: https://github.com/NetworkConfiguration/dhcpcd/compare/v10.0.10...v10.1.0

dhcpcd: update to 10.1.0

---

srcpkgs/perl-namespace-autoclean/template

perl-namespace-autoclean: update to 0.31

---

srcpkgs/libarchive/template

libarchive: update to 3.7.7

---

srcpkgs/zf/template

zf: update to 0.10.1

---

srcpkgs/scons/template

- x86_64-musl
Test built all packages using scons for xbps build style:

scons: update to 4.8.1

---

srcpkgs/bluez/patches/disable-test-vcp.patch
srcpkgs/bluez/template

bluez: update to 5.78.

---

srcpkgs/dpp/patches/fix_ctime.diff
srcpkgs/dpp/template

dpp: update to 10.0.34.

---

srcpkgs/libnatpmp/template
srcpkgs/minissdpd/template
srcpkgs/miniupnpc/template
srcpkgs/miniupnpd/template

Replace HTTP miniupnp.free.fr with HTTPS miniupnp.tuxfamily.org mirror

miniupnp: Update homepage and distfiles

---

srcpkgs/e16/template

Update e16 and also add the libXft dependency as it is mentioned on the e16 website and I noticed it was missing here. I can be convinced to remove it though if its not actually needed.
- x86_64-musl

e16: update to 1.0.30

---

srcpkgs/ruby-tmuxinator/template

ruby-tmuxinator: update to 3.3.2.

---

srcpkgs/dinit/template

- x86_64-musl
- i686
@dkwo, as the maintainer could you please take a look and give me feedback?
I've changed the configuration to enable shutdown but prefix everything with `dinit-`.
Also I added both Markdown files with the explanation for dinit as PID1 and user-init, aswell as copying the example services.

dinit: update to 0.19.1.

---

srcpkgs/octoxbps/template
srcpkgs/qt-sudo/template

Had to package qt-sudo since it's now necessary on octoxbps.

octoxbps: update to 0.4.0 and add new dependency

---

srcpkgs/mesa/template

mesa: update to 24.2.6

---

srcpkgs/gnome-mahjongg/template

- I built this PR locally for these architectures :
- armv7l
- armv6l-musl
- aarch64-musl
Added desktop-file-utils because of this new requirement :
> Program update-desktop-database found: NO
>
> meson.build:40:6: ERROR: Program 'update-desktop-database' not found or not executable

gnome-mahjongg: update to 47.0

---

srcpkgs/os-prober/template

- armv7l
- armv6l-musl
- aarch64-musl

os-prober: update to 1.83

---

srcpkgs/sqlcipher/template

- armv7l
- armv6l-musl
- aarch64-musl

sqlcipher: update to 4.6.1

---

srcpkgs/virtiofsd/template

virtiofsd: update to 1.12.0

---

srcpkgs/python3-dnsrecon/template
srcpkgs/python3-loguru/template

- This new package (python3-loguru) conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**
The dependencies for dnsrecon have changed as of 1.3.0.

python3-dnsrecon update (also add python3-loguru)

---

srcpkgs/texstudio/template

texstudio: update to 4.8.4.

---

srcpkgs/ktouch/template

- I built this PR locally for my native architecture, (x86-64-glib)
- aarch64-musl

ktouch: update to 24.08.2.

---

srcpkgs/mash/template
srcpkgs/pidgin-gpg/template
srcpkgs/pidgin-window-merge/template
srcpkgs/wmfs/template

`mash`'s latest available tag is [`0.2.0`](https://github.com/clutter-project/mash/releases/tag/0.2.0), which is on par with Void linux's package
`wmfs` latest available tag is [`201003`](https://github.com/xorg62/wmfs/releases/tag/201003), which is `< 201104`
`pidgin-window-merge` doesn't have any tags or releases.
`pidgin-gpg`'s latest available tag is [`0.5`](https://github.com/segler-alex/Pidgin-GPG/releases/tag/0.5), which is `< 0.9` (`pidgin-gpg` appears to be a fork of some other project, releases `>=0.9` were created by the forker).
I personally believe that many of these projects deserve to be removed (at least `pidgin-window-merge` does, because it has no releases and therefore no longer meets quality requirements). I have not done so because you (Void maintainers) were …

Fix deprecated GitHub /downloads/ downloads

---

srcpkgs/kodi-addon-pvr-hts/template

kodi-addon-pvr-hts: update to 21.2.5.

---

srcpkgs/kodi-addon-pvr-iptvsimple/template

kodi-addon-pvr-iptvsimple: update to 21.8.7.

---

srcpkgs/kodi-addon-inputstream-rtmp/template

kodi-addon-inputstream-rtmp: update to 21.1.0.

---

srcpkgs/gede/template

Changed homepage as the current one is dead (and gede.dexar.se straight up says "welcome to gede homepage")
Opened, ran against dolphin-emu. Nothing beyond that.

gede: update to 2.19.3

---

srcpkgs/PopCorn/files/popcorn/run
srcpkgs/PopCorn/template

as discussed on #xbps, current will run twice at the snooze time (snooze invocation, then the chpst invocation) and will always run at system start.  
new only runs at system start if haven't run in last day, and doesn't run twice when snooze fires.
- I tested the changes in this PR: **YES** 
x86_64

PopCorn: avoid double runs, use snooze timefile

---

srcpkgs/PrismLauncher/template

Since cmake version 3.8 it will automatically use SOURCE_DATE_EPOCH for the build timestamp.
https://cmake.org/cmake/help/latest/command/string.html#timestamp

PrismLauncher: remove SOURCE_DATE_EPOCH special handling

---

srcpkgs/krita/template

I added `python3-PyQt5` to `depends` since it's necessary for the krita python plugin manager to work and for dockers like the quick settings docker to show up.
@Johnnynator may you please review this PR? Thanks.

krita: update to 5.2.6

---

srcpkgs/qbittorrent/template

Removed the `DQT6=ON` arg since it's unecessary, qbittorrent supports only Qt6 from 5.0.0 onwards.

qbittorrent: update to 5.0.1

---

srcpkgs/pinfo/patches/36.patch
srcpkgs/pinfo/template

To show a man page (e.g. when there is no info file) this program uses
`man -w -W <name>` but option `-W` is unsupported by our `man(1)`.
This results in:
$ pinfo man
man: BADARG: bad command line argument: -W man
Error executing command 'man -w -W  man'
and the terminal is left in a broken state.
Fix by applying this PR: https://github.com/baszoetekouw/pinfo/pull/36

pinfo: fix showing of man pages

---

srcpkgs/pmars/template

pmars: change upstream to site that should work with builders

---

srcpkgs/mise/template

mise: update to 2024.11.1

---

srcpkgs/swirc/template

swirc: update to 3.5.1.

---

srcpkgs/nushell/template

nushell: update to 0.99.1

---

srcpkgs/zfsbootmenu/patches/dracut-config.patch
srcpkgs/zfsbootmenu/template

Adds a workaround for https://github.com/zbm-dev/zfsbootmenu/issues/690 until the upcoming ZFSBootMenu major release can be tagged.

zfsbootmenu: add a fix for dracut-ng behavior change

---

srcpkgs/lsp-plugins-gst
srcpkgs/lsp-plugins-vst3
srcpkgs/lsp-plugins/patches/aarch64-atomic.patch
srcpkgs/lsp-plugins/patches/musl-locale.patch
srcpkgs/lsp-plugins/template

- x86_64-musl
- i686
patch submitted upstream: https://github.com/lsp-plugins/lsp-common-lib/pull/1
Also relevant for: https://github.com/void-linux/void-packages/pull/39796

lsp-plugins: update to 1.2.19, enable cross build.

---

srcpkgs/pmbootstrap/template

pmbootstrap --version
pmbootstrap init (for qemu)
pmbootstrap install (for qemu)
- aarch64-musl - cross compiled on x86_64
- armv7l - cross compiled on x86_64
- armv6l-musl - cross compiled on x86_64
Information about the gitlab migration changes that have been made in this PR. 
https://postmarketos.org/blog/2024/10/14/gitlab-migration/
Release notes for upgrade, tests should be re-enabled so let me know if I'm missing anything here to get them to run in the CI process. Thank you!
https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/tags/3.0.0

pmbootstrap: update to 3.0.0.

---

srcpkgs/llvm19/template

llvm19: disable debug on 32bit build machines

---

srcpkgs/libclc/template

libclc: use libclc alternatives group

---

srcpkgs/discord/template

discord: update to 0.0.74.

---

srcpkgs/llvm19/template

llvm19: fix cross tools, disable mlir

---

srcpkgs/llvm19/template

This reverts commit a7bd3bcfecdc02f77161f14654ba2bc02f31a215.
do not merge until build is done on x86_64 and x86_64-musl
[ci skip]

Revert "llvm19: nocross (save the builders!)"

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.18, 5.19, 6.0, 6.1, 6.3–6.11; running on 6.11.7.

tuxedo-drivers: update to 4.10.2

---

srcpkgs/aerc/template

With 2991ed7a16f6 ("musl: backport patch to fix fgetws") merged, the
tests of the included filters written in C no longer fail on musl and
can thus be enabled.
---

aerc: run the full test suite

---

srcpkgs/streamlink/template

Really just a version bump. No breaking changes from what I could see in release notes and no changes required to python libraries.
- x86_64-musl
- aarch64-musl
- aarch64

streamlink: update to 7.0.0

---

srcpkgs/routinator/template

- aarch64-musl
- armv7l
- armv6l-musl

routinator: update to 0.14.0

---

srcpkgs/synapse/patches/setuptools_rust_upperbound.patch
srcpkgs/synapse/template

synapse: update to 1.119.0.

---

srcpkgs/traceroute/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l

traceroute: update to 2.1.6.

---

srcpkgs/libgpiod-devel
srcpkgs/libgpiod-python3
srcpkgs/libgpiod-tools
srcpkgs/libgpiod/template

Fixes https://github.com/void-linux/void-packages/issues/49469

New package: libgpiod-2.1.3

---

srcpkgs/kid3/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

kid3: update to 3.9.6.

---

srcpkgs/LuaJIT/template

LuaJIT: update to 2.1.1731601260.

---

srcpkgs/NetworkManager/template

- x86_64-musl
- i686
- aarch64
- armv7l

NetworkManager: update to 1.50.0.

---

srcpkgs/chromium/patches/build-support-musl.patch
srcpkgs/chromium/template
srcpkgs/gn/template

Chromium 131

---

srcpkgs/screen/patches/fix-musl.patch
srcpkgs/screen/template

This adjusts configure changes necessary for 5.0.0
- Use `/run/screens/S-<USER>` for socket dir as before; the default `$HOME/.screen` is not nice when home is shared.
- Enable UTMP so screen sessions show up (used to be enabled by default in 4.9.1)
- Other minor cleanup in the configure args
- No need to run autogen.sh
- skip check which are broken (https://savannah.gnu.org/bugs/?66416)

screen: fix socket dir and utmp

---

srcpkgs/SPIRV-LLVM-Translator19/template
srcpkgs/llvm19/template

This reverts commit a10c71946d28e5ad1869dc56405e302228441a81.
[ci skip]

Revert "llvm19: nocross (im sorry buildbot)"

---

srcpkgs/xpadneo/patches/fix-xpadneo-dkms-linux-6.12.patch
srcpkgs/xpadneo/template

- aarch64-musl
- x64-MuslC
Ref: https://github.com/atar-axis/xpadneo/issues/498

xpadneo: Fix dkms build for linux6.12

---

srcpkgs/vaultwarden/template

[Upstream says to update promptly due to a CVE](https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.5):
>  This release further fixed some CVE Reports reported by a third party security auditor and we recommend everybody to update to the latest version as soon as possible. The contents of these reports will be disclosed publicly in the future.

vaultwarden: update to 1.32.5.

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.18, 5.19, 6.0, 6.1, 6.3–6.12; running on 6.12.0

tuxedo-drivers: update to 4.11.3

---

srcpkgs/python3-pygit2/template

python3-pygit2: update to 1.16.0

---

srcpkgs/moosefs/patches/fix-musl.patch
srcpkgs/moosefs/template

- I built this PR locally for these architectures (using crossbuilds):
- aarch64-musl
- armv7l
- armv6l-musl

moosefs: update to 4.56.6

---

srcpkgs/mbedtls/template

fixes broken TLS support in bctoolbox/linphone.

mbedtls: update to 3.6.2.

---

srcpkgs/coin3/patches/no-cpack.patch
srcpkgs/coin3/template
srcpkgs/coin3/update

Fixes #41425 (FreeCAD crash on wayland)

coin3: update to 4.0.3.

---

srcpkgs/typstyle/template

typstyle: update to 0.12.3.

---

srcpkgs/mdadm/patches/musl.patch
srcpkgs/mdadm/template

The mdadm package installs a service that runs `mdadm --monitor --scan`, but that combination of flags segfaults on musl.
After reviewing the backtrace and checking the code, it is due to the code using the GNU `basename()` function instead of the  POSIX one, as noted in the VERSIONS section of basename(3). Due to this, the `basename()` function is not defined under musl and that crashes the program.
backtrace:
```
#0  0x00007ffff7fb3f88 in memchr (src=src@entry=0x55628e05, c=c@entry=0, n=n@entry=2147483647) at src/string/memchr.c:16
#1  0x00007ffff7fb4f56 in strnlen (s=s@entry=0x55628e05 <error: Cannot access memory at address 0x55628e05>, n=n@entry=2147483647)
at src/string/strnlen.c:5
#2  0x00007ffff7faf31b in printf_core (f=f@entry=0x7fffffffe2e0, fmt=fmt@entry=0x5555555f5f6c …
```

mdadm: fix segfault on musl

---

srcpkgs/go/template

- aarch64-musl
- aarch64
- i686
- i686-musl
@the-maldridge @classabbyamp

go: update to 1.23.3.

---

srcpkgs/virtiofsd/template

- I tested the changes in this PR: **YES** (x86_64, Windows 11 guest)

virtiofsd: update to 1.13.0

---

srcpkgs/python3-Faker/template

This version brings Python 3.13 support btw, just before 3.13.1 on Dec 3 per [PEP 719](https://peps.python.org/pep-0719/).

python3-Faker: update to 33.1.0.

---

srcpkgs/gns3-gui/template
srcpkgs/gns3-server/template

gns3-server: update to 2.2.52.
gns3-gui: update to 2.2.52.

GNS3 - update to 2.2.52

---

srcpkgs/apcupsd/files/apcupsd-powerfail.sh
srcpkgs/apcupsd/patches/skip-man-txt-build.patch
srcpkgs/apcupsd/template

apcupsd: add powerfail logic at shutdown

---

srcpkgs/niri/patches/remove-session.patch
srcpkgs/niri/template

- I tested the changes in this PR:  **YES**
contains templates for the niri window manager. i added extra rustflags for musl as it will not compile without those (cannot check if the actual musl checking part works as of now, but i've tested and it only compiles by adding those flags)
closes #48456

new package: niri 0.1.10.1

---

srcpkgs/podman/template

- I tested the changes in this PR: **Testing...**
Still testing, specifically for https://blog.podman.io/2024/10/podman-5-3-changes-for-improved-networking-experience-with-pasta/ (in my case, container/app to host/db)
Tests for Quadlet (probably because systemd?) are not passing.

podman: update to 5.3.1.

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.18, 5.19, 6.0, 6.1, 6.3–6.12; running on 6.12.3

tuxedo-drivers: update to 4.11.6

---

common/hooks/do-pkg/00-gen-pkg.sh
common/hooks/post-install/06-strip-and-debug-pkgs.sh
common/hooks/post-install/98-shlib-provides.sh
common/hooks/pre-pkg/04-generate-runtime-deps.sh
common/hooks/pre-pkg/05-generate-32bit-runtime-deps.sh
common/hooks/pre-pkg/99-pkglint.sh
common/hooks/pre-pkg/999-collected-rdeps.sh
common/xbps-src/shutils/show.sh

to `XBPS_STATEDIR`. There's no need for them to pollute `PKGDESTDIR`. Keep `INSTALL.msg`/`REMOVE.msg` handling as-is for now because it's a little more complex. Keep the pkglints for these files because xbps still ignores them.

common: move handling of rdeps, shlib-provides, shlib-requires files

---

srcpkgs/mesa/template

- x64-muslc
In response to https://github.com/void-linux/void-packages/issues/53434, my sincere apologies for the inconvenience. 
I should have tested the update with more hardware.
I think it's the wisest option we have for now.
I though took the liberty to update to the next minor version, this should fix the max amount of bugs we have with mesa globally.

Revert: "mesa: update to 24.3.1." + Update to 24.2.8

---

srcpkgs/pacman/template

pacman: update to 7.0.0.

---

srcpkgs/xmlto/template

As indicated on the cyberelk website, the project was moved to Fedora pagure. This also has a newer release with fixes for gcc 14.

xmlto: update to 0.0.29

---

Manual.md
common/hooks/pre-pkg/06-verify-python-deps.sh

- **Manual.md: fix naming of nopyverifydeps**
- **common/hooks/pre-pkg/06-verify-python-deps: check for nopyverifydeps**

Correct noverifypydeps documentation, actually use it in 06-verify-python-deps

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.18, 5.19, 6.0, 6.1, 6.3–6.12; running on 6.12.4

tuxedo-drivers: update to 4.11.7

---

srcpkgs/libjpeg-turbo/template

libjpeg-turbo: update to 3.1.0, adopt.

---

srcpkgs/Signal-Desktop/template

As the the new package do not have hicolor icons present I have modified the post_extract script.
Please correct me if I'm wrong

Signal-Desktop: update to 7.34.0

---

srcpkgs/spotify-player/template

- I built this PR locally for these architectures: 
- **armv7l (crossbuild)**
- **armv6l-musl (crossbuild)**
@mdkcore0

spotify-player: update to 0.20.4.

---

srcpkgs/libnitrokey/template
srcpkgs/nitrokey-udev-rules/template

the Nitrokey team has moved [41-nitrokey.rules](https://github.com/Nitrokey/nitrokey-udev-rules?tab=readme-ov-file#nitrokey-udev-rules) to a separate repository where it still remains maintained. The file shipped with libnitrokey is obsolete and no longer maintained.
Using the maintained version of udev rules is more futureproof as it is supposed to be compatible with both legacy (Pro/Storage) and current Nitrokey devices.
https://docs.nitrokey.com/software/nitropy/linux/udev

libnitrokey: use the up-to-date udev rules file

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.36.1

---

srcpkgs/deluge/patches/replace-cgi.patch
srcpkgs/deluge/template
srcpkgs/python3-openssl/template
srcpkgs/python3-pytest-rerunfailures/template
srcpkgs/python3-zope.interface/template

With the update to python 3.13 `deluge` became incompatible with a few things and it crashes on startup, so I had to update `python3-openssl` and `python3-zope.interface` in order for it to work again. 
It's also necessary to patch this [commit](https://github.com/deluge-torrent/deluge/commit/5d96cfc72f0bfa36d90afd2725aa2216b8073d66) into the package, since python 3.13 dropped support for cgi.
We could also just wait to see if upstream releases a new version of deluge compatible with python 3.13, but it could take a while.

fix deluge

---

srcpkgs/gst-libav/template
srcpkgs/gst-plugins-bad1/template
srcpkgs/gst-plugins-base1/template
srcpkgs/gst-plugins-good1/template
srcpkgs/gst-plugins-ugly1/template
srcpkgs/gst-rtsp-server/template
srcpkgs/gst1-editing-services/template
srcpkgs/gst1-python3/template
srcpkgs/gstreamer-vaapi/template
srcpkgs/gstreamer1/template

Security fixes https://gstreamer.freedesktop.org/security/
some of them are remote code execution (RCE)
- https://gstreamer.freedesktop.org/security/sa-2024-0014.html
- https://gstreamer.freedesktop.org/security/sa-2016-0001.html
- https://gstreamer.freedesktop.org/security/sa-2016-0002.html
- https://gstreamer.freedesktop.org/security/sa-2021-0002.html
- https://gstreamer.freedesktop.org/security/sa-2021-0003.html
- https://gstreamer.freedesktop.org/security/sa-2022-0001.html
using on top of my intel libvpl stuff https://github.com/void-linux/void-packages/pull/51496

gstreamer: update to 1.24.10 (security)

---

srcpkgs/Carla/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

Carla: update to 2.5.9, adopt.

---

srcpkgs/linux/template

with the merge of zfs 2.2.7, we should now be safe to update this to 6.12

linux: update to 6.12.

---

srcpkgs/tzutils/patches/only-check-relevant.patch
srcpkgs/tzutils/template

according to the [Python documentation][1], the `zoneinfo` module uses the system timezone data if available, and also provides an installable `tzdata` library on PyPi. Some Python packages (like pandas) spuriously always depend on this library. By having `tzdata` provide this py3: package, it would work around Python packages that make this mistake, and avoid needing to package `python3-tzdata` or set `noverifypydeps` (which would be overkill).
@sgn, this is your package, what do you think?
[1]: https://docs.python.org/3/library/zoneinfo.html

tzutils: tzdata provides py3:tzdata

---

srcpkgs/wee-slack/template

wee-slack 2.10.1 no longer works.  There was a change to the API.

wee-slack: update to 2.11.0.

---

srcpkgs/backblaze-b2/template
srcpkgs/python3-b2sdk/template

backblaze-b2: adding missing runtime dependencies.

---

srcpkgs/kwalletmanager/template

Changes name of dbus service from `kwalletmanager5` to `kwalletmanager`, which is expected by KDE Plasma 6

kwalletmanager: update to 24.12.0.

---

common/scripts/parse-py-metadata.py
srcpkgs/python3-pandas/template

[2.2.3](https://pandas.pydata.org/pandas-docs/stable/whatsnew/v2.2.3.html#pandas-2-2-3-is-now-compatible-with-python-3-13) has Python 3.13 support.
Building succeeded with warning about missing [tzdata](https://github.com/python/tzdata). I guess it's different from python3-pytzdata and not packaged? Not sure if it is needed as previous versions all require it.🤔 Tested against my scripts and pandas just works like 2.2.2.
<details><summary>Build log</summary>
<p>
```
Successfully built pandas-2.2.3-cp313-cp313-linux_x86_64.whl
=> python3-pandas-2.2.3_1: skipping check (make_check=no) ...
=> python3-pandas-2.2.3_1: running pre-install hook: 00-libdir ...
=> …
```

python3-pandas: update to 2.2.3.

---

srcpkgs/colobot-data/template
srcpkgs/colobot/template

colobot: update to 0.2.2

---

srcpkgs/hatchling/template
srcpkgs/python3-ipython_ipykernel/patches/1248.patch
srcpkgs/python3-ipython_ipykernel/patches/1277.diff
srcpkgs/python3-ipython_ipykernel/patches/disable-debugpy.patch
srcpkgs/python3-ipython_ipykernel/template
srcpkgs/python3-jupyter_client/template
srcpkgs/python3-pytest-asyncio/template
srcpkgs/python3-tornado/template

- **hatchling: update to 1.27.0.**
- **python3-pytest-asyncio: update to 0.25.0.**
- **python3-tornado: update to 6.4.2.**
- **python3-jupyter_client: update to 8.6.3.**
- **python3-ipython_ipykernel: patch for python 3.13**

python3-ipython_ipykernel: update deps and patch for python 3.13

---

srcpkgs/greybird-themes/template

Fixes greybird theme display bug with xfdesktop v4.19 and v4.20.
Closes https://github.com/void-linux/void-packages/issues/53634.

greybird-themes: update to 3.23.4

---

srcpkgs/rust-bindgen/template

rust-bindgen: update to 0.71.1

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: fix missing program icons

---

srcpkgs/containerd/template

containerd: update to 2.0.1.

---

srcpkgs/python3-lxml_html_clean/template
srcpkgs/python3-readability-lxml/template

- **This package adds a new / split-off dependency that is required by an existing package (see below).**
- armv7l-musl
lxml 5.2 moved lxml.html.clean to a separate project, leaving only a compatibility shim in its place. Since the update to Void's python3-lxml package on Dec. 13, importing readability causes the following error to be emitted:
```
ImportError: lxml.html.clean module is now a separate project …
```

python3-readability-lxml: add new python3-lxml_html_clean dependency, required since lxml 5.2

---

srcpkgs/libtpms/patches/806141196296150c03e5d826ab7e6c3602f41b98.patch
srcpkgs/libtpms/template
srcpkgs/swtpm/template

- **libtpms: update to 0.10.0.**
- **swtpm: update to 0.10.0.**

libtpms/swtpm: update to 0.10.0

---

srcpkgs/ppsspp/patches/fix-ffmpeg6.patch
srcpkgs/ppsspp/template

the discussion about ffmpeg6 can be had once we actually drop ffmpeg4
ffmpeg6 breaks video playback twofold:
a) messed up video (can be fixed by using private API to set AVSTREAM_PARSE_FULL)
b) ppsspp hangs at the end of a video

ppsspp: update to 1.18.1., revert to ffmpeg4

---

srcpkgs/singular/update

See my comment https://github.com/sagemath/sage/pull/38689#issuecomment-2366934173
@dkwo

singular: skip *p* versions which are not stable releases

---

srcpkgs/plasma-workspace/template

used by the org.kde.plasma.cameraindicator plasmoid

plasma-workspace: add kpipewire dependency

---

srcpkgs/python3-pystache/template
srcpkgs/removed-packages/template

This reverts commit c4563fb92874f300a36c16fb85fbb4cceade59f3.
this package was still used by linphone as a buildtime dependency

Revert "python3-pystache: remove package", update to 0.6.7.

---

srcpkgs/python3-contourpy/template
srcpkgs/python3-kiwisolver/template

- **python3-kiwisolver: update to 1.4.8.**
- **python3-contourpy: update to 1.3.1.**
cc: @ahesford

matplotlib deps

---

srcpkgs/bcmatroska2/template
srcpkgs/bctoolbox/patches/disable-psa-crypto.patch
srcpkgs/bctoolbox/template
srcpkgs/belcard/template
srcpkgs/belle-sip/template
srcpkgs/belr/template
srcpkgs/bzrtp/template
srcpkgs/linphone-desktop/template
srcpkgs/linphone/template
srcpkgs/mediastreamer/template
srcpkgs/ortp/template

mediastreamer still not compatible with ffmpeg6 :(

Linphone 5.3.100

---

srcpkgs/tealdeer/template
srcpkgs/tldr/template

Without this, fish shell doesn't automatically load completions for the `tldr` symlink.
cc @filiprojek

tealdeer: add alternative symlink for fish completions

---

srcpkgs/firewalld-applet
srcpkgs/firewalld-config
srcpkgs/firewalld/files/firewalld/check
srcpkgs/firewalld/files/firewalld/conf
srcpkgs/firewalld/files/firewalld/run
srcpkgs/firewalld/template

- x86_64-musl
- i686
based on https://github.com/void-linux/void-packages/pull/34378, but splitting the configuration gui and applet into subpackages, and gave them the proper dependencies

New package: firewalld-2.2.1

---

srcpkgs/milkytracker/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

milkytracker: update to 1.05.01, adopt.

---

srcpkgs/freerdp3/patches/fix-cross.patch
srcpkgs/freerdp3/patches/warn-print-after-ssl-init.patch
srcpkgs/freerdp3/template

freerdp3: update to 3.10.3

---

srcpkgs/xonotic/template

sources/darkplaces/makefile checks arch with `uname -m`, which gives host arch, not target one, and then applies some AMD64-exclusive flags if it's compiled on AMD64, which causes breaks.
- I tested the changes in this PR: **NO** (only building)

xonotic: allow cross-compilation

---

srcpkgs/python3-minidb/template
srcpkgs/urlwatch/template

This PR updates `python3-minidb` as well to fix the test added because of this bug: thp/urlwatch#779

urlwatch: update to 2.29

---

common/shlibs
srcpkgs/fplll/template
srcpkgs/python3-fpylll/template

- **fplll: update to 5.5.0.**
- **python3-fpylll: update to 0.6.2.**

fplll: update to 5.5.0, python3-fpylll: update to 0.6.2.

---

srcpkgs/helix/template

helix: update to 25.01

---

srcpkgs/yadm/template

yadm: update to 3.3.0, do_check, adopt.

---

srcpkgs/font-cozette/template

Primarily version bump. I had no issues compiling and tested in XFCE terminal.
- x86_64-musl
- aarch64
- aarch64-musl

font-cozette: update to 1.26.0

---

srcpkgs/prosody/template

- **New package: lua54-say-1.4.1**
- **New package: lua54-assert-1.9.0**
- **New package: lua54-cliargs-3.0.2**
- **New package: lua54-dkjson-2.8**
- **New package: lua54-mediator-1.1.2**
- **New package: lua54-penlight-1.14.0**
- **New package: lua54-system-0.4.5**
- **New package: lua54-term-0.8**
- **New package: busted-2.2.0**
- **prosody: update to 0.12.5.**
Built on x86_64-glibc for aarch64-musl and tested correctly. 
Server comes up and I can chat with folks
Opening it now ~~to have an open PR on January 1st~~ because it uses
some work from PR #51222. So I want to signal that these 2 PRs use
the same technique (luarocks) for packaging some dependencies.
If the busted …

prosody: update to 0.12.5.

---

srcpkgs/LuaJIT/template

LuaJIT: update to 2.1.1734355927.

---

srcpkgs/luanti/template

This package is using a bundled luajit. It should use our luajit instead.
- x86_64-musl
- i686

luanti: Build with LuaJIT

---

srcpkgs/lua54-luarepl/template

When cross compiling the path in /usr/bin/repl.lua contains the target
arch in the destdir path, which must be replaced differently than the
others.
Aside from that, added lua version to the package and sub packages
descriptions, as well as switched to vsed to catch this next time. And
move vlicense in _package.

lua54-luarepl: fix cross compiled binary

---

srcpkgs/libgit2-1.8/template

Switches newest libgit2 to invoke `openssh` from commandline for ssh git remotes etc.
Rationale:
- `git` also uses openssh under the hood
- parses ssh configuration files, making use of all openssh features
Note that since consistency is one of the goals here, I'd consider rebuilding any remaining non-rust packages to 1.8 a priority.

[RFC] libgit2-1.8: switch from libssh2 to openssh

---

srcpkgs/python3-socks/template
srcpkgs/python3-tiny-proxy/template

`python3-tiny-proxy` is now needed for the tests to run. I considered `make_check=no`, but well, it's tiny, and this way we can also enable tests for `python3-aiohttp_socks`.

python3-socks: update to 2.6.1.

---

srcpkgs/ktouch/template

ktouch: update to 24.08.3.

---

srcpkgs/android-udev-rules/template

android-udev-rules: update to 20241109.

---

srcpkgs/python3-scipy/patches/test-32bit.patch
srcpkgs/python3-scipy/template
srcpkgs/sagemath/patches/39261-scipy_1.15.patch
srcpkgs/sagemath/patches/get_patches

- **python3-scipy: update to 1.15.0.**
- **sagemath: patch doctests for scipy-1.15**
- I tested the changes in this PR: **briefly** (tested with sagemath)

python3-scipy: update to 1.15.0.

---

srcpkgs/eza/template

eza: update to 0.20.16

---

srcpkgs/sile/template

Untested bump in the blind ;-)
This includes one change from the recently approved major overhaul (see #51222). The *default* upstream options use a bundling system to wrap dozens and dozens of project Lua files and embed them into the final Rust binary. This was made the default upstream to simplify installation from source for end users that may have trouble working out their system's Lua paths and may or may not compile with the right options. That being said as the upstream developer I personally recommend *not* using this option and installing all the files directly using the package manager if possible. Since this is a system package it will have all the Lua path stuff sorted out for the end user already, and this makes it easier to use SILE. One common thing to do in a SILE based …

sile: update to 0.15.9

---

srcpkgs/eudev/patches/78-sound-card.rules.patch
srcpkgs/eudev/template

- I tested the changes in this PR: yes, on aarch64 Apple silicon

eudev: import upstream patch for audio

---

srcpkgs/corectrl/template

Just a version bump. Although I was able to build for x86_64, aarch64, and aarch64-musl but x86_64-musl would not build with this error.
```
CMake Error: AUTOMOC for target corectrl_lib: Test run of "moc" executable "/usr/x86_64-linux-musl/usr/lib/qt5/bin/moc" failed.
/usr/x86_64-linux-musl/usr/lib/qt5/bin/moc -h
no such file or directory
CMake Generate step failed.  Build files cannot be regenerated correctly.
=> ERROR: corectrl-1.4.3_1: do_configure: 'CFLAGS="-DNDEBUG ${CFLAGS/ -pipe / }" CXXFLAGS="-DNDEBUG ${CXXFLAGS/ -pipe / }" cmake ${cmake_args} ${configure_args} ${LIBS:+-DCMAKE_C_STANDARD_LIBRARIES="$LIBS"} ${LIBS:+-DCMAKE_CXX_STANDARD_LIBRARIES="$LIBS"} ${wrksrc}/${build_wrksrc}' exited with 1
=> ERROR:   in do_configure() at common/build-style/cmake.sh:77
```
I was able to run …

corectrl: update to 1.4.3

---

srcpkgs/python3-pika/template
srcpkgs/radicale/template

radicale: update to 3.4.0.

---

srcpkgs/lzfse/template

cc @classabbyamp otherwise, lzfse just pulls in devel

lzfse: do not vmove its so into devel

---

srcpkgs/openblas/template
srcpkgs/python3-scipy/template

- **openblas: update to 0.3.29.**
- **python3-scipy: update to 1.15.1.**
- **sagemath: bump to test - DO NOT MERGE**
- I tested the changes in this PR: **briefly** (locally sagemath on x86_64)
@ahesford scipy ftbfs without libgomp-devel, I think it should go in openblas-devel depends

update openblas 0.3.29 / scipy 1.15.1

---

srcpkgs/wslu/template

wslu: update to 4.1.4

---

srcpkgs/libqalculate/template
srcpkgs/qalculate-gtk/template
srcpkgs/qalculate-qt/template

of course an update releases half an hour before the last one was merged x)

qalculate: update to 5.5.0

---

srcpkgs/hut/template

additional:
- the main repo has moved from ~emersion to ~xenrox

hut: update to 0.6.0.

---

srcpkgs/nitrokey-udev-rules/template

nitrokey-udev-rules: update to 1.1.0

---

srcpkgs/lego/template

lego: update to 4.21.0.

---

common/shlibs
srcpkgs/maliit-framework-devel
srcpkgs/maliit-framework-doc
srcpkgs/maliit-framework-examples
srcpkgs/maliit-framework/template
srcpkgs/maliit-keyboard-doc
srcpkgs/maliit-keyboard/template

Maybe fix: #49597
- I tested the changes in this PR: **YES**, but maliit virtual keyboard still not working. any advice @classabbyamp ?
```
Operating System: Void 
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.6.48_1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i5-10500H CPU @ 2.50GHz
Memory: 23.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: Micro-Star International Co., Ltd.
Product Name: GF63 Thin 10UC
System Version: REV:1.0
```

New package: maliit-keyboard

---

srcpkgs/nvidia470/patches/0001-Fix-conftest-to-ignore-implicit-function-declaration.patch
srcpkgs/nvidia470/patches/0002-Fix-conftest-to-use-a-short-wchar_t.patch
srcpkgs/nvidia470/patches/0003-Fix-conftest-to-use-nv_drm_gem_vmap-which-has-the-se.patch
srcpkgs/nvidia470/patches/kernel-6.10.patch
srcpkgs/nvidia470/patches/kernel-6.12.patch
srcpkgs/nvidia470/template

nvidia470: update to 470.256.02.

---

srcpkgs/soju/files/README.voidlinux
srcpkgs/soju/template

soju: fix wrong command name in README.voidlinux

---

srcpkgs/font-sarasa-gothic/template

The path (TTC vs. TTF) mismatch finally bothers me enough to make a fix.

font-sarasa-gothic: use correct path

---

srcpkgs/dillo/template

See <https://dillo-browser.github.io/dillo.org.html>

dillo: update homepage

---

srcpkgs/iperf/patches/fix-udphdr-musl.patch
srcpkgs/iperf/template

iperf: update to 2.2.1.

---

srcpkgs/nauty/patches/fix-runalltests.patch
srcpkgs/nauty/template

nauty: update to 2.8.9.

---

srcpkgs/libbraiding/template

libbraiding: update to 1.3.1.

---

srcpkgs/libmtp/patches/fix-warning.patch
srcpkgs/libmtp/template

libmtp: update to 1.1.22, adopt.

---

srcpkgs/ttf-vista-fonts/template

add ttf-vista-fonts package (nonfree)

---

srcpkgs/lzlib/template
srcpkgs/plzip/template

lzlib: also move the info documentation to the -devel subpackage.

lzlib and plzip: update

---

srcpkgs/streamlink/template

Version bump. Did not see any major/breaking changes in the release notes. The one thing I did see is they removed the typing extensions dependency. I tested and it works fine.
- x86_64-musl
- aarch64
- aarch64-musl

streamlink: update to 7.1.1

---

srcpkgs/swayimg/template

swayimg: update to 3.7.

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.18, 5.19, 6.0, 6.1, 6.3–6.12; running on 6.12.10

tuxedo-drivers: update to 4.12.0

---

srcpkgs/virtualbox-ose/template

- Checks passed locally.
7.1.6 has initial linux-6.13 support and fixed several issues on linux-6.12.

virtualbox-ose: update to 7.1.6.

---

srcpkgs/Komikku/template
srcpkgs/python3-colorthief/template

Komikku migrated to codeberg.
- https://github.com/void-linux/void-packages/pull/50777
Ty @chrysos349

Komikku: update to 1.68.0, adopt.

---

srcpkgs/gnome-autoar/template

gnome-autoar: update to 0.4.5

---

srcpkgs/tuxedo-drivers/template

Built for kernels 5.15, 5.18, 5.19, 6.0, 6.1, 6.3–6.12; running on 6.12.11

tuxedo-drivers: update to 4.12.1

---

srcpkgs/juliaup/template

juliaup: update to 1.17.11.

---

srcpkgs/github-cli/template

github-cli: update to 2.66.1

---

srcpkgs/rio/template

rio: update to 0.2.5

---

srcpkgs/google-chrome/template

Latest Google Chrome release per the Chrome blog on January 28:
https://chromereleases.googleblog.com/2025/01/stable-channel-update-for-desktop_28.html

google-chrome: update to 132.0.6834.159.

---

srcpkgs/asahi-base/template

Other "base" packages depend on dracut, and asahi-scripts is needed for the dracut hooks
@dkwo

asahi-base: update to 20250202, depend on asahi-scripts and dracut.

---

common/shlibs
srcpkgs/SDL3/template

Removed the SDL_ESD=off tag, because it wasn't used in the compilation.

SDL3: update to 3.2.2

---

srcpkgs/electron33/patches/spellchecker-infinate-loop.patch
srcpkgs/electron33/template

[ci skip]
cc: @Johnnynator 
Tested on x86_64 and x86_64-musl and appears to work.
Fixes crashing in vscode 1.96.x.
See: https://github.com/void-linux/void-packages/pull/51909
- x86_64-musl (native)

electron33: update to 33.2.0.

---

srcpkgs/vscode/patches/disable-crash-reporter.patch
srcpkgs/vscode/template

vscode: update to 1.96.4

---

common/xbps-src/libexec/xbps-src-doinstall.sh

[ci skip]
This fixed the issue where the post-install hooks are not rerun even though `-f` was specified. Resulting in some weird error about lib64 not being allowed, since xbps-src creates the symlink in the destdir and removes it again in the post-install hook.

xbps-src: re-run post-install hooks if -f flag is used

---

srcpkgs/gnome-mahjongg/template

- armv7l
- armv6l-musl
- aarch64-musl

gnome-mahjongg: update to 47.1

---

srcpkgs/opera/template

<br/>
@mobinmob could you please review the changes??
<br/>
I have migrated to ffmpeg6 and it seems to work fine for me, the package itself installs the ffmpeg6 so I don't think we require ffmpeg4 anymore

opera: update to 116.0.5366.71

---

srcpkgs/glances/template

- x86_64-musl
- i686 (cross)
<br/>
@icp1994 could you please review the changes??
Thanks for your time!!

glances: update to 4.3.0.8

---

srcpkgs/swirc/template

swirc: update to 3.5.2.

---

srcpkgs/incus/template

- I tested the changes in this PR: **YES**,  with XBPS_CHECK_PKGS=yes and on a running system with lxc containers and qemu VMs.
- I built this PR locally for my native architecture: amd64 glibc
- I cross-compiled this PR locally for aarch64
This PR affects incus and symlinked srcpkgs incus-client and incus-tools.

incus: update to 6.9.0.

---

srcpkgs/google-chrome/template

Other info: This is the latest stable channel release, addressing 12 security fixes including 2 high severity undisclosed (as yet) issues.
https://chromereleases.googleblog.com/2025/02/stable-channel-update-for-desktop.html

google-chrome: update to 133.0.6943.53.

---

srcpkgs/mesa-asahi/template

- I built this PR locally for my native architecture, aarch64-glibc
- aarch64-musl

mesa-asahi: Enable Honeykrisp vulkan driver

---

srcpkgs/polychromatic/template

Problem:  `polychromatic-controller`  misses a dependency:
```
File "/usr/bin/polychromatic-controller", line 36, in <module>
import polychromatic.controller as controller
File "/usr/lib/python3.12/site-packages/polychromatic/controller/__init__.py", line 1, in <module>
from . import devices, effects, menubar, preferences, shared
File "/usr/lib/python3.12/site-packages/polychromatic/controller/devices.py", line 27, in <module>
from . import shared
File "/usr/lib/python3.12/site-packages/polychromatic/controller/shared.py", line 17, in <module>
from PyQt6.QtSvg import QSvgRenderer
ModuleNotFoundError: No module named 'PyQt6.QtSvg'
```
This adds the missing dependency which is requred for `polychromatic-controller` to work.
- I tested the changes in this …

polychromatic: Add missing dependency

---

srcpkgs/miniserve/template

miniserve: update to 0.29.0

---

srcpkgs/gnome-keyring/template

gnome-keyring: update to 46.2.

---

srcpkgs/gst-plugins-base1/template

Closes: #54215
I have no idea if the absence of this plugin breaks any packages as we ship them, or how many people's workflows will be disrupted, but cutting `libvisual` out of the loop seems to be the easiest way to break a dependency cycle.
cc: @Piraty

gst-plugins-base1: break cycle by making libvisual dependency optional

---

srcpkgs/gst-plugins-bad1/template

This change adds the nv-codec-headers package as a build dependency to gst-plugins-bad1 enabling the build of the nvcodec plugins.

gst-plugins-bad1: enable build with nvcodec

---

srcpkgs/spotify/template

spotify: update to 1.2.56

---

srcpkgs/cryptsetup/template
srcpkgs/qemu-user/template
srcpkgs/qemu/template
srcpkgs/toybox/template
srcpkgs/xbps-static/template

To be merged after the cross-* rebuild is done.
Missing:

Rebuild static programs against fixed musl

---

srcpkgs/google-chrome/template

(yet another) Stable channel update addressing 4 CVEs.
https://chromereleases.googleblog.com/2025/02/stable-channel-update-for-desktop_12.html

google-chrome: update to 133.0.6943.98.

---

srcpkgs/python3-pyzstd/template

python3-pyzstd: update to 0.16.2.

---

srcpkgs/python3-keyring/template

python3-keyring: update to 25.6.0.

---

srcpkgs/LuaJIT/template

LuaJIT: update to 2.1.1736781742.

---

srcpkgs/orca/template

orca: update to 47.3.

---

srcpkgs/gmic-krita/patches/conflict.patch
srcpkgs/gmic-krita/template
srcpkgs/gmic-krita/update

cc @johnnynator
the files in `/usr/share/gmic` were moved to `/usr/share/gmic-krita` to avoid conflicts with regular gmic, which will install some of the same files there in new versions

gmic-krita: update to 3.5.0.1.

---

srcpkgs/owncloudclient/patches/11943.patch
srcpkgs/owncloudclient/template
srcpkgs/qtkeychain-qt6/template

- **qtkeychain-qt6: update to 0.15.0.**
- **owncloudclient: update to 5.3.2.**

owncloudclient: update to 5.3.2.

---

srcpkgs/eog-plugins/template
srcpkgs/eog/template

eog: update to 47.0.

---

srcpkgs/StyLua/template

- Also enable LuaJIT support as it's packaged in Void
Did not ping the maintainer due to inactivity (last commit to this repo dated back to Jan 2023).

StyLua: update to 2.0.2.

---

srcpkgs/kfind/template
srcpkgs/kolourpaint/template
srcpkgs/kompare/template

kompare, kolourpaint, kfind: update to 24.12.2.

---

srcpkgs/wpa_supplicant/INSTALL.msg
srcpkgs/wpa_supplicant/files/wpa_supplicant.conf
srcpkgs/wpa_supplicant/files/wpa_supplicant/run
srcpkgs/wpa_supplicant/patches/unsurprising-ext-password.patch
srcpkgs/wpa_supplicant/template

The capabilities are the ones recommended in upstream README. They recommend to set them on the executable, but it seems safer to set them in the service.
- I tested the changes in this PR: yes, but only using the runit service. I.e., did not test other potential consumers of wpa_supplicant, like network manager or wpa_cli. 
Added a patch to the external file function, which is now upstream.

[rfc] wpa_supplicant: use capabilities in service to run as non-root

---

srcpkgs/openh264/template

> A vulnerability in the decoding functions of OpenH264 codec library could allow a remote, unauthenticated attacker to trigger a heap overflow.
**[https://github.com/cisco/openh264/security/advisories/GHSA-m99q-5j7x-7m9x](https://github.com/cisco/openh264/security/advisories/GHSA-m99q-5j7x-7m9x)**
- i686
- x86_64-musl

openh264: update to 2.6.0

---

srcpkgs/fontconfig/template

`70-no-bitmaps` now includes `70-no-bitmaps-except-emoji`, but this only works if `70-no-bitmaps-except-emoji` is already in `conf.d` (not just `conf.avail`). This fixes regressions some users have been reporting with bitmap fonts showing up again since the latest update.

fontconfig: fix 70-no-bitmaps for deprecation

---

srcpkgs/wpa_supplicant/INSTALL.msg
srcpkgs/wpa_supplicant/files/wpa_supplicant.conf
srcpkgs/wpa_supplicant/files/wpa_supplicant/run
srcpkgs/wpa_supplicant/template

This reverts commit b43eee69fdadff822b9c0988d4867395426139bc.
Many users have reported an inability to control wpa_supplicant with this change, including not being able to use wpa_cli as root or not and not having working internet on fresh installs.
cc @dkwo @leahneukirchen

Revert "wpa_supplicant: use capabilities in service"

---

srcpkgs/emacs/template

JSON is builtin now, drop xwidgets as our webkit2gtk is too recent.

emacs: update to 30.1.

---

srcpkgs/base-files/files/locale.sh
srcpkgs/base-files/template

Fixes overwriting user/desktop specified locale.
Currently we always overwrite LANG on login, even if it was already set by the desktop or user which causes issues with GDM.
You can see what Arch does here:
https://bugs.archlinux.org/task/42162
https://gitlab.archlinux.org/archlinux/packaging/packages/filesystem/-/blob/main/locale.sh
You can see what Fedora does here:
https://gist.github.com/oreo639/3b83b852ce0db21e21eed102a57c5148
(taken from the setup package)
https://github.com/void-linux/void-packages/issues/15292

base-files: don't overwrite existing locale and define default LANG

---

srcpkgs/lego/template

lego: update to 4.22.2.

---

common/shlibs
srcpkgs/chafa/template
srcpkgs/darktable/template
srcpkgs/digikam/template
srcpkgs/glycin/template
srcpkgs/imlib2/template
srcpkgs/kf6-kimageformats/template
srcpkgs/krita/template
srcpkgs/libjxl/template
srcpkgs/rawtherapee/template
srcpkgs/swayimg/template
srcpkgs/vips/template

libjxl: update to 0.11.1.

---

srcpkgs/fish-shell/template

fish-shell: update to 4.0.0, adopt

---

srcpkgs/LACT/files/lact/run
srcpkgs/LACT/template

New package: LACT-0.7.0

---

srcpkgs/wine/INSTALL
srcpkgs/wine/REMOVE
srcpkgs/wine/files/wine
srcpkgs/wine/files/wineserver
srcpkgs/wine/template

Also add doc about the new WoW64 build option and update the alert in the script.
Broken wine64 symlink was removed.
Hotfix for updated wine-tools, the script now passes the 0th argument to wine properly(Props to @oreo639).
The removal of the wine/wine64 scheme caused issues with users not being able to install both wine and wine-32bit together. It's being addressed by now installing to `/usr/libexec/wine/wine32` and `/usr/libexec/wine/wine64` respectively.
There is a bug report that the 32bit build is broken, uncertain if it's related to the issue described above, left as a [WIP] & draft until resolved.
logs: https://gist.github.com/oreo639/cf2f5f8cb27475db87fc58051e69ddf4

wine: update to 10.2

---

srcpkgs/docker-cli/template
srcpkgs/moby/template

- aarch64-musl (cross-build)
- i686 (cross-build)
- x86_64
This PR fixes #54524

moby: update to 28.0.1, fix and re-enable cross builds & docker-cli: update to 28.0.1

---

srcpkgs/mkinitcpio/files/zfs_hook
srcpkgs/mkinitcpio/template

In response to my comments in https://github.com/void-linux/void-packages/pull/54391, I propose the following cleanup of the mkinitcpio ZFS hook. I have not yet tested these changes!
I'd be open to changing the walk for `/usr` to descend from `${ZFS_DATASET}` to preserve the current behavior. This would still drop the mounting of **all other** children, which I still maintain is a job for the final init. I'm not even thrilled about mounting `/usr` here, but I guess we need it to fill the gaps in the `usr` hook for ZFS users with mount management enabled.
cc: @classabbyamp 

mkinitcpio: improve zfs hook

---

srcpkgs/kf6-kimageformats/template
srcpkgs/x265/template

This adds support for higher bit depths and fixes the kimageformats-write-heif test for kf6-kimageformats.
Unfortunately this requires x265 to be built 3 times, thankfully the compiles are pretty short.
https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/x265/APKBUILD
https://salsa.debian.org/multimedia-team/x265/-/blob/master/debian/rules

x265: enable higher bit depths

---

srcpkgs/streamlink/template

Primarily just a version bump. No major changes on streamlinks end, besides requiring freezegun 1.5.0 and we (Void) are already on 1.5.1.
- aarch64-musl
- aarch64
- x86-64-musl

streamlink: update to 7.1.3

---

srcpkgs/libfido2/INSTALL.msg
srcpkgs/libfido2/template

Proposal to change group permissions from "users" to "plugdev" for accessing FIDO2 devices.
This has been previously discussed in #39688, I could not find a follow-up PR so I created this.

libfido2: use upstream group "plugdev" for udev

---

srcpkgs/moby/files/docker/run
srcpkgs/moby/template

This change removes the code that created the `/sys/fs/cgroup/systemd` mountpoint.
The change was added in an [earlier PR](https://github.com/void-linux/void-packages/pull/5959
) that referenced a page in the wiki.  The wiki is gone but I believe the error was the one described in [this comment](https://github.com/void-linux/void-packages/issues/5402#issue-387336249).
I do not believe the mountpoint is required anymore.
Also, when running kubernetes on a host with docker running the following errors show up in the kubelet logs.  They disappear when the  `/sys/fs/cgroup/systemd` mountpoint is removed.
```
2025-01-15T07:59:14.160779-06:00 localhost kubelet: E0115 07:59:14.160635    2856 cadvisor_stats_provider.go:522] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: …
```

moby: Remove unneeded systemd cgroup mount

---

srcpkgs/davmail/template

- None
I'd love to switch to Github releases, but sadly the author does not reliably [tag his releases here](https://github.com/mguessan/davmail/tags).

davmail: update to 6.3.0.

---

srcpkgs/mlt7/template
srcpkgs/shotcut/template

- cross **i686**
runs fine, exported quick video cut up with resize + no sound + normal sections
~~@Johnnynator~~ johnny orphaned between opening this and 25 update
updated mlt7 to 7.30, 32bit builds were bombing

shotcut: update to 25.01.25

---

srcpkgs/dunst/template

- aarch64-musl
- aarch64
- armv7l
- armv7l-musl

dunst: update to 1.12.0.

---

srcpkgs/libutf8proc/template

libutf8proc: update to 2.10.0

---

srcpkgs/cmusfm/template

cmusfm: update to 0.5.0

---

srcpkgs/wine/template

Tested old WoW64, launch with 32bit wine, new WoW64 on musl.
Small release mainly consisting of bugfixes, added clipboard support for the wayland driver.
@Hoshpak

wine: update to 10.3

---

srcpkgs/libnotify/patches/stylesheet_url.patch
srcpkgs/libnotify/template

- aarch64-musl [ok]
- armv7l [ok]
- armv6l-musl [ok]
!!
meson.build:75:4: ERROR: Problem encountered: DocBook stylesheet for generating man pages not
found, you need to install docbook-xsl-ns or similar package.
!!
- add patch `meson: update stylesheet url`

libnotify: update to 0.8.4.

---

srcpkgs/fish-shell/patches/test-args.patch
srcpkgs/fish-shell/template

fish-shell: update to 4.0.1

---

srcpkgs/DirectXShaderCompiler/template
srcpkgs/amdvlk/template

- **DirectXShaderCompiler: update to 1.8.2502.**
- **amdvlk: update to 2025.Q1.3.**

amdvlk: update to 2025.Q1.3

---

srcpkgs/swirc/template

swirc: update to 3.5.4.

---

common/build-style/go.sh

The output with `-v` is often too verbose, making it difficult to scour the logs, especially in the GitHub actions UI.

common/build-style/go.sh: disable verbose test output

---

srcpkgs/kio-gdrive/template

kio-gdrive: update to 24.12.1.

---

srcpkgs/lagrange/template

lagrange: update to 1.18.5.

---

srcpkgs/routinator/template

From the release announcement: "This release fixes an issue in the bundled UI that caused it to retrieve data from our own test instance rather than the actual Routinator instance. Users of the bundled UI should upgrade."
- aarch64-musl
- armv7l
- armv6l-musl

routinator: update to 0.14.2

---

srcpkgs/sane/template

sane: update to 1.3.1.

---

srcpkgs/elfutils/template

elfutils: update to 0.192.

---

srcpkgs/iproute2/template

iproute2: update to 6.13.0.

---

srcpkgs/ffmpeg/patches/00001-v4l-config.patch
srcpkgs/ffmpeg/patches/00002-v4l-ioctl-musl.patch
srcpkgs/ffmpeg6/patches/00003-v4l-config.patch
srcpkgs/ffmpeg6/patches/00004-v4l-ioctl-musl.patch
srcpkgs/gst-plugins-good1/patches/musl-ioctl.patch
srcpkgs/v4l-utils/patches/musl-ioctl.patch
srcpkgs/v4l-utils/patches/sbin.patch
srcpkgs/v4l-utils/template

v4l-utils: update to 1.28.1.

---

srcpkgs/gnome-mahjongg/template

- armv7l
- armv6l-musl
- aarch64-musl

gnome-mahjongg: update to 48.0

---

srcpkgs/audit/template

audit: update to 4.0.3.

---

common/shlibs
srcpkgs/kodi/template
srcpkgs/libcdio/patches/gcc14.patch
srcpkgs/libcdio/template
srcpkgs/mpd/template
srcpkgs/python3-pycdio/template
srcpkgs/vcdimager/template

libcdio: update to 2.2.0, fix build with gcc14

---

srcpkgs/prosody/template

Crossbuilt on x86_64-glibc for aarch64-musl. Tested on a aarch64-musl
and runs as expected

prosody: update to 13.0.0.

---

srcpkgs/python3-attrs/template
srcpkgs/python3-coverage/template
srcpkgs/python3-fastjsonschema/template
srcpkgs/python3-isodate/template
srcpkgs/python3-jsonschema-path/template
srcpkgs/python3-jsonschema-specifications/template
srcpkgs/python3-lazy-object-proxy/template
srcpkgs/python3-openapi-core/template
srcpkgs/python3-openapi-schema-validator/template
srcpkgs/python3-pathable/template
srcpkgs/python3-py-cpuinfo/template
srcpkgs/python3-pytest-asyncio/template
srcpkgs/python3-pytest-benchmark/template
srcpkgs/python3-pytest-httpserver/template
srcpkgs/python3-referencing/template
srcpkgs/python3-responses/template
srcpkgs/python3-rpds-py/template

- **python3-py-cpuinfo: update to 9.0.0.**
- **python3-pytest-benchmark: update to 5.1.0.**
- **python3-fastjsonschema: update to 2.21.1.**
- **python3-attrs: update to 25.1.0.**
- **python3-rpds-py: update to 0.23.1.**
- **python3-referencing: update to 0.36.2.**
- **python3-jsonschema-specifications: update to 2024.10.1.**
- **python3-isodate: update to 0.7.2.**
- **python3-pytest-asyncio: update to 0.25.3.**
- **python3-coverage: update to 7.6.12.**
- **python3-pytest-httpserver: update to 1.1.2.**
- **python3-responses: update to 0.25.6.**
- **python3-pathable: update to 0.4.4.**
- **python3-jsonschema-path: update to 0.3.4.**
- **python3-lazy-object-proxy: update to 1.10.0.**
- **python3-openapi-schema-validator: update to 0.6.3.**
- **python3-openapi-core: update to 0.19.4.**
- I …

python updates (jsonschema, openapi-core, and many deps)

---

common/shlibs

it's `libgirepository-2.0.so.0`, not `libgrepository-2.0.so.0`

common/shlibs: fix typo

---

common/travis/check-install.sh

This allows for showing all install errors for a package at once, rather than having to check one at a time.
This also fixes displaying the error message (which currently doesn't happen due to `set -e`)
(I tested this with the glib update PR: https://github.com/void-linux/void-packages/actions/runs/14007226644/job/39222652926)

common/travis/check-install.sh: don't exit after install failure

---

srcpkgs/vala/template
srcpkgs/valadoc/template

vala{,doc}: update to 0.56.18

---

srcpkgs/at-spi2-core/template

at-spi2-core: update to 2.56.0

---

srcpkgs/lightsoff/template

lightsoff: update to 48.0

---

srcpkgs/asahi-firmware/template

It does not make sense to build this for all archs.

asahi-firmware: restrict arch

---

srcpkgs/alsa-ucm-conf-asahi/template
srcpkgs/asahi-audio/template
srcpkgs/triforce/template

I changed speakersafetyd service to run as non-root. This seems to work fine (as in, audio is fine, logs show no errors or warnings), but let's wait for comments from upstream before merging this. Also I patched it by hand for now. The rest are routine updates.

asahi audio

---

common/hooks/pre-pkg/03-rewrite-python-shebang.sh

Shebangs containing #!python are ignored currently, which causes a problem since newer versions of python3-setuptools generate this, so replace them with the proper shebang when encountered.
https://github.com/pypa/setuptools/issues/4863

hooks/pre-pkg/03-rewrite-python-shebang.sh: rewrite plain python shebang

---

srcpkgs/amp/template

Mostly to get rid of the longstanding build failure.

amp: update to 0.7.1

---

srcpkgs/SuiteSparse/template

- **SuiteSparse: update to 7.10.1.**
- ~~**octave: update to 9.4.0.**~~
~~There's an alternative update to octave-9.4.0 as part of #51891 (to enable hdf5 support for octave on cross).~~
Note that it's not necessary to recompile octave for the SuiteSparse update; I include it here mostly so the SuiteSparse update is also tested through octave.

SuiteSparse: update to 7.10.1

---

srcpkgs/libxcrypt/template

Also fix typo in maintainer email.

libxcrypt: update to 4.4.38

---

srcpkgs/newsboat/template

newsboat, update to 2.39.

---

srcpkgs/libcap/template

Currently, the bootsrap is broken for me on aarch64. This should fix it.
cc @sgn

libcap: fix bootstrap

---

srcpkgs/soju/files/soju/run
srcpkgs/soju/template

The default configuration file now contains
listen unix+admin://
which defaults to /run/soju/admin, the directory thus needs to exist.

soju: create /run/soju on startup

---

srcpkgs/wine/template

[ci-skip]
Upstream wine have added a dependency on git where it's now needed when running the patchinstall.py program that applies the wine staging patches to the wine source tree. This change adds git as a build dependency if the "staging" option is specified to xbps-src.
Tested with the following command
./xbps-src -o staging pkg wine
- i686

wine: Fix wine staging build

---

srcpkgs/mesa-demos/patches/disable-nonfree.patch
srcpkgs/mesa-demos/patches/mesa-demos-data-dir.patch
srcpkgs/mesa-demos/template

Continuation of: https://github.com/void-linux/void-packages/pull/42959
While most of the demos are under MIT or public domain, there are a few that are under a custom license that may be nonfree (which we are currently distributing): https://gitlab.freedesktop.org/mesa/demos/-/blob/mesa-demos-9.0.0/src/demos/dinoshade.c#L2-6
Fedora removes them: https://src.fedoraproject.org/rpms/mesa-demos/blob/rawhide/f/mesa-demos-8.5.0-legal.patch

mesa-demos: update to 9.0.0.

---

srcpkgs/gnome-builder/template
srcpkgs/gtksourceview5/template

gnome-bulider: update to 48.0.

---

srcpkgs/zellij/template

zellij: update to 0.42.2

---

srcpkgs/gnome-mahjongg/template

- armv7l
- armv6l-musl
- aarch64-musl

gnome-mahjongg: update to 48.1

---

srcpkgs/libnvidia-container/patches/fix-go1.24.patch
srcpkgs/libnvidia-container/template
srcpkgs/nvidia-container-toolkit/template

Alternative to #55088
Same: Fixes #55062, fixes the tests bin path.
Different: updates versions
Note on building nvidia-container-toolkit:
Local tests still (current 1.16.1_2 does this too) error out on creating mock test control devices if an Nvidia GPU is present in the system.
With tests disabled builds and runs fine.

nvidia-container-toolkit libnvidia-container fix and update to 1.17.5

---

srcpkgs/libdeflate/template

Void packages dynamically linked executables, but the libdeflate utilities are built with libdeflate itself statically linked by default, despite libdeflate.so.0 being provided in the same package

libdeflate: link utilities (libdeflate-gzip) to installed shared library

---

srcpkgs/python3-urwid/template

This update is required to fix `stig` and possibly other packages.

python3-urwid: update to 2.6.16, adopt

---

srcpkgs/android-file-transfer-linux/template

The new release fixes issue with recent Android (otherwise broken), and builds with qt6.
Edit: even though the package ships its own `libmpt-ng`, I had to install `libmtp` and add my user to `plugdev` group in order for this tool to work for non-root (the reason being that libmtp ships udev rules, while they don't).
cc @Vaelatern

android-file-transfer-linux: update to 4.4

---

common/xbps-src/shutils/build_dependencies.sh
srcpkgs/python3-jsonschema-specifications/template
srcpkgs/python3-jsonschema/template
srcpkgs/python3-referencing/template

- **shutils/build_dependencies.sh: non-recursive check**
- **python3-referencing: check circular dep**
- **python3-jsonschema-specifications: bump to test check cycle**
- **python3-jsonschema: bump to test check cycle**
There's too many build-check cycles and handling them is complicated
when updating simultaneously a few interdependent packages.
This PR makes it so enabling check on a package will not affect dependencies
that are built in the process.
For CI and for xbulk, this means that some packages could be built more than
once (at most twice) but every package will be checked exactly one time. But
only if there is a build-check cycle, since otherwise sort-dependencies will
find a good build order that avoids it.

[RFC] non-recursive check to break build-check cycles

---

srcpkgs/ksanecore6/template
srcpkgs/leptonica/template
srcpkgs/skanpage/template
srcpkgs/tesseract-ocr/template

I scanned a page in skanpage, saved it with OCR eng and equ, converted it to a png (tesseract-ocr doesn't have in-built INPUT pdf support) and ran tesseract-ocr on the image file. It produced text.
pdfsandwich, which is a wrapper around tesseract-ocr, works on pdfs.
EDIT 4/19/25: updated skanpage and ksanecore6 to 25.04.0 ([the former requires the latter in this version](https://github.com/KDE/skanpage/blob/86fcb50fab7d0a2a1d5da68e1301538706a7a4eb/CMakeLists.txt#L61))
CC: @Idesmi @Johnnynator 

tesseract-ocr: update to 5.5.0, leptonica: update to 1.85.0, skanpage and ksanecore6: update to 25.04.0

---

srcpkgs/leptonica/template

The -devel packages used to be pulled in by libwebp-devel until @Johnnynator cleaned this mess up in Aug 2024. leptonica didn't get a rebuild until now.
This fixes, for instance, errors produced by tesseract-ocr like:
```
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Error in pixReadStreamPng: function not present
Error in pixReadStream: png: no pix returned
Leptonica Error in pixRead: pix not read: img.png
Error during processing.
```

leptonica: add required image support

---

srcpkgs/asahi-base/files/tinyramfs-hook-asahi.init
srcpkgs/asahi-base/template

This lets tinyramfs use keyboard on mac mini to e.g. decrypt luks.
The reference dracut implementation in asahi-scripts does the same btw.

asahi-base: force load module in tinyramfs

---

srcpkgs/runit-void/files/09-apparmor.sh
srcpkgs/runit-void/template

Fixes: the existing script doesn't load apparmor profiles from symlinks, so eg. if you symlink to one of the /usr/share/apparmor/extra-profiles/, that will be silently skipped
This also doesn't rely on shell whitespace splitting (ot that there should be whitespace anywhere in these filenames anyway)

runit-void: load apparmor profiles from symlinks in /etc/apparmor.d

---

srcpkgs/mame/template

This includes an [upstream patch](https://github.com/Tencent/rapidjson/pull/719) for a rapidjson bug that causes some builds (including mame) to fail, and bumps mame version to the latest 0276.

mame: update to 0276

---

srcpkgs/tree-sitter/template

tree-sitter: update to 0.25.3

---

srcpkgs/cross-bpf-binutils/template
srcpkgs/cross-bpf-gcc/template
srcpkgs/dtrace-utils/patches/configure.patch
srcpkgs/dtrace-utils/template

This is WIP.
Issues to fix before merging:
- binutils needs to be at least 2.42 because of a PIE linking bug: 
https://sourceware.org/bugzilla/show_bug.cgi?id=31047
- bpf-binutils must be not newer than 2.41 unless we move bpf-gcc to 14.x

New package: dtrace-utils-2.0.2

---

srcpkgs/meld/template

I added the `desktop-file-utils` dependency, because this pkg's meson build system needs `update-desktop-database`.
I tested running `meld .` from within a git repository with modifications and everything worked OK.
- I built this PR locally for these architectures (crossbuilt, but it's python...):
- aarch64
- aarch64-musl

meld: update to 3.23.0

---

srcpkgs/libarchive/template

libarchive: update to 3.7.9

---

srcpkgs/dive/template

dive: update to 0.13.1

---

srcpkgs/python3-cachetools/template
srcpkgs/python3-filelock/template
srcpkgs/python3-platformdirs/template
srcpkgs/python3-virtualenv/template
srcpkgs/tox/template

- **python3-cachetools: update to 5.5.2.**
- **python3-filelock: update to 3.18.0.**
- **python3-platformdirs: update to 4.3.7.**
- **python3-virtualenv: update to 20.30.0.**
- **tox: update to 4.25.0.**

tox: update to 4.25.0 (and deps).

---

srcpkgs/python3-h11/template

This is missing to match the update of `python3-httpcore` to 1.0.9.
Running `pip check` gives
```
httpcore 1.0.9 has requirement h11>=0.16, but you have h11 0.14.0.
```
but the same information can be found using only `python3-build` as in:
```
$ python -c 'from build._util import check_dependency;print(*check_dependency("httpcore"),sep="\n")'
('httpcore', 'h11>=0.16')
```

python3-h11: update to 0.16.0.

---

srcpkgs/maddy/INSTALL
srcpkgs/maddy/files/maddy/run
srcpkgs/maddy/template

Also create /run/maddy required for maddy to run in the runit service
and set CAP_NET_BIND_SERVICE on the binary to allow listening on
privileged ports.
Cc: @the-maldridge
---
- x86_64 (cross)

maddy: update to 0.8.1.

---

srcpkgs/ibus/template

ibus: update to 1.5.32.

---

srcpkgs/rustup/template

rustup: update to 1.28.2

---

srcpkgs/cargo-auditable-bootstrap/template
srcpkgs/cargo-auditable/template

- **cargo-auditable-bootstrap: update to 0.6.7**
- **cargo-auditable: update to 0.6.7**

cargo-auditable: update to 0.6.7

---

srcpkgs/papirus-icon-theme/template

ePapirus(-Dark) theme removed upstream, use Papirus(-Dark) instead.

papirus-icon-theme: update to 20250501.

---

xbps-src

Document in usage that running check with -Q is not recursive,
and running check with -K is recursive.
This behaviour was implemented in #54633.

xbps-src: document -Q non-recursiveness

---

srcpkgs/openresolv/template

This fixes an important issue from 3.16.0 where only the last DNS nameserver would make it into /etc/resolv.conf (more [here](https://github.com/NetworkConfiguration/openresolv/issues/35))

openresolv: update to 3.16.2

---

srcpkgs/vscode/template

I get the error message
```
Error [ERR_WORKER_OUT_OF_MEMORY]: Worker terminated due to reaching memory limit: JS heap out of memory
```
probably due to my personal system being limited to 8GB of RAM.
__Update__: I had to change a few bits, but I finally fixed the build. It now requires 16GB at least (using swap works fine, but slows things down considerably).

vscode: update to 1.99.3

---

srcpkgs/mpv/patches/0.39.0-pipewire-1.4-fix.patch
srcpkgs/mpv/template
srcpkgs/pipewire/template

- I tested the changes in this PR: **briefly** (at least for the official 1.4 release, though I have been using the 1.3.x release candidates without any issues for about a month)
PipeWire 1.4 adds support for EBU R128 loudness normalization (via libebur128), so I've added that as a dependency. Should it be put behind a build option? I would have to make sure that it actually has a meson flag and isn't a hard dependency.

pipewire: update to 1.4.2

---

srcpkgs/gnome-keyring/template

gnome-keyring: update to 48.0

---

srcpkgs/gnome-color-manager/template

gnome-color-manager: update to 3.36.2

---

srcpkgs/decibels/template

it's a new official gnome app since version 48 (see #54783), a simple audio player.

New package: decibels-48.0

---

srcpkgs/adwaita-fonts/template

Replaces cantarell and adobe-source-code-pro in GNOME 48.

New package: adwaita-fonts-48.2.

---

srcpkgs/wluma/template

Automatic brightness adjustment based on screen contents and ALS.
https://github.com/maximbaz/wluma
#32485, #31431

New package: wluma-4.9.0

---

srcpkgs/Bonzomatic/patches/fix-wayland.patch
srcpkgs/Bonzomatic/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
---
This patch, placed alongside the template, fixes the issues that arise when enabling `-DBONZOMATIC_USE_SYSTEM_GLEW=ON` and `-DBONZOMATIC_USE_SYSTEM_GLFW=ON` to use the system libraries instead of the ones provided in the externals folder.
It addresses the GLEW initialization and screen size …

New package: Bonzomatic-2023.06.15

---

common/scripts/parse-py-metadata.py

hooks/pre-pkg/06-verify-python-deps: support alternative packages

---

srcpkgs/fuse-sshfs/template

fuse-sshfs: fix manpage generation while cross-compiling

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.54.0

---

srcpkgs/sbctl/template

This update adds the Microsoft 2023 Secure Boot Certificates. The current 2011 certificates are set to expire next year.

sbctl: update to 0.17.

---

srcpkgs/spotify-player/template

Seems the [aws-lc-sys](https://github.com/aws/aws-lc-rs/issues/632) issue was fixed upstream, so removing the workaround that was introduced before.

spotify-player: update to 0.20.5

---

srcpkgs/go/template

- aarch64
- aarch64-musl
- i686
- i686-musl
- armv7l
- armv6l

go: update to 1.24.3

---

common/shlibs
srcpkgs/gtk4-layer-shell-devel
srcpkgs/gtk4-layer-shell/patches/remove-failing-tests.patch
srcpkgs/gtk4-layer-shell/template
srcpkgs/walker/template

- x86_64-musl
- i686
Closes #43810 with 0afe89ff2ad04971dd8084fa49a7aa8d7a8206ca

New package: walker-0.12.21, gtk4-layer-shell-1.1.1

---

srcpkgs/gdk-pixbuf/template

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=285185
https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/merge_requests/167/diffs
Claws-mail stopped displaying icons after the most recent update of gdk-pixbuf; hence the additional build flags. Other GTK packages could potentially be affected, too.

gdk-pixbuf: bring back support for xpm, gif and other loaders

---

srcpkgs/swirc/template

swirc: update to 3.5.5.

---

srcpkgs/nv-codec-headers/template
srcpkgs/obs/template

requires an additional version bump to `nv-codec-headers` to include a missing enum.

obs: ENABLE_NVENC under `nvenc` option for x86_64

---

srcpkgs/xdg-desktop-portal/template

@Duncaen
required by gnome-48 (https://github.com/void-linux/void-packages/pull/54783)

xdg-desktop-portal: update to 1.20.3

---

srcpkgs/incus/template

- I tested the changes in this PR: **YES**:
- checked with `./xbps-src -Q pkg incus`
- installed on a system with an incus-managed container and VM
- aarch64-musl
- armv7l
- armv6l-musl
With qemu 10.x, incus 6.9 can no longer launch VMs because of a removed (previously deprecated) command line option. Incus 6.12 includes a fix: https://github.com/lxc/incus/pull/1871
This is my first PR for void-packages. I took the liberty of updating this myself because it was broken on my system. If there's anything else I need to do, please let me know.

incus: update to 6.12.0.

---

srcpkgs/walker/template

walker: update to 0.12.22.

---

srcpkgs/dnsrecon/patches/python3-compat.patch
srcpkgs/dnsrecon/template
srcpkgs/python3-dnsrecon

Renaming this to 'dnsrecon' due to the fact that it's meant to be used as a command line tool, similar to other programs run from command line (i.e. yt-dlp) that also happen to be python packages. Hoping I did all the rname steps correctly.
Fixing bugs I encountered from running rare switches of this program, that are from the git master branch.

python3-dnsrecon: rename to dnsrecon, fix bugs.

---

srcpkgs/hyperrogue/template

This doesn't address #55301, the issue reproduces, but I haven't found a reliable fix yet.

hyperrogue: update to 13.0y

---

srcpkgs/podman-compose/template

podman-compose stack of 2 containers: mosquitto & zigbee2mqtt (with a passed-in USB zigbee dongle)
with podman 5.5.0 (as of pr #55337)

podman-compose: update to 1.4.0.

---

srcpkgs/tree-sitter/template

tree-sitter: update to 0.25.5

---

srcpkgs/python3-nethsm/template

This minor update satisfies python3-pynitrokey's dependency on "nethsm >=1.4.0, <2" for users of Nitrokey NetHSM hardware.
https://github.com/Nitrokey/pynitrokey/commit/2b067ae48f68b8f6b0e249a4c6a4fd6be769d2c9

python3-nethsm: update to 1.4.0

---

srcpkgs/showtime/template

This is a new official video player for Gnome, which replaces Totem.

New package: showtime-48.1

---

srcpkgs/kompose/template

Kompose is a conversion tool for Docker Compose to container orchestrators such as Kubernetes (or OpenShift). 
- https://github.com/kubernetes/kompose
- https://kompose.io/
Closes #27231 
- x86_64-musl

New package: kompose-1.36.0

---

srcpkgs/better-control/template

New package: better-control-6.11.7

---

srcpkgs/gearlever/template

New package: gearlever-3.2.2

---

srcpkgs/lazydocker/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

lazydocker: update to 0.24.1.

---

srcpkgs/xiphos/patches/build-without-uuidgen.patch
srcpkgs/xiphos/patches/https-by-default.patch
srcpkgs/xiphos/template

Based on the template provided by @jonpikum at
https://github.com/void-linux/void-packages/issues/50026#issuecomment-2766343046 . Includes the patch from https://gitlab.archlinux.org/archlinux/packaging/packages/xiphos/-/blob/main/https-by-default.patch .
Fixes: #50026

New package: xiphos-4.3.1

---

srcpkgs/tuxedo-yt6801/template

Built for kernels 6.6 and 6.10, 6.12–6.14; running on 6.14.8

tuxedo-yt6801: update to 1.0.29tux1

---

srcpkgs/keychain/INSTALL.msg
srcpkgs/keychain/template

NOTE: I don't know if _hostmakedepends="perl"_  is the best solution. The problem is that keychain requires pod2man to generate the manual now, as it does not seem to come bundled anymore in the tar archive (or maybe im just a noob).

keychain: update to 2.9.5

---

srcpkgs/Bear/template

- aarch64
- armv7l
- armv6l
- i686
- Update Bear to version 3.1.6
- Updated checksum
- Adjusted build to work with Bear's CMake superbuild pattern
- No upstream patching required; final install paths are clean
- Package builds and runs correctly

Bear: update to 3.1.6.

---

srcpkgs/python3-hidapi/template

I tested it specifically with Nitrokey devices in mind. After updating to `python3-hidapi 0.14.0.post4` and rebooting my computer I'm still able to access hidraw devices as a non-root user. Non-elogind users belonging to _plugdev_ should also be able to access such devices:
```
$ ls -la /dev/hidraw*
crw-rw----+ 1 root plugdev 239, 0 May 31 16:31 /dev/hidraw0
crw-------  1 root root    239, 1 May 31 16:31 /dev/hidraw1
crw-------  1 root root    239, 2 May 31 16:31 /dev/hidraw2
crw-------  1 root root    239, 3 May 31 16:31 /dev/hidraw3
crw-------  1 root root    239, 4 May 31 16:31 /dev/hidraw4
crw-------  1 root root    239, 5 May 31 16:31 /dev/hidraw5
crw-------  1 root root    239, 6 May 31 16:31 /dev/hidraw6
crw-------  1 root root    239, 7 …
```

python3-hidapi: update to 0.14.0.post4, switch backend to libusb

---

srcpkgs/rmpc/template

- x86_64-musl
- i686
- aarch64-musl
- aarch64
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

New package: rmpc-0.8.0

---

srcpkgs/neovide/template

Closes #43688
- x86_64-musl
- aarch64
- aarch64-musl
Currently figuring out how to get aarch64{,"-musl"} to build.

New package: neovide-0.15.0

---

srcpkgs/podman/template

- x86_64-musl
- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

podman: update to 5.5.0

---

srcpkgs/lz4/template

- aarch64-musl
- aarch64
- armv5tel-musl
- armv5tel
- armv6l-musl
- armv6l
- armv7l-musl
- armv7l
- i686-musl
- i686
- mips-musl
- mipsel-musl
- mipselhf-musl
- mipshf-musl
- ppc-musl
- ppc
- ppc64-musl
- ppc64
- ppc64le-musl
- ppc64le
- x86_64-musl
I had [#55155](https://github.com/void-linux/void-packages/pull/55155), and I seem to have done something incorrectly during my force push, and the pull request became closed. I understand from the contributing document that this is unwanted behavior, so for that I sincerely apologize. All suggested changes from 55155 are present in this commit. Again, …

Lz4: update to 1.10.0

---

srcpkgs/gnome-boxes/template

gnome-boxes: update to 48.0

---

srcpkgs/gnome-clocks/template

gnome-clocks: update to 48.0

---

srcpkgs/gnome-font-viewer/template

gnome-font-viewer: update to 48.0

---

srcpkgs/gnome-backgrounds/template

gnome-backgrounds: update to 48.0

---

srcpkgs/supersonic-desktop/patches/println-to-printf.patch
srcpkgs/supersonic-desktop/template

Resolves #53617 
- I tested the changes in this PR: **NO**(t yet, i can get to after the holidays)
@tommyalatalo Feel free to test, if you are able
Might be missing runtime dependencies.

New package: supersonic-desktop-0.15.2

---

srcpkgs/asahi-base/files/tinyramfs-hook-asahi.init
srcpkgs/asahi-base/template

No need to force load module and taint kernel; also, reorder maintainers, so that it appears in void-updates at the right place.

asahi-base: no need to force load module

---

srcpkgs/tuxedo-drivers/template

Built for kernels 6.1, 6.3–6.14; running on 6.14.6
Note: Build fails for 5.* (last working version is tuxedo-drivers-4.12.2)

tuxedo-drivers: update to 4.13.1

---

srcpkgs/praat/template

praat: update to 4.6.34

---

srcpkgs/opus/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
---
This update incorporates advanced features that enhance real-time audio quality, redundancy, and overall codec flexibility. For more details, see the [Opus 1.5 Demo](https://opus-codec.org/demo/opus-1.5/).
- **Deep Packet Loss Concealment (Deep-PLC):**  
Utilizes neural networks to reconstruct audio during packet loss. Enabled via `--enable-deep-plc`
- **Deep Redundancy (DRED):**  
Improves robustness with additional error correction. Enabled via …

opus: update to 1.5.2, adopt.

---

srcpkgs/virtualbox-ose/template

Support linux-6.15 and linux-6.16-rc0, no longer depends on libIDL.

virtualbox-ose: update to 7.1.10.

---

srcpkgs/biblioteq/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

biblioteq: update to 2025.05.26.

---

srcpkgs/gtest/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
---
Tested the update of the package using [Cockatrice PR#54508](https://github.com/void-linux/void-packages/pull/54508) compilation. Everything builds and works as expected.

gtest: update to 1.17.0.

---

srcpkgs/python3-peewee/template

Tested using the following code:
```
#!/usr/bin/python
import peewee
import datetime
db = peewee.SqliteDatabase('test.db')
class Note(peewee.Model):
text = peewee.CharField()
created = peewee.DateField(default=datetime.date.today)
class Meta:
database = db
db_table = 'notes'
Note.create_table()
note1 = Note.create(text='Went to the cinema')
note1.save()
note2 = Note.create(text='Exercised in the morning',
created=datetime.date(2018, 10, 20))
note2.save()
note3 = Note.create(text='Worked in the garden',
created=datetime.date(2018, 10, 22))
note3.save()
note4 = Note.create(text='Listened to music')
note4.save()
data = [
{ 'text': 'Tai chi in the morning', 'created': datetime.date(2018, 10, 20) },
{ 'text': 'Visited friend', 'created': …
```

python3-peewee: update to 3.18.1.

---

srcpkgs/gnome-nibbles/template

- armv7l
- armv6l-musl
- aarch64-musl

gnome-nibbles: update to 4.2.1

---

srcpkgs/shadowsocks-rust/files/shadowsocks-rust-client/run
srcpkgs/shadowsocks-rust/files/shadowsocks-rust-server/run
srcpkgs/shadowsocks-rust/template

- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): **YES**: system, compiled
Both new and old, this is the currently actively developed and maintained port of shadowsocks. Currently void provides the libev version, which received 1 commit in 2.5 years and hasn't had a release for nearly 4.5.
A few things I'd want to ask for guidance on:
1. Current template is modeled closely after the libev one, but considering that shadowsocks is commonly used with binary plugins these days, running the service as separate user requires adding the capabilities to plugins similar to how it's done with shadowsocks's binaries, i.e. `setcap cap_net_bind_service+ep …

New package: shadowsocks-rust-1.23.2

---

srcpkgs/puddletag/template
srcpkgs/puddletag/update

In-repo release is broken due to imghdr removed from python3.13, upstream patched the issue
Takeover as maintainer, as @progrestian 's last activity was 1.5 years ago and puddletag is their only contribution to void repos
Added update script
Dependency checking hook wants PyQt5-Qt5 but that's just Qt5 libs which we already include in python3-PyQt5, so ignored that warning. Applied others.
- I built this PR locally for these architectures as cross:
- aarch64-musl
- aarch64
- armv6l-musl
- armv6l
- armv7l-musl
- armv7l
- i686
- x86_64-musl

puddletag: update to 2.4.0

---

srcpkgs/bup/template

This update resolves possible missing data issues; details at https://github.com/bup/bup/blob/main/note/0.33.5-from-0.33.4.md and https://bup.github.io/issue/missing-objects.html.
Please know I'm new to GitHub, so it's very possible something here is incorrect.

bup: update to 0.33.7

---

srcpkgs/vale/template

vale: update to 3.10.0.

---

srcpkgs/python3-pulsectl-asyncio/template

python3-pulsectl-asyncio: update to 1.2.2.

---

srcpkgs/remote-touchpad/template

remote-touchpad: update to 1.5.0

---

srcpkgs/dnscrypt-proxy/template

dnscrypt-proxy: update to 2.1.8.

---

srcpkgs/libgbinder/template
srcpkgs/waydroid/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
---
This PR updates the Waydroid package in Void Linux. I tested it with a fresh installation, and everything seems to be working correctly. Additionally, I updated the libgbinder package, which is used by Waydroid.

waydroid: update to 1.5.2. (libgbinder 1.1.42.)

---

common/shlibs
srcpkgs/libgensio-devel
srcpkgs/libgensio/template
srcpkgs/ser2net/template

Redirected a USB-serial adapter, connected to a HW serial console, to a
local tcp port, and used nc to interact with it successfully.
This is serial-over-LAN with any hardware capable of serial & network (i.e.: without expensive "real" BMC HW).
This should also make possible to redirect a serial port from a zigbee USB adapter, but I've not tested that yet.
Test suites are disabled globally, because they depend on parts not built, without checks for feature availabilty (or that's how I interpreted the results I saw)
Not completely sure about the licenses, I put a `AND` in libgensio to appease pkg linting...
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-r …

New packages: ser2net & libgensio

---

srcpkgs/fooyin/patches/fix-cmake-sndfile.patch
srcpkgs/fooyin/template

- I tried building for other architectures such as armv6l, but couldn't get past this error:
```
CMake Error at cmake/modules/FindSndFile.cmake:33 (file):
file STRINGS file "/usr/include/sndfile.h" cannot be read.
```
You can also see the [failure in CI](https://github.com/void-linux/void-packages/actions/runs/13873851395/job/38823716818?pr=54695).
`libsndfile-devel` is specified in `makedepends`, so I'm not sure why that happens.
This is based on the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fooyin …

New package: fooyin-0.8.1

---

srcpkgs/minijail/patches/ppc.patch
srcpkgs/minijail/template

Updates minijail to the latest released tag. As for testing, I'm currently using this quite [extensively](https://codeberg.org/gruf/dotfiles/src/branch/main/system/etc/sv) (on x86_64) myself without any issues.
The patch change was a very simple case of they changed the comments around the changed code, which needed updating. Zero logic changes.

minijail: update to v2024.05.22

---

srcpkgs/jd/template

jd: update to 2.1.2.

---

srcpkgs/Dwarf-Therapist/template
srcpkgs/dwarffortress/files/dwarffortress
srcpkgs/dwarffortress/template

---
**Summary of Changes:**  
The `dwarffortress` package required updates due to changes in its versioning system and file structure starting from version `0.47.05`. Additionally, I updated the `dwarftherapist` package, which depends on `dwarffortress`. Below are the details of the changes:  
1. **Dwarffortress Package Updates:**  
- **Versioning Adjustments:**  
- Simplified version handling to align with the new tagging system.  
- Updated URLs from `http` to `https` for security.  
- **Installation Adjustments:**  
- Removed the now-unnecessary `post_extract` function.  
- Updated `do_install` to ensure compliance with the new file structure and installation standards.  
- …

dwarffortress: update to 51.11, adopt; Dwarf-Therapist: update to 42.1.13, adopt.

---

srcpkgs/qbittorrent/template

qbittorrent: update to 5.0.5

---

srcpkgs/OpenLP/template

OpenLP: update to 3.1.7.

---

srcpkgs/smem/template

smem: conflicts with cfitsio

---

common/xbps-src/shutils/update_check.sh

This one catches tags of the form `<pkgname>-v<major>.<minor>.<patch>` which would get through the previous one. And possibly some other cursed patterns. But maybe there's some unintended side effects. I did check it against quite a few packages but GH sources are far too many to do an exhaustive testing.

xbps-src: improve update-check pattern for GitHub

---

srcpkgs/gnome-network-displays/template

New package: gnome-network-displays-0.96.0

---

srcpkgs/rage/template

[rage](https://github.com/str4d/rage) is:
> A simple, secure and modern file encryption tool (and Rust library) with small explicit keys, no config options, and UNIX-style composability. 
It is also a rust implementation of [age](https://github.com/FiloSottile/age).
---

New package: rage-0.10.0

---

srcpkgs/pizauth/template

This is a command-line OAuth2 authentication daemon that could be a nice alternative to `mutt_oauth2.py`.
- I tested the changes in this PR: tested with google and microsoft, as well as my user dinit service at https://github.com/dkwo/dotfiles/tree/master/private_dot_config/private_dinit.d
- This new package conforms to the [package requirements](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md#package-requirements): yes
- I built this PR locally for my native architectures, `x86_64-glibc` and `aarch64-glibc`

New package: pizauth

---

srcpkgs/tarlz/template

- I tested the changes in this PR: **In progress**
From the [tarlz homepage](https://www.nongnu.org/lzip/tarlz.html): "Tarlz creates tar archives using a simplified and safer variant of the POSIX pax format compressed in lzip format, keeping the alignment between tar members and lzip members. The resulting multimember tar.lz archive is fully backward compatible with standard tar tools like GNU tar, which treat it like any other tar.lz archive."
Keeping the alignment has advantages, which the webpage explains nicely.
Also from the homepage: "Tarlz does not understand other tar formats like gnu, oldgnu, star or v7. The command …

New package: tarlz-0.27.1

---

srcpkgs/cava/patches/iniparser-pkgconfig.patch
srcpkgs/cava/template

- aarch64
- armv7l
- armv6l
- i686
- update cava to version 0.10.4
- update checksum
- patch to force pkg-config for iniparser

cava: update to 0.10.4.

---

srcpkgs/python3-pydot/template

- Pydot is a useful package building on graphviz and is required by the `gem5` simulator to generate visual output
- I built this PR locally for my native architecture, x86_glibc

New package: python3-pydot-4.0.0

---

srcpkgs/bibiman/template

Minor bugfix regarding expansion of tilde into home dir, which was broken after the last release two days ago.

bibiman: update to 0.12.3

---

srcpkgs/cmark/template

- I built this PR locally for my native architecture, (x86_64-glibx)
- aarch64
- armv7l
- armv6l
- i686
Updated version and checksum. Modify `pre_configure()` to fix SONAME version. Remove handling of `*.a` static library files during installation as upstream no longer builds static library files by default. Added CMake `BUILD_SHARED_LIBS` flag to control shared/static builds as per CMake recommendations, aligns with upstream changes. Added conflict with `python3-commonmark`.

cmark: update to 0.31.1.

---

srcpkgs/llvm19/template

llvm19: fix libz3 link

---

srcpkgs/python3/patches/135332.patch
srcpkgs/python3/template

Issue: https://github.com/python/cpython/issues/135326
PR: https://github.com/python/cpython/pull/135332
@ahesford
The regression causes problems in sagemath, e.g.:
```
$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 10.6, Release Date: 2025-03-31                    │
│ Using Python 3.13.4. Type "help()" for help.                       │
└────────────────────────────────────────────────────────────────────┘
sage: import random ; r = random.Random()
sage: r.getrandbits(20)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
TypeError: an integer is required
```

python3: fix a regression

---

srcpkgs/rust-bacon/template

[bacon](https://dystroy.org/bacon/) is a background rust code checker designed for minimal interaction so that you can just let it run, alongside your editor, and be notified of warnings, errors, or test failures in your Rust code.

New package: rust-bacon-3.15.0

---

srcpkgs/checkbashisms/template

- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

checkbashisms: update to 2.25.14, adopt

---

srcpkgs/cliflux/template

- I built this PR locally for my native architecture, (x84_64-glibc)

cliflux: update to 1.8.0.

---

srcpkgs/gradle/template

- I built this PR locally for my native architecture, x86_64-glibc (cross with -musl masterdir)
It appears that starting with gradle 8.12, musl builds no longer work: see https://github.com/gradle/gradle/issues/31939.
To reproduce:
```
$ ./xbps-src binary-bootstrap -A x86_64-musl
$ ./xbps-src pkg Apktool -A x86_64-musl
```
For more context, see https://github.com/void-linux/void-packages/pull/51361.

gradle: revert to 8.11.1

---

srcpkgs/libjpeg-turbo/template

libjpeg-turbo: update to 3.1.1.

---

srcpkgs/fluidsynth/template

- Tested out FluidSynth's functionality by running `fluidsynth -a pulseaudio gm.sf2` and then tested out FluidSynth's general MIDI functionality in a game, which relied on a general MIDI synthesizer to provide MIDI playback for its music. The audio worked in the game via FluidSynth, with no issues or regressions as far as I could tell.
- Played a MIDI file with FluidSynth, which seemingly went well.

fluidsynth: update to 2.4.6.

---

srcpkgs/dnsmasq/template

Changelog: https://thekelleys.org.uk/dnsmasq/CHANGELOG

dnsmasq: update to 2.91

---

srcpkgs/sway/template

- I've been personally using Sway 1.11 on my system with this template for a while now, and it works fine. Haven't noticed any issues or regressions.

sway: update to 1.11.

---

srcpkgs/podman-tui/template

- x86_64-musl
- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

podman-tui: update to 1.6.1

---

srcpkgs/podman/template

- x86_64-musl
- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

podman: update to 5.5.1

---

srcpkgs/gnome-text-editor/template

gnome-text-editor: update to 48.3

---

srcpkgs/syncplay/template

Update to latest, add missing dependency required to support TLS connections to SyncPlay servers, and update my maintainer email

syncplay: update to 1.7.4, support TLS

---

srcpkgs/Komikku/template
srcpkgs/python3-modern_colorthief/template

Added `python3-modern_colorthief`.
- crossbuilt on:
- armv7l-musl

Komikku: update to 1.79.1.

---

srcpkgs/persepolis/files/README.voidlinux
srcpkgs/persepolis/template

- I tested the changes in this PR: **briefly** - downloaded a video, tested which dependencies were needed at runtime (because no packager can agree)
- i686 (cross)
The project has changed dramatically since 2019, including changing to meson build system. 
Honestly not sure if it's still a relevant package, but it needed to be done to remove `youtube-dl` deps. Should also count towards #46170

persepolis: update to 5.1.1

---

srcpkgs/ifupdown-ng/patches/fix-tests.patch
srcpkgs/ifupdown-ng/template

- aarch64-musl [crossbuild]
- armv7l [crossbuild]
- armv6l-musl [crossbuild]
NOTES: 
- ifupdown-ng is a network device manager which is backwards compatible with traditional ifup and ifdown as used on Debian and Alpine systems.
- Contemporary network configuration for Linux (by Aaron A. Glenn & Maximilian Wilhelm) - https://www.youtube.com/watch?v=m7dfP65JfPU
- Is there interest in having 15-ifupdown.sh file as well? (just like in the ifupdown package)
- Check tests …

New package: ifupdown-ng-0.12.1

---

srcpkgs/virtiofsd/template

- I tested the changes in this PR: **YES** (Windows 11 guest)

virtiofsd: update to 1.13.2

---

srcpkgs/tuxedo-drivers/template

- Built for kernels 6.1, 6.3–6.15; running on 6.15.2

tuxedo-drivers: update to 4.14.0

---

srcpkgs/qrencode/template

tarballs no longer accessible on their personal website, source releases don't include configure scripts.

qrencode: fix distfiles.

---

srcpkgs/tuxedo-yt6801/template

fixes build with kernel 6.15
- built for kernels 6.6, 6.12, 6.14, 6.15, running on 6.15.2
@suturar

tuxedo-yt6801: update to 1.0.30tux1

---

srcpkgs/iso-codes/template

4.17.0 sources no longer available

iso-codes: update to 4.18.0.

---

srcpkgs/kcachegrind/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

kcachegrind: update to 25.04.2.

---

srcpkgs/perl-CGI/template

reverts 4.68 which breaks backward compatibility
- x86_64-musl
- i686

perl-CGI: update to 4.69

---

srcpkgs/android-tools/patches/armhf.patch
srcpkgs/android-tools/template

This is the minimum version that works with modern Android.
The next version requires more extensive changes, as done in #55099

android-tools: update to 35.0.1

---

srcpkgs/FeatherPad/template

- aarch64-musl
- armv7l
- armv6l
- i686
Update version and checksum. Update dependencies from `qt5` to `qt6`.

FeatherPad: update to 1.6.2.

---

srcpkgs/video-compare/template

This adds a new package for https://github.com/pixop/video-compare. I use it for easily comparing differences between encoded videos.
I'm not sure if the `pre_install` step or if my use of `make_use_env` is appropriate, but it works fine like this.
- x86_64-musl

New package: video-compare-20250420

---

srcpkgs/spice-protocol/template
srcpkgs/spice/template

- I built this PR locally for my native architecture, (x86_64-gblic)

spice: update to 0.16.0

---

srcpkgs/dav1d/template

- `mpv` decoding with `libdav1d` (at least according to the on-screen info script)
- Opening `.avif` files with `mpv`
- Opening `.avif` or `.svg` files with `swayimg`
- Rendering `.avif` or .`svg` files with `chafa` inside `foot` terminal

dav1d: update to 1.5.1

---

srcpkgs/SoapyAirspy/template
srcpkgs/SoapyHackRF/template

- aarch64
- armv7l
- armv6l
- i686
Update versions and checksums for Soapy SDR plugins: `SoapyHackRF` and `SoapyAirspy`

Soapy SDR plugins update

---

srcpkgs/rockpro64-uboot/files/README.voidlinux
srcpkgs/rockpro64-uboot/template

I tested the U-Boot install methods that I documented in the README.voidlinux file.
- Writing U-Boot to eMMC using the `/usr/lib/rockpro64-uboot/u-boot-rockchip.bin` image and booting from eMMC.
- Writing U-Boot to SPI using the `/usr/lib/rockpro64-uboot/u-boot-rockchip-spi.bin` image and booting from USB.

rockpro64-uboot: update to 2025.04.

---

common/shlibs
srcpkgs/nanomsg/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
---
[Criterion](https://github.com/void-linux/void-packages/pull/50109) builds and works fine with nanomsg 1.1.5, but its meson wrap expects version 1.2.
Updating ensures compatibility and avoids potential issues, especially since there was a SONAME change in the library. This was tested to ensure Criterion builds correctly with the updated version.

nanomsg: update to 1.2.

---

srcpkgs/khal/template

I am not using the package anymore and trying to update it wasn't easy, as it required new dependencies and versions.

khal: orphan [ci skip]

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.58.0.

---

srcpkgs/xorg-server/template

Looks like .18 has some security fixes, testing it now...
Version 21.1.17 was running OK, still running OK with 21.1.18.
- armv7hf (crossbuild)

xorg-server: update to 21.1.18.

---

srcpkgs/tuxedo-drivers/template

- Built for kernels 6.1, 6.3–6.15; running on 6.15.2

tuxedo-drivers: update to 4.14.1

---

srcpkgs/perl-Number-Format/template

v1.75 has been broken since Perl 5.38
- x86_64-musl
- i686
Tests on *-musl disabled because radix character and thousand separator are not localizable, yet:
```
t/locale.t ........... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/12 subtests 
```

perl-Number-Format: update to 1.76

---

srcpkgs/firejail/patches/musl.patch
srcpkgs/firejail/patches/profiles-fix-xkeyboard-config.patch
srcpkgs/firejail/template

https://github.com/netblue30/firejail/issues/6773
- Prior to applying this patch`firefox` and `zathura` wouldn't launch after the recent `xkeyboard-config-2.45_1` update
cc @Duncaen

firejail: add patch to fix xkeyboard config in profiles

---

srcpkgs/libmpeg2/patches/global-symbol-test.patch
srcpkgs/libmpeg2/template

~~Internals are identical to those of the original source (found on archive.org), according to diff -r~~
EDIT: switched to debian-hosted distfiles, hash matches previous version. Added patch of test from [gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/libmpeg2/files/libmpeg2-0.5.1-global-symbol-test.patch)

libmpeg2: fix distfiles.

---

common/shlibs
srcpkgs/ImageMagick/template
srcpkgs/cutter/template
srcpkgs/edb-debugger/template
srcpkgs/graphviz/template
srcpkgs/valadoc/template

graphviz: update to 13.0.0.

---

srcpkgs/libblockdev/template

[CVE-2025-6019](https://github.com/advisories/GHSA-mpgj-hch9-5rvx)

libblockdev: update to 3.3.1.

---

srcpkgs/python3-pytest-httpbin/template
srcpkgs/python3-requests/template

pytest-httpbin fixes tests in requests (see https://github.com/psf/requests/blob/91a3eabd3dcc4d7f36dd8249e4777a90ef9b4305/requirements-dev.txt#L4)

python3-requests: update to 2.32.4, python3-pytest-httpbin: update to 2.1.0

---

srcpkgs/typos-lsp/template

cc @Bnyro
Turns out this doesn't need the `typos` tool separately, since it pulls in the necessary typos crates instead.

typos-lsp: update to 0.1.39

---

srcpkgs/jinja-lsp/template

jinja-lsp: update to 0.1.89.

---

srcpkgs/lxqt-wayland-session/template

tested with labwc (default), kwin_wayland, wayfire and niri
It may also be nice to have this package depend on labwc, since that's the fallback compositor the session uses, but it's technically also possible to configure a default compositor from the terminal/tty

New Package: lxqt-wayland-session

---

srcpkgs/kubernetes/template

- I built this PR locally for my native architecture: **x86_64 (libc)**
I got the same error as with [`kubernetes-kind`](https://github.com/void-linux/void-packages/pull/55987). It fails locally using `./xbps-src pkg -Q kubernetes`, but it builds fine with `./xbps-src pkg kubernetes` and runs correctly after `xi kubectl`.

kubernetes: update to 1.33.2.

---

srcpkgs/siril/patches/musl.patch
srcpkgs/siril/template

- **aarch64-musl**
- **x86_64-musl**
Saw a [opencv PR](https://github.com/void-linux/void-packages/pull/55041), realized this is not building at all now with musl errors (old and new version both need the patch).
https://gitlab.com/ncopa/siril/-/blob/7f09478f4522b65b476c788a696159e5a4974286/src/io/avi_pipp/pipp_utf8.h
if there's a better way to tell meson to link execinfo for musl lmk

siril: update to 1.2.6

---

srcpkgs/hatch-vcs/template
srcpkgs/python3-cachetools/template
srcpkgs/python3-coverage/template
srcpkgs/python3-mock/template
srcpkgs/python3-platformdirs/template
srcpkgs/python3-pluggy/template
srcpkgs/python3-pyproject-api/template
srcpkgs/python3-pytest-asyncio/template
srcpkgs/python3-pytest-cov/template
srcpkgs/python3-pytest-mock/template
srcpkgs/python3-pytest-timeout/template
srcpkgs/python3-virtualenv/template
srcpkgs/tox/template

- **python3-coverage: update to 7.9.1.**
- **python3-mock: update to 5.2.0.**
- **python3-pytest-asyncio: update to 1.0.0.**
- **python3-pytest-cov: update to 6.2.1.**
- **python3-pytest-mock: update to 3.14.1.**
- **python3-pytest-timeout: update to 2.4.0.**
- **hatch-vcs: update to 0.5.0.**
- **python3-cachetools: update to 6.1.0.**
- **python3-platformdirs: update to 4.3.8.**
- **python3-pluggy: update to 1.6.0.**
- **python3-pyproject-api: update to 1.9.1.**
- **python3-virtualenv: update to 20.31.2.**
- **tox: update to 4.27.0.**

tox: update to 4.27.0, and deps

---

srcpkgs/coturn/INSTALL
srcpkgs/coturn/template
srcpkgs/prosody/INSTALL
srcpkgs/prosody/template

- **coturn: restrict access to the configuration file**
- **prosody: restrict access to the configuration file**

coturn, prosody: restrict access to configuration files

---

srcpkgs/libssh/template

libssh: update to 0.11.2.

---

srcpkgs/waydroid/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl

waydroid: update to 1.5.4.

---

srcpkgs/btop/template

Ran the new btop during the aarch64 crossbuild (and a few other builds),
inside tmux, with (de-)zooming on a pane, with a few mouse clicks.
Also in a bare st terminal.

btop: update to 1.4.4.

---

srcpkgs/ZMusic/template
srcpkgs/gzdoom/patches/pk3location.patch
srcpkgs/gzdoom/template

- Updated `pk3location.patch` because it failed to patch with GZDoom 4.14.2. The patch should still make the same changes.
- I included ZMusic in the same PR because it was updated with GZDoom 4.14.

gzdoom: update to 4.14.2, ZMusic: update to 1.1.14

---

srcpkgs/libvpl/template

Adopting per maldridge's comment. https://github.com/void-linux/void-packages/pull/51496#issuecomment-3013921018
libvpl 2.15 seemed to remove the examples? I made an issue to ask if it was a mistake or intended, but I highly doubt anyone who cares will be heartbroken that they have to build the binaries manually.

libvpl: update to 2.15, adopt

---

srcpkgs/pcsc-ccid/template

pcsc-ccid: update to 1.6.2.

---

srcpkgs/openvpn/template

- x86_64-musl
- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

openvpn: update to 2.6.14, adopt

---

srcpkgs/SPIRV-Headers/template
srcpkgs/SPIRV-Headers/update
srcpkgs/SPIRV-LLVM-Translator/template
srcpkgs/SPIRV-LLVM-Translator19/template
srcpkgs/SPIRV-Tools/template
srcpkgs/SPIRV-Tools/update
srcpkgs/Vulkan-Headers/template
srcpkgs/Vulkan-Headers/update
srcpkgs/Vulkan-Tools/template
srcpkgs/Vulkan-Tools/update
srcpkgs/Vulkan-Utility-Libraries/template
srcpkgs/Vulkan-Utility-Libraries/update
srcpkgs/Vulkan-ValidationLayers/template
srcpkgs/Vulkan-ValidationLayers/update
srcpkgs/vulkan-loader/template
srcpkgs/vulkan-loader/update
srcpkgs/zeux-volk/template
srcpkgs/zeux-volk/update

- aarch64
- armv7l
- armv6l
- i686
- Updated packages to `Vulkan SDK 1.4.313.0.`
- Updated/created `update` pattern for automated update checks.

Vulkan/SPIR-V packages update to 1.4.313.0.

---

srcpkgs/mediastreamer/template

upstream has [deprecated it][1] and considers it [unmaintained][2]. only compatible with ffmpeg4.
cc maintainer @Johnnynator
[1]: https://gitlab.linphone.org/BC/public/mediastreamer2/-/commit/8261f82741f454d5b523f224aec3c66ee97e2fdc
[2]: https://gitlab.linphone.org/BC/public/mediastreamer2/-/commit/a455e96189eda038f4de51a8a0b874215ca86226

mediastreamer: disable ffmpeg support

---

srcpkgs/which/template

`which which` finds where and which which is `which`...

which: update to 2.23.

---

srcpkgs/nftables/template
srcpkgs/socklog-void/template

An unopinionated batch run of `xlint` on a list of local packages reported these "errors".
Not skipping checks since I didn't build the packages locally.

nftables, socklog-void: clean-up after xlint-ing

---

srcpkgs/timewarrior/template

- aarch64
- armv7l
- armv6l
- i686
- x86_64

timewarrior: update to 1.8.0

---

srcpkgs/biblioteq/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

biblioteq: update to 2025.07.02.

---

srcpkgs/freeorion/patches/fix-gigi-config-file-finding.patch
srcpkgs/freeorion/template

Source code URL changed a bit.
Added a patch for build failure (cmake cannot find `GG/GG/Config.h`) Reported upstream as: https://github.com/freeorion/freeorion/pull/5259
Ran a few turns of a new game.
- aarch64

freeorion: update to 0.5.1.1.

---

srcpkgs/v4l2loopback/template

Tested it out on the latest version of obs-studio and looked at v4l2loopback-ctl, everything seems to work fine.
NOTE: The current version of v4l2loopback on the repos, (0.13.2) doesn't seem to build correctly on the mainline kernel and 0.15.0 fixes this.

v4l2loopback: update to 0.15.0

---

srcpkgs/corectrl/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

corectrl: update to 1.5.1.

---

srcpkgs/diffutils/template

A quick diff & cmp on a bunch of files ran OK.
And `xbp-src check diffutils` output:
```
[...]
============================================================================
Testsuite summary for GNU diffutils 3.12
============================================================================
============================================================================
```
- NOPE, tried aarch64 (crossbuild) but that fails

diffutils: update to 3.12.

---

srcpkgs/docker-buildx/template

docker-buildx: update to 0.25.0.

---

srcpkgs/onefetch/template

onefetch: update to 2.25.0

---

srcpkgs/vale/template

vale: update to 3.12.0.

---

srcpkgs/python3-s-tui/template
srcpkgs/stress-ng/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

python3-s-tui: update to 1.2.0; stress-ng: update to 0.19.02.

---

srcpkgs/znc/template

- I built this PR locally for my native architecture, `x86_64`
- I built this PR locally for these architectures (if supported. mark crossbuilds): `aarch64`
Functionality has been tested and confirmed on x86_64 and aarch64. While the package builds successfully for all target architectures, runtime testing has not been performed on other platforms (e.g., `arm*`, `i686`).
cc: @Duncaen

znc: update to 1.10.1, adopt.

---

srcpkgs/flashrom/template
srcpkgs/fwupd/patches/skip-fu-self-tests.patch
srcpkgs/fwupd/template

This update is needed due to my `StarLabs MK V` tablet requiring new versions to update its firmware.

flashrom + fwupd: Update to 1.5.1 and 2.0.12

---

srcpkgs/gnome-control-center/template

- I built this PR locally for these architectures (if supported. mark crossbuilds): X

gnome-control-center: update to 48.3.

---

srcpkgs/tuxedo-drivers/template

- Built for kernels 6.1, 6.3–6.15; running on 6.15.4

tuxedo-drivers: update to 4.14.2

---

srcpkgs/crispy-doom/template

- Ran through a couple of levels of Doom 1 and 2, both games worked fine without any issues.
- Removed `post_install` stuff from the template, as it wasn't necessary anymore. we don't have to rename those files anymore to avoid conflicts with `chocolate-doom`, since upstream has done it for us.

crispy-doom: update to 7.0.

---

srcpkgs/wthrr/patches/fix-builds.patch
srcpkgs/wthrr/template

- I've been using the app for a couple years now
https://github.com/ttytm/wthrr-the-weathercrab
https://github.com/ttytm/wthrr-the-weathercrab/blob/main/INSTALL.md
> To display symbols correctly, the used terminal must be configured to use a NerdFont.
Since terminal configuration is up to the user, I did not add a hard dependency on a special font, and the app runs fine without.
The included patch removes a failing test from `src/modules/localization.rs` until there is a response/fix from upstream.
`wthrr` being a …

New package: wthrr-1.2.1

---

srcpkgs/nestopia/template

- Tested out the new build by emulating various different games, which all worked properly, and I couldn't notice any issues or regressions with the program itself.

nestopia: update to 1.53.1.

---

srcpkgs/qgit/template

qgit: update to 2.12, switch to qt6

---

srcpkgs/notmuch/notmuch-python3.INSTALL.msg
srcpkgs/notmuch/patches/0008-fix-cross-for-ruby-bindings.patch
srcpkgs/notmuch/template

I added libnotmuch's api manpage as well. Some previously masked tests seem to be passing now, but I haven't removed them in this patch, I can resubmit if wanted.
I also have patches for enabling cross on `notmuch-ruby`, adding the `notmuch-git` tool and the notmuch vim plugin. Please let me know if it's desirable to include any or all in this PR as well or to open separate PR's for them.

notmuch: update to 0.39.

---

srcpkgs/libxcb/template

xorg running with it since ~1h (and counting...)

libxcb: update to 1.17.0.

---

srcpkgs/qjackctl/template

qjackctl: update to 1.0.4, switch to qt6, adopt

---

srcpkgs/biblioteq/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

biblioteq: update to 2025.07.13.

---

srcpkgs/ytcc/template

- Ignoring `tests/test_cli.py` until https://github.com/pallets/click/issues/2939 is resolved (which _should_  affect older versions too, so we may just as well update to 2.8.0 - personally, I haven't experienced any issues at runtime, so far)
- Removed `mpv` (optional) from `depends` - the app does what is advertised without a media player present
[Changelog](https://github.com/woefe/ytcc/releases/tag/v2.8.0)

ytcc: update to 2.8.0

---

srcpkgs/spotify/template

spotify: update to 1.2.36

---

srcpkgs/helix/template

helix: update to 25.07.1

---

common/shlibs
srcpkgs/kwin-effects-forceblur/template

This does need the updated kde-plasma packages that I don't think are built yet at the time of writing, but I built it on my machine since it's on the void-packages git and it works.

kwin-effects-forceblur: update to 1.4.0

---

srcpkgs/tuxedo-yt6801/template

- Built for kernels 6.6, 6.12, 6.14, 6.15, running on 6.15.6
@suturar

tuxedo-yt6801: update to 1.0.30tux2

---

srcpkgs/kwayland/patches/drm_fourcc-typedef.patch

FTBFS, patch from upstream
- I built the changes in this PR locally on x86_64, x86_64-musl, i686
edit: forgot to revbump

kwayland: fix typedef

---

srcpkgs/watchexec/update

Currently, library updates are also detected as new release although we only care about the CLI.
cc @cinerea0

watchexec: fix update-check

---

srcpkgs/libiio/template

libiio: update to 0.26

---

srcpkgs/nfs-utils/files/nfs-server/run
srcpkgs/nfs-utils/template

An NFSv4 server does not require statd or rpcbind. On the client side, these two services can also remain disabled.
A prerequisite for this to work is setting the NFSV4_ONLY var:
```
/etc/sv/nfs-server/conf
NFSV4_ONLY=yes
```
as well as disabling NFSv3:
```
/etc/nfs.conf 
[nfsd]
vers3=n
vers4=y
vers4.1=y
vers4.2=y
```
I can create a PR documenting the changes https://github.com/void-linux/void-docs/commit/197ff670e6a068d401bc090421509d88beca6320
- https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/storage_administration_guide/ch-nfs#s1-nfs-how
> The mounting and locking protocols have been incorporated into the NFSv4 protocol. The server also listens on the well-known TCP port 2049. As such, NFSv4 does not need to interact …

nfs-utils: add an option for NFSv4 server to not rely on statd or rpcbind

---

srcpkgs/scaleway-cli/template

- i686
- x86_64-musl
- aarch64
- armv7l

scaleway-cli: update to 2.42.0

---

srcpkgs/atari800/template

- Emulator starts
- Few games checked to be working
- Cartridge functionality works (Action!, Sparta DOS X)
- Alternative basics works (Turbo Basic XL, Advan Basic, etc)

atari800: update to 5.2.0

---

srcpkgs/libayatana-appindicator/template

mainly deprecation changes
- i686-glibc
- x86_64-musl
- aarch64-glibc (x86_64-glibc)
- aarch64-musl (x86_64-musl)
- armv7l-glibc (x86_64-glibc)
- armv6l-musl - x86_64-musl

libayatana-appindicator: update to 0.5.94.

---

srcpkgs/wofi/template

- i686-glibc
- x86_64-musl
- aarch64-glibc (x86_64-glibc)
- aarch64-musl (x86_64-musl)
- armv7l-glibc (x86_64-glibc)
- armv6l-musl - x86_64-musl

wofi: update to 1.5.1.

---

srcpkgs/docker-compose/template

docker-compose: update to 2.39.1

---

srcpkgs/Vulkan-Tools/template

`vulkaninfo` in the `Vulkan-Tools` package apparently requires `vulkan-loader`.    
Installing `vulkan-loader` resolves the error displayed when running `vulkaninfo` without `vulkan-loader` installed.
```
$ vulkaninfo
ERROR at /builddir/Vulkan-Tools-1.4.313.0/vulkaninfo/./vulkaninfo.h:526: Failed to initialize: Vulkan loader is not installed, not found, or failed to load.
```

Vulkan-Tools: Add dependency on vulkan-loader

---

srcpkgs/river-bedload/template

New package: river-bedload-0.1.1

---

srcpkgs/python3-Flask/template
srcpkgs/python3-Werkzeug/template
srcpkgs/python3-blinker/template
srcpkgs/python3-itsdangerous/template

- **python3-Flask: update to 3.1.1.**
- **python3-Werkzeug: update to 3.1.3.**
- **python3-itsdangerous: update to 2.2.0.**
- **python3-blinker: update to 1.9.0. adopt.**
- aarch64-musl
- armv7l
- armv6l-musl

Update some pallets' pkgs

---

srcpkgs/dssi/patches/alsa-include.patch
srcpkgs/dssi/patches/fix-incompatible-pointer.patch
srcpkgs/dssi/template

- I tested the changes in this PR: **briefly** — built rev. deps for all platforms listed below, used one (calf) on x86_64
- x86_64-musl
- i686
- armv6l [Cross] 
- armv6l-musl [Cross]
- armv7l [Cross]
- armv7l-musl [Cross]
- aarch64 [Cross and native]
- aarch64-musl [Cross and native]
~~With this change, `whysynth` builds on cross armv6l-musl, armv7l-musl and aarch64-musl, without it doesn't. The rest all build fine as-is.~~
Edit: Nevermind the above line, it was an issue in local builds, re-tested and build of whysynth prior to applying this PR completed successfully too.

dssi: fix gcc14 compat, alsa include

---

srcpkgs/findutils/patches/fix-musl.patch
srcpkgs/findutils/template

- Personal `bash` scripts utilizing `find` or `xargs` are still working as expected
- Rerunning commands mentioned above (+ args) from my shell history are still working as expected
- Briefly tested `xdeptree` `xdiff` `xgrep` `xlocate` `xrevshlib` `xsrc`
[Changelog](https://git.savannah.gnu.org/cgit/findutils.git/plain/NEWS)

findutils: update to 4.10.0

---

srcpkgs/python3-nitrokey/template
srcpkgs/python3-pynitrokey/template

https://github.com/Nitrokey/pynitrokey/compare/v0.9.3...v0.10.0
https://github.com/Nitrokey/nitrokey-sdk-py/compare/v0.3.2...v0.4.0
One needs the other; hence one PR.

python3-pynitrokey: update to 0.10.0, python3-nitrokey: update to 0.4.0

---

srcpkgs/mise/template

mise: update to 2025.8.4

---

srcpkgs/wayland/template

```
[*] Waybar-0.14.0_1         Polybar-like Wayland Bar for Sway and Wlroots based compositors
[*] cliphist-0.6.1_1        Wayland clipboard manager
[*] foot-1.23.1_1           Fast, lightweight and minimalistic Wayland terminal emulator
[*] foot-terminfo-1.23.1_1  Fast, lightweight and minimalistic Wayland terminal emulator -...
[*] grim-1.4.1_1            Grab images from a Wayland compositor
[*] gtk-layer-shell-0.9.2_1 Library to create panels and other desktop components for Wayl...
[*] labwc-0.9.1_1           Wayland window-stacking compositor
[*] libdecor-0.2.2_1        Client-side decorations library for Wayland client
[*] libinput-1.28.1_1       Provides handling input devices in Wayland compositors and X
[*] niri-25.05.1_1 …
```

wayland: update to 1.24.0

---

srcpkgs/python3-uvicorn/template

python3-uvicorn: update to 0.35.0

---

srcpkgs/rio/template

rio: update to 0.2.28, orphan

---

srcpkgs/python3-dbus-fast/template

python3-dbus-fast: update to 2.44.3.

---

srcpkgs/doasedit/template

I know that simple shell scripts are generally not accepted, but I do think that this one could be valuable for `doas` users.

New package: doasedit-1.0.8

---

srcpkgs/python3-fire/template

py3-six [obsolete](https://github.com/google/python-fire/pull/541) as of [v. 0.7.0 ](https://github.com/google/python-fire/releases)

python3-fire: update to 0.7.1

---

srcpkgs/incus/files/README.voidlinux
srcpkgs/incus/template

Hi, just making an update build for incus @dkwo 
Removed umoci from the readme because [6.13](https://discuss.linuxcontainers.org/t/incus-6-13-has-been-released/23899) removed it as a dependency. 
I will also make a PR to remove it from the void docs. 
(if there is a consensus on whether we want this info in only one place, I can adjust this PR to remove the README or adjust void docs to not have the redundant information) @classabbyamp 

incus: update to 6.15.0.

---

srcpkgs/manpages-pt-br/template

Checked some polish manpages, looks OK
I think that this package needs more customization in the future, like removing pages relevant for systemd (`/usr/share/man/pl/man8/shutdown.8` for example). I'm not sure if this is relevant only for polish manpages, or maybe for other languages also.

manpages-pt-br: update to 4.27.0.

---

srcpkgs/zfs/patches/0003-musl-statx.patch
srcpkgs/zfs/template

- aarch64-musl, root on zfs, built against linux 6.12, 6.15, and 6.16, booted on 6.16
cc: @Vaelatern

zfs: update to 2.3.4.

---

srcpkgs/etckeeper/template

This new release fixes a bug when used with xbps, where an error message would be produced by 'etckeeper post-install' after installing a package
Changelog: https://etckeeper.branchable.com/news/version_1.18.23/
- armv6l
- armv7l

etckeeper: update to 1.18.23

---

srcpkgs/libutf8proc/template

libutf8proc: update to 2.11.0

---

srcpkgs/cotp/template

Command line TOTP/HOTP authenticator: https://github.com/replydev/cotp
Since [OTPClient](https://github.com/void-linux/void-packages/blob/master/srcpkgs/OTPClient/template), a GTK program, is the only simple OTP authenticator currently available in Void repositories, I reckon this package could be a good addition for users without a graphical environment. Upstream development is active.

New package: cotp-1.9.7

---

srcpkgs/miniserve/template

miniserve: update to 0.32.0.

---

srcpkgs/ncspot/template

- x86_64-musl
The built packages are available for the above mentioned architectures in the following repository for testing: https://voidrepo.nordstadt.club/pr-update-ncspot
This repo is signed by 'Moabeat' with fingerprint 29:37:3f:88:73:9a:c2:6c:24:63:29:63:3b:e0:40:7d

ncspot: update to 1.3.1.

---

common/shlibs
srcpkgs/enter-tex/template
srcpkgs/gedit-plugins/template
srcpkgs/gedit/template
srcpkgs/libgedit-amtk/template
srcpkgs/libgedit-gfls/template
srcpkgs/libgedit-gtksourceview/template
srcpkgs/libgedit-tepl/template

**PLEASE NOTE**: plugins implemented in python are no longer supported.
The official plugins written in python have been removed.
See [https://gitlab.gnome.org/World/gedit/gedit/-/issues/614](https://gitlab.gnome.org/World/gedit/gedit/-/issues/614)
for more details.
Also see [https://gitlab.gnome.org/World/gedit/gedit/-/issues/618](https://gitlab.gnome.org/World/gedit/gedit/-/issues/618)
concerning the status for third-party plugins.
It seems support for third-party python plugins [may return](https://gedit-text-editor.org/blog/2025-07-14-mid-july-news.html)?
Either way, it looks like going forward official plugins will be written in C or Rust or something else.
If python support is desired, it may be best to skip this version.  Python …

[DRAFT] gedit: update to 48.2 and update dependencies

---

srcpkgs/gamescope/template

- I built this PR locally for my native architecture: **x86_64 (libc)**

gamescope: update to 3.16.17.

---

srcpkgs/tuxedo-drivers/template

- Built for kernels 6.1, 6.3–6.15; running on 6.16.8
The source tarball contains now some udev rules, add them to the package.

tuxedo-drivers: add udev rules

---

srcpkgs/libssh/template

libssh: update to 0.11.3.

---

srcpkgs/Signal-Desktop/template

Note the deprecation warnings for our old node.

Signal-Desktop: update to 7.69.0

---

srcpkgs/slirp4netns/template

slirp4netns: update to 1.3.3.

---

srcpkgs/docker-buildx/template

docker-buildx: update to 0.28.0.

---

srcpkgs/openvpn/template

- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

openvpn: update to 2.6.15

---

srcpkgs/python3-pytest-black/template

python3-pytest-black: update to 0.6.0, adopt.

---

srcpkgs/python3-starlette/template

python3-starlette: update to 0.48.0

---

srcpkgs/pgbackrest/template

pgbackrest: update to 2.56.0.

---

srcpkgs/wine/template

@Hoshpak 
I only tested x86_64-glibc.
Worth noting that in this new version the new WoW64 mode now supports 16bit apps too, closing the feature parity gap.
Given that arch switched to those by default and there are many more testers, perhaps it's time to consider the transition as I expect it to fully mature promptly.

wine: update to 10.16

---

srcpkgs/caddy/template

caddy: update to 2.10.2.

---

srcpkgs/fish-shell/template

fish-shell: update to 4.1.2
