- srcpkgs/kubernetes-helm/template
> kubernetes-helm: update to 3.16.3

- srcpkgs/instaloader/template
> instaloader: update to 4.14.

- srcpkgs/duckdb/template
> duckdb: update to 1.1.3.

- srcpkgs/mise/template
> mise: update to 2024.11.13.

- srcpkgs/pnpm/template
> pnpm: update to 9.13.2.

- srcpkgs/intellij-idea-community-edition/template
> intellij-idea-community-edition: update to 2024.3.

- srcpkgs/tlpui/template
- x86_64
<br/>
@motorto  could you please review the changes??
And thanks for your time!
> tlpui: update to 1.7.1

- srcpkgs/gtkwave/template
> gtkwave: update to 3.3.121.

- srcpkgs/rio/template
> rio: update to 0.2.0

- srcpkgs/limine/template
> limine: update to 8.4.0.

- srcpkgs/odilia/patches/fix-lock.diff
- srcpkgs/odilia/template
> New package: odilia-0.1.4

- srcpkgs/gwenview/template
> gwenview: update to 24.08.3.

- srcpkgs/falkon/template
> falkon: update to 24.08.3.

- srcpkgs/warzone2100/template
> warzone2100: update to 4.5.5.

- srcpkgs/Swapspace/template
> Swapspace: update to 1.18.1

- srcpkgs/pan/template
> pan: update to 0.161.

- srcpkgs/lychee/template
> lychee: update to 0.17.0.

- srcpkgs/fend/template
> fend: update to 1.5.5

- srcpkgs/digikam/template
> digikam: update to 8.5.0.

- srcpkgs/codeberg-cli/template
> codeberg-cli: update to 0.4.6

- srcpkgs/clj-kondo/template
[clj-kondo](https://github.com/clj-kondo/clj-kondo): Static analyzer and linter for Clojure
> New package: clj-kondo-2024.11.14

- srcpkgs/electrum/template
- srcpkgs/libsecp256k1/template
- srcpkgs/python3-jsonpatch/template
python3-jsonpatch is required for electrum v4.5.
> electrum: update to 4.5.8; New package: python3-jsonpatch-1.33

- srcpkgs/discord/template
> discord: update to 0.0.75

- srcpkgs/rio/template
> rio: update to 0.2.1

- srcpkgs/pixman/template
- I tested the changes in this PR: **BRIEFLY**
@ericonr
> pixman: update to 0.44.0.

- srcpkgs/xrandr/template
> xrandr: update to 1.5.3

- srcpkgs/clojure-lsp/template
> clojure-lsp: update to 2024.11.08.

- srcpkgs/ncdu2/template
> ncdu2: update to 2.7

- srcpkgs/git-cliff/template
> git-cliff: update to 2.7.0

- srcpkgs/ast-grep/template
> ast-grep: update to 0.30.0.

- srcpkgs/eza/template
> eza: update to 0.20.9

- srcpkgs/wget/template
- x86_64-glibc
<br/>
@skmpz could you please review the changes??
> wget: update to 1.25.0

- srcpkgs/yaydl/template
> yaydl: update to 0.17.0

- srcpkgs/sublime-merge/template
<br/>
@mobinmob could you please review the changes??
> sublime-merge: update to 2102

- srcpkgs/zoom/template
> zoom: update to 6.2.10.4983

- srcpkgs/m17n-db/template
> m17n-db: update to 1.8.9

- srcpkgs/llvm19-bootstrap/template
- srcpkgs/llvm19/template
- x86_64-musl
- i686
[ci skip]
> llvm19: update to 19.1.4.

- srcpkgs/lapce/patches/desktop-icon.patch
- srcpkgs/lapce/template
- x86_64-musl
<br/>
@atk could you please review the changes??
> lapce: update to 0.4.2, adopt

- common/build-helper/meson.sh
- common/build-helper/qemu.sh
- common/hooks/pre-configure/02-script-wrapper.sh
- srcpkgs/mesa/template
> Mesa llvm19

- srcpkgs/flnet/template
> New package: flnet-7.5.0

- srcpkgs/fllog/template
> New package: fllog-1.2.8

- srcpkgs/remote-touchpad/template
- Tested on Mate/X11, Gnome/Wayland, and KDE/Wayland
> New package: remote-touchpad

- srcpkgs/borgmatic/template
> borgmatic: update to 1.9.2.

- srcpkgs/cargo-auditable-bootstrap/template
- srcpkgs/cargo-auditable/template
> cargo-auditable: update to 0.6.6

- srcpkgs/pnpm/template
> pnpm: update to 9.14.2.

- srcpkgs/gradle/template
> gradle: update to 8.11.1.

- srcpkgs/rclone/template
> rclone: update to 1.68.2.

- srcpkgs/calibre/template
> calibre: update to 7.21.0.

- srcpkgs/swayimg/template
> swayimg: update to 3.5.

- srcpkgs/jwm/template
> jwm: update to 2.4.6

- srcpkgs/discord/template
> discord: update to 0.0.76

- srcpkgs/CastXML/template
- srcpkgs/bcc/template
- srcpkgs/bpftrace/template
- srcpkgs/ccls/template
- srcpkgs/gnome-builder/template
- srcpkgs/ispc/template
- srcpkgs/juCi++/template
- srcpkgs/kdevelop/template
> Rebuild several packages with llvm19

- srcpkgs/xorg-server-xwayland/template
> xorg-server-xwayland: update to 24.1.4.

- srcpkgs/clojure/template
> clojure: update to 1.12.0.1488.

- srcpkgs/skim/template
> skim: update to 0.11.11, adopt

- srcpkgs/sbctl/template
> sbctl: update to 0.16

- srcpkgs/victoria-logs/files/victoria-logs/run
- srcpkgs/victoria-logs/template
- srcpkgs/victoria-logs/update
- srcpkgs/victoria-metrics/files/victoria-metrics/run
- srcpkgs/victoria-metrics/template
> New package: victoria-metrics-1.106.1, victoria-logs-1.0.0

- srcpkgs/rio/template
> rio: update to 0.2.2

- srcpkgs/qrcp/template
> qrcp: update to 0.11.3

- srcpkgs/github-cli/template
> github-cli: update to 2.63.0

- srcpkgs/kak-lsp/template
> kak-lsp: update to 18.1.0.

- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.13.2.

- srcpkgs/k3d/template
> k3d: update to 5.7.5.

- srcpkgs/cocogitto/template
> cocogitto: update to 6.2.0, orphan

- srcpkgs/eza/template
> eza: update to 0.20.10

- srcpkgs/ntpd-rs/template
> ntpd-rs: update to 1.3.1

- srcpkgs/yosys/template
- srcpkgs/yosys/update
- Installed locally, tested that yosys reports new version.
> yosys: update to 0.47.

- srcpkgs/synapse/template
> synapse: update to 1.120.0.

- srcpkgs/treefmt/template
> treefmt: update to 2.1.1.

- srcpkgs/hcloud/template
> hcloud: update to 1.49.0.

- srcpkgs/7zip/template
> 7zip: update to 24.09.

- srcpkgs/clifm/template
> clifm: update to 1.22.

- srcpkgs/toot/template
> toot: update to 0.47.1.

- srcpkgs/lite-xl/template
> lite-xl: update to 2.1.6

- srcpkgs/revive/template
> revive: update to 1.5.1.

- srcpkgs/inspircd/template
> inspircd: update to 4.4.0

- srcpkgs/gopass-jsonapi/template
- srcpkgs/gopass/template
> gopass{,-jsonapi}: update to 1.15.15

- srcpkgs/gnucash/template
> gnucash: update to 5.9

- srcpkgs/cargo-bootstrap/template
- srcpkgs/cargo/template
- srcpkgs/rust-bootstrap/template
- srcpkgs/rust/patches/0002-Remove-nostdlib-and-musl_root-from-musl-targets.patch
- srcpkgs/rust/patches/0010-Fix-dynamic-linkage-of-musl-libc-for-the-libc-crate.patch
- srcpkgs/rust/patches/0011-Use-ELFv2-ABI-on-all-powerpc64-targets.patch
- srcpkgs/rust/template
> rust: revert broken version

- srcpkgs/ddclient/patches/porkbun.patch
- srcpkgs/ddclient/template
Upstream is currently MIA on merging https://github.com/ddclient/ddclient/pull/752. This will keep ddclient on life support for now.
> ddclient: update porkbun API endpoint.

- srcpkgs/tree/template
> tree: update to 2.2.1.

- srcpkgs/nvidia/template
> nvidia: update to 550.135.

- srcpkgs/github-cli/template
> github-cli: update to 2.63.1

- srcpkgs/strace/template
> strace: update to 6.12.

- srcpkgs/intellij-idea-ultimate-edition/template
> intellij-idea-ultimate-edition: update to 2024.3, adopt

- srcpkgs/skim/template
> skim: update to 0.15.4

- srcpkgs/scrcpy/template
> scrcpy: update to 3.0.2.

- srcpkgs/ruby-tmuxinator/template
- x86_64-musl
- i686
- aarch64
- armv7l
> ruby-tmuxinator: update to 3.3.3.

- srcpkgs/github-cli/template
> github-cli: update to 2.63.2

- srcpkgs/jaq/template
> New package: jaq-2.0.0

- srcpkgs/eza/template
> eza: update to 0.20.11

- srcpkgs/topgrade/template
> topgrade: update to 16.0.2

- srcpkgs/font-sarasa-gothic/template
> font-sarasa-gothic: update to 1.0.25.

- srcpkgs/proplib/template
> proplib: fix distfile, update to 0.6.10.

- srcpkgs/pekwm/template
- I tested the changes in this PR: **Brifely**
- aarch64-musl [X]
- armv7l [X]
- armv6l-musl [X]
> pekwm: update to 0.3.1.

- srcpkgs/mesa/template
> mesa: update to 24.3.1.

- srcpkgs/fwupd/template
> fwupd: update to 2.0.2.

- srcpkgs/tcpdump/template
- I did tests with the same way I usually use it
- I built this PR locally for these architectures (armv6hf-musl)
> tcpdump: update to 4.99.5.

- srcpkgs/ast-grep/template
> ast-grep: update to 0.31.0.

- srcpkgs/volta/template
> volta: update to 2.0.2

- srcpkgs/river/template
> river: update to 0.3.6

- srcpkgs/act/template
I haven't been able to use this in a while, and each update is just bs dependabot bumps
> act: orphan.

- srcpkgs/opera/template
> opera: update to 115.0.5322.77.

- srcpkgs/skim/template
> skim: update to 0.15.5

- srcpkgs/fnott/template
> fnott: update to 1.7.0

- srcpkgs/eza/template
> eza: update to 0.20.12

- srcpkgs/limine/template
> limine: update to 8.6.0.

- srcpkgs/discord/template
> discord: update to 0.0.77

- srcpkgs/vaultwarden/template
> vaultwarden: update to 1.32.6.

- srcpkgs/rsyslog/files/rsyslog.conf
- srcpkgs/rsyslog/template
> rsyslog: update to 8.2412.0.

- srcpkgs/ntpd-rs/template
> ntpd-rs: update to 1.4.0

- srcpkgs/wlroots0.18/template
> wlroots0.18: update to 0.18.2

- srcpkgs/labwc/template
> labwc: update to 0.8.2

- srcpkgs/sequoia-sq/template
> sequoia-sq: update to 1.0.0.

- srcpkgs/go-md2man/template
> go-md2man: update to 2.0.6.

- srcpkgs/eza/template
> eza: update to 0.20.13

- srcpkgs/tealdeer/template
> tealdeer: update to 1.7.1

- srcpkgs/gnome-app-list/template
- srcpkgs/gnome-software/template
> gnome-software: update to 47.2

- srcpkgs/pragha/patches/rygel-2.8.patch
- srcpkgs/pragha/template
- srcpkgs/rygel/patches/require-gupnp.patch
- srcpkgs/rygel/template
> Pragha dlna

- srcpkgs/lvm2/patches/fix-stdio-usage.patch
- srcpkgs/lvm2/template
- I tested the changes in this PR: **YES** (booted a non-encrypted lvm2 root machine with mkinitcpio)
> lvm2: update to 2.03.29.

- srcpkgs/yazi/template
* I tested the changes in this PR: **YES**
* I built this PR locally for my native architecture, x86_64-glibc
> yazi: update to 0.4.1.

- srcpkgs/zoom/template
> zoom: update to 6.3.0.5527

- srcpkgs/discord/template
> discord: update to 0.0.78

- srcpkgs/github-cli/template
> github-cli: update to 2.64.0

- srcpkgs/sublime-text4/template
> sublime-text4: update to 4189, adopt

- Manual.md
- common/build-helper/rust.sh
> common/build-helper/rust.sh: add cargo wrapper

- srcpkgs/gpgme-qt6/template
- srcpkgs/gpgme/template
- srcpkgs/gpgmeqt-headers
> gpgme 1.24.1

- srcpkgs/yazi/template
> yazi: update to 0.4.2.

- srcpkgs/nicotine+/template
- srcpkgs/python3-gobject/template
- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl
> nicotine+: update to 3.3.7.

- srcpkgs/neovim/template
> neovim: update to 0.10.3

- srcpkgs/font-sarasa-gothic/template
> font-sarasa-gothic: update to 1.0.26.

- srcpkgs/zfs/template
> zfs: update to 2.2.7.

- srcpkgs/zfs-lts/template
> zfs-lts: update to 2.1.16.

- srcpkgs/python3-PyQt-builder/patches/no-packaging.patch
- srcpkgs/python3-PyQt-builder/template
- srcpkgs/python3-PyQt5-networkauth/template
- srcpkgs/python3-PyQt5-webengine/template
- srcpkgs/python3-PyQt5/template
- srcpkgs/python3-sip-PyQt5/template
- srcpkgs/sip/template
> Pyqt5 update

- srcpkgs/ufetch/template
> ufetch: update to 0.4

- srcpkgs/hyperrogue/template
> hyperrogue: update to 13.0w

- srcpkgs/playonlinux/patches/replace-pipes.patch
- srcpkgs/playonlinux/template
- i686 (cross)
Probably resolves #53628
> fix playonlinux

- srcpkgs/dinit/template
> dinit: update to 0.19.2

- srcpkgs/samsung-unified-driver/template
> samsung-unified-driver: update to 1.00.39

- srcpkgs/ncspot/template
> ncspot: update to 1.2.1

- srcpkgs/strawberry/template
> strawberry: update to 1.2.3, adopt

- srcpkgs/pylint/template
> pylint: update to 3.3.3

- srcpkgs/yggdrasil/template
> yggdrasil: update to 0.5.12

- srcpkgs/nvidia/template
> nvidia: update to 550.142.

- srcpkgs/lutris/template
> lutris: update to 0.5.18.

- srcpkgs/eza/template
> eza: update to 0.20.14

- srcpkgs/nim/template
> nim: update to 2.0.14.

- srcpkgs/atuin/template
> atuin: update to 18.4.0

- srcpkgs/gping/template
> gping: update to 1.19.0.

- srcpkgs/xfce4-panel-profiles/template
- Tested in host Void and fresh VM, backup/import/export all work fine
> xfce4-panel-profiles: update to 1.0.15.

- srcpkgs/hyperrogue/template
> hyperrogue: use fontconfig

- srcpkgs/skim/template
> skim: update to 0.15.7

- srcpkgs/kak-lsp/template
> kak-lsp: update to 18.1.1.

- srcpkgs/mise/template
> mise: update to 2024.12.24.

- srcpkgs/google-chrome/template
- I built this PR locally for my native architecture, (X86_64_LIBC)
> google-chrome: update to 131.0.6778.204.

- srcpkgs/runit-void/INSTALL.msg
- srcpkgs/runit-void/template
https://github.com/void-linux/void-runit/pull/103
> runit-void: add INSTALL.msg concerning cgroup mode

- srcpkgs/eza/template
> eza: update to 0.20.15

- srcpkgs/xh/template
> xh: update to 0.23.1

- srcpkgs/font-sarasa-gothic/template
> font-sarasa-gothic: update to 1.0.27.

- srcpkgs/miniflux/template
> miniflux: update to 2.2.4, adopt.

- srcpkgs/conky/template
Fixes race condition starting X11 that prevents conky from starting
closes #50564
> conky: update to 1.22.0. 

- srcpkgs/ast-grep/template
> ast-grep: update to 0.32.3.

- srcpkgs/river/template
- I tested the changes in this PR: Briefly
> river: update to 0.3.7.

- srcpkgs/numbat/template
> numbat: update to 1.15.0

- srcpkgs/pipewire/template
> pipewire: update to 1.2.7

- srcpkgs/trippy/template
> trippy: update to 0.12.2.

- srcpkgs/erlang_ls/template
> erlang_ls: update to 1.1.0.

- srcpkgs/xonotic/template
> xonotic: proper --host triplet

- srcpkgs/xurls/template
> xurls: update to 2.6.0.

- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.13.5.

- srcpkgs/mercurial/template
> mercurial: update to 6.9.

- srcpkgs/iniparser/template
> iniparser: update to 4.2.5

- srcpkgs/github-cli/template
> github-cli: update to 2.65.0

- srcpkgs/codeberg-cli/template
> codeberg-cli: update to 0.4.7

- srcpkgs/opam/template
> opam: update to 2.3.0

- srcpkgs/bat/template
> bat: update to 0.25.0

- srcpkgs/usbkvm/template
> New package: usbkvm-0.1.0

- srcpkgs/telegram-desktop/template
> telegram-desktop: update to 5.10.2.

- common/shlibs
- srcpkgs/collada-dom-devel
- srcpkgs/collada-dom/patches/null.patch
- srcpkgs/collada-dom/template
- srcpkgs/osg/template
- **osg: enable collada-dom**
- **New package: collada-dom-2.5.0**
> osg: build collada-dom plugin

- srcpkgs/scrcpy/template
> scrcpy: update to 3.1.

- srcpkgs/i2pd/template
> i2pd: update to 2.55.0

- srcpkgs/runelite-launcher/template
> runelite-launcher: update to 2.7.2.

- srcpkgs/fselect/template
> fselect: update to 0.8.8.

- srcpkgs/discover/template
> New package: discover-6.1.5

- srcpkgs/dbeaver/patches/force-jdk17.patch
- srcpkgs/dbeaver/template
> dbeaver: update to 24.3.2.

- srcpkgs/strawberry/template
> strawberry: update to 1.2.4

- srcpkgs/ast-grep/template
> ast-grep: update to 0.33.0.

- srcpkgs/purpose/template
> purpose: remove conflicting files

- srcpkgs/zoom/template
> zoom: update to 6.3.5.6065

- srcpkgs/asahi-base/INSTALL
- srcpkgs/asahi-base/template
cc @classabbyamp Just a small fix, so that it only tries to create a symlink if not exist.
> asahi-base: INSTALL: better check for service

- srcpkgs/libqalculate/template
- srcpkgs/qalculate-gtk/template
- srcpkgs/qalculate-qt/template
- i686
- x86_64-musl
@yoshiyoshyosh
> qalculate: update to 5.4.0

- srcpkgs/yamlfmt/template
> yamlfmt: update to 0.15.0.

- srcpkgs/gum/template
> gum: update to 0.15.0

- srcpkgs/yt-dlp/template
> yt-dlp: update to 2025.01.12

- srcpkgs/jaq/template
> jaq: update to 2.1.0

- srcpkgs/gopls/template
> gopls: update to 0.17.1.

- srcpkgs/frp/template
> frp: update to 0.61.1.

- srcpkgs/vhs/template
> vhs: update to 0.9.0

- srcpkgs/rofi/patches/buffer-overflow.patch
- srcpkgs/rofi/template
Please see https://github.com/davatorium/rofi/pull/2082 and https://github.com/davatorium/rofi/issues/2081
> rofi: Fix buffer overflow

- srcpkgs/spice/template
> spice: update to 0.15.2.

- srcpkgs/aerc/template
> aerc: update to 0.19.0.

- srcpkgs/ast-grep/template
> ast-grep: update to 0.33.1.

- srcpkgs/lazygit/template
> lazygit: update to 0.45.0.

- srcpkgs/asahi-base/INSTALL
- srcpkgs/asahi-base/template
> asahi-base: fix symlink

- srcpkgs/oniguruma/template
> oniguruma: update to 6.9.10

- srcpkgs/rio/template
> rio: update to 0.2.4

- srcpkgs/syncthing/template
Upstream recommends installing this.
I tested the changes in this PR within my dinit user service.
cc @Duncaen
> syncthing: install sysctl file

- srcpkgs/syncthing/template
cc @Duncaen Sorry, I messed up the tag.
> syncthing: fix tag

- srcpkgs/nvidia/template
> nvidia: update to 550.144.03.

- srcpkgs/helix/template
> helix: update to 25.01.1

- srcpkgs/lazygit/template
> lazygit: update to 0.45.2.

- srcpkgs/limine/template
> limine: update to 8.7.0.

- srcpkgs/font-iosevka/template
> font-iosevka: update to 32.4.0.

- common/shlibs
- srcpkgs/gnome-builder/template
- srcpkgs/libdex/template
- srcpkgs/libpanel/template
- srcpkgs/libspelling-devel
- srcpkgs/libspelling/template
> gnome-builder: update to 47.0.

- srcpkgs/gamescope/patches/0002-version-string.patch
- srcpkgs/gamescope/template
> gamescope: update to 3.16.1.

- srcpkgs/pgbackrest/template
> pgbackrest: update to 2.54.1.

- srcpkgs/fzf/template
> fzf: update to 0.58.0

- srcpkgs/discord-ptb/template
> discord-ptb: update to 0.0.126.

- srcpkgs/minisign/template
> minisign: update to 0.12.

- srcpkgs/xq/template
> xq: update to 1.3.0

- srcpkgs/diffstat/template
> diffstat: update to 1.67.

- srcpkgs/primesieve/template
> primesieve: update to 12.6.

- srcpkgs/igraph/template
> igraph: update to 0.10.15.

- srcpkgs/gap/template
> gap: update to 4.14.0.

- srcpkgs/octave/template
> octave: update to 9.3.0.

- srcpkgs/lapack/template
> lapack: update to 3.12.1.

- srcpkgs/eza/template
> eza: update to 0.20.18

- srcpkgs/mtr/template
mtr added dependency of jansson for json output ref https://github.com/traviscross/mtr/issues/377
- I built this PR locally for my native architecture, x86_64-LIBC
> mtr: add dependency for json output

- srcpkgs/lzip/template
> lzip: update to 1.25.

- srcpkgs/incus/files/README.voidlinux
- srcpkgs/incus/template
> incus: fix typo in README.voidlinux

- srcpkgs/telegram-desktop/template
> telegram-desktop: update to 5.10.4.

- srcpkgs/discord/template
> discord: update to 0.0.81

- srcpkgs/inxi/template
> inxi: update to 3.3.37.1

- srcpkgs/python3-yapf/template
> python3-yapf: update to 0.43.0.

- srcpkgs/stow/template
> stow: update to 2.4.1

- srcpkgs/pgbackrest/template
> pgbackrest: update to 2.54.2.

- srcpkgs/git-cliff/patches/rust-version.patch
- srcpkgs/git-cliff/template
> git-cliff: update to 2.8.0

- srcpkgs/ov/template
> ov: update to 0.38.0.

- srcpkgs/aerc/template
> aerc: update to 0.20.0.

- srcpkgs/xwayland-satellite/template
> New package: xwayland-satellite-0.5

- srcpkgs/tiff/template
> tiff: update to 4.7.0.

- srcpkgs/discord/template
> discord: 82

- srcpkgs/vaultwarden-web/template
- srcpkgs/vaultwarden/patches/reference-static-in-constant.patch
- srcpkgs/vaultwarden/patches/rust-version.patch
- srcpkgs/vaultwarden/template
> vaultwarden: update to 1.33.0.

- srcpkgs/vala/patches/array-len-dup-overflow.patch
- srcpkgs/vala/template
- srcpkgs/valadoc/template
- I built this PR locally for my native architecture, `x86_64-glibc`.
> vala, valadoc: update to 0.56.17

- common/shlibs
- srcpkgs/balsa/template
- srcpkgs/cherrytree/template
- srcpkgs/enter-tex/template
- srcpkgs/evince/template
- srcpkgs/evolution/template
- srcpkgs/fractal/template
- srcpkgs/geary/template
- srcpkgs/gedit/template
- srcpkgs/gitg/template
- srcpkgs/gspell/template
- srcpkgs/inkscape/template
- srcpkgs/mousepad/template
- srcpkgs/pan/template
- srcpkgs/wxWidgets-gtk3/template
- srcpkgs/yad/template
> gspell: update to 1.14.0

- srcpkgs/evolution-data-server/template
- srcpkgs/evolution-ews/template
- srcpkgs/evolution/template
> evolution{,-data-server,-ews}: update to 3.54.3.

- srcpkgs/neovim/template
> neovim: update to 0.10.4

- srcpkgs/eza/template
> eza: update to 0.20.19

- srcpkgs/aerc/template
> aerc: update to 0.20.1.

- srcpkgs/gum/template
> gum: update to 0.15.2

- srcpkgs/numbat/template
> numbat: update to 1.16.0

- srcpkgs/font-sarasa-gothic/template
> font-sarasa-gothic: update to 1.0.28.

- srcpkgs/halloy/patches/dynamic-liblzma.patch
- srcpkgs/halloy/template
> halloy: update to 2025.1

- srcpkgs/yaydl/template
> yaydl: update to 0.17.2

- srcpkgs/skim/template
> skim: update to 0.16.0

- srcpkgs/discord/template
> discord: update to 0.0.83

- srcpkgs/zoom/template
> zoom: update to 6.3.6.6315

- srcpkgs/curl/template
> curl: update to 8.12.0

- srcpkgs/ast-grep/template
> ast-grep: update to 0.34.4.

- srcpkgs/lsd/template
> lsd: generate and install manpage

- srcpkgs/kak-lsp/template
> kak-lsp: update to 18.1.2.

- srcpkgs/vaultwarden/template
> vaultwarden: update to 1.33.1.

- srcpkgs/moar/template
- x86_64-musl
- i686 (cross)
@DiegoMagdaleno could you please review the changes??
> moar: update to 1.31.2

- srcpkgs/neovim-qt/template
- I tested the changes in this PR: **YES** (been using it for days)
> neovim-qt: update to 0.2.19, switch to qt6, adopt

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 7.41.0.

- srcpkgs/eza/template
> eza: update to 0.20.20

- srcpkgs/scid_vs_pc/template
> scid_vs_pc: update to 4.26

- srcpkgs/sheldon/template
> sheldon: update to 0.8.1

- srcpkgs/rio/template
> rio: update to 0.2.6

- srcpkgs/srb2/template
> srb2: update to 2.2.15.

- srcpkgs/Komikku/template
- aarch64
- armv7l-musl
- x86_64-musl
> Komikku: update to 1.69.0.

- srcpkgs/python3-dbus/template
- srcpkgs/python3-dbusmock/template
> python3-dbusmock: update to 0.34.2.

- srcpkgs/extension-manager/template
> extension-manager: update to 0.6.1

- srcpkgs/discord/template
> discord: update to 0.0.85

- srcpkgs/kotlin-bin/template
> This is my first time contributing to something like this if I did something wrong or could improve anything please feel free to tell me and sorry in advance if that is the case.
> kotlin-bin: update to 2.1.10 and updated shortdesc

- srcpkgs/glib-networking/template
- srcpkgs/glib/template
> glib: update to 2.82.4.

- srcpkgs/libgweather/patches/a0834413ad51a2e461f9a1aeb813490dc48f2e22.patch
- srcpkgs/libgweather/template
> libgweather: update to 4.4.4.

- srcpkgs/gnome-characters/template
> gnome-characters: update to 47.0.

- srcpkgs/kaccounts-providers/template
- srcpkgs/kf6-kaccounts-integration/patches/cmake-parse-args.patch
- srcpkgs/kf6-kaccounts-integration/template
> kaccounts-providers 24.12

- srcpkgs/rio/template
> rio: update to 0.2.7

- srcpkgs/github-cli/template
> github-cli: update to 2.67.0

- srcpkgs/baobab/template
> baobab: update to 47.0.

- srcpkgs/gnome-boxes/template
> gnome-boxes: update to 47.0.

- srcpkgs/gnome-calculator/template
> gnome-calculator: update to 47.1.

- srcpkgs/gnome-calendar/template
> gnome-calendar: update to 47.0.

- srcpkgs/file-roller/template
> file-roller: update to 44.5.

- srcpkgs/curl/template
> curl: update to 8.12.1

- srcpkgs/vaultwarden/template
> vaultwarden: update to 1.33.2.

- srcpkgs/lf/template
> lf: update to r34.

- srcpkgs/gtk4/template
> gtk4: update to 4.16.12.

- srcpkgs/libadwaita/template
> libadwaita: update to 1.6.4.

- srcpkgs/gnome-maps/template
> gnome-maps: update to 47.4.

- srcpkgs/gnome-weather/template
> gnome-weather: update to 47.0.

- srcpkgs/Signal-Desktop/template
> Signal-Desktop: update to 7.42.0.

- srcpkgs/intel-ucode/template
> intel-ucode: update to 20250211.

- srcpkgs/gnome-system-monitor/template
> gnome-system-monitor: update to 47.1.

- srcpkgs/gnome-music/template
> gnome-music: update to 47.1.

- srcpkgs/gnome-clocks/template
> gnome-clocks: update to 47.0.

- srcpkgs/gnome-text-editor/template
> gnome-text-editor: update to 47.3.

- srcpkgs/zola/template
> zola: update to 0.20.0

- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.13.6.

- srcpkgs/pre-commit/template
> pre-commit: update to 4.1.0.

- srcpkgs/python3-codespell/template
> python3-codespell: update to 2.4.1.

- srcpkgs/python3-path/template
> python3-path: update to 17.1.0.

- srcpkgs/autopep8/template
> autopep8: update to 2.3.2.

- srcpkgs/lets/template
> lets: update to 0.0.55.

- srcpkgs/gnome-contacts/template
> gnome-contacts: update to 47.1.1.

- srcpkgs/gnome-tour/template
> gnome-tour: update to 47.0.

- srcpkgs/sysprof/template
> sysprof: update to 47.2.

- srcpkgs/yamlfmt/template
> yamlfmt: update to 0.16.0.

- srcpkgs/yazi/template
> yazi: update to 25.2.11.

- srcpkgs/epiphany/template
> epiphany: update to 47.3.1.

- srcpkgs/luakit/template
> luakit: update to 2.4.0.

- srcpkgs/gnome-disk-utility/template
> gnome-disk-utility: update to 46.1.

- srcpkgs/ast-grep/template
> ast-grep: update to 0.35.0.

- srcpkgs/difftastic/template
> difftastic: update to 0.63.0.

- srcpkgs/rr/template
> rr: update to 5.9.0

- srcpkgs/mawk/template
> mawk: update to 1.3.4.20250131.

- srcpkgs/nushell/template
> nushell: update to 0.102.0

- srcpkgs/mesa/template
> mesa: update to 24.3.4

- srcpkgs/vscode/template
> vscode: update to 1.97.2

- srcpkgs/xh/template
> xh: update to 0.24.0

- srcpkgs/SDL3/template
> SDL3: update to 3.2.4.

- srcpkgs/luanti/template
> luanti: update to 5.11.0.

- srcpkgs/discord/template
> discord: update to 0.0.86

- common/shlibs
- srcpkgs/emacs/template
- srcpkgs/neovim/template
- srcpkgs/rizin/template
- srcpkgs/tree-sitter/template
> tree-sitter: update to 0.25.2

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.02.17.

- srcpkgs/gnome-connections/template
> gnome-connections: update to 47.2.1.

- srcpkgs/gnote/template
> gnote: update to 47.2.

- srcpkgs/eza/template
> eza: update to 0.20.22

- srcpkgs/celluloid/template
- x86_64-glibc
<br/>
@Gottox could you please review the changes??
> celluloid: update to 0.27

- srcpkgs/clojure-lsp/template
- srcpkgs/mandrel/template
> mandrel: update to 23.1.6.0; clojure-lsp: update to 2025.02.07.

- srcpkgs/cargo-update/template
> cargo-update: update to 16.1.0

- srcpkgs/halloy/template
> halloy: update to 2025.2

- srcpkgs/gnome-sudoku/template
> gnome-sudoku: update to 47.1.1.

- srcpkgs/mesa-asahi/update
> mesa-asahi: fix update check

- srcpkgs/jaq/template
> jaq: update to 2.1.1

- srcpkgs/rust-cargo-audit/template
> rust-cargo-audit: update to 0.21.1

- srcpkgs/lazygit/template
> lazygit: update to 0.46.0.

- srcpkgs/glab/template
> glab: update to 1.53.0.

- srcpkgs/kicad-doc/template
- srcpkgs/kicad/patches/aarch64-musl-ice.patch
- srcpkgs/kicad/patches/fix-linking.patch
- srcpkgs/kicad/template
- srcpkgs/ngspice/template
- srcpkgs/protobuf/template
- **protobuf: install cmake files**
- **ngspice: update to 44.2.**
- **kicad-doc: update to 9.0.0.**
- **kicad: update to 9.0.0.**
> kicad: update to 9.0.0.

- srcpkgs/oxipng/template
> oxipng: update to 9.1.4.

- srcpkgs/hyperrogue/template
> hyperrogue: update to 13.0x

- srcpkgs/power-profiles-daemon/template
> power-profiles-daemon: update to 0.30.

- srcpkgs/codeberg-cli/patches/revert-rust-edition.patch
- srcpkgs/codeberg-cli/template
> codeberg-cli: update to 0.4.9

- srcpkgs/discord/template
Local build testing
I built this PR locally for my native architecture, (x86_64-glibc)
> discord: update to version 0.0.87

- srcpkgs/zoom/template
> zoom: update to 6.3.10.7150

- srcpkgs/labwc/template
> labwc: update to 0.8.3

- srcpkgs/dino/template
> dino: update to 0.4.5.

- srcpkgs/eza/template
> eza: update to 0.20.23

- srcpkgs/inspircd/template
- aarch64-musl
- aarch64
- x86_64-musl
> inspircd: update to 4.5.0

- srcpkgs/ntpd-rs/patches/use-ring.patch
- srcpkgs/ntpd-rs/template
> ntpd-rs: update to 1.5.0

- srcpkgs/nvidia/template
- I tested the changes in this PR: **YES** (played a few games :) )
> nvidia: update to 570.124.04

- srcpkgs/qView/template
CC: @newbluemoon 
related #54541
> qView: switch to qt6

- srcpkgs/mesa-asahi/template
> mesa-asahi: update to 20250221

- srcpkgs/PrismLauncher/template
NOTE: built with -E flag. (dep building took too long)
> PrismLauncher: update to 9.2.

- srcpkgs/lazygit/template
> lazygit: update to 0.48.0

- srcpkgs/ov/template
> ov: update to 0.39.0.

- srcpkgs/yazi/template
> yazi: update to 25.3.2.

- srcpkgs/arti/template
> arti: update to 1.4.0.

- srcpkgs/dust/template
> dust: update to 1.1.2.

- srcpkgs/clifm/template
- I built this PR locally for these architectures (\* crossbuild)
- aarch64 \*
- armv7l-musl \*
> clifm: update to 1.24.

- srcpkgs/font-sarasa-gothic/template
> font-sarasa-gothic: update to 1.0.29.

- srcpkgs/intellij-idea-community-edition/template
> intellij-idea-community-edition: update to 2024.3.4.

- srcpkgs/android-studio/template
> android-studio: update to 2024.2.2.15.

- srcpkgs/steamguard-cli/template
> steamguard-cli: update to 0.16.0

- srcpkgs/github-cli/template
> github-cli: update to 2.68.0

- srcpkgs/github-cli/template
> github-cli: update to 2.68.1

- srcpkgs/discord-ptb/template
> discord-ptb: update to 0.0.132.

- srcpkgs/joker/template
> joker: update to 1.4.1.

- srcpkgs/fselect/template
> fselect: update to 0.8.9.

- srcpkgs/hydroxide/template
> hydroxide: update to 0.2.29.

- srcpkgs/ffsend/template
> ffsend: update to 0.2.77.

- srcpkgs/iwd/template
> iwd: Update to 3.4.

- srcpkgs/gtk+3/template
- Mind I test/run a local classic patched version.
- Update distfile url
- @Gottox 
- aarch64-musl [ok]
- armv7l [ok]
- armv6l-musl [ok]
- x86_64-musl [ok]
- i686 [ok]
> gtk+3: update to 3.24.49.

- srcpkgs/fcft/template
> fcft: update to 3.2.0

- srcpkgs/perl-CGI/template
> perl-CGI: update to 4.67

- srcpkgs/perl-YAML-Tiny/template
> perl-YAML-Tiny: update to 1.76

- srcpkgs/kmahjongg/template
- srcpkgs/libkmahjongg/template
> kmahjongg: update to 24.12.3

- srcpkgs/audex/template
> audex: update to 24.12.3.

- srcpkgs/rustup/patches/0001-Symlink-rustup-instead-of-copying-it.patch
- srcpkgs/rustup/template
> rustup: update to 1.28.1

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.03.10.

- srcpkgs/eza/template
> eza: update to 0.20.24

- srcpkgs/python3-pytest-env/template
> python3-pytest-env: touch for build

- srcpkgs/rio/template
> rio: update to 0.2.10

- srcpkgs/fend/template
> fend: update to 1.5.6

- srcpkgs/ballerburg/template
> ballerburg: update to 1.2.3.

- srcpkgs/libgit2-glib/template
> libgit2-glib: update to 1.2.1

- srcpkgs/ast-grep/template
> ast-grep: update to 0.36.1.

- srcpkgs/cargo-deny/template
> cargo-deny: update to 0.18.2.

- srcpkgs/revive/template
> revive: update to 1.7.0.

- srcpkgs/pex/template
> pex: update to 2.33.4.

- srcpkgs/bombardier/template
> bombardier: update to 2.0.2.

- srcpkgs/halloy/template
> halloy: update to 2025.3

- srcpkgs/starship/template
> starship: update to 1.22.1

- srcpkgs/xwayland-satellite/template
> xwayland-satellite: update to 0.5.1.

- srcpkgs/btdu/template
> btdu: update to 0.6.0.

- srcpkgs/git-absorb/template
> git-absorb: update to 0.7.0.

- srcpkgs/hurl/template
> hurl: update to 6.1.0.

- srcpkgs/just/template
> just: update to 1.40.0

- srcpkgs/senpai/template
> senpai: update to 0.4.0.

- srcpkgs/libheif/template
- srcpkgs/python3-pillow_heif/template
> python3-pillow_heif: update to 0.22.0

- srcpkgs/qsv/template
> qsv: update to 3.2.0.

- srcpkgs/gajim/template
- srcpkgs/python3-nbxmpp/template
* **python3-nbxmpp: update to 6.0.2.**
* **gajim: update to 2.0.3.**
- I built this PR locally for armv6l
> gajim: update to 2.0.3.

- srcpkgs/mutt/template
> mutt: update to 2.2.14

- srcpkgs/zellij/template
> zellij: update to 0.42.0

- srcpkgs/limine/template
> limine: update to 9.2.0.

- srcpkgs/zfs/template
> zfs: update to 2.3.1.

- srcpkgs/vim/template
> vim: update to 9.1.1215.

- common/shlibs
- srcpkgs/ffmpeg/template
- srcpkgs/ffmpeg6/template
- srcpkgs/vmaf/template
> vmaf: update to 3.0.0.

- srcpkgs/platformio/template
> platformio: update to 6.1.18

- srcpkgs/adwaita-icon-theme/template
> adwaita-icon-theme: update to 48.0.

- srcpkgs/slack-desktop/template
> slack-desktop: update to 4.43.43

- srcpkgs/audacity/template
ffmpeg 6 tracking https://github.com/void-linux/void-packages/issues/51522
old pr https://github.com/void-linux/void-packages/pull/51407
~~update: tested. works. some visual glitchery? splash screens are a bit weird, may just be my wm fork?~~
> audacity: update to 3.7.3

- srcpkgs/libgnome-games-support2/template
> libgnome-games-support2: update to 2.0.1

- srcpkgs/mako/template
> mako: update to 1.10.0.

- srcpkgs/github-cli/template
> github-cli: update to 2.69.0

- srcpkgs/heisenbridge/template
> heisenbridge: update to 1.15.2

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.03.17.

- srcpkgs/python3-attrs/template
- srcpkgs/python3-idna/template
- srcpkgs/python3-openssl/template
- srcpkgs/python3-pyasn1-modules/patches/22.patch
- srcpkgs/python3-pyasn1-modules/template
- srcpkgs/python3-pyasn1/template
- srcpkgs/python3-service_identity/template
- srcpkgs/python3-trustme/template
- **python3-openssl: update to 25.0.0.**
- **python3-attrs: update to 25.1.0.**
- **python3-idna: update to 3.10.**
- **python3-pyasn1: update to 0.6.1.**
- **python3-pyasn1-modules: update to 0.4.1.**
- **python3-service_identity: update to 24.2.0.**
- **python3-trustme: update to 1.2.1.**
> python3-trustme: update to 1.2.1 and deps.

- srcpkgs/python3-aiosignal/template
> python3-aiosignal: update to 1.3.2.

- srcpkgs/sfeed/template
- I built this PR locally for my native architecture, amd64
> sfeed: update to 2.2.

- srcpkgs/nvidia/template
> nvidia: update to 570.133.07.

- common/shlibs
- srcpkgs/scenefx/template
- srcpkgs/swayfx/template
> scenefx: update to 0.2.1.

- srcpkgs/mise/template
> mise: update to 2025.3.7.

- srcpkgs/zellij/template
> zellij: update to 0.42.1

- srcpkgs/ast-grep/template
> ast-grep: update to 0.36.2.

- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.13.9.

- srcpkgs/blueprint-compiler/template
- srcpkgs/gnome-sudoku/template
> blueprint-compiler: update to 0.16.0; gnome-sudoku: update to 48.0.

- srcpkgs/totem/template
> totem: update to 43.1

- srcpkgs/evolution-data-server/template
- srcpkgs/evolution-ews/template
- srcpkgs/evolution/template
> evolution{,-data-server,-ews}: update to 3.56.0

- srcpkgs/python3-gobject/template
> python3-gobject: update to 3.52.3

- srcpkgs/ghex/template
> ghex: update to 46.2

- srcpkgs/orca/template
> orca: update to 48.0

- srcpkgs/gvfs/template
> gvfs: update to 1.56.1

- srcpkgs/aisleriot/template
> aisleriot: update to 3.22.35

- srcpkgs/gnome-nibbles/template
> gnome-nibbles: update to 4.2.0

- srcpkgs/gnome-chess/template
> gnome-chess: update to 48.0

- srcpkgs/five-or-more/template
> five-or-more: update to 48.0

- srcpkgs/swell-foop/template
> swell-foop: update to 48.0

- srcpkgs/kak-lsp/template
> kak-lsp: update to 18.1.3.

- srcpkgs/skim/template
> skim: update to 0.16.1

- srcpkgs/limine/template
> limine: update to 9.2.1.

- srcpkgs/discord/template
> discord: update to 0.0.89

- srcpkgs/dbus/template
> dbus: update to 1.16.2.

- srcpkgs/gnome-epub-thumbnailer/template
> gnome-epub-thumbnailer: update to 1.8

- srcpkgs/cairo/template
- srcpkgs/gtk4/patches/remove-failing-tests.patch
- srcpkgs/gtk4/template
- srcpkgs/pango/template
@cinerea0
gtk4 requires new versions of cairo, and pango.
> gtk4: update to 4.18.2

- srcpkgs/zenity/template
> zenity: update to 4.0.5

- srcpkgs/libadwaita/template
> libadwaita: update to 1.7.0.

- srcpkgs/nautilus/template
> nautilus: update to 48.0.

- srcpkgs/rio/template
> rio: update to 0.2.12

- srcpkgs/SDL3/template
> SDL3: update to 3.2.8.

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.03.24.

- srcpkgs/gnome-characters/template
> gnome-characters: update to 48.0

- srcpkgs/tecla/template
> tecla: update to 48.0.2

- srcpkgs/speakersafetyd/files/speakersafetyd/run
- srcpkgs/speakersafetyd/template
WIP: pending upstream pr https://github.com/AsahiLinux/speakersafetyd/pull/24
> speakersafetyd: run as non-root

- srcpkgs/furnace/template
> furnace: update to 0.6.8

- srcpkgs/fselect/template
> fselect: update to 0.8.11.

- srcpkgs/gupnp/patches/fix-tests.patch
- srcpkgs/gupnp/template
> gupnp: update to 1.6.7

- srcpkgs/rygel/template
> rygel: update to 0.44.2

- srcpkgs/gcr4/template
> gcr4: update to 4.4.0.1

- srcpkgs/gnome-calculator/template
> gnome-calculator: update to 48.0

- srcpkgs/eza/template
> eza: update to 0.21.0

- srcpkgs/furnace/template
> furnace: update to 0.6.8.1

- srcpkgs/dust/template
> dust: update to 1.2.0.

- srcpkgs/topgrade/template
> topgrade: update to 16.0.3

- srcpkgs/godot/patches/20-fix-musl.patch
- srcpkgs/godot/template
> godot: update to 4.4.1

- srcpkgs/limine/template
> limine: update to 9.2.2.

- srcpkgs/discord/template
> discord: update to 0.0.90.

- srcpkgs/opera/template
<br/>
@mobinmob could you please review the changes
And, thanks for your time
> opera: update to 117.0.5408.93

- srcpkgs/libsfdo/template
> libsfdo: update to 0.1.4

- srcpkgs/stagit/template
> stagit: rebuild for libgit2-1.9

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.03.31.

- srcpkgs/dua-cli/template
> dua-cli: update to 2.30.0.

- srcpkgs/fnott/template
> fnott: update to 1.7.1.

- srcpkgs/pari/template
> pari: update to 2.17.2.

- srcpkgs/primecount/template
- srcpkgs/primesieve/template
- **primesieve: update to 12.7.**
- **primecount: update to 7.15.**
> update to primecount-7.15, primesieve-12.7

- srcpkgs/kup/template
> kup: rebuild for libgit2-1.9

- srcpkgs/xdg-user-dirs-gtk/template
> xdg-user-dirs-gtk: update to 0.14

- srcpkgs/cargo-update/template
> cargo-update: update to 16.2.1

- srcpkgs/halloy/template
> halloy: update to 2025.4

- srcpkgs/foliate/template
> foliate: update to 3.3.0

- srcpkgs/QLC+/template
> QLC+: Update to 4.14.1.

- srcpkgs/linux-mainline/template
> linux-mainline: update to 6.14

- srcpkgs/atuin/template
> atuin: update to 18.5.0

- srcpkgs/fuzzel/template
> fuzzel: update to 1.12.0

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.04.07.

- srcpkgs/openjdk-common/INSTALL
- srcpkgs/openjdk-common/REMOVE
- srcpkgs/openjdk-common/template
- srcpkgs/openjdk11/template
- srcpkgs/openjdk17/template
- srcpkgs/openjdk21/template
- srcpkgs/openjdk8/template
> OpenJDK use system ca certs

- srcpkgs/gnome-ssh-askpass/template
- srcpkgs/openssh/patches/sshd_config.patch
- srcpkgs/openssh/patches/time_t.patch
- srcpkgs/openssh/template
> openssh: update to 10.0p1.

- srcpkgs/scrcpy/template
> scrcpy: update to 3.2.

- srcpkgs/limine/template
> limine: update to 9.2.3.

- srcpkgs/mise/template
> mise: update to 2025.4.2.

- srcpkgs/cargo-about/template
> cargo-about: update to 0.7.1.

- srcpkgs/treefmt/template
> treefmt: update to 2.2.1.

- srcpkgs/lua-language-server/template
> lua-language-server: update to 3.14.0.

- srcpkgs/hurl/template
> hurl: update to 6.1.1.

- srcpkgs/pueue/template
> pueue: update to 4.0.0.

- srcpkgs/dbeaver/template
- I built this PR locally for my native architecture, x86_64.
> dbeaver: update to 25.0.2.

- srcpkgs/github-cli/template
> github-cli: update to 2.70.0

- srcpkgs/ov/template
> ov: update to 0.40.1.

- srcpkgs/google-chrome/template
> google-chrome: update to 135.0.7049.84.

- srcpkgs/discord/template
> discord: update to 0.0.91.

- srcpkgs/spotify/template
> spotify: update to 1.2.59.

- srcpkgs/font-sarasa-gothic/template
> font-sarasa-gothic: update to 1.0.30.

- srcpkgs/slack-desktop/template
> slack-desktop: update to 4.43.51

- srcpkgs/PrismLauncher/template
> PrismLauncher: update to 9.4

- srcpkgs/seaweedfs/template
> seaweedfs: update to 3.86.

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.04.14.

- srcpkgs/libadwaita/template
> libadwaita: update to 1.7.2

- srcpkgs/nautilus/template
> nautilus: update to 48.1

- srcpkgs/eza/template
> eza: update to 0.21.1

- srcpkgs/restic/template
> restic: update to 0.18.0.

- srcpkgs/m17n-db/template
> m17n-db: update to 1.8.10

- srcpkgs/ast-grep/template
> ast-grep: update to 0.37.0.

- srcpkgs/fish-shell/template
> fish-shell: update to 4.0.2

- common/shlibs
- srcpkgs/OpenTimelineIO-devel
- srcpkgs/OpenTimelineIO/patches/0001-Use-System-rapidjson.patch
- srcpkgs/OpenTimelineIO/patches/0002-43de3e5065c860865ede0c0bbb879578c7b325a2.patch
- srcpkgs/OpenTimelineIO/patches/0099-cmake.patch
- srcpkgs/OpenTimelineIO/template
- srcpkgs/rapidjson/patches/0002-GenericStreamWrapper.patch
- srcpkgs/rapidjson/patches/0003-GenericStreamWrapper.patch
- srcpkgs/rapidjson/patches/0004-cursorstreamwrapper.patch
- srcpkgs/rapidjson/patches/0005-cursorstreamwrapper.patch
- srcpkgs/rapidjson/patches/3b2441b87f99ab65f37b141a7b548ebadb607b96.patch
- srcpkgs/rapidjson/patches/5d9d0f78b53dd8cd1ec757fd8ef07211ee114161.patch
- srcpkgs/rapidjson/patches/CVE-2024-38517.patch
- srcpkgs/rapidjson/template
- **rapidjson: gcc14 compat, backport cursorstreamwrapper**
- **New package: OpenTimelineIO-0.17.0**
> New package: OpenTimelineIO-0.17.0

- srcpkgs/senpai/template
> senpai: update to 0.4.1

- srcpkgs/virtualbox-ose/template
> virtualbox-ose: update to 7.1.8.

- srcpkgs/discord/template
> discord: update to 0.0.92

- srcpkgs/yakuake/template
> yakuake: update to 25.04.0

- srcpkgs/gerbera/template
I no longer use gerbera and don't have active UPNP client devices anymore to test new releases.
> gerbera: orphan.

- srcpkgs/github-cli/template
> github-cli: update to 2.71.0

- srcpkgs/tealdeer/template
> tealdeer: update to 1.7.2

- srcpkgs/steamguard-cli/template
> steamguard-cli: update to 0.17.0

- srcpkgs/iniparser/template
> iniparser: update to 4.2.6

- srcpkgs/valkey/template
> valkey: update to 8.1.1.

- srcpkgs/github-cli/template
> github-cli: update to 2.71.1

- srcpkgs/Tuba/template
> Tuba: update to 0.9.2.

- srcpkgs/github-cli/template
> github-cli: update to 2.71.2

- srcpkgs/eza/template
> eza: update to 0.21.2

- srcpkgs/emptty/template
> emptty: update to 0.14.0

- srcpkgs/lazygit/template
> lazygit: update to 0.49.0.

- srcpkgs/direnv/template
> direnv: update to 2.36.0.

- srcpkgs/strace/template
> strace: update to 6.14.

- srcpkgs/jaq/template
> jaq: update to 2.2.0

- srcpkgs/pipe-viewer/template
> pipe-viewer: update to 0.5.6

- srcpkgs/prosody/template
> prosody: update to 13.0.1

- srcpkgs/tigervnc/template
> tigervnc: update to 1.15.0

- srcpkgs/LibreCAD/template
> LibreCAD: update to 2.2.1.1

- srcpkgs/neovim/template
> neovim: update to 0.11.1

- srcpkgs/perl-CGI/template
> perl-CGI: update to 4.68

- srcpkgs/perl-CryptX/template
> perl-CryptX: update to 0.085

- srcpkgs/perl-Sub-Name/template
> perl-Sub-Name: update to 0.28

- srcpkgs/perl-Specio/template
> perl-Specio: update to 0.50

- srcpkgs/gdu/template
> gdu: update to 5.30.1.

- srcpkgs/uncrustify/template
> uncrustify: update to 0.80.1, adopt

- srcpkgs/lighttpd/template
- Tested across a matrix of architectures in github runners in the lighttpd CI.
supercedes #54802
> lighttpd: update to 1.4.79

- common/shlibs
- srcpkgs/libcupsfilters/template
- srcpkgs/python3-pikepdf/template
- srcpkgs/qpdf/template
cc: @benalb 
EDIT 4/15/25: qpdf updated to 12.1.0
- I also built this PR for x86_64-musl
> qpdf: update to 12.1.0

- srcpkgs/nvidia/template
> nvidia: update to 570.144.

- srcpkgs/spotify/template
> spotify: update to 1.2.60.

- srcpkgs/lf/template
> lf: update to r35.

- srcpkgs/libfishsound/template
> libfishsound: update to 1.0.1

- srcpkgs/qutebrowser/template
- I built this PR locally for my native architecture, x86_64/glibc
> qutebrowser: update to 3.5.0

- srcpkgs/khard/template
> khard: update to 0.19.1

- srcpkgs/mitmproxy/template
> Update mitm_update to 11.1.3

- srcpkgs/github-cli/template
> github-cli: update to 2.72.0

- srcpkgs/yt-dlp/template
> yt-dlp: update to 2025.04.30

- srcpkgs/vte3/patches/a33d089c1d2b669ee932df9a8b29236934102aad.patch
- srcpkgs/vte3/template
> vte3: update to 0.80.1

- srcpkgs/snapshot/template
> snapshot: update to 48.0.1

- common/shlibs
- srcpkgs/clapper-devel
- srcpkgs/clapper-libs
- srcpkgs/clapper/template
- srcpkgs/newsflash/template
> newsflash: update to 3.3.5.

- srcpkgs/evolution-data-server/template
- srcpkgs/evolution-ews/template
- srcpkgs/evolution/template
> evolution{,-data-server,-ews}: update to 3.56.1

- srcpkgs/eza/template
> eza: update to 0.21.3

- srcpkgs/sox/patches/gcc14.patch
- srcpkgs/sox/template
> sox: fix build with gcc14

- srcpkgs/xh/template
> xh: update to 0.24.1

- srcpkgs/rio/template
> rio: update to 0.2.13

- srcpkgs/qsv/template
> qsv: update to 4.0.0.

- srcpkgs/git-absorb/template
> git-absorb: update to 0.8.0.

- srcpkgs/primecount/template
- srcpkgs/primesieve/template
- **primesieve: update to 12.8.**
- **primecount: update to 7.17.**
> update to primesieve-12.8, primecount-7.17

- srcpkgs/diffstat/template
> diffstat: update to 1.68.

- srcpkgs/discord/template
> discord: update to 0.0.94

- srcpkgs/halloy/template
> halloy: update to 2025.5

- srcpkgs/rust-analyzer/template
> rust-analyzer: update to 2025.05.05.

- srcpkgs/atuin/template
> atuin: update to 18.6.0

- srcpkgs/glab/template
> glab: update to 1.57.0.

- srcpkgs/gum/template
> gum: update to 0.16.0

- srcpkgs/merkaartor/patches/75223944dc3e61fbe124a0677af709cdd7c83028.patch
- srcpkgs/merkaartor/template
- srcpkgs/proj/template
- **merkaartor: update to 0.20.0.**
- **proj: update to 9.5.1.**
> WIP: merkaartor: update to 0.20.0

- srcpkgs/atuin/template
> atuin: update to 18.6.1

- srcpkgs/limine/template
> limine: update to 9.3.0.

- srcpkgs/openldap/INSTALL
- srcpkgs/openldap/template
> openldap: use make_dirs.

- common/shlibs
- srcpkgs/catgirl/template
- srcpkgs/geomyidae/template
- srcpkgs/got/template
- srcpkgs/libtls/template
- srcpkgs/litterbox/template
- srcpkgs/openntpd/template
- srcpkgs/pounce/template
- srcpkgs/sacc/template
> libtls: update to 4.1.0.

- srcpkgs/sequoia-sop/template
- srcpkgs/sequoia-sq/template
- srcpkgs/sequoia-sqv/template
- **sequoia-sq: update to 1.3.1.**
- **sequoia-sqv: update to 1.3.0.**
- **sequoia-sop: update to 0.37.1.**
> sequoia updates

- srcpkgs/trurl/template
> trurl: update to 0.16.1.

- srcpkgs/stern/template
> stern: update to 1.32.0

- srcpkgs/tree-sitter/template
> tree-sitter: update to 0.25.4

- srcpkgs/rio/template
> rio: update to 0.2.15

- srcpkgs/satty/template
- https://github.com/void-linux/void-packages/pull/51550
- https://github.com/void-linux/void-packages/pull/50640
- https://github.com/void-linux/void-packages/pull/50611
> New package: satty

- srcpkgs/vips/template
> vips: update to 8.16.1.

- srcpkgs/bc/template
- x86_64-musl
- i686-musl
- i686
- aarch64-musl
- aarch64
- armv7l-musl
- armv7l
- armv6l-musl
- arm6l
> bc: update to 1.08.1

- srcpkgs/newsraft/template
> newsraft: update to 0.30

- srcpkgs/freerdp3/template
> freerdp3: update to 3.15.0

- srcpkgs/swayimg/template
> swayimg: update to 3.9.

- srcpkgs/intel-ucode/template
> intel-ucode: update to 20250512.

- srcpkgs/remind/template
> remind: update to 05.03.07.

- srcpkgs/mise/template
> mise: update to 2025.5.6.

- srcpkgs/cameractrls/template
> New package: cameractrls-0.6.7

- srcpkgs/ffsend/template
- srcpkgs/websocat/template
> ffsend, websocat: fix for Rust 1.87

- srcpkgs/Thunar/template
> Thunar: update to 4.30.3. adopt

- srcpkgs/discord/template
- I built this PR locally for my native architecture **x86_64**
> discord: update to 0.0.95

- srcpkgs/github-cli/template
> github-cli: update to 2.73.0

- srcpkgs/rio/template
> rio: update to 0.2.16
