void-linux/void-packages

srcpkgs/ov/template

ov: update to 0.41.0.

---

srcpkgs/oxipng/template

oxipng: update to 9.1.5.

---

srcpkgs/lazygit/template

lazygit: update to 0.50.0.

---

srcpkgs/libinput/template

libinput: update to 1.28.1

---

srcpkgs/AusweisApp2/template

AusweisApp2: update to 2.3.1.

---

srcpkgs/goldendict/template

maintainer ping @Johnnynator 
[changes since 1.5.0](https://github.com/goldendict/goldendict/releases/tag/1.5.1)
- I also cross-built it for aarch64-musl

goldendict: update to 1.5.1

---

srcpkgs/limine/template

limine: update to 9.3.2.

---

srcpkgs/postgresql16/template
srcpkgs/postgresql17/template

postgresql17: update to 17.5. 

---

srcpkgs/dehydrated/template

dehydrated: update to 0.7.2

---

srcpkgs/memray/patches/rm-snapshopt-config.patch
srcpkgs/memray/template
srcpkgs/python3-textual/template

python3-textual: update to 2.1.2; memray: update to 1.16.0.

---

srcpkgs/hg-evolve/template

hg-evolve: update to 11.1.8.

---

srcpkgs/sheldon/template

sheldon: update to 0.8.2

---

srcpkgs/perl-CryptX/template

perl-CryptX: update to 0.086

---

srcpkgs/acme.sh/template

acme.sh: update to 3.1.1

---

srcpkgs/pgmetrics/template

pgmetrics: update to 1.17.1.

---

srcpkgs/erlang/template

erlang: update to 26.2.5.5

---

srcpkgs/kdenlive/template

kdenlive: update to 25.04.1.

---

srcpkgs/google-earth-pro/template

google-earth-pro: update to 7.3.6.10201.

---

srcpkgs/ripgrep-all/template

ripgrep-all: update to 0.10.9.

---

srcpkgs/enchant2-aspell
srcpkgs/enchant2-hunspell
srcpkgs/enchant2-nuspell
srcpkgs/enchant2-voikko
srcpkgs/enchant2/template
srcpkgs/libenchant2

enchant2: update to 2.8.2.

---

srcpkgs/asahi-audio/template
srcpkgs/triforce/template

asahi audio updates

---

srcpkgs/yt-dlp/template

yt-dlp: update to 2025.05.22

---

srcpkgs/pnpm/template

pnpm: update to 10.4.1.

---

srcpkgs/runc/template

runc: update to 1.2.5.

---

srcpkgs/SDL3/template

SDL3: update to 3.2.14

---

srcpkgs/ergo/template

ergo: update to 2.16.0.

---

srcpkgs/openldap/template

- I built this PR locally for my native architecture, (x86_64-musl, x86_64-glibc)
- aarch64-musl
- armv7l
- armv6l-musl

openldap: update to 2.6.10

---

srcpkgs/dnsdist/template

dnsdist: update to 1.9.10

---

srcpkgs/rust-sccache/template

rust-sccache: update to 0.10.0.

---

srcpkgs/instaloader/template

- x86_64-musl
maintainer ping @fosslinux

instaloader: update to 4.14.1

---

srcpkgs/freeciv/template

Tested: sdl, gtk3 & qt6 frontends on x86_64-musl, all running a few turns into new games.

freeciv: update to 3.1.5

---

srcpkgs/clifm/template

clifm: update to 1.25.

---

srcpkgs/inxi/template

inxi: update to 3.3.38.1

---

srcpkgs/python3-PyOpenGL-accelerate/template
srcpkgs/python3-PyOpenGL/template

- I tested the changes in this PR: **YES** (checking fixes while working on my own python3 program that uses pyopengl)
- armv7l-glibc (crossbuild)

PyOpenGL: upgrade to 3.1.9

---

srcpkgs/xiccd/template

xiccd: update to 0.4.1.

---

srcpkgs/passt/template

passt: update to 2025.05.12.8ec1341.

---

srcpkgs/walker/template

walker: update to 0.12.23.

---

srcpkgs/neovim/template

neovim: update to 0.11.2

---

srcpkgs/limine/template

limine: update to 9.3.3.

---

srcpkgs/Quaternion/template
srcpkgs/libQuotient/template
srcpkgs/neochat/template

libQuotient: update to 0.9.3 and client updates

---

srcpkgs/conduit/template

conduit: update to 0.10.4.

---

srcpkgs/radicale/template

radicale: update to 3.5.4.

---

srcpkgs/pnpm/template

pnpm: update to 10.11.0.

---

srcpkgs/swayimg/template

swayimg: update to 4.1.

---

srcpkgs/tint/template

- aarch64-musl
- armv7l
- armv6l-musl

New package: tint-0.1.3

---

srcpkgs/eqonomize/template

- armv7l
- armv6l-musl
- aarch64-musl

eqonomize: update to 1.5.10

---

srcpkgs/python3-ocrmypdf/patches/use_pillow_heif_instead_of_pi_heif.patch
srcpkgs/python3-ocrmypdf/template

python3-ocrmypdf: update to 16.10.2

---

srcpkgs/shikane/template

- x86_64-musl
- i686
Closes #55153

New package: shikane-1.0.1

---

srcpkgs/cargo-machete/template

- I tested the changes in this PR: **YES** (I ran it against a Rust project of mine and got a list of unused deps)

New package: cargo-machete-0.8.0

---

srcpkgs/intellij-idea-community-edition/template

intellij-idea-community-edition: update to 2025.1.1.1.

---

srcpkgs/nnn/template

nnn: update to 5.1.

---

srcpkgs/caligula/template

- x86_64-musl
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

New package: caligula-0.4.8

---

srcpkgs/anubis/files/anubis/run
srcpkgs/anubis/patches/npm-assets.diff
srcpkgs/anubis/template
srcpkgs/esbuild/template

Crossbuilt from x86_64-glibc to aarch64-musl and tested on aarch64-musl

New package: anubis-1.16.0.

---

srcpkgs/choose/template

New package: choose-v1.3.6

---

srcpkgs/gaupol/template

New package: gaupol-1.15

---

srcpkgs/matcha/template

New package: matcha-2.1.0

---

srcpkgs/age-plugin-yubikey/template

- I built this PR locally for my native architecture, (x86_64-glibc, aarch64-glibc)

New package: age-plugin-yubikey-0.5.0

---

srcpkgs/tailspin/template

- I built this PR locally for ALL architectures

New package: tailspin-5.4.2

---

srcpkgs/bibiman/template

- I tested the changes in this PR: **Yes**
*PS*: original PR was #52954, but I messed it up due to unreckognized rebase and following force-push on wrong branch. Thus, I had to reopen it again. Wont happen again. Sorry for the inconvenience!

New package: bibiman-0.11.4

---

srcpkgs/Apktool/files/Apktool
srcpkgs/Apktool/template

New package: Apktool-2.10.0

---

srcpkgs/dune3d/template

New package: dune3d-1.3.0

---

srcpkgs/cliflux/template

New package: cliflux-1.4.4

---

srcpkgs/kew/template

- I built this PR locally for my native architecture, (X86-64_GLIBC)

New package: kew-3.3.2

---

srcpkgs/typos/template

- I built this PR locally for my native architecture,  x86_64-glibc
- armv6l-musl

New package: typos-1.29.9

---

srcpkgs/cmake-language-server/template
srcpkgs/python3-lsprotocol/template
srcpkgs/python3-pygls/template

- I built this PR locally for my native architecture, (GLIBC-X86_64)

New package: cmake-language-server-0.1.11

---

srcpkgs/python3-pylsp-mypy/template

- I built this PR locally for my native architecture, (GLIBC-X86_64)

New package: python3-pylsp-mypy-0.6.9

---

srcpkgs/pika-backup/patches/remove-git-describe.patch
srcpkgs/pika-backup/template

New package: pika-backup-0.7.4

---

srcpkgs/json2tsv/template

New package: json2tsv-1.2

---

srcpkgs/bmaptool/template

New package: bmaptool-3.9.0

---

srcpkgs/sway/template

- I built this PR locally for these architectures (\* crossbuild):
- aarch64 \*
- x86_64-musl \*

sway: update to 1.10.1.

---

srcpkgs/typos/template

typos: update to 1.32.0.

---

srcpkgs/labwc-menu-generator/template

- I built this PR locally for my native architecture, x64 glibc

New package: labwc-menu-generator-0.2.0

---

srcpkgs/Apktool/template

Apktool: update to 2.11.1.

---

srcpkgs/fx/template

fx: update to 36.0.3.

---

srcpkgs/gitui/template

- i686
- x86_64-musl
cc: @cinerea0

gitui: update to 0.27.0.

---

srcpkgs/pmbootstrap/template

pmbootstrap: update to 3.4.2.

---

srcpkgs/nethogs/template

nethogs: update to 0.8.8.

---

srcpkgs/wmenu/template

wmenu: update to 0.2.0

---

srcpkgs/discord/template

discord: update to 0.0.96

---

srcpkgs/lms/template

lms: update to 3.66.1.

---

srcpkgs/gtkmm4/template

gtkmm4: update to 4.18.0.

---

srcpkgs/better-control/template

better-control: update to 6.12.0.

---

srcpkgs/jadx/template

jadx: install desktop entry for jadx-gui

---

srcpkgs/geckodriver/template

- I built this PR locally for my native architecture, (**x86_64**)

geckodriver: update to 0.36.0

---

srcpkgs/uptimed/template

uptimed: update to 0.4.7.

---

srcpkgs/gnome-sudoku/template

gnome-sudoku: update to 48.1.

---

srcpkgs/gnome-connections/template

gnome-connections: update to 48.0

---

srcpkgs/gnome-calculator/template

gnome-calculator: update to 48.1

---

srcpkgs/baobab/template

baobab: update to 48.0

---

srcpkgs/epiphany/template

epiphany: update to 48.3

---

srcpkgs/gnome-system-monitor/template

gnome-system-monitor: update to 48.1

---

srcpkgs/gnome-calendar/template

gnome-calendar: update to 48.1

---

srcpkgs/gjs/template

gjs: update to 1.84.2

---

srcpkgs/gnome-initial-setup/template

gnome-initial-setup: update to 48.1

---

srcpkgs/gnome-tour/template

gnome-tour: update to 48.1

---

srcpkgs/gnome-user-docs/template

gnome-user-docs: update to 48.1

---

srcpkgs/curl/template

curl: update to 8.14.1

---

srcpkgs/libspelling/template

libspelling: update to 0.4.8

---

srcpkgs/ast-grep/template

ast-grep: update to 0.38.4.

---

srcpkgs/kakoune/template

kakoune: update to 2025.06.03

---

srcpkgs/evolution-data-server/template
srcpkgs/evolution-ews/template
srcpkgs/evolution/template

evolution{,-data-server,-ews}: update to 3.56.2

---

srcpkgs/usbguard/template

usbguard: create required rules.d directory

---

srcpkgs/dosbox/template

dosbox: adding debug mode as a build option

---

srcpkgs/rio/template

rio: update to 0.2.17

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2025.06.02.

---

srcpkgs/sq/template

sq: update to 0.48.5.

---

srcpkgs/gnome/template

gnome: remove duplicated gnome-music from -apps.

---

srcpkgs/onefetch/template

onefetch: update to 2.24.0

---

srcpkgs/carapace/template

carapace: update to 1.3.2.

---

srcpkgs/libgexiv2/template

libgexiv2: update to 0.14.5

---

srcpkgs/m17n-lib/template

- I tested the changes in this PR: **NO** (change log says only configure script fixes)
- x86_64-musl
- i868

m17n-lib: update to 1.8.5

---

srcpkgs/rosegarden/template

rosegarden: update to 24.12.1

---

common/shlibs
srcpkgs/libgit2-1.8/template
srcpkgs/libgit2-1.9/template
srcpkgs/llhttp/template

libgit2-*: routine updates

---

srcpkgs/rio/template

rio: update to 0.2.18

---

srcpkgs/supersonic-desktop/template

supersonic-desktop: install icons to default hicolor theme

---

srcpkgs/yadm/template

yadm: update to 3.5.0.

---

srcpkgs/exult/template

- I built this PR locally for these architectures (if supported. mark crossbuilds): None

New package: exult-1.12.0

---

srcpkgs/CastXML/template

- I built this PR locally for my native architecture, (x86_64-glibx)
- aarch64
- armv7l
- armv6l
- i686
- Update version
- Update checksum

CastXML: update to 0.6.11.

---

srcpkgs/treefmt/template

treefmt: update to 2.3.1.

---

srcpkgs/primecount/template
srcpkgs/primesieve/template
srcpkgs/python3-primecountpy/template

- **primesieve: update to 12.9.**
- **primecount: update to 7.19.**
- **python3-primecountpy: update to 0.1.1.**

update primesieve-12.9, primecount-7.19, primecountpy-0.1.1

---

srcpkgs/nikto/template

Web-server vulnerability scanner.
- https://github.com/sullo/nikto
- https://cirt.net/Nikto2

New package: nikto-2.5.0

---

srcpkgs/pyradio/template

Minimal changes, checked on a VM

Update template for 0.9.3.11.13

---

srcpkgs/powerline-go/template

- I built this PR locally for my native architecture, x86_64 (glibc)
- aarch64
- aarch64-musl
- armv6l
- armv6l-musl
- i686 
- i686-musl
- x86_64-musl
There were 2 failed attempts by others to push this upstream, here's my two cents as 3rd attempt:
https://github.com/void-linux/void-packages/pull/23361
https://github.com/void-linux/void-packages/pull/34806

New package: powerline-go-1.25

---

srcpkgs/wl-clip-persist/template

New package: wl-clip-persist-0.4.3

---

srcpkgs/zwm/patches/fix-makefile.patch
srcpkgs/zwm/patches/fix-musl.patch
srcpkgs/zwm/template

New package: zwm-0.1.2

---

srcpkgs/shotwell/template

shotwell: update to 0.32.10

---

srcpkgs/gnome-usage/template

gnome-usage: update to 46.1

---

srcpkgs/extension-manager/template

extension-manager: update to 0.6.3

---

srcpkgs/amberol/template

amberol: update to 2025.1

---

srcpkgs/sov/template

New package: sov-0.95

---

srcpkgs/python3-pulsectl/template

python3-pulsectl: update to 24.12.0.

---

srcpkgs/gajim/template
srcpkgs/python3-nbxmpp/template

* **python3-nbxmpp: update to 6.2.0.**
* **gajim: update to 2.2.0.**
- I built this PR locally for armv6l

gajim: update to 2.2.0.

---

srcpkgs/xonsh/template

xonsh: update to 0.19.3

---

srcpkgs/Komikku/template

Komikku: update to 1.75.0.

---

common/shlibs
srcpkgs/kwin-effects-forceblur/template

New package: kwin-effects-forceblur-1.3.6

---

srcpkgs/libqalculate/template
srcpkgs/qalculate-gtk/template
srcpkgs/qalculate-qt/template

qalculate{-gtk,qt}: update to 5.5.2, 5.5.1

---

srcpkgs/qownnotes/template

- I built this PR locally for my native architecture,  (x86_64,glibc)

qownnotes: update to 25.3.3.

---

srcpkgs/SDL2/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

SDL2: update to 2.32.8.

---

srcpkgs/shfmt/template

shfmt: update to 3.11.0

---

srcpkgs/mgba/template

mgba: update to 0.10.5.

---

srcpkgs/zoom/template

zoom: update to 6.4.5.1259

---

srcpkgs/minicom/template

minicom: update to 2.10.

---

srcpkgs/python3-chess/template

python3-chess: update to 1.11.2.

---

srcpkgs/dooble/patches/translations-dooble_application.patch
srcpkgs/dooble/template

dooble: update to 2025.02.28.

---

srcpkgs/k9s/template

k9s: update to 0.50.6, adopt.

---

srcpkgs/phpMyAdmin/template

phpMyAdmin: update to 5.2.2

---

srcpkgs/himalaya/template

himalaya: update to 1.1.0.

---

srcpkgs/bovo/template

bovo: update to 25.04.2

---

srcpkgs/mpd/template

mpd: update to 0.23.17.

---

srcpkgs/git-delete-merged-branches/template

git-delete-merged-branches: update to 7.5.0.

---

srcpkgs/passff-host/template

passff-host: update to 1.2.5.

---

srcpkgs/qtractor/template

qtractor: update to 1.5.3

---

srcpkgs/jp2a/template

jp2a: update to 1.3.2

---

srcpkgs/ruff/template

ruff: update to 0.11.2.

---

srcpkgs/picmi/template

picmi: update to 25.04.2

---

srcpkgs/cargo-modules/template

cargo-modules: update to 0.24.2.

---

srcpkgs/winegui/template

winegui: Update to 2.8.1

---

srcpkgs/clojure/template

clojure: update to 1.12.0.1530.

---

srcpkgs/sprec/template

New package: sprec-0.1

---

srcpkgs/pet/template

New package: pet-1.0.1

---

srcpkgs/netscanner/template

New package: netscanner-0.6.2

---

srcpkgs/synapse-compress-state/template

New package: synapse-compress-state-0.1.4

---

srcpkgs/OpenRCT2/patches/i686-FormatToken.patch
srcpkgs/OpenRCT2/patches/time_t-musl.patch
srcpkgs/OpenRCT2/template

OpenRCT2: update to 0.4.22.

---

srcpkgs/gradle/template

gradle: update to 8.14.1.

---

srcpkgs/Solaar/template
srcpkgs/python3-dbus/template
srcpkgs/python3-evdev/template

 Solaar: update to 1.1.14.

---

srcpkgs/runit/files/sv
srcpkgs/runit/template

runit: add SVDIR support to bash completion

---

srcpkgs/freecol/template

- I built this PR locally for these architectures (if supported. mark crossbuilds): None

New package: freecol-1.2.0

---

srcpkgs/lite-xl/template

- I tested the changes in this PR:**briefly**

lite-xl: update to 2.1.8

---

srcpkgs/tlp/template

tlp: update to 1.8.0

---

srcpkgs/strace/template

strace: update to 6.15.

---

srcpkgs/benchmark/template

- aarch64
- armv7l
- armv6l
- i686
- Updated version
- Updated checksum

benchmark: update to 1.9.4.

---

srcpkgs/zcfan/files/README.voidlinux
srcpkgs/zcfan/files/zcfan/run
srcpkgs/zcfan/template

New package: zcfan-1.4.0

---

srcpkgs/blocky/files/blocky/run
srcpkgs/blocky/template

- I built this PR locally for my native architecture, (aarch64-musl)
- x86_64 (cross)

New package: blocky-0.26.2

---

srcpkgs/rawtherapee/template

- I built this PR locally for my native architecture, x86_64-glibc, aarch64-glibc
- x86_64
- x86_64-musl
- i686
- aarch64

rawtherapee: update to 5.12.

---

srcpkgs/icewm/template

- I built this PR locally for these architectures (if supported. mark crossbuilds):  
- armv7l

icewm: update to 3.7.5.

---

srcpkgs/UxPlay/template

UxPlay: update to 1.72.1.

---

srcpkgs/gum/template

gum: update to 0.16.1

---

srcpkgs/github-cli/template

github-cli: update to 2.74.1

---

srcpkgs/chromium/patches/llvm19.patch
srcpkgs/chromium/patches/musl-no-sandbox-settls.patch
srcpkgs/chromium/patches/musl-tid-caching.patch
srcpkgs/chromium/patches/pdfium-fix-build-with-system-libpng.patch
srcpkgs/chromium/template

chromium: update to 137.0.7151.55.

---

srcpkgs/furnace/template

furnace: update to 0.6.8.3

---

srcpkgs/swayimg/template

swayimg: update to 4.2.

---

srcpkgs/revive/template

revive: update to 1.10.0.

---

srcpkgs/ruff/template

ruff: update to 0.11.13.

---

srcpkgs/qbittorrent/template

qbittorrent: update to 5.1.0

---

srcpkgs/hcloud/template

hcloud: update to 1.51.0.

---

srcpkgs/bc/template

- x86_64-musl
- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

bc: update to 1.08.2

---

srcpkgs/five-or-more/template

five-or-more: update to 48.1

---

srcpkgs/gnome-desktop/template

gnome-desktop: update to 44.3

---

srcpkgs/gnome-software/template

gnome-software: update to 48.2

---

srcpkgs/gnome-mines/template

gnome-mines: update to 48.1

---

srcpkgs/leveldb/template

- I built this PR locally for my native architecture, (x86_64-glibx)
- aarch64
- armv7l
- armv6l
- i686
Update version and checksum.

leveldb: update to 1.23.

---

srcpkgs/trivy/template

- aarch64-musl [crossbuild]
- armv7l [crossbuild]
- armv6l-musl [crossbuild]

New package: trivy-0.63.0

---

srcpkgs/topgrade/template

topgrade: update to 16.0.4

---

srcpkgs/lightsoff/template

lightsoff: update to 48.1

---

srcpkgs/orca/template

orca: update to 48.1

---

srcpkgs/shotwell/template

shotwell: update to 0.32.13

---

srcpkgs/totem/template

totem: update to 43.2

---

srcpkgs/tint/template

- aarch64-musl
- armv7l
- armv6l-musl

tint: update to 0.1.6

---

srcpkgs/jd/template

jd: update to 2.2.3.

---

srcpkgs/gdu/template

gdu: update to 5.31.0.

---

srcpkgs/go-md2man/template

go-md2man: update to 2.0.7

---

srcpkgs/halloy/template

halloy: update to 2025.6

---

srcpkgs/dust/template

dust: update to 1.2.1.

---

common/shlibs
srcpkgs/R-cran-nloptr/template
srcpkgs/libnest2d/template
srcpkgs/nlopt/template
srcpkgs/stellarium/template

And do the required revbumps
Also adopt the package
Only rebuilt the 3 revbumped packages
- None

nlopt: update to 2.10.0

---

srcpkgs/impala/template

- I built this PR locally for these architectures (all crossbuilds):
- aarch64-musl
- armv7l
- armv6l-musl

New package: impala-0.2.4

---

srcpkgs/android-studio/template

android-studio: update to 2024.3.2.15.

---

srcpkgs/chrony/template

From: cavnbinpkg <charles.based30284@tutanota.de>
- I tested the changes in this PR: **YES** (both of us did)
- I built this PR locally for my native architecture, (x86_64, x86_64-musl)

chrony: update to 4.7.

---

srcpkgs/m17n-lib/template

- I tested the changes in this PR: **NO** (I have no means to test this properly)
- x86_64-musl
- i686

m17n-lib: update to 1.8.6

---

srcpkgs/rosegarden/template

rosegraden: update to 25.06

---

srcpkgs/d2/template

d2: update to 0.7.0.

---

srcpkgs/gomuks/template

gomuks: update to 0.3.1.

---

srcpkgs/pysolfc-cardsets/template
srcpkgs/pysolfc/template

pysolfc: update to 3.4.0 / pysolfc-cardsets: update to 3.1

---

srcpkgs/discord/template

discord: update to 0.0.98

---

srcpkgs/vhs/template

vhs: update to 0.10.0

---

srcpkgs/dnscrypt-proxy/template

- I tested the changes in this PR:**briefly**

dnscrypt-proxy: update to 2.1.12

---

srcpkgs/cargo-update/template

cargo-update: update to 16.3.2

---

srcpkgs/gallery-dl/template

gallery-dl: update to 1.29.7.

---

srcpkgs/praat/template

praat: update to 6.4.35

---

srcpkgs/vale/template

vale: update to 3.11.2.

---

srcpkgs/Komikku/template

Komikku: update to 1.80.0.

---

srcpkgs/stopmotion/patches/nftw-musl.patch
srcpkgs/stopmotion/template

New package: stopmotion-0.9.0

---

srcpkgs/wayland-protocols/template

wayland-protocols: update to 1.45

---

srcpkgs/xinit/patches/06_move_serverauthfile_into_tmp.diff
srcpkgs/xinit/patches/fs25361.patch
srcpkgs/xinit/template

Refresh both patches as upstream renamed the target files.
Adopt the package.

xinit: update to 1.4.4.

---

srcpkgs/python3-uvicorn/template

python3-uvicorn: update to 0.34.2

---

srcpkgs/file/patches/0002-PR-571-jschleus-Some-zip-files-are-misclassified-as-data.patch
srcpkgs/file/template

file: add patch to fix zip misclassication

---

srcpkgs/clojure-lsp/template

clojure-lsp: update to 2025.06.06.

---

srcpkgs/clojure/template

clojure: update to 1.12.1.1550.

---

srcpkgs/gnome-nibbles/template

gnome-nibbles: update to 4.2.2

---

srcpkgs/ncmpc/template

- i686 (cross)
---
Cc: @ologantr

ncmpc: update to 0.52.

---

srcpkgs/mpd/template

mpd: update to 0.24.4.

---

srcpkgs/litecli/template
srcpkgs/pgcli/template
srcpkgs/python3-cli_helpers/template
srcpkgs/python3-pgspecial/template
srcpkgs/python3-psycopg/template
srcpkgs/python3-sqlparse/template

pgcli: update to 4.3.0. litecli: update to 1.15.0, adopt.

---

srcpkgs/kdenlive/template

I built this PR locally for my native architecture, x86-64-libc

kdenlive: update to 25.04.2.

---

srcpkgs/perl-CryptX/template

perl-CryptX: update to 0.087

---

srcpkgs/ast-grep/template

ast-grep: update to 0.38.5.

---

srcpkgs/eza/template

eza: update to 0.21.5

---

srcpkgs/git/template

git: update to 2.50.0.

---

srcpkgs/rio/patches/downgrade-rust-version.patch
srcpkgs/rio/template

rio: update to 0.2.20

---

srcpkgs/papers/template

papers: update to 48.4

---

srcpkgs/zk/template

- I built this PR locally for these architectures (cross builds):
- armv6l

zk: update to 0.15.1

---

srcpkgs/perl-Specio/template

perl-Specio: update to 0.51

---

srcpkgs/openhantek/template

New package: openhantek-3.4.0

---

srcpkgs/xcaddy/template

- aarch64-musl
- armv7l
- armv6l-musl

New package: xcaddy-0.4.4

---

srcpkgs/limine/template

limine: update to 9.3.4.

---

common/shlibs
srcpkgs/scenefx/template
srcpkgs/swayfx/template

swayfx: update to 0.5.1

---

srcpkgs/newsraft/template

newsraft: update to 0.31.

---

srcpkgs/rust-bacon/template

rust-bacon: update to 3.16.0.

---

srcpkgs/bc-gh/template

bc-gh: update to 7.0.3

---

srcpkgs/adwaita-icon-theme/template

adwaita-icon-theme: update to 48.1.

---

srcpkgs/nss/template

nss: update to 3.113.

---

srcpkgs/colord/template

- I built this PR locally for my native architecture, x86-64 (and i686)

colord: update to 1.4.7.

---

srcpkgs/spotify-player/template

spotify-player: update to 0.20.6

---

srcpkgs/Waybar/template

Waybar: update to 0.13.0.

---

srcpkgs/Waybar/template
srcpkgs/upower/template

upower: add missing polkit dependency to -devel

---

srcpkgs/pyradio/files/README.voidlinux
srcpkgs/pyradio/template

pyradio: update to 0.9.3.11.15.

---

srcpkgs/discord/template

discord: update to 0.0.99

---

srcpkgs/python3-nethsm/template

python3-nethsm: update to 1.4.1

---

srcpkgs/python3-click/template

python3-click: update to 8.2.1

---

srcpkgs/python3-tqdm/template

python3-tqdm: update to 4.67.1

---

srcpkgs/boxflat/template

boxflat: update to 1.32.1.

---

srcpkgs/ast-grep/template

- I built this PR locally for my native architecture: **x86_64 (libc)**

ast-grep: update to 0.38.6.

---

srcpkgs/eza/template

eza: update to 0.21.6

---

srcpkgs/ntpd-rs/patches/use-ring.patch
srcpkgs/ntpd-rs/template

ntpd-rs: update to 1.6.0

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.59.0.

---

srcpkgs/sxwm/template

sxwm: update to 1.6.

---

srcpkgs/act/template

act: update to 0.2.78

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2025.06.23.

---

srcpkgs/dkms/template

- I tested the changes in this PR: **pending**

dkms: update to 3.2.1.

---

srcpkgs/difftastic/template

difftastic: update to 0.64.0.

---

srcpkgs/darktable/patches/ec6b2d2194963f5f17df136b490b6d21c34cc503.patch
srcpkgs/darktable/template

darktable: update to 5.2.0.

---

srcpkgs/discord/template

discord: update to 0.0.100

---

srcpkgs/lua-language-server/template

lua-language-server: update to 3.15.0.

---

common/shlibs
srcpkgs/CPU-X/template
srcpkgs/igt-gpu-tools/patches/libproc.patch
srcpkgs/igt-gpu-tools/patches/musl.patch
srcpkgs/igt-gpu-tools/template
srcpkgs/lxqt-session/template
srcpkgs/procps-ng/patches/0001-fix-breakage-in-unhex.patch
srcpkgs/procps-ng/template
srcpkgs/xpra/template

procps-ng: update to 4.0.5.

---

srcpkgs/lcms2/template

lcms2: update to 2.17.

---

srcpkgs/libcap/template

libcap: update to 2.76.

---

srcpkgs/snappy/template

snappy: update to 1.2.2.

---

srcpkgs/qarma/template

qarma: update to 1.0.0

---

srcpkgs/swayimg/template

- I  built this PR locally for my native architecture, (x86_64-glibc)

swayimg: update to 4.3.

---

srcpkgs/swayfx/template

- I tested the changes in this PR:  **briefly**
I built this PR locally for my native architecture, (x86_64)

swayfx: update to 0.5.3.

---

srcpkgs/font-sarasa-gothic/template

font-sarasa-gothic: update to 1.0.31.

---

srcpkgs/opera/template

@mobinmob could you please review the changes

opera: update to 119.0.5497.88

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2025.06.30.

---

srcpkgs/gum/template

gum: update to 0.16.2

---

srcpkgs/moar/template

- x86_64-musl
@DiegoMagdaleno could you please review the changes??

moar: update to 1.32.2

---

srcpkgs/jq/template

jq: update to 1.8.1

---

srcpkgs/unrar/template

unrar: update to 7.1.8, enable all archs

---

srcpkgs/less/template

less: update to 678

---

srcpkgs/eza/template

eza: update to 0.22.0

---

srcpkgs/font-iosevka/template

font-iosevka: update to 33.2.6.

---

srcpkgs/vice/template

vice: update to 3.9.

---

srcpkgs/android-studio/template

android-studio: update to 2025.1.1.13.

---

srcpkgs/gopls/template

gopls: update to 0.19.1.

---

srcpkgs/praat/template

praat: update to 6.4.38

---

srcpkgs/exempi/template

exempi: update to 2.6.6.

---

srcpkgs/git-extras/template

git-extras: update to 7.4.0.

---

srcpkgs/pex/template

pex: update to 2.42.0.

---

srcpkgs/fx/template

fx: update to 37.0.0.

---

srcpkgs/bleachbit/template

- x86_64-musl
- i686 (cross)
@graysky2 could you please review the changes??

bleachbit: update to 5.0.0, orphan

---

srcpkgs/Dwarf-Therapist/template
srcpkgs/dwarffortress/template

dwarffortress: update to 51.13; Dwarf-Therapist: update to 42.1.15.

---

srcpkgs/rsgain/template

@MIvanchev @cinerea0 
i see this had prs a few times over the years. could you test this with ffmpeg6?

rsgain: use ffmpeg6

---

srcpkgs/manuskript/template

- I built this PR locally for my native architecture, (amd64-glibc)

manuskript: update to 0.17.0

---

srcpkgs/Marker/patches/gcc14.patch
srcpkgs/Marker/template

https://github.com/void-linux/void-packages/issues/56033

Marker: patch gcc14 incompat

---

srcpkgs/libgnt/patches/fix-ncurses6.5.patch
srcpkgs/libgnt/template

No revbump, just patch for future builds
https://github.com/void-linux/void-packages/pull/56052

libgnt: patch build ncurses 6.5

---

srcpkgs/Minder/template

https://github.com/void-linux/void-packages/pull/56052

Minder: update to 1.17.0

---

srcpkgs/desktop-file-utils/template

desktop-file-utils: update to 0.28.

---

srcpkgs/python3-poetry-core/template

- aarch64-musl
- armv7l
- armv6l-musl

python3-poetry-core: update to 2.1.3.

---

srcpkgs/cagebreak/template

cagebreak: update to 3.0.0.

---

srcpkgs/libarchive/template

libarchive: update to 3.8.1

---

srcpkgs/opera/template

@mobinmob could you review the changes

opera: update to 120.0.5543.38

---

srcpkgs/devedeng/template

devedeng: update to 4.21.0.

---

srcpkgs/direnv/template

direnv: update to 2.37.0.

---

srcpkgs/ruff/template

ruff: update to 0.12.2.

---

srcpkgs/mise/template

mise: update to 2025.7.1.

---

srcpkgs/s/template

s: update to 0.7.3.

---

srcpkgs/lapce/template

lapce: update to 0.4.3

---

srcpkgs/7zip/template

7zip: update to 25.00.

---

srcpkgs/Komikku/template

Komikku: update to 1.81.0.

---

srcpkgs/glslang/template
srcpkgs/shaderc/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

glslang: update to 15.4.0; shaderc: update to 2025.3.

---

srcpkgs/picmi/template

picmi: update to 25.04.3

---

srcpkgs/kmahjongg/template
srcpkgs/libkmahjongg/template

kmahjongg: update to 25.04.3

---

srcpkgs/asm-lsp/template

- I built this PR locally for my native architecture, (X86_GLIBC)

New package: asm-lsp-0.10.0

---

srcpkgs/bovo/template

bovo: update to 25.04.3

---

srcpkgs/jaq/template

jaq: update to 2.3.0

---

srcpkgs/discord/template

fixed escape to clear chat -_-

discord: update to 0.0.101

---

srcpkgs/sheldon/template

sheldon: update to 0.8.4

---

srcpkgs/typos/template

typos: update to 1.34.0.

---

srcpkgs/pciutils/template

pciutils: update to 3.14.0.

---

srcpkgs/carapace/template

carapace: update to 1.3.3.

---

srcpkgs/UxPlay/template

UxPlay: update to 1.72.2.

---

srcpkgs/qsv/template

This one fails a couple test locally but I think it's fine.

qsv: update to 5.1.0.

---

srcpkgs/conduit/template

conduit: update to 0.10.6.

---

srcpkgs/dust/template

dust: update to 1.2.2.

---

srcpkgs/OpenRCT2/template

OpenRCT2: update to 0.4.24.

---

srcpkgs/kdenlive/template

I built this PR locally for my native architecture, x86-64-libc

kdenlive: update to 25.04.3.

---

srcpkgs/swayimg/template

swayimg: update to 4.5.

---

srcpkgs/bibiman/template

- I built this PR locally for my native architecture, (x64_86 glibc)

bibiman: update to 0.13.1

---

srcpkgs/perl-CGI/template

perl-CGI: update to 4.70

---

srcpkgs/editorconfig/template

- I built this PR locally for these architectures (if supported. mark crossbuilds): X

editorconfig: update to 0.12.9.

---

srcpkgs/plattenalbum/template

plattenalbum: update to 2.3.1.

---

srcpkgs/python3-ocrmypdf/patches/use_pillow_heif_instead_of_pi_heif.patch
srcpkgs/python3-ocrmypdf/template

python3-ocrmypdf: update to 16.10.4

---

srcpkgs/qgit/template

qgit: update to 2.11

---

srcpkgs/gtk-layer-shell/template

[Changelog](https://github.com/wmww/gtk-layer-shell/releases)
cc @travankor

gtk-layer-shell: update to 0.9.2

---

srcpkgs/shfmt/template

shfmt: update to 3.12.0.

---

srcpkgs/imsprog/template

imsprog: update to 1.6.2

---

srcpkgs/mpc-qt/template

mpc-qt: update to 25.07

---

srcpkgs/rage/template

rage: add docs, completions, rage-mount utility

---

srcpkgs/Komikku/template

Komikku: update to 1.82.0.

---

srcpkgs/amsynth/template

amsynth: update to 1.13.4

---

srcpkgs/vibe/template

new vibe package

---

srcpkgs/calibre/template

calibre: update to 8.6.0.

---

srcpkgs/python3-pynitrokey/template

Full changelog: https://github.com/Nitrokey/pynitrokey/compare/v0.9.0...v0.9.2

python3-pynitrokey: update to 0.9.2

---

srcpkgs/usql/template

usql: update to 0.19.24.

---

srcpkgs/ntfy/template

ntfy: update to 2.13.0.

---

srcpkgs/fprintd/template
srcpkgs/libfprint/template

fprintd: update to 1.94.5, libfprint: update to 1.94.9

---

srcpkgs/walker/template

walker: update to 0.12.33.

---

srcpkgs/seer/template

seer: update to 2.5

---

srcpkgs/clojure-lsp/template

clojure-lsp: update to 2025.06.13.

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2025.07.14.

---

srcpkgs/slack-desktop/template

slack-desktop: update to 4.45.60.

---

srcpkgs/fx/template

fx: update to 37.0.1.

---

srcpkgs/k9s/template

k9s: update to 0.50.9.

---

srcpkgs/ruff/template

ruff: update to 0.12.3.

---

srcpkgs/papirus-folders/template

papirus-folders: update to 1.14.0

---

srcpkgs/libosinfo/template

libosinfo: update to 1.12.0

---

srcpkgs/atuin/template

- I built this PR locally for my native architecture, x86-64_GLIBC

atuin: update to 18.7.1

---

srcpkgs/virtualbox-ose/template

virtualbox-ose: update to 7.1.12.

---

srcpkgs/fnott/template

fnott: update to 1.8.0.

---

srcpkgs/limine/template

limine: update to 9.5.0.

---

srcpkgs/python3-nitrokey/template
srcpkgs/python3-pynitrokey/template

The new release of pynitrokey ships with one minor bugfix. More info can be obtained at  https://github.com/Nitrokey/pynitrokey/compare/v0.9.2...v0.9.3
I also included an update of py3-nitrokey in this PR as these packages are mutually dependent.

python3-pynitrokey: update to 0.9.3, python3-nitrokey: update to 0.3.2

---

srcpkgs/fend/template

fend: update to 1.5.7

---

srcpkgs/ntpd-rs/template

ntpd-rs: update to 1.6.1

---

srcpkgs/libopenmpt/template

libopenmpt: update to 0.8.1

---

srcpkgs/checkbashisms/template

- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

checkbashisms: update to 2.25.16

---

srcpkgs/python3-numpy/template
srcpkgs/python3-scipy/patches/test-32bit.patch
srcpkgs/python3-scipy/template

@tornaria, please confirm that these don't cause any issues for `sagemath`.

python3-{numpy,scipy}: update

---

srcpkgs/yelp-xsl/template
srcpkgs/yelp/template

yelp: update to 42.3, yelp-xsl: update to 42.4

---

srcpkgs/typstyle/template

typstyle: update to 0.13.16.

---

srcpkgs/libversion/template

libversion: update to 3.0.3

---

srcpkgs/ast-grep/template

ast-grep: update to 0.39.1.

---

srcpkgs/libwebp/template

libwebp: update to 1.6.0

---

srcpkgs/darkhttpd/template

darkhttpd: update to 1.17.

---

common/shlibs
srcpkgs/Clight/template
srcpkgs/activate-linux/template
srcpkgs/ahoviewer/template
srcpkgs/libconfig/template
srcpkgs/libffado/template
srcpkgs/lms/template
srcpkgs/logiops/template
srcpkgs/nwipe/template
srcpkgs/picom/template
srcpkgs/pinentry-dmenu/template
srcpkgs/srain/template
srcpkgs/sslh/template
srcpkgs/toxcore/template
srcpkgs/toxic/template
srcpkgs/umurmur/template
srcpkgs/xob/template
srcpkgs/yabar/template

libconfig: update to 1.8.1.

---

srcpkgs/anubis/template

- aarch64-musl
cross compiled from x86\_64-glibc to aarch64-musl and tested on
aarch64-musl.

anubis: update to 1.21.3.

---

srcpkgs/ngtcp2/template

ngtcp2: update to 1.14.0

---

srcpkgs/yq-go/template

yq-go: update to 4.47.1, adopt.

---

srcpkgs/carapace/template

carapace: update to 1.4.1.

---

srcpkgs/xbps-static/template
srcpkgs/xbps/template

xbps: use raw changelog

---

srcpkgs/rofimoji/template

rofimoji: update to 6.6.0

---

srcpkgs/foot/template

foot: update to 1.23.1.

---

srcpkgs/walker/template

walker: update to 0.13.11.

---

srcpkgs/duckdb/patches/fix-pythonpkg-build.patch
srcpkgs/duckdb/template

duckdb: update to 1.3.2.

---

srcpkgs/python3-humanize/template

python3-humanize: update to 4.12.3.

---

srcpkgs/fonttools/template

fonttools: update to 4.59.0.

---

srcpkgs/Ice/template

Ice: update to 3.7.10

---

srcpkgs/clyrics/template

clyrics: update to 0.17

---

srcpkgs/cloog/template

cloog: update to 0.21.1

---

srcpkgs/thermald/template

thermald: added missing dbus depedency

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.63.0.

---

srcpkgs/at-spi2-core/template

at-spi2-core: update to 2.56.3

---

srcpkgs/lms/template

lms: update to 3.68.1.

---

srcpkgs/gi-docgen/template

gi-docgen: update to 2025.4

---

srcpkgs/libdex/template

libdex: update to 0.11.0

---

srcpkgs/orca/template

orca: update to 48.6

---

srcpkgs/nautilus/template

nautilus: update to 48.3

---

srcpkgs/papers/template

papers: update to 48.5

---

srcpkgs/libtickit/template

libtickit: update to 0.4.5

---

srcpkgs/irust/files/README.voidlinux
srcpkgs/irust/template

<!--
- aarch64-musl
- armv7l
- armv6l-musl
--!>

 New package: irust-1.74.0 

---

srcpkgs/newsboat/template

newsboat: update to 2.40

---

srcpkgs/mutter/template

mutter: update to 48.4

---

srcpkgs/grilo-plugins/template
srcpkgs/grilo/template

grilo: update to 0.3.19, grilo-plugins: update to 0.3.18

---

srcpkgs/vte3/template

vte3: update to 0.80.3

---

srcpkgs/ghex/template

ghex: update to 46.3

---

srcpkgs/epiphany/template

epiphany: update to 48.5

---

srcpkgs/gnome-shell-extensions/template
srcpkgs/gnome-shell/template

gnome-shell{,-extensions}: update to 48.3

---

srcpkgs/gnome-online-accounts/template

gnome-online-accounts: update to 3.54.4

---

srcpkgs/libadwaita/template

libadwaita: update to 1.7.5

---

srcpkgs/crun/template

crun: update to 1.23.

---

srcpkgs/pistol/template

- aarch64-musl
- armv6l-musl
- armv6l
- armv7l-musl
- armv7l
- i686
This resolves #33312.

New package: pistol-0.5.2

---

srcpkgs/lidm/files/lidm/finish
srcpkgs/lidm/files/lidm/run
srcpkgs/lidm/template

- aarch64
- armv7l
- i686
- riscv64

New package: lidm-1.2.3

---

srcpkgs/checkbashisms/template

- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

checkbashisms: update to 2.25.17

---

srcpkgs/discord/template

discord: update to 0.0.103

---

srcpkgs/linux-asahi/files/arm64-dotconfig
srcpkgs/linux-asahi/template

linux-asahi: update to 6.15.8+1.

---

srcpkgs/cargo-update/template

cargo-update: update to 17.0.0

---

srcpkgs/hydroxide/template

hydroxide: update to 0.2.30.

---

srcpkgs/halloy/template

halloy: update to 2025.8

---

srcpkgs/inih/template

inih: update to 61

---

srcpkgs/qt5ct/template

- I built this PR locally for my native architecture,  (x86_64-glibc)

qt5ct: update to 1.9.

---

srcpkgs/libwpe/template

libwpe: update to 1.16.2

---

srcpkgs/memray/template
srcpkgs/python3-textual/template

python3-textual: update to 5.0.1; memray: update to 1.17.2.

---

srcpkgs/dust/template

dust: update to 1.2.3.

---

srcpkgs/hurl/template

hurl: update to 7.0.0.

---

srcpkgs/python3-SQLAlchemy2/template

python3-SQLAlchemy2: update to 2.0.42.

---

srcpkgs/atuin/template

atuin: update to 18.8.0

---

srcpkgs/zellij/template

zellij: update to 0.43.0

---

srcpkgs/fx/template

fx: update to 38.0.0.

---

srcpkgs/direnv/template

direnv: update to 2.37.1.

---

srcpkgs/impala/template

impala: update to 0.3.0

---

srcpkgs/Signal-Desktop/template

Signal-Desktop: update to 7.64.0.

---

srcpkgs/lf/template

lf: add changelog

---

srcpkgs/mpd/template

mpd: update to 0.24.5.

---

srcpkgs/cflow/template

cflow: update to 1.8

---

srcpkgs/droidcam/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

droidcam: update to 2.1.4.

---

srcpkgs/qView/template

qView: update to 7.1

---

srcpkgs/xtermcontrol/template

xtermcontrol: update to 3.10

---

srcpkgs/7zip/template

7zip: update to 25.01.

---

srcpkgs/sublime-merge/template

sublime-merge: update to 2110.

---

srcpkgs/SDL3/template

SDL3: update to 3.2.20

---

srcpkgs/walker/template

walker: update to 0.13.22.

---

srcpkgs/composer8.1/template

composer8.1: update to 2.8.10

---

srcpkgs/python3-mpd2/template

updating this for plattenalbum which requires a newer version (>=3.1.0) and since the maintainer hasn't responded

python3-mpd2: update to 3.1.1.

---

srcpkgs/discord/template

discord: update to 0.0.104

---

srcpkgs/gallery-dl/template

gallery-dl: update to 1.30.2.

---

srcpkgs/pueue/template

pueue: update to 4.0.1.

---

srcpkgs/python3-neovim/template

**Testing the changes**
**Local build testing**
- I built this PR locally for my native architecture: x86_64

python3-neovim: update to 0.5.2

---

srcpkgs/zellij/template

zellij: update to 0.43.1

---

srcpkgs/linux-mainline/template

linux-mainline: update to 6.16.

---

srcpkgs/Komikku/template

Komikku: update to 1.84.0.

---

srcpkgs/osv-scanner/template

osv-scanner: update to 2.2.0.

---

srcpkgs/rio/template

rio: update to 0.2.27

---

srcpkgs/icewm/template

icewm: update to 3.8.2.

---

srcpkgs/python3-isort/template

python3-isort: update to 6.0.1. adopt.

---

srcpkgs/font-cozette/template

- I built this PR locally for my native architecture, x86_64, glibc
- aarch64-musl
- armv7l
- armv6l-musl

font-cozette: update to 1.30.0

---

srcpkgs/streamlink/template

streamlink: update to 7.5.0.

---

srcpkgs/orage/template

orage: update to 4.20.2

---

srcpkgs/conduit/template

conduit: update to 0.10.8.

---

srcpkgs/ruff/template

ruff: update to 0.12.8.

---

srcpkgs/cargo-deny/template

cargo-deny: update to 0.18.3.

---

srcpkgs/ntfy/template

ntfy: update to 2.14.0.

---

srcpkgs/man-pages/template

man-pages: update to 6.15

---

srcpkgs/mnamer/patches/requests-cache.patch
srcpkgs/mnamer/template
srcpkgs/python3-requests-cache/template
srcpkgs/python3-teletype/template
srcpkgs/python3-url-normalize/template

New package: mnamer-2.5.5

---

srcpkgs/podman-compose/template

started an nginx server and checked that everything worked
Question: podman-compose provides an extensive testing-suite, should this be included in the template?

podman-compose: update to v1.5.0, adopt.

---

srcpkgs/python3-qtile-extras/template

python3-qtile-extras: update to 0.33.0.

---

srcpkgs/util-linux-common/template
srcpkgs/util-linux/template

util-linux: update to 2.41.1.

---

srcpkgs/font-sil-lateef/template

font-sil-lateef: update to 4.400

---

srcpkgs/strawberry/template

strawberry: update to 1.2.12.

---

srcpkgs/python3-xcffib/template

python3-xcffib: update to 1.9.0.

---

srcpkgs/freecad/template

fixes bad sketcher constraints

freecad: update to 1.0.2

---

srcpkgs/gifski/template

gifski: update to 1.34.0

---

srcpkgs/openrazer-meta/template

openrazer-meta: update to 3.10.3.

---

srcpkgs/Komikku/template

Komikku: update to 1.85.0.

---

srcpkgs/cargo-auditable-bootstrap/template
srcpkgs/cargo-auditable/template

cargo-auditable: update to 0.7.0

---

srcpkgs/limine/template

limine: update to 9.6.1.

---

srcpkgs/discord/template

- I built this PR locally for my native architecture, *x86_64**

discord: update to 0.0.105

---

srcpkgs/fuzzel/template

fuzzel: update to 1.13.1

---

srcpkgs/github-cli/template

github-cli: update to 2.78.0

---

srcpkgs/rebar3/template

rebar3: update to 3.25.1.

---

srcpkgs/clojure-lsp/template
srcpkgs/mandrel/template

mandrel: update to 23.1.8.0; clojure-lsp: update to 2025.08.15.

---

srcpkgs/grml-zsh-config/template

- aarch64-musl
- armv7l
- armv6l-musl

grml-zsh-config: update to 0.19.24.

---

srcpkgs/wtfutil/template

wtfutil: update to 0.46.0, orphan.

---

srcpkgs/clojure-lsp/template

clojure-lsp: update to 2025.08.25.

---

srcpkgs/ruff/template

ruff: update to 0.12.10.

---

srcpkgs/checkbashisms/template

- aarch64-musl
- aarch64
- i686
- armv7l-musl
- armv7l
- armv6l-musl
- armv6l

checkbashisms: update to 2.25.19

---

srcpkgs/SuiteSparse/template

SuiteSparse: update to 7.11.0.

---

srcpkgs/gowall/template

- aarch64-musl
- armv7l
- armv6l-musl

New package: gowall-0.2.1

---

srcpkgs/aerc/template

aerc: update to 0.21.0.

---

srcpkgs/LGOGDownloader/template

LGOGDownloader: update to 3.17

---

srcpkgs/usql/template

usql: update to 0.19.25.

---

srcpkgs/ov/template

ov: update to 0.43.0.

---

srcpkgs/typstyle/template

typstyle: update to 0.13.17.

---

srcpkgs/autoconf/patches/largefile.patch
srcpkgs/autoconf/template

autoconf: update to 2.72.

---

srcpkgs/eza/template

eza: update 0.23.1

---

srcpkgs/neovim/template

neovim: update to 0.11.4

---

srcpkgs/libgnome-games-support2/template

libgnome-games-support2: update to 2.0.2

---

srcpkgs/hyperrogue/template

hyperrogue: update to 13.1d

---

srcpkgs/discord/template

discord: update to 0.0.108

---

srcpkgs/spectrwm/template

spectrwm: update to 3.7.0.

---

srcpkgs/icewm/template

icewm: update to 3.9.0.

---

srcpkgs/eza/template

eza: update to 0.23.2

---

srcpkgs/rofimoji/template

rofimoji: update to 6.7.0

---

srcpkgs/github-cli/template

github-cli: update to 2.79.0

---

srcpkgs/discord/template

discord: update to 0.0.109

---

common/shlibs
srcpkgs/libcbor/template
srcpkgs/libfido2/template
srcpkgs/qemu-user/template
srcpkgs/qemu/template

libcbor: update to 0.13.0 + qemu: update to 10.1.0.

---

srcpkgs/python3-neovim/template

- I built this PR locally for my native architecture: x86_64

python3-neovim: update to 0.6.0

---

srcpkgs/tailspin/template

\#### Testing the changes  
\- I tested the changes in this PR: \*\*briefly\*\*
\#### Local build testing  
\- I built this PR locally for my native architecture, (x64 glibc)

tailspin: update to 5.5.0

---

srcpkgs/havoc/template

havoc: update to 0.7.0.

---

srcpkgs/synapse/template

synapse: update to 1.138.0.

---

srcpkgs/dufs/template

dufs: update to 0.45.0

---

srcpkgs/memray/template
srcpkgs/python3-textual/template

python3-textual: update to 5.3.0; memray: update to 1.18.0.

---

srcpkgs/lychee/template

lychee: update to 0.20.1.

---

srcpkgs/limine/template

limine: update to 9.6.7.

---

srcpkgs/d2/template

d2: update to 0.7.1.

---

srcpkgs/wine/template

wine: update to 10.15

---

srcpkgs/eza/template

eza: update to 0.23.3

---

srcpkgs/mercurial/template

mercurial: update to 7.1.1.

---

srcpkgs/dialog/template

dialog: update to 1.3.20250817.

---

srcpkgs/codeberg-cli/template

codeberg-cli: update to 0.5.0

---

srcpkgs/rust-analyzer/template

rust-analyzer: update to 2025.08.25.

---

srcpkgs/konversation/template

konversation: update to 25.08.1.

---

srcpkgs/discord/template

discord: update to 0.0.110

---

srcpkgs/tigervnc/template

Adds about 15 MB in ffmpeg library dependencies.

tigervnc: add H.264 encoding support

---

srcpkgs/jpegoptim/template

jpegoptim: update to 1.5.6.

---

srcpkgs/nushell/template

nushell: update to 0.107.0

---

srcpkgs/xarchiver/template

xarchiver: update to 0.5.4.26.

---

srcpkgs/xh/template

xh: update to 0.25.0

---

srcpkgs/fish-shell/template

fish-shell: update to 4.0.8

---

srcpkgs/xwayland-satellite/template

xwayland-satellite: update to 0.7.

---

srcpkgs/iputils/template

[Changelog](https://raw.githubusercontent.com/iputils/iputils/master/CHANGES)
cc @Gottox

iputils: update to 20250605

---

srcpkgs/heaptrack/patches/boost-1.89.patch
srcpkgs/heaptrack/patches/kf6.patch
srcpkgs/heaptrack/template

heaptrack: switch to Qt6

---

srcpkgs/pipewire/template

- x86_64-musl
- i686
- aarch64
- aarch64-musl
- armv7l
- armv7l-musl
- armv6l
- armv6l-musl

pipewire: update to 1.4.8.

---

srcpkgs/at-spi2-core/template

at-spi2-core: update to 2.56.5

---

srcpkgs/libtirpc/template

- I built this PR locally for these architectures: x86_64-musl

libtirpc: update to 1.3.7

---

srcpkgs/hcloud/template

hcloud: update to 1.52.0.

---

srcpkgs/wlroots0.19/template

wlroots0.19: update to 0.19.1

---

srcpkgs/thunar-media-tags-plugin/template

thunar-media-tags-plugin: update to 0.6.0

---

srcpkgs/xfce4-wavelan-plugin/template

xfce4-wavelan-plugin: update to 0.7.0

---

srcpkgs/xfce4-mailwatch-plugin/template

xfce4-mailwatch-plugin: update to 0.7.0

---

srcpkgs/thunar-archive-plugin/template

thunar-archive-plugin: update to 0.6.0

---

srcpkgs/hyperrogue/template

hyperrogue: update to 13.1e

---

srcpkgs/LanguageTool/files/languagetool.properties
srcpkgs/LanguageTool/files/languagetool/run
srcpkgs/LanguageTool/template
srcpkgs/fasttext-devel
srcpkgs/fasttext-lid/template
srcpkgs/fasttext/patches/cmake.patch
srcpkgs/fasttext/patches/includes.patch
srcpkgs/fasttext/template

- **LanguageTool: update to 6.6.**
- **New package: fasttext-0.9.2**
- **New package: fasttext-lid-0.9.2**

LanguageTool: update to 6.6.

---

srcpkgs/just/template

- I built this PR locally for these architectures :

just: update to 1.43.0

---

srcpkgs/just/template

just: install provided completion scripts

---

srcpkgs/hicolor-icon-theme/template

hicolor-icon-theme: update to 0.18

---

srcpkgs/tinyramfs-uefi
srcpkgs/tinyramfs/files/kernel-uefi-hook-postinst
srcpkgs/tinyramfs/files/kernel-uefi-hook-postrm
srcpkgs/tinyramfs/template

tinyramfs: update to 0.3, split uefi bundle pkg.

---

srcpkgs/github-cli/template

github-cli: update to 2.81.0

---

srcpkgs/opentofu/template

opentofu: update to 1.10.6.

---

srcpkgs/alertmanager/template

alertmanager: update to 0.28.1.

---

srcpkgs/kubernetes-helm/template

kubernetes-helm: update to 3.19.0.

---

srcpkgs/kubernetes-kind/template

kubernetes-kind: update to 0.30.0.

---

srcpkgs/fluidsynth/template

fluidsynth: update to 2.4.8

---

srcpkgs/qsynth/template

qsynth: update to 1.0.3

---

srcpkgs/perl-XS-Parse-Keyword/template

- I built this PR locally for my native architecture, (x86_84)
- x86_64-musl
- i686

perl-XS-Parse-Keyword: upate to 0.49

---

srcpkgs/perl-Syntax-Keyword-Try/template

- I built this PR locally for my native architecture, (x86_84)
- x86_64-musl
- i686

perl-Syntax-Keyword-Try: update to 0.31

---

srcpkgs/ufw-extras/template

ufw-extras: update to 1.1.0

---

srcpkgs/blindfold/template

blindfold: update to 1.2.0.

---

srcpkgs/passt/template

passt: update to 2025.09.19.623dbf6.

---

srcpkgs/pnpm/template

pnpm: update to 10.17.1.

---

srcpkgs/ROCm-SMI/template

ping maintainer @Calandracas606

ROCm-SMI: Update to 7.0.1

---

srcpkgs/hwids/template

hwids: update to 0.399

---

srcpkgs/restic/template

restic: update to 0.18.1.

---

srcpkgs/boxflat/template

boxflat: update to 1.34.4.

---

srcpkgs/exiftool/template
srcpkgs/exiftool/update

exiftool: update to 13.36

---

srcpkgs/qpdf/template
srcpkgs/qpdf/update

qpdf: update to 12.2.0

---

srcpkgs/smplayer/template

smplayer: update to 25.6.0

---

srcpkgs/kdenlive/template

- I built this PR locally for my native architecture x86_64-glibc
- armv6l

kdenlive: update to 25.08.1.

---

srcpkgs/horizon/template

horizon: update to 2.7.1.

---

srcpkgs/rbenv/template

rbenv: update to 1.3.2

---

srcpkgs/ruby-build/template

ruby-build: update to 20250916.1

---

srcpkgs/pistol/template

pistol: update to 0.5.3

---

srcpkgs/xfburn/template

xfburn: update to 0.8.0

---

srcpkgs/dolphin-emu/patches/musl-cstdint.patch
srcpkgs/dolphin-emu/template

dolphin-emu: update to 2509

---

srcpkgs/prometheus/template

prometheus: update to 3.6.0.

---

srcpkgs/python3-ocrmypdf/template

python3-ocrmypdf: update to 16.11.0

---

srcpkgs/frp/template

frp: update to 0.65.0.

---

srcpkgs/media-downloader/template

media-downloader: update to 5.4.2

---

srcpkgs/carapace/template

- x86_64-musl
<br/>
@icp1994 could you please review the changes

carapace: update to 1.5.0

---

srcpkgs/opera/template

<br/>
@mobinmob could you please review the changes

opera: update to 122.0.5643.92

---

srcpkgs/chromium-qt6
srcpkgs/chromium/patches/chromium-141-cross-toolchain.patch
srcpkgs/chromium/patches/chromium-141-cssstylesheet-iwyu.patch
srcpkgs/chromium/patches/chromium-141-fc-cache-version.patch
srcpkgs/chromium/template

chromium: update to 141.0.7390.54.

---

srcpkgs/eza/template

eza: update to 0.23.4

---

srcpkgs/cmake-bootstrap/template
srcpkgs/cmake/patches/ignore-crape-compiler-test.patch
srcpkgs/cmake/patches/musl-test.patch
srcpkgs/cmake/patches/no-license.patch
srcpkgs/cmake/patches/not-found.patch
srcpkgs/cmake/template

CMake 4.1.2

---

srcpkgs/glow/template

glow: update to 2.1.1.

---

srcpkgs/snooze/template

snooze: add changelog

---

srcpkgs/carapace/template

carapace: update to 1.5.1.

---

srcpkgs/clojure/template

clojure: update to 1.12.3.1577.

---

srcpkgs/iwd/template

- briefly tested `impala` tui, as well
[Changelog](https://git.kernel.org/pub/scm/network/wireless/iwd.git/plain/ChangeLog)
cc @ericonr

iwd: update to 3.10

---

srcpkgs/kwin-effects-forceblur/template

kwin-effects-forceblur: revbump for kwin update

---

srcpkgs/nudoku/template

nudoku: update to 6.0.0

---

srcpkgs/black/template
srcpkgs/python3-pytokens/template

black: update to 25.9.0.

---

srcpkgs/kbreakout/template

New package: kbreakout-25.08.1

---

srcpkgs/newsraft/template

newsraft: update to 0.34.

---

srcpkgs/ruff/template

ruff: update to 0.13.3.

---

srcpkgs/StyLua/template

StyLua: update to 2.3.0.

---

srcpkgs/uv/template

uv: update to 0.9.0.
